In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('karachi_properties.csv')

In [4]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type
0,"Brand New, West Open","saadi town - block 7, saadi town",scheme 33,22800000.0,1080.0,4,5,1.0,NaN,2.0,3.0,0,1,1,1,2025.0,house
1,Double Storey House Available For Sale,"north nazimabad - block b, north nazimabad",north nazimabad,100000000.0,4500.0,5,5,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house
2,166 Square Yard Flat For Sale In North Nazimab...,"north nazimabad - block f, north nazimabad",north nazimabad,25500000.0,1494.0,3,3,0.0,NaN,12.0,0.0,2,0,1,0,NaN,flat
3,Flat Available For Sale,"pechs block 2, pechs",jamshed town,65000000.0,2403.0,4,4,2.0,NaN,NaN,2.0,0,0,1,0,NaN,flat
4,North Vista 2 Bed D D Flat For Sale,"north nazimabad - block b, north nazimabad",north nazimabad,16500000.0,954.0,2,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat

In [5]:
price_per_sqft = (df['price'] / df['area']).round(2)

In [6]:
df.insert(4, 'price_per_sqft', price_per_sqft.round(2))

In [7]:
df['location'].value_counts()

location
dha defence                                        4415
scheme 33                                          2500
gulshan-e-iqbal town                               2156
gulistan-e-jauhar                                  1822
bahria town karachi                                1757
cantt                                              1424
north nazimabad                                    1075
malir                                               867
gadap town                                          838
naya nazimabad                                      809
clifton                                             627
jamshed town                                        461
north karachi                                       408
federal b area                                      405
university road                                     345
jinnah avenue                                       247
shaheed millat road                                 178
korangi                                             167
navy housing scheme karsaz                          131
bath island                                         128
khalid bin walid road                               124
karachi motorway                                     87
kda scheme 1                                         87
civil lines                                          86
rashid minhas road                                   83
shah faisal town                                     83
malir link to super highway                          79
nazimabad                                            74
dha city karachi                                     58
bin qasim town                                       57
jamshed road                                         57
saadi road                                           57
saddar town                                          53
defence view society                                 47
suparco road                                         46
shahra-e-faisal                                      46
frere town                                           43
chapal courtyard                                     39
tariq road                                           39
sea view apartments                                  39
airport road                                         37
falaknaz harmony                                     37
amir khusro                                          36
kn gohar green city                                  35
saima luxury homes                                   32
tipu sultan road                                     32
northern bypass                                      31
amil colony                                          29
hill park                                            27
dalmia cement factory road                           27
falaknaz dynasty                                     27
cotton export cooperative housing society            23
garden west                                          20
abul hassan isphani road                             18
cosmopolitan society                                 17
qayyumabad                                           16
chapal uptown                                        16
shahra-e-qaideen                                     14
falcon complex faisal                                14
zamzama                                              14
shaheed-e-millat expressway                          12
gulshan-e-usman housing society                      12
muslimabad society                                   12
mehmoodabad                                          11
karachi - hyderabad motorway                         11
super highway                                        11
gizri                                                11
gulberg town                                         11
yousaf goth                                          11
kda scheme 1 extension                               11
p & t colony                                         10
shahrah-e-pakistan                                   10
new karachi                                          10
darul aman society                                    9
naval colony                                          9
airport                                               8
al-hilal society                                      8
pak ideal cooperative housing society                 8
orangi town                                           7
liaquatabad                                           7
oasis park residencia                                 6
rufi lake drive apartments                            6
chapal skymark                                        6
sindh industrial trading estate (site)                6
metrovil colony                                       6
siraj-ud-daula road                                   5
national highway                                      5
delhi colony                                          5
punjab colony                                         5
i. i. chundrigar road                                 5
app employees co-operative housing society            5
kamran chowrangi                                      5
liaquat avenue                                        4
khayaban-e-ittehad road                               4
pib colony                                            4
shahra-e-usman                                        4
manzoor colony                                        4
kemari town                                           4
kashmir colony                                        4
scheme 45                                             3
m. a. jinnah road                                     2
rufi rose petals                                      2
ranchore line bazar                                   2
guru mandir chorangi                                  2
kashmir road                                          2
punjab chowrangi                                      2
baldia town                                           2
abid town                                             2
mt khan road                                          2
gadap road                                            2
muhammad bin qasim co-operative housing society       2
baloch colony                                         2
royal defence tower                                   1
jamaluddin afghani road                               1
allama iqbal town                                     1
mangopir                                              1
old ravians co-operative housing society              1
sakhi hassan chowrangi                                1
gulistan-e-malir                                      1
maskan chowrangi                                      1
stadium road                                          1
gulshan-e-umair                                       1
dr daud pota road                                     1
surti muslim co-operative housing society             1
maqboolabad society                                   1
landhi                                                1
numaish chowrangi                                     1
dastgir colony                                        1
aisha manzil                                          1
police society                                        1
khokan cooperative housing society                    1
asf tower                                             1
rabia city                                            1
moria goth                                            1
cutchi memon cooperative housing society              1
Name: count, dtype: int64

In [ ]:
# mapping = {

#     # Locations grouped under DHA Defence.
#     "dha defence": "DHA Defence",
#     "royal defence tower": "DHA Defence",
#     "khayaban-e-ittehad road": "DHA Defence",
#     "zamzama": "DHA Defence",
#     "sea view apartments": "DHA Defence",
#     "defence view society": "DHA Defence",

#     "dha city karachi": "DHA City",

#     # Locations grouped under Clifton.
#     "clifton": "Clifton",
#     "frere town": "Clifton",
#     "gizri": "Clifton",
#     "bath island": "Clifton",
#     "delhi colony": "Clifton",
#     "punjab colony": "Clifton",
#     "punjab chowrangi": "Clifton",

#     # Locations grouped under Cantt.
#     "cantt": "Cantt",
#     "civil lines": "Cantt",
#     "p & t colony": "Cantt",
#     "dr daud pota road": "Cantt",

#     # Keep Navy Housing Scheme Karsaz as its own area.
#     "navy housing scheme karsaz": "Navy Housing Scheme Karsaz",

#     # Locations grouped under Scheme 33.
#     "scheme 33": "Scheme 33",
#     "saima luxury homes": "Scheme 33",
#     "falaknaz harmony": "Scheme 33",
#     "falaknaz dynasty": "Scheme 33",
#     "chapal courtyard": "Scheme 33",
#     "chapal uptown": "Scheme 33",
#     "kn gohar green city": "Scheme 33",
#     "suparco road": "Scheme 33",
#     "gulshan-e-usman housing society": "Scheme 33",
#     "yousaf goth": "Scheme 33",
#     "cotton export cooperative housing society": "Scheme 33",
#     "asf tower": "Scheme 33",
#     "oasis park residencia": "Scheme 33",
#     "cutchi memon cooperative housing society": "Scheme 33",
#     "muhammad bin qasim co-operative housing society": "Scheme 33",
#     "gulshan-e-umair": "Scheme 33",
#     "abid town": "Scheme 33",
#     "police society": "Scheme 33",
#     "old ravians co-operative housing society": "Scheme 33",
#     "scheme 45": "Scheme 33",

#     # Locations grouped under Gulshan-e-Iqbal.
#     "gulshan-e-iqbal town": "Gulshan-e-Iqbal",
#     "university road": "Gulshan-e-Iqbal",
#     "kda scheme 1": "Gulshan-e-Iqbal",
#     "kda scheme 1 extension": "Gulshan-e-Iqbal",
#     "rashid minhas road": "Gulshan-e-Iqbal",
#     "dalmia cement factory road": "Gulshan-e-Iqbal",
#     "abul hassan isphani road": "Gulshan-e-Iqbal",
#     "maskan chowrangi": "Gulshan-e-Iqbal",
#     "al-hilal society": "Gulshan-e-Iqbal",
#     "pak ideal cooperative housing society": "Gulshan-e-Iqbal",
#     "siraj-ud-daula road": "Gulshan-e-Iqbal",
#     "stadium road": "Gulshan-e-Iqbal",

#     # Locations grouped under Gulistan-e-Jauhar.
#     "gulistan-e-jauhar": "Gulistan-e-Jauhar",
#     "kamran chowrangi": "Gulistan-e-Jauhar",
#     "rabia city": "Gulistan-e-Jauhar",
#     "rufi lake drive apartments": "Gulistan-e-Jauhar",
#     "rufi rose petals": "Gulistan-e-Jauhar",

#     # Keep Bahria Town as a separate parent area.
#     "bahria town karachi": "Bahria Town",

#     # Locations grouped under Jamshed Town.
#     "jamshed town": "Jamshed Town",
#     "shaheed millat road": "Jamshed Town",
#     "khalid bin walid road": "Jamshed Town",
#     "jamshed road": "Jamshed Town",
#     "amir khusro": "Jamshed Town",
#     "amil colony": "Jamshed Town",
#     "cosmopolitan society": "Jamshed Town",
#     "shahra-e-qaideen": "Jamshed Town",
#     "shaheed-e-millat expressway": "Jamshed Town",
#     "muslimabad society": "Jamshed Town",
#     "maqboolabad society": "Jamshed Town",
#     "guru mandir chorangi": "Jamshed Town",
#     "jamaluddin afghani road": "Jamshed Town",
#     "numaish chowrangi": "Jamshed Town",
#     "pib colony": "Jamshed Town",
#     "mehmoodabad": "Jamshed Town",
#     "manzoor colony": "Jamshed Town",
#     "baloch colony": "Jamshed Town",
#     "tariq road": "Jamshed Town",
#     "hill park": "Jamshed Town",

#     # Locations grouped under North Nazimabad.
#     "north nazimabad": "North Nazimabad",
#     "sakhi hassan chowrangi": "North Nazimabad",
#     "buffer zone": "North Nazimabad",
#     "hyderi": "North Nazimabad",
#     "five star chowrangi": "North Nazimabad",
#     "shadman": "North Nazimabad",

#     # Locations grouped under Nazimabad.
#     "nazimabad": "Nazimabad",
#     "liaquatabad": "Nazimabad",

#     # Locations grouped under North Karachi.
#     "north karachi": "North Karachi",
#     "new karachi": "North Karachi",
#     "shahra-e-usman": "North Karachi",
#     "orangi town": "North Karachi",
#     "metrovil colony": "North Karachi",

#     # Locations grouped under Federal B Area.
#     "federal b area": "Federal B Area",
#     "aisha manzil": "Federal B Area",
#     "dastgir colony": "Federal B Area",
#     "shahrah-e-pakistan": "Federal B Area",
#     "gulberg town": "Federal B Area",

#     # Locations grouped under Malir.
#     "malir": "Malir",
#     "airport": "Malir",
#     "airport road": "Malir",
#     "malir link to super highway": "Malir",
#     "gulistan-e-malir": "Malir",
#     "liaquat avenue": "Malir",
#     "moria goth": "Malir",
#     "allama iqbal town": "Malir",
#     "khokan cooperative housing society": "Malir",

#     # Locations grouped under Gadap.
#     "gadap town": "Gadap",
#     "mangopir": "Gadap",

#     # Locations grouped along the Super Highway.
#     "super highway": "Super Highway",
#     "karachi motorway": "Super Highway",
#     "karachi - hyderabad motorway": "Super Highway",
#     "northern bypass": "Super Highway",
#     "gadap road": "Super Highway",
#     "national highway": "Super Highway",

#     # Keep Naya Nazimabad as its own area.
#     "naya nazimabad": "Naya Nazimabad",

#     # Locations grouped under Shah Faisal.
#     "shah faisal town": "Shah Faisal",
#     "falcon complex faisal": "Shah Faisal",

#     # Locations grouped under Korangi.
#     "korangi": "Korangi",
#     "qayyumabad": "Korangi",
#     "landhi": "Korangi",

#     # Locations grouped under Saddar.
#     "saddar town": "Saddar",
#     "chapal skymark": "Saddar",
#     "ranchore line bazar": "Saddar",
#     "m. a. jinnah road": "Saddar",
#     "i. i. chundrigar road": "Saddar",
#     "mt khan road": "Saddar",
#     "garden west": "Saddar",

#     # Locations grouped under SITE Area.
#     "sindh industrial trading estate (site)": "SITE Area",

#     # Locations grouped under Kemari.
#     "kemari town": "Kemari",
#     "baldia town": "Kemari",
#     "naval colony": "Kemari",
# }

In [9]:
df['location'].value_counts()

location
dha defence                                        4415
scheme 33                                          2500
gulshan-e-iqbal town                               2156
gulistan-e-jauhar                                  1822
bahria town karachi                                1757
cantt                                              1424
north nazimabad                                    1075
malir                                               867
gadap town                                          838
naya nazimabad                                      809
clifton                                             627
jamshed town                                        461
north karachi                                       408
federal b area                                      405
university road                                     345
jinnah avenue                                       247
shaheed millat road                                 178
korangi                                             167
navy housing scheme karsaz                          131
bath island                                         128
khalid bin walid road                               124
karachi motorway                                     87
kda scheme 1                                         87
civil lines                                          86
rashid minhas road                                   83
shah faisal town                                     83
malir link to super highway                          79
nazimabad                                            74
dha city karachi                                     58
bin qasim town                                       57
jamshed road                                         57
saadi road                                           57
saddar town                                          53
defence view society                                 47
suparco road                                         46
shahra-e-faisal                                      46
frere town                                           43
chapal courtyard                                     39
tariq road                                           39
sea view apartments                                  39
airport road                                         37
falaknaz harmony                                     37
amir khusro                                          36
kn gohar green city                                  35
saima luxury homes                                   32
tipu sultan road                                     32
northern bypass                                      31
amil colony                                          29
hill park                                            27
dalmia cement factory road                           27
falaknaz dynasty                                     27
cotton export cooperative housing society            23
garden west                                          20
abul hassan isphani road                             18
cosmopolitan society                                 17
qayyumabad                                           16
chapal uptown                                        16
shahra-e-qaideen                                     14
falcon complex faisal                                14
zamzama                                              14
shaheed-e-millat expressway                          12
gulshan-e-usman housing society                      12
muslimabad society                                   12
mehmoodabad                                          11
karachi - hyderabad motorway                         11
super highway                                        11
gizri                                                11
gulberg town                                         11
yousaf goth                                          11
kda scheme 1 extension                               11
p & t colony                                         10
shahrah-e-pakistan                                   10
new karachi                                          10
darul aman society                                    9
naval colony                                          9
airport                                               8
al-hilal society                                      8
pak ideal cooperative housing society                 8
orangi town                                           7
liaquatabad                                           7
oasis park residencia                                 6
rufi lake drive apartments                            6
chapal skymark                                        6
sindh industrial trading estate (site)                6
metrovil colony                                       6
siraj-ud-daula road                                   5
national highway                                      5
delhi colony                                          5
punjab colony                                         5
i. i. chundrigar road                                 5
app employees co-operative housing society            5
kamran chowrangi                                      5
liaquat avenue                                        4
khayaban-e-ittehad road                               4
pib colony                                            4
shahra-e-usman                                        4
manzoor colony                                        4
kemari town                                           4
kashmir colony                                        4
scheme 45                                             3
m. a. jinnah road                                     2
rufi rose petals                                      2
ranchore line bazar                                   2
guru mandir chorangi                                  2
kashmir road                                          2
punjab chowrangi                                      2
baldia town                                           2
abid town                                             2
mt khan road                                          2
gadap road                                            2
muhammad bin qasim co-operative housing society       2
baloch colony                                         2
royal defence tower                                   1
jamaluddin afghani road                               1
allama iqbal town                                     1
mangopir                                              1
old ravians co-operative housing society              1
sakhi hassan chowrangi                                1
gulistan-e-malir                                      1
maskan chowrangi                                      1
stadium road                                          1
gulshan-e-umair                                       1
dr daud pota road                                     1
surti muslim co-operative housing society             1
maqboolabad society                                   1
landhi                                                1
numaish chowrangi                                     1
dastgir colony                                        1
aisha manzil                                          1
police society                                        1
khokan cooperative housing society                    1
asf tower                                             1
rabia city                                            1
moria goth                                            1
cutchi memon cooperative housing society              1
Name: count, dtype: int64

In [10]:
drop_locations = [
    "app employees co-operative housing society",
    "kashmir colony",
    "kashmir road",
    "surti muslim co-operative housing society",
]

df = df[~df["location"].isin(drop_locations)].copy()

In [11]:
mapping = {

    # This section handles Dha.    "dha defence": "DHA Defence",
    "royal defence tower": "DHA Defence",
    "khayaban-e-ittehad road": "DHA Defence",
    "zamzama": "DHA Defence",
    "sea view apartments": "DHA Defence",

    "defence view society": "Defence View",
    "dha city karachi": "DHA City",

    # This section handles Clifton.    "clifton": "Clifton",
    "frere town": "Clifton",
    "gizri": "Clifton",
    "bath island": "Clifton",
    "delhi colony": "Clifton",
    "punjab colony": "Clifton",
    "punjab chowrangi": "Clifton",

    # This section handles Cantt.    "cantt": "Cantt",
    "p & t colony": "Cantt",
    "dr daud pota road": "Cantt",
    "navy housing scheme karsaz": "Cantt",

    # This section handles Civil Line.    "civil lines": "Civil Lines",

    # This section handles Scheme 33.    "scheme 33": "Scheme 33",
    "falaknaz harmony": "Scheme 33",
    "falaknaz dynasty": "Scheme 33",
    "chapal courtyard": "Scheme 33",
    "chapal uptown": "Scheme 33",
     "saadi road" : "saadi road",
    "suparco road": "Scheme 33",
    "gulshan-e-usman housing society": "Scheme 33",
    "yousaf goth": "Scheme 33",
    "cotton export cooperative housing society": "Scheme 33",
    "asf tower": "Scheme 33",
    "cutchi memon cooperative housing society": "Scheme 33",
    "muhammad bin qasim co-operative housing society": "Scheme 33",
    "gulshan-e-umair": "Scheme 33",
    "abid town": "Scheme 33",
    "police society": "Scheme 33",
    "old ravians co-operative housing society": "Scheme 33",
    "metrovil colony": "Scheme 33",

    # This section handles Scheme 45.    "scheme 45": "Scheme 45",

    # This section handles Bin Qasim Town.    "bin qasim town" : "Bin Qasim Town",

    # This section handles Gulshan-E-Iqbal.    "gulshan-e-iqbal town": "Gulshan-e-Iqbal",
    "kda scheme 1": "Gulshan-e-Iqbal",
    "kda scheme 1 extension": "Gulshan-e-Iqbal",
    "dalmia cement factory road": "Gulshan-e-Iqbal",
    "maskan chowrangi": "Gulshan-e-Iqbal",
    "al-hilal society": "Gulshan-e-Iqbal",
    "pak ideal cooperative housing society": "Gulshan-e-Iqbal",
    "siraj-ud-daula road": "Gulshan-e-Iqbal",
    "stadium road": "Gulshan-e-Iqbal",
    "khokan cooperative housing society": "Gulshan-e-Iqbal",

    # This section handles Gulistan-E-Jauhar.    "gulistan-e-jauhar": "Gulistan-e-Jauhar",
    "kamran chowrangi": "Gulistan-e-Jauhar",
    "rabia city": "Gulistan-e-Jauhar",
    "rufi lake drive apartments": "Gulistan-e-Jauhar",
    "rufi rose petals": "Gulistan-e-Jauhar",

    # This section handles Bahria Town.    "bahria town karachi": "Bahria Town",

    # This section handles Jamshed Town.    "jamshed town": "Jamshed Town",
    "shaheed millat road": "Jamshed Town",
    "khalid bin walid road": "Jamshed Town",
    "jamshed road": "Jamshed Town",
    "amir khusro": "Jamshed Town",
    "amil colony": "Jamshed Town",
    "cosmopolitan society": "Jamshed Town",
    "shahra-e-qaideen": "Jamshed Town",
    "shaheed-e-millat expressway": "Jamshed Town",
    "muslimabad society": "Jamshed Town",
    "maqboolabad society": "Jamshed Town",
    "guru mandir chorangi": "Jamshed Town",
    "jamaluddin afghani road": "Jamshed Town",
    "numaish chowrangi": "Jamshed Town",
    "pib colony": "Jamshed Town",
    "mehmoodabad": "Jamshed Town",
    "manzoor colony": "Jamshed Town",
    "baloch colony": "Jamshed Town",
    "tariq road": "Jamshed Town",
    "hill park": "Jamshed Town",
    "darul aman society":"Jamshed Town",

    # This section handles North Nazimabad.    "north nazimabad": "North Nazimabad",
    "sakhi hassan chowrangi": "North Nazimabad",
    "buffer zone": "North Nazimabad",
    "hyderi": "North Nazimabad",
    "five star chowrangi": "North Nazimabad",
    "shadman": "North Nazimabad",
    "allama iqbal town": "North Nazimabad",

    # This section handles Nazimabad.    "nazimabad": "Nazimabad",

    # This section handles Liaquatabad.    "liaquatabad": "Liaquatabad",

    # This section handles North Karachi.    "north karachi": "North Karachi",
    "new karachi": "North Karachi",
    "shahra-e-usman": "North Karachi",


    # This section handles Orangi Town.    "orangi town":"Orangi Town",

    # This section handles National Highway.    "national highway": "National Highway",

    # This section handles Northern Bypass.    "northern bypass": "Northern Bypass",

    # This section handles Federal B Area.    "federal b area": "Federal B Area",
    "aisha manzil": "Federal B Area",
    "dastgir colony": "Federal B Area",
    "shahrah-e-pakistan": "Federal B Area",
    "gulberg town": "Federal B Area",

    # This section handles Malir.    "malir": "Malir",
    "airport": "Malir",
    "airport road": "Malir",
    "malir link to super highway": "Malir",
    "gulistan-e-malir": "Malir",
    "liaquat avenue": "Malir",
    "moria goth": "Malir",

    # This section handles Shahra-E-Faisal.    "shahra-e-faisal":"Shahra-e-Faisal",

    # This section handles Tipu Sultan Road.    "tipu sultan road":"Tipu Sultan Road",

    # This section handles Gadap.    "gadap town": "Gadap",
    "mangopir": "Gadap",
    "gadap road": "Gadap",

    # This section handles Super Highway.    "super highway": "Super Highway",
    "karachi motorway": "Super Highway",
    "karachi - hyderabad motorway": "Super Highway",
    "oasis park residencia": "Super Highway",

    # This section handles Naya Nazimabad.    "naya nazimabad": "Naya Nazimabad",

    # This section handles Shah Faisal.    "shah faisal town": "Shah Faisal",
    "falcon complex faisal": "Shah Faisal",
    "kn gohar green city": "Shah Faisal",
    "saima luxury homes": "Shah Faisal",

    # This section handles Road.    "university road": "University Road",
    "rashid minhas road": "Rashid Minhas Road",
    "abul hassan isphani road": "Abul Hassan Isphani Road",

    # This section handles Korangi.    "korangi": "Korangi",
    "qayyumabad": "Korangi",
    "landhi": "Korangi",

    # This section handles Saddar.    "saddar town": "Saddar",
    "chapal skymark": "Saddar",
    "ranchore line bazar": "Saddar",
    "m. a. jinnah road": "Saddar",
    "i. i. chundrigar road": "Saddar",
    "mt khan road": "Saddar",
    "garden west": "Saddar",

    # This section handles Site Area.    "sindh industrial trading estate (site)": "SITE Area",

    "jinnah avenue" : "Jinnah Avenue",

    # This section handles Keamari / West Coast.
    "kemari town": "Kemari",

    "baldia town": "Baldia Town",
    "naval colony": "Baldia Town",

    "hawks bay": "Hawks Bay",

}

In [12]:
df['location'] = df['location'].str.lower().map(mapping)

In [13]:
df['location'].value_counts()

location
DHA Defence                 4473
Scheme 33                   2726
Gulshan-e-Iqbal             2305
Gulistan-e-Jauhar           1836
Bahria Town                 1757
Cantt                       1566
North Nazimabad             1077
Jamshed Town                1041
Malir                        997
Gadap                        841
Clifton                      821
Naya Nazimabad               809
Federal B Area               428
North Karachi                422
University Road              345
Jinnah Avenue                247
Korangi                      184
Shah Faisal                  164
Super Highway                115
Saddar                        90
Civil Lines                   86
Rashid Minhas Road            83
Nazimabad                     74
DHA City                      58
saadi road                    57
Bin Qasim Town                57
Defence View                  47
Shahra-e-Faisal               46
Tipu Sultan Road              32
Northern Bypass               31
Abul Hassan Isphani Road      18
Baldia Town                   11
Orangi Town                    7
Liaquatabad                    7
SITE Area                      6
National Highway               5
Kemari                         4
Scheme 45                      3
Name: count, dtype: int64

In [14]:
df['location'].isnull().sum()

np.int64(0)

In [15]:
df['address'].value_counts()

address
dha phase 8, dha defence                                                                      743
dha phase 6, dha defence                                                                      656
askari 6, malir cantonment                                                                    585
falcon complex new malir, malir                                                               516
hmr waterfront, dha phase 8                                                                   511
naya nazimabad, karachi                                                                       469
askari 5 - sector j, askari 5                                                                 404
dha phase 5, dha defence                                                                      328
scheme 33, karachi                                                                            277
callachi cooperative housing society, gulshan-e-iqbal - block 10-a                            266
dha phase 7, dha defence                                                                      250
capital cooperative housing society, scheme 33 - sector 35-a                                  225
north nazimabad - block f, north nazimabad                                                    183
gulistan-e-jauhar - block 15, gulistan-e-jauhar                                               181
shaheed millat road, karachi                                                                  178
gulistan-e-jauhar, karachi                                                                    176
dha phase 4, dha defence                                                                      167
clifton - block 2, clifton                                                                    160
emaar the views, dha phase 8                                                                  158
saadi town, scheme 33                                                                         158
emaar crescent bay, dha phase 8                                                               157
gulistan-e-jauhar - block 14, gulistan-e-jauhar                                               152
burj-ul-harmain, university road                                                              143
dha phase 7 extension, dha defence                                                            139
gulistan-e-jauhar - block 13, gulistan-e-jauhar                                               132
north nazimabad - block h, north nazimabad                                                    131
bath island, karachi                                                                          127
emaar panorama, dha phase 8                                                                   124
khalid bin walid road, karachi                                                                124
bukhari commercial area, dha phase 6                                                          122
pechs block 2, pechs                                                                          122
north nazimabad - block l, north nazimabad                                                    120
bahria apartments, bahria town karachi                                                        120
north nazimabad - block n, north nazimabad                                                    118
gulistan-e-jauhar - block 12, gulistan-e-jauhar                                               117
gulistan-e-jauhar - block 17, gulistan-e-jauhar                                               114
gulshan-e-iqbal - block 10-a, gulshan-e-iqbal                                                 110
bahria town - ali block, bahria town - precinct 12                                            109
bahria sports city, bahria town karachi                                                       108
gulistan-e-jauhar - block 3-a, gulistan-e-jauhar                                              108
emaar coral towers, emaar crescent bay                                                        107
emaar pearl towers, emaar crescent bay                                                        105
gulshan-e-iqbal - block 1, gulshan-e-iqbal                                                    105
metropolis residency, jinnah avenue                                                           102
bahadurabad, gulshan-e-iqbal town                                                             100
gulistan-e-jauhar - block 7, gulistan-e-jauhar                                                100
gulshan-e-maymar, gadap town                                                                   99
gulistan-e-jauhar - block 18, gulistan-e-jauhar                                                98
model colony - malir, malir                                                                    96
naya nazimabad - block a, naya nazimabad                                                       95
bahria town - precinct 8, bahria town karachi                                                  94
clifton - block 9, clifton                                                                     94
gulshan-e-iqbal, gulshan-e-iqbal town                                                          93
bahria town - precinct 10-a, bahria town karachi                                               92
gulshan-e-iqbal - block 7, gulshan-e-iqbal                                                     90
clifton - block 8, clifton                                                                     89
gulshan-e-iqbal - block 4, gulshan-e-iqbal                                                     89
harmain royal residency, gulshan-e-iqbal - block 1                                             88
gulistan-e-jauhar - block 2, gulistan-e-jauhar                                                 88
naya nazimabad - block c, naya nazimabad                                                       87
saadi garden, scheme 33                                                                        87
clifton - block 1, clifton                                                                     87
kda scheme 1, karachi                                                                          87
north town residency, surjani town                                                             86
gulshan-e-iqbal - block 5, gulshan-e-iqbal                                                     84
north nazimabad - block b, north nazimabad                                                     83
askari 5, malir cantonment                                                                     83
civil lines, karachi                                                                           83
bahria town - precinct 11-a, bahria town - precinct 11                                         83
bahria town - precinct 31, bahria town karachi                                                 82
saima arabian villas, gadap town                                                               81
pechs block 6, pechs                                                                           80
gulshan-e-iqbal - block 2, gulshan-e-iqbal                                                     78
navy housing scheme karsaz, karachi                                                            77
federal b area - block 10, federal b area                                                      75
bahria town - precinct 11-b, bahria town - precinct 11                                         74
north karachi, karachi                                                                         73
gulshan-e-iqbal - block 13-d2, gulshan-e-iqbal                                                 73
saima villas, karachi motorway                                                                 72
gulistan-e-jauhar - block 19, gulistan-e-jauhar                                                72
bahria town - quaid villas, bahria town - precinct 2                                           72
bahria town - precinct 1, bahria town karachi                                                  70
dha phase 2 extension, dha defence                                                             69
gulshan-e-maymar - sector r, gulshan-e-maymar                                                  69
bahria town - precinct 10-b, bahria town karachi                                               68
naya nazimabad - block d, naya nazimabad                                                       68
university road, karachi                                                                       68
naya nazimabad - block b, naya nazimabad                                                       67
dha phase 8 - zone a, dha phase 8                                                              65
gulshan-e-iqbal - block 13/d-1, gulshan-e-iqbal                                                65
dha phase 1, dha defence                                                                       65
gulistan-e-jauhar - block 16, gulistan-e-jauhar                                                64
jinnah avenue, karachi                                                                         64
bahria town - precinct 6, bahria town karachi                                                  63
emaar reef towers, emaar crescent bay                                                          63
falaknaz dreams, malir                                                                         63
bahria town karachi, karachi                                                                   62
daniyal residency, scheme 33                                                                   62
askari 5 - sector h, askari 5                                                                  62
bahria town - precinct 27, bahria town karachi                                                 61
gulshan-e-maymar - sector y, gulshan-e-maymar                                                  61
bahria homes - iqbal villas, bahria town - precinct 2                                          60
dhoraji colony, gulshan-e-iqbal town                                                           59
gulshan-e-iqbal - block 13/d, gulshan-e-iqbal                                                  58
gulzar-e-hijri, scheme 33                                                                      58
gulistan-e-jauhar - block 3, gulistan-e-jauhar                                                 57
jamshed road, karachi                                                                          57
meerut society, scheme 33                                                                      57
bahria heights, bahria town karachi                                                            57
gulshan-e-iqbal - block 6, gulshan-e-iqbal                                                     57
badar commercial area, dha phase 5                                                             57
hansa society, scheme 33                                                                       56
allahwala town - sector 31-g, allahwala town                                                   55
federal b area - block 12, federal b area                                                      54
bahria hills, bahria town karachi                                                              54
falaknaz presidency, malir                                                                     54
cantt view lodges, malir link to super highway                                                 53
north nazimabad - block m, north nazimabad                                                     52
clifton - block 4, clifton                                                                     52
north nazimabad, karachi                                                                       52
karachi university housing society, scheme 33                                                  51
north nazimabad - block k, north nazimabad                                                     51
dohs phase 1, malir cantonment                                                                 51
north nazimabad - block a, north nazimabad                                                     50
saima jinnah avenue, university road                                                           50
sector 31 - punjabi saudagar city phase 2, scheme 33 - sector 31                               50
dha phase 2, dha defence                                                                       50
paragon tower, bahria town - precinct 17                                                       50
emaar park edge, dha phase 8                                                                   50
saima residencia, scheme 33 - sector 34-a                                                      49
bahria town - precinct 4, bahria town karachi                                                  49
creek vista, dha phase 8                                                                       49
gulshan-e-maymar - sector t, gulshan-e-maymar                                                  49
sector 25-a - punjabi saudagar multi purpose society, scheme 33 - sector 25-a                  48
nishat commercial area, dha phase 6                                                            47
sharfabad, gulshan-e-iqbal town                                                                47
north nazimabad - block d, north nazimabad                                                     45
falaknaz twin tower, gulzar-e-hijri                                                            45
pilibhit cooperative housing society, scheme 33 - sector 18-a                                  45
tulip tower, saadi road                                                                        45
shahra-e-faisal, karachi                                                                       44
gulshan-e-iqbal - block 17, gulshan-e-iqbal                                                    44
gulshan-e-roomi, faisal cantonment                                                             43
kda officers society, gulshan-e-iqbal town                                                     43
frere town, karachi                                                                            43
shaz residency, gulshan-e-iqbal town                                                           43
al-murtaza commercial area, dha phase 8                                                        42
lucky one apartment, rashid minhas road                                                        41
federal b area - block 13, federal b area                                                      41
gulshan-e-iqbal town, karachi                                                                  41
gulshan-e-iqbal - block 13/a, gulshan-e-iqbal                                                  41
government teacher housing society - sector 16-a, scheme 33 - sector 16-a                      41
al madni heights, university road                                                              41
dascon tower, bahria hills                                                                     41
bahria paradise - precinct 51, bahria paradise                                                 40
clifton - block 7, clifton                                                                     40
gwalior cooperative housing society, scheme 33                                                 40
zeenatabad, scheme 33                                                                          40
chapal courtyard, karachi                                                                      39
sea view apartments, karachi                                                                   39
clifton, karachi                                                                               39
gulshan-e-iqbal - block 3, gulshan-e-iqbal                                                     39
tariq road, karachi                                                                            39
gulshan-e-iqbal - block 13/c, gulshan-e-iqbal                                                  39
karachi administration employees society, jamshed town                                         38
aman golf view, jinnah avenue                                                                  38
lakhani fantasia, scheme 33                                                                    38
state bank of pakistan housing society, scheme 33 - sector 17-a                                38
saadi town - block 5, saadi town                                                               38
saddar, saddar town                                                                            38
falaknaz harmony, karachi                                                                      37
saima elite villas, malir                                                                      37
bahria town - precinct 16, bahria town karachi                                                 37
airport road, karachi                                                                          37
north nazimabad - block j, north nazimabad                                                     37
sehar commercial area, dha phase 7                                                             36
amir khusro, karachi                                                                           36
shadman town - sector-14/b, shadman                                                            36
ittehad commercial area, dha phase 6                                                           36
bahria paradise, bahria town karachi                                                           36
kn gohar green city, karachi                                                                   35
clifton - block 5, clifton                                                                     35
dha city karachi, karachi                                                                      35
gulshan-e-maymar - sector x, gulshan-e-maymar                                                  34
askari 4, gulistan-e-jauhar                                                                    34
bahria town - precinct 19, bahria town karachi                                                 34
north nazimabad - block i, north nazimabad                                                     34
gulshan-e-iqbal - block 11, gulshan-e-iqbal                                                    34
mateen complex, bin qasim town                                                                 34
saadi garden - block 5, saadi garden                                                           33
chapal sun city, scheme 33                                                                     33
gulistan-e-jauhar - block 1, gulistan-e-jauhar                                                 32
gulshan-e-maymar - sector q, gulshan-e-maymar                                                  32
saima luxury homes, karachi                                                                    32
federal b area, karachi                                                                        32
garden east, jamshed town                                                                      32
saima royal residency, rashid minhas road                                                      32
tipu sultan road, karachi                                                                      32
allahwala town - sector 31-b, allahwala town                                                   32
gulshan-e-iqbal - block 13/d-3, gulshan-e-iqbal                                                32
gulistan-e-jauhar - block 10, gulistan-e-jauhar                                                32
north nazimabad - block g, north nazimabad                                                     32
pechs block 3, pechs                                                                           30
sadaf cooperative housing society, gulzar-e-hijri                                              30

In [22]:
df[df['location']=='Gadap']['sub_location'].value_counts()

sub_location
gulshan-e-maymar, gadap town                                                            99
north town residency, surjani town                                                      86
saima arabian villas, gadap town                                                        81
gulshan-e-maymar - sector r, gulshan-e-maymar                                           69
gulshan-e-maymar - sector y, gulshan-e-maymar                                           61
gulshan-e-maymar - sector t, gulshan-e-maymar                                           49
gulshan-e-maymar - sector x, gulshan-e-maymar                                           34
gulshan-e-maymar - sector q, gulshan-e-maymar                                           32
surjani town, gadap town                                                                28
gulshan-e-maymar - sector z, gulshan-e-maymar                                           26
silk garden, surjani town                                                               19
gulshan-e-maymar - sector w, gulshan-e-maymar                                           17
diamond city, gulshan-e-maymar                                                          16
alize garden, gadap town                                                                16
saima green valley, gadap town                                                          13
wasi country park, gulshan-e-maymar                                                     11
surjani town - sector 5d, surjani town - sector 5                                       10
al-jadeed residency, gadap town                                                          9
garden city - block a, garden city                                                       9
gulshan-e-maymar - sector s, gulshan-e-maymar                                            9
gulshan-e-maymar - sector v, gulshan-e-maymar                                            9
surjani town - sector 7a, surjani town                                                   8
surjani town - sector 7b, surjani town                                                   8
surjani town - sector 6, surjani town                                                    8
rainbow towers and shopping mall, gulshan-e-maymar                                       7
gulshan-e-maymar - sector u, gulshan-e-maymar                                            7
al jannat city, gadap town                                                               7
ahsanabad, gadap town                                                                    6
surjani town - sector 1, surjani town                                                    6
pir ahmed zaman town - block 1, pir ahmed zaman town                                     6
gulshan-e-maymar - sector p, gulshan-e-maymar                                            6
gadap town                                                                               5
memon goth, gadap town                                                                   5
rainbow classic homes, gulshan-e-maymar                                                  5
alize garden - block 1, alize garden                                                     4
commander city, gadap town                                                               3
pha maymar towers, gulshan-e-maymar                                                      3
pearl villas, surjani town                                                               3
surjani town - sector 6b, surjani town - sector 6                                        3
memon goth road, gadap town                                                              2
gulshan-e-maymar - sector za, gulshan-e-maymar                                           2
muhammadpur, gulshan-e-maymar - sector v                                                 2
pir ahmed zaman town, gadap town                                                         2
commander enclave, gadap road                                                            2
surjani town - sector 4d, surjani town                                                   2
surjani town - sector 7c, surjani town                                                   2
garden city - block b, garden city                                                       2
ahsanabad phase 1, ahsanabad                                                             1
ahsanabad phase 3, ahsanabad                                                             1
salafia society, taiser town                                                             1
mangopir                                                                                 1
olympic pride phase ii, surjani town                                                     1
surjani town - sector 2, surjani town                                                    1
the dream villas, memon goth                                                             1
ahsanabad phase 2, ahsanabad                                                             1
al ghafoor grande city, surjani town                                                     1
sherwani royal suites, gadap town                                                        1
surjani town - sector 5b, surjani town - sector 5                                        1
lakhani park vista, gulshan-e-maymar                                                     1
surjani town - sector 4b, surjani town                                                   1
gulshan-e-kaneez fatima society - surjani, surjani town - sector 3                       1
al-ghafoor grande tower, gulshan-e-maymar - sector z                                     1
gulshan-e-noor, taiser town                                                              1
surjani town - sector 4a, surjani town                                                   1
surjani town - sector 4c, surjani town                                                   1
roti corporation of pakistan employees cooperative housing society, gulshan-e-maymar     1
surjani town - sector 5, surjani town                                                    1
garden city, gadap town                                                                  1
pir ahmed zaman town - block 2, pir ahmed zaman town                                     1
Name: count, dtype: int64

In [23]:
sub_location_mapping = {

    # This section handles Gulshan-E-Maymar.    "diamond city, gulshan-e-maymar": "Gulshan-e-Maymar",
    "wasi country park, gulshan-e-maymar": "Gulshan-e-Maymar",
    "pha maymar towers, gulshan-e-maymar": "Gulshan-e-Maymar",
    "lakhani park vista, gulshan-e-maymar": "Gulshan-e-Maymar",
    "rainbow towers and shopping mall, gulshan-e-maymar": "Gulshan-e-Maymar",
    "rainbow classic homes, gulshan-e-maymar": "Gulshan-e-Maymar",
    "roti corporation of pakistan employees cooperative housing society, gulshan-e-maymar": "Gulshan-e-Maymar",

    # This section handles Surjani Town.    "north town residency, surjani town": "Surjani Town",
    "silk garden, surjani town": "Surjani Town",
    "pearl villas, surjani town": "Surjani Town",
    "olympic pride phase ii, surjani town": "Surjani Town",
    "al ghafoor grande city, surjani town": "Surjani Town",
    "gulshan-e-kaneez fatima society - surjani, surjani town - sector 3": "Surjani Town",

    # This section handles Memon Goth / Gadap.    "alize garden, gadap town": "Memon Goth",
    "alize garden - block 1, alize garden": "Memon Goth",
    "saima green valley, gadap town": "Memon Goth",
    "al-jadeed residency, gadap town": "Memon Goth",
    "memon goth road, gadap town": "Memon Goth",
    "the dream villas, memon goth": "Memon Goth",
    "memon goth, gadap town": "Memon Goth",

    # This section handles Garden City.    "garden city - block a, garden city": "Garden City",
    "garden city - block b, garden city": "Garden City",
    "garden city, gadap town": "Garden City",

    # This section handles Ahsanabad.    "ahsanabad phase 1, ahsanabad": "Ahsanabad",
    "ahsanabad phase 2, ahsanabad": "Ahsanabad",
    "ahsanabad phase 3, ahsanabad": "Ahsanabad",

    # This section handles Pir Ahmed Zaman Town.    "pir ahmed zaman town - block 1, pir ahmed zaman town": "Pir Ahmed Zaman Town",
    "pir ahmed zaman town - block 2, pir ahmed zaman town": "Pir Ahmed Zaman Town",
    "pir ahmed zaman town, gadap town": "Pir Ahmed Zaman Town",

    # This section handles Commander City.    "commander city, gadap town": "Commander City",
    "commander enclave, gadap road": "Commander City",

    # This section handles Taiser Town.    "salafia society, taiser town": "Taiser Town",
    "gulshan-e-noor, taiser town": "Taiser Town",
}

df["sub_location"] = (
    df["sub_location"]
    .replace(sub_location_mapping)
)

In [24]:
sub_location_mapping = {

    # ---------------- Gulshan-e-Maymar ----------------
    "gulshan-e-maymar, gadap town": "Gulshan-e-Maymar",
    "Gulshan-e-Maymar": "Gulshan-e-Maymar",

    "gulshan-e-maymar - sector p, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector q, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector r, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector s, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector t, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector u, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector v, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector w, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector x, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector y, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector z, gulshan-e-maymar": "Gulshan-e-Maymar",
    "gulshan-e-maymar - sector za, gulshan-e-maymar": "Gulshan-e-Maymar",

    "diamond city, gulshan-e-maymar": "Gulshan-e-Maymar",
    "wasi country park, gulshan-e-maymar": "Gulshan-e-Maymar",
    "rainbow towers and shopping mall, gulshan-e-maymar": "Gulshan-e-Maymar",
    "rainbow classic homes, gulshan-e-maymar": "Gulshan-e-Maymar",
    "pha maymar towers, gulshan-e-maymar": "Gulshan-e-Maymar",
    "lakhani park vista, gulshan-e-maymar": "Gulshan-e-Maymar",
    "roti corporation of pakistan employees cooperative housing society, gulshan-e-maymar": "Gulshan-e-Maymar",
    "al-ghafoor grande tower, gulshan-e-maymar - sector z": "Gulshan-e-Maymar",
    "muhammadpur, gulshan-e-maymar - sector v": "Gulshan-e-Maymar",
    "sherwani royal suites, gadap town": "Gulshan-e-Maymar",

    # ---------------- Surjani Town ----------------
    "Surjani Town": "Surjani Town",
    "surjani town, gadap town": "Surjani Town",

    "surjani town - sector 1, surjani town": "Surjani Town",
    "surjani town - sector 2, surjani town": "Surjani Town",
    "surjani town - sector 4a, surjani town": "Surjani Town",
    "surjani town - sector 4b, surjani town": "Surjani Town",
    "surjani town - sector 4c, surjani town": "Surjani Town",
    "surjani town - sector 4d, surjani town": "Surjani Town",
    "surjani town - sector 5, surjani town": "Surjani Town",
    "surjani town - sector 5b, surjani town - sector 5": "Surjani Town",
    "surjani town - sector 5d, surjani town - sector 5": "Surjani Town",
    "surjani town - sector 6, surjani town": "Surjani Town",
    "surjani town - sector 6b, surjani town - sector 6": "Surjani Town",
    "surjani town - sector 7a, surjani town": "Surjani Town",
    "surjani town - sector 7b, surjani town": "Surjani Town",
    "surjani town - sector 7c, surjani town": "Surjani Town",

    "saima arabian villas, gadap town": "Surjani Town",

    # ---------------- Memon Goth ----------------
    "Memon Goth": "Memon Goth",
    "gadap town": "Memon Goth",

    # ---------------- Garden City ----------------
    "Garden City": "Garden City",

    # ---------------- Pir Ahmed Zaman Town ----------------
    "Pir Ahmed Zaman Town": "Pir Ahmed Zaman Town",

    # ---------------- Ahsanabad ----------------
    "ahsanabad, gadap town": "Ahsanabad",
    "Ahsanabad": "Ahsanabad",

    # ---------------- Commander City ----------------
    "Commander City": "Commander City",

    # ---------------- Al Jannat City ----------------
    "al jannat city, gadap town": "Al Jannat City",

    # ---------------- Taiser Town ----------------
    "Taiser Town": "Taiser Town",

    # ---------------- Manghopir ----------------
    "mangopir": "Manghopir",
}

df["sub_location"] = df["sub_location"].replace(sub_location_mapping)

In [25]:
locations_to_remove = [
    "Garden City",
    "Pir Ahmed Zaman Town",
    "Ahsanabad",
    "Al Jannat City",
    "Commander City",
    "Taiser Town",
    "Manghopir"
]

df = df[~df["sub_location"].isin(locations_to_remove)].copy()

In [26]:
df.groupby('location')['sub_location'].value_counts()

location            sub_location
Bahria Town         bahria apartments, bahria town karachi                                                        120
                    bahria town - ali block, bahria town - precinct 12                                            109
                    bahria sports city, bahria town karachi                                                       108
                    bahria town - precinct 8, bahria town karachi                                                  94
                    bahria town - precinct 10-a, bahria town karachi                                               92
                    bahria town - precinct 11-a, bahria town - precinct 11                                         83
                    bahria town - precinct 31, bahria town karachi                                                 82
                    bahria town - precinct 11-b, bahria town - precinct 11                                         74
                    bahria town - quaid villas, bahria town - precinct 2                                           72
                    bahria town - precinct 1, bahria town karachi                                                  70
                    bahria town - precinct 10-b, bahria town karachi                                               68
                    bahria town - precinct 6, bahria town karachi                                                  63
                    bahria town karachi                                                                            62
                    bahria town - precinct 27, bahria town karachi                                                 61
                    bahria homes - iqbal villas, bahria town - precinct 2                                          60
                    bahria heights, bahria town karachi                                                            57
                    bahria hills, bahria town karachi                                                              54
                    paragon tower, bahria town - precinct 17                                                       50
                    bahria town - precinct 4, bahria town karachi                                                  49
                    dascon tower, bahria hills                                                                     41
                    bahria paradise - precinct 51, bahria paradise                                                 40
                    bahria town - precinct 16, bahria town karachi                                                 37
                    bahria paradise, bahria town karachi                                                           36
                    bahria town - precinct 19, bahria town karachi                                                 34
                    bahria town - precinct 17, bahria town karachi                                                 26
                    bahria town - precinct 15, bahria town karachi                                                 22
                    bahria town - precinct 12, bahria town karachi                                                 21
                    bahria town - precinct 35, bahria sports city                                                  17
                    bahria town - precinct 7, bahria town karachi                                                  14
                    bahria town - precinct 2, bahria town karachi                                                  13
                    bahria town - precinct 9, bahria town karachi                                                  11
                    bahria town - precinct 18, bahria town karachi                                                  5
                    bahria town - precinct 36, bahria sports city                                                   3
                    bahria town - precinct 11, bahria town karachi                                                  2
                    bahria town - precinct 3, bahria town karachi                                                   2
                    bahria town - precinct 30, bahria town karachi                                                  2
                    bahria golf city, bahria town karachi                                                           1
                    bahria town - precinct 20, bahria town karachi                                                  1
                    dolce mall & signature residency, bahria town karachi                                           1
Baldia Town         gulshan-e-mazdoor housing scheme, naval colony                                                  4
                    naval colony                                                                                    4
                    haroon bahria society - sector 1, hbchs - haroon bahria society                                 1
Bin Qasim Town      mateen complex                                                                                 34
                    shah latif town                                                                                 5
                    model colony                                                                                    4
                    pn welfare housing scheme                                                                       4
                    quaidabad                                                                                       4
                    gulshan-e-hadeed - phase 2, gulshan-e-hadeed                                                    2
                    gulshan-e-benazir - block a, gulshan-e-benazir township scheme                                  1
                    gulshan-e-benazir - block b, gulshan-e-benazir township scheme                                  1
                    gulshan-e-hadeed                                                                                1
                    port qasim                                                                                      1
Cantt               askari 6, malir cantonment                                                                    585
                    askari 5 - sector j, askari 5                                                                 404
                    askari 5, malir cantonment                                                                     83
                    navy housing scheme karsaz                                                                     77
                    askari 5 - sector h, askari 5                                                                  62
                    dohs phase 1, malir cantonment                                                                 51
                    gulshan-e-roomi, faisal cantonment                                                             43
                    askari 5 - sector f, askari 5                                                                  26
                    askari 5 - sector g, askari 5                                                                  24
                    saima presidency, malir cantonment                                                             24
                    navy housing scheme karsaz - phase 3, navy housing scheme karsaz                               23
                    malir cantonment                                                                               20
                    navy housing scheme karsaz - phase 1, navy housing scheme karsaz                               15
                    askari 5 - sector e, askari 5                                                                  14
                    cantt bazar, malir cantonment                                                                  14
                    navy housing scheme karsaz - phase 2, navy housing scheme karsaz                               13
                    dohs phase 2, malir cantonment                                                                 11
                    askari 5 - sector b, askari 5                                                                  10
                    p & t colony                                                                                   10
                    army officers housing society, faisal cantonment                                                9
                    falcon complex (afohs), malir cantonment                                                        8
                    pia housing society, faisal cantonment                                                          5
                    sohni serenity executive apartments, gulshan-e-roomi                                            5
                    askari 3, karachi cantonment                                                                    4
                    dadabhoy town, faisal cantonment                                                                3
                    navy housing scheme karsaz road, navy housing scheme karsaz                                     3
                    sohni golf view apartments, gulshan-e-roomi                                                     3
                    askari 2, karachi cantonment                                                                    2
                    askari 5 - sector c, askari 5                                                                   2
                    atap city, gulshan-e-roomi                                                                      2
                    falcon complex - air force officers housing scheme (afohs), faisal cantonment                   2
                    fariha excellency, malir cantonment                                                             2
                    askari 5 - sector d, askari 5                                                                   1
                    dr daud pota road                                                                               1
                    karachi cantonment                                                                              1
                    karsaz, faisal cantonment                                                                       1
Civil Lines         hsj icon                                                                                        3
Clifton             clifton - block 2                                                                             160
                    bath island                                                                                   127
                    clifton - block 9                                                                              94
                    clifton - block 8                                                                              89
                    clifton - block 1                                                                              87
                    clifton - block 4                                                                              52
                    frere town                                                                                     43
                    clifton - block 7                                                                              40
                    clifton - block 5                                                                              35
                    clifton - block 3                                                                              11
                    clifton - block 6                                                                              11
                    upper gizri, gizri                                                                              9
                    grand monarch seaside residency, clifton - block 1                                              6
                    delhi colony                                                                                    5
                    punjab colony                                                                                   3
                    chandio village, punjab colony                                                                  2
                    punjab chowrangi                                                                                2
                    dynasty tower, clifton - block 9                                                                1
                    gizri                                                                                           1
                    khaliq-uz-zaman road, clifton - block 8                                                         1
                    khayaban-e-iqbal                                                                                1
                    lower gizri, gizri                                                                              1
                    sawera grand, bath island                                                                       1
DHA City            dha city karachi                                                                               35
                    dha city - sector 1, dha city karachi                                                           6
                    ary laguna, dha city karachi                                                                    5
                    dha city - sector 14b, dha city - sector 14                                                     3
                    dha city - sector 3a, dha city - sector 3                                                       2
                    dha city - sector 3c, dha city - sector 3                                                       2
                    askari towers, dha city - sector 1                                                              1
                    dha city - cbd commercial, dha city karachi                                                     1
                    dha city - sector 3b, dha city - sector 3                                                       1
                    dha oasis - sector 1, dha oasis                                                                 1
                    dha oasis, dha city karachi                                                                     1
DHA Defence         dha phase 8                                                                                   743
                    dha phase 6                                                                                   656
                    hmr waterfront, dha phase 8                                                                   511
                    dha phase 5                                                                                   328
                    dha phase 7                                                                                   250
                    dha phase 4                                                                                   167
                    emaar the views, dha phase 8                                                                  158
                    emaar crescent bay, dha phase 8                                                               157
                    dha phase 7 extension                                                                         139
                    emaar panorama, dha phase 8                                                                   124
                    bukhari commercial area, dha phase 6                                                          122
                    emaar coral towers, emaar crescent bay                                                        107
                    emaar pearl towers, emaar crescent bay                                                        105
                    dha phase 2 extension                                                                          69
                    dha phase 1                                                                                    65
                    dha phase 8 - zone a, dha phase 8                                                              65
                    emaar reef towers, emaar crescent bay                                                          63
                    badar commercial area, dha phase 5                                                             57
                    dha phase 2                                                                                    50
                    emaar park edge, dha phase 8                                                                   50
                    creek vista, dha phase 8                                                                       49
                    nishat commercial area, dha phase 6                                                            47
                    al-murtaza commercial area, dha phase 8                                                        42
                    sea view apartments                                                                            39
                    ittehad commercial area, dha phase 6                                                           36
                    sehar commercial area, dha phase 7                                                             36
                    dha phase 8 - zone b, dha phase 8                                                              30
                    rahat commercial area, dha phase 6                                                             30
                    dha phase 5 extension, dha phase 5                                                             21
                    tauheed commercial area, dha phase 5                                                           16
                    zamzama commercial area, dha phase 5                                                           13
                    dha phase 8 extension, dha phase 8                                                             12
                    muslim commercial area, dha phase 6                                                            12
                    jami commercial area, dha phase 7                                                              10
                    navy housing scheme zamzama, zamzama                                                           10
                    darakhshan villas, dha phase 6                                                                  7
                    khalid commercial area, dha phase 7 extension                                                   7
                    the arkadians, dha phase 8 - zone b                                                             7
                    emaar ocean front, dha phase 8                                                                  6
                    saba commercial area, dha phase 5                                                               6
                    dha phase 8 - zone d, dha phase 8                                                               5
                    dha phase 2 - sunset boulevard commercial area, dha phase 2                                     4
                    dha phase 8 - zone e, dha phase 8                                                               4
                    emaar pearl tower 3, emaar crescent bay                                                         4
                    khayaban-e-ittehad road                                                                         4
                    khayaban-e-roomi, dha phase 8                                                                   4

In [27]:
df['location'].isnull().sum()

np.int64(0)

In [28]:
df.sample(100)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type
1227,Double Storey House for Sale Merchant Navy Soc...,"pakistan merchant navy society, scheme 33 - se...",Scheme 33,"pakistan merchant navy society, scheme 33 - se...",32500000.0,36111.11,900.0,4,4,2.0,NaN,2.0,1.0,0,0,0,0,2022.0,house
1591,85 Gaz Brand New West Open Home For Sale In Da...,"gulshan-e-dad rahim, shah faisal town",Shah Faisal,"gulshan-e-dad rahim, shah faisal town",9200000.0,12026.14,765.0,2,3,1.0,NaN,2.0,1.0,0,1,1,0,2025.0,house
171,House For sale In Karachi,"askari 5 - sector h, askari 5",Cantt,"askari 5 - sector h, askari 5",97500000.0,25370.80,3843.0,5,5,1.0,NaN,NaN,1.0,0,1,1,0,2026.0,house
18018,Brand New 120 Sq-Yards G+1 West Open 30 Fit Wi...,"gulshan-e-maymar - sector r, gulshan-e-maymar",Gadap,Gulshan-e-Maymar,21500000.0,19907.41,1080.0,4,4,2.0,NaN,2.0,1.0,0,2,1,1,2025.0,house
8798,Gulshan E Iqbal Block 18 (350 Sq Yards),"gulshan-e-iqbal - block 18, gulshan-e-iqbal",Gulshan-e-Iqbal,gulshan-e-iqbal - block 18,125000000.0,39682.54,3150.0,5,5,2.0,NaN,NaN,1.0,0,2,1,1,2021.0,house
12029,Stunning and affordable Prime Location Flat av...,"bufferzone - sector 15-a/2, buffer zone",North Karachi,"bufferzone - sector 15-a/2, buffer zone",11000000.0,10018.21,1098.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
17589,Beautiful Single Storey Villa For Sale,"the dream villas, memon goth",Gadap,Memon Goth,12000000.0,11111.11,1080.0,3,2,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house
2329,FLAT FOR SALE PHASE 2 E X T D H A 3 BED D/D 3R...,"dha phase 2 extension, dha defence",DHA Defence,dha phase 2 extension,20000000.0,18214.94,1098.0,3,3,1.0,NaN,NaN,1.0,0,0,0,0,2017.0,flat
22487,1000 Yards Brand Ultra Modern Designer House F...,"dha phase 6, dha defence",DHA Defence,dha phase 6,480000000.0,53333.33,9000.0,6,6,2.0,NaN,2.0,6.0,0,2,1,1,2026.0,house
21999,Double story House available for sale,"north nazimabad - block a, north nazimabad",North Nazimabad,north nazimabad - block a,150000000.0,27777.78,5400.0,8,7,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house
408,FLAT FOR SALE ||NORTH NAZMABAD BLOCK K||3BED D...,"north nazimabad - block k, north nazimabad",North Nazimabad,north nazimabad - block k,12500000.0,9259.26,1350.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
3378,Your Dream 240 Square Yards House Is Available...,"saima luxury homes, karachi",Shah Faisal,saima luxury homes,41000000.0,18981.48,2160.0,3,3,1.0,NaN,NaN,1.0,0,0,1,1,NaN,house
21023,Bungalow Available For Sale Proper Two Units,"dha phase 7, dha defence",DHA Defence,dha phase 7,155000000.0,43055.56,3600.0,6,6,2.0,NaN,2.0,2.0,0,1,1,0,2016.0,house
17791,240 Sq Yds West Open Corner Fully Furnished On...,"capital cooperative housing society, scheme 33...",Scheme 33,"capital cooperative housing society, scheme 33...",52500000.0,24305.56,2160.0,5,6,1.0,NaN,1.0,1.0,0,0,1,1,2024.0,house
11172,Last Floor Avaliable | Views Tower 2 | 2 Bed w...,"emaar the views, dha phase 8",DHA Defence,"emaar the views, dha phase 8",82300000.0,45046.52,1827.0,2,2,1.0,NaN,NaN,1.0,1,1,1,1,NaN,flat
6324,Perfect Prime Location 2354 Square Feet Flat I...,"emaar park edge, dha phase 8",DHA Defence,"emaar park edge, dha phase 8",108000000.0,45801.53,2358.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
4429,3 BED DD APARTMENT FOR SALE IN NORTH NAZIMABAD...,"north nazimabad - block b, north nazimabad",North Nazimabad,north nazimabad - block b,30000000.0,20703.93,1449.0,3,3,1.0,NaN,13.0,1.0,2,0,1,0,NaN,flat
16436,Luxurious Apartment For Sale,"clifton - block 2, clifton",Clifton,clifton - block 2,70000000.0,27977.62,2502.0,3,4,2.0,17.0,22.0,2.0,3,1,1,1,2021.0,flat
11841,3 Bed Dd Flat For Sale 1600 SQ Ft 1st Floor,"shadman town - sector-14/b, shadman",North Nazimabad,"shadman town - sector-14/b, shadman",18000000.0,11235.96,1602.0,3,3,1.0,NaN,NaN,1.0,0,0,1,0,2015.0,flat
7701,120 Square Yards Brand New House,"zeenatabad, scheme 33",Scheme 33,zeenatabad,30000000.0,27777.78,1080.0,4,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
14176,Bungalow For Sale,"dha phase 4, dha defence",DHA Defence,dha phase 4,140000000.0,31111.11,4500.0,3,4,1.0,NaN,NaN,3.0,0,1,1,0,2002.0,house
18877,End Your Search For Prime Location House Here ...,"bahria paradise - precinct 51, bahria paradise",Bahria Town,"bahria paradise - precinct 51, bahria paradise",52000000.0,11555.56,4500.0,5,5,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
20623,Double Story House For Sale North Nazimabad Bl...,"north nazimabad - block n, north nazimabad",North Nazimabad,north nazimabad - block n,62500000.0,27126.74,2304.0,6,6,2.0,NaN,1.0,1.0,0,0,1,0,NaN,house
10793,A House Which Make You Feel Royal Luxuirous Id...,"bath island, karachi",Clifton,bath island,100000000.0,43402.78,2304.0,3,5,2.0,6.0,10.0,2.0,2,0,1,0,2020.0,flat
12517,Avail Yourself A Great Prime Location 1050 Squ...,"gulistan-e-jauhar - block 13, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 13,12500000.0,11870.85,1053.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11032,West Open 400 Yard House For Sale In Johar,"gulistan-e-jauhar - block 14, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 14,87500000.0,24305.56,3600.0,8,6,2.0,NaN,2.0,1.0,0,1,1,1,2015.0,house
7878,FLAT FOR SALE,"khalid bin walid road, karachi",Jamshed Town,khalid bin walid road,55000000.0,34332.08,1602.0,3,3,1.0,1.0,1.0,1.0,2,1,1,1,2022.0,flat
18033,Flat For Sale 2 Bed Lounge Main Shahrah-E-Paki...,"federal b area - block 10, federal b area",Federal B Area,federal b area - block 10,8000000.0,12345.68,648.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
12109,"3 Bed Apartment For Sale In Titan One, Callach...","callachi cooperative housing society, gulshan-...",Gulshan-e-Iqbal,"callachi cooperative housing society, gulshan-...",32000000.0,13570.82,2358.0,3,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11404,BRAND NEW MODERN LUXURY APARTMENTS AT AFFORDAB...,"gulistan-e-jauhar - block 7, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 7,20000000.0,16708.44,1197.0,2,2,1.0,4.0,5.0,1.0,1,1,1,1,2025.0,flat
9425,Flat For Sale In Emaar The Views,"emaar the views, dha phase 8",DHA Defence,"emaar the views, dha phase 8",97500000.0,67287.78,1449.0,2,3,2.0,NaN,NaN,1.0,0,1,1,0,NaN,flat
11499,You Can Find A Gorgeous Flat For Sale In Askar...,"askari 5 - sector j, askari 5",Cantt,"askari 5 - sector j, askari 5",41000000.0,17062.01,2403.0,3,3,2.0,4.0,7.0,4.0,1,1,1,1,2023.0,flat
13489,Double Storey Brand New House Available For Sale,"north nazimabad - block f, north nazimabad",North Nazimabad,north nazimabad - block f,160000000.0,35555.56,4500.0,6,7,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house
12380,BRAND NEW GROUND PLUS ONE HOUSE FOR SALE,musalmanan-e-punjab cooperative housing societ...,Scheme 33,musalmanan-e-punjab cooperative housing societ...,27500000.0,25462.96,1080.0,4,5,2.0,NaN,2.0,0.0,0,0,1,1,2026.0,house
14226,EXCELLENT CHANCE DEAL: 500 SQ YD WEST-OPEN BUN...,"dha phase 7, dha defence",DHA Defence,dha phase 7,120000000.0,26666.67,4500.0,5,5,2.0,NaN,NaN,4.0,0,2,1,0,NaN,house
5415,Distinctive 1 Bedroom 964 Square Feet Apartmen...,"hmr waterfront, dha phase 8",DHA Defence,"hmr waterfront, dha phase 8",40500000.0,42056.07,963.0,1,1,1.0,NaN,35.0,1.0,3,0,1,0,NaN,flat
1964,120 Sq/Yd Luxury Bungalow For Sale In Naya Naz...,"naya nazimabad, karachi",Naya Nazimabad,None,41000000.0,37962.96,1080.0,3,3,2.0,NaN,2.0,2.0,0,1,1,1,2026.0,house
16430,Brand New 500 SQU House Available In Falcon Co...,"falcon complex new malir, malir",Malir,falcon complex new malir,115000000.0,25555.56,4500.0,5,5,1.0,NaN,3.0,3.0,0,2,1,0,2020.0,house
8064,Precinct 27 Villa For Sale Chance Deal Urgent ...,"bahria town - precinct 27, bahria town karachi",Bahria Town,"bahria town - precinct 27, bahria town karachi",16500000.0,7801.42,2115.0,3,4,2.0,NaN,2.0,1.0,0,1,1,1,2024.0,house
3570,2950 Square Feet Flat In Central Askari 6 For ...,"askari 6, malir cantonment",Cantt,"askari 6, malir cantonment",40000000.0,13550.14,2952.0,4,4,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
13128,Beautifully Designed 6-Bedroom House Featuring...,"dha phase 6, dha defence",DHA Defence,dha phase 6,152500000.0,33888.89,4500.0,6,6,1.0,NaN,NaN,3.0,0,1,1,0,NaN,house
22751,Prime Location 1151 Square Feet Flat In Karach...,"karachi - hyderabad motorway, karachi",Super Highway,karachi - hyderabad motorway,17500000.0,15190.97,1152.0,3,3,0.0,NaN,NaN,2.0,1,0,0,1,2026.0,flat
6484,Apartment For Sale - Small Complex Building,"bath island, karachi",Clifton,bath island,55000000.0,25045.54,2196.0,4,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
3021,Luxury Living by the Sea | 1 Bedroom with Brea...,"hmr waterfront, dha phase 8",DHA Defence,"hmr waterfront, dha phase 8",38000000.0,39460.02,963.0,1,2,1.0,NaN,40.0,1.0,4,1,1,0,NaN,flat
14576,540sq Ft 1BHK Luxury Flat Available On CASH/ I...,"paragon tower, bahria town - precinct 17",Bahria Town,"paragon tower, bahria town - precinct 17",2500000.0,4629.63,540.0,1,1,1.0,NaN,NaN,1.0,0,0,1,0,NaN,flat
17982,200 Square Yards House Up For Sale In Bahria T...,"bahria town - quaid villas, bahria town - prec...",Bahria Town,"bahria town - quaid villas, bahria town - prec...",23000000.0,12777.78,1800.0,3,3,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house
3110,400 SqYd House For Sale In Best Residential Lo...,"gulshan-e-iqbal - block 13/d, gulshan-e-iqbal",Gulshan-e-Iqbal,gulshan-e-iqbal - block 13/d,87500000.0,24305.56,3600.0,4,4,1.0,NaN,NaN,1.0,0,0,1,0,NaN,house
19612,Friend Heights Flat For Sale,"north nazimabad - block k, north nazimabad",North Nazimabad,north nazimabad - block k,18000000.0,10582.01,1701.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
13245,5-Year-Old 300-Yard Bungalow For Sale In DHA P...,"dha phase 7 extension, dha defence",DHA Defence,dha phase 7 extension,112500000.0,41666.67,2700.0,4,4,1.0,NaN,NaN,1.0,0,0,1,0,NaN,house
15928,Flat For Sell In Gulistan-E-Jauhar Block 15,"gulistan-e-jauhar - block 15, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 15,21000000.0,13972.06,1503.0,3,3,2.0,3.0,NaN,2.0,0,1,1,0,2026.0,flat
6503,250 YARDS DUPLEX HOUSE,"dha phase 4, dha defence",DHA Defence,dha phase 4,85000000.0,37777.78,2250.0,4,4,1.0,NaN,2.0,1.0,0,1,1,1,2025.0,house
22571,Own A House In 427 Square Yards Karachi,"askari 5 - sector h, askari 5",Cantt,"askari 5 - sector h, askari 5",101000000.0,26281.55,3843.0,5,5,1.0,NaN,1.0,5.0,0,1,1,1,NaN,house
17183,APARTMENT AVAILABLE FOR SALE IN ASKARI-VI,"askari 6, malir cantonment",Cantt,"askari 6, malir cantonment",43000000.0,14347.68,2997.0,4,4,1.0,4.0,13.0,2.0,3,1,1,1,2026.0,flat
8489,2 Bed Flat For Sale In Jinnah Tower Near Munaw...,"gulistan-e-jauhar - block 11, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 11,10500000.0,10510.51,999.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11971,Prime Location 2000 Square Feet Flat In Parsi ...,"parsi colony, jamshed town",Jamshed Town,parsi colony,42500000.0,21271.27,1998.0,4,4,1.0,NaN,NaN,0.0,1,0,0,1,NaN,flat
13830,AA Residencia Apartment Is Available,"callachi cooperative housing society, gulshan-...",Gulshan-e-Iqbal,"callachi cooperative housing society, gulshan-...",24500000.0,18148.15,1350.0,2,3,1.0,1.0,10.0,1.0,2,1,1,1,2025.0,flat
16549,Brand New Furnished Bungalow 1000 Yards For Sale,"khayaban-e-roomi, dha phase 8",DHA Defence,"khayaban-e-roomi, dha phase 8",560000000.0,62222.22,9000.0,6,6,0.0,NaN,NaN,0.0,0,2,1,1,NaN,house
12879,Semi Furnished 2 Bed DD | CHANCE DEAL FLAT FOR...,"falcon complex (afohs), malir cantonment",Cantt,"falcon complex (afohs), malir cantonment",28500000.0,17304.19,1647.0,2,3,1.0,10.0,16.0,1.0,1,0,1,0,2026.0,flat
840,Askari V Malir Cantt Sector J Apartment,"askari 5 - sector j, askari 5",Cantt,"askari 5 - sector j, askari 5",41500000.0,15370.37,2700.0,3,5,1.0,NaN,NaN,1.0,2,2,1,1,2025.0,flat
19567,Tower 9 READY TO MOVE 955sq ft 2Bed Lounge Fla...,"bahria apartments, bahria town karachi",Bahria Town,"bahria apartments, bahria town karachi",8900000.0,9329.14,954.0,2,2,1.0,NaN,NaN,1.0,0,0,1,0,NaN,flat
9475,Brand New Villa For Sale In Saima Villas 4 Bed...,"saima villas, karachi motorway",Super Highway,"saima villas, karachi motorway",15000000.0,13888.89,1080.0,3,3,1.0,NaN,2.0,4.0,0,1,1,1,2024.0,house
1565,House For Sale In Gulistan-E-Johar Block 2 Par...,"gulistan-e-jauhar - block 2, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 2,68000000.0,31481.48,2160.0,6,6,2.0,NaN,3.0,1.0,0,1,1,0,NaN,house
16360,Brand new flat in living condition,"the court twin towers, callachi cooperative ho...",Gulshan-e-Iqbal,"the court twin towers, callachi cooperative ho...",39000000.0,26915.11,1449.0,2,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11121,Brand New Construction House Is Available For ...,"dha phase 6, dha defence",DHA Defence,dha phase 6,350000000.0,64814.81,5400.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
3519,Chance Deal 150yards Slightly Used Bungalow In...,"dha phase 7 extension, dha defence",DHA Defence,dha phase 7 extension,75000000.0,55555.56,1350.0,4,5,2.0,NaN,2.0,1.0,0,1,1,0,2015.0,house
17565,120 Sq. Yd House For Sale In Andaleeb Society,"andaleeb cooperative housing society, scheme 33",Scheme 33,andaleeb cooperative housing society,27500000.0,25462.96,1080.0,4,6,2.0,NaN,2.0,0.0,0,0,1,1,2026.0,house
19154,House For Sale Brand New,"north nazimabad - block b, north nazimabad",North Nazimabad,north nazimabad - block b,55000000.0,30555.56,1800.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
5709,Prime Location 1000 Square Yards House Situate...,"delhi mercantile society, gulshan-e-iqbal town",Gulshan-e-Iqbal,"delhi mercantile society, gulshan-e-iqbal town",420000000.0,46666.67,9000.0,5,5,1.0,NaN,2.0,1.0,0,1,1,1,2024.0,house
3620,OCEAN GARDEN PHASE III - DUPLEXES PRE-LAUNCHIN...,"ocean gardens, scheme 33 - sector 44",Scheme 33,"ocean gardens, scheme 33 - sector 44",35000000.0,16271.50,2151.0,4,4,1.0,19.0,19.0,1.0,3,1,1,1,NaN,flat
20760,1475 Square Feet Flat Up For Sale In The Court...,"the court regency, dalmia cement factory road",Gulshan-e-Iqbal,"the court regency, dalmia cement factory road",32500000.0,22018.97,1476.0,2,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
2764,Embrace The Sophistication Of A Spacious 4 Bed...,"emaar crescent bay, dha phase 8",DHA Defence,"emaar crescent bay, dha phase 8",190000000.0,60664.11,3132.0,4,5,1.0,NaN,41.0,2.0,1,1,1,0,2023.0,flat
12077,Chance Deal 2 Bedrooms DD Apartment Available ...,"clifton - block 2, clifton",Clifton,clifton - block 2,18000000.0,10309.28,1746.0,2,2,1.0,NaN,6.0,0.0,1,0,1,0,NaN,flat
16411,Prime Location 240 Square Yards House For Grab...,"north nazimabad - block l, north nazimabad",North Nazimabad,north nazimabad - block l,50000000.0,23148.15,2160.0,6,6,3.0,NaN,2.0,1.0,0,1,1,1,2020.0,house
4916,CHANCE DEAL 350 SQUARE YARDS BRAND NEW BEHIND ...,"falcon complex new malir, malir",Malir,falcon complex new malir,94000000.0,29841.27,3150.0,4,5,1.0,NaN,2.0,1.0,0,1,1,1,NaN,house
7979,Ready To Buy A Prime Location Flat 1700 Square...,"bahadurabad, gulshan-e-iqbal town",Gulshan-e-Iqbal,"bahadurabad, gulshan-e-iqbal town",47500000.0,27924.75,1701.0,3,3,1.0,NaN,NaN,1.0,1,0,1,1,2025.0,flat
11996,One Unit Architect Designed Bungalow Available...,"gulistan-e-jauhar - block 16, gulistan-e-jauhar",Gulistan-e-Jauhar,gulistan-e-jauhar - block 16,90000000.0,22222.22,4050.0,4,4,0.0,NaN,NaN,1.0,0,1,1,1,2025.0,house
5046,4 BED DD FLAT FOR SALE IN GOHAR TOWER BLOCK 13E,"gulshan-e-iqbal - block 13/d-3, gulshan-e-iqbal",Gulshan-e-Iqbal,gulshan-e-iqbal - block 13/d-3,24000000.0,10928.96,2196.0,4,5,1.0,12.0,17.0,1.0,3,1,1,0,2022.0,flat
16627,500sq yd Luxury Villa FOR SALE. 2km from Entra...,"bahria town - precinct 4, bahria town karachi",Bahria Town,"bahria town - precinct 4, bahria town karachi",55000000.0,12222.22,4500.0,6,6,2.0,NaN,NaN,1.0,0,1,1,0,NaN,house
20717,Iqbal Villas 152sq Yard Close To Entrance Of B...,"bahria homes - iqbal villas, bahria town - pre...",Bahria Town,"bahria homes - iqbal villas, bahria town - pre...",19000000.0,13888.89,1368.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house
9770,Reasonably-Priced Prime Location 500 Square Ya...,"bahria hills, bahria town karachi",Bahria Town,"bahria hills, bahria town karachi",55000000.0,12222.22,4500.0,6,6,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
2946,Luxurious 3 Bedrooms Apartment For Sale In Tri...,"bath island, karachi",Clifton,bath island,87500000.0,38888.89,2250.0,3,4,1.0,1.0,10.0,2.0,1,1,1,1,2018.0,flat
16900,EMAAR OCEANFRONT: 02 BEDROOMS APARTMENT IN COR...,"emaar crescent bay, dha phase 8",DHA Defence,"emaar crescent bay, dha phase 8",52500000.0,34930.14,1503.0,2,2,2.0,NaN,NaN,1.0,3,1,1,0,2020.0,flat
10807,Brand New 120 Sq. yd. Bungalow For Sale,"naya nazimabad - block c, naya nazimabad",Naya Nazimabad,naya nazimabad - block c,42500000.0,39351.85,1080.0,4,4,1.0,NaN,2.0,0.0,0,0,1,1,2026.0,house
18674,Buying A Prime Location House In Karachi?,"shadman town - sector-14/a, shadman",North Nazimabad,"shadman town - sector-14/a, shadman",27500000.0,25462.96,1080.0,4,4,2.0,NaN,NaN,0.0,0,1,0,1,NaN,house
17359,3 Bed DD Available For Sale,"bahadurabad, gulshan-e-iqbal town",Gulshan-e-Iqbal,"bahadurabad, gulshan-e-iqbal town",15000000.0,11990.41,1251.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
9705,Indulge in waterfront luxury with this two bed...,"hmr waterfront, dha phase 8",DHA Defence,"hmr waterfront, dha phase 8",71300000.0,41916.52,1701.0,2,2,1.0,NaN,35.0,1.0,1,1,1,0,NaN,flat
13485,1880 Square Feet Flat Situated In Harmain Roya...,"harmain royal residency, gulshan-e-iqbal - blo...",Gulshan-e-Iqbal,"harmain royal residency, gulshan-e-iqbal - blo...",28000000.0,14885.70,1881.0,4,4,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
13970,Chance deal,"shadman town - sector-14/b, shadman",North Nazimabad,"shadman town - sector-14/b, shadman",3500000.0,5804.31,603.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
8851,House For Sale Karachi University Society Sect...,"karachi university housing society, scheme 33",Scheme 33,karachi university housing society,75000000.0,20833.33,3600.0,9,7,1.0,NaN,2.0,2.0,0,1,1,0,2016.0,house
20579,Prime Location In Naya Nazimabad Flat For sale...,"naya nazimabad, karachi",Naya Nazimabad,None,29300000.0,16525.66,1773.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
4826,Apartment For Sale,"kolachi cooperative housing society, gulshan-e...",Gulshan-e-Iqbal,"kolachi cooperative housing society, gulshan-e...",36500000.0,19312.17,1890.0,3,4,1.0,NaN,21.0,1.0,1,1,1,1,2026.0,flat
13694,1750 Sqft Renovated Three-Side Corner Apartmen...,"kda scheme 1, karachi",Gulshan-e-Iqbal,kda scheme 1,40000000.0,22909.51,1746.0,3,3,1.0,NaN,NaN,1.0,1,2,1,1,NaN,flat
2671,Saima Marina Residence | 3 Bed Luxury Apartmen...,"hmr waterfront, dha phase 8",DHA Defence,"hmr waterfront, dha phase 8",103200000.0,43933.59,2349.0,3,4,1.0,NaN,NaN,0.0,1,0,0,0,2026.0,flat
22428,Avail Yourself A Great 600 Square Yards House ...,"dha phase 6, dha defence",DHA Defence,dha phase 6,200000000.0,37037.04,5400.0,5,5,0.0,NaN,2.0,1.0,0,1,1,0,NaN,house
3505,Brand New Luxury Villa,"dha phase 8, dha defence",DHA Defence,dha phase 8,820000000.0,91111.11,9000.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
5739,1 BED + 1 LOUNCH MORDREN APARTMENT FOR SALE IN...,"surjani town, gadap town",Gadap,Surjani Town,2600000.0,6565.66,396.0,1,1,0.0,NaN,NaN,1.0,1,0,1,1,2020.0,flat
20734,HOT DEAL | LIMITED-TIME OPPORTUNITY EMAAR OCEA...,"emaar coral towers, emaar crescent bay",DHA Defence,"emaar coral towers, emaar crescent bay",65000000.0,35931.45,1809.0,2,4,1.0,13.0,26.0,2.0,3,1,1,1,2019.0,flat
5726,2 Bed DD Flat Available For Sale In Abuzar Gha...,"abuzar ghaffari cooperative housing society, s...",Scheme 33,"abuzar ghaffari cooperative housing society, s...",11500000.0,10921.18,1053.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
13368,3 BED DD FLAT FOR SALE,"amil colony, karachi",Jamshed Town,amil colony,32000000.0,22792.02,1404.0,3,3,1.0,NaN,3.0,1.0,1,1,1,1,2022.0,flat
8587,Burj Ul Harmain Brand New Project All Categori...,"burj-ul-harmain, university road",University Road,burj-ul-harmain,13500000.0,11278.20,1197.0,2,2,1.0,NaN,NaN,1.0,0,0,1,1,NaN,flat

In [29]:
bahria_mapping = {
    "bahria apartments, bahria town karachi": "Bahria Apartments",
    "bahria town - ali block, bahria town - precinct 12": "Ali Block",
    "bahria sports city, bahria town karachi": "Bahria Sports City",
    "bahria town - precinct 1, bahria town karachi": "Precinct 1",
    "bahria town - precinct 2, bahria town karachi": "Precinct 2",
    "bahria town - precinct 3, bahria town karachi": "Precinct 3",
    "bahria town - precinct 4, bahria town karachi": "Precinct 4",
    "bahria town - precinct 6, bahria town karachi": "Precinct 6",
    "bahria town - precinct 7, bahria town karachi": "Precinct 7",
    "bahria town - precinct 8, bahria town karachi": "Precinct 8",
    "bahria town - precinct 9, bahria town karachi": "Precinct 9",
    "bahria town - precinct 10-a, bahria town karachi": "Precinct 10A",
    "bahria town - precinct 10-b, bahria town karachi": "Precinct 10B",
    "bahria town - precinct 11-a, bahria town - precinct 11": "Precinct 11A",
    "bahria town - precinct 11, bahria town karachi": "Precinct 11A",
    "bahria town - precinct 11-b, bahria town - precinct 11": "Precinct 11B",
    "bahria town - precinct 12, bahria town karachi": "Precinct 12",
    "bahria town - precinct 15, bahria town karachi": "Precinct 15",
    "bahria town - precinct 16, bahria town karachi": "Precinct 16",
    "bahria town - precinct 17, bahria town karachi": "Precinct 17",
    "bahria town - precinct 18, bahria town karachi": "Precinct 18",
    "bahria town - precinct 19, bahria town karachi": "Precinct 19",
    "bahria town - precinct 27, bahria town karachi": "Precinct 27",
    "bahria town - precinct 31, bahria town karachi": "Precinct 31",

    "bahria homes - iqbal villas, bahria town - precinct 2": "Iqbal Villas",
    "bahria town - quaid villas, bahria town - precinct 2": "Quaid Villas",

    "bahria heights, bahria town karachi": "Bahria Heights",
    "bahria hills, bahria town karachi": "Bahria Hills",

    "bahria paradise, bahria town karachi": "Bahria Paradise",
    "bahria paradise - precinct 51, bahria paradise": "Bahria Paradise",

    "bahria town - precinct 35, bahria sports city": "Bahria Sports City",
    "bahria town - precinct 36, bahria sports city": "Bahria Sports City",

    "bahria golf city, bahria town karachi": "Golf City",
    "bahria town - precinct 20, bahria town karachi": "Golf City",

    "bahria town - precinct 30, bahria town karachi": "Precinct 31",

    "paragon tower, bahria town - precinct 17": "Private High-Rises",
    "dascon tower, bahria hills": "Private High-Rises",
    "dolce mall & signature residency, bahria town karachi": "Private High-Rises",

    "bahria town karachi": "Bahria Town",
}

df["sub_location"] = df["sub_location"].str.lower().str.strip().replace(bahria_mapping)

In [30]:
df.loc[
    df["sub_location"].isin(["precinct 18", "precinct 3", "golf city",'bahria town']),
    "sub_location"
] = np.nan

In [31]:
df[df["location"] == "Bahria Town"]["sub_location"].value_counts()

sub_location
Bahria Sports City    128
Bahria Apartments     120
Ali Block             109
Precinct 8             94
Precinct 10A           92
Private High-Rises     92
Precinct 11A           85
Precinct 31            84
Bahria Paradise        76
Precinct 11B           74
Quaid Villas           72
Precinct 1             70
Precinct 10B           68
Precinct 6             63
Bahria Town            62
Precinct 27            61
Iqbal Villas           60
Bahria Heights         57
Bahria Hills           54
Precinct 4             49
Precinct 16            37
Precinct 19            34
Precinct 17            26
Precinct 15            22
Precinct 12            21
Precinct 7             14
Precinct 2             13
Precinct 9             11
Precinct 18             5
Precinct 3              2
Golf City               2
Name: count, dtype: int64

In [32]:
df.groupby('location')['sub_location'].value_counts()

location            sub_location
Bahria Town         Bahria Sports City                                                                            128
                    Bahria Apartments                                                                             120
                    Ali Block                                                                                     109
                    Precinct 8                                                                                     94
                    Precinct 10A                                                                                   92
                    Private High-Rises                                                                             92
                    Precinct 11A                                                                                   85
                    Precinct 31                                                                                    84
                    Bahria Paradise                                                                                76
                    Precinct 11B                                                                                   74
                    Quaid Villas                                                                                   72
                    Precinct 1                                                                                     70
                    Precinct 10B                                                                                   68
                    Precinct 6                                                                                     63
                    Bahria Town                                                                                    62
                    Precinct 27                                                                                    61
                    Iqbal Villas                                                                                   60
                    Bahria Heights                                                                                 57
                    Bahria Hills                                                                                   54
                    Precinct 4                                                                                     49
                    Precinct 16                                                                                    37
                    Precinct 19                                                                                    34
                    Precinct 17                                                                                    26
                    Precinct 15                                                                                    22
                    Precinct 12                                                                                    21
                    Precinct 7                                                                                     14
                    Precinct 2                                                                                     13
                    Precinct 9                                                                                     11
                    Precinct 18                                                                                     5
                    Golf City                                                                                       2
                    Precinct 3                                                                                      2
Baldia Town         gulshan-e-mazdoor housing scheme, naval colony                                                  4
                    naval colony                                                                                    4
                    haroon bahria society - sector 1, hbchs - haroon bahria society                                 1
Bin Qasim Town      mateen complex                                                                                 34
                    shah latif town                                                                                 5
                    model colony                                                                                    4
                    pn welfare housing scheme                                                                       4
                    quaidabad                                                                                       4
                    gulshan-e-hadeed - phase 2, gulshan-e-hadeed                                                    2
                    gulshan-e-benazir - block a, gulshan-e-benazir township scheme                                  1
                    gulshan-e-benazir - block b, gulshan-e-benazir township scheme                                  1
                    gulshan-e-hadeed                                                                                1
                    port qasim                                                                                      1
Cantt               askari 6, malir cantonment                                                                    585
                    askari 5 - sector j, askari 5                                                                 404
                    askari 5, malir cantonment                                                                     83
                    navy housing scheme karsaz                                                                     77
                    askari 5 - sector h, askari 5                                                                  62
                    dohs phase 1, malir cantonment                                                                 51
                    gulshan-e-roomi, faisal cantonment                                                             43
                    askari 5 - sector f, askari 5                                                                  26
                    askari 5 - sector g, askari 5                                                                  24
                    saima presidency, malir cantonment                                                             24
                    navy housing scheme karsaz - phase 3, navy housing scheme karsaz                               23
                    malir cantonment                                                                               20
                    navy housing scheme karsaz - phase 1, navy housing scheme karsaz                               15
                    askari 5 - sector e, askari 5                                                                  14
                    cantt bazar, malir cantonment                                                                  14
                    navy housing scheme karsaz - phase 2, navy housing scheme karsaz                               13
                    dohs phase 2, malir cantonment                                                                 11
                    askari 5 - sector b, askari 5                                                                  10
                    p & t colony                                                                                   10
                    army officers housing society, faisal cantonment                                                9
                    falcon complex (afohs), malir cantonment                                                        8
                    pia housing society, faisal cantonment                                                          5
                    sohni serenity executive apartments, gulshan-e-roomi                                            5
                    askari 3, karachi cantonment                                                                    4
                    dadabhoy town, faisal cantonment                                                                3
                    navy housing scheme karsaz road, navy housing scheme karsaz                                     3
                    sohni golf view apartments, gulshan-e-roomi                                                     3
                    askari 2, karachi cantonment                                                                    2
                    askari 5 - sector c, askari 5                                                                   2
                    atap city, gulshan-e-roomi                                                                      2
                    falcon complex - air force officers housing scheme (afohs), faisal cantonment                   2
                    fariha excellency, malir cantonment                                                             2
                    askari 5 - sector d, askari 5                                                                   1
                    dr daud pota road                                                                               1
                    karachi cantonment                                                                              1
                    karsaz, faisal cantonment                                                                       1
Civil Lines         hsj icon                                                                                        3
Clifton             clifton - block 2                                                                             160
                    bath island                                                                                   127
                    clifton - block 9                                                                              94
                    clifton - block 8                                                                              89
                    clifton - block 1                                                                              87
                    clifton - block 4                                                                              52
                    frere town                                                                                     43
                    clifton - block 7                                                                              40
                    clifton - block 5                                                                              35
                    clifton - block 3                                                                              11
                    clifton - block 6                                                                              11
                    upper gizri, gizri                                                                              9
                    grand monarch seaside residency, clifton - block 1                                              6
                    delhi colony                                                                                    5
                    punjab colony                                                                                   3
                    chandio village, punjab colony                                                                  2
                    punjab chowrangi                                                                                2
                    dynasty tower, clifton - block 9                                                                1
                    gizri                                                                                           1
                    khaliq-uz-zaman road, clifton - block 8                                                         1
                    khayaban-e-iqbal                                                                                1
                    lower gizri, gizri                                                                              1
                    sawera grand, bath island                                                                       1
DHA City            dha city karachi                                                                               35
                    dha city - sector 1, dha city karachi                                                           6
                    ary laguna, dha city karachi                                                                    5
                    dha city - sector 14b, dha city - sector 14                                                     3
                    dha city - sector 3a, dha city - sector 3                                                       2
                    dha city - sector 3c, dha city - sector 3                                                       2
                    askari towers, dha city - sector 1                                                              1
                    dha city - cbd commercial, dha city karachi                                                     1
                    dha city - sector 3b, dha city - sector 3                                                       1
                    dha oasis - sector 1, dha oasis                                                                 1
                    dha oasis, dha city karachi                                                                     1
DHA Defence         dha phase 8                                                                                   743
                    dha phase 6                                                                                   656
                    hmr waterfront, dha phase 8                                                                   511
                    dha phase 5                                                                                   328
                    dha phase 7                                                                                   250
                    dha phase 4                                                                                   167
                    emaar the views, dha phase 8                                                                  158
                    emaar crescent bay, dha phase 8                                                               157
                    dha phase 7 extension                                                                         139
                    emaar panorama, dha phase 8                                                                   124
                    bukhari commercial area, dha phase 6                                                          122
                    emaar coral towers, emaar crescent bay                                                        107
                    emaar pearl towers, emaar crescent bay                                                        105
                    dha phase 2 extension                                                                          69
                    dha phase 1                                                                                    65
                    dha phase 8 - zone a, dha phase 8                                                              65
                    emaar reef towers, emaar crescent bay                                                          63
                    badar commercial area, dha phase 5                                                             57
                    dha phase 2                                                                                    50
                    emaar park edge, dha phase 8                                                                   50
                    creek vista, dha phase 8                                                                       49
                    nishat commercial area, dha phase 6                                                            47
                    al-murtaza commercial area, dha phase 8                                                        42
                    sea view apartments                                                                            39
                    ittehad commercial area, dha phase 6                                                           36
                    sehar commercial area, dha phase 7                                                             36
                    dha phase 8 - zone b, dha phase 8                                                              30
                    rahat commercial area, dha phase 6                                                             30
                    dha phase 5 extension, dha phase 5                                                             21
                    tauheed commercial area, dha phase 5                                                           16
                    zamzama commercial area, dha phase 5                                                           13
                    dha phase 8 extension, dha phase 8                                                             12
                    muslim commercial area, dha phase 6                                                            12
                    jami commercial area, dha phase 7                                                              10
                    navy housing scheme zamzama, zamzama                                                           10
                    darakhshan villas, dha phase 6                                                                  7
                    khalid commercial area, dha phase 7 extension                                                   7
                    the arkadians, dha phase 8 - zone b                                                             7
                    emaar ocean front, dha phase 8                                                                  6
                    saba commercial area, dha phase 5                                                               6
                    dha phase 8 - zone d, dha phase 8                                                               5
                    dha phase 2 - sunset boulevard commercial area, dha phase 2                                     4
                    dha phase 8 - zone e, dha phase 8                                                               4
                    emaar pearl tower 3, emaar crescent bay                                                         4
                    khayaban-e-ittehad road                                                                         4
                    khayaban-e-roomi, dha phase 8                                                                   4
                    the trillium, dha phase 5                                                                       4
                    zamzama                                                                                         4
                    khayaban-e-shahbaz, dha phase 6                                                                 3
                    stadium commercial area, dha phase 5                                                            3
                    zulfiqar commercial area, dha phase 8                                                           3
                    9th commercial street - dha phase 4, dha phase 4                                                1
                    beach terraces by metro, dha phase 8 - zone d                                                   1
                    brentwood signature 27, dha phase 7 extension                                                   1

In [33]:
df = df[df["location"] != "Baldia Town"].copy()

In [34]:
df.groupby('location')['sub_location'].value_counts()

location            sub_location
Bahria Town         Bahria Sports City                                                                            128
                    Bahria Apartments                                                                             120
                    Ali Block                                                                                     109
                    Precinct 8                                                                                     94
                    Precinct 10A                                                                                   92
                    Private High-Rises                                                                             92
                    Precinct 11A                                                                                   85
                    Precinct 31                                                                                    84
                    Bahria Paradise                                                                                76
                    Precinct 11B                                                                                   74
                    Quaid Villas                                                                                   72
                    Precinct 1                                                                                     70
                    Precinct 10B                                                                                   68
                    Precinct 6                                                                                     63
                    Bahria Town                                                                                    62
                    Precinct 27                                                                                    61
                    Iqbal Villas                                                                                   60
                    Bahria Heights                                                                                 57
                    Bahria Hills                                                                                   54
                    Precinct 4                                                                                     49
                    Precinct 16                                                                                    37
                    Precinct 19                                                                                    34
                    Precinct 17                                                                                    26
                    Precinct 15                                                                                    22
                    Precinct 12                                                                                    21
                    Precinct 7                                                                                     14
                    Precinct 2                                                                                     13
                    Precinct 9                                                                                     11
                    Precinct 18                                                                                     5
                    Golf City                                                                                       2
                    Precinct 3                                                                                      2
Bin Qasim Town      mateen complex                                                                                 34
                    shah latif town                                                                                 5
                    model colony                                                                                    4
                    pn welfare housing scheme                                                                       4
                    quaidabad                                                                                       4
                    gulshan-e-hadeed - phase 2, gulshan-e-hadeed                                                    2
                    gulshan-e-benazir - block a, gulshan-e-benazir township scheme                                  1
                    gulshan-e-benazir - block b, gulshan-e-benazir township scheme                                  1
                    gulshan-e-hadeed                                                                                1
                    port qasim                                                                                      1
Cantt               askari 6, malir cantonment                                                                    585
                    askari 5 - sector j, askari 5                                                                 404
                    askari 5, malir cantonment                                                                     83
                    navy housing scheme karsaz                                                                     77
                    askari 5 - sector h, askari 5                                                                  62
                    dohs phase 1, malir cantonment                                                                 51
                    gulshan-e-roomi, faisal cantonment                                                             43
                    askari 5 - sector f, askari 5                                                                  26
                    askari 5 - sector g, askari 5                                                                  24
                    saima presidency, malir cantonment                                                             24
                    navy housing scheme karsaz - phase 3, navy housing scheme karsaz                               23
                    malir cantonment                                                                               20
                    navy housing scheme karsaz - phase 1, navy housing scheme karsaz                               15
                    askari 5 - sector e, askari 5                                                                  14
                    cantt bazar, malir cantonment                                                                  14
                    navy housing scheme karsaz - phase 2, navy housing scheme karsaz                               13
                    dohs phase 2, malir cantonment                                                                 11
                    askari 5 - sector b, askari 5                                                                  10
                    p & t colony                                                                                   10
                    army officers housing society, faisal cantonment                                                9
                    falcon complex (afohs), malir cantonment                                                        8
                    pia housing society, faisal cantonment                                                          5
                    sohni serenity executive apartments, gulshan-e-roomi                                            5
                    askari 3, karachi cantonment                                                                    4
                    dadabhoy town, faisal cantonment                                                                3
                    navy housing scheme karsaz road, navy housing scheme karsaz                                     3
                    sohni golf view apartments, gulshan-e-roomi                                                     3
                    askari 2, karachi cantonment                                                                    2
                    askari 5 - sector c, askari 5                                                                   2
                    atap city, gulshan-e-roomi                                                                      2
                    falcon complex - air force officers housing scheme (afohs), faisal cantonment                   2
                    fariha excellency, malir cantonment                                                             2
                    askari 5 - sector d, askari 5                                                                   1
                    dr daud pota road                                                                               1
                    karachi cantonment                                                                              1
                    karsaz, faisal cantonment                                                                       1
Civil Lines         hsj icon                                                                                        3
Clifton             clifton - block 2                                                                             160
                    bath island                                                                                   127
                    clifton - block 9                                                                              94
                    clifton - block 8                                                                              89
                    clifton - block 1                                                                              87
                    clifton - block 4                                                                              52
                    frere town                                                                                     43
                    clifton - block 7                                                                              40
                    clifton - block 5                                                                              35
                    clifton - block 3                                                                              11
                    clifton - block 6                                                                              11
                    upper gizri, gizri                                                                              9
                    grand monarch seaside residency, clifton - block 1                                              6
                    delhi colony                                                                                    5
                    punjab colony                                                                                   3
                    chandio village, punjab colony                                                                  2
                    punjab chowrangi                                                                                2
                    dynasty tower, clifton - block 9                                                                1
                    gizri                                                                                           1
                    khaliq-uz-zaman road, clifton - block 8                                                         1
                    khayaban-e-iqbal                                                                                1
                    lower gizri, gizri                                                                              1
                    sawera grand, bath island                                                                       1
DHA City            dha city karachi                                                                               35
                    dha city - sector 1, dha city karachi                                                           6
                    ary laguna, dha city karachi                                                                    5
                    dha city - sector 14b, dha city - sector 14                                                     3
                    dha city - sector 3a, dha city - sector 3                                                       2
                    dha city - sector 3c, dha city - sector 3                                                       2
                    askari towers, dha city - sector 1                                                              1
                    dha city - cbd commercial, dha city karachi                                                     1
                    dha city - sector 3b, dha city - sector 3                                                       1
                    dha oasis - sector 1, dha oasis                                                                 1
                    dha oasis, dha city karachi                                                                     1
DHA Defence         dha phase 8                                                                                   743
                    dha phase 6                                                                                   656
                    hmr waterfront, dha phase 8                                                                   511
                    dha phase 5                                                                                   328
                    dha phase 7                                                                                   250
                    dha phase 4                                                                                   167
                    emaar the views, dha phase 8                                                                  158
                    emaar crescent bay, dha phase 8                                                               157
                    dha phase 7 extension                                                                         139
                    emaar panorama, dha phase 8                                                                   124
                    bukhari commercial area, dha phase 6                                                          122
                    emaar coral towers, emaar crescent bay                                                        107
                    emaar pearl towers, emaar crescent bay                                                        105
                    dha phase 2 extension                                                                          69
                    dha phase 1                                                                                    65
                    dha phase 8 - zone a, dha phase 8                                                              65
                    emaar reef towers, emaar crescent bay                                                          63
                    badar commercial area, dha phase 5                                                             57
                    dha phase 2                                                                                    50
                    emaar park edge, dha phase 8                                                                   50
                    creek vista, dha phase 8                                                                       49
                    nishat commercial area, dha phase 6                                                            47
                    al-murtaza commercial area, dha phase 8                                                        42
                    sea view apartments                                                                            39
                    ittehad commercial area, dha phase 6                                                           36
                    sehar commercial area, dha phase 7                                                             36
                    dha phase 8 - zone b, dha phase 8                                                              30
                    rahat commercial area, dha phase 6                                                             30
                    dha phase 5 extension, dha phase 5                                                             21
                    tauheed commercial area, dha phase 5                                                           16
                    zamzama commercial area, dha phase 5                                                           13
                    dha phase 8 extension, dha phase 8                                                             12
                    muslim commercial area, dha phase 6                                                            12
                    jami commercial area, dha phase 7                                                              10
                    navy housing scheme zamzama, zamzama                                                           10
                    darakhshan villas, dha phase 6                                                                  7
                    khalid commercial area, dha phase 7 extension                                                   7
                    the arkadians, dha phase 8 - zone b                                                             7
                    emaar ocean front, dha phase 8                                                                  6
                    saba commercial area, dha phase 5                                                               6
                    dha phase 8 - zone d, dha phase 8                                                               5
                    dha phase 2 - sunset boulevard commercial area, dha phase 2                                     4
                    dha phase 8 - zone e, dha phase 8                                                               4
                    emaar pearl tower 3, emaar crescent bay                                                         4
                    khayaban-e-ittehad road                                                                         4
                    khayaban-e-roomi, dha phase 8                                                                   4
                    the trillium, dha phase 5                                                                       4
                    zamzama                                                                                         4
                    khayaban-e-shahbaz, dha phase 6                                                                 3
                    stadium commercial area, dha phase 5                                                            3
                    zulfiqar commercial area, dha phase 8                                                           3
                    9th commercial street - dha phase 4, dha phase 4                                                1
                    beach terraces by metro, dha phase 8 - zone d                                                   1
                    brentwood signature 27, dha phase 7 extension                                                   1
                    dha phase 3                                                                                     1
                    dha phase 8 - zone c, dha phase 8                                                               1
                    khayaban-e-qasim, dha phase 8                                                                   1

In [35]:
# This section handles Keep Only Mateen Complex As A Sub-Location.df.loc[
    (df["location"] == "Bin Qasim Town") &
    (df["sub_location"] != "mateen complex"),
    "sub_location"
] = None

In [36]:
import numpy as np

cantt_mapping = {
    # This section handles Askari.    "askari 6, malir cantonment": "Askari 6",
    "askari 5, malir cantonment": "Askari 5",
    "askari 5 - sector j, askari 5": "Askari 5",
    "askari 5 - sector h, askari 5": "Askari 5",
    "askari 5 - sector f, askari 5": "Askari 5",
    "askari 5 - sector g, askari 5": "Askari 5",
    "askari 5 - sector e, askari 5": "Askari 5",
    "askari 5 - sector b, askari 5": "Askari 5",
    "askari 5 - sector c, askari 5": "Askari 5",
    "askari 5 - sector d, askari 5": "Askari 5",

    "askari 3, karachi cantonment": np.nan,
    "askari 2, karachi cantonment": np.nan,

    # This section handles Dohs.    "dohs phase 1, malir cantonment": "DOHS Phase 1",
    "dohs phase 2, malir cantonment": "DOHS Phase 2",

    # This section handles Navy Housing Scheme Karsaz.    "navy housing scheme karsaz": "Navy Housing Scheme Karsaz",
    "navy housing scheme karsaz - phase 1, navy housing scheme karsaz": "Navy Housing Scheme Karsaz",
    "navy housing scheme karsaz - phase 2, navy housing scheme karsaz": "Navy Housing Scheme Karsaz",
    "navy housing scheme karsaz - phase 3, navy housing scheme karsaz": "Navy Housing Scheme Karsaz",
    "navy housing scheme karsaz road, navy housing scheme karsaz": "Navy Housing Scheme Karsaz",

    # This section handles Gulshan-E-Roomi.    "gulshan-e-roomi, faisal cantonment": "Gulshan-e-Roomi",

    # This section handles Rare Sub-Locations.    "saima presidency, malir cantonment": np.nan,
    "cantt bazar, malir cantonment": np.nan,
    "army officers housing society, faisal cantonment": np.nan,
    "falcon complex (afohs), malir cantonment": np.nan,
    "pia housing society, faisal cantonment": np.nan,
    "sohni serenity executive apartments, gulshan-e-roomi": np.nan,
    "dadabhoy town, faisal cantonment": np.nan,
    "sohni golf view apartments, gulshan-e-roomi": np.nan,
    "atap city, gulshan-e-roomi": np.nan,
    "falcon complex - air force officers housing scheme (afohs), faisal cantonment": np.nan,
    "fariha excellency, malir cantonment": np.nan,
    "karsaz, faisal cantonment": np.nan,
}

mask = df["location"] == "Cantt"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(cantt_mapping)
)

In [37]:
df[df['location']=='Cantt']['sub_location'].value_counts()

sub_location
Askari 5                      626
Askari 6                      585
Navy Housing Scheme Karsaz    131
DOHS Phase 1                   51
Gulshan-e-Roomi                43
malir cantonment               20
DOHS Phase 2                   11
p & t colony                   10
karachi cantonment              1
dr daud pota road               1
Name: count, dtype: int64

In [38]:
import numpy as np

# This section handles Clifton Sub-Location Cleaning.
clifton_mapping = {

    # This section handles Clifton Blocks.    "clifton - block 1": "Clifton Block 1",
    "clifton - block 2": "Clifton Block 2",
    "clifton - block 3": "Clifton Block 3",
    "clifton - block 4": "Clifton Block 4",
    "clifton - block 5": "Clifton Block 5",
    "clifton - block 6": "Clifton Block 6",
    "clifton - block 7": "Clifton Block 7",
    "clifton - block 8": "Clifton Block 8",
    "clifton - block 9": "Clifton Block 9",


    # This section handles Bath Island.    "bath island": "Bath Island",
    "sawera grand, bath island": "Bath Island",


    # This section handles Frere Town.    "frere town": "Frere Town",


    # This section handles Gizri.    "gizri": "Gizri",
    "upper gizri, gizri": "Gizri",
    "lower gizri, gizri": "Gizri",


    # Rare / insufficient samples → Missing
    "grand monarch seaside residency, clifton - block 1": np.nan,
    "delhi colony": np.nan,
    "punjab colony": np.nan,
    "chandio village, punjab colony": np.nan,
    "punjab chowrangi": np.nan,
    "dynasty tower, clifton - block 9": np.nan,
    "khaliq-uz-zaman road, clifton - block 8": np.nan,
    "khayaban-e-iqbal": np.nan,
}


# This section handles Apply Only To Clifton.mask = df["location"] == "Clifton"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(clifton_mapping)
)

In [39]:
df[df['location']=='Clifton']['sub_location'].value_counts()

sub_location
Clifton Block 2    160
Bath Island        128
Clifton Block 9     94
Clifton Block 8     89
Clifton Block 1     87
Clifton Block 4     52
Frere Town          43
Clifton Block 7     40
Clifton Block 5     35
Clifton Block 6     11
Clifton Block 3     11
Gizri               11
Name: count, dtype: int64

In [40]:
import numpy as np

# This section handles Dha City Sub-Location Cleaning.
dha_city_mapping = {

    "dha city karachi": np.nan,
    "dha city - sector 1, dha city karachi": np.nan,
    "ary laguna, dha city karachi": np.nan,
    "dha city - sector 14b, dha city - sector 14": np.nan,
    "dha city - sector 3a, dha city - sector 3": np.nan,
    "dha city - sector 3b, dha city - sector 3": np.nan,
    "dha city - sector 3c, dha city - sector 3": np.nan,
    "askari towers, dha city - sector 1": np.nan,
    "dha city - cbd commercial, dha city karachi": np.nan,
    "dha oasis - sector 1, dha oasis": np.nan,
    "dha oasis, dha city karachi": np.nan,

}

# This section handles Apply Only To Dha City.mask = df["location"] == "DHA City"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(dha_city_mapping)
)

C:\Users\FCC\AppData\Local\Temp\ipykernel_11112\934569580.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(dha_city_mapping)

In [41]:
import numpy as np

# This section handles Dha Defence Sub-Location Cleaning.
dha_mapping = {

    # This section handles Dha Phase 8.    "dha phase 8": "DHA Phase 8",
    "hmr waterfront, dha phase 8": "DHA Phase 8",
    "emaar the views, dha phase 8": "DHA Phase 8",
    "emaar crescent bay, dha phase 8": "DHA Phase 8",
    "emaar panorama, dha phase 8": "DHA Phase 8",
    "emaar coral towers, emaar crescent bay": "DHA Phase 8",
    "emaar pearl towers, emaar crescent bay": "DHA Phase 8",
    "emaar reef towers, emaar crescent bay": "DHA Phase 8",
    "emaar park edge, dha phase 8": "DHA Phase 8",
    "creek vista, dha phase 8": "DHA Phase 8",
    "al-murtaza commercial area, dha phase 8": "DHA Phase 8",
    "dha phase 8 - zone a, dha phase 8": "DHA Phase 8",
    "dha phase 8 - zone b, dha phase 8": "DHA Phase 8",
    "dha phase 8 - zone c, dha phase 8": "DHA Phase 8",
    "dha phase 8 - zone d, dha phase 8": "DHA Phase 8",
    "dha phase 8 - zone e, dha phase 8": "DHA Phase 8",
    "the arkadians, dha phase 8 - zone b": "DHA Phase 8",
    "emaar ocean front, dha phase 8": "DHA Phase 8",
    "khayaban-e-roomi, dha phase 8": "DHA Phase 8",
    "zulfiqar commercial area, dha phase 8": "DHA Phase 8",
    "peninsula commercial area, dha phase 8": "DHA Phase 8",
    "khayaban-e-qasim, dha phase 8": "DHA Phase 8",


    # This section handles Dha Phase 6.    "dha phase 6": "DHA Phase 6",
    "bukhari commercial area, dha phase 6": "DHA Phase 6",
    "nishat commercial area, dha phase 6": "DHA Phase 6",
    "ittehad commercial area, dha phase 6": "DHA Phase 6",
    "rahat commercial area, dha phase 6": "DHA Phase 6",
    "muslim commercial area, dha phase 6": "DHA Phase 6",
    "shahbaz commercial area, dha phase 6": "DHA Phase 6",
    "khayaban-e-shahbaz, dha phase 6": "DHA Phase 6",



    # This section handles Dha Phase 5.    "dha phase 5": "DHA Phase 5",
    "badar commercial area, dha phase 5": "DHA Phase 5",
    "tauheed commercial area, dha phase 5": "DHA Phase 5",
    "zamzama commercial area, dha phase 5": "DHA Phase 5",
    "saba commercial area, dha phase 5": "DHA Phase 5",
    "stadium commercial area, dha phase 5": "DHA Phase 5",
    "the trillium, dha phase 5": "DHA Phase 5",


    # This section handles Dha Phase 7.    "dha phase 7": "DHA Phase 7",
    "sehar commercial area, dha phase 7": "DHA Phase 7",
    "jami commercial area, dha phase 7": "DHA Phase 7",


    # This section handles Dha Phase 7 Extension.    "dha phase 7 extension": "DHA Phase 7 Extension",
    "khalid commercial area, dha phase 7 extension": "DHA Phase 7 Extension",
    "brentwood signature 27, dha phase 7 extension": "DHA Phase 7 Extension",


    # This section handles Dha Phase 4.    "dha phase 4": "DHA Phase 4",
    "9th commercial street - dha phase 4, dha phase 4": "DHA Phase 4",


    # This section handles Dha Phase 2.    "dha phase 2": "DHA Phase 2",
    "dha phase 2 extension": "DHA Phase 2 Extension",
    "dha phase 2 - sunset boulevard commercial area, dha phase 2": "DHA Phase 2",


    # This section handles Dha Phase 1.    "dha phase 1": "DHA Phase 1",


    # This section handles Other Extensions.    "dha phase 5 extension, dha phase 5": "DHA Phase 5 Extension",
    "dha phase 8 extension, dha phase 8": "DHA Phase 8 Extension",


    # This section handles Keep But Rare.    "sea view apartments": np.nan,
    "navy housing scheme zamzama, zamzama": np.nan,
    "zamzama": np.nan,
    "khayaban-e-ittehad road": np.nan,
    "royal defence tower": np.nan,
    "emaar pearl tower 3, emaar crescent bay": "DHA Phase 8",
    "beach terraces by metro, dha phase 8 - zone d": "DHA Phase 8",


    # This section handles Very Low Samples.    "dha phase 3": np.nan,
}


# This section handles Apply Only To Dha Defence.mask = df["location"] == "DHA Defence"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(dha_mapping)
)

In [42]:
df[df['location']=='DHA Defence']['sub_location'].value_counts()

sub_location
DHA Phase 8                       2241
DHA Phase 6                        907
DHA Phase 5                        427
DHA Phase 7                        296
DHA Phase 4                        168
DHA Phase 7 Extension              147
DHA Phase 2 Extension               69
DHA Phase 1                         65
DHA Phase 2                         54
DHA Phase 5 Extension               21
DHA Phase 8 Extension               12
darakhshan villas, dha phase 6       7
Name: count, dtype: int64

In [43]:
# This section handles Defence View Sub-Location.defence_view_mapping = {

    "defence view society": np.nan,
    "defence view phase 1, defence view society": np.nan,
    "defence view phase 2, defence view society": np.nan,
    "defence view phase 3, defence view society": np.nan,
    "diamond residency, defence view phase 2": np.nan,

}

# This section handles Apply Only To Defence View.mask = df["location"] == "Defence View"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(defence_view_mapping)
)

C:\Users\FCC\AppData\Local\Temp\ipykernel_11112\755705997.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(defence_view_mapping)

In [44]:
import numpy as np

# This section handles Federal B Area Sub-Location Cleaning.
federal_b_area_mapping = {

    # This section handles Keep Important Blocks.    "federal b area - block 10": "Federal B Area Block 10",
    "federal b area - block 12": "Federal B Area Block 12",
    "federal b area - block 13": "Federal B Area Block 13",
    "federal b area - block 11": "Federal B Area Block 11",
    "federal b area - block 14": "Federal B Area Block 14",
    "federal b area - block 16": "Federal B Area Block 16",
    "federal b area - block 9": "Federal B Area Block 9",
    "federal b area - block 15": "Federal B Area Block 15",
    "federal b area - block 8": "Federal B Area Block 8",
    "federal b area - block 19": "Federal B Area Block 19",
    "federal b area - block 6": "Federal B Area Block 6",
    "federal b area - block 20": "Federal B Area Block 20",
    "federal b area - block 7": "Federal B Area Block 7",
    "aisha manzil": "Federal B Area Block 7",
    "shahrah-e-pakistan": "Shahrah-e-Pakistan",

    # This section handles Low count -> NaN.    "federal b area - block 5": np.nan,
    "yaseenabad, gulberg town": np.nan,
    "federal b area - block 18": np.nan,
    "de comforts, federal b area - block 8": np.nan,
    "federal b area - block 4": np.nan,
    "gulshan-e-shameem, gulberg town": np.nan,
    "federal b area - block 17": np.nan,
    "federal b area - block 21": np.nan,
    "azizabad, gulberg town": np.nan,
    "dastgir colony": np.nan,
    "federal b area - block 2": np.nan,
    "federal b area - block 22": np.nan,
    "federal b area - block 3": np.nan,
    "hussainabad, gulberg town": np.nan,
}


# This section handles Apply Only To Federal B Area.mask = df["location"] == "Federal B Area"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(federal_b_area_mapping)
)

In [45]:
df[df['location']=='Federal B Area']['sub_location'].value_counts()

sub_location
Federal B Area Block 10    75
Federal B Area Block 12    54
Federal B Area Block 13    41
Federal B Area Block 11    29
Federal B Area Block 14    23
Federal B Area Block 9     19
Federal B Area Block 16    19
Federal B Area Block 15    18
Federal B Area Block 8     18
Federal B Area Block 19    17
Federal B Area Block 6     12
Federal B Area Block 7     11
Shahrah-e-Pakistan         10
Federal B Area Block 20    10
Name: count, dtype: int64

In [46]:
df[df['location']=='Gadap']['sub_location'].value_counts()

sub_location
gulshan-e-maymar    468
surjani town        273
memon goth           55
Name: count, dtype: int64

In [47]:
df[df['location']=='Gulistan-e-Jauhar']['sub_location'].value_counts()

sub_location
gulistan-e-jauhar - block 15                                         181
gulistan-e-jauhar - block 14                                         152
gulistan-e-jauhar - block 13                                         132
gulistan-e-jauhar - block 12                                         117
gulistan-e-jauhar - block 17                                         114
gulistan-e-jauhar - block 3-a                                        108
gulistan-e-jauhar - block 7                                          100
gulistan-e-jauhar - block 18                                          98
gulistan-e-jauhar - block 2                                           88
gulistan-e-jauhar - block 19                                          72
gulistan-e-jauhar - block 16                                          64
gulistan-e-jauhar - block 3                                           57
askari 4                                                              34
gulistan-e-jauhar - block 1                                           32
gulistan-e-jauhar - block 10                                          32
gulistan-e-jauhar - block 4                                           28
gulistan-e-jauhar - block 11                                          26
gulistan-e-jauhar - block 20                                          25
fatima golf residency                                                 25
gulistan-e-jauhar - block 16-a                                        14
kings cottages, gulistan-e-jauhar - block 7                           13
gulistan-e-jauhar - block 9                                           11
kings classic, gulistan-e-jauhar - block 7                             9
latifi cooperative housing society                                     8
kings presidency                                                       8
safoora goth                                                           8
kings tower, gulistan-e-jauhar - block 15                              8
gulistan-e-jauhar - block 8-a                                          8
kda overseas bungalows                                                 7
bisma greens, gulistan-e-jauhar - block 15                             7
rana residency, gulistan-e-jauhar - block 16                           7
rufi lake drive apartments                                             6
gulistan-e-jauhar - block 5                                            6
gulistan-e-jauhar - block 1-a                                          5
kamran chowrangi                                                       5
saima mall & residency                                                 5
gulistan-e-jauhar - block 8                                            4
gulistan-e-jauhar - block 6                                            4
al minal tower, gulistan-e-jauhar - block 3                            3
works cooperative housing society, gulistan-e-jauhar - block 4         3
kings highrise apartments, gulistan-e-jauhar - block 2                 3
rufi rose petals                                                       2
sachal goth                                                            2
gulistan-e-jauhar - block 10-a                                         2
gulistan-e-jauhar - block 9-a                                          2
rana presidency, gulistan-e-jauhar - block 1                           2
palm residency                                                         2
sindh baloch housing society                                           2
goldline royal apartments, gulistan-e-jauhar - block 16-a              1
rabia city                                                             1
petal residency, gulistan-e-jauhar - block 9-a                         1
abbas town                                                             1
falaknaz golden pebbles                                                1
pioneer cottages                                                       1
saadabad cooperative housing society, gulistan-e-jauhar - block 5      1
zohra nagar                                                            1
mehran banglows town                                                   1
Name: count, dtype: int64

In [48]:
# This section handles Move Misclassified Gulistan-E-Jauhar Areas To Scheme 33.
scheme33_mapping = {
    "sachal goth": "Sachal Goth",
    "sindh baloch housing society": "Sindh Baloch Housing Society",
    "abbas town": "Abbas Town",
    "falaknaz golden pebbles": "Falaknaz Golden Pebbles",
    "pioneer cottages": "Pioneer Cottages",
    "zohra nagar": "Zohra Nagar",
}

mask = (
    (df["location"] == "Gulistan-e-Jauhar") &
    (df["sub_location"].isin(scheme33_mapping.keys()))
)

# This section handles Change Parent Location.df.loc[mask, "location"] = "Scheme 33"

# This section handles Standardize Sub-Location Names.df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(scheme33_mapping)
)

In [49]:
# This section handles Gulistan-E-Jauhar Sub-Location Cleaning.
jauhar_mapping = {

    # This section handles Blocks.    "gulistan-e-jauhar - block 1": "Block 1",
    "gulistan-e-jauhar - block 1-a": "Block 1",

    "gulistan-e-jauhar - block 2": "Block 2",

    "gulistan-e-jauhar - block 3": "Block 3",
    "gulistan-e-jauhar - block 3-a": "Block 3A",

    "gulistan-e-jauhar - block 4": "Block 4",

    "gulistan-e-jauhar - block 5": "Block 5",

    "gulistan-e-jauhar - block 6": "Block 6",

    "gulistan-e-jauhar - block 7": "Block 7",

    "gulistan-e-jauhar - block 8": "Block 8",
    "gulistan-e-jauhar - block 8-a": "Block 8",

    "gulistan-e-jauhar - block 9": "Block 9",
    "gulistan-e-jauhar - block 9-a": "Block 9",

    "gulistan-e-jauhar - block 10": "Block 10",
    "gulistan-e-jauhar - block 10-a": "Block 10",

    "gulistan-e-jauhar - block 11": "Block 11",
    "gulistan-e-jauhar - block 12": "Block 12",
    "gulistan-e-jauhar - block 13": "Block 13",
    "gulistan-e-jauhar - block 14": "Block 14",
    "gulistan-e-jauhar - block 15": "Block 15",
    "gulistan-e-jauhar - block 16": "Block 16",
    "gulistan-e-jauhar - block 16-a": "Block 16A",
    "gulistan-e-jauhar - block 17": "Block 17",
    "gulistan-e-jauhar - block 18": "Block 18",
    "gulistan-e-jauhar - block 19": "Block 19",
    "gulistan-e-jauhar - block 20": "Block 20",

    # This section handles Independent Areas.    "askari 4": "Askari 4",
    "latifi cooperative housing society": "Latifi Cooperative Housing Society",
    "kda overseas bungalows": "KDA Overseas Bungalows",
    "safoora goth": "Safoora Goth",

    # This section handles Merge Projects Into Parent Blocks.    "fatima golf residency": "Block 18",
    "kings cottages, gulistan-e-jauhar - block 7": "Block 7",
    "kings classic, gulistan-e-jauhar - block 7": "Block 7",
    "kings presidency": "Block 3A",
    "kings tower, gulistan-e-jauhar - block 15": "Block 15",
    "bisma greens, gulistan-e-jauhar - block 15": "Block 15",
    "rana residency, gulistan-e-jauhar - block 16": "Block 16",
    "rufi lake drive apartments": "Block 18",
    "saima mall & residency": "Block 10",
    "al minal tower, gulistan-e-jauhar - block 3": "Block 3A",
    "kings highrise apartments, gulistan-e-jauhar - block 2": "Block 2",
    "works cooperative housing society, gulistan-e-jauhar - block 4": "Block 4",
    "palm residency": "Block 11",
    "rana presidency, gulistan-e-jauhar - block 1": "Block 1",
    "rufi rose petals": "Block 18",
    "goldline royal apartments, gulistan-e-jauhar - block 16-a": "Block 19",
    "petal residency, gulistan-e-jauhar - block 9-a": "Block 9",
    "kamran chowrangi": "Block 11",
    "rabia city": "Block 18",
    "mehran banglows town": "Block 19",
    "saadabad cooperative housing society, gulistan-e-jauhar - block 5": "Block 5",
}

# This section handles Apply Only To Gulistan-E-Jauhar.mask = df["location"] == "Gulistan-e-Jauhar"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(jauhar_mapping)
)

In [50]:
df[df['location']=='Gulistan-e-Jauhar']['sub_location'].value_counts()

sub_location
Block 15                              196
Block 14                              152
Block 13                              132
Block 18                              132
Block 7                               122
Block 3A                              119
Block 12                              117
Block 17                              114
Block 2                                91
Block 19                               74
Block 16                               71
Block 3                                57
Block 1                                39
Block 10                               39
Askari 4                               34
Block 11                               33
Block 4                                31
Block 20                               25
Block 9                                14
Block 16A                              14
Block 8                                12
Latifi Cooperative Housing Society      8
Safoora Goth                            8
KDA Overseas Bungalows                  7
Block 5                                 7
Block 6                                 4
Name: count, dtype: int64

In [51]:
# This section handles Gulshan-E-Iqbal Town Sub-Location Cleaning.
gulshan_mapping = {

    # This section handles Parent.    "gulshan-e-iqbal town": np.nan,

    # This section handles Official Blocks.    "gulshan-e-iqbal - block 1": "Block 1",
    "gulshan-e-iqbal - block 2": "Block 2",
    "gulshan-e-iqbal - block 3": "Block 3",
    "gulshan-e-iqbal - block 4": "Block 4",
    "gulshan-e-iqbal - block 4a": "Block 4A",
    "gulshan-e-iqbal - block 5": "Block 5",
    "gulshan-e-iqbal - block 6": "Block 6",
    "gulshan-e-iqbal - block 7": "Block 7",
    "gulshan-e-iqbal - block 8": "Block 8",
    "gulshan-e-iqbal - block 9": "Block 9",
    "gulshan-e-iqbal - block 10": "Block 10",
    "gulshan-e-iqbal - block 10-a": "Block 10A",
    "gulshan-e-iqbal - block 11": "Block 11",

    "gulshan-e-iqbal - block 13": "Block 13",
    "gulshan-e-iqbal - block 13/a": "Block 13A",
    "gulshan-e-iqbal - block 13/b": "Block 13B",
    "gulshan-e-iqbal - block 13/c": "Block 13C",
    "gulshan-e-iqbal - block 13/d": "Block 13D",
    "gulshan-e-iqbal - block 13/d-1": "Block 13D1",
    "gulshan-e-iqbal - block 13-d2": "Block 13D2",
    "gulshan-e-iqbal - block 13/d-3": "Block 13D3",
    "gulshan-e-iqbal - block 13/g": "Block 13G",

    "gulshan-e-iqbal - block 14": "Block 14",
    "gulshan-e-iqbal - block 15": "Block 15",
    "gulshan-e-iqbal - block 16": "Block 16",
    "gulshan-e-iqbal - block 17": "Block 17",
    "gulshan-e-iqbal - block 18": "Block 18",
    "gulshan-e-iqbal - block 19": "Block 19",

    # This section handles Independent Societies / Areas.    "callachi cooperative housing society, gulshan-e-iqbal - block 10-a": "Callachi Cooperative Housing Society",
    "kolachi cooperative housing society, gulshan-e-iqbal town": "Callachi Cooperative Housing Society",

    "bahadurabad, gulshan-e-iqbal town": "Bahadurabad",
    "dhoraji colony, gulshan-e-iqbal town": "Dhoraji Colony",
    "sharfabad, gulshan-e-iqbal town": "Sharfabad",

    "kda scheme 1": "KDA Scheme 1",
    "kda scheme 1 extension": "KDA Scheme 1 Extension",
    "kda officers society, gulshan-e-iqbal town": "KDA Officers Society",

    "mohammad ali society, gulshan-e-iqbal town": "Mohammad Ali Society",
    "adamjee nagar, gulshan-e-iqbal town": "Adamjee Nagar",
    "cp berar society, gulshan-e-iqbal town": "CP Berar Society",
    "national stadium colony, gulshan-e-iqbal town": "National Stadium Colony",
    "dawood society, gulshan-e-iqbal town": "Dawood Society",

    "gulshan-e-jamal, gulshan-e-iqbal town": "Gulshan-e-Jamal",
    "gulshan-e-jamal - block b, gulshan-e-jamal": "Gulshan-e-Jamal",
    "gulshan-e-jamal - block c, gulshan-e-jamal": "Gulshan-e-Jamal",

    "al-hilal society": "Al-Hilal Society",
    "pak ideal cooperative housing society": "Pak Ideal Cooperative Housing Society",
    "faran cooperative housing society, gulshan-e-iqbal town": "Faran Cooperative Housing Society",
    "al hamra society, gulshan-e-iqbal town": "Al Hamra Society",
    "bangalore town, gulshan-e-iqbal town": "Bangalore Town",
    "delhi mercantile society, gulshan-e-iqbal town": "Delhi Mercantile Society",
    "central govt coop housing society, gulshan-e-iqbal town": "Central Govt Cooperative Housing Society",
    "karachi memon society, gulshan-e-iqbal town": "Karachi Memon Society",

    "khokan cooperative housing society": "Kokan Cooperative Housing Society",
    "kokan cooperative housing society, gulshan-e-iqbal town": "Kokan Cooperative Housing Society",
    "kokan society, gulshan-e-iqbal town": "Kokan Cooperative Housing Society",

    # Apartment Projects → Parent Area
    "harmain royal residency, gulshan-e-iqbal - block 1": "Block 1",
    "the court twin towers, callachi cooperative housing society": "Callachi Cooperative Housing Society",
    "shayan iconic palace, callachi cooperative housing society": "Callachi Cooperative Housing Society",
    "bhayani heights, gulshan-e-iqbal - block 4": "Block 4",

    "kings shaes residency, jauhar chowrangi road": "Block 10A",
    "royal 8 icon, gulshan-e-iqbal town": "Block 13D2",
    "sidra capital, jauhar chowrangi road": "Block 10A",

    # This section handles Roads / Landmarks.    "shaz residency, gulshan-e-iqbal town": np.nan,
    "the court regency, dalmia cement factory road": "Block 10A",
    "alamgir road, gulshan-e-iqbal town": "Bahadurabad",
    "siraj-ud-daula road": "Bahadurabad",
    "dalmia cement factory road": "Block 10A",
    "chandni chowk society": "Block 14",
    "ghausia colony, gulshan-e-iqbal town": "Block 1",
    "maskan chowrangi": "Block 7",
    "national cement employees housing, gulshan-e-iqbal town": "Block 10A",
    "new town police lines, gulshan-e-iqbal town": "Block 14",
    "overseas society, gulshan-e-iqbal town": "Block 16",
}

# This section handles Apply Only To Gulshan-E-Iqbal Town.mask = df["location"] == "Gulshan-e-Iqbal"
df.loc[mask, "location"] = "Gulshan-e-Iqbal Town"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(gulshan_mapping)
)

In [52]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Callachi Cooperative Housing Society        302
Block 1                                     194
Block 10A                                   144
Bahadurabad                                 121
Block 4                                      92
Block 7                                      91
KDA Scheme 1                                 87
Block 5                                      84
Block 2                                      78
Block 13D2                                   76
Block 13D1                                   65
Dhoraji Colony                               59
Block 13D                                    58
Block 6                                      57
Sharfabad                                    47
Block 17                                     44
KDA Officers Society                         43
Block 13A                                    41
Block 3                                      39
Block 13C                                    39
Block 11                                     34
Block 13D3                                   32
Block 13B                                    24
Block 16                                     23
Block 10                                     21
Mohammad Ali Society                         18
Block 9                                      17
Block 19                                     17
Block 14                                     16
Adamjee Nagar                                16
National Stadium Colony                      14
cp barar society, gulshan-e-iqbal town       14
Gulshan-e-Jamal                              13
Block 4A                                     13
Dawood Society                               13
KDA Scheme 1 Extension                       11
Block 13                                     10
Block 8                                       8
Pak Ideal Cooperative Housing Society         8
Al-Hilal Society                              8
Faran Cooperative Housing Society             7
Block 18                                      6
Al Hamra Society                              4
Bangalore Town                                4
Delhi Mercantile Society                      4
Kokan Cooperative Housing Society             3
Block 15                                      2
Central Govt Cooperative Housing Society      2
Block 13G                                     2
Karachi Memon Society                         2
stadium road                                  1
Name: count, dtype: int64

In [53]:
counts = df.loc[df["location"] == "Gulshan-e-Iqbal Town", "sub_location"].value_counts()
rare = counts[counts < 10].index

df.loc[
    (df["location"] == "Gulshan-e-Iqbal Town") &
    (df["sub_location"].isin(rare)),
    "sub_location"
] = np.nan

In [54]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Callachi Cooperative Housing Society      302
Block 1                                   194
Block 10A                                 144
Bahadurabad                               121
Block 4                                    92
Block 7                                    91
KDA Scheme 1                               87
Block 5                                    84
Block 2                                    78
Block 13D2                                 76
Block 13D1                                 65
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 17                                   44
KDA Officers Society                       43
Block 13A                                  41
Block 13C                                  39
Block 3                                    39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  24
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Block 14                                   16
Adamjee Nagar                              16
National Stadium Colony                    14
cp barar society, gulshan-e-iqbal town     14
Dawood Society                             13
Gulshan-e-Jamal                            13
Block 4A                                   13
KDA Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [55]:
mapping = {
    # This section handles Pechs.    "pechs block 2, pechs": "PECHS",
    "pechs block 3, pechs": "PECHS",
    "pechs block 6, pechs": "PECHS",
    "allama iqbal road, pechs": "PECHS",
    "maniya cooperative housing society, pechs": "PECHS",

    # This section handles Nearby Societies.    "darul aman society": "PECHS",
    "gulistan-e-zafar": "PECHS",
    "jinnah society": "PECHS",
    "maqboolabad society": "PECHS",

    # This section handles Smchs.    "sindhi muslim society - block a, smchs - sindhi muslim society": "SMCHS - Sindhi Muslim Society",
    "sindhi muslim society - block b, smchs - sindhi muslim society": "SMCHS - Sindhi Muslim Society",

    # This section handles Karachi Administration Employees Society (KAECHS).    "kaechs - block 2, karachi administration employees society": "Karachi Administration Employees Society",
    "kaechs - block 3, karachi administration employees society": "Karachi Administration Employees Society",
    "kaechs - block 4, karachi administration employees society": "Karachi Administration Employees Society",
    "kaechs - block 5, karachi administration employees society": "Karachi Administration Employees Society",
    "kaechs - block 8, karachi administration employees society": "Karachi Administration Employees Society",
    "kaechs - block 9, karachi administration employees society": "Karachi Administration Employees Society",

    # This section handles Mehmoodabad.    "mehmoodabad number 1, mehmoodabad": "Mehmoodabad",
    "mehmoodabad number 3, mehmoodabad": "Mehmoodabad",
    "mehmoodabad number 4, mehmoodabad": "Mehmoodabad",
    "mehmoodabad number 5, mehmoodabad": "Mehmoodabad",

    "akhtar colony": "Mehmoodabad",

    # This section handles Soldier Bazar.    "soldier bazar no 1, soldier bazar": "Soldier Bazar",
    "soldier bazar no 2, soldier bazar": "Soldier Bazar",
    "soldier bazar no 3, soldier bazar": "Soldier Bazar",

    # This section handles Jamshed Road.    "guru mandir chorangi": "Jamshed Road",
    "jamshed quarters": "Jamshed Road",
    "numaish chowrangi": "Jamshed Road",

    # This section handles Garden East.    "central jacob lines": "Garden East",
    "gulshan-e-zahoor": "Garden East",

    # This section handles Shaheed Millat Road.    "jamaluddin afghani road": "Shaheed Millat Road",

    # This section handles Baloch Colony.    "azam basti": "Baloch Colony",
}

mask = df["location"] == "Jamshed Town"
df.loc[mask, "sub_location"] = df.loc[mask, "sub_location"].replace(mapping)

In [56]:
df[df['location']=='Jamshed Town']['sub_location'].value_counts()

sub_location
PECHS                                           260
shaheed millat road                             178
khalid bin walid road                           124
jamshed road                                     57
tariq road                                       39
karachi administration employees society         38
amir khusro                                      36
garden east                                      32
amil colony                                      29
hill park                                        27
SMCHS - Sindhi Muslim Society                    26
pechs                                            24
parsi colony                                     21
smchs - sindhi muslim society                    19
soldier bazar                                    17
cosmopolitan society                             17
Mehmoodabad                                      17
shahra-e-qaideen                                 14
muslimabad society                               12
defence skyline, shaheed-e-millat expressway     12
Karachi Administration Employees Society          8
Soldier Bazar                                     5
manzoor colony                                    4
pib colony                                        4
Jamshed Road                                      4
baloch colony                                     2
Garden East                                       2
mehmoodabad                                       2
Baloch Colony                                     1
Shaheed Millat Road                               1
Name: count, dtype: int64

In [57]:
mapping = {
    # This section handles Capitalization.    "pechs": "PECHS",
    "smchs - sindhi muslim society": "SMCHS - Sindhi Muslim Society",
    "karachi administration employees society": "Karachi Administration Employees Society",
    "soldier bazar": "Soldier Bazar",
    "garden east": "Garden East",
    "jamshed road": "Jamshed Road",
    "mehmoodabad": "Mehmoodabad",
    "shaheed millat road": "Shaheed Millat Road",
    "baloch colony": "Baloch Colony",
}

mask = df["location"] == "Jamshed Town"
df.loc[mask, "sub_location"] = df.loc[mask, "sub_location"].replace(mapping)

In [58]:
df[df['location']=='Jamshed Town']['sub_location'].value_counts()

sub_location
PECHS                                           284
Shaheed Millat Road                             179
khalid bin walid road                           124
Jamshed Road                                     61
Karachi Administration Employees Society         46
SMCHS - Sindhi Muslim Society                    45
tariq road                                       39
amir khusro                                      36
Garden East                                      34
amil colony                                      29
hill park                                        27
Soldier Bazar                                    22
parsi colony                                     21
Mehmoodabad                                      19
cosmopolitan society                             17
shahra-e-qaideen                                 14
defence skyline, shaheed-e-millat expressway     12
muslimabad society                               12
pib colony                                        4
manzoor colony                                    4
Baloch Colony                                     3
Name: count, dtype: int64

In [59]:
df = df[
    ~df["sub_location"].isin([
        "pib colony",
        "manzoor colony",
        "Baloch Colony",
        "baloch colony"
    ])
].reset_index(drop=True)

In [60]:
df[df['location']=='Jamshed Town']['sub_location'].value_counts()

sub_location
PECHS                                           284
Shaheed Millat Road                             179
khalid bin walid road                           124
Jamshed Road                                     61
Karachi Administration Employees Society         46
SMCHS - Sindhi Muslim Society                    45
tariq road                                       39
amir khusro                                      36
Garden East                                      34
amil colony                                      29
hill park                                        27
Soldier Bazar                                    22
parsi colony                                     21
Mehmoodabad                                      19
cosmopolitan society                             17
shahra-e-qaideen                                 14
defence skyline, shaheed-e-millat expressway     12
muslimabad society                               12
Name: count, dtype: int64

In [61]:
mapping = {
    # This section handles Established Projects.    "burj al-jinnah": "Metropolis Residency",   # Same corridor, similar apartment market

    # This section handles Very Small Projects.    "ibrahim heaven": "Roomi Residency",
    "burj-ul-ohad": "Roomi Residency",
    "metropolis signature": "Metropolis Residency",
}

mask = df["location"] == "Jinnah Avenue"
df.loc[mask, "sub_location"] = df.loc[mask, "sub_location"].replace(mapping)

In [62]:
df[df['location']=='Jinnah Avenue']['sub_location'].value_counts()

sub_location
metropolis residency    102
aman golf view           38
roomi residency          27
Metropolis Residency     10
Roomi Residency           6
Name: count, dtype: int64

In [63]:
mapping = {
    "metropolis residency": "Metropolis Residency",
    "roomi residency": "Roomi Residency",
}

mask = df["location"] == "Jinnah Avenue"
df.loc[mask, "sub_location"] = df.loc[mask, "sub_location"].replace(mapping)

In [64]:
df[df['location']=='Jinnah Avenue']['sub_location'].value_counts()

sub_location
Metropolis Residency    112
aman golf view           38
Roomi Residency          33
Name: count, dtype: int64

In [65]:
df = df[df["location"] != "Kemari"].reset_index(drop=True)

In [66]:
mapping_korangi = {

    # This section handles Allahwala Town.    "allahwala town - sector 31-g, allahwala town": "Allahwala Town",
    "allahwala town - sector 31-b, allahwala town": "Allahwala Town",
    "mbchs - makhdoom bilawal society": "Allahwala Town",

    # This section handles Qayyumabad.    "grove residency, qayyumabad": "Qayyumabad",
    "qayyumabad - d area, qayyumabad": "Qayyumabad",
    "qayyumabad": "Qayyumabad",

    # This section handles Kda Employees Society.    "kda employees society - korangi": "KDA Employees Society",
    "kda employees society - sector 31-c1, kda employees society - korangi": "KDA Employees Society",
    "kda employees society - sector 31-c2, kda employees society - korangi": "KDA Employees Society",
    "p & t housing society": "KDA Employees Society",

    # This section handles Korangi Industrial Area.    "korangi - sector 31-a, korangi industrial area": "Korangi Industrial Area",
    "korangi - sector 31-g": "Korangi Industrial Area",
    "korangi industrial area": "Korangi Industrial Area",
    "korangi - sector 33, korangi industrial area": "Korangi Industrial Area",
    "korangi - sector 33/c, korangi - sector 33": "Korangi Industrial Area",
    "korangi - sector 34-1": "Korangi Industrial Area",
    "korangi - sector 50-a": "Korangi Industrial Area",
    "korangi road": "Korangi Industrial Area",
    "mehran town sector 6b, mehran town": "Korangi Industrial Area",
    "zaman town": "Korangi Industrial Area",

    # This section handles Bhittai Colony.    "bhittai colony": "Bhittai Colony",
    "bhittai colony - block d, bhittai colony": "Bhittai Colony",

    # This section handles Korangi Creek Cantonment.    "korangi creek cantonment": "Korangi Creek Cantonment",

    # This section handles Landhi Town.    "landhi town sector 37 c, landhi": "Landhi Town",
    "gulshan-e-millat - block a, gulshan-e-millat": "Landhi Town",
}

In [67]:
mask = df["location"] == "Korangi"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping_korangi)
)

In [68]:
df[df['location']=='Korangi']['sub_location'].value_counts()

sub_location
Allahwala Town              88
allahwala town              25
Korangi Industrial Area     23
KDA Employees Society       16
Qayyumabad                  16
Bhittai Colony               6
Korangi Creek Cantonment     2
Landhi Town                  2
Name: count, dtype: int64

In [69]:
df = df[
    ~(
        (df["location"] == "Korangi") &
        (df["sub_location"].isin([
            "Bhittai Colony",
            "Korangi Creek Cantonment",
            "Landhi Town"
        ]))
    )
].reset_index(drop=True)

In [70]:
df = df[df["location"] != "Liaquatabad"].reset_index(drop=True)

In [71]:
mapping_malir = {

    # This section handles Falcon Complex.    "falcon complex new malir": "Falcon Complex New Malir",

    # This section handles Model Colony.    "model colony - malir": "Model Colony",

    # This section handles Falaknaz Projects.    "falaknaz dreams": "Falaknaz",
    "falaknaz presidency": "Falaknaz",
    "falaknaz excellency": "Falaknaz",

    # This section handles Malir Link To Super Highway Projects.    "cantt view lodges, malir link to super highway": "Malir Link To Super Highway",
    "saima jinnah icon, malir link to super highway": "Malir Link To Super Highway",
    "shanzil exclusive, malir link to super highway": "Malir Link To Super Highway",
    "saima paari avenue, malir link to super highway": "Malir Link To Super Highway",
    "burj ul imran apartments, malir link to super highway": "Malir Link To Super Highway",
    "karachi revenue judicial chs, malir link to super highway": "Malir Link To Super Highway",
    "roomi icon, malir link to super highway": "Malir Link To Super Highway",
    "hakeem villas, malir link to super highway": "Malir Link To Super Highway",

    # This section handles Saima Projects.    "saima elite villas": "Saima Projects",

    # This section handles Malir Town Residency.    "malir town residency": "Malir Town Residency",
    "malir town residency - phase 2, malir town residency": "Malir Town Residency",

    # This section handles Airport.    "airport road": "Airport",
    "airport": "Airport",

    # This section handles Malir Areas.    "jamia millia road": "Jamia Millia Road",
    "malir halt": "Malir Halt",
    "saudabad": "Saudabad",
    "kazimabad": "Kazimabad",
    "jaffar-e-tayyar": "Jaffar-e-Tayyar",
    "khokhrapar": "Khokhrapar",
    "malir kalaboard": "Malir Kalaboard",
}

In [72]:
    # # ==================================
    # # Small Societies / Projects
    # # ==================================
    # "gohar complex, liaquat avenue": "Malir",
    # "tariq bin ziyad housing society": "Malir",
    # "tipu sultan society": "Malir",
    # "anwar-e-ibrahim": "Malir",
    # "millat garden": "Malir",
    # "moinabad": "Malir",
    # "rafi pride 2, gulshan-e-rafi": "Malir",
    # "al amin society": "Malir",
    # "ghazi town - block 2, ghazi town": "Malir",
    # "gulistan-e-malir": "Malir",
    # "moria goth": "Malir",
    # "raza residency": "Malir",

In [73]:
mask = df["location"] == "Malir"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping_malir)
)

In [74]:
df[df['location']=='Malir']['sub_location'].value_counts()

sub_location
Falcon Complex New Malir            516
Falaknaz                            118
Model Colony                         96
Malir Link To Super Highway          79
Airport                              45
Saima Projects                       37
golden town                          16
Jamia Millia Road                    14
Malir Town Residency                 10
tariq bin ziyad housing society       6
anwar-e-ibrahim                       6
tipu sultan society                   5
gohar complex, liaquat avenue         4
Saudabad                              4
Malir Halt                            4
Kazimabad                             3
moinabad                              2
rafi pride 2, gulshan-e-rafi          2
millat garden                         2
Jaffar-e-Tayyar                       2
raza residency                        1
al amin society                       1
Khokhrapar                            1
gulistan-e-malir                      1
Malir Kalaboard                       1
moria goth                            1
ghazi town - block 2, ghazi town      1
Name: count, dtype: int64

In [75]:
import numpy as np

# This section handles Malir Mapping.
mapping_malir = {

    # This section handles Falaknaz Projects.    "falaknaz dreams": "Falaknaz",
    "falaknaz presidency": "Falaknaz",
    "falaknaz excellency": "Falaknaz",

    # This section handles Malir Link To Super Highway.    "cantt view lodges, malir link to super highway": "Malir Link To Super Highway",
    "saima jinnah icon, malir link to super highway": "Malir Link To Super Highway",
    "shanzil exclusive, malir link to super highway": "Malir Link To Super Highway",
    "saima paari avenue, malir link to super highway": "Malir Link To Super Highway",
    "burj ul imran apartments, malir link to super highway": "Malir Link To Super Highway",
    "karachi revenue judicial chs, malir link to super highway": "Malir Link To Super Highway",
    "roomi icon, malir link to super highway": "Malir Link To Super Highway",
    "hakeem villas, malir link to super highway": "Malir Link To Super Highway",

    "rafi pride 2, gulshan-e-rafi": "Malir Link To Super Highway",
    "ghazi town - block 2, ghazi town": "Malir Link To Super Highway",


    # This section handles Airport.    "airport road": "Airport",
    "airport": "Airport",


    # This section handles Saima Projects.    "saima elite villas": "Saima Projects",


    # This section handles Malir Town Residency.    "malir town residency": "Malir Town Residency",
    "malir town residency - phase 2, malir town residency": "Malir Town Residency",
    "millat garden": "Malir Town Residency",
    "raza residency": "Malir Town Residency",


    # This section handles Jamia Millia Road.    "jamia millia road": "Jamia Millia Road",
    "anwar-e-ibrahim": "Jamia Millia Road",


    # This section handles Old Malir Belt.    "kazimabad": "Saudabad",
    "jaffar-e-tayyar": "Saudabad",
    "moinabad": "Saudabad",
    "khokhrapar": "Saudabad",
    "malir kalaboard": "Saudabad",


    # This section handles Keep Separate Projects.    "tariq bin ziyad housing society": "Tariq Bin Ziyad Housing Society",
    "tipu sultan society": "Tipu Sultan Society",


    # This section handles Preserve names (not Malir -> Malir).    "gohar complex, liaquat avenue": "Gohar Complex",
    "malir halt": "Malir Halt",
    "gulistan-e-malir": "Gulistan-e-Malir",
}


# This section handles Apply Mapping Only On Malir.mask = df["location"] == "Malir"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping_malir)
)


# Remove rare Malir sub_locations
# This section handles count < 10.
malir_counts = (
    df[df["location"] == "Malir"]["sub_location"]
    .value_counts()
)

rare_malir = malir_counts[malir_counts < 10].index


df.loc[
    (df["location"] == "Malir") &
    (df["sub_location"].isin(rare_malir)),
    "sub_location"
] = np.nan

In [76]:
df[df['location']=='Malir']['sub_location'].value_counts()

sub_location
Falcon Complex New Malir       516
Falaknaz                       118
Model Colony                    96
Malir Link To Super Highway     82
Airport                         45
Saima Projects                  37
Jamia Millia Road               20
golden town                     16
Malir Town Residency            13
Name: count, dtype: int64

In [77]:
# Remove "naya nazimabad - " prefix from sub_location
mask = df["location"] == "Naya Nazimabad"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .str.replace("naya nazimabad - ", "", regex=False)
)

In [78]:
df[df['location']=='Naya Nazimabad']['sub_location'].value_counts()

sub_location
block a    95
block c    87
block d    68
block b    67
block m    23
Name: count, dtype: int64

In [79]:
mapping_nazimabad = {

    # This section handles Nazimabad No. 1.    "nazimabad 1": "Nazimabad 1",
    "nazimabad 1 - block e, nazimabad 1": "Nazimabad 1",
    "nazimabad 1 - block j, nazimabad 1": "Nazimabad 1",

    # This section handles Nazimabad No. 2.    "nazimabad 2": "Nazimabad 2",

    # This section handles Nazimabad No. 3.    "nazimabad 3": "Nazimabad 3",
    "nazimabad 3 - block e, nazimabad 3": "Nazimabad 3",
    "nazimabad 3 - block c, nazimabad 3": "Nazimabad 3",
    "nazimabad 3 - block f, nazimabad 3": "Nazimabad 3",

    # This section handles Nazimabad No. 4.    "nazimabad 4": "Nazimabad 4",
    "nazimabad 4 - block c, nazimabad 4": "Nazimabad 4",
    "nazimabad 4 - block d, nazimabad 4": "Nazimabad 4",

    # This section handles Nazimabad No. 5.    "nazimabad 5": "Nazimabad 5",
    "nazimabad - block 5c": "Nazimabad 5",
    "nazimabad - block 5e": "Nazimabad 5",
}

In [80]:
mask = df["location"] == "Nazimabad"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping_nazimabad)
)

In [81]:
df[df['location']=='Nazimabad']['sub_location'].value_counts()

sub_location
Nazimabad 4    22
Nazimabad 3    20
Nazimabad 5     9
Nazimabad 1     8
Nazimabad 2     5
Name: count, dtype: int64

In [82]:
df[df['location']=='North Karachi']['sub_location'].value_counts()

sub_location
north karachi - sector 9                                     26
north karachi - sector 11b                                   24
north karachi - sector 11a                                   23
north karachi - sector 7-d3                                  20
bufferzone - sector 15-a/2, buffer zone                      20
bufferzone - sector 15-a/4, buffer zone                      18
bufferzone - sector 15-a/1, buffer zone                      17
bufferzone - sector 15-a/5, buffer zone                      16
north karachi - sector 8                                     14
north karachi - sector 10                                    14
bufferzone - sector 15-a/3, buffer zone                      11
buffer zone                                                  11
north karachi - sector 7d-2                                  10
north karachi - sector 5-c/1, north karachi - sector 5-c     10
north karachi - sector 5l                                    10
north karachi - sector 11-c/2                                 7
north karachi - sector 5-c/4, north karachi - sector 5-c      7
north karachi - sector 11-c/1                                 7
north karachi - sector 7-d1                                   7
north karachi - sector 5-k                                    6
bufferzone - sector 16-a, buffer zone                         6
north karachi - sector 5-c/3, north karachi - sector 5-c      6
north karachi - sector 11-c/3                                 5
north karachi - sector 11e                                    5
north karachi - sector 3                                      5
royal tower, shahra-e-usman                                   4
new karachi                                                   4
north karachi - sector 5-h                                    4
north karachi - sector 11k                                    4
bufferzone - sector 15-b, buffer zone                         3
north karachi - sector 11i                                    2
new karachi - sector 5-a/3, new karachi - sector 5-a          2
north karachi - sector 5-c                                    2
abu zar ghaffari, new karachi                                 2
north karachi - sector 11c                                    2
serena mobile mall, buffer zone                               1
north karachi - sector 15-a/4, north karachi - sector 15a     1
al-ghazi villas                                               1
north karachi - sector 11l                                    1
north karachi - sector 1-a/4                                  1
north karachi - sector 5-b1                                   1
north karachi - sector 7-d4                                   1
north karachi - sector 14a                                    1
north karachi - sector 4                                      1
north karachi - sector 5-c/2, north karachi - sector 5-c      1
new karachi - sector 5-m, new karachi                         1
north karachi - sector 5-b2                                   1
north karachi - sector 15-b                                   1
north karachi - sector 5m                                     1
new karachi - sector 5-j, new karachi                         1
Name: count, dtype: int64

In [83]:
mapping_north_karachi = {

    # This section handles Buffer Zone.    "bufferzone": "Buffer Zone",
    "buffer zone": "Buffer Zone",

    "bufferzone - sector 15-a/1, buffer zone": "Buffer Zone",
    "bufferzone - sector 15-a/2, buffer zone": "Buffer Zone",
    "bufferzone - sector 15-a/3, buffer zone": "Buffer Zone",
    "bufferzone - sector 15-a/4, buffer zone": "Buffer Zone",
    "bufferzone - sector 15-a/5, buffer zone": "Buffer Zone",

    "bufferzone - sector 15-b, buffer zone": "Buffer Zone",
    "north karachi - sector 15-b": "Buffer Zone",
    "north karachi - sector 15-a/4, north karachi - sector 15a": "Buffer Zone",

    "bufferzone - sector 16-a, buffer zone": "Buffer Zone",
    "serena mobile mall, buffer zone": "Buffer Zone",


    # This section handles New Karachi.    "new karachi": "New Karachi",
    "abu zar ghaffari, new karachi": "New Karachi",
    "new karachi - sector 5-a/3, new karachi - sector 5-a": "New Karachi",
    "new karachi - sector 5-j, new karachi": "New Karachi",
    "new karachi - sector 5-m, new karachi": "New Karachi",


    # This section handles North Karachi Sector 11.    "north karachi - sector 11b": "North Karachi Sector 11",
    "north karachi - sector 11a": "North Karachi Sector 11",
    "north karachi - sector 11-c/1": "North Karachi Sector 11",
    "north karachi - sector 11-c/2": "North Karachi Sector 11",
    "north karachi - sector 11-c/3": "North Karachi Sector 11",
    "north karachi - sector 11c": "North Karachi Sector 11",
    "north karachi - sector 11e": "North Karachi Sector 11",
    "north karachi - sector 11i": "North Karachi Sector 11",
    "north karachi - sector 11k": "North Karachi Sector 11",
    "north karachi - sector 11l": "North Karachi Sector 11",


    # This section handles North Karachi Sector 5.    "north karachi - sector 5-c": "North Karachi Sector 5",
    "north karachi - sector 5-c/1, north karachi - sector 5-c": "North Karachi Sector 5",
    "north karachi - sector 5-c/2, north karachi - sector 5-c": "North Karachi Sector 5",
    "north karachi - sector 5-c/3, north karachi - sector 5-c": "North Karachi Sector 5",
    "north karachi - sector 5-c/4, north karachi - sector 5-c": "North Karachi Sector 5",

    "north karachi - sector 5l": "North Karachi Sector 5",
    "north karachi - sector 5-k": "North Karachi Sector 5",
    "north karachi - sector 5-h": "North Karachi Sector 5",
    "north karachi - sector 5m": "North Karachi Sector 5",
    "north karachi - sector 5-b1": "North Karachi Sector 5",
    "north karachi - sector 5-b2": "North Karachi Sector 5",


    # This section handles North Karachi Sector 7.    "north karachi - sector 7-d3": "North Karachi Sector 7",
    "north karachi - sector 7d-2": "North Karachi Sector 7",
    "north karachi - sector 7-d1": "North Karachi Sector 7",
    "north karachi - sector 7-d4": "North Karachi Sector 7",


    # This section handles North Karachi Sector 9 / 10 / 8.    "north karachi - sector 9": "North Karachi Sector 9",
    "north karachi - sector 10": "North Karachi Sector 10",
    "north karachi - sector 8": "North Karachi Sector 8",


    # This section handles North Karachi Sector 3.    "north karachi - sector 3": "North Karachi Sector 3",


    # This section handles General North Karachi.    "north karachi - sector 1-a/4": "North Karachi",
    "north karachi - sector 4": "North Karachi",
    "north karachi - sector 14a": "North Karachi",
    "al-ghazi villas": "North Karachi",
    "royal tower, shahra-e-usman": "North Karachi",
}

In [84]:
mask = df["location"] == "North Karachi"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping_north_karachi)
)

In [85]:
df[df['location']=='North Karachi']['sub_location'].value_counts()

sub_location
Buffer Zone                105
North Karachi Sector 11     80
North Karachi Sector 5      49
North Karachi Sector 7      38
North Karachi Sector 9      26
North Karachi Sector 10     14
North Karachi Sector 8      14
New Karachi                 10
North Karachi                8
North Karachi Sector 3       5
Name: count, dtype: int64

In [86]:
drop_north_karachi = [
    "North Karachi",
    "North Karachi Sector 3"
]

df = df[
    ~df["sub_location"].isin(drop_north_karachi)
]

In [87]:
df[df['location']=='North Karachi']['sub_location'].value_counts()

sub_location
Buffer Zone                105
North Karachi Sector 11     80
North Karachi Sector 5      49
North Karachi Sector 7      38
North Karachi Sector 9      26
North Karachi Sector 10     14
North Karachi Sector 8      14
New Karachi                 10
Name: count, dtype: int64

In [88]:
mask = df["location"] == "Northern Bypass"
df.loc[mask, "sub_location"] = np.nan

In [89]:
df.loc[df["location"] == "Saddar", "sub_location"] = np.nan

In [90]:
import numpy as np

mapping = {

    # This section handles Remove Generic Gulzar-E-Hijri.    "gulzar-e-hijri": np.nan,


    # This section handles Saadi Town.    "saadi town - block 1, saadi town": "Saadi Town",
    "saadi town - block 2, saadi town": "Saadi Town",
    "saadi town - block 3, saadi town": "Saadi Town",
    "saadi town - block 4, saadi town": "Saadi Town",
    "saadi town - block 5, saadi town": "Saadi Town",
    "saadi town - block 6, saadi town": "Saadi Town",
    "saadi town - block 7, saadi town": "Saadi Town",


    # This section handles Saadi Garden.    "saadi garden - block 1, saadi garden": "Saadi Garden",
    "saadi garden - block 2, saadi garden": "Saadi Garden",
    "saadi garden - block 3, saadi garden": "Saadi Garden",
    "saadi garden - block 4, saadi garden": "Saadi Garden",
    "saadi garden - block 5, saadi garden": "Saadi Garden",


    # This section handles Punjabi Saudagar.    "sector 31 - punjabi saudagar city phase 2, scheme 33 - sector 31":
        "Punjabi Saudagar Society",

    "sector 32 - punjabi saudagar city phase 1, scheme 33 - sector 32":
        "Punjabi Saudagar Society",

    "sector 25-a - punjabi saudagar multi purpose society, scheme 33 - sector 25-a":
        "Punjabi Saudagar Society",

    "punjabi saudagar society phase 2, scheme 33 - sector 50":
        "Punjabi Saudagar Society",

    "punjabi saudagaran phase 1, sector 25-a - punjabi saudagar multi purpose society":
        "Punjabi Saudagar Society",

    "prestige one, scheme 33 - sector 25-a":
        "Punjabi Saudagar Society",

    "sector 25-a - karachi bar association cooperative housing society, scheme 33 - sector 25-a":
        "Punjabi Saudagar Society",

    "sector 49-a - punjabi saudagar residency, scheme 33 - sector 49-a":
        "Punjabi Saudagar Society",


    # This section handles Gulshan-E-Kanez Fatima.    "gulshan-e-kaneez fatima - block 1, gulshan-e-kaneez fatima":
        "Gulshan-e-Kaneez Fatima",

    "gulshan-e-kaneez fatima - block 2, gulshan-e-kaneez fatima":
        "Gulshan-e-Kaneez Fatima",

    "gulshan-e-kaneez fatima - block 4, gulshan-e-kaneez fatima":
        "Gulshan-e-Kaneez Fatima",

    "shaaz bungalows, gulshan-e-kaneez fatima":
        "Gulshan-e-Kaneez Fatima",


    # This section handles Country Heights.    "country apartment":
        "Country Heights",

    "country comforts appartment":
        "Country Heights",


    # This section handles Hansa.    "hanas society":
        "Hansa Society",


    # This section handles Metroville.    "metrovil colony - block 1/1, metrovil colony":
        "Metroville Colony",

    "metrovil colony - block 2/1, metrovil colony":
        "Metroville Colony",

    "metrovil colony - block 2/2, metrovil colony":
        "Metroville Colony",

    "metrovil colony - block 3/1, metrovil colony":
        "Metroville Colony",

    "metrovil colony - block 3/2, metrovil colony":
        "Metroville Colony",


    # This section handles Ptv.    "ptv society - block b, ptv society":
        "PTV Society",


    # This section handles Kesc.    "rim jhim towers, kesc housing society":
        "KESC Housing Society",


    # This section handles Ali Garh.    "ali garh society - sector 5a, ali garh society":
        "Ali Garh Society",

    "ali garh society - sector 9a1, ali garh society":
        "Ali Garh Society",

    "ali garh society - sector 9a2, ali garh society":
        "Ali Garh Society",


    # This section handles Kathiawar.    "samrina grand, kathiawar society":
        "Kathiawar Society",

    "samrina boulevard":
        "Kathiawar Society",


    # This section handles NAN (UNKNOWN SMALL PROJECTS).    "a one villas, gulzar-e-hijri": np.nan,
    "asf tower": np.nan,
    "city comfort": np.nan,
    "commander heights": np.nan,
    "prem villas phase 2": np.nan,
    "premier one, kda road": np.nan,
    "rimjhim villas": np.nan,
    "rufi greenland": np.nan,
    "al fatah brishna heights": np.nan,
    "ahsan dreamland": np.nan,
    "memon nagar": np.nan,
    "pir gul hassan town": np.nan,
    "police society": np.nan,
    "old ravians co-operative housing society": np.nan,
    "nipa employees cooperative housing scheme": np.nan,
    "muslim cutchi khatri society": np.nan,
    "cutchi memon cooperative housing society": np.nan,
    "al-mehran cooperative housing scheme": np.nan,

}

In [91]:
mask = df["location"] == "Scheme 33"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(mapping)
)

In [92]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                                  225
saadi town                                                                                    158
Punjabi Saudagar Society                                                                      142
Saadi Town                                                                                    114
saadi garden                                                                                   87
Saadi Garden                                                                                   86
daniyal residency                                                                              62
meerut society                                                                                 57
hansa society                                                                                  56
Gulshan-e-Kaneez Fatima                                                                        56
karachi university housing society                                                             51
saima residencia, scheme 33 - sector 34-a                                                      49
pilibhit cooperative housing society, scheme 33 - sector 18-a                                  45
falaknaz twin tower, gulzar-e-hijri                                                            45
government teacher housing society - sector 16-a, scheme 33 - sector 16-a                      41
zeenatabad                                                                                     40
gwalior cooperative housing society                                                            40
chapal courtyard                                                                               39
state bank of pakistan housing society, scheme 33 - sector 17-a                                38
lakhani fantasia                                                                               38
falaknaz harmony                                                                               37
chapal sun city                                                                                33
sadaf cooperative housing society, gulzar-e-hijri                                              30
pakistan merchant navy society, scheme 33 - sector 15-a                                        28
sawera enclave, suparco road                                                                   27
falaknaz dynasty                                                                               27
grey noor tower & shopping mall                                                                27
rafi premier residency                                                                         26
noman residencia                                                                               25
sania corner, gulzar-e-hijri                                                                   25
cotton export cooperative housing society                                                      23
madras cooperative housing society, scheme 33 - sector 17-a                                    22
musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a                       21
gulshan-e-kaneez fatima                                                                        20
federal government employees housing foundation                                                19
fatima ali towers, gulzar-e-hijri                                                              19
chapal uptown                                                                                  16
quetta town - sector 18-a, scheme 33 - sector 18-a                                             15
Kathiawar Society                                                                              14
sumaira sky tower, gulzar-e-hijri                                                              14
andaleeb cooperative housing society                                                           13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                                 13
government teacher society - sector 19-a, scheme 33 - sector 19-a                              12
yousaf goth                                                                                    11
al muslim society, scheme 33 - sector 34-a                                                     11
safari signature, scheme 33 - sector 36-a                                                      11
central information cooperative housing society                                                10
scheme 33 - sector 19-a                                                                        10
taloo gold residency, suparco road                                                             10
sadat-e-amroha coop housing society                                                            10
suparco road                                                                                    9
soomra society                                                                                  9
Ali Garh Society                                                                                9
etawa society, scheme 33 - sector 52-a                                                          9
kings grand towers, scheme 33 - sector 35-a                                                     9
new lyari cooperative housing society, scheme 33 - sector 15-a                                  8
kda employees cooperative housing society, scheme 33 - sector 15-a                              8
incholi cooperative housing society, scheme 33 - sector 24-a                                    8
lateef duplex luxuria, scheme 33 - sector 35-a                                                  8
gulshan-e-usman housing society                                                                 7
suparco cooperative housing society, scheme 33 - sector 52-a                                    7
pakistan scientists cooperative housing society, scheme 33 - sector 17-a                        7
scheme 33 - sector 34-a                                                                         7
rok cooperative housing society                                                                 7
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a                            6
Metroville Colony                                                                               6
rufi spring flower, gulzar-e-hijri                                                              6
new rizvia cooperative housing society, scheme 33 - sector 34-a                                 6
kesc housing society                                                                            6
safari sunley cottages, scheme 33 - sector 51-a                                                 6
scheme 33 - sector 35-a                                                                         6
pakistan post office workers chs, scheme 33 - sector 36-a                                       5
sumaira comforts, gulzar-e-hijri                                                                5
scheme 33 - sector 15-a                                                                         5
lawyers colony - karachi bar cooperative housing society                                        5
alaska residency, gulzar-e-hijri                                                                5
white house garden society                                                                      5
kings garden, gulzar-e-hijri                                                                    5
scheme 33 - sector 31                                                                           5
kathiawar society, scheme 33 - sector 19-a                                                      5
ocean gardens, scheme 33 - sector 44                                                            4
gulistan society phase 1, scheme 33 - sector 19-a                                               4
mashraqi society, scheme 33 - sector 52-a                                                       4
scheme 33 - sector 32                                                                           4
saadabad cooperative housing society                                                            4
pakistan air crew cooperative housing society                                                   4
gulshan-e-usman phase 1 - block 2, gulshan-e-usman phase 1                                      3
scheme 33 - sector 17-a                                                                         3
ptv society, scheme 33 - sector 52-a                                                            3
pcsir housing society, scheme 33 - sector 24-a                                                  3
KESC Housing Society                                                                            3
scheme 33 - sector 51-a                                                                         3
karachi rajput co-operative housing society                                                     3
country heights                                                                                 3
hadiabad                                                                                        3
scheme 33 - sector 25-a                                                                         3
pia society, scheme 33 - sector 27-a                                                            3
karachi memon cooperative housing society                                                       3
scheme 33 - sector 18-a                                                                         3
rizwan cooperative housing scheme, gulzar-e-hijri                                               3
al-muslim cooperative housing society phase 2, scheme 33 - sector 38-a                          2
ps heights, scheme 33 - sector 31                                                               2
delhi raiyan cooperative housing society, scheme 33 - sector 51-a                               2
sumaira noor apartment, scheme 33 - sector 19-a                                                 2
Sachal Goth                                                                                     2
sumaira bungalows, scheme 33 - sector 34-a                                                      2
abid town                                                                                       2
pioneer fountain phase 2, gulzar-e-hijri                                                        2
county garden, gulzar-e-hijri                                                                   2
Hansa Society                                                                                   2
zubaida corner, zeenatabad                                                                      2
kehkashan homes, sadaf cooperative housing society                                              2
al raheem raza phase 1, scheme 33 - sector 32                                                   2
custom preventive cooperative housing society, scheme 33 - sector 52-a                          2
Sindh Baloch Housing Society                                                                    2
Country Heights                                                                                 2
bilawal shah noorani goth, gulzar-e-hijri                                                       2
gulshan-e-usman phase 1, gulshan-e-usman housing society                                        2
grey stylux residences, gulzar-e-hijri                                                          2
scheme 33 - sector 38-a                                                                         2
scheme 33 - sector 44                                                                           2
federal government employees - sector 24b, federal government employees housing foundation      1
af garden, scheme 33 - sector 24-a                                                              1
scheme 33 - sector 50                                                                           1
al-muslim cooperative housing society phase 1, scheme 33 - sector 38-a                          1
gulshan-e-azeem                                                                                 1
Zohra Nagar                                                                                     1
Abbas Town                                                                                      1
scheme 33 - sector 27-a                                                                         1
quetta town, scheme 33 - sector 3-a                                                             1
Falaknaz Golden Pebbles                                                                         1
muhammad bin qasim society - phase 2, muhammad bin qasim co-operative housing society           1
gulshan-e-umair                                                                                 1
arisha society, scheme 33 - sector 6-a                                                          1
government teacher society - sector 21-a, scheme 33 - sector 21-a                               1
state bank employees housing society, scheme 33 - sector 8-a                                    1
gulshan-e-elahi                                                                                 1
Pioneer Cottages                                                                                1
makhdomabad cooperative housing society, scheme 33 - sector 21-a                                1
scheme 33 - sector 21-a                                                                         1
pakistan writers guild co-operative housing society, scheme 33 - sector 51-a                    1
cantt pearl residency & shopping mall, scheme 33 - sector 35-a                                  1
muhammad bin qasim co-operative housing society                                                 1
scheme 33 - sector 20-a                                                                         1
PTV Society                                                                                     1
Name: count, dtype: int64

In [93]:
small_mapping_scheme33 = {

    # This section handles Same Parent Exists.    "pakistan writers guild co-operative housing society, scheme 33 - sector 51-a":
        "scheme 33 - sector 51-a",

    "cantt pearl residency & shopping mall, scheme 33 - sector 35-a":
        "scheme 33 - sector 35-a",

    "government teacher society - sector 21-a, scheme 33 - sector 21-a":
        "government teacher housing society - sector 16-a, scheme 33 - sector 16-a",

    "state bank employees housing society, scheme 33 - sector 8-a":
        "state bank of pakistan housing society, scheme 33 - sector 17-a",

    "federal government employees - sector 24b, federal government employees housing foundation":
        "federal government employees housing foundation",

    "Falaknaz Golden Pebbles":
        "falaknaz harmony",

    "af garden, scheme 33 - sector 24-a":
        "incholi cooperative housing society, scheme 33 - sector 24-a",

    "muhammad bin qasim society - phase 2, muhammad bin qasim co-operative housing society":
        "muhammad bin qasim co-operative housing society",


    # This section handles Remove Because No Reliable Parent.    "Pioneer Cottages": np.nan,
    "makhdomabad cooperative housing society, scheme 33 - sector 21-a": np.nan,
    "gulshan-e-elahi": np.nan,
    "muhammad bin qasim co-operative housing society": np.nan,
    "arisha society, scheme 33 - sector 6-a": np.nan,
    "gulshan-e-umair": np.nan,
    "Abbas Town": np.nan,
    "gulshan-e-azeem": np.nan,
    "Zohra Nagar": np.nan,

    # This section handles No Parent Available.    "scheme 33 - sector 3-a": np.nan,
    "quetta town, scheme 33 - sector 3-a": np.nan,
}

In [94]:
df["sub_location"] = df["sub_location"].replace(small_mapping_scheme33)

In [95]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     142
Saadi Town                                                                   114
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
meerut society                                                                57
hansa society                                                                 56
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
pilibhit cooperative housing society, scheme 33 - sector 18-a                 45
falaknaz twin tower, gulzar-e-hijri                                           45
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
zeenatabad                                                                    40
gwalior cooperative housing society                                           40
chapal courtyard                                                              39
state bank of pakistan housing society, scheme 33 - sector 17-a               39
falaknaz harmony                                                              38
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
grey noor tower & shopping mall                                               27
falaknaz dynasty                                                              27
sawera enclave, suparco road                                                  27
rafi premier residency                                                        26
sania corner, gulzar-e-hijri                                                  25
noman residencia                                                              25
cotton export cooperative housing society                                     23
madras cooperative housing society, scheme 33 - sector 17-a                   22
musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a      21
gulshan-e-kaneez fatima                                                       20
federal government employees housing foundation                               20
fatima ali towers, gulzar-e-hijri                                             19
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
sumaira sky tower, gulzar-e-hijri                                             14
Kathiawar Society                                                             14
andaleeb cooperative housing society                                          13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
al muslim society, scheme 33 - sector 34-a                                    11
safari signature, scheme 33 - sector 36-a                                     11
yousaf goth                                                                   11
taloo gold residency, suparco road                                            10
sadat-e-amroha coop housing society                                           10
scheme 33 - sector 19-a                                                       10
central information cooperative housing society                               10
suparco road                                                                   9
Ali Garh Society                                                               9
kings grand towers, scheme 33 - sector 35-a                                    9
etawa society, scheme 33 - sector 52-a                                         9
incholi cooperative housing society, scheme 33 - sector 24-a                   9
soomra society                                                                 9
kda employees cooperative housing society, scheme 33 - sector 15-a             8
new lyari cooperative housing society, scheme 33 - sector 15-a                 8
lateef duplex luxuria, scheme 33 - sector 35-a                                 8
suparco cooperative housing society, scheme 33 - sector 52-a                   7
pakistan scientists cooperative housing society, scheme 33 - sector 17-a       7
gulshan-e-usman housing society                                                7
scheme 33 - sector 35-a                                                        7
scheme 33 - sector 34-a                                                        7
rok cooperative housing society                                                7
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
kesc housing society                                                           6
rufi spring flower, gulzar-e-hijri                                             6
Metroville Colony                                                              6
new rizvia cooperative housing society, scheme 33 - sector 34-a                6
safari sunley cottages, scheme 33 - sector 51-a                                6
lawyers colony - karachi bar cooperative housing society                       5
scheme 33 - sector 31                                                          5
alaska residency, gulzar-e-hijri                                               5
sumaira comforts, gulzar-e-hijri                                               5
kathiawar society, scheme 33 - sector 19-a                                     5
kings garden, gulzar-e-hijri                                                   5
pakistan post office workers chs, scheme 33 - sector 36-a                      5
scheme 33 - sector 15-a                                                        5
white house garden society                                                     5
pakistan air crew cooperative housing society                                  4
scheme 33 - sector 32                                                          4
mashraqi society, scheme 33 - sector 52-a                                      4
scheme 33 - sector 51-a                                                        4
gulistan society phase 1, scheme 33 - sector 19-a                              4
ocean gardens, scheme 33 - sector 44                                           4
saadabad cooperative housing society                                           4
gulshan-e-usman phase 1 - block 2, gulshan-e-usman phase 1                     3
KESC Housing Society                                                           3
country heights                                                                3
hadiabad                                                                       3
karachi rajput co-operative housing society                                    3
ptv society, scheme 33 - sector 52-a                                           3
scheme 33 - sector 17-a                                                        3
pcsir housing society, scheme 33 - sector 24-a                                 3
scheme 33 - sector 25-a                                                        3
pia society, scheme 33 - sector 27-a                                           3
karachi memon cooperative housing society                                      3
scheme 33 - sector 18-a                                                        3
rizwan cooperative housing scheme, gulzar-e-hijri                              3
Hansa Society                                                                  2
sumaira noor apartment, scheme 33 - sector 19-a                                2
delhi raiyan cooperative housing society, scheme 33 - sector 51-a              2
custom preventive cooperative housing society, scheme 33 - sector 52-a         2
Sachal Goth                                                                    2
sumaira bungalows, scheme 33 - sector 34-a                                     2
pioneer fountain phase 2, gulzar-e-hijri                                       2
county garden, gulzar-e-hijri                                                  2
Sindh Baloch Housing Society                                                   2
zubaida corner, zeenatabad                                                     2
ps heights, scheme 33 - sector 31                                              2
al-muslim cooperative housing society phase 2, scheme 33 - sector 38-a         2
kehkashan homes, sadaf cooperative housing society                             2
al raheem raza phase 1, scheme 33 - sector 32                                  2
gulshan-e-usman phase 1, gulshan-e-usman housing society                       2
bilawal shah noorani goth, gulzar-e-hijri                                      2
abid town                                                                      2
grey stylux residences, gulzar-e-hijri                                         2
scheme 33 - sector 38-a                                                        2
Country Heights                                                                2
scheme 33 - sector 44                                                          2
scheme 33 - sector 20-a                                                        1
scheme 33 - sector 21-a                                                        1
muhammad bin qasim co-operative housing society                                1
scheme 33 - sector 50                                                          1
al-muslim cooperative housing society phase 1, scheme 33 - sector 38-a         1
scheme 33 - sector 27-a                                                        1
PTV Society                                                                    1
Name: count, dtype: int64

In [96]:
small_location_mapping = {

    # This section handles Duplicate Names.    "Hansa Society": "hansa society",
    "KESC Housing Society": "kesc housing society",
    "Country Heights": "country heights",
    "PTV Society": "ptv society, scheme 33 - sector 52-a",


    # This section handles Scheme 33 Sectors.    "scheme 33 - sector 15-a": "Scheme 33 Sector 15-A",
    "scheme 33 - sector 17-a": "Scheme 33 Sector 17-A",
    "scheme 33 - sector 18-a": "Scheme 33 Sector 18-A",
    "scheme 33 - sector 20-a": "Scheme 33 Sector 20-A",
    "scheme 33 - sector 21-a": "Scheme 33 Sector 21-A",
    "scheme 33 - sector 25-a": "Scheme 33 Sector 25-A",
    "scheme 33 - sector 27-a": "Scheme 33 Sector 27-A",
    "scheme 33 - sector 31": "Scheme 33 Sector 31",
    "scheme 33 - sector 32": "Scheme 33 Sector 32",
    "scheme 33 - sector 34-a": "Scheme 33 Sector 34-A",
    "scheme 33 - sector 35-a": "Scheme 33 Sector 35-A",
    "scheme 33 - sector 38-a": "Scheme 33 Sector 38-A",
    "scheme 33 - sector 44": "Scheme 33 Sector 44",
    "scheme 33 - sector 50": "Scheme 33 Sector 50",
    "scheme 33 - sector 51-a": "Scheme 33 Sector 51-A",


    # This section handles Society -> Sector mapping.    "muhammad bin qasim co-operative housing society": "Scheme 33 Sector 51-A",

    "delhi raiyan cooperative housing society, scheme 33 - sector 51-a":
        "Scheme 33 Sector 51-A",

    "custom preventive cooperative housing society, scheme 33 - sector 52-a":
        "Scheme 33 Sector 52-A",

    "ptv society, scheme 33 - sector 52-a":
        "Scheme 33 Sector 52-A",

    "ps heights, scheme 33 - sector 31":
        "Scheme 33 Sector 31",

    "al raheem raza phase 1, scheme 33 - sector 32":
        "Scheme 33 Sector 32",

    "sumaira noor apartment, scheme 33 - sector 19-a":
        "Scheme 33 Sector 19-A",

    "sumaira bungalows, scheme 33 - sector 34-a":
        "Scheme 33 Sector 34-A",

    "al-muslim cooperative housing society phase 1, scheme 33 - sector 38-a":
        "Scheme 33 Sector 38-A",

    "al-muslim cooperative housing society phase 2, scheme 33 - sector 38-a":
        "Scheme 33 Sector 38-A",


    # This section handles Gulzar-E-Hijri Merge.    "pioneer fountain phase 2, gulzar-e-hijri":
        "gulzar-e-hijri",

    "county garden, gulzar-e-hijri":
        "gulzar-e-hijri",

    "grey stylux residences, gulzar-e-hijri":
        "gulzar-e-hijri",

    "bilawal shah noorani goth, gulzar-e-hijri":
        "gulzar-e-hijri",

    "kehkashan homes, sadaf cooperative housing society":
        "gulzar-e-hijri",


    # This section handles Gulshan-E-Usman.    "gulshan-e-usman phase 1 - block 2, gulshan-e-usman phase 1":
        "gulshan-e-usman housing society",

    "gulshan-e-usman phase 1, gulshan-e-usman housing society":
        "gulshan-e-usman housing society",


    # This section handles Misc Known Areas.    "zubaida corner, zeenatabad":
        "zeenatabad",

    "Sindh Baloch Housing Society":
        "Scheme 33 Sector 52-A",

}

In [97]:
df["sub_location"] = df["sub_location"].replace(small_location_mapping)

In [98]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     142
Saadi Town                                                                   114
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
pilibhit cooperative housing society, scheme 33 - sector 18-a                 45
falaknaz twin tower, gulzar-e-hijri                                           45
zeenatabad                                                                    42
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
gwalior cooperative housing society                                           40
state bank of pakistan housing society, scheme 33 - sector 17-a               39
chapal courtyard                                                              39
lakhani fantasia                                                              38
falaknaz harmony                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
falaknaz dynasty                                                              27
sawera enclave, suparco road                                                  27
grey noor tower & shopping mall                                               27
rafi premier residency                                                        26
noman residencia                                                              25
sania corner, gulzar-e-hijri                                                  25
cotton export cooperative housing society                                     23
madras cooperative housing society, scheme 33 - sector 17-a                   22
musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a      21
gulshan-e-kaneez fatima                                                       20
federal government employees housing foundation                               20
fatima ali towers, gulzar-e-hijri                                             19
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
Kathiawar Society                                                             14
sumaira sky tower, gulzar-e-hijri                                             14
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
andaleeb cooperative housing society                                          13
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
gulshan-e-usman housing society                                               12
safari signature, scheme 33 - sector 36-a                                     11
yousaf goth                                                                   11
al muslim society, scheme 33 - sector 34-a                                    11
gulzar-e-hijri                                                                10
taloo gold residency, suparco road                                            10
central information cooperative housing society                               10
sadat-e-amroha coop housing society                                           10
scheme 33 - sector 19-a                                                       10
soomra society                                                                 9
Scheme 33 Sector 34-A                                                          9
suparco road                                                                   9
incholi cooperative housing society, scheme 33 - sector 24-a                   9
etawa society, scheme 33 - sector 52-a                                         9
kings grand towers, scheme 33 - sector 35-a                                    9
kesc housing society                                                           9
Ali Garh Society                                                               9
kda employees cooperative housing society, scheme 33 - sector 15-a             8
new lyari cooperative housing society, scheme 33 - sector 15-a                 8
lateef duplex luxuria, scheme 33 - sector 35-a                                 8
Scheme 33 Sector 35-A                                                          7
rok cooperative housing society                                                7
pakistan scientists cooperative housing society, scheme 33 - sector 17-a       7
Scheme 33 Sector 52-A                                                          7
Scheme 33 Sector 51-A                                                          7
Scheme 33 Sector 31                                                            7
suparco cooperative housing society, scheme 33 - sector 52-a                   7
safari sunley cottages, scheme 33 - sector 51-a                                6
Metroville Colony                                                              6
new rizvia cooperative housing society, scheme 33 - sector 34-a                6
rufi spring flower, gulzar-e-hijri                                             6
Scheme 33 Sector 32                                                            6
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
pakistan post office workers chs, scheme 33 - sector 36-a                      5
Scheme 33 Sector 38-A                                                          5
kings garden, gulzar-e-hijri                                                   5
country heights                                                                5
sumaira comforts, gulzar-e-hijri                                               5
white house garden society                                                     5
kathiawar society, scheme 33 - sector 19-a                                     5
alaska residency, gulzar-e-hijri                                               5
lawyers colony - karachi bar cooperative housing society                       5
Scheme 33 Sector 15-A                                                          5
gulistan society phase 1, scheme 33 - sector 19-a                              4
saadabad cooperative housing society                                           4
mashraqi society, scheme 33 - sector 52-a                                      4
pakistan air crew cooperative housing society                                  4
ocean gardens, scheme 33 - sector 44                                           4
hadiabad                                                                       3
Scheme 33 Sector 25-A                                                          3
pcsir housing society, scheme 33 - sector 24-a                                 3
karachi rajput co-operative housing society                                    3
rizwan cooperative housing scheme, gulzar-e-hijri                              3
Scheme 33 Sector 17-A                                                          3
karachi memon cooperative housing society                                      3
Scheme 33 Sector 18-A                                                          3
pia society, scheme 33 - sector 27-a                                           3
Scheme 33 Sector 44                                                            2
abid town                                                                      2
Scheme 33 Sector 19-A                                                          2
Sachal Goth                                                                    2
Scheme 33 Sector 50                                                            1
Scheme 33 Sector 20-A                                                          1
Scheme 33 Sector 21-A                                                          1
ptv society, scheme 33 - sector 52-a                                           1
Scheme 33 Sector 27-A                                                          1
Name: count, dtype: int64

In [99]:
falaknaz_mapping = {

    "falaknaz twin tower, gulzar-e-hijri": "Falaknaz",
    "falaknaz harmony": "Falaknaz",
    "falaknaz dynasty": "Falaknaz",
    "Falaknaz Golden Pebbles": "Falaknaz",

}

In [100]:
df["sub_location"] = df["sub_location"].replace(falaknaz_mapping)

In [101]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     142
Saadi Town                                                                   114
Falaknaz                                                                     110
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
pilibhit cooperative housing society, scheme 33 - sector 18-a                 45
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
zeenatabad                                                                    42
gwalior cooperative housing society                                           40
chapal courtyard                                                              39
state bank of pakistan housing society, scheme 33 - sector 17-a               39
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
grey noor tower & shopping mall                                               27
sawera enclave, suparco road                                                  27
rafi premier residency                                                        26
noman residencia                                                              25
sania corner, gulzar-e-hijri                                                  25
cotton export cooperative housing society                                     23
madras cooperative housing society, scheme 33 - sector 17-a                   22
musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a      21
gulshan-e-kaneez fatima                                                       20
federal government employees housing foundation                               20
fatima ali towers, gulzar-e-hijri                                             19
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
sumaira sky tower, gulzar-e-hijri                                             14
Kathiawar Society                                                             14
andaleeb cooperative housing society                                          13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
gulshan-e-usman housing society                                               12
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
safari signature, scheme 33 - sector 36-a                                     11
yousaf goth                                                                   11
al muslim society, scheme 33 - sector 34-a                                    11
scheme 33 - sector 19-a                                                       10
gulzar-e-hijri                                                                10
sadat-e-amroha coop housing society                                           10
taloo gold residency, suparco road                                            10
central information cooperative housing society                               10
kesc housing society                                                           9
soomra society                                                                 9
Scheme 33 Sector 34-A                                                          9
Ali Garh Society                                                               9
incholi cooperative housing society, scheme 33 - sector 24-a                   9
etawa society, scheme 33 - sector 52-a                                         9
kings grand towers, scheme 33 - sector 35-a                                    9
suparco road                                                                   9
kda employees cooperative housing society, scheme 33 - sector 15-a             8
new lyari cooperative housing society, scheme 33 - sector 15-a                 8
lateef duplex luxuria, scheme 33 - sector 35-a                                 8
rok cooperative housing society                                                7
suparco cooperative housing society, scheme 33 - sector 52-a                   7
Scheme 33 Sector 31                                                            7
Scheme 33 Sector 51-A                                                          7
Scheme 33 Sector 35-A                                                          7
Scheme 33 Sector 52-A                                                          7
pakistan scientists cooperative housing society, scheme 33 - sector 17-a       7
safari sunley cottages, scheme 33 - sector 51-a                                6
Metroville Colony                                                              6
Scheme 33 Sector 32                                                            6
new rizvia cooperative housing society, scheme 33 - sector 34-a                6
rufi spring flower, gulzar-e-hijri                                             6
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
Scheme 33 Sector 38-A                                                          5
country heights                                                                5
Scheme 33 Sector 15-A                                                          5
kathiawar society, scheme 33 - sector 19-a                                     5
lawyers colony - karachi bar cooperative housing society                       5
sumaira comforts, gulzar-e-hijri                                               5
pakistan post office workers chs, scheme 33 - sector 36-a                      5
kings garden, gulzar-e-hijri                                                   5
alaska residency, gulzar-e-hijri                                               5
white house garden society                                                     5
ocean gardens, scheme 33 - sector 44                                           4
pakistan air crew cooperative housing society                                  4
mashraqi society, scheme 33 - sector 52-a                                      4
saadabad cooperative housing society                                           4
gulistan society phase 1, scheme 33 - sector 19-a                              4
pia society, scheme 33 - sector 27-a                                           3
karachi rajput co-operative housing society                                    3
pcsir housing society, scheme 33 - sector 24-a                                 3
Scheme 33 Sector 17-A                                                          3
rizwan cooperative housing scheme, gulzar-e-hijri                              3
Scheme 33 Sector 18-A                                                          3
karachi memon cooperative housing society                                      3
hadiabad                                                                       3
Scheme 33 Sector 25-A                                                          3
Sachal Goth                                                                    2
Scheme 33 Sector 44                                                            2
Scheme 33 Sector 19-A                                                          2
abid town                                                                      2
Scheme 33 Sector 21-A                                                          1
Scheme 33 Sector 50                                                            1
ptv society, scheme 33 - sector 52-a                                           1
Scheme 33 Sector 27-A                                                          1
Scheme 33 Sector 20-A                                                          1
Name: count, dtype: int64

In [102]:
small_society_sector_mapping = {

    # This section handles Sector 15-A.    "kda employees cooperative housing society, scheme 33 - sector 15-a": "Scheme 33 Sector 15-A",
    "new lyari cooperative housing society, scheme 33 - sector 15-a": "Scheme 33 Sector 15-A",


    # This section handles Sector 17-A.    "pakistan scientists cooperative housing society, scheme 33 - sector 17-a": "Scheme 33 Sector 17-A",


    # This section handles Sector 18-A.    "pilibhit cooperative housing society, scheme 33 - sector 18-a": "Scheme 33 Sector 18-A",


    # This section handles Sector 19-A.    "kathiawar society, scheme 33 - sector 19-a": "Scheme 33 Sector 19-A",
    "gulistan society phase 1, scheme 33 - sector 19-a": "Scheme 33 Sector 19-A",
    "sumaira noor apartment, scheme 33 - sector 19-a": "Scheme 33 Sector 19-A",


    # This section handles Sector 20-A.    "musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a": "Scheme 33 Sector 20-A",


    # This section handles Sector 24-A.    "pcsir housing society, scheme 33 - sector 24-a": "Scheme 33 Sector 24-A",


    # This section handles Sector 27-A.    "pia society, scheme 33 - sector 27-a": "Scheme 33 Sector 27-A",


    # This section handles Sector 31.    "ps heights, scheme 33 - sector 31": "Scheme 33 Sector 31",


    # This section handles Sector 32.    "al raheem raza phase 1, scheme 33 - sector 32": "Scheme 33 Sector 32",


    # This section handles Sector 34-A.    "new rizvia cooperative housing society, scheme 33 - sector 34-a": "Scheme 33 Sector 34-A",
    "sumaira bungalows, scheme 33 - sector 34-a": "Scheme 33 Sector 34-A",


    # This section handles Sector 35-A.    "kings grand towers, scheme 33 - sector 35-a": "Scheme 33 Sector 35-A",
    "lateef duplex luxuria, scheme 33 - sector 35-a": "Scheme 33 Sector 35-A",


    # This section handles Sector 38-A.    "al-muslim cooperative housing society phase 1, scheme 33 - sector 38-a": "Scheme 33 Sector 38-A",
    "al-muslim cooperative housing society phase 2, scheme 33 - sector 38-a": "Scheme 33 Sector 38-A",


    # This section handles Sector 44.    "ocean gardens, scheme 33 - sector 44": "Scheme 33 Sector 44",


    # This section handles Sector 51-A.    "safari sunley cottages, scheme 33 - sector 51-a": "Scheme 33 Sector 51-A",
    "delhi raiyan cooperative housing society, scheme 33 - sector 51-a": "Scheme 33 Sector 51-A",


    # This section handles Sector 52-A.    "suparco cooperative housing society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",
    "mashraqi society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",
    "ptv society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",

}

In [103]:
df["sub_location"] = df["sub_location"].replace(small_society_sector_mapping)

In [104]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     142
Saadi Town                                                                   114
Falaknaz                                                                     110
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
Scheme 33 Sector 18-A                                                         48
zeenatabad                                                                    42
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
gwalior cooperative housing society                                           40
state bank of pakistan housing society, scheme 33 - sector 17-a               39
chapal courtyard                                                              39
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
grey noor tower & shopping mall                                               27
sawera enclave, suparco road                                                  27
rafi premier residency                                                        26
noman residencia                                                              25
sania corner, gulzar-e-hijri                                                  25
Scheme 33 Sector 35-A                                                         24
cotton export cooperative housing society                                     23
Scheme 33 Sector 20-A                                                         22
madras cooperative housing society, scheme 33 - sector 17-a                   22
Scheme 33 Sector 15-A                                                         21
federal government employees housing foundation                               20
gulshan-e-kaneez fatima                                                       20
Scheme 33 Sector 52-A                                                         19
fatima ali towers, gulzar-e-hijri                                             19
chapal uptown                                                                 16
Scheme 33 Sector 34-A                                                         15
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
sumaira sky tower, gulzar-e-hijri                                             14
Kathiawar Society                                                             14
Scheme 33 Sector 51-A                                                         13
andaleeb cooperative housing society                                          13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
gulshan-e-usman housing society                                               12
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
safari signature, scheme 33 - sector 36-a                                     11
Scheme 33 Sector 19-A                                                         11
al muslim society, scheme 33 - sector 34-a                                    11
yousaf goth                                                                   11
sadat-e-amroha coop housing society                                           10
scheme 33 - sector 19-a                                                       10
gulzar-e-hijri                                                                10
taloo gold residency, suparco road                                            10
Scheme 33 Sector 17-A                                                         10
central information cooperative housing society                               10
etawa society, scheme 33 - sector 52-a                                         9
incholi cooperative housing society, scheme 33 - sector 24-a                   9
suparco road                                                                   9
soomra society                                                                 9
Ali Garh Society                                                               9
kesc housing society                                                           9
Scheme 33 Sector 31                                                            7
rok cooperative housing society                                                7
Scheme 33 Sector 44                                                            6
Scheme 33 Sector 32                                                            6
Metroville Colony                                                              6
rufi spring flower, gulzar-e-hijri                                             6
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
white house garden society                                                     5
kings garden, gulzar-e-hijri                                                   5
country heights                                                                5
sumaira comforts, gulzar-e-hijri                                               5
pakistan post office workers chs, scheme 33 - sector 36-a                      5
lawyers colony - karachi bar cooperative housing society                       5
Scheme 33 Sector 38-A                                                          5
alaska residency, gulzar-e-hijri                                               5
pakistan air crew cooperative housing society                                  4
saadabad cooperative housing society                                           4
Scheme 33 Sector 27-A                                                          4
rizwan cooperative housing scheme, gulzar-e-hijri                              3
karachi memon cooperative housing society                                      3
Scheme 33 Sector 25-A                                                          3
karachi rajput co-operative housing society                                    3
hadiabad                                                                       3
Scheme 33 Sector 24-A                                                          3
abid town                                                                      2
Sachal Goth                                                                    2
Scheme 33 Sector 21-A                                                          1
Scheme 33 Sector 50                                                            1
Name: count, dtype: int64

In [105]:
scheme_parent_mapping = {

    # This section handles Punjabi Saudagar Society Master Plan.    "Scheme 33 Sector 31": "Punjabi Saudagar Society",
    "Scheme 33 Sector 32": "Punjabi Saudagar Society",
    "Scheme 33 Sector 50": "Punjabi Saudagar Society",


    # This section handles Lawyers Colony / Karachi Bar.    "Scheme 33 Sector 25-A": "Lawyers Colony",


    # This section handles Faridi Niazi / Musalmanan-E-Punjab.    "Scheme 33 Sector 20-A": "Musalmanan-E-Punjab Cooperative Housing Society",


    # This section handles Ocean Gardens.    "Scheme 33 Sector 44": "Ocean Gardens",


    # This section handles Yasin Cooperative.    "Scheme 33 Sector 27-A": "Yasin Cooperative Housing Society",


    # This section handles Peoples Cooperative.    "Scheme 33 Sector 38-A": "Peoples Cooperative Housing Society",


    # This section handles P&T Society.    "Scheme 33 Sector 21-A": "P&T Society",
}

In [106]:
df["sub_location"] = df["sub_location"].replace(scheme_parent_mapping)

In [107]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     156
Saadi Town                                                                   114
Falaknaz                                                                     110
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
Scheme 33 Sector 18-A                                                         48
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
zeenatabad                                                                    42
gwalior cooperative housing society                                           40
chapal courtyard                                                              39
state bank of pakistan housing society, scheme 33 - sector 17-a               39
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
grey noor tower & shopping mall                                               27
sawera enclave, suparco road                                                  27
rafi premier residency                                                        26
sania corner, gulzar-e-hijri                                                  25
noman residencia                                                              25
Scheme 33 Sector 35-A                                                         24
cotton export cooperative housing society                                     23
madras cooperative housing society, scheme 33 - sector 17-a                   22
Musalmanan-E-Punjab Cooperative Housing Society                               22
Scheme 33 Sector 15-A                                                         21
federal government employees housing foundation                               20
gulshan-e-kaneez fatima                                                       20
fatima ali towers, gulzar-e-hijri                                             19
Scheme 33 Sector 52-A                                                         19
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
Scheme 33 Sector 34-A                                                         15
Kathiawar Society                                                             14
sumaira sky tower, gulzar-e-hijri                                             14
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
Scheme 33 Sector 51-A                                                         13
andaleeb cooperative housing society                                          13
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
gulshan-e-usman housing society                                               12
safari signature, scheme 33 - sector 36-a                                     11
al muslim society, scheme 33 - sector 34-a                                    11
yousaf goth                                                                   11
Scheme 33 Sector 19-A                                                         11
scheme 33 - sector 19-a                                                       10
taloo gold residency, suparco road                                            10
gulzar-e-hijri                                                                10
sadat-e-amroha coop housing society                                           10
Scheme 33 Sector 17-A                                                         10
central information cooperative housing society                               10
incholi cooperative housing society, scheme 33 - sector 24-a                   9
suparco road                                                                   9
kesc housing society                                                           9
soomra society                                                                 9
Ali Garh Society                                                               9
etawa society, scheme 33 - sector 52-a                                         9
rok cooperative housing society                                                7
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
Ocean Gardens                                                                  6
Metroville Colony                                                              6
rufi spring flower, gulzar-e-hijri                                             6
lawyers colony - karachi bar cooperative housing society                       5
kings garden, gulzar-e-hijri                                                   5
alaska residency, gulzar-e-hijri                                               5
Peoples Cooperative Housing Society                                            5
white house garden society                                                     5
country heights                                                                5
sumaira comforts, gulzar-e-hijri                                               5
pakistan post office workers chs, scheme 33 - sector 36-a                      5
Yasin Cooperative Housing Society                                              4
pakistan air crew cooperative housing society                                  4
saadabad cooperative housing society                                           4
karachi memon cooperative housing society                                      3
rizwan cooperative housing scheme, gulzar-e-hijri                              3
Lawyers Colony                                                                 3
karachi rajput co-operative housing society                                    3
hadiabad                                                                       3
Scheme 33 Sector 24-A                                                          3
Sachal Goth                                                                    2
abid town                                                                      2
P&T Society                                                                    1
Name: count, dtype: int64

In [108]:
final_small_mapping = {

    # This section handles Duplicate Normalization.    "scheme 33 - sector 19-a": "Scheme 33 Sector 19-A",
    "ptv society, scheme 33 - sector 52-a": "PTV Society",
    "Hansa Society": "hansa society",
    "kesc housing society": "KESC Housing Society",

    # This section handles Sector Based Mapping.    "Scheme 33 Sector 24-A": "Scheme 33 Sector 24-A",
    "hadiabad": "Scheme 33 Sector 51-A",
    "rizwan cooperative housing scheme, gulzar-e-hijri": "Scheme 33 Sector 22-A",
    "karachi rajput co-operative housing society": "Scheme 33 Sector 11-A",
    "karachi memon cooperative housing society": "Scheme 33 Sector 17-A",
    "P&T Society": "Scheme 33 Sector 21-A",

    # This section handles Remove Very Small Unknowns.    "Sachal Goth": np.nan,
    "abid town": np.nan,

}

In [109]:
df["sub_location"] = df["sub_location"].replace(final_small_mapping)

In [110]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     156
Saadi Town                                                                   114
Falaknaz                                                                     110
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
Scheme 33 Sector 18-A                                                         48
zeenatabad                                                                    42
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
gwalior cooperative housing society                                           40
state bank of pakistan housing society, scheme 33 - sector 17-a               39
chapal courtyard                                                              39
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
pakistan merchant navy society, scheme 33 - sector 15-a                       28
sawera enclave, suparco road                                                  27
grey noor tower & shopping mall                                               27
rafi premier residency                                                        26
noman residencia                                                              25
sania corner, gulzar-e-hijri                                                  25
Scheme 33 Sector 35-A                                                         24
cotton export cooperative housing society                                     23
madras cooperative housing society, scheme 33 - sector 17-a                   22
Musalmanan-E-Punjab Cooperative Housing Society                               22
Scheme 33 Sector 19-A                                                         21
Scheme 33 Sector 15-A                                                         21
federal government employees housing foundation                               20
gulshan-e-kaneez fatima                                                       20
fatima ali towers, gulzar-e-hijri                                             19
Scheme 33 Sector 52-A                                                         19
Scheme 33 Sector 51-A                                                         16
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
Scheme 33 Sector 34-A                                                         15
Kathiawar Society                                                             14
sumaira sky tower, gulzar-e-hijri                                             14
andaleeb cooperative housing society                                          13
Scheme 33 Sector 17-A                                                         13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
gulshan-e-usman housing society                                               12
safari signature, scheme 33 - sector 36-a                                     11
al muslim society, scheme 33 - sector 34-a                                    11
yousaf goth                                                                   11
sadat-e-amroha coop housing society                                           10
central information cooperative housing society                               10
gulzar-e-hijri                                                                10
taloo gold residency, suparco road                                            10
incholi cooperative housing society, scheme 33 - sector 24-a                   9
KESC Housing Society                                                           9
suparco road                                                                   9
soomra society                                                                 9
etawa society, scheme 33 - sector 52-a                                         9
Ali Garh Society                                                               9
rok cooperative housing society                                                7
abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a           6
rufi spring flower, gulzar-e-hijri                                             6
Ocean Gardens                                                                  6
Metroville Colony                                                              6
kings garden, gulzar-e-hijri                                                   5
white house garden society                                                     5
lawyers colony - karachi bar cooperative housing society                       5
country heights                                                                5
Peoples Cooperative Housing Society                                            5
alaska residency, gulzar-e-hijri                                               5
pakistan post office workers chs, scheme 33 - sector 36-a                      5
sumaira comforts, gulzar-e-hijri                                               5
saadabad cooperative housing society                                           4
pakistan air crew cooperative housing society                                  4
Yasin Cooperative Housing Society                                              4
Scheme 33 Sector 22-A                                                          3
Lawyers Colony                                                                 3
Scheme 33 Sector 11-A                                                          3
Scheme 33 Sector 24-A                                                          3
Scheme 33 Sector 21-A                                                          1
Name: count, dtype: int64

In [111]:
scheme33_sector_cluster = {

    # This section handles Sector 24-A cluster (25).    "incholi cooperative housing society, scheme 33 - sector 24-a": "Scheme 33 Sector 24-A",
    "white house garden society": "Scheme 33 Sector 24-A",
    "lawyers colony - karachi bar cooperative housing society": "Scheme 33 Sector 24-A",
    "Scheme 33 Sector 24-A": "Scheme 33 Sector 24-A",

    # This section handles Sector 22-A cluster (21).    "rufi spring flower, gulzar-e-hijri": "Scheme 33 Sector 22-A",
    "sumaira comforts, gulzar-e-hijri": "Scheme 33 Sector 22-A",
    "saadabad cooperative housing society": "Scheme 33 Sector 22-A",
    "rizwan cooperative housing scheme, gulzar-e-hijri": "Scheme 33 Sector 22-A",

    # This section handles Sector 36-A Cluster.    "soomra society": "Scheme 33 Sector 36-A",
    "pakistan post office workers chs, scheme 33 - sector 36-a": "Scheme 33 Sector 36-A",

    # This section handles Sector 52-A Cluster.    "etawa society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",
    "ptv society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",
    "suparco cooperative housing society, scheme 33 - sector 52-a": "Scheme 33 Sector 52-A",

    # This section handles Sector 53-A.    "abuzar ghaffari cooperative housing society, scheme 33 - sector 53-a": "Scheme 33 Sector 53-A",

    # This section handles Sector 38-A.    "Peoples Cooperative Housing Society": "Scheme 33 Sector 38-A",

    # This section handles Sector 27-A.    "Yasin Cooperative Housing Society": "Scheme 33 Sector 27-A",

    # This section handles Sector 21-A.    "P&T Society": "Scheme 33 Sector 21-A",
}

In [112]:
df["sub_location"] = df["sub_location"].replace(scheme33_sector_cluster)

In [113]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
capital cooperative housing society, scheme 33 - sector 35-a                 225
saadi town                                                                   158
Punjabi Saudagar Society                                                     156
Saadi Town                                                                   114
Falaknaz                                                                     110
saadi garden                                                                  87
Saadi Garden                                                                  86
daniyal residency                                                             62
hansa society                                                                 58
meerut society                                                                57
Gulshan-e-Kaneez Fatima                                                       56
karachi university housing society                                            51
saima residencia, scheme 33 - sector 34-a                                     49
Scheme 33 Sector 18-A                                                         48
government teacher housing society - sector 16-a, scheme 33 - sector 16-a     42
zeenatabad                                                                    42
gwalior cooperative housing society                                           40
chapal courtyard                                                              39
state bank of pakistan housing society, scheme 33 - sector 17-a               39
lakhani fantasia                                                              38
chapal sun city                                                               33
sadaf cooperative housing society, gulzar-e-hijri                             30
Scheme 33 Sector 52-A                                                         28
pakistan merchant navy society, scheme 33 - sector 15-a                       28
sawera enclave, suparco road                                                  27
grey noor tower & shopping mall                                               27
rafi premier residency                                                        26
noman residencia                                                              25
sania corner, gulzar-e-hijri                                                  25
Scheme 33 Sector 35-A                                                         24
cotton export cooperative housing society                                     23
Musalmanan-E-Punjab Cooperative Housing Society                               22
Scheme 33 Sector 24-A                                                         22
madras cooperative housing society, scheme 33 - sector 17-a                   22
Scheme 33 Sector 19-A                                                         21
Scheme 33 Sector 15-A                                                         21
federal government employees housing foundation                               20
gulshan-e-kaneez fatima                                                       20
fatima ali towers, gulzar-e-hijri                                             19
Scheme 33 Sector 22-A                                                         18
Scheme 33 Sector 51-A                                                         16
chapal uptown                                                                 16
quetta town - sector 18-a, scheme 33 - sector 18-a                            15
Scheme 33 Sector 34-A                                                         15
Scheme 33 Sector 36-A                                                         14
Kathiawar Society                                                             14
sumaira sky tower, gulzar-e-hijri                                             14
andaleeb cooperative housing society                                          13
shahnawaz cooperative housing society, scheme 33 - sector 51-a                13
Scheme 33 Sector 17-A                                                         13
gulshan-e-usman housing society                                               12
government teacher society - sector 19-a, scheme 33 - sector 19-a             12
safari signature, scheme 33 - sector 36-a                                     11
al muslim society, scheme 33 - sector 34-a                                    11
yousaf goth                                                                   11
sadat-e-amroha coop housing society                                           10
taloo gold residency, suparco road                                            10
central information cooperative housing society                               10
gulzar-e-hijri                                                                10
suparco road                                                                   9
KESC Housing Society                                                           9
Ali Garh Society                                                               9
rok cooperative housing society                                                7
Scheme 33 Sector 53-A                                                          6
Metroville Colony                                                              6
Ocean Gardens                                                                  6
kings garden, gulzar-e-hijri                                                   5
alaska residency, gulzar-e-hijri                                               5
country heights                                                                5
Scheme 33 Sector 38-A                                                          5
pakistan air crew cooperative housing society                                  4
Scheme 33 Sector 27-A                                                          4
Lawyers Colony                                                                 3
Scheme 33 Sector 11-A                                                          3
Scheme 33 Sector 21-A                                                          1
Name: count, dtype: int64

In [114]:
scheme33_sector_mapping = {

    # This section handles Sector 35-A.    "capital cooperative housing society, scheme 33 - sector 35-a": "Scheme 33 Sector 35-A",
    "Scheme 33 Sector 35-A": "Scheme 33 Sector 35-A",

    # This section handles Sector 18-A.    "Scheme 33 Sector 18-A": "Scheme 33 Sector 18-A",
    "pilipbhit cooperative housing society, scheme 33 - sector 18-a": "Scheme 33 Sector 18-A",
    "quetta town - sector 18-a, scheme 33 - sector 18-a": "Scheme 33 Sector 18-A",

    # This section handles Sector 16-A.    "government teacher housing society - sector 16-a, scheme 33 - sector 16-a": "Scheme 33 Sector 16-A",

    # This section handles Sector 17-A.    "state bank of pakistan housing society, scheme 33 - sector 17-a": "Scheme 33 Sector 17-A",
    "madras cooperative housing society, scheme 33 - sector 17-a": "Scheme 33 Sector 17-A",
    "Scheme 33 Sector 17-A": "Scheme 33 Sector 17-A",

    # This section handles Sector 52-A.    "Scheme 33 Sector 52-A": "Scheme 33 Sector 52-A",

    # This section handles Sector 15-A.    "pakistan merchant navy society, scheme 33 - sector 15-a": "Scheme 33 Sector 15-A",
    "Scheme 33 Sector 15-A": "Scheme 33 Sector 15-A",

    # This section handles Sector 24-A.    "Scheme 33 Sector 24-A": "Scheme 33 Sector 24-A",

    # This section handles Sector 19-A.    "Scheme 33 Sector 19-A": "Scheme 33 Sector 19-A",
    "government teacher society - sector 19-a, scheme 33 - sector 19-a": "Scheme 33 Sector 19-A",

    # This section handles Sector 22-A.    "Scheme 33 Sector 22-A": "Scheme 33 Sector 22-A",

    # This section handles Sector 51-A.    "Scheme 33 Sector 51-A": "Scheme 33 Sector 51-A",
    "shahnawaz cooperative housing society, scheme 33 - sector 51-a": "Scheme 33 Sector 51-A",

    # This section handles Sector 36-A.    "Scheme 33 Sector 36-A": "Scheme 33 Sector 36-A",
    "safari signature, scheme 33 - sector 36-a": "Scheme 33 Sector 36-A",

    # This section handles Sector 34-A.    "Scheme 33 Sector 34-A": "Scheme 33 Sector 34-A",
    "saima residencia, scheme 33 - sector 34-a": "Scheme 33 Sector 34-A",
    "al muslim society, scheme 33 - sector 34-a": "Scheme 33 Sector 34-A",

}

In [115]:
df["sub_location"] = df["sub_location"].replace(scheme33_sector_mapping)

In [116]:
sub_location_mapping = {

    # This section handles Capital / Scheme 33.    "capital cooperative housing society, scheme 33 - sector 35-a":
        "Capital Cooperative Housing Society",

    "Scheme 33 Sector 18-A":
        "Scheme 33 Sector 18-A",

    "Scheme 33 Sector 52-A":
        "Scheme 33 Sector 52-A",

    "Scheme 33 Sector 35-A":
        "Scheme 33 Sector 35-A",

    "Scheme 33 Sector 24-A":
        "Scheme 33 Sector 24-A",

    "Scheme 33 Sector 19-A":
        "Scheme 33 Sector 19-A",

    "Scheme 33 Sector 15-A":
        "Scheme 33 Sector 15-A",

    "Scheme 33 Sector 22-A":
        "Scheme 33 Sector 22-A",

    "Scheme 33 Sector 51-A":
        "Scheme 33 Sector 51-A",

    "Scheme 33 Sector 34-A":
        "Scheme 33 Sector 34-A",

    "Scheme 33 Sector 36-A":
        "Scheme 33 Sector 36-A",

    "Scheme 33 Sector 17-A":
        "Scheme 33 Sector 17-A",


    # This section handles Saadi.    "saadi town":
        "Saadi Town",

    "Saadi Town":
        "Saadi Town",

    "saadi garden":
        "Saadi Garden",

    "Saadi Garden":
        "Saadi Garden",


    # This section handles Gulshan-E-Kaneez Fatima.    "gulshan-e-kaneez fatima":
        "Gulshan-e-Kaneez Fatima",

    "Gulshan-e-Kaneez Fatima":
        "Gulshan-e-Kaneez Fatima",


    # This section handles Government Teacher Society.    "government teacher housing society - sector 16-a, scheme 33 - sector 16-a":
        "Government Teacher Housing Society",

    "government teacher society - sector 19-a, scheme 33 - sector 19-a":
        "Government Teacher Housing Society",


    # This section handles Scheme 33 Societies.    "state bank of pakistan housing society, scheme 33 - sector 17-a":
        "State Bank of Pakistan Housing Society",

    "madras cooperative housing society, scheme 33 - sector 17-a":
        "Madras Cooperative Housing Society",

    "pakistan merchant navy society, scheme 33 - sector 15-a":
        "Pakistan Merchant Navy Society",

    "saima residencia, scheme 33 - sector 34-a":
        "Saima Residencia",

    "pilibhit cooperative housing society, scheme 33 - sector 18-a":
        "Pilibhit Cooperative Housing Society",

    "musalmanan-e-punjab cooperative housing society, scheme 33 - sector 20-a":
        "Musalmanan-e-Punjab Cooperative Housing Society",

    "quetta town - sector 18-a, scheme 33 - sector 18-a":
        "Quetta Town",


    # This section handles Gulzar-E-Hijri.    "sadaf cooperative housing society, gulzar-e-hijri":
        "Sadaf Cooperative Housing Society",

    "sania corner, gulzar-e-hijri":
        "Sania Corner",

    "fatima ali towers, gulzar-e-hijri":
        "Fatima Ali Towers",

    "sumaira sky tower, gulzar-e-hijri":
        "Sumaira Sky Tower",

    "gulzar-e-hijri":
        "Gulzar-e-Hijri",


    # This section handles Chapal Projects.    "chapal courtyard":
        "Chapal Courtyard",

    "chapal sun city":
        "Chapal Sun City",

    "chapal uptown":
        "Chapal Uptown",


    # This section handles Other Normalization.    "zeenatabad":
        "Zeenatabad",

    "gwalior cooperative housing society":
        "Gwalior Cooperative Housing Society",

    "hansa society":
        "Hansa Society",

    "meerut society":
        "Meerut Society",

    "karachi university housing society":
        "Karachi University Housing Society",

    "lakhani fantasia":
        "Lakhani Fantasia",

    "grey noor tower & shopping mall":
        "Grey Noor Tower",

    "sawera enclave, suparco road":
        "Sawera Enclave",

    "taloo gold residency, suparco road":
        "Taloo Gold Residency",

    "kathiawar society":
        "Kathiawar Society",

    "Kathiawar Society":
        "Kathiawar Society",

    "gulshan-e-usman housing society":
        "Gulshan-e-Usman Housing Society",

    "shahnawaz cooperative housing society, scheme 33 - sector 51-a":
        "Shahnawaz Cooperative Housing Society",

    "andaleeb cooperative housing society":
        "Andaleeb Cooperative Housing Society",

    "safari signature, scheme 33 - sector 36-a":
        "Safari Signature",

    "central information cooperative housing society":
        "Central Information Cooperative Housing Society",

    "sadat-e-amroha coop housing society":
        "Sadat-e-Amroha Cooperative Housing Society",

    "Gulzar-e-Hijri":np.nan


}

In [117]:
df["sub_location"] = df["sub_location"].replace(sub_location_mapping)

In [118]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Saadi Town                                         272
Scheme 33 Sector 35-A                              249
Saadi Garden                                       173
Punjabi Saudagar Society                           156
Falaknaz                                           110
Gulshan-e-Kaneez Fatima                             76
Scheme 33 Sector 34-A                               75
Scheme 33 Sector 17-A                               74
Scheme 33 Sector 18-A                               63
daniyal residency                                   62
Hansa Society                                       58
Meerut Society                                      57
Karachi University Housing Society                  51
Scheme 33 Sector 15-A                               49
Scheme 33 Sector 16-A                               42
Zeenatabad                                          42
Gwalior Cooperative Housing Society                 40
Chapal Courtyard                                    39
Lakhani Fantasia                                    38
Scheme 33 Sector 19-A                               33
Chapal Sun City                                     33
Sadaf Cooperative Housing Society                   30
Scheme 33 Sector 51-A                               29
Scheme 33 Sector 52-A                               28
Sawera Enclave                                      27
Grey Noor Tower                                     27
rafi premier residency                              26
Scheme 33 Sector 36-A                               25
noman residencia                                    25
Sania Corner                                        25
cotton export cooperative housing society           23
Scheme 33 Sector 24-A                               22
Musalmanan-E-Punjab Cooperative Housing Society     22
federal government employees housing foundation     20
Fatima Ali Towers                                   19
Scheme 33 Sector 22-A                               18
Chapal Uptown                                       16
Sumaira Sky Tower                                   14
Kathiawar Society                                   14
Andaleeb Cooperative Housing Society                13
Gulshan-e-Usman Housing Society                     12
yousaf goth                                         11
Gulzar-e-Hijri                                      10
Sadat-e-Amroha Cooperative Housing Society          10
Central Information Cooperative Housing Society     10
Taloo Gold Residency                                10
Ali Garh Society                                     9
KESC Housing Society                                 9
suparco road                                         9
rok cooperative housing society                      7
Scheme 33 Sector 53-A                                6
Ocean Gardens                                        6
Metroville Colony                                    6
country heights                                      5
Scheme 33 Sector 38-A                                5
alaska residency, gulzar-e-hijri                     5
kings garden, gulzar-e-hijri                         5
pakistan air crew cooperative housing society        4
Scheme 33 Sector 27-A                                4
Lawyers Colony                                       3
Scheme 33 Sector 11-A                                3
Scheme 33 Sector 21-A                                1
Name: count, dtype: int64

In [119]:
scheme33_mask = df["location"].str.contains("Scheme 33", case=False, na=False)

scheme33_counts = df.loc[scheme33_mask, "sub_location"].value_counts()

valid_scheme33 = scheme33_counts[scheme33_counts >= 10].index

df.loc[
    scheme33_mask & ~df["sub_location"].isin(valid_scheme33),
    "sub_location"
] = np.nan

In [120]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Saadi Town                                         272
Scheme 33 Sector 35-A                              249
Saadi Garden                                       173
Punjabi Saudagar Society                           156
Falaknaz                                           110
Gulshan-e-Kaneez Fatima                             76
Scheme 33 Sector 34-A                               75
Scheme 33 Sector 17-A                               74
Scheme 33 Sector 18-A                               63
daniyal residency                                   62
Hansa Society                                       58
Meerut Society                                      57
Karachi University Housing Society                  51
Scheme 33 Sector 15-A                               49
Scheme 33 Sector 16-A                               42
Zeenatabad                                          42
Gwalior Cooperative Housing Society                 40
Chapal Courtyard                                    39
Lakhani Fantasia                                    38
Chapal Sun City                                     33
Scheme 33 Sector 19-A                               33
Sadaf Cooperative Housing Society                   30
Scheme 33 Sector 51-A                               29
Scheme 33 Sector 52-A                               28
Grey Noor Tower                                     27
Sawera Enclave                                      27
rafi premier residency                              26
noman residencia                                    25
Scheme 33 Sector 36-A                               25
Sania Corner                                        25
cotton export cooperative housing society           23
Musalmanan-E-Punjab Cooperative Housing Society     22
Scheme 33 Sector 24-A                               22
federal government employees housing foundation     20
Fatima Ali Towers                                   19
Scheme 33 Sector 22-A                               18
Chapal Uptown                                       16
Sumaira Sky Tower                                   14
Kathiawar Society                                   14
Andaleeb Cooperative Housing Society                13
Gulshan-e-Usman Housing Society                     12
yousaf goth                                         11
Sadat-e-Amroha Cooperative Housing Society          10
Central Information Cooperative Housing Society     10
Gulzar-e-Hijri                                      10
Taloo Gold Residency                                10
Name: count, dtype: int64

In [121]:
shah_faisal_mapping = {

    # This section handles Main / Parent.    "shah faisal town": "Shah Faisal Town",

    # This section handles Major Societies / Projects.    "kn gohar green city": "KN Gohar Green City",
    "saima luxury homes": "Saima Luxury Homes",
    "shamsi society, shah faisal town": "Shamsi Society",
    "falcon complex faisal": "Falcon Complex Faisal",

    # This section handles Residential Areas.    "azeem pura, shah faisal town": "Azeem Pura",
    "green town, shah faisal town": "Green Town",
    "al ghaffar nagori city, shah faisal town": "Al Ghaffar Nagori City",
    "drigh colony, shah faisal town": "Drigh Colony",
    "rafah-e-aam, shah faisal town": "Rafah-e-Aam",
    "bagh-e-malir, shah faisal town": "Bagh-e-Malir",
    "gulshan-e-dad rahim, shah faisal town": "Gulshan-e-Dad Rahim",

    # This section handles Blocks.    "shah faisal town - block 1, shah faisal town": "Shah Faisal Town Block 1",
    "shah faisal town - block 2, shah faisal town": "Shah Faisal Town Block 2",

    # This section handles Societies.    "al-falah society, shah faisal town": "Al-Falah Society",
    "muhammad ali shaheed society, shah faisal town": "Muhammad Ali Shaheed Society",
    "bagh-e-ibrahim society, shah faisal town": "Bagh-e-Ibrahim Society",
    "bagh-e-rafi, shah faisal town": "Bagh-e-Rafi",
    "natha khan goth, shah faisal town": "Natha Khan Goth",
    "rafi bungalows, shah faisal town": "Rafi Bungalows",
    "salman farsi society, shah faisal town": "Salman Farsi Society",
    "shaheed abdullah murad housing city, shah faisal town": "Shaheed Abdullah Murad Housing City",
}

In [122]:
df["sub_location"] = (
    df["sub_location"]
    .str.lower()
    .replace(shah_faisal_mapping)
)

In [123]:
df[df['location']=='Shah Faisal']['sub_location'].value_counts()

sub_location
KN Gohar Green City                    35
Saima Luxury Homes                     32
Shamsi Society                         25
Falcon Complex Faisal                  14
Shah Faisal Town                       12
Azeem Pura                              7
Green Town                              7
Drigh Colony                            4
Rafah-e-Aam                             4
Al Ghaffar Nagori City                  4
Shah Faisal Town Block 1                3
Gulshan-e-Dad Rahim                     3
Bagh-e-Malir                            3
Al-Falah Society                        2
Muhammad Ali Shaheed Society            2
Shah Faisal Town Block 2                1
Salman Farsi Society                    1
Natha Khan Goth                         1
Bagh-e-Rafi                             1
Rafi Bungalows                          1
Bagh-e-Ibrahim Society                  1
Shaheed Abdullah Murad Housing City     1
Name: count, dtype: int64

In [124]:
df.loc[df['sub_location'].str.lower() == 'shah faisal town', 'sub_location'] = np.nan

In [125]:
shah_faisal_cluster_mapping = {

    # This section handles Keep Premium / Strong Identities.    "kn gohar green city": "Gohar Green City Cluster",
    "al ghaffar nagori city": "Gohar Green City Cluster",
    "gulshan-e-dad rahim": "Gohar Green City Cluster",

    "saima luxury homes": "Saima Luxury Belt",
    "shaheed abdullah murad housing city": "Saima Luxury Belt",

    "shamsi society": "Shamsi / Al-Falah Belt",
    "al-falah society": "Shamsi / Al-Falah Belt",

    "green town": "Green Town / Rafah-e-Aam Belt",
    "azeem pura": "Green Town / Rafah-e-Aam Belt",
    "rafah-e-aam": "Green Town / Rafah-e-Aam Belt",
    "bagh-e-malir": "Green Town / Rafah-e-Aam Belt",
    "bagh-e-ibrahim society": "Green Town / Rafah-e-Aam Belt",
    "bagh-e-rafi": "Green Town / Rafah-e-Aam Belt",
    "rafi bungalows": "Green Town / Rafah-e-Aam Belt",

    "shah faisal town block 1": "Shah Faisal Core",
    "shah faisal town block 2": "Shah Faisal Core",
    "muhammad ali shaheed society": "Shah Faisal Core",
    "salman farsi society": "Shah Faisal Core",
    "natha khan goth": "Shah Faisal Core",
    "drigh colony": "Shah Faisal Core",

    # This section handles Keep Independent.    "falcon complex faisal": "Falcon Complex Faisal",
}

In [126]:
df["sub_location"] = (
    df["sub_location"]
    .str.lower()
    .replace(shah_faisal_cluster_mapping )
)

In [127]:
df[df["location"].str.contains("shah faisal", case=False, na=False)]["sub_location"].value_counts()

sub_location
Gohar Green City Cluster         42
Saima Luxury Belt                33
Shamsi / Al-Falah Belt           27
Green Town / Rafah-e-Aam Belt    24
Falcon Complex Faisal            14
Shah Faisal Core                 12
Name: count, dtype: int64

In [128]:
df.loc[df["sub_location"]== "Shah Faisal Core", "sub_location"]=np.nan

In [129]:
df[df["location"].str.contains("shah faisal", case=False, na=False)]["sub_location"].value_counts()

sub_location
Gohar Green City Cluster         42
Saima Luxury Belt                33
Shamsi / Al-Falah Belt           27
Green Town / Rafah-e-Aam Belt    24
Falcon Complex Faisal            14
Name: count, dtype: int64

In [130]:
super_highway_mapping = {

    # This section handles Keep Meaningful Locations.    "saima villas, karachi motorway": "Saima Villas",
    "rabia enclave, karachi motorway": "Rabia Enclave",
    "oasis park residencia": "Oasis Park Residencia",

    # This section handles Small / unclear locations -> NaN.    "abdullah gabol goth - block d, abdullah gabol goth": np.nan,
    "aviation enclave, karachi motorway": np.nan,
    "gulmohar city, karachi motorway": np.nan,
    "roomi city, karachi - hyderabad motorway": np.nan,

    # This section handles Generic road names -> NaN.    "karachi - hyderabad motorway": np.nan,
    "karachi motorway": np.nan,
}

df["sub_location"] = df["sub_location"].replace(super_highway_mapping)

In [131]:
df[df["location"].str.contains("super highway", case=False, na=False)]["sub_location"].value_counts()

sub_location
Saima Villas             72
Rabia Enclave             9
Oasis Park Residencia     6
Name: count, dtype: int64

In [132]:
saadi_road_mapping = {
    "saadi road": "Saadi Road",
    "tulip tower": "Saadi Road",
    "sanober twin tower": "Saadi Road"
}

df["sub_location"] = df["sub_location"].str.lower().replace(saadi_road_mapping)

In [133]:
df.loc[df["sub_location"].isin(
    ["Saadi Road"]
), "location"] = "Scheme 33"

In [134]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
saadi town                                         272
scheme 33 sector 35-a                              249
saadi garden                                       173
punjabi saudagar society                           156
falaknaz                                           110
gulshan-e-kaneez fatima                             76
scheme 33 sector 34-a                               75
scheme 33 sector 17-a                               74
scheme 33 sector 18-a                               63
daniyal residency                                   62
hansa society                                       58
meerut society                                      57
Saadi Road                                          57
karachi university housing society                  51
scheme 33 sector 15-a                               49
zeenatabad                                          42
scheme 33 sector 16-a                               42
gwalior cooperative housing society                 40
chapal courtyard                                    39
lakhani fantasia                                    38
scheme 33 sector 19-a                               33
chapal sun city                                     33
sadaf cooperative housing society                   30
scheme 33 sector 51-a                               29
scheme 33 sector 52-a                               28
sawera enclave                                      27
grey noor tower                                     27
rafi premier residency                              26
sania corner                                        25
scheme 33 sector 36-a                               25
noman residencia                                    25
cotton export cooperative housing society           23
scheme 33 sector 24-a                               22
musalmanan-e-punjab cooperative housing society     22
federal government employees housing foundation     20
fatima ali towers                                   19
scheme 33 sector 22-a                               18
chapal uptown                                       16
sumaira sky tower                                   14
kathiawar society                                   14
andaleeb cooperative housing society                13
gulshan-e-usman housing society                     12
yousaf goth                                         11
gulzar-e-hijri                                      10
central information cooperative housing society     10
sadat-e-amroha cooperative housing society          10
taloo gold residency                                10
Name: count, dtype: int64

In [135]:
import numpy as np

university_road_mapping = {

    # This section handles Keep Important Sub Locations.    "burj-ul-harmain": "Burj-ul-Harmain",
    "saima jinnah avenue": "Saima Jinnah Avenue",
    "al madni heights": "Al Madni Heights",
    "safari enclave apartments": "Safari Enclave Apartments",
    "city tower and shopping mall": "City Tower and Shopping Mall",

    # This section handles Rare / Low Count Sub Locations.    "urban twin towers": np.nan,
    "rufi dream land bungalows": np.nan,
    "shahmir residency": np.nan,
    "old sabzi mandi": np.nan,
}

mask = df["location"] == "University Road"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
      .replace(university_road_mapping)
)

In [136]:
df[df['location']=='University Road']['sub_location'].value_counts()

sub_location
Burj-ul-Harmain                 143
Saima Jinnah Avenue              50
Al Madni Heights                 41
Safari Enclave Apartments        18
City Tower and Shopping Mall     17
Name: count, dtype: int64

In [137]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           bahria sports city                                     128
                      bahria apartments                                      120
                      ali block                                              109
                      precinct 8                                              94
                      precinct 10a                                            92
                      private high-rises                                      92
                      precinct 11a                                            85
                      precinct 31                                             84
                      bahria paradise                                         76
                      precinct 11b                                            74
                      quaid villas                                            72
                      precinct 1                                              70
                      precinct 10b                                            68
                      precinct 6                                              63
                      bahria town                                             62
                      precinct 27                                             61
                      iqbal villas                                            60
                      bahria heights                                          57
                      bahria hills                                            54
                      precinct 4                                              49
                      precinct 16                                             37
                      precinct 19                                             34
                      precinct 17                                             26
                      precinct 15                                             22
                      precinct 12                                             21
                      precinct 7                                              14
                      precinct 2                                              13
                      precinct 9                                              11
                      precinct 18                                              5
                      golf city                                                2
                      precinct 3                                               2
Bin Qasim Town        mateen complex                                          34
Cantt                 askari 5                                               626
                      askari 6                                               585
                      navy housing scheme karsaz                             131
                      dohs phase 1                                            51
                      gulshan-e-roomi                                         43
                      malir cantonment                                        20
                      dohs phase 2                                            11
                      p & t colony                                            10
                      dr daud pota road                                        1
                      karachi cantonment                                       1
Civil Lines           hsj icon                                                 3
Clifton               clifton block 2                                        160
                      bath island                                            128
                      clifton block 9                                         94
                      clifton block 8                                         89
                      clifton block 1                                         87
                      clifton block 4                                         52
                      frere town                                              43
                      clifton block 7                                         40
                      clifton block 5                                         35
                      clifton block 3                                         11
                      clifton block 6                                         11
                      gizri                                                   11
DHA Defence           dha phase 8                                           2241
                      dha phase 6                                            907
                      dha phase 5                                            427
                      dha phase 7                                            296
                      dha phase 4                                            168
                      dha phase 7 extension                                  147
                      dha phase 2 extension                                   69
                      dha phase 1                                             65
                      dha phase 2                                             54
                      dha phase 5 extension                                   21
                      dha phase 8 extension                                   12
                      darakhshan villas, dha phase 6                           7
Federal B Area        federal b area block 10                                 75
                      federal b area block 12                                 54
                      federal b area block 13                                 41
                      federal b area block 11                                 29
                      federal b area block 14                                 23
                      federal b area block 16                                 19
                      federal b area block 9                                  19
                      federal b area block 15                                 18
                      federal b area block 8                                  18
                      federal b area block 19                                 17
                      federal b area block 6                                  12
                      federal b area block 7                                  11
                      federal b area block 20                                 10
                      shahrah-e-pakistan                                      10
Gadap                 gulshan-e-maymar                                       468
                      surjani town                                           273
                      memon goth                                              55
Gulistan-e-Jauhar     block 15                                               196
                      block 14                                               152
                      block 13                                               132
                      block 18                                               132
                      block 7                                                122
                      block 3a                                               119
                      block 12                                               117
                      block 17                                               114
                      block 2                                                 91
                      block 19                                                74
                      block 16                                                71
                      block 3                                                 57
                      block 1                                                 39
                      block 10                                                39
                      askari 4                                                34
                      block 11                                                33
                      block 4                                                 31
                      block 20                                                25
                      block 16a                                               14
                      block 9                                                 14
                      block 8                                                 12
                      latifi cooperative housing society                       8
                      safoora goth                                             8
                      block 5                                                  7
                      kda overseas bungalows                                   7
                      block 6                                                  4
Gulshan-e-Iqbal Town  callachi cooperative housing society                   302
                      block 1                                                194
                      block 10a                                              144
                      bahadurabad                                            121
                      block 4                                                 92
                      block 7                                                 91
                      kda scheme 1                                            87
                      block 5                                                 84
                      block 2                                                 78
                      block 13d2                                              76
                      block 13d1                                              65
                      dhoraji colony                                          59
                      block 13d                                               58
                      block 6                                                 57
                      sharfabad                                               47
                      block 17                                                44
                      kda officers society                                    43
                      block 13a                                               41
                      block 13c                                               39
                      block 3                                                 39
                      block 11                                                34
                      block 13d3                                              32
                      block 13b                                               24
                      block 16                                                23
                      block 10                                                21
                      mohammad ali society                                    18
                      block 19                                                17
                      block 9                                                 17
                      adamjee nagar                                           16
                      block 14                                                16
                      cp barar society, gulshan-e-iqbal town                  14
                      national stadium colony                                 14
                      block 4a                                                13
                      dawood society                                          13
                      gulshan-e-jamal                                         13
                      kda scheme 1 extension                                  11
                      block 13                                                10
Jamshed Town          pechs                                                  284
                      shaheed millat road                                    179
                      khalid bin walid road                                  124
                      jamshed road                                            61
                      karachi administration employees society                46
                      smchs - sindhi muslim society                           45
                      tariq road                                              39
                      amir khusro                                             36
                      garden east                                             34
                      amil colony                                             29
                      hill park                                               27
                      soldier bazar                                           22
                      parsi colony                                            21
                      mehmoodabad                                             19
                      cosmopolitan society                                    17
                      shahra-e-qaideen                                        14
                      defence skyline, shaheed-e-millat expressway            12
                      muslimabad society                                      12
Jinnah Avenue         metropolis residency                                   112
                      aman golf view                                          38
                      roomi residency                                         33
Korangi               allahwala town                                         113
                      korangi industrial area                                 23
                      kda employees society                                   16
                      qayyumabad                                              16
Malir                 falcon complex new malir                               516
                      falaknaz                                               118
                      model colony                                            96
                      malir link to super highway                             82
                      airport                                                 45
                      saima projects                                          37
                      jamia millia road                                       20
                      golden town                                             16
                      malir town residency                                    13
Naya Nazimabad        block a                                                 95
                      block c                                                 87
                      block d                                                 68
                      block b                                                 67
                      block m                                                 23
Nazimabad             nazimabad 4                                             22
                      nazimabad 3                                             20
                      nazimabad 5                                              9
                      nazimabad 1                                              8
                      nazimabad 2                                              5
North Karachi         buffer zone                                            105
                      north karachi sector 11                                 80
                      north karachi sector 5                                  49
                      north karachi sector 7                                  38
                      north karachi sector 9                                  26
                      north karachi sector 10                                 14
                      north karachi sector 8                                  14
                      new karachi                                             10
North Nazimabad       north nazimabad - block f                              183
                      north nazimabad - block h                              131
                      north nazimabad - block l                              120
                      north nazimabad - block n                              118
                      north nazimabad - block b                               83
                      north nazimabad - block m                               52
                      north nazimabad - block k                               51
                      north nazimabad - block a                               50
                      north nazimabad - block d                               45
                      north nazimabad - block j                               37
                      shadman town - sector-14/b, shadman                     36
                      north nazimabad - block i                               34
                      north nazimabad - block g                               32
                      north nazimabad - block c                               12
                      shadman                                                  6
                      shadman town - sector-14/a, shadman                      6
                      north nazimabad - block r                                5
                      north nazimabad - block t                                5
                      nagan chowrangi                                          3
                      north nazimabad - block w                                3
                      al-rauf sky towers, north nazimabad - block m            2
                      north nazimabad - block q                                2
                      north nazimabad - block s                                2
                      silver sands tower, north nazimabad - block m            2
                      allama iqbal town                                        1
                      north nazimabad - block e                                1
                      saima grands, north nazimabad - block h                  1
                      saima pari star, north nazimabad - block h               1
                      sakhi hassan chowrangi                                   1
Orangi Town           orangi town - sector 11                                  2
                      ghaziabad                                                1
                      orangi town - sector 8                                   1
Rashid Minhas Road    lucky one apartment                                     41
                      saima royal residency                                   32
                      lakhani presidency                                       8
SITE Area             metroville 3, metroville                                 4
                      pak colony, sindh industrial trading estate (site)       1
                      sindh industrial trading estate (site)                   1
Scheme 33             saadi town                                             272
                      scheme 33 sector 35-a                                  249
                      saadi garden                                           173
                      punjabi saudagar society                               156
                      falaknaz                                               110
                      gulshan-e-kaneez fatima                                 76
                      scheme 33 sector 34-a                                   75
                      scheme 33 sector 17-a                                   74
                      scheme 33 sector 18-a                                   63

In [138]:
remove_locations = [
    "Shahrah-e-Faisal",
    "Scheme 45",
    "SITE Area",
    "Orangi Town"
]

df = df[~df["location"].isin(remove_locations)]

In [139]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           bahria sports city                                  128
                      bahria apartments                                   120
                      ali block                                           109
                      precinct 8                                           94
                      precinct 10a                                         92
                      private high-rises                                   92
                      precinct 11a                                         85
                      precinct 31                                          84
                      bahria paradise                                      76
                      precinct 11b                                         74
                      quaid villas                                         72
                      precinct 1                                           70
                      precinct 10b                                         68
                      precinct 6                                           63
                      bahria town                                          62
                      precinct 27                                          61
                      iqbal villas                                         60
                      bahria heights                                       57
                      bahria hills                                         54
                      precinct 4                                           49
                      precinct 16                                          37
                      precinct 19                                          34
                      precinct 17                                          26
                      precinct 15                                          22
                      precinct 12                                          21
                      precinct 7                                           14
                      precinct 2                                           13
                      precinct 9                                           11
                      precinct 18                                           5
                      golf city                                             2
                      precinct 3                                            2
Bin Qasim Town        mateen complex                                       34
Cantt                 askari 5                                            626
                      askari 6                                            585
                      navy housing scheme karsaz                          131
                      dohs phase 1                                         51
                      gulshan-e-roomi                                      43
                      malir cantonment                                     20
                      dohs phase 2                                         11
                      p & t colony                                         10
                      dr daud pota road                                     1
                      karachi cantonment                                    1
Civil Lines           hsj icon                                              3
Clifton               clifton block 2                                     160
                      bath island                                         128
                      clifton block 9                                      94
                      clifton block 8                                      89
                      clifton block 1                                      87
                      clifton block 4                                      52
                      frere town                                           43
                      clifton block 7                                      40
                      clifton block 5                                      35
                      clifton block 3                                      11
                      clifton block 6                                      11
                      gizri                                                11
DHA Defence           dha phase 8                                        2241
                      dha phase 6                                         907
                      dha phase 5                                         427
                      dha phase 7                                         296
                      dha phase 4                                         168
                      dha phase 7 extension                               147
                      dha phase 2 extension                                69
                      dha phase 1                                          65
                      dha phase 2                                          54
                      dha phase 5 extension                                21
                      dha phase 8 extension                                12
                      darakhshan villas, dha phase 6                        7
Federal B Area        federal b area block 10                              75
                      federal b area block 12                              54
                      federal b area block 13                              41
                      federal b area block 11                              29
                      federal b area block 14                              23
                      federal b area block 16                              19
                      federal b area block 9                               19
                      federal b area block 15                              18
                      federal b area block 8                               18
                      federal b area block 19                              17
                      federal b area block 6                               12
                      federal b area block 7                               11
                      federal b area block 20                              10
                      shahrah-e-pakistan                                   10
Gadap                 gulshan-e-maymar                                    468
                      surjani town                                        273
                      memon goth                                           55
Gulistan-e-Jauhar     block 15                                            196
                      block 14                                            152
                      block 13                                            132
                      block 18                                            132
                      block 7                                             122
                      block 3a                                            119
                      block 12                                            117
                      block 17                                            114
                      block 2                                              91
                      block 19                                             74
                      block 16                                             71
                      block 3                                              57
                      block 1                                              39
                      block 10                                             39
                      askari 4                                             34
                      block 11                                             33
                      block 4                                              31
                      block 20                                             25
                      block 16a                                            14
                      block 9                                              14
                      block 8                                              12
                      latifi cooperative housing society                    8
                      safoora goth                                          8
                      block 5                                               7
                      kda overseas bungalows                                7
                      block 6                                               4
Gulshan-e-Iqbal Town  callachi cooperative housing society                302
                      block 1                                             194
                      block 10a                                           144
                      bahadurabad                                         121
                      block 4                                              92
                      block 7                                              91
                      kda scheme 1                                         87
                      block 5                                              84
                      block 2                                              78
                      block 13d2                                           76
                      block 13d1                                           65
                      dhoraji colony                                       59
                      block 13d                                            58
                      block 6                                              57
                      sharfabad                                            47
                      block 17                                             44
                      kda officers society                                 43
                      block 13a                                            41
                      block 13c                                            39
                      block 3                                              39
                      block 11                                             34
                      block 13d3                                           32
                      block 13b                                            24
                      block 16                                             23
                      block 10                                             21
                      mohammad ali society                                 18
                      block 19                                             17
                      block 9                                              17
                      adamjee nagar                                        16
                      block 14                                             16
                      cp barar society, gulshan-e-iqbal town               14
                      national stadium colony                              14
                      block 4a                                             13
                      dawood society                                       13
                      gulshan-e-jamal                                      13
                      kda scheme 1 extension                               11
                      block 13                                             10
Jamshed Town          pechs                                               284
                      shaheed millat road                                 179
                      khalid bin walid road                               124
                      jamshed road                                         61
                      karachi administration employees society             46
                      smchs - sindhi muslim society                        45
                      tariq road                                           39
                      amir khusro                                          36
                      garden east                                          34
                      amil colony                                          29
                      hill park                                            27
                      soldier bazar                                        22
                      parsi colony                                         21
                      mehmoodabad                                          19
                      cosmopolitan society                                 17
                      shahra-e-qaideen                                     14
                      defence skyline, shaheed-e-millat expressway         12
                      muslimabad society                                   12
Jinnah Avenue         metropolis residency                                112
                      aman golf view                                       38
                      roomi residency                                      33
Korangi               allahwala town                                      113
                      korangi industrial area                              23
                      kda employees society                                16
                      qayyumabad                                           16
Malir                 falcon complex new malir                            516
                      falaknaz                                            118
                      model colony                                         96
                      malir link to super highway                          82
                      airport                                              45
                      saima projects                                       37
                      jamia millia road                                    20
                      golden town                                          16
                      malir town residency                                 13
Naya Nazimabad        block a                                              95
                      block c                                              87
                      block d                                              68
                      block b                                              67
                      block m                                              23
Nazimabad             nazimabad 4                                          22
                      nazimabad 3                                          20
                      nazimabad 5                                           9
                      nazimabad 1                                           8
                      nazimabad 2                                           5
North Karachi         buffer zone                                         105
                      north karachi sector 11                              80
                      north karachi sector 5                               49
                      north karachi sector 7                               38
                      north karachi sector 9                               26
                      north karachi sector 10                              14
                      north karachi sector 8                               14
                      new karachi                                          10
North Nazimabad       north nazimabad - block f                           183
                      north nazimabad - block h                           131
                      north nazimabad - block l                           120
                      north nazimabad - block n                           118
                      north nazimabad - block b                            83
                      north nazimabad - block m                            52
                      north nazimabad - block k                            51
                      north nazimabad - block a                            50
                      north nazimabad - block d                            45
                      north nazimabad - block j                            37
                      shadman town - sector-14/b, shadman                  36
                      north nazimabad - block i                            34
                      north nazimabad - block g                            32
                      north nazimabad - block c                            12
                      shadman                                               6
                      shadman town - sector-14/a, shadman                   6
                      north nazimabad - block r                             5
                      north nazimabad - block t                             5
                      nagan chowrangi                                       3
                      north nazimabad - block w                             3
                      al-rauf sky towers, north nazimabad - block m         2
                      north nazimabad - block q                             2
                      north nazimabad - block s                             2
                      silver sands tower, north nazimabad - block m         2
                      allama iqbal town                                     1
                      north nazimabad - block e                             1
                      saima grands, north nazimabad - block h               1
                      saima pari star, north nazimabad - block h            1
                      sakhi hassan chowrangi                                1
Rashid Minhas Road    lucky one apartment                                  41
                      saima royal residency                                32
                      lakhani presidency                                    8
Scheme 33             saadi town                                          272
                      scheme 33 sector 35-a                               249
                      saadi garden                                        173
                      punjabi saudagar society                            156
                      falaknaz                                            110
                      gulshan-e-kaneez fatima                              76
                      scheme 33 sector 34-a                                75
                      scheme 33 sector 17-a                                74
                      scheme 33 sector 18-a                                63
                      daniyal residency                                    62
                      hansa society                                        58
                      Saadi Road                                           57
                      meerut society                                       57
                      karachi university housing society                   51
                      scheme 33 sector 15-a                                49
                      scheme 33 sector 16-a                                42
                      zeenatabad                                           42
                      gwalior cooperative housing society                  40
                      chapal courtyard                                     39
                      lakhani fantasia                                     38
                      chapal sun city                                      33
                      scheme 33 sector 19-a                                33
                      sadaf cooperative housing society                    30
                      scheme 33 sector 51-a                                29

In [140]:
north_nazimabad_mapping = {

    # This section handles Buildings -> block.    "al-rauf sky towers, north nazimabad - block m": "North Nazimabad Block M",
    "silver sands tower, north nazimabad - block m": "North Nazimabad Block M",

    "saima grands, north nazimabad - block h": "North Nazimabad Block H",
    "saima pari star, north nazimabad - block h": "North Nazimabad Block H",

    # This section handles Small blocks -> NaN.    "north nazimabad - block r": np.nan,
    "north nazimabad - block t": np.nan,
    "north nazimabad - block w": np.nan,
    "north nazimabad - block q": np.nan,
    "north nazimabad - block s": np.nan,
    "north nazimabad - block e": np.nan,

}

mask = df["location"] == "North Nazimabad"

df.loc[mask, "sub_location"] = (
    df.loc[mask, "sub_location"]
    .replace(north_nazimabad_mapping)
)

In [141]:
df[df['location']=='North Nazimabad']['sub_location'].value_counts()

sub_location
north nazimabad - block f              183
north nazimabad - block h              131
north nazimabad - block l              120
north nazimabad - block n              118
north nazimabad - block b               83
north nazimabad - block m               52
north nazimabad - block k               51
north nazimabad - block a               50
north nazimabad - block d               45
north nazimabad - block j               37
shadman town - sector-14/b, shadman     36
north nazimabad - block i               34
north nazimabad - block g               32
north nazimabad - block c               12
shadman town - sector-14/a, shadman      6
shadman                                  6
North Nazimabad Block M                  4
nagan chowrangi                          3
North Nazimabad Block H                  2
allama iqbal town                        1
sakhi hassan chowrangi                   1
Name: count, dtype: int64

In [142]:
df.groupby('location')['sub_location'].value_counts().shape

(285,)

In [143]:
import re

def format_sub_location(x):
    if pd.isna(x):
        return x

    x = str(x).strip().lower()

    # This section handles Remove Extra Spaces.    x = re.sub(r"\s+", " ", x)

    # Remove parent names from sub_location
    x = re.sub(r"^north nazimabad\s*-\s*", "", x)
    x = re.sub(r"^federal b area\s*", "", x)
    x = re.sub(r"^dha\s*", "", x)
    x = re.sub(r"^scheme 33\s*", "", x)

    # This section handles Block Formatting.    x = re.sub(r"block\s*([a-z0-9]+)", lambda m: f"block {m.group(1)}", x)

    # This section handles Phase Formatting.    x = re.sub(r"phase\s*(\d+[a-z]?)", lambda m: f"phase {m.group(1)}", x)

    # This section handles Sector Formatting.    x = re.sub(r"sector\s*(\d+[a-z]?-\w?)", lambda m: f"sector {m.group(1)}", x)

    # This section handles Title Case.    x = x.title()

    return x


df["sub_location"] = df["sub_location"].apply(format_sub_location)

In [144]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Bahria Sports City                                  128
                      Bahria Apartments                                   120
                      Ali Block                                           109
                      Precinct 8                                           94
                      Precinct 10A                                         92
                      Private High-Rises                                   92
                      Precinct 11A                                         85
                      Precinct 31                                          84
                      Bahria Paradise                                      76
                      Precinct 11B                                         74
                      Quaid Villas                                         72
                      Precinct 1                                           70
                      Precinct 10B                                         68
                      Precinct 6                                           63
                      Bahria Town                                          62
                      Precinct 27                                          61
                      Iqbal Villas                                         60
                      Bahria Heights                                       57
                      Bahria Hills                                         54
                      Precinct 4                                           49
                      Precinct 16                                          37
                      Precinct 19                                          34
                      Precinct 17                                          26
                      Precinct 15                                          22
                      Precinct 12                                          21
                      Precinct 7                                           14
                      Precinct 2                                           13
                      Precinct 9                                           11
                      Precinct 18                                           5
                      Golf City                                             2
                      Precinct 3                                            2
Bin Qasim Town        Mateen Complex                                       34
Cantt                 Askari 5                                            626
                      Askari 6                                            585
                      Navy Housing Scheme Karsaz                          131
                      Dohs Phase 1                                         51
                      Gulshan-E-Roomi                                      43
                      Malir Cantonment                                     20
                      Dohs Phase 2                                         11
                      P & T Colony                                         10
                      Dr Daud Pota Road                                     1
                      Karachi Cantonment                                    1
Civil Lines           Hsj Icon                                              3
Clifton               Clifton Block 2                                     160
                      Bath Island                                         128
                      Clifton Block 9                                      94
                      Clifton Block 8                                      89
                      Clifton Block 1                                      87
                      Clifton Block 4                                      52
                      Frere Town                                           43
                      Clifton Block 7                                      40
                      Clifton Block 5                                      35
                      Clifton Block 3                                      11
                      Clifton Block 6                                      11
                      Gizri                                                11
DHA Defence           Phase 8                                            2241
                      Phase 6                                             907
                      Phase 5                                             427
                      Phase 7                                             296
                      Phase 4                                             168
                      Phase 7 Extension                                   147
                      Phase 2 Extension                                    69
                      Phase 1                                              65
                      Phase 2                                              54
                      Phase 5 Extension                                    21
                      Phase 8 Extension                                    12
                      Darakhshan Villas, Dha Phase 6                        7
Federal B Area        Block 10                                             75
                      Block 12                                             54
                      Block 13                                             41
                      Block 11                                             29
                      Block 14                                             23
                      Block 16                                             19
                      Block 9                                              19
                      Block 15                                             18
                      Block 8                                              18
                      Block 19                                             17
                      Block 6                                              12
                      Block 7                                              11
                      Block 20                                             10
                      Shahrah-E-Pakistan                                   10
Gadap                 Gulshan-E-Maymar                                    468
                      Surjani Town                                        273
                      Memon Goth                                           55
Gulistan-e-Jauhar     Block 15                                            196
                      Block 14                                            152
                      Block 13                                            132
                      Block 18                                            132
                      Block 7                                             122
                      Block 3A                                            119
                      Block 12                                            117
                      Block 17                                            114
                      Block 2                                              91
                      Block 19                                             74
                      Block 16                                             71
                      Block 3                                              57
                      Block 1                                              39
                      Block 10                                             39
                      Askari 4                                             34
                      Block 11                                             33
                      Block 4                                              31
                      Block 20                                             25
                      Block 16A                                            14
                      Block 9                                              14
                      Block 8                                              12
                      Latifi Cooperative Housing Society                    8
                      Safoora Goth                                          8
                      Block 5                                               7
                      Kda Overseas Bungalows                                7
                      Block 6                                               4
Gulshan-e-Iqbal Town  Callachi Cooperative Housing Society                302
                      Block 1                                             194
                      Block 10A                                           144
                      Bahadurabad                                         121
                      Block 4                                              92
                      Block 7                                              91
                      Kda Scheme 1                                         87
                      Block 5                                              84
                      Block 2                                              78
                      Block 13D2                                           76
                      Block 13D1                                           65
                      Dhoraji Colony                                       59
                      Block 13D                                            58
                      Block 6                                              57
                      Sharfabad                                            47
                      Block 17                                             44
                      Kda Officers Society                                 43
                      Block 13A                                            41
                      Block 13C                                            39
                      Block 3                                              39
                      Block 11                                             34
                      Block 13D3                                           32
                      Block 13B                                            24
                      Block 16                                             23
                      Block 10                                             21
                      Mohammad Ali Society                                 18
                      Block 19                                             17
                      Block 9                                              17
                      Adamjee Nagar                                        16
                      Block 14                                             16
                      Cp Barar Society, Gulshan-E-Iqbal Town               14
                      National Stadium Colony                              14
                      Block 4A                                             13
                      Dawood Society                                       13
                      Gulshan-E-Jamal                                      13
                      Kda Scheme 1 Extension                               11
                      Block 13                                             10
Jamshed Town          Pechs                                               284
                      Shaheed Millat Road                                 179
                      Khalid Bin Walid Road                               124
                      Jamshed Road                                         61
                      Karachi Administration Employees Society             46
                      Smchs - Sindhi Muslim Society                        45
                      Tariq Road                                           39
                      Amir Khusro                                          36
                      Garden East                                          34
                      Amil Colony                                          29
                      Hill Park                                            27
                      Soldier Bazar                                        22
                      Parsi Colony                                         21
                      Mehmoodabad                                          19
                      Cosmopolitan Society                                 17
                      Shahra-E-Qaideen                                     14
                      Defence Skyline, Shaheed-E-Millat Expressway         12
                      Muslimabad Society                                   12
Jinnah Avenue         Metropolis Residency                                112
                      Aman Golf View                                       38
                      Roomi Residency                                      33
Korangi               Allahwala Town                                      113
                      Korangi Industrial Area                              23
                      Kda Employees Society                                16
                      Qayyumabad                                           16
Malir                 Falcon Complex New Malir                            516
                      Falaknaz                                            118
                      Model Colony                                         96
                      Malir Link To Super Highway                          82
                      Airport                                              45
                      Saima Projects                                       37
                      Jamia Millia Road                                    20
                      Golden Town                                          16
                      Malir Town Residency                                 13
Naya Nazimabad        Block A                                              95
                      Block C                                              87
                      Block D                                              68
                      Block B                                              67
                      Block M                                              23
Nazimabad             Nazimabad 4                                          22
                      Nazimabad 3                                          20
                      Nazimabad 5                                           9
                      Nazimabad 1                                           8
                      Nazimabad 2                                           5
North Karachi         Buffer Zone                                         105
                      North Karachi Sector 11                              80
                      North Karachi Sector 5                               49
                      North Karachi Sector 7                               38
                      North Karachi Sector 9                               26
                      North Karachi Sector 10                              14
                      North Karachi Sector 8                               14
                      New Karachi                                          10
North Nazimabad       Block F                                             183
                      Block H                                             131
                      Block L                                             120
                      Block N                                             118
                      Block B                                              83
                      Block M                                              52
                      Block K                                              51
                      Block A                                              50
                      Block D                                              45
                      Block J                                              37
                      Shadman Town - Sector-14/B, Shadman                  36
                      Block I                                              34
                      Block G                                              32
                      Block C                                              12
                      Shadman                                               6
                      Shadman Town - Sector-14/A, Shadman                   6
                      North Nazimabad Block M                               4
                      Nagan Chowrangi                                       3
                      North Nazimabad Block H                               2
                      Allama Iqbal Town                                     1
                      Sakhi Hassan Chowrangi                                1
Rashid Minhas Road    Lucky One Apartment                                  41
                      Saima Royal Residency                                32
                      Lakhani Presidency                                    8
Scheme 33             Saadi Town                                          272
                      Sector 35-A                                         249
                      Saadi Garden                                        173
                      Punjabi Saudagar Society                            156
                      Falaknaz                                            110
                      Gulshan-E-Kaneez Fatima                              76
                      Sector 34-A                                          75
                      Sector 17-A                                          74
                      Sector 18-A                                          63
                      Daniyal Residency                                    62
                      Hansa Society                                        58
                      Meerut Society                                       57
                      Saadi Road                                           57
                      Karachi University Housing Society                   51
                      Sector 15-A                                          49
                      Sector 16-A                                          42
                      Zeenatabad                                           42
                      Gwalior Cooperative Housing Society                  40
                      Chapal Courtyard                                     39
                      Lakhani Fantasia                                     38
                      Chapal Sun City                                      33
                      Sector 19-A                                          33
                      Sadaf Cooperative Housing Society                    30
                      Sector 51-A                                          29
                      Sector 52-A                                          28
                      Grey Noor Tower                                      27
                      Sawera Enclave                                       27
                      Rafi Premier Residency                               26
                      Noman Residencia                                     25
                      Sania Corner                                         25
                      Sector 36-A                                          25
                      Cotton Export Cooperative Housing Society            23

In [145]:
df['sub_location'].isnull().sum()

np.int64(2464)

In [146]:
df.sample(100)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type
6492,"200 Sq Yd Villa For Sale Precinct-10A, Bahria ...","bahria town - precinct 10-a, bahria town karachi",Bahria Town,Precinct 10A,2.000000e+07,11111.11,1800.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house
5239,URGENT BUNGALOW FOR SALE,"dha phase 5, dha defence",DHA Defence,Phase 5,1.700000e+08,18888.89,9000.0,8,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
17199,SHAHJAHAN PRIDE FALAKNAZ DREAMS,"falaknaz dreams, malir",Malir,Falaknaz,6.000000e+06,8547.01,702.0,2,2,1.0,2.0,5.0,1.0,1,2,1,1,NaN,flat
13843,120 Yards Leased House For Sale Near Lasania R...,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 10A,3.700000e+07,34259.26,1080.0,6,7,2.0,NaN,3.0,1.0,0,1,1,0,2010.0,house
2570,Pre-Booking | Sawera Grand Enclave | OK Estate...,"gulzar-e-hijri, scheme 33",Scheme 33,NaN,9.500000e+06,10451.05,909.0,2,2,1.0,NaN,22.0,1.0,3,1,1,0,2031.0,flat
17341,1000 Yards Semi Furnished Bungalow For Sale,"dha phase 6, dha defence",DHA Defence,Phase 6,4.000000e+08,44444.44,9000.0,6,6,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
1073,Sawera Icon A New Landmark In The Heart Of Kar...,"saddar town, karachi",Saddar,NaN,2.250000e+07,13661.20,1647.0,3,3,1.0,NaN,23.0,1.0,4,1,1,0,2027.0,flat
16832,Want To Buy A Flat In Karachi?,"gulshan-e-iqbal - block 13/b, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13B,1.150000e+07,12777.78,900.0,2,2,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
14089,400 Sq. Yards Bungalow for Sale in Gulshan-e-I...,"gulshan-e-iqbal - block 6, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 6,1.350000e+08,37500.00,3600.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
9207,Saadi Garden West Open House For Sale Ground+One,"saadi garden, scheme 33",Scheme 33,Saadi Garden,2.100000e+07,19444.44,1080.0,4,4,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house
500,BRAND NEW FLAT FOR SALE,"north nazimabad - block n, north nazimabad",North Nazimabad,Block N,1.250000e+07,17806.27,702.0,2,2,0.0,NaN,NaN,1.0,0,0,1,0,2025.0,flat
21294,NHS Luxurious Apartment Deal,"navy housing scheme karsaz, karachi",Cantt,Navy Housing Scheme Karsaz,1.450000e+08,34499.17,4203.0,4,4,1.0,NaN,6.0,1.0,2,1,1,1,2024.0,flat
735,Highly-Desirable Prime Location Flat Available...,"sector 31 - punjabi saudagar city phase 2, sch...",Scheme 33,Punjabi Saudagar Society,7.500000e+06,8169.93,918.0,2,2,0.0,NaN,NaN,0.0,1,0,0,1,NaN,flat
4491,500 yards two unit bungalow for sale in DHA Ph...,"dha phase 8, dha defence",DHA Defence,Phase 8,1.700000e+08,37777.78,4500.0,6,6,3.0,NaN,NaN,3.0,0,1,1,0,2017.0,house
6138,250 Square Yard Ready To Move Villa In Precinc...,"bahria town - precinct 1, bahria town karachi",Bahria Town,Precinct 1,3.250000e+07,14444.44,2250.0,5,5,2.0,NaN,NaN,1.0,0,1,1,0,NaN,house
2478,HOUSE FOR SALE,"pak ideal cooperative housing society, karachi",Gulshan-e-Iqbal Town,NaN,1.200000e+08,22222.22,5400.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
2497,FLAT FOR SALE NOMAN GRAND CITY GULISTAN E JAUH...,"gulistan-e-jauhar - block 17, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 17,8.500000e+06,6794.56,1251.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
7784,1880 Square Feet Flat Available For Sale In Gu...,"gulshan-e-iqbal - block 1, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 1,2.800000e+07,14885.70,1881.0,4,4,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
4850,Full Floor For Sale,"badar commercial area, dha phase 5",DHA Defence,Phase 5,1.750000e+07,8758.76,1998.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
7176,Flat With Well Maintenance Security At Ayesha ...,"aisha manzil, karachi",Federal B Area,Block 7,1.350000e+07,15000.00,900.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
12503,House Of 2000 Square Yards Is Available In Con...,"dha phase 6, dha defence",DHA Defence,Phase 6,8.000000e+08,44444.44,18000.0,7,6,3.0,NaN,2.0,6.0,0,2,1,1,2013.0,house
21956,2 Bed DD Corner Park Facing Apartment with Ext...,"naya nazimabad, karachi",Naya Nazimabad,None,1.800000e+07,14388.49,1251.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
12854,"Rufi Green City, West Open ,3 Bed DD Apartment...","gulistan-e-jauhar - block 18, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 18,1.200000e+07,8492.57,1413.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
15913,120 Sq. Yd One Unit House For Sell In Rufi Fou...,"gulistan-e-jauhar, karachi",Gulistan-e-Jauhar,None,3.000000e+07,27777.78,1080.0,3,3,1.0,NaN,2.0,1.0,0,0,0,0,NaN,house
801,Best Apartment For Sale,"navy housing scheme karsaz, karachi",Cantt,Navy Housing Scheme Karsaz,1.300000e+08,28267.01,4599.0,5,5,2.0,NaN,NaN,10.0,0,2,1,1,2015.0,flat
9406,Modern 1 Bedroom 862 Square Feet Apartment Wit...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,3.620000e+07,41898.15,864.0,1,1,1.0,2.0,38.0,1.0,2,1,1,0,2024.0,flat
3031,Ready To Move 250 Square Yard 4 & 5 Bedroom DD...,"bahria town - precinct 8, bahria town karachi",Bahria Town,Precinct 8,3.500000e+07,15555.56,2250.0,5,5,2.0,NaN,NaN,1.0,0,1,1,0,NaN,house
14309,With ROOF 3 BED DD | 2 Rooms on ROOF,"garden east, jamshed town",Jamshed Town,Garden East,4.500000e+07,28089.89,1602.0,5,6,2.0,NaN,NaN,1.0,1,1,1,0,2020.0,flat
10903,Corner Brigadier House 300 Sq Yd House For Sal...,"askari 6, malir cantonment",Cantt,Askari 6,7.800000e+07,28888.89,2700.0,5,6,2.0,NaN,2.0,2.0,0,1,1,0,2026.0,house
6921,120 Square Yards House In Federal B Area Of Ka...,"federal b area - block 14, federal b area",Federal B Area,Block 14,3.100000e+07,28703.70,1080.0,5,5,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house
4911,450 Square Yards 60 ft wide location House For...,"gulshan-e-iqbal - block 18, gulshan-e-iqbal",Gulshan-e-Iqbal Town,NaN,1.250000e+08,30864.20,4050.0,6,5,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
22104,Prime Location 152 Square Yards House For sale...,"bahria town - precinct 11-b, bahria town - pre...",Bahria Town,Precinct 11B,1.450000e+07,10599.42,1368.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
15466,Gulistan E Johar Block 2 400 Sq Yd | Single St...,"gulistan-e-jauhar - block 2, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 2,6.750000e+07,18750.00,3600.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house
8446,Fair-Priced Prime Location 1000 Square Yards H...,"dha phase 6, dha defence",DHA Defence,Phase 6,3.400000e+08,37777.78,9000.0,6,6,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
21527,350sq yd 4Bed DDL Sports Villas with 100sq yd ...,"bahria sports city, bahria town karachi",Bahria Town,Bahria Sports City,1.800000e+07,5714.29,3150.0,4,4,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house
12316,Brand New Condition Tower 10 First Floor Corne...,"bahria apartments, bahria town karachi",Bahria Town,Bahria Apartments,9.500000e+06,9958.07,954.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,2022.0,flat
1051,125yds Double Storey Townhouse for Sale in DHA...,"dha city - sector 14b, dha city - sector 14",DHA City,NaN,1.750000e+07,15555.56,1125.0,4,5,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house
18556,Corner 400 Sq Yard House For Sale In Gulistan ...,"gulistan-e-jauhar - block 3, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 3,6.750000e+07,18750.00,3600.0,4,4,2.0,NaN,2.0,2.0,0,2,1,1,NaN,house
8704,1550 Square Feet Flat Up For sale In Gulistan-...,"gulistan-e-jauhar - block 11, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 11,2.350000e+07,15180.88,1548.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11190,300 SQ YARDS WELL MAINTAINED DOUBLE STOREY LEA...,"gulistan-e-jauhar - block 15, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 15,8.000000e+07,29629.63,2700.0,8,6,2.0,NaN,NaN,1.0,0,1,1,0,2020.0,house
12830,160 Square Yard Luxury Brand New Bungalow For ...,"naya nazimabad - block a, naya nazimabad",Naya Nazimabad,Block A,6.600000e+07,45833.33,1440.0,5,5,2.0,NaN,2.0,2.0,0,1,1,1,2025.0,house
8176,"In Bukhari Commercial Area Of Karachi, A 1050 ...","bukhari commercial area, dha phase 6",DHA Defence,Phase 6,1.700000e+07,16144.35,1053.0,3,3,3.0,NaN,NaN,1.0,0,0,0,0,2025.0,flat
12798,Prime Location Naya Nazimabad Flat Sized 1249 ...,"naya nazimabad, karachi",Naya Nazimabad,None,1.900000e+07,15187.85,1251.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
18702,House Is Available For Sale In North Nazimabad...,"north nazimabad - block h, north nazimabad",North Nazimabad,Block H,3.500000e+07,29914.53,1170.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
205,500 Sq Yard House Is Available For Sale,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,1.075000e+08,23888.89,4500.0,5,5,1.0,NaN,NaN,3.0,0,1,1,1,2022.0,house
16932,First Floor Flat Leased Parking Lift Main Road...,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 10A,2.800000e+07,14014.01,1998.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
2435,North Nazimabad - Block I 200 Square Yards Hou...,"north nazimabad - block i, north nazimabad",North Nazimabad,Block I,4.500000e+07,25000.00,1800.0,9,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
55,120 Sq Yard Block H Saima Arabian Villas Bangl...,"saima arabian villas, gadap town",Gadap,Surjani Town,1.350000e+07,12500.00,1080.0,3,2,1.0,NaN,NaN,0.0,0,0,1,1,2000.0,house
5272,SHAH Facial Town Flat For Sale,"shah faisal town, karachi",Shah Faisal,NaN,9.000000e+06,10000.00,900.0,2,2,1.0,NaN,NaN,1.0,2,1,1,0,2018.0,flat
4476,EMAAR OCEANFRONT 2BED SEAFACING AVALIABLE HOUS...,"emaar pearl towers, emaar crescent bay",DHA Defence,Phase 8,7.200000e+07,43956.04,1638.0,2,4,1.0,NaN,2.0,1.0,0,1,1,0,2021.0,house
7128,Jheel Park Facing Bungalow For Sale,"pechs block 6, pechs",Jamshed Town,Pechs,2.600000e+08,28888.89,9000.0,10,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
6147,Prime Location 2300 Square Feet Flat Situated ...,"amil colony, karachi",Jamshed Town,Amil Colony,5.950000e+07,25824.65,2304.0,5,5,1.0,NaN,NaN,0.0,1,0,0,1,NaN,flat
11980,125 Square Yards Villa Available For Sale in P...,"bahria town - ali block, bahria town - precinc...",Bahria Town,Ali Block,1.250000e+07,11111.11,1125.0,3,4,1.0,NaN,NaN,0.0,0,0,0,1,NaN,house
10892,Luxury 2 Bedroom Apartment with Private Plunge...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,8.090000e+07,39950.62,2025.0,2,3,1.0,NaN,38.0,1.0,4,1,1,1,2029.0,flat
7384,Apartment For sale,"national stadium colony, gulshan-e-iqbal town",Gulshan-e-Iqbal Town,National Stadium Colony,7.350000e+07,26259.38,2799.0,4,4,1.0,NaN,NaN,1.0,2,0,0,0,2026.0,flat
769,EMAAR CORAL TOWER 2 BEDROOM APARTMENT FOR SALE,"dha phase 8, dha defence",DHA Defence,Phase 8,5.250000e+07,34930.14,1503.0,2,2,1.0,NaN,NaN,1.0,0,1,1,1,NaN,flat
5217,120 With 80 Yards Extra Land Garden Space Sing...,"saima elite villas, malir",Malir,Saima Projects,2.500000e+07,23148.15,1080.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
14199,Instalment Based Flat Is Available For Sale In...,"scheme 33, karachi",Scheme 33,NaN,1.760000e+07,12146.31,1449.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
17084,2 Bed Drawing Dining Flat At Suparco Road Mosm...,"sawera enclave, suparco road",Scheme 33,Sawera Enclave,1.350000e+07,10791.37,1251.0,2,2,1.0,4.0,6.0,1.0,1,1,1,1,NaN,flat
1738,Elevate Your Lifestyle With A Lavish 3 Bedroom...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,1.034000e+08,56595.51,1827.0,3,3,1.0,NaN,39.0,2.0,2,1,1,1,2024.0,flat
11123,"Golden Tower, Ayesha Manzil ,3 Bed DD Flat For...","federal b area - block 10, federal b area",Federal B Area,Block 10,2.050000e+07,16386.89,1251.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
11664,Highly-Desirable Prime Location Flat Available...,"north nazimabad - block m, north nazimabad",North Nazimabad,Block M,1.850000e+07,11232.54,1647.0,3,3,1.0,NaN,5.0,1.0,1,1,1,1,2025.0,flat
4106,1000yards Beautiful Bungalow Available On Khy ...,"dha phase 7, dha defence",DHA Defence,Phase 7,2.800000e+08,31111.11,9000.0,6,6,2.0,NaN,2.0,4.0,0,2,0,0,2015.0,house
14538,Flat For Sale Saima Meadows Sector Y Gulshan-e...,"gulshan-e-maymar - sector y, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,1.050000e+07,8771.93,1197.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
2689,Buy Prime Location 200 Square Feet House At Hi...,"bahria town - precinct 11-a, bahria town - pre...",Bahria Town,Precinct 11A,1.800000e+07,10000.00,1800.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house
9841,SAMRINA GRAND APARTMENTS FOR SALE,"samrina grand, kathiawar society",Scheme 33,Kathiawar Society,2.000000e+07,11454.75,1746.0,3,4,1.0,NaN,16.0,6.0,3,2,1,0,2017.0,flat
19624,Aohs 800 yard house general colony national st...,"army officers housing society, faisal cantonment",Cantt,NaN,8.500000e+08,118055.56,7200.0,7,7,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
9839,75 SQUARE YARDS G+2 HOUSE FOR SALE,"pechs block 6, pechs",Jamshed Town,Pechs,2.250000e+07,33333.33,675.0,5,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
3317,3 Bed DD Flat for Sale in Saima Jinnah Avenue ...,"saima jinnah avenue, university road",University Road,Saima Jinnah Avenue,3.300000e+07,15027.32,2196.0,3,4,1.0,NaN,11.0,2.0,4,1,1,0,2025.0,flat
4206,Flat For Sale In Hina Garden Gulistan-e-Jauhar...,"gulistan-e-jauhar - block 19, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 19,1.100000e+07,8148.15,1350.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,2025.0,flat
2319,BANK LOAN APPLICABLE CANTT. VEIW LODGES LUXURY...,"cantt view lodges, malir link to super highway",Malir,Malir Link To Super Highway,1.750000e+07,14619.88,1197.0,2,3,0.0,NaN,NaN,1.0,0,0,0,0,NaN,flat
7827,HOUSE FOR SALE,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,9.100000e+07,28888.89,3150.0,4,5,1.0,NaN,1.0,1.0,0,1,1,1,2019.0,house
15597,Gulistan Johar Block 3 Brand New Double Story ...,"gulistan-e-jauhar - block 15, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 15,6.300000e+07,29166.67,2160.0,6,6,2.0,NaN,1.0,4.0,0,2,1,0,1990.0,house
19811,This Is Your Chance To Buy House In Gulshan-e-...,"gulshan-e-iqbal - block 10, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 10,9.500000e+07,21630.24,4392.0,7,6,2.0,NaN,2.0,3.0,0,0,1,1,2008.0,house
21672,House For Sale Shah Faisal Town Near Malir Halt,"airport road, karachi",Malir,Airport,4.950000e+07,27500.00,1800.0,8,7,0.0,NaN,NaN,1.0,0,0,1,1,NaN,house
8659,Naya Nazimabad 2 Bed DD Elegant And Luxury Bra...,"naya nazimabad, karachi",Naya Nazimabad,None,1.950000e+07,15587.53,1251.0,2,3,1.0,8.0,15.0,1.0,3,1,1,1,2025.0,flat
16282,House Of 375 Square Yards Available For Sale I...,"askari 6, malir cantonment",Cantt,Askari 6,7.550000e+07,22370.37,3375.0,5,5,1.0,NaN,3.0,1.0,0,1,1,1,2003.0,house
6175,In Naya Nazimabad - Block C 120 Square Yards H...,"naya nazimabad - block c, naya nazimabad",Naya Nazimabad,Block C,4.250000e+07,39351.85,1080.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
21190,"RENOVATED 2 BED D/D FLAT FOR SALE IN BLOCK 17,...","gulshan-e-iqbal - block 17, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 17,1.450000e+07,17139.48,846.0,2,3,1.0,2.0,4.0,1.0,0,0,0,0,1990.0,flat
16445,Prime Location 900 Square Feet Flat In Gulshan...,"gulshan-e-iqbal - block 4, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 4,1.000000e+07,11111.11,900.0,2,2,1.0,NaN,NaN,1.0,1,1,1,1,2022.0,flat
12286,LEASED BANK LOAN APPLICABLE BRAND NEW 2 BED DR...,"gulzar-e-hijri, scheme 33",Scheme 33,NaN,1.200000e+07,10928.96,1098.0,2,2,2.0,NaN,3.0,1.0,2,1,1,1,2024.0,flat
14096,LUXURY APARTMENT FOR SALE Hill Park With Roof ...,"hill park, karachi",Jamshed Town,Hill Park,5.250000e+07,18756.70,2799.0,4,4,1.0,2.0,1.0,1.0,1,1,1,1,2022.0,flat
15727,Prime 400 SQ YARD Corner Structure Best Invest...,"saadi town - block 4, saadi town",Scheme 33,Saadi Town,4.300000e+07,11944.44,3600.0,6,6,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house
5288,Looking For A Flat In Rana Presidency,"rana presidency, gulistan-e-jauhar - block 1",Gulistan-e-Jauhar,Block 1,3.100000e+07,16639.83,1863.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
5387,House for Sale 400yds North Nazimabad Block L,"north nazimabad - block l, north nazimabad",North Nazimabad,Block L,8.250000e+07,22916.67,3600.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
1035,FULLY RENOVATED 3 BED DD FLAT AVAILABLE FOR SALE,"gulshan-e-iqbal - block 13-d2, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13D2,1.500000e+07,11111.11,1350.0,3,3,1.0,1.0,6.0,3.0,1,1,1,1,2026.0,flat
7133,A Stunning Prime Location House Is Up For Grab...,"gulshan-e-usman phase 1 - block 2, gulshan-e-u...",Scheme 33,Gulshan-E-Usman Housing Society,3.500000e+07,16203.70,2160.0,6,6,1.0,NaN,2.0,1.0,0,1,1,1,NaN,house
12602,"West Open Corner, Well Maintained 500 Sq Yds B...","falcon complex new malir, malir",Malir,Falcon Complex New Malir,1.075000e+08,23888.89,4500.0,5,5,1.0,NaN,2.0,2.0,0,1,1,0,2016.0,house
19654,Defence 500 Ii Owner Built Well Mainted Bungal...,"dha phase 2, dha defence",DHA Defence,Phase 2,1.700000e+08,37777.78,4500.0,5,6,2.0,NaN,NaN,0.0,0,1,0,0,NaN,house
22030,"BURJ-UL-HARMAIN,4 BED DRAWING & DINING, Spacio...","burj-ul-harmain, university road",University Road,Burj-Ul-Harmain,3.050000e+07,16061.08,1899.0,4,4,0.0,NaN,NaN,1.0,1,0,1,0,2024.0,flat
11109,Apartment For Sale,"dha phase 5, dha defence",DHA Defence,Phase 5,1.500000e+07,16666.67,900.0,2,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat
2043,The 240 Signature Home!,"saadi town - block 4, saadi town",Scheme 33,Saadi Town,2.850000e+07,13194.44,2160.0,4,5,2.0,NaN,2.0,2.0,0,1,1,1,2022.0,house
7179,For Sale 3 Bed DD Flat 1St Floor G+3 Building ...,"askari 5, malir cantonment",Cantt,Askari 5,3.900000e+07,17402.95,2241.0,3,3,1.0,1.0,3.0,2.0,0,1,1,0,2014.0,flat
16976,Bungalow Is Available For Sale,"dha phase 6, dha defence",DHA Defence,Phase 6,1.300000e+09,42483.66,30600.0,10,6,4.0,NaN,3.0,15.0,0,6,1,1,2013.0,house
20119,"Clifton Block 9, 1000 Square Feet, Brand New A...","clifton - block 9, clifton",Clifton,Clifton Block 9,5.500000e+07,55055.06,999.0,2,2,1.0,NaN,NaN,1.0,2,0,1,0,NaN,flat
7525,"Falcon Complex, New Malir Spacious 350 Square ...","falcon complex new malir, malir",Malir,Falcon Complex New Malir,8.850000e+07,28095.24,3150.0,4,5,2.0,NaN,NaN,0.0,0,0,0,1,NaN,house
10364,House For sale In Karachi,"gulshan-e-iqbal - block 17, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 17,1.100000e+08,39426.52,2790.0,6,6,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house
12271,Ideal Family Apartment 3 Bed Flat in Askari 5 ...,"askari 5 - sector j, askari 5",Cantt,Askari 5,4.250000e+07,16686.30,2547.0,3,4,2.0,NaN,NaN,2.0,0,1,1,1,2022.0,flat
3997,HOUSE AVAILABLE FOR SALE,"bufferzone - sector 15-a/4, buffer zone",North Karachi,Buffer Zone,2.300000e+07,21296.30,1080.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house
8776,A 1600 Square Feet Flat Is Up For Grabs In Jin...,"metropolis residency, jinnah avenue",Jinnah Avenue,Metropolis Residency,3.000000e+07,18726.59,1602.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat

In [147]:
df['completion_year'].value_counts()

completion_year
2025.0    2113
2026.0    2026
2024.0    1410
2023.0     852
2022.0     741
2020.0     630
2021.0     417
2015.0     365
2018.0     343
2000.0     303
2019.0     271
2010.0     262
2028.0     208
2016.0     145
2017.0     141
2027.0     127
2005.0     124
2012.0     117
2030.0     115
2029.0     109
2008.0      77
2014.0      77
1990.0      65
2013.0      59
2031.0      44
2011.0      41
2009.0      39
2002.0      34
1999.0      28
2006.0      27
2007.0      25
2001.0      21
1995.0      20
2003.0      17
2004.0      15
1996.0      15
2032.0      14
1992.0      11
1985.0      10
1998.0       8
1980.0       8
1988.0       7
1994.0       5
1997.0       5
2033.0       4
1970.0       4
1993.0       4
1989.0       3
1972.0       1
1968.0       1
1960.0       1
1979.0       1
1918.0       1
1965.0       1
1975.0       1
1976.0       1
Name: count, dtype: int64

In [148]:
CURRENT_YEAR = 2026


df["property_age"] = CURRENT_YEAR - df["completion_year"]

# This section handles Create Age Category.def age_category(age):
    if pd.isna(age):
        return np.nan
    elif age < 0:
        return "Under Construction"
    elif age == 0:
        return "New"
    elif age <= 5:
        return "Relatively New"
    elif age <= 10:
        return "Moderately Old"
    else:
        return "Old"

df["age_category"] = df["property_age"].apply(age_category)

# This section handles Check Distribution.print(df["age_category"].value_counts(dropna=False))

age_category
NaN                   11245
Relatively New         5533
New                    2026
Old                    1804
Moderately Old         1530
Under Construction      621
Name: count, dtype: int64

In [149]:
df.sample(6)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category
9931,Spacious Flat Is Available In Askari 5 - Secto...,"askari 5 - sector j, askari 5",Cantt,Askari 5,45000000.0,16666.67,2700.0,3,3,1.0,NaN,NaN,1.0,0,1,1,1,2022.0,flat,4.0,Relatively New
20227,DEFENCE 1200 YARDS BUNGALOW FOR SALE,"dha phase 1, dha defence",DHA Defence,Phase 1,145000000.0,13425.93,10800.0,3,3,1.0,NaN,NaN,3.0,0,1,1,0,1995.0,house,31.0,Old
16587,Beautiful West Open Bungalow For Sale,"dha phase 5, dha defence",DHA Defence,Phase 5,140000000.0,31111.11,4500.0,5,5,3.0,NaN,2.0,4.0,0,1,1,1,2024.0,house,2.0,Relatively New
10172,Your Dream Apartment Is Now Affordable! Book T...,"scheme 33, karachi",Scheme 33,NaN,12000000.0,10101.01,1188.0,2,2,1.0,5.0,22.0,1.0,1,1,1,1,2032.0,flat,-6.0,Under Construction
20061,BRAND NEW APPARTMENT AVAILABLE FOR SALE,"askari 6, malir cantonment",Cantt,Askari 6,40000000.0,13550.14,2952.0,4,5,1.0,1.0,13.0,1.0,1,1,1,1,2025.0,flat,1.0,Relatively New
20689,235sq Yd Villas At Precinct-31 Close To Galler...,"bahria town - precinct 31, bahria town karachi",Bahria Town,Precinct 31,15400000.0,7281.32,2115.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN

In [150]:
# This section handles Group by location, calculate mean price and count, then sort by price.location_summary = (
    df.groupby("sub_location")["price"]
    .agg(count="count", mean_price="mean")
    .sort_values(by="mean_price", ascending=False)
)

display(location_summary)

                                                 count    mean_price
sub_location
Dr Daud Pota Road                                    1  6.855000e+08
National Stadium Colony                             14  5.877500e+08
Falcon Complex Faisal                               14  3.482143e+08
Kda Scheme 1 Extension                              11  3.063636e+08
Kda Officers Society                                43  2.998837e+08
Dawood Society                                      13  2.361538e+08
Navy Housing Scheme Karsaz                         131  2.160687e+08
Kda Scheme 1                                        87  2.139816e+08
Mohammad Ali Society                                18  2.035833e+08
Precinct 3                                           2  1.800000e+08
Dohs Phase 1                                        51  1.732922e+08
Phase 2                                             54  1.728519e+08
Phase 6                                            907  1.654388e+08
Phase 8                                           2241  1.629607e+08
Adamjee Nagar                                       16  1.604688e+08
Smchs - Sindhi Muslim Society                       45  1.525667e+08
Phase 7                                            296  1.498338e+08
Precinct 18                                          5  1.480000e+08
Dohs Phase 2                                        11  1.450000e+08
Phase 5                                            427  1.392705e+08
Phase 8 Extension                                   12  1.383333e+08
Amir Khusro                                         36  1.379028e+08
Latifi Cooperative Housing Society                   8  1.371875e+08
Phase 1                                             65  1.351646e+08
Hill Park                                           27  1.338519e+08
Precinct 7                                          14  1.310714e+08
Phase 5 Extension                                   21  1.260476e+08
Phase 4                                            168  1.244036e+08
Pechs                                              284  1.210616e+08
Clifton Block 5                                     35  1.107143e+08
Kda Overseas Bungalows                               7  1.057857e+08
Falcon Complex New Malir                           516  1.017888e+08
Clifton Block 7                                     40  9.948750e+07
Shaheed Millat Road                                179  9.427263e+07
Block 13D                                           58  8.942241e+07
Clifton Block 6                                     11  8.827273e+07
Cp Barar Society, Gulshan-E-Iqbal Town              14  8.614286e+07
Darakhshan Villas, Dha Phase 6                       7  8.571429e+07
Block 5                                             91  8.439121e+07
Block 6                                             73  8.423011e+07
Block F                                            183  8.324153e+07
Bath Island                                        128  8.288281e+07
Clifton Block 4                                     52  8.256154e+07
Clifton Block 8                                     89  8.195955e+07
Precinct 17                                         26  8.139615e+07
Askari 4                                            34  7.881176e+07
Bahadurabad                                        121  7.627273e+07
Block I                                             34  7.006765e+07
Block 9                                             50  6.858800e+07
Block 13D1                                          65  6.829692e+07
Phase 7 Extension                                  147  6.597143e+07
Bahria Hills                                        54  6.579444e+07
Shahra-E-Qaideen                                    14  6.532143e+07
Askari 6                                           585  6.442718e+07
Block 4                                            123  6.404634e+07
Block N                                            118  6.352119e+07
Clifton Block 9                                     94  6.311170e+07
Gulshan-E-Jamal                                     13  6.203846e+07
Block 7                                            224  6.139542e+07
Clifton Block 3                                     11  6.090909e+07
Block L                                            120  6.088750e+07
Block A                                            145  5.973931e+07
Askari 5                                           626  5.959105e+07
Meerut Society                                      57  5.908596e+07
Lakhani Presidency                                   8  5.843750e+07
Block 3                                             96  5.814583e+07
Khalid Bin Walid Road                              124  5.791532e+07
Precinct 9                                          11  5.707273e+07
Block 10                                           135  5.661370e+07
Block B                                            150  5.515067e+07
Block J                                             37  5.509189e+07
Hsj Icon                                             3  5.500000e+07
Clifton Block 2                                    160  5.489750e+07
Block D                                            113  5.439204e+07
Block 4A                                            13  5.415385e+07
Precinct 4                                          49  5.411020e+07
Block 2                                            169  5.401538e+07
Gizri                                               11  5.357273e+07
Sharfabad                                           47  5.323404e+07
Block C                                             99  5.206970e+07
Lucky One Apartment                                 41  5.102439e+07
Amil Colony                                         29  5.067241e+07
Qayyumabad                                          16  5.057500e+07
Block H                                            131  5.040076e+07
Frere Town                                          43  5.017442e+07
Central Information Cooperative Housing Society     10  4.889000e+07
Cosmopolitan Society                                17  4.755882e+07
Block 15                                           214  4.659206e+07
Bahria Paradise                                     76  4.555921e+07
Sector 17-A                                         74  4.526959e+07
Block 11                                            96  4.525312e+07
Dhoraji Colony                                      59  4.471186e+07
Clifton Block 1                                     87  4.455287e+07
Block 14                                           191  4.387696e+07
Tariq Road                                          39  4.242308e+07
Block 12                                           171  4.234737e+07
Block 13                                           183  4.183989e+07
Sector 35-A                                        249  4.082490e+07
Block 16                                           113  4.022965e+07
Garden East                                         34  3.923529e+07
Karachi Administration Employees Society            46  3.884130e+07
Gwalior Cooperative Housing Society                 40  3.669000e+07
Precinct 8                                          94  3.571596e+07
Callachi Cooperative Housing Society               302  3.544768e+07
Block 10A                                          144  3.494792e+07
Sector 24-A                                         22  3.490909e+07
Muslimabad Society                                  12  3.441667e+07
Block 1                                            233  3.428841e+07
Golf City                                            2  3.425000e+07
Precinct 1                                          70  3.415857e+07
Karachi Cantonment                                   1  3.400000e+07
Malir Cantonment                                    20  3.393125e+07
Metropolis Residency                               112  3.280893e+07
Bahria Town                                         62  3.252458e+07
Allama Iqbal Town                                    1  3.250000e+07
Saima Luxury Belt                                   33  3.225758e+07
Sector 16-A                                         42  3.189643e+07
Phase 2 Extension                                   69  3.181594e+07
Saima Projects                                      37  3.172432e+07
Block 16A                                           14  3.167857e+07
Saadi Town                                         272  3.115956e+07
North Nazimabad Block H                              2  3.100000e+07
Precinct 6                                          63  3.079841e+07
Hansa Society                                       58  3.069310e+07
Shadman Town - Sector-14/A, Shadman                  6  3.066667e+07
Sector 52-A                                         28  2.975714e+07
North Karachi Sector 11                             80  2.948000e+07
North Karachi Sector 10                             14  2.940714e+07
Saima Jinnah Avenue                                 50  2.927400e+07
Saima Royal Residency                               32  2.917188e+07
Shadman Town - Sector-14/B, Shadman                 36  2.907778e+07
Block 13C                                           39  2.895385e+07
Cotton Export Cooperative Housing Society           23  2.895217e+07
Parsi Colony                                        21  2.890476e+07
Nazimabad 2                                          5  2.890000e+07
Sector 15-A                                         49  2.882857e+07
Block 3A                                           119  2.848193e+07
Soldier Bazar                                       22  2.779545e+07
Andaleeb Cooperative Housing Society                13  2.776154e+07
Sadaf Cooperative Housing Society                   30  2.742540e+07
Block 13D2                                          76  2.741053e+07
Model Colony                                        96  2.740521e+07
Buffer Zone                                        105  2.724667e+07
Sector 19-A                                         33  2.719697e+07
Punjabi Saudagar Society                           156  2.718269e+07
Block 17                                           158  2.712753e+07
Precinct 16                                         37  2.701892e+07
Sector 22-A                                         18  2.694444e+07
North Karachi Sector 9                              26  2.658462e+07
Block 20                                            35  2.647429e+07
Block 19                                           108  2.626296e+07
Nazimabad 3                                         20  2.620500e+07
Nazimabad 4                                         22  2.545455e+07
Gulshan-E-Maymar                                   468  2.539615e+07
Chapal Sun City                                     33  2.534848e+07
Aman Golf View                                      38  2.517368e+07
North Karachi Sector 8                              14  2.510000e+07
Block 8                                             30  2.491667e+07
Al Madni Heights                                    41  2.487805e+07
Block 13A                                           41  2.480244e+07
Sector 34-A                                         75  2.474267e+07
Zeenatabad                                          42  2.439048e+07
Sector 51-A                                         29  2.436897e+07
Defence Skyline, Shaheed-E-Millat Expressway        12  2.434167e+07
Quaid Villas                                        72  2.397361e+07
Sadat-E-Amroha Cooperative Housing Society          10  2.373000e+07
Musalmanan-E-Punjab Cooperative Housing Society     22  2.362727e+07
Nazimabad 5                                          9  2.348889e+07
Sector 36-A                                         25  2.325600e+07
Airport                                             45  2.254889e+07
Oasis Park Residencia                                6  2.241667e+07
Gulshan-E-Kaneez Fatima                             76  2.192632e+07
Sumaira Sky Tower                                   14  2.189286e+07
Shahrah-E-Pakistan                                  10  2.171000e+07
Jamshed Road                                        61  2.128197e+07
Gulshan-E-Roomi                                     43  2.106977e+07
Saadi Garden                                       173  2.105723e+07
Sector 18-A                                         63  2.091905e+07
Saadi Road                                          57  2.065439e+07
Karachi University Housing Society                  51  2.063922e+07
Roomi Residency                                     33  2.040606e+07
Bahria Sports City                                 128  2.033438e+07
Precinct 2                                          13  2.020769e+07
Malir Link To Super Highway                         82  2.014634e+07
Gulshan-E-Usman Housing Society                     12  1.962500e+07
Precinct 10A                                        92  1.953804e+07
Burj-Ul-Harmain                                    143  1.948881e+07
Shadman                                              6  1.911667e+07
Block 13D3                                          32  1.881875e+07
Iqbal Villas                                        60  1.873500e+07
Kathiawar Society                                   14  1.864286e+07
Block M                                             75  1.849333e+07
Grey Noor Tower                                     27  1.830741e+07
Green Town / Rafah-E-Aam Belt                       24  1.830167e+07
City Tower And Shopping Mall                        17  1.801176e+07
North Karachi Sector 7                              38  1.797632e+07
Shah Faisal Colony                                   1  1.750000e+07
Sawera Enclave                                      27  1.740741e+07
Precinct 11A                                        85  1.721647e+07
Rafi Premier Residency                              26  1.700192e+07
Taloo Gold Residency                                10  1.605000e+07
Saima Villas                                        72  1.603056e+07
Gulzar-E-Hijri                                      10  1.553000e+07
Block 13B                                           24  1.546042e+07
Chapal Uptown                                       16  1.531250e+07
Falaknaz                                           228  1.514131e+07
Precinct 31                                         84  1.512500e+07
Precinct 27                                         61  1.494754e+07
Safoora Goth                                         8  1.451250e+07
Fatima Ali Towers                                   19  1.438421e+07
Block 18                                           132  1.437121e+07
Ali Block                                          109  1.433716e+07
Precinct 12                                         21  1.420000e+07
Precinct 11B                                        74  1.382297e+07
Chapal Courtyard                                    39  1.322308e+07
Sakhi Hassan Chowrangi                               1  1.300000e+07
Noman Residencia                                    25  1.298400e+07
Safari Enclave Apartments                           18  1.290556e+07
North Karachi Sector 5                              49  1.288980e+07
Yousaf Goth                                         11  1.282727e+07
Precinct 10B                                        68  1.277794e+07
Kda Employees Society                               16  1.261250e+07
North Nazimabad Block M                              4  1.250000e+07
Memon Goth                                          55  1.203000e+07
Precinct 15                                         22  1.192273e+07
Gohar Green City Cluster                            42  1.157143e+07
Daniyal Residency                                   62  1.144113e+07
Mehmoodabad                                         19  1.140526e+07
Bahria Apartments                                  120  1.129000e+07
Sania Corner                                        25  1.124760e+07
Block K                                             51  1.121961e+07
Block G                                             32  1.110312e+07
Surjani Town                                       273  1.109066e+07
New Karachi                                         10  1.107000e+07
Precinct 19                                         34  1.103235e+07
Jamia Millia Road                                   20  1.099000e+07
Lakhani Fantasia                                    38  1.039079e+07
Nazimabad 1                                          8  9.937500e+06
Korangi Industrial Area                             23  9.891304e+06
Rabia Enclave                                        9  9.527778e+06
Federal Government Employees Housing Foundation     20  8.605000e+06
Shamsi / Al-Falah Belt                              27  8.427778e+06
Falaknaz Plaza                                       1  8.200000e+06
Bahria Heights                                      57  7.505263e+06
Private High-Rises                                  92  7.445652e+06
P & T Colony                                        10  6.450000e+06
Malir Town Residency                                13  6.276923e+06
Nagan Chowrangi                                      3  5.333333e+06
Golden Town                                         16  4.993750e+06
Allahwala Town                                     113  3.802743e+06
Mateen Complex                                      34  2.554412e+06

In [151]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Bahria Sports City                                  128
                      Bahria Apartments                                   120
                      Ali Block                                           109
                      Precinct 8                                           94
                      Precinct 10A                                         92
                      Private High-Rises                                   92
                      Precinct 11A                                         85
                      Precinct 31                                          84
                      Bahria Paradise                                      76
                      Precinct 11B                                         74
                      Quaid Villas                                         72
                      Precinct 1                                           70
                      Precinct 10B                                         68
                      Precinct 6                                           63
                      Bahria Town                                          62
                      Precinct 27                                          61
                      Iqbal Villas                                         60
                      Bahria Heights                                       57
                      Bahria Hills                                         54
                      Precinct 4                                           49
                      Precinct 16                                          37
                      Precinct 19                                          34
                      Precinct 17                                          26
                      Precinct 15                                          22
                      Precinct 12                                          21
                      Precinct 7                                           14
                      Precinct 2                                           13
                      Precinct 9                                           11
                      Precinct 18                                           5
                      Golf City                                             2
                      Precinct 3                                            2
Bin Qasim Town        Mateen Complex                                       34
Cantt                 Askari 5                                            626
                      Askari 6                                            585
                      Navy Housing Scheme Karsaz                          131
                      Dohs Phase 1                                         51
                      Gulshan-E-Roomi                                      43
                      Malir Cantonment                                     20
                      Dohs Phase 2                                         11
                      P & T Colony                                         10
                      Dr Daud Pota Road                                     1
                      Karachi Cantonment                                    1
Civil Lines           Hsj Icon                                              3
Clifton               Clifton Block 2                                     160
                      Bath Island                                         128
                      Clifton Block 9                                      94
                      Clifton Block 8                                      89
                      Clifton Block 1                                      87
                      Clifton Block 4                                      52
                      Frere Town                                           43
                      Clifton Block 7                                      40
                      Clifton Block 5                                      35
                      Clifton Block 3                                      11
                      Clifton Block 6                                      11
                      Gizri                                                11
DHA Defence           Phase 8                                            2241
                      Phase 6                                             907
                      Phase 5                                             427
                      Phase 7                                             296
                      Phase 4                                             168
                      Phase 7 Extension                                   147
                      Phase 2 Extension                                    69
                      Phase 1                                              65
                      Phase 2                                              54
                      Phase 5 Extension                                    21
                      Phase 8 Extension                                    12
                      Darakhshan Villas, Dha Phase 6                        7
Federal B Area        Block 10                                             75
                      Block 12                                             54
                      Block 13                                             41
                      Block 11                                             29
                      Block 14                                             23
                      Block 16                                             19
                      Block 9                                              19
                      Block 15                                             18
                      Block 8                                              18
                      Block 19                                             17
                      Block 6                                              12
                      Block 7                                              11
                      Block 20                                             10
                      Shahrah-E-Pakistan                                   10
Gadap                 Gulshan-E-Maymar                                    468
                      Surjani Town                                        273
                      Memon Goth                                           55
Gulistan-e-Jauhar     Block 15                                            196
                      Block 14                                            152
                      Block 13                                            132
                      Block 18                                            132
                      Block 7                                             122
                      Block 3A                                            119
                      Block 12                                            117
                      Block 17                                            114
                      Block 2                                              91
                      Block 19                                             74
                      Block 16                                             71
                      Block 3                                              57
                      Block 1                                              39
                      Block 10                                             39
                      Askari 4                                             34
                      Block 11                                             33
                      Block 4                                              31
                      Block 20                                             25
                      Block 16A                                            14
                      Block 9                                              14
                      Block 8                                              12
                      Latifi Cooperative Housing Society                    8
                      Safoora Goth                                          8
                      Block 5                                               7
                      Kda Overseas Bungalows                                7
                      Block 6                                               4
Gulshan-e-Iqbal Town  Callachi Cooperative Housing Society                302
                      Block 1                                             194
                      Block 10A                                           144
                      Bahadurabad                                         121
                      Block 4                                              92
                      Block 7                                              91
                      Kda Scheme 1                                         87
                      Block 5                                              84
                      Block 2                                              78
                      Block 13D2                                           76
                      Block 13D1                                           65
                      Dhoraji Colony                                       59
                      Block 13D                                            58
                      Block 6                                              57
                      Sharfabad                                            47
                      Block 17                                             44
                      Kda Officers Society                                 43
                      Block 13A                                            41
                      Block 13C                                            39
                      Block 3                                              39
                      Block 11                                             34
                      Block 13D3                                           32
                      Block 13B                                            24
                      Block 16                                             23
                      Block 10                                             21
                      Mohammad Ali Society                                 18
                      Block 19                                             17
                      Block 9                                              17
                      Adamjee Nagar                                        16
                      Block 14                                             16
                      Cp Barar Society, Gulshan-E-Iqbal Town               14
                      National Stadium Colony                              14
                      Block 4A                                             13
                      Dawood Society                                       13
                      Gulshan-E-Jamal                                      13
                      Kda Scheme 1 Extension                               11
                      Block 13                                             10
Jamshed Town          Pechs                                               284
                      Shaheed Millat Road                                 179
                      Khalid Bin Walid Road                               124
                      Jamshed Road                                         61
                      Karachi Administration Employees Society             46
                      Smchs - Sindhi Muslim Society                        45
                      Tariq Road                                           39
                      Amir Khusro                                          36
                      Garden East                                          34
                      Amil Colony                                          29
                      Hill Park                                            27
                      Soldier Bazar                                        22
                      Parsi Colony                                         21
                      Mehmoodabad                                          19
                      Cosmopolitan Society                                 17
                      Shahra-E-Qaideen                                     14
                      Defence Skyline, Shaheed-E-Millat Expressway         12
                      Muslimabad Society                                   12
Jinnah Avenue         Metropolis Residency                                112
                      Aman Golf View                                       38
                      Roomi Residency                                      33
Korangi               Allahwala Town                                      113
                      Korangi Industrial Area                              23
                      Kda Employees Society                                16
                      Qayyumabad                                           16
Malir                 Falcon Complex New Malir                            516
                      Falaknaz                                            118
                      Model Colony                                         96
                      Malir Link To Super Highway                          82
                      Airport                                              45
                      Saima Projects                                       37
                      Jamia Millia Road                                    20
                      Golden Town                                          16
                      Malir Town Residency                                 13
Naya Nazimabad        Block A                                              95
                      Block C                                              87
                      Block D                                              68
                      Block B                                              67
                      Block M                                              23
Nazimabad             Nazimabad 4                                          22
                      Nazimabad 3                                          20
                      Nazimabad 5                                           9
                      Nazimabad 1                                           8
                      Nazimabad 2                                           5
North Karachi         Buffer Zone                                         105
                      North Karachi Sector 11                              80
                      North Karachi Sector 5                               49
                      North Karachi Sector 7                               38
                      North Karachi Sector 9                               26
                      North Karachi Sector 10                              14
                      North Karachi Sector 8                               14
                      New Karachi                                          10
North Nazimabad       Block F                                             183
                      Block H                                             131
                      Block L                                             120
                      Block N                                             118
                      Block B                                              83
                      Block M                                              52
                      Block K                                              51
                      Block A                                              50
                      Block D                                              45
                      Block J                                              37
                      Shadman Town - Sector-14/B, Shadman                  36
                      Block I                                              34
                      Block G                                              32
                      Block C                                              12
                      Shadman                                               6
                      Shadman Town - Sector-14/A, Shadman                   6
                      North Nazimabad Block M                               4
                      Nagan Chowrangi                                       3
                      North Nazimabad Block H                               2
                      Allama Iqbal Town                                     1
                      Sakhi Hassan Chowrangi                                1
Rashid Minhas Road    Lucky One Apartment                                  41
                      Saima Royal Residency                                32
                      Lakhani Presidency                                    8
Scheme 33             Saadi Town                                          272
                      Sector 35-A                                         249
                      Saadi Garden                                        173
                      Punjabi Saudagar Society                            156
                      Falaknaz                                            110
                      Gulshan-E-Kaneez Fatima                              76
                      Sector 34-A                                          75
                      Sector 17-A                                          74
                      Sector 18-A                                          63
                      Daniyal Residency                                    62
                      Hansa Society                                        58
                      Meerut Society                                       57
                      Saadi Road                                           57
                      Karachi University Housing Society                   51
                      Sector 15-A                                          49
                      Sector 16-A                                          42
                      Zeenatabad                                           42
                      Gwalior Cooperative Housing Society                  40
                      Chapal Courtyard                                     39
                      Lakhani Fantasia                                     38
                      Chapal Sun City                                      33
                      Sector 19-A                                          33
                      Sadaf Cooperative Housing Society                    30
                      Sector 51-A                                          29
                      Sector 52-A                                          28
                      Grey Noor Tower                                      27
                      Sawera Enclave                                       27
                      Rafi Premier Residency                               26
                      Noman Residencia                                     25
                      Sania Corner                                         25
                      Sector 36-A                                          25
                      Cotton Export Cooperative Housing Society            23

In [152]:
counts = df.groupby('sub_location')['sub_location'].transform('count')


df['sub_location'] = np.where(counts > 4, df['sub_location'], np.nan)

In [153]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Bahria Sports City                                  128
                      Bahria Apartments                                   120
                      Ali Block                                           109
                      Precinct 8                                           94
                      Precinct 10A                                         92
                      Private High-Rises                                   92
                      Precinct 11A                                         85
                      Precinct 31                                          84
                      Bahria Paradise                                      76
                      Precinct 11B                                         74
                      Quaid Villas                                         72
                      Precinct 1                                           70
                      Precinct 10B                                         68
                      Precinct 6                                           63
                      Bahria Town                                          62
                      Precinct 27                                          61
                      Iqbal Villas                                         60
                      Bahria Heights                                       57
                      Bahria Hills                                         54
                      Precinct 4                                           49
                      Precinct 16                                          37
                      Precinct 19                                          34
                      Precinct 17                                          26
                      Precinct 15                                          22
                      Precinct 12                                          21
                      Precinct 7                                           14
                      Precinct 2                                           13
                      Precinct 9                                           11
                      Precinct 18                                           5
Bin Qasim Town        Mateen Complex                                       34
Cantt                 Askari 5                                            626
                      Askari 6                                            585
                      Navy Housing Scheme Karsaz                          131
                      Dohs Phase 1                                         51
                      Gulshan-E-Roomi                                      43
                      Malir Cantonment                                     20
                      Dohs Phase 2                                         11
                      P & T Colony                                         10
Clifton               Clifton Block 2                                     160
                      Bath Island                                         128
                      Clifton Block 9                                      94
                      Clifton Block 8                                      89
                      Clifton Block 1                                      87
                      Clifton Block 4                                      52
                      Frere Town                                           43
                      Clifton Block 7                                      40
                      Clifton Block 5                                      35
                      Clifton Block 3                                      11
                      Clifton Block 6                                      11
                      Gizri                                                11
DHA Defence           Phase 8                                            2241
                      Phase 6                                             907
                      Phase 5                                             427
                      Phase 7                                             296
                      Phase 4                                             168
                      Phase 7 Extension                                   147
                      Phase 2 Extension                                    69
                      Phase 1                                              65
                      Phase 2                                              54
                      Phase 5 Extension                                    21
                      Phase 8 Extension                                    12
                      Darakhshan Villas, Dha Phase 6                        7
Federal B Area        Block 10                                             75
                      Block 12                                             54
                      Block 13                                             41
                      Block 11                                             29
                      Block 14                                             23
                      Block 16                                             19
                      Block 9                                              19
                      Block 15                                             18
                      Block 8                                              18
                      Block 19                                             17
                      Block 6                                              12
                      Block 7                                              11
                      Block 20                                             10
                      Shahrah-E-Pakistan                                   10
Gadap                 Gulshan-E-Maymar                                    468
                      Surjani Town                                        273
                      Memon Goth                                           55
Gulistan-e-Jauhar     Block 15                                            196
                      Block 14                                            152
                      Block 13                                            132
                      Block 18                                            132
                      Block 7                                             122
                      Block 3A                                            119
                      Block 12                                            117
                      Block 17                                            114
                      Block 2                                              91
                      Block 19                                             74
                      Block 16                                             71
                      Block 3                                              57
                      Block 1                                              39
                      Block 10                                             39
                      Askari 4                                             34
                      Block 11                                             33
                      Block 4                                              31
                      Block 20                                             25
                      Block 16A                                            14
                      Block 9                                              14
                      Block 8                                              12
                      Latifi Cooperative Housing Society                    8
                      Safoora Goth                                          8
                      Block 5                                               7
                      Kda Overseas Bungalows                                7
                      Block 6                                               4
Gulshan-e-Iqbal Town  Callachi Cooperative Housing Society                302
                      Block 1                                             194
                      Block 10A                                           144
                      Bahadurabad                                         121
                      Block 4                                              92
                      Block 7                                              91
                      Kda Scheme 1                                         87
                      Block 5                                              84
                      Block 2                                              78
                      Block 13D2                                           76
                      Block 13D1                                           65
                      Dhoraji Colony                                       59
                      Block 13D                                            58
                      Block 6                                              57
                      Sharfabad                                            47
                      Block 17                                             44
                      Kda Officers Society                                 43
                      Block 13A                                            41
                      Block 13C                                            39
                      Block 3                                              39
                      Block 11                                             34
                      Block 13D3                                           32
                      Block 13B                                            24
                      Block 16                                             23
                      Block 10                                             21
                      Mohammad Ali Society                                 18
                      Block 19                                             17
                      Block 9                                              17
                      Adamjee Nagar                                        16
                      Block 14                                             16
                      Cp Barar Society, Gulshan-E-Iqbal Town               14
                      National Stadium Colony                              14
                      Block 4A                                             13
                      Dawood Society                                       13
                      Gulshan-E-Jamal                                      13
                      Kda Scheme 1 Extension                               11
                      Block 13                                             10
Jamshed Town          Pechs                                               284
                      Shaheed Millat Road                                 179
                      Khalid Bin Walid Road                               124
                      Jamshed Road                                         61
                      Karachi Administration Employees Society             46
                      Smchs - Sindhi Muslim Society                        45
                      Tariq Road                                           39
                      Amir Khusro                                          36
                      Garden East                                          34
                      Amil Colony                                          29
                      Hill Park                                            27
                      Soldier Bazar                                        22
                      Parsi Colony                                         21
                      Mehmoodabad                                          19
                      Cosmopolitan Society                                 17
                      Shahra-E-Qaideen                                     14
                      Defence Skyline, Shaheed-E-Millat Expressway         12
                      Muslimabad Society                                   12
Jinnah Avenue         Metropolis Residency                                112
                      Aman Golf View                                       38
                      Roomi Residency                                      33
Korangi               Allahwala Town                                      113
                      Korangi Industrial Area                              23
                      Kda Employees Society                                16
                      Qayyumabad                                           16
Malir                 Falcon Complex New Malir                            516
                      Falaknaz                                            118
                      Model Colony                                         96
                      Malir Link To Super Highway                          82
                      Airport                                              45
                      Saima Projects                                       37
                      Jamia Millia Road                                    20
                      Golden Town                                          16
                      Malir Town Residency                                 13
Naya Nazimabad        Block A                                              95
                      Block C                                              87
                      Block D                                              68
                      Block B                                              67
                      Block M                                              23
Nazimabad             Nazimabad 4                                          22
                      Nazimabad 3                                          20
                      Nazimabad 5                                           9
                      Nazimabad 1                                           8
                      Nazimabad 2                                           5
North Karachi         Buffer Zone                                         105
                      North Karachi Sector 11                              80
                      North Karachi Sector 5                               49
                      North Karachi Sector 7                               38
                      North Karachi Sector 9                               26
                      North Karachi Sector 10                              14
                      North Karachi Sector 8                               14
                      New Karachi                                          10
North Nazimabad       Block F                                             183
                      Block H                                             131
                      Block L                                             120
                      Block N                                             118
                      Block B                                              83
                      Block M                                              52
                      Block K                                              51
                      Block A                                              50
                      Block D                                              45
                      Block J                                              37
                      Shadman Town - Sector-14/B, Shadman                  36
                      Block I                                              34
                      Block G                                              32
                      Block C                                              12
                      Shadman                                               6
                      Shadman Town - Sector-14/A, Shadman                   6
Rashid Minhas Road    Lucky One Apartment                                  41
                      Saima Royal Residency                                32
                      Lakhani Presidency                                    8
Scheme 33             Saadi Town                                          272
                      Sector 35-A                                         249
                      Saadi Garden                                        173
                      Punjabi Saudagar Society                            156
                      Falaknaz                                            110
                      Gulshan-E-Kaneez Fatima                              76
                      Sector 34-A                                          75
                      Sector 17-A                                          74
                      Sector 18-A                                          63
                      Daniyal Residency                                    62
                      Hansa Society                                        58
                      Meerut Society                                       57
                      Saadi Road                                           57
                      Karachi University Housing Society                   51
                      Sector 15-A                                          49
                      Sector 16-A                                          42
                      Zeenatabad                                           42
                      Gwalior Cooperative Housing Society                  40
                      Chapal Courtyard                                     39
                      Lakhani Fantasia                                     38
                      Chapal Sun City                                      33
                      Sector 19-A                                          33
                      Sadaf Cooperative Housing Society                    30
                      Sector 51-A                                          29
                      Sector 52-A                                          28
                      Grey Noor Tower                                      27
                      Sawera Enclave                                       27
                      Rafi Premier Residency                               26
                      Noman Residencia                                     25
                      Sania Corner                                         25
                      Sector 36-A                                          25
                      Cotton Export Cooperative Housing Society            23
                      Musalmanan-E-Punjab Cooperative Housing Society      22
                      Sector 24-A                                          22
                      Federal Government Employees Housing Foundation      20
                      Fatima Ali Towers                                    19
                      Sector 22-A                                          18
                      Chapal Uptown                                        16
                      Kathiawar Society                                    14
                      Sumaira Sky Tower                                    14
                      Andaleeb Cooperative Housing Society                 13
                      Gulshan-E-Usman Housing Society                      12

In [154]:
df.head()

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category
0,"Brand New, West Open","saadi town - block 7, saadi town",Scheme 33,Saadi Town,22800000.0,21111.11,1080.0,4,5,1.0,NaN,2.0,3.0,0,1,1,1,2025.0,house,1.0,Relatively New
1,Double Storey House Available For Sale,"north nazimabad - block b, north nazimabad",North Nazimabad,Block B,100000000.0,22222.22,4500.0,5,5,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house,NaN,NaN
2,166 Square Yard Flat For Sale In North Nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,Block F,25500000.0,17068.27,1494.0,3,3,0.0,NaN,12.0,0.0,2,0,1,0,NaN,flat,NaN,NaN
3,Flat Available For Sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,27049.52,2403.0,4,4,2.0,NaN,NaN,2.0,0,0,1,0,NaN,flat,NaN,NaN
4,North Vista 2 Bed D D Flat For Sale,"north nazimabad - block b, north nazimabad",North Nazimabad,Block B,16500000.0,17295.60,954.0,2,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN

In [155]:
df["luxury_score"] = (
    (df["parking"] > 0).astype(int) +
    (df["servant_quarters"] > 0).astype(int) +
    df["elevator"].astype(int) +
    df["electricity_backup"].astype(int) +
    df["furnished"].astype(int)
)

In [156]:
# 1. Convert all potential count features to binary flags (1 or 0)
parking_bin = (df["parking"] > 0).astype(int)
servant_bin = (df["servant_quarters"] > 0).astype(int)
elevator_bin = (df["elevator"] > 0).astype(int)
elec_backup_bin = (df["electricity_backup"] > 0).astype(int)
furnished_bin = (df["furnished"] > 0).astype(int)

# 2. Initialize luxury_score column
df["luxury_score"] = 0

# 3. Create masks
flat_mask = df["property_type"].str.lower() == "flat"
house_mask = df["property_type"].str.lower() == "house"

# 4. Calculate for Flats
df.loc[flat_mask, "luxury_score"] = (
    1 * parking_bin[flat_mask] +
    2 * elevator_bin[flat_mask] +
    2 * elec_backup_bin[flat_mask] +
    2 * servant_bin[flat_mask] +
    1 * furnished_bin[flat_mask]
)

# 5. Calculate for Houses
df.loc[house_mask, "luxury_score"] = (
    2 * parking_bin[house_mask] +
    2 * elec_backup_bin[house_mask] +
    3 * servant_bin[house_mask] +
    1 * furnished_bin[house_mask]
)

In [157]:
df['luxury_score'].value_counts()

luxury_score
8    6762
0    5658
7    3022
5    2274
6    1427
3    1324
4     885
2     845
1     562
Name: count, dtype: int64

In [158]:
df.groupby('luxury_score')['price'].mean()

luxury_score
0    5.775226e+07
1    4.634484e+07
2    6.207041e+07
3    4.034217e+07
4    7.155835e+07
5    6.088478e+07
6    4.178452e+07
7    9.188175e+07
8    8.310216e+07
Name: price, dtype: float64

In [159]:
df["luxury_score"].value_counts().sort_index()

luxury_score
0    5658
1     562
2     845
3    1324
4     885
5    2274
6    1427
7    3022
8    6762
Name: count, dtype: int64

In [160]:
df.groupby("luxury_score")["location"].value_counts().head(20)

luxury_score  location
0             DHA Defence             844
              Scheme 33               719
              Gulshan-e-Iqbal Town    683
              Gulistan-e-Jauhar       630
              Naya Nazimabad          432
              Cantt                   335
              Bahria Town             280
              North Nazimabad         253
              Gadap                   246
              Federal B Area          244
              Jamshed Town            196
              North Karachi           158
              Clifton                 147
              Malir                   129
              University Road          83
              Jinnah Avenue            44
              Korangi                  38
              Nazimabad                32
              Super Highway            31
              DHA City                 28
Name: count, dtype: int64

In [161]:
df.groupby('sub_location')['price'].agg(['count','mean']).sort_values(by='mean',ascending=False)

                                                 count          mean
sub_location
National Stadium Colony                             14  5.877500e+08
Falcon Complex Faisal                               14  3.482143e+08
Kda Scheme 1 Extension                              11  3.063636e+08
Kda Officers Society                                43  2.998837e+08
Dawood Society                                      13  2.361538e+08
Navy Housing Scheme Karsaz                         131  2.160687e+08
Kda Scheme 1                                        87  2.139816e+08
Mohammad Ali Society                                18  2.035833e+08
Dohs Phase 1                                        51  1.732922e+08
Phase 2                                             54  1.728519e+08
Phase 6                                            907  1.654388e+08
Phase 8                                           2241  1.629607e+08
Adamjee Nagar                                       16  1.604688e+08
Smchs - Sindhi Muslim Society                       45  1.525667e+08
Phase 7                                            296  1.498338e+08
Precinct 18                                          5  1.480000e+08
Dohs Phase 2                                        11  1.450000e+08
Phase 5                                            427  1.392705e+08
Phase 8 Extension                                   12  1.383333e+08
Amir Khusro                                         36  1.379028e+08
Latifi Cooperative Housing Society                   8  1.371875e+08
Phase 1                                             65  1.351646e+08
Hill Park                                           27  1.338519e+08
Precinct 7                                          14  1.310714e+08
Phase 5 Extension                                   21  1.260476e+08
Phase 4                                            168  1.244036e+08
Pechs                                              284  1.210616e+08
Clifton Block 5                                     35  1.107143e+08
Kda Overseas Bungalows                               7  1.057857e+08
Falcon Complex New Malir                           516  1.017888e+08
Clifton Block 7                                     40  9.948750e+07
Shaheed Millat Road                                179  9.427263e+07
Block 13D                                           58  8.942241e+07
Clifton Block 6                                     11  8.827273e+07
Cp Barar Society, Gulshan-E-Iqbal Town              14  8.614286e+07
Darakhshan Villas, Dha Phase 6                       7  8.571429e+07
Block 5                                             91  8.439121e+07
Block 6                                             73  8.423011e+07
Block F                                            183  8.324153e+07
Bath Island                                        128  8.288281e+07
Clifton Block 4                                     52  8.256154e+07
Clifton Block 8                                     89  8.195955e+07
Precinct 17                                         26  8.139615e+07
Askari 4                                            34  7.881176e+07
Bahadurabad                                        121  7.627273e+07
Block I                                             34  7.006765e+07
Block 9                                             50  6.858800e+07
Block 13D1                                          65  6.829692e+07
Phase 7 Extension                                  147  6.597143e+07
Bahria Hills                                        54  6.579444e+07
Shahra-E-Qaideen                                    14  6.532143e+07
Askari 6                                           585  6.442718e+07
Block 4                                            123  6.404634e+07
Block N                                            118  6.352119e+07
Clifton Block 9                                     94  6.311170e+07
Gulshan-E-Jamal                                     13  6.203846e+07
Block 7                                            224  6.139542e+07
Clifton Block 3                                     11  6.090909e+07
Block L                                            120  6.088750e+07
Block A                                            145  5.973931e+07
Askari 5                                           626  5.959105e+07
Meerut Society                                      57  5.908596e+07
Lakhani Presidency                                   8  5.843750e+07
Block 3                                             96  5.814583e+07
Khalid Bin Walid Road                              124  5.791532e+07
Precinct 9                                          11  5.707273e+07
Block 10                                           135  5.661370e+07
Block B                                            150  5.515067e+07
Block J                                             37  5.509189e+07
Clifton Block 2                                    160  5.489750e+07
Block D                                            113  5.439204e+07
Block 4A                                            13  5.415385e+07
Precinct 4                                          49  5.411020e+07
Block 2                                            169  5.401538e+07
Gizri                                               11  5.357273e+07
Sharfabad                                           47  5.323404e+07
Block C                                             99  5.206970e+07
Lucky One Apartment                                 41  5.102439e+07
Amil Colony                                         29  5.067241e+07
Qayyumabad                                          16  5.057500e+07
Block H                                            131  5.040076e+07
Frere Town                                          43  5.017442e+07
Central Information Cooperative Housing Society     10  4.889000e+07
Cosmopolitan Society                                17  4.755882e+07
Block 15                                           214  4.659206e+07
Bahria Paradise                                     76  4.555921e+07
Sector 17-A                                         74  4.526959e+07
Block 11                                            96  4.525312e+07
Dhoraji Colony                                      59  4.471186e+07
Clifton Block 1                                     87  4.455287e+07
Block 14                                           191  4.387696e+07
Tariq Road                                          39  4.242308e+07
Block 12                                           171  4.234737e+07
Block 13                                           183  4.183989e+07
Sector 35-A                                        249  4.082490e+07
Block 16                                           113  4.022965e+07
Garden East                                         34  3.923529e+07
Karachi Administration Employees Society            46  3.884130e+07
Gwalior Cooperative Housing Society                 40  3.669000e+07
Precinct 8                                          94  3.571596e+07
Callachi Cooperative Housing Society               302  3.544768e+07
Block 10A                                          144  3.494792e+07
Sector 24-A                                         22  3.490909e+07
Muslimabad Society                                  12  3.441667e+07
Block 1                                            233  3.428841e+07
Precinct 1                                          70  3.415857e+07
Malir Cantonment                                    20  3.393125e+07
Metropolis Residency                               112  3.280893e+07
Bahria Town                                         62  3.252458e+07
Saima Luxury Belt                                   33  3.225758e+07
Sector 16-A                                         42  3.189643e+07
Phase 2 Extension                                   69  3.181594e+07
Saima Projects                                      37  3.172432e+07
Block 16A                                           14  3.167857e+07
Saadi Town                                         272  3.115956e+07
Precinct 6                                          63  3.079841e+07
Hansa Society                                       58  3.069310e+07
Shadman Town - Sector-14/A, Shadman                  6  3.066667e+07
Sector 52-A                                         28  2.975714e+07
North Karachi Sector 11                             80  2.948000e+07
North Karachi Sector 10                             14  2.940714e+07
Saima Jinnah Avenue                                 50  2.927400e+07
Saima Royal Residency                               32  2.917188e+07
Shadman Town - Sector-14/B, Shadman                 36  2.907778e+07
Block 13C                                           39  2.895385e+07
Cotton Export Cooperative Housing Society           23  2.895217e+07
Parsi Colony                                        21  2.890476e+07
Nazimabad 2                                          5  2.890000e+07
Sector 15-A                                         49  2.882857e+07
Block 3A                                           119  2.848193e+07
Soldier Bazar                                       22  2.779545e+07
Andaleeb Cooperative Housing Society                13  2.776154e+07
Sadaf Cooperative Housing Society                   30  2.742540e+07
Block 13D2                                          76  2.741053e+07
Model Colony                                        96  2.740521e+07
Buffer Zone                                        105  2.724667e+07
Sector 19-A                                         33  2.719697e+07
Punjabi Saudagar Society                           156  2.718269e+07
Block 17                                           158  2.712753e+07
Precinct 16                                         37  2.701892e+07
Sector 22-A                                         18  2.694444e+07
North Karachi Sector 9                              26  2.658462e+07
Block 20                                            35  2.647429e+07
Block 19                                           108  2.626296e+07
Nazimabad 3                                         20  2.620500e+07
Nazimabad 4                                         22  2.545455e+07
Gulshan-E-Maymar                                   468  2.539615e+07
Chapal Sun City                                     33  2.534848e+07
Aman Golf View                                      38  2.517368e+07
North Karachi Sector 8                              14  2.510000e+07
Block 8                                             30  2.491667e+07
Al Madni Heights                                    41  2.487805e+07
Block 13A                                           41  2.480244e+07
Sector 34-A                                         75  2.474267e+07
Zeenatabad                                          42  2.439048e+07
Sector 51-A                                         29  2.436897e+07
Defence Skyline, Shaheed-E-Millat Expressway        12  2.434167e+07
Quaid Villas                                        72  2.397361e+07
Sadat-E-Amroha Cooperative Housing Society          10  2.373000e+07
Musalmanan-E-Punjab Cooperative Housing Society     22  2.362727e+07
Nazimabad 5                                          9  2.348889e+07
Sector 36-A                                         25  2.325600e+07
Airport                                             45  2.254889e+07
Oasis Park Residencia                                6  2.241667e+07
Gulshan-E-Kaneez Fatima                             76  2.192632e+07
Sumaira Sky Tower                                   14  2.189286e+07
Shahrah-E-Pakistan                                  10  2.171000e+07
Jamshed Road                                        61  2.128197e+07
Gulshan-E-Roomi                                     43  2.106977e+07
Saadi Garden                                       173  2.105723e+07
Sector 18-A                                         63  2.091905e+07
Saadi Road                                          57  2.065439e+07
Karachi University Housing Society                  51  2.063922e+07
Roomi Residency                                     33  2.040606e+07
Bahria Sports City                                 128  2.033438e+07
Precinct 2                                          13  2.020769e+07
Malir Link To Super Highway                         82  2.014634e+07
Gulshan-E-Usman Housing Society                     12  1.962500e+07
Precinct 10A                                        92  1.953804e+07
Burj-Ul-Harmain                                    143  1.948881e+07
Shadman                                              6  1.911667e+07
Block 13D3                                          32  1.881875e+07
Iqbal Villas                                        60  1.873500e+07
Kathiawar Society                                   14  1.864286e+07
Block M                                             75  1.849333e+07
Grey Noor Tower                                     27  1.830741e+07
Green Town / Rafah-E-Aam Belt                       24  1.830167e+07
City Tower And Shopping Mall                        17  1.801176e+07
North Karachi Sector 7                              38  1.797632e+07
Sawera Enclave                                      27  1.740741e+07
Precinct 11A                                        85  1.721647e+07
Rafi Premier Residency                              26  1.700192e+07
Taloo Gold Residency                                10  1.605000e+07
Saima Villas                                        72  1.603056e+07
Gulzar-E-Hijri                                      10  1.553000e+07
Block 13B                                           24  1.546042e+07
Chapal Uptown                                       16  1.531250e+07
Falaknaz                                           228  1.514131e+07
Precinct 31                                         84  1.512500e+07
Precinct 27                                         61  1.494754e+07
Safoora Goth                                         8  1.451250e+07
Fatima Ali Towers                                   19  1.438421e+07
Block 18                                           132  1.437121e+07
Ali Block                                          109  1.433716e+07
Precinct 12                                         21  1.420000e+07
Precinct 11B                                        74  1.382297e+07
Chapal Courtyard                                    39  1.322308e+07
Noman Residencia                                    25  1.298400e+07
Safari Enclave Apartments                           18  1.290556e+07
North Karachi Sector 5                              49  1.288980e+07
Yousaf Goth                                         11  1.282727e+07
Precinct 10B                                        68  1.277794e+07
Kda Employees Society                               16  1.261250e+07
Memon Goth                                          55  1.203000e+07
Precinct 15                                         22  1.192273e+07
Gohar Green City Cluster                            42  1.157143e+07
Daniyal Residency                                   62  1.144113e+07
Mehmoodabad                                         19  1.140526e+07
Bahria Apartments                                  120  1.129000e+07
Sania Corner                                        25  1.124760e+07
Block K                                             51  1.121961e+07
Block G                                             32  1.110312e+07
Surjani Town                                       273  1.109066e+07
New Karachi                                         10  1.107000e+07
Precinct 19                                         34  1.103235e+07
Jamia Millia Road                                   20  1.099000e+07
Lakhani Fantasia                                    38  1.039079e+07
Nazimabad 1                                          8  9.937500e+06
Korangi Industrial Area                             23  9.891304e+06
Rabia Enclave                                        9  9.527778e+06
Federal Government Employees Housing Foundation     20  8.605000e+06
Shamsi / Al-Falah Belt                              27  8.427778e+06
Bahria Heights                                      57  7.505263e+06
Private High-Rises                                  92  7.445652e+06
P & T Colony                                        10  6.450000e+06
Malir Town Residency                                13  6.276923e+06
Golden Town                                         16  4.993750e+06
Allahwala Town                                     113  3.802743e+06
Mateen Complex                                      34  2.554412e+06

In [162]:
pd.crosstab(df["luxury_score"], df["property_type"])

property_type  flat  house
luxury_score
0              2697   2961
1               268    294
2               323    522
3              1018    306
4               317    568
5              1496    778
6              1307    120
7               903   2119
8              3307   3455

In [163]:
pd.crosstab(df["luxury_score"], df["location"])

location,Abul Hassan Isphani Road,Bahria Town,Bin Qasim Town,Cantt,Civil Lines,Clifton,DHA City,DHA Defence,Defence View,Federal B Area,Gadap,Gulistan-e-Jauhar,Gulshan-e-Iqbal Town,Jamshed Town,Jinnah Avenue,Korangi,Malir,National Highway,Naya Nazimabad,Nazimabad,North Karachi,North Nazimabad,Northern Bypass,Rashid Minhas Road,Saddar,Scheme 33,Shah Faisal,Shahra-e-Faisal,Super Highway,Tipu Sultan Road,University Road
luxury_score,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,8,280,3,335,5,147,28,844,11,244,246,630,683,196,44,38,129,0,432,32,158,253,5,19,20,719,20,11,31,4,83
1,4,34,0,14,0,13,1,80,5,8,40,61,60,20,0,8,17,0,12,1,32,21,0,1,1,119,4,0,2,1,3
2,0,63,3,15,1,15,6,169,2,21,42,83,112,46,1,1,32,0,35,3,12,41,0,2,2,110,7,2,4,2,13
3,2,152,0,48,3,40,1,196,3,16,41,111,107,87,6,9,41,0,33,6,19,60,0,7,16,264,14,2,15,2,23
4,0,37,0,45,6,21,3,192,3,18,24,89,74,41,11,4,45,0,31,2,24,44,0,0,0,146,11,0,4,0,10
5,0,86,2,111,13,122,2,469,7,20,72,193,252,141,34,8,100,0,61,7,17,122,0,8,4,315,18,6,9,3,72
6,1,21,1,77,7,52,1,251,6,15,40,128,208,94,39,16,36,0,33,7,48,87,1,16,5,180,12,3,0,3,39
7,1,869,3,195,12,123,5,934,3,15,35,151,163,97,12,3,82,0,24,10,20,59,1,4,5,149,11,5,8,3,20
8,2,215,45,726,39,288,11,1338,7,71,256,382,646,308,100,87,515,5,148,6,79,390,24,26,37,789,67,17,42,14,82

In [164]:
df['parking_score']=np.minimum(df['parking'],2)

In [165]:
df['servant_quarter_score']=np.minimum(df['servant_quarters'],2)

In [166]:
df.groupby('parking_score')['price'].mean()

parking_score
0.0    5.707234e+07
1.0    5.236908e+07
2.0    1.095619e+08
Name: price, dtype: float64

In [167]:
df.groupby('servant_quarter_score')['price'].mean()

servant_quarter_score
0    5.171460e+07
1    7.240786e+07
2    1.488740e+08
Name: price, dtype: float64

In [168]:
pd.crosstab(df['parking_score'],df['property_type'])

property_type  flat  house
parking_score
0.0            3655   3628
1.0            5616   4031
2.0            2365   3423

In [169]:
pd.crosstab(df['servant_quarter_score'],df['property_type'])

property_type          flat  house
servant_quarter_score
0                      6134   4867
1                      4839   5096
2                       663   1160

In [170]:
# This section handles Create Binary Flags For Non-Score Columns.parking_bin = (df['parking'].fillna(0) > 0).astype(int)
elevator_bin = (df['elevator'].fillna(0) > 0).astype(int)
elec_backup_bin = (df['electricity_backup'].fillna(0) > 0).astype(int)
furnished_bin = (df['furnished'].fillna(0) > 0).astype(int)

# This section handles Initialize Column.df['luxury_score'] = 0.0

# This section handles Define Logic Per Property Type.is_flat = df['property_type'].str.lower() == 'flat'
is_house = df['property_type'].str.lower() == 'house'

# 1. Flat calculation: Elevators & Backup power carry high weight
df.loc[is_flat, 'luxury_score'] = (
    (2.5 * elevator_bin[is_flat]) +
    (2.0 * elec_backup_bin[is_flat]) +
    (1.5 * df.loc[is_flat, 'servant_quarter_score'].fillna(0)) +
    (1.0 * parking_bin[is_flat]) +
    (1.0 * furnished_bin[is_flat])
)

# 2. House calculation: Servant quarters & Parking carry high weight
df.loc[is_house, 'luxury_score'] = (
    (2.5 * df.loc[is_house, 'servant_quarter_score'].fillna(0)) +
    (2.0 * parking_bin[is_house]) +
    (2.0 * elec_backup_bin[is_house]) +
    (1.0 * furnished_bin[is_house])
)

In [171]:
df['luxury_score'].value_counts()

luxury_score
0.0     5658
8.0     2933
7.5     2747
6.5     2414
5.5     1658
7.0     1089
4.5      814
10.0     709
2.0      692
4.0      671
3.0      646
1.0      562
3.5      497
5.0      463
9.5      404
9.0      314
2.5      285
6.0      103
1.5       57
8.5       43
Name: count, dtype: int64

In [172]:
df.groupby('luxury_score')['price'].mean()

luxury_score
0.0     5.775226e+07
1.0     4.634484e+07
1.5     3.958421e+07
2.0     6.757168e+07
2.5     7.552246e+07
3.0     2.755697e+07
3.5     2.789302e+07
4.0     8.091142e+07
4.5     7.167114e+07
5.0     7.276890e+07
5.5     3.674651e+07
6.0     4.686408e+07
6.5     6.992196e+07
7.0     7.188962e+07
7.5     1.028942e+08
8.0     4.598101e+07
8.5     5.296512e+07
9.0     2.342162e+08
9.5     2.951689e+07
10.0    1.978197e+08
Name: price, dtype: float64

In [173]:
df[df["luxury_score"] == 6]["property_type"].value_counts()
# df[df["luxury_score"] == 5]["property_type"].value_counts()

property_type
flat     100
house      3
Name: count, dtype: int64

In [174]:
sub_location_price = (
    df.groupby('sub_location')['price_per_sqft']
    .median()
)

In [175]:
sub_location_score = pd.qcut(
    sub_location_price,
    q=5,
    labels=[1,2,3,4,5]
)

In [176]:
df['sub_location_score'] = df['sub_location'].map(sub_location_score).astype('Int64')

In [177]:
df.groupby('sub_location')['price_per_sqft'].median().sort_values(ascending=False)

sub_location
National Stadium Colony                            114271.940
Kda Officers Society                                88888.890
Falcon Complex Faisal                               76666.670
Dawood Society                                      66666.670
Navy Housing Scheme Karsaz                          65873.020
Phase 7 Extension                                   55555.560
Adamjee Nagar                                       55555.560
Amir Khusro                                         51666.665
Phase 8 Extension                                   50000.000
Mohammad Ali Society                                49000.000
Kda Scheme 1 Extension                              46666.670
Hill Park                                           44444.440
Phase 8                                             44022.500
Phase 4                                             41666.665
Kda Scheme 1                                        40740.740
Kda Overseas Bungalows                              37593.980
Block 13D1                                          37037.040
Block C                                             36944.440
Block A                                             36111.110
Latifi Cooperative Housing Society                  34027.775
Clifton Block 6                                     32771.540
Bath Island                                         32769.060
Pechs                                               32384.935
Dohs Phase 1                                        32323.230
Phase 7                                             32222.220
Block D                                             32222.220
Shaheed Millat Road                                 31500.570
Dohs Phase 2                                        31313.130
Block 5                                             31250.000
Phase 6                                             31111.110
North Karachi Sector 10                             30138.890
Clifton Block 8                                     30030.030
Smchs - Sindhi Muslim Society                       29782.360
Qayyumabad                                          29526.060
Phase 5 Extension                                   28888.890
Gulshan-E-Jamal                                     28888.890
Phase 2                                             28888.890
Shahra-E-Qaideen                                    28584.875
Clifton Block 7                                     28570.240
Clifton Block 9                                     28115.160
Darakhshan Villas, Dha Phase 6                      28011.200
Bahadurabad                                         27924.750
Block 3                                             27777.780
Frere Town                                          27777.780
Block 6                                             27777.780
Central Information Cooperative Housing Society     27546.300
Khalid Bin Walid Road                               27224.570
Askari 4                                            27000.780
Hansa Society                                       26898.145
Shadman Town - Sector-14/B, Shadman                 26736.110
Sector 17-A                                         26722.225
Falcon Complex New Malir                            26444.440
Block 13D                                           26296.300
Clifton Block 5                                     26276.280
Block 12                                            26157.410
North Karachi Sector 9                              25925.930
Andaleeb Cooperative Housing Society                25925.930
Block 9                                             25862.795
Phase 5                                             25555.560
Garden East                                         25483.890
Shadman Town - Sector-14/A, Shadman                 25462.960
Cp Barar Society, Gulshan-E-Iqbal Town              25231.965
Cosmopolitan Society                                25025.030
Sector 35-A                                         25000.000
Buffer Zone                                         25000.000
Saima Projects                                      25000.000
Block 4A                                            25000.000
Model Colony                                        24933.860
Block I                                             24765.510
Askari 6                                            24740.740
Punjabi Saudagar Society                            24537.040
Muslimabad Society                                  24451.100
Sector 24-A                                         24120.370
Clifton Block 3                                     23611.110
Sharfabad                                           23611.110
North Karachi Sector 8                              23564.815
Tariq Road                                          23286.760
Dhoraji Colony                                      23286.760
Block 14                                            23148.150
Gwalior Cooperative Housing Society                 23148.150
Saima Luxury Belt                                   23148.150
Clifton Block 2                                     23047.635
Amil Colony                                         23023.020
Nazimabad 5                                         22974.100
Block L                                             22927.690
Block 2                                             22916.670
Musalmanan-E-Punjab Cooperative Housing Society     22314.815
Cotton Export Cooperative Housing Society           22222.220
Meerut Society                                      22222.220
Block 15                                            22222.220
Block B                                             22222.220
Block 4                                             22222.220
Phase 1                                             22222.220
Soldier Bazar                                       22150.995
Block N                                             22131.845
Zeenatabad                                          21990.740
Shadman                                             21759.260
Parsi Colony                                        21394.060
Clifton Block 4                                     20794.365
Block J                                             20609.320
Block H                                             20287.140
Sadat-E-Amroha Cooperative Housing Society          19675.930
Sector 52-A                                         19675.925
Lucky One Apartment                                 19607.840
Sadaf Cooperative Housing Society                   19560.185
Callachi Cooperative Housing Society                19519.520
Chapal Sun City                                     19444.440
Sector 51-A                                         19444.440
Oasis Park Residencia                               19444.440
Block 10A                                           19285.725
Sector 22-A                                         19166.665
Clifton Block 1                                     19083.970
North Karachi Sector 11                             18904.320
Block F                                             18888.890
Block 19                                            18750.000
Saima Royal Residency                               18588.135
Gulshan-E-Roomi                                     18518.520
Saadi Town                                          18055.560
Block 8                                             17824.070
Defence Skyline, Shaheed-E-Millat Expressway        17768.670
Lakhani Presidency                                  17369.455
North Karachi Sector 5                              17361.110
Jamshed Road                                        17342.740
Askari 5                                            17222.220
Sector 19-A                                         17129.630
Block 7                                             17001.555
Block 16                                            16848.820
Phase 2 Extension                                   16708.440
Precinct 18                                         16666.670
Block 10                                            16516.520
Gulshan-E-Usman Housing Society                     16435.185
Saadi Garden                                        16203.700
North Karachi Sector 7                              15879.630
Saima Jinnah Avenue                                 15871.915
Sector 16-A                                         15800.095
Karachi Administration Employees Society            15772.025
Al Madni Heights                                    15618.030
Block 3A                                            15605.490
Block 13C                                           15555.560
Block 16A                                           15529.720
Shahrah-E-Pakistan                                  15517.185
Airport                                             15432.100
Nazimabad 4                                         15323.850
Nazimabad 2                                         15277.780
Block 1                                             15021.460
Malir Cantonment                                    15017.360
Sector 15-A                                         14775.410
Block 13A                                           14697.240
Precinct 1                                          14666.670
Metropolis Residency                                14565.130
Block 11                                            14529.525
City Tower And Shopping Mall                        14444.440
Block M                                             14314.310
Precinct 8                                          14297.390
Aman Golf View                                      14245.010
Chapal Courtyard                                    13756.610
Grey Noor Tower                                     13752.280
Block 13D2                                          13737.940
Sector 34-A                                         13661.200
Roomi Residency                                     13533.830
Precinct 2                                          13523.390
Iqbal Villas                                        13523.390
Quaid Villas                                        13472.220
Block 13B                                           13463.355
Gulshan-E-Maymar                                    13425.930
Yousaf Goth                                         13425.930
New Karachi                                         13385.885
Precinct 9                                          13333.330
Precinct 7                                          13333.330
Fatima Ali Towers                                   13176.640
Precinct 6                                          13111.110
Bahria Hills                                        13055.555
Lakhani Fantasia                                    13031.330
Precinct 12                                         12888.890
Nazimabad 1                                         12833.145
Block 13                                            12750.460
Gohar Green City Cluster                            12610.675
Sector 36-A                                         12500.000
Precinct 17                                         12500.000
Sawera Enclave                                      12500.000
Sania Corner                                        12449.800
Ali Block                                           12444.440
Kathiawar Society                                   12391.625
Taloo Gold Residency                                12345.790
Falaknaz                                            12312.325
Gulshan-E-Kaneez Fatima                             12283.950
Sector 18-A                                         12234.710
Precinct 4                                          12222.220
Malir Link To Super Highway                         12167.920
Karachi University Housing Society                  12063.490
Kda Employees Society                               12037.040
Nazimabad 3                                         11916.170
Safari Enclave Apartments                           11845.785
Surjani Town                                        11805.560
Saima Villas                                        11701.390
Burj-Ul-Harmain                                     11695.910
Daniyal Residency                                   11396.010
Chapal Uptown                                       11284.720
Noman Residencia                                    11284.720
Precinct 16                                         11233.660
Saadi Road                                          11191.050
Rafi Premier Residency                              11168.380
Safoora Goth                                        11126.735
Memon Goth                                          11111.110
Block 13D3                                          11020.035
Block K                                             10928.960
Block 17                                            10743.115
Sumaira Sky Tower                                   10625.380
Precinct 11B                                        10599.420
Rabia Enclave                                       10555.560
Gizri                                               10555.560
Precinct 11A                                        10555.560
Precinct 10A                                        10555.560
Precinct 15                                         10488.890
Gulzar-E-Hijri                                      10429.195
Precinct 10B                                        10133.330
Bahria Paradise                                     10000.000
Bahria Town                                          9934.210
Block G                                              9664.445
Block 20                                             9444.440
Block 18                                             8561.280
Precinct 19                                          8415.090
Bahria Apartments                                    8176.100
Federal Government Employees Housing Foundation      7980.545
Green Town / Rafah-E-Aam Belt                        7853.640
Jamia Millia Road                                    7842.540
Mehmoodabad                                          7777.780
Precinct 27                                          7328.610
Shamsi / Al-Falah Belt                               7222.220
Precinct 31                                          7092.200
Bahria Heights                                       6944.440
Malir Town Residency                                 6712.960
Korangi Industrial Area                              6464.650
Private High-Rises                                   6410.260
Bahria Sports City                                   6190.480
Golden Town                                          6166.785
Allahwala Town                                       5277.780
P & T Colony                                         5270.655
Mateen Complex                                       4137.120
Name: price_per_sqft, dtype: float64

In [178]:
df.sample(100)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,luxury_score,parking_score,servant_quarter_score,sub_location_score
22412,For Residential Bungalow,"pechs block 3, pechs",Jamshed Town,Pechs,320000000.0,35555.56,9000.0,8,6,2.0,NaN,2.0,8.0,0,2,1,1,2015.0,house,11.0,Old,10.0,2.0,2,5
19082,Brand New House Available For Sale,"saadi garden, scheme 33",Scheme 33,Saadi Garden,26500000.0,24537.04,1080.0,5,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,3
18840,House for Sale | Main Gulshan-e-Iqbal Block-4 ...,"gulshan-e-iqbal - block 4, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 4,85000000.0,39351.85,2160.0,8,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,4
18407,Spacious 4 Bedrooms Park Facing Apartment For ...,"civil lines, karachi",Civil Lines,NaN,75000000.0,29976.02,2502.0,4,4,1.0,7.0,11.0,2.0,2,1,1,1,2012.0,flat,14.0,Old,8.0,2.0,1,<NA>
22768,2100 Square Feet 3 Bedroom Drawing Dining Apar...,"bath island, karachi",Clifton,Bath Island,65000000.0,30996.66,2097.0,3,3,1.0,NaN,19.0,2.0,1,1,1,1,2028.0,flat,-2.0,Under Construction,8.0,2.0,1,5
20938,120 Sq. Yds Brand-New G+1 House For Sale In Se...,"gulshan-e-maymar - sector r, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,19000000.0,17592.59,1080.0,4,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,2
4990,500 Square Yards House In DHA Defence Of Karac...,"dha phase 8, dha defence",DHA Defence,Phase 8,240000000.0,53333.33,4500.0,6,6,2.0,NaN,1.0,4.0,0,1,1,0,NaN,house,NaN,NaN,6.5,2.0,1,5
20348,Brand New Bungalow For Sale,"dha phase 8, dha defence",DHA Defence,Phase 8,380000000.0,42222.22,9000.0,6,6,2.0,NaN,2.0,6.0,0,2,1,0,NaN,house,NaN,NaN,9.0,2.0,2,5
22550,Ready To sale A Prime Location House 120 Squar...,"zeenatabad, scheme 33",Scheme 33,Zeenatabad,26000000.0,24074.07,1080.0,4,4,0.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,4
13075,Beautifully Designed 6-Bedroom House Featuring...,"dha phase 6, dha defence",DHA Defence,Phase 6,152500000.0,33888.89,4500.0,6,6,1.0,NaN,NaN,3.0,0,1,1,0,NaN,house,NaN,NaN,6.5,2.0,1,5
1865,READY TO MOVE 955sq Ft 2Bed Lounge Flat FOR SA...,"bahria apartments, bahria town karachi",Bahria Town,Bahria Apartments,6000000.0,6289.31,954.0,2,2,1.0,NaN,NaN,1.0,0,0,1,0,NaN,flat,NaN,NaN,3.0,1.0,0,1
7680,Dha Phase 8 666 Sq Yard Brand New Bungalow 2+4...,"dha phase 8, dha defence",DHA Defence,Phase 8,420000000.0,70070.07,5994.0,6,6,1.0,NaN,3.0,3.0,0,1,1,1,2024.0,house,2.0,Relatively New,7.5,2.0,1,5
4003,BUNGALOW FOR SALE NAZIMABAD NO. 4 Prime Locati...,"nazimabad 4, nazimabad",Nazimabad,Nazimabad 4,110000000.0,28962.61,3798.0,11,7,3.0,NaN,NaN,1.0,0,0,1,0,NaN,house,NaN,NaN,4.0,1.0,0,3
15795,PRIME LOCATION OF BLOCK-14 WEST OPEN ON MAIN 1...,"gulistan-e-jauhar - block 14, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 14,62500000.0,26709.40,2340.0,6,6,4.0,NaN,3.0,3.0,0,1,1,1,2025.0,house,1.0,Relatively New,7.5,2.0,1,4
18550,Downpayment 1400sq ft 2BHK Luxury Flat (READY ...,"paragon tower, bahria town - precinct 17",Bahria Town,Private High-Rises,2900000.0,2065.53,1404.0,2,2,1.0,NaN,NaN,1.0,0,0,1,0,NaN,flat,NaN,NaN,3.0,1.0,0,1
22336,Stunning And Affordable House Available For Sa...,"gulshan-e-iqbal - block 13/d, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13D,130000000.0,36111.11,3600.0,5,5,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,4
16112,Available For Sell One. Bed Lounge Apartment I...,"scheme 33, karachi",Scheme 33,NaN,6500000.0,14444.44,450.0,1,1,1.0,10.0,10.0,1.0,2,0,1,1,2023.0,flat,3.0,Relatively New,6.5,1.0,0,<NA>
22058,Unoccupied Prime Location Flat Of 1344 Square ...,pakistan scientists cooperative housing societ...,Scheme 33,Sector 17-A,21400000.0,15958.24,1341.0,3,3,0.0,NaN,NaN,0.0,1,0,0,1,NaN,flat,NaN,NaN,3.5,0.0,0,4
5721,Wake Up To Skyline & Sea | 1 Bed Apartment For...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,40000000.0,41536.86,963.0,1,1,1.0,NaN,NaN,1.0,1,0,1,0,NaN,flat,NaN,NaN,5.5,1.0,0,5
6882,Naya Nazimabad Block C 120 Sqyd Brand New Bun...,"naya nazimabad - block c, naya nazimabad",Naya Nazimabad,Block C,41500000.0,38425.93,1080.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,5
3968,"Precinct 7, 1000sq yds Ultra Luxury Villa for ...","bahria town - precinct 7, bahria town karachi",Bahria Town,Precinct 7,115000000.0,12777.78,9000.0,7,7,2.0,NaN,2.0,4.0,0,2,1,0,2025.0,house,1.0,Relatively New,9.0,2.0,2,2
19530,Buying A Prime Location House In Naya Nazimaba...,"naya nazimabad - block d, naya nazimabad",Naya Nazimabad,Block D,36000000.0,30769.23,1170.0,4,4,0.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,5
21340,Buying A Prime Location House In Bahria Town -...,"bahria town - quaid villas, bahria town - prec...",Bahria Town,Quaid Villas,23000000.0,12777.78,1800.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,2
17401,400 Yard Beautiful Banglow For Sale Prime Loca...,"gulistan-e-jauhar - block 15, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 15,68500000.0,31712.96,2160.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,4
20071,G+1 Modern West-Open House (400 Sq. Yds) Prime...,"gulshan-e-kaneez fatima - block 4, gulshan-e-k...",Scheme 33,Gulshan-E-Kaneez Fatima,78500000.0,21805.56,3600.0,6,6,4.0,NaN,2.0,0.0,0,1,1,0,NaN,house,NaN,NaN,4.5,0.0,1,2
19180,Flat Of 100 Square Feet Is Available For Sale,"gulistan-e-jauhar - block 4, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 4,2200000.0,22222.22,99.0,1,1,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,4
4561,160 YARDS GROUND+1 ONE UNIT WEST OPEN 24 HOURS...,"gulshan-e-iqbal - block 19, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 19,47500000.0,32986.11,1440.0,4,4,0.0,NaN,NaN,3.0,0,0,0,1,NaN,house,NaN,NaN,3.0,2.0,0,3
17803,West Open Park Facing 300 Square Yard House Fo...,"askari 6, malir cantonment",Cantt,Askari 6,80500000.0,29814.81,2700.0,5,5,1.0,NaN,NaN,1.0,0,0,1,0,NaN,house,NaN,NaN,4.0,1.0,0,4
19779,Luxurious Sea & Pool Facing Apartment For Sale...,"emaar reef towers, emaar crescent bay",DHA Defence,Phase 8,75000000.0,41666.67,1800.0,2,3,1.0,8.0,24.0,1.0,4,1,1,1,2019.0,flat,7.0,Moderately Old,8.0,1.0,1,5
7853,Prime Location 120 Square Yards House In Naya ...,"naya nazimabad - block b, naya nazimabad",Naya Nazimabad,Block B,32900000.0,30462.96,1080.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,4
22612,Sale House 240 GHz Double Story Lasaniya Resta...,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 10A,65000000.0,30092.59,2160.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,3
15295,Clifton - Block 4 Flat For Sale Sized 1800 Squ...,"clifton - block 4, clifton",Clifton,Clifton Block 4,33500000.0,18611.11,1800.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,3
13865,Premium Corner 400 Square Yards House Is Avail...,"gulshan-e-iqbal - block 13/d-1, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13D1,115000000.0,31944.44,3600.0,6,6,2.0,NaN,2.0,1.0,0,1,1,1,2015.0,house,11.0,Old,7.5,1.0,1,5
4501,CHANCE DEAL SUH HAMZA DESIGNE 500 Square Yards...,"askari 5 - sector g, askari 5",Cantt,Askari 5,93500000.0,20777.78,4500.0,5,5,1.0,NaN,NaN,4.0,0,1,1,0,2017.0,house,9.0,Moderately Old,6.5,2.0,1,3
14253,200 Square Yards Villa Available For Sale in P...,"bahria town - precinct 10-a, bahria town karachi",Bahria Town,Precinct 10A,16000000.0,8888.89,1800.0,3,3,1.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,1
6047,Reef Tower F Type Apartment Full Sea Facing,"emaar reef towers, emaar crescent bay",DHA Defence,Phase 8,82500000.0,32973.62,2502.0,3,4,1.0,3.0,11.0,1.0,1,1,1,1,2020.0,flat,6.0,Moderately Old,8.0,1.0,1,5
13327,Luxury 5 Bedroom Apartment | Easy 12-Month Ins...,"al madni heights, university road",University Road,Al Madni Heights,35000000.0,15618.03,2241.0,5,5,1.0,NaN,NaN,1.0,1,0,1,0,2026.0,flat,0.0,New,5.5,1.0,0,3
18873,Architectural Perfection Brand New 500 Yards B...,"dha phase 8, dha defence",DHA Defence,Phase 8,280000000.0,62222.22,4500.0,6,7,3.0,NaN,2.0,3.0,0,2,1,0,2026.0,house,0.0,New,9.0,2.0,2,5
11207,120 Sq Yards Ground +1 AVAILABLE IN REASONABLE...,"gulshan-e-maymar - sector q, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,18500000.0,17129.63,1080.0,4,4,2.0,NaN,1.0,2.0,0,1,1,1,2025.0,house,1.0,Relatively New,7.5,2.0,1,2
11717,Stunning 1050 Square Feet Flat In Falaknaz Pre...,"falaknaz presidency, malir",Malir,Falaknaz,15500000.0,14719.85,1053.0,2,2,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,2
4521,"Bungalow for sale 500sq yard ,off khy Badban D...","dha phase 7, dha defence",DHA Defence,Phase 7,150000000.0,33333.33,4500.0,6,7,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,5
20512,950 Square Feet Flat For Sale In Clifton - Blo...,"clifton - block 1, clifton",Clifton,Clifton Block 1,17100000.0,17924.53,954.0,2,2,1.0,7.0,20.0,1.0,3,0,1,0,2030.0,flat,-4.0,Under Construction,5.5,1.0,0,3
22134,FLAT FOR SALE - BISMILLAH TOWERS - 4 BED DD,"gulistan-e-jauhar - block 10, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 10,26000000.0,9629.63,2700.0,4,6,1.0,NaN,14.0,1.0,3,1,1,0,2011.0,flat,15.0,Old,7.0,1.0,1,3
12896,Brand New House For Sale Ground Plus 1,"model colony - malir, malir",Malir,Model Colony,29000000.0,26411.66,1098.0,4,5,2.0,NaN,2.0,1.0,0,2,1,1,2025.0,house,1.0,Relatively New,10.0,1.0,2,4
8700,Beautifully Constructed Flat Is Available For ...,"askari 5 - sector j, askari 5",Cantt,Askari 5,51000000.0,17017.02,2997.0,4,4,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,3
17565,Brand New 500-Yard Luxury Bungalow For Sale In...,"dha phase 8, dha defence",DHA Defence,Phase 8,330000000.0,73333.33,4500.0,6,7,0.0,NaN,3.0,4.0,0,0,1,1,2026.0,house,0.0,New,5.0,2.0,0,5
6026,House For Sale At Phase 2 Proper Prime Locatio...,"dha phase 2, dha defence",DHA Defence,Phase 2,160000000.0,35555.56,4500.0,5,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,5
6015,Golden Town Flat For Sale,"golden town, malir",Malir,Golden Town,8000000.0,8888.89,900.0,2,2,1.0,5.0,18.0,4.0,4,2,1,1,2022.0,flat,4.0,Relatively New,9.5,2.0,2,1
14796,Saima Royal Residency Flat For Sale,"gulshan-e-iqbal - block 2, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 2,21500000.0,17961.57,1197.0,2,2,2.0,NaN,19.0,2.0,2,1,1,1,2025.0,flat,1.0,Relatively New,8.0,2.0,1,4
18464,Beautiful House For Buy In Gulistan E Jauhar B...,"gulistan-e-jauhar - block 7, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 7,49900000.0,23101.85,2160.0,6,6,0.0,NaN,NaN,1.0,0,0,1,1,NaN,house,NaN,NaN,5.0,1.0,0,3
2784,Flats Available For Resale Scheme 33 Near Dow ...,"scheme 33, karachi",Scheme 33,NaN,15000000.0,11990.41,1251.0,2,2,2.0,1.0,9.0,1.0,2,1,1,1,NaN,flat,NaN,NaN,8.0,1.0,1,<NA>
4099,Reserve A House Of 240 Square Yards Now In Gul...,"gulshan-e-iqbal - block 1, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 1,71000000.0,32870.37,2160.0,8,6,0.0,NaN,2.0,2.0,0,0,0,1,2024.0,house,2.0,Relatively New,3.0,2.0,0,2
16062,Your Search Ends Right Here With The Beautiful...,"bahria town - precinct 8, bahria town karachi",Bahria Town,Precinct 8,46000000.0,18790.85,2448.0,5,5,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,2
13026,Prime Location House Of 200 Square Yards In Ba...,"bahria town - precinct 10-a, bahria town karachi",Bahria Town,Precinct 10A,19000000.0,10555.56,1800.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,1
19603,Chance Deal! Well-Renovated 500 Sq. Yards Hous...,"falcon complex faisal, karachi",Shah Faisal,Falcon Complex Faisal,337500000.0,75000.00,4500.0,5,5,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN,6.5,1.0,1,5
3318,2 Rooms Flat For Sale Ground Floor 50 Sq Yards...,"allahwala town - sector 31-b, allahwala town",Korangi,Allahwala Town,2200000.0,4888.89,450.0,2,1,1.0,NaN,9.0,3.0,2,1,1,1,NaN,flat,NaN,NaN,8.0,2.0,1,1
13050,200 Square Yard Classic Bungalow For Sale In C...,"chapal uptown, karachi",Scheme 33,Chapal Uptown,21000000.0,11666.67,1800.0,4,4,1.0,NaN,2.0,1.0,0,1,1,1,2022.0,house,4.0,Relatively New,7.5,1.0,1,1
15504,Prime Location Affordable House For Sale In Na...,"naya nazimabad, karachi",Naya Nazimabad,NaN,39000000.0,36111.11,1080.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,<NA>
6557,Well Maintained Flat For Sale,"north nazimabad - block h, north nazimabad",North Nazimabad,Block H,32500000.0,20994.83,1548.0,3,3,1.0,NaN,NaN,1.0,4,1,1,1,NaN,flat,NaN,NaN,8.0,1.0,1,3
18558,2 Bed DD Flat With Roof For Sale in Kaneez Fat...,"gulshan-e-kaneez fatima, scheme 33",Scheme 33,Gulshan-E-Kaneez Fatima,10000000.0,10010.01,999.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,2
8737,Flat For Sale,"gulshan-e-iqbal - block 2, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 2,21000000.0,13972.06,1503.0,3,3,1.0,NaN,NaN,0.0,1,0,1,1,NaN,flat,NaN,NaN,5.5,0.0,0,4
11664,Highly-Desirable Prime Location Flat Available...,"north nazimabad - block m, north nazimabad",North Nazimabad,Block M,18500000.0,11232.54,1647.0,3,3,1.0,NaN,5.0,1.0,1,1,1,1,2025.0,flat,1.0,Relatively New,8.0,1.0,1,2
16884,Brand New House For Sale,"capital cooperative housing society, scheme 33...",Scheme 33,Sector 35-A,85000000.0,23611.11,3600.0,8,6,0.0,NaN,NaN,0.0,0,0,0,0,2026.0,house,0.0,New,0.0,0.0,0,4
2661,Perfect Prime Location 240 Square Yards House ...,"naya nazimabad - block b, naya nazimabad",Naya Nazimabad,Block B,48000000.0,22222.22,2160.0,3,3,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house,NaN,NaN,7.5,1.0,1,4
19985,Prime Location Flat Of 1300 Square Feet Is Ava...,"bahadurabad, gulshan-e-iqbal town",Gulshan-e-Iqbal Town,Bahadurabad,27500000.0,21219.14,1296.0,3,3,0.0,NaN,NaN,0.0,0,0,1,0,NaN,flat,NaN,NaN,2.0,0.0,0,5
8968,"Chance Deal, Beautifully Maintained 300 Sqryd ...","gulistan-e-jauhar - block 15, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 15,68500000.0,25370.37,2700.0,6,6,2.0,NaN,2.0,3.0,0,1,1,1,NaN,house,NaN,NaN,7.5,2.0,1,4
13687,Brand New House For Sale 80 Sq Yards - Single ...,"north town residency, surjani town",Gadap,Surjani Town,9000000.0,12500.00,720.0,2,2,1.0,NaN,NaN,4.0,0,1,1,1,2026.0,house,0.0,New,7.5,2.0,1,1
71,80 Sq Yard Leased House For Sale Executive Blo...,"north town residency, surjani town",Gadap,Surjani Town,13600000.0,18888.89,720.0,4,3,2.0,NaN,2.0,0.0,0,0,1,1,2026.0,house,0.0,New,3.0,0.0,0,1
5999,Apartment For Sale DHA Phase 4,"dha phase 4, dha defence",DHA Defence,Phase 4,16000000.0,16016.02,999.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,5
20967,In DHA Phase 7 Extension 100 Square Yards Hous...,"dha phase 7 extension, dha defence",DHA Defence,Phase 7 Extension,65000000.0,72222.22,900.0,4,5,1.0,NaN,1.0,1.0,0,1,1,1,2021.0,house,5.0,Relatively New,7.5,1.0,1,5
18629,"PREMIUM 1,000 SQ YD 2-UNIT HOUSE FOR SALE IN D...","dha phase 2, dha defence",DHA Defence,Phase 2,260000000.0,28888.89,9000.0,10,6,0.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,5
2418,55 Square Yards Flat For Sale In Korangi - Sec...,"korangi - sector 31-a, korangi industrial area",Korangi,Korangi Industrial Area,3200000.0,6464.65,495.0,2,2,1.0,1.0,4.0,1.0,1,1,1,1,2015.0,flat,11.0,Old,8.0,1.0,1,1
6771,SAWERA ICON A PROJECT BY OK ESTATE & BUILDERS,"saddar town, karachi",Saddar,NaN,19800000.0,11891.89,1665.0,3,3,1.0,NaN,18.0,1.0,2,1,1,1,2026.0,flat,0.0,New,8.0,1.0,1,<NA>
11083,Best Options For Prime Location House Is Avail...,"gwalior cooperative housing society, scheme 33",Scheme 33,Gwalior Cooperative Housing Society,26000000.0,24074.07,1080.0,2,2,0.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,4
2772,ULTRALUXE SIGNATURE LIVING: MAGNIFICENT 1000 S...,"dha phase 6, dha defence",DHA Defence,Phase 6,650000000.0,72222.22,9000.0,6,6,2.0,NaN,NaN,8.0,0,2,1,1,2026.0,house,0.0,New,10.0,2.0,2,5
16824,Brand New Lease House For Sale,"gulshan-e-maymar - sector r, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,21000000.0,19444.44,1080.0,4,5,2.0,NaN,NaN,1.0,0,0,1,0,2024.0,house,2.0,Relatively New,4.0,1.0,0,2
7725,3Bed DDL 125sq yd Villa FOR SALE at ALI BLOCK ...,"bahria town - ali block, bahria town - precinc...",Bahria Town,Ali Block,11000000.0,9777.78,1125.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN,6.5,1.0,1,2
12718,The Tilt HMR Waterfront | Luxury 1 Bed Partial...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,40000000.0,41536.86,963.0,1,1,1.0,NaN,NaN,1.0,1,0,1,0,NaN,flat,NaN,NaN,5.5,1.0,0,5
8273,Flat Available For Sale In Sharafabad Karachi,"sharfabad, gulshan-e-iqbal town",Gulshan-e-Iqbal Town,Sharfabad,32000000.0,18812.46,1701.0,3,3,1.0,1.0,3.0,1.0,1,1,1,1,2015.0,flat,11.0,Old,8.0,1.0,1,4
10997,Direct Owner Meeting Well Maintained House,"gulistan-e-jauhar - block 2, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 2,82000000.0,20246.91,4050.0,10,6,3.0,NaN,2.0,4.0,0,1,1,1,2024.0,house,2.0,Relatively New,7.5,2.0,1,4
10318,Defence 500 viii slightly used like New bungal...,"dha phase 8, dha defence",DHA Defence,Phase 8,210000000.0,46666.67,4500.0,5,6,2.0,NaN,2.0,2.0,0,1,0,0,2023.0,house,3.0,Relatively New,4.5,2.0,1,5
11282,ROOMI ICON BOOKING FLAT FOR SALE,"jinnah avenue, karachi",Jinnah Avenue,NaN,39500000.0,16135.62,2448.0,3,4,1.0,15.0,24.0,4.0,1,0,1,1,2030.0,flat,-4.0,Under Construction,6.5,2.0,0,<NA>
10329,500 Yards Luxury Brand New Semi-Furnished Hous...,"dha phase 8, dha defence",DHA Defence,Phase 8,285000000.0,63333.33,4500.0,5,6,2.0,NaN,NaN,2.0,0,0,1,1,2025.0,house,1.0,Relatively New,5.0,2.0,0,5
1626,(DIRECT OWNER DEAL),"malir cantonment, cantt",Cantt,Malir Cantonment,75000000.0,20833.33,3600.0,7,6,2.0,NaN,2.0,2.0,0,2,1,1,2025.0,house,1.0,Relatively New,10.0,2.0,2,2
7497,BUNGALOW FOR SALE,"dha phase 7 extension, dha defence",DHA Defence,Phase 7 Extension,63000000.0,58333.33,1080.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,5
5799,House For Sale,"gulshan-e-iqbal - block 19, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 19,55000000.0,38194.44,1440.0,5,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,3
4389,Prime Properties Presents A New Standard of Li...,"darul aman society, karachi",Jamshed Town,Pechs,25000000.0,25025.03,999.0,2,2,1.0,NaN,30.0,2.0,6,1,1,1,2024.0,flat,2.0,Relatively New,8.0,2.0,1,5
1801,BABAR VISTA | BANK LOAN APPLICABLE | K BLOCK |...,"north nazimabad - block k, north nazimabad",North Nazimabad,Block K,11000000.0,11213.05,981.0,2,2,1.0,NaN,4.0,1.0,1,0,1,1,2000.0,flat,26.0,Old,6.5,1.0,0,1
9858,Flat For Sale In Gulshan Apartment 3 Bed DD,"gulshan-e-iqbal - block 7, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 7,13500000.0,11278.20,1197.0,3,3,1.0,NaN,NaN,1.0,1,1,1,1,2025.0,flat,1.0,Relatively New,8.0,1.0,1,3
13719,Brigadier House Available For Sale In Askari 6...,"askari 6, malir cantonment",Cantt,Askari 6,78000000.0,28888.89,2700.0,5,6,2.0,NaN,2.0,2.0,0,1,1,1,2026.0,house,0.0,New,7.5,2.0,1,4
6570,"Flat for Sale 3rd Floor, 2 Bed Rooms Drawing D...","north nazimabad - block k, north nazimabad",North Nazimabad,Block K,7000000.0,8739.08,801.0,2,2,1.0,NaN,NaN,1.0,0,0,1,0,2000.0,flat,26.0,Old,3.0,1.0,0,1
4259,120 Yards One Unit House 2 Kitchens 6 Washrooms,"naya nazimabad, karachi",Naya Nazimabad,NaN,45000000.0,41666.67,1080.0,4,6,1.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,1.0,0.0,0,<NA>
13788,950 Square Feet 2 Bedroom Flat Available For S...,"bahria town - precinct 19, bahria town karachi",Bahria Town,Precinct 19,7500000.0,7861.64,954.0,2,2,1.0,NaN,6.0,1.0,4,0,1,0,NaN,flat,NaN,NaN,5.5,1.0,0,1
10497,Prime Location House Of 120 Square Yards Avail...,"saima arabian villas, gadap town",Gadap,Surjani Town,12600000.0,11666.67,1080.0,2,2,2.0,NaN,2.0,1.0,0,1,1,1,NaN,house,NaN,NaN,7.5,1.0,1,1
8529,READY TO MOVE 235sq Yd 3Bed DDL Villas FOR SAL...,"bahria town - precinct 27, bahria town karachi",Bahria Town,Precinct 27,14000000.0,6619.39,2115.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN,6.5,1.0,1,1
14184,Get In Touch Now To Buy A 700 Square Feet Flat...,"gulshan-e-maymar - sector r, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,7200000.0,10256.41,702.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0.0,0,2
4382,400 Yards Single Storey In Block 13 Gulistan E...,"gulistan-e-jauhar - block 13, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 13,65000000.0,18055.56,3600.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0.0,0,2

In [179]:
df.groupby(['sub_location_score', 'location', 'sub_location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median'
).reset_index()

,sub_location_score,location,sub_location,count,median_ppsqft
0,1,Bahria Town,Bahria Apartments,120,8176.100
1,1,Bahria Town,Bahria Heights,57,6944.440
2,1,Bahria Town,Bahria Paradise,76,10000.000
3,1,Bahria Town,Bahria Sports City,128,6190.480
4,1,Bahria Town,Bahria Town,62,9934.210
5,1,Bahria Town,Precinct 10A,92,10555.560
6,1,Bahria Town,Precinct 10B,68,10133.330
7,1,Bahria Town,Precinct 11A,85,10555.560
8,1,Bahria Town,Precinct 11B,74,10599.420
9,1,Bahria Town,Precinct 15,22,10488.890
10,1,Bahria Town,Precinct 16,37,11233.660
11,1,Bahria Town,Precinct 19,34,8415.090
12,1,Bahria Town,Precinct 27,61,7328.610
13,1,Bahria Town,Precinct 31,84,7092.200
14,1,Bahria Town,Private High-Rises,92,6410.260
15,1,Bin Qasim Town,Mateen Complex,34,4137.120
16,1,Cantt,P & T Colony,10,5270.655
17,1,Clifton,Gizri,11,10555.560
18,1,Federal B Area,Block 20,10,18269.230
19,1,Gadap,Memon Goth,55,11111.110
20,1,Gadap,Surjani Town,273,11805.560
21,1,Gulistan-e-Jauhar,Block 17,114,7652.920
22,1,Gulistan-e-Jauhar,Block 18,132,8561.280
23,1,Gulistan-e-Jauhar,Block 20,25,8208.210
24,1,Gulistan-e-Jauhar,Safoora Goth,8,11126.735
25,1,Gulshan-e-Iqbal Town,Block 13D3,32,11020.035
26,1,Gulshan-e-Iqbal Town,Block 17,44,24114.330
27,1,Jamshed Town,Mehmoodabad,19,7777.780
28,1,Korangi,Allahwala Town,113,5277.780
29,1,Korangi,Korangi Industrial Area,23,6464.650
30,1,Malir,Golden Town,16,6166.785
31,1,Malir,Jamia Millia Road,20,7842.540
32,1,Malir,Malir Town Residency,13,6712.960
33,1,Nazimabad,Nazimabad 3,20,11916.170
34,1,North Nazimabad,Block G,32,9664.445
35,1,North Nazimabad,Block K,51,10928.960
36,1,Scheme 33,Chapal Uptown,16,11284.720
37,1,Scheme 33,Daniyal Residency,62,11396.010
38,1,Scheme 33,Federal Government Employees Housing Foundation,20,7980.545
39,1,Scheme 33,Gulzar-E-Hijri,10,10429.195
40,1,Scheme 33,Noman Residencia,25,11284.720
41,1,Scheme 33,Rafi Premier Residency,26,11168.380
42,1,Scheme 33,Saadi Road,57,11191.050
43,1,Scheme 33,Sumaira Sky Tower,14,10625.380
44,1,Shah Faisal,Green Town / Rafah-E-Aam Belt,24,7853.640
45,1,Shah Faisal,Shamsi / Al-Falah Belt,27,7222.220
46,1,Super Highway,Rabia Enclave,9,10555.560
47,1,Super Highway,Saima Villas,72,11701.390
48,1,University Road,Burj-Ul-Harmain,143,11695.910
49,1,University Road,Safari Enclave Apartments,18,11845.785
50,2,Bahria Town,Ali Block,109,12444.440
51,2,Bahria Town,Bahria Hills,54,13055.555
52,2,Bahria Town,Iqbal Villas,60,13523.390
53,2,Bahria Town,Precinct 1,70,14666.670
54,2,Bahria Town,Precinct 12,21,12888.890
55,2,Bahria Town,Precinct 17,26,12500.000
56,2,Bahria Town,Precinct 2,13,13523.390
57,2,Bahria Town,Precinct 4,49,12222.220
58,2,Bahria Town,Precinct 6,63,13111.110
59,2,Bahria Town,Precinct 7,14,13333.330
60,2,Bahria Town,Precinct 8,94,14297.390
61,2,Bahria Town,Precinct 9,11,13333.330
62,2,Bahria Town,Quaid Villas,72,13472.220
63,2,Cantt,Malir Cantonment,20,15017.360
64,2,Federal B Area,Block 11,29,22222.220
65,2,Federal B Area,Block 13,41,25000.000
66,2,Gadap,Gulshan-E-Maymar,468,13425.930
67,2,Gulistan-e-Jauhar,Block 1,39,23148.150
68,2,Gulistan-e-Jauhar,Block 11,33,13433.520
69,2,Gulistan-e-Jauhar,Block 13,132,11287.015
70,2,Gulshan-e-Iqbal Town,Block 1,194,14885.700
71,2,Gulshan-e-Iqbal Town,Block 11,34,13468.440
72,2,Gulshan-e-Iqbal Town,Block 13,10,29861.110
73,2,Gulshan-e-Iqbal Town,Block 13A,41,14697.240
74,2,Gulshan-e-Iqbal Town,Block 13B,24,13463.355
75,2,Gulshan-e-Iqbal Town,Block 13D2,76,13737.940
76,2,Jinnah Avenue,Aman Golf View,38,14245.010
77,2,Jinnah Avenue,Metropolis Residency,112,14565.130
78,2,Jinnah Avenue,Roomi Residency,33,13533.830
79,2,Korangi,Kda Employees Society,16,12037.040
80,2,Malir,Falaknaz,118,11574.070
81,2,Malir,Malir Link To Super Highway,82,12167.920
82,2,Naya Nazimabad,Block M,23,27777.780
83,2,Nazimabad,Nazimabad 1,8,12833.145
84,2,Nazimabad,Nazimabad 2,5,15277.780
85,2,North Karachi,New Karachi,10,13385.885
86,2,North Nazimabad,Block M,52,13033.525
87,2,Scheme 33,Chapal Courtyard,39,13756.610
88,2,Scheme 33,Falaknaz,110,13242.400
89,2,Scheme 33,Fatima Ali Towers,19,13176.640
90,2,Scheme 33,Grey Noor Tower,27,13752.280
91,2,Scheme 33,Gulshan-E-Kaneez Fatima,76,12283.950
92,2,Scheme 33,Karachi University Housing Society,51,12063.490
93,2,Scheme 33,Kathiawar Society,14,12391.625
94,2,Scheme 33,Lakhani Fantasia,38,13031.330
95,2,Scheme 33,Sania Corner,25,12449.800
96,2,Scheme 33,Sawera Enclave,27,12500.000
97,2,Scheme 33,Sector 15-A,49,14775.410
98,2,Scheme 33,Sector 18-A,63,12234.710
99,2,Scheme 33,Sector 34-A,75,13661.200
100,2,Scheme 33,Sector 36-A,25,12500.000
101,2,Scheme 33,Taloo Gold Residency,10,12345.790
102,2,Scheme 33,Yousaf Goth,11,13425.930
103,2,Shah Faisal,Gohar Green City Cluster,42,12610.675
104,2,University Road,City Tower And Shopping Mall,17,14444.440
105,3,Bahria Town,Precinct 18,5,16666.670
106,3,Cantt,Askari 5,626,17222.220
107,3,Cantt,Gulshan-E-Roomi,43,18518.520
108,3,Clifton,Clifton Block 1,87,19083.970
109,3,Clifton,Clifton Block 4,52,20794.365
110,3,DHA Defence,Phase 2 Extension,69,16708.440
111,3,Federal B Area,Block 10,75,20925.930
112,3,Federal B Area,Block 16,19,32407.410
113,3,Federal B Area,Block 19,17,28703.700
114,3,Federal B Area,Block 7,11,10416.670
115,3,Federal B Area,Block 8,18,13813.810
116,3,Federal B Area,Shahrah-E-Pakistan,10,15517.185
117,3,Gulistan-e-Jauhar,Block 10,39,12777.780
118,3,Gulistan-e-Jauhar,Block 16,71,15714.920
119,3,Gulistan-e-Jauhar,Block 16A,14,15529.720
120,3,Gulistan-e-Jauhar,Block 19,74,14644.830
121,3,Gulistan-e-Jauhar,Block 3A,119,15605.490
122,3,Gulistan-e-Jauhar,Block 7,122,14697.450
123,3,Gulistan-e-Jauhar,Block 8,12,17824.070
124,3,Gulshan-e-Iqbal Town,Block 10,21,21527.780
125,3,Gulshan-e-Iqbal Town,Block 10A,144,19285.725
126,3,Gulshan-e-Iqbal Town,Block 13C,39,15555.560
127,3,Gulshan-e-Iqbal Town,Block 16,23,22159.800
128,3,Gulshan-e-Iqbal Town,Block 19,17,32986.110
129,3,Gulshan-e-Iqbal Town,Block 7,91,22685.190
130,3,Gulshan-e-Iqbal Town,Callachi Cooperative Housing Society,302,19519.520
131,3,Jamshed Town,"Defence Skyline, Shaheed-E-Millat Expressway",12,17768.670
132,3,Jamshed Town,Jamshed Road,61,17342.740
133,3,Jamshed Town,Karachi Administration Employees Society,46,15772.025
134,3,Jamshed Town,Parsi Colony,21,21394.060
135,3,Malir,Airport,45,15432.100
136,3,Nazimabad,Nazimabad 4,22,15323.850
137,3,North Karachi,North Karachi Sector 11,80,18904.320
138,3,North Karachi,North Karachi Sector 5,49,17361.110
139,3,North Karachi,North Karachi Sector 7,38,15879.630
140,3,North Nazimabad,Block F,183,18888.890
141,3,North Nazimabad,Block H,131,20287.140
142,3,North Nazimabad,Block J,37,20609.320
143,3,North Nazimabad,Shadman,6,21759.260
144,3,Rashid Minhas Road,Lakhani Presidency,8,17369.455
145,3,Rashid Minhas Road,Lucky One Apartment,41,19607.840
146,3,Rashid Minhas Road,Saima Royal Residency,32,18588.135
147,3,Scheme 33,Chapal Sun City,33,19444.440
148,3,Scheme 33,Gulshan-E-Usman Housing Society,12,16435.185
149,3,Scheme 33,Saadi Garden,173,16203.700
150,3,Scheme 33,Saadi Town,272,18055.560
151,3,Scheme 33,Sadaf Cooperative Housing Society,30,19560.185
152,3,Scheme 33,Sadat-E-Amroha Cooperative Housing Society,10,19675.930
153,3,Scheme 33,Sector 16-A,42,15800.095
154,3,Scheme 33,Sector 19-A,33,17129.630
155,3,Scheme 33,Sector 22-A,18,19166.665
156,3,Scheme 33,Sector 51-A,29,19444.440
157,3,Scheme 33,Sector 52-A,28,19675.925
158,3,Super Highway,Oasis Park Residencia,6,19444.440
159,3,University Road,Al Madni Heights,41,15618.030
160,3,University Road,Saima Jinnah Avenue,50,15871.915
161,4,Cantt,Askari 6,585,24740.740
162,4,Clifton,Clifton Block 2,160,23047.635
163,4,Clifton,Clifton Block 3,11,23611.110
164,4,Clifton,Clifton Block 5,35,26276.280
165,4,DHA Defence,Phase 1,65,22222.220
166,4,DHA Defence,Phase 5,427,25555.560
167,4,Federal B Area,Block 12,54,28055.555
168,4,Federal B Area,Block 14,23,35185.190
169,4,Federal B Area,Block 15,18,31250.000
170,4,Federal B Area,Block 9,19,15000.000
171,4,Gulistan-e-Jauhar,Block 12,117,23148.150
172,4,Gulistan-e-Jauhar,Block 14,152,20000.000
173,4,Gulistan-e-Jauhar,Block 15,196,20833.330
174,4,Gulistan-e-Jauhar,Block 2,91,23611.110
175,4,Gulistan-e-Jauhar,Block 4,31,24305.560
176,4,Gulistan-e-Jauhar,Block 9,14,21180.555
177,4,Gulshan-e-Iqbal Town,Block 13D,58,26296.300
178,4,Gulshan-e-Iqbal Town,Block 14,16,21669.135
179,4,Gulshan-e-Iqbal Town,Block 2,78,22222.220
180,4,Gulshan-e-Iqbal Town,Block 4,92,19702.260
181,4,Gulshan-e-Iqbal Town,Block 4A,13,25000.000
182,4,Gulshan-e-Iqbal Town,Block 9,17,28571.430
183,4,Gulshan-e-Iqbal Town,"Cp Barar Society, Gulshan-E-Iqbal Town",14,25231.965
184,4,Gulshan-e-Iqbal Town,Dhoraji Colony,59,23286.760
185,4,Gulshan-e-Iqbal Town,Sharfabad,47,23611.110
186,4,Jamshed Town,Amil Colony,29,23023.020
187,4,Jamshed Town,Cosmopolitan Society,17,25025.030
188,4,Jamshed Town,Garden East,34,25483.890
189,4,Jamshed Town,Muslimabad Society,12,24451.100
190,4,Jamshed Town,Soldier Bazar,22,22150.995
191,4,Jamshed Town,Tariq Road,39,23286.760
192,4,Malir,Falcon Complex New Malir,516,26444.440
193,4,Malir,Model Colony,96,24933.860
194,4,Malir,Saima Projects,37,25000.000
195,4,Naya Nazimabad,Block B,67,29166.670
196,4,Nazimabad,Nazimabad 5,9,22974.100
197,4,North Karachi,Buffer Zone,105,25000.000
198,4,North Karachi,North Karachi Sector 8,14,23564.815
199,4,North Karachi,North Karachi Sector 9,26,25925.930
200,4,North Nazimabad,Block B,83,18296.740
201,4,North Nazimabad,Block I,34,24765.510
202,4,North Nazimabad,Block L,120,22927.690
203,4,North Nazimabad,Block N,118,22131.845
204,4,North Nazimabad,"Shadman Town - Sector-14/A, Shadman",6,25462.960
205,4,North Nazimabad,"Shadman Town - Sector-14/B, Shadman",36,26736.110
206,4,Scheme 33,Andaleeb Cooperative Housing Society,13,25925.930
207,4,Scheme 33,Cotton Export Cooperative Housing Society,23,22222.220
208,4,Scheme 33,Gwalior Cooperative Housing Society,40,23148.150
209,4,Scheme 33,Hansa Society,58,26898.145
210,4,Scheme 33,Meerut Society,57,22222.220
211,4,Scheme 33,Musalmanan-E-Punjab Cooperative Housing Society,22,22314.815
212,4,Scheme 33,Punjabi Saudagar Society,156,24537.040
213,4,Scheme 33,Sector 17-A,74,26722.225
214,4,Scheme 33,Sector 24-A,22,24120.370
215,4,Scheme 33,Sector 35-A,249,25000.000
216,4,Scheme 33,Zeenatabad,42,21990.740
217,4,Shah Faisal,Saima Luxury Belt,33,23148.150
218,5,Cantt,Dohs Phase 1,51,32323.230
219,5,Cantt,Dohs Phase 2,11,31313.130
220,5,Cantt,Navy Housing Scheme Karsaz,131,65873.020
221,5,Clifton,Bath Island,128,32769.060
222,5,Clifton,Clifton Block 6,11,32771.540
223,5,Clifton,Clifton Block 7,40,28570.240
224,5,Clifton,Clifton Block 8,89,30030.030
225,5,Clifton,Clifton Block 9,94,28115.160
226,5,Clifton,Frere Town,43,27777.780
227,5,DHA Defence,"Darakhshan Villas, Dha Phase 6",7,28011.200
228,5,DHA Defence,Phase 2,54,28888.890
229,5,DHA Defence,Phase 4,168,41666.665
230,5,DHA Defence,Phase 5 Extension,21,28888.890
231,5,DHA Defence,Phase 6,907,31111.110
232,5,DHA Defence,Phase 7,296,32222.220
233,5,DHA Defence,Phase 7 Extension,147,55555.560
234,5,DHA Defence,Phase 8,2241,44022.500
235,5,DHA Defence,Phase 8 Extension,12,50000.000
236,5,Federal B Area,Block 6,12,29686.680
237,5,Gulistan-e-Jauhar,Askari 4,34,27000.780
238,5,Gulistan-e-Jauhar,Block 3,57,28935.190
239,5,Gulistan-e-Jauhar,Block 5,7,25641.030
240,5,Gulistan-e-Jauhar,Block 6,4,8578.080
241,5,Gulistan-e-Jauhar,Kda Overseas Bungalows,7,37593.980
242,5,Gulistan-e-Jauhar,Latifi Cooperative Housing Society,8,34027.775
243,5,Gulshan-e-Iqbal Town,Adamjee Nagar,16,55555.560
244,5,Gulshan-e-Iqbal Town,Bahadurabad,121,27924.750
245,5,Gulshan-e-Iqbal Town,Block 13D1,65,37037.040
246,5,Gulshan-e-Iqbal Town,Block 3,39,26620.370
247,5,Gulshan-e-Iqbal Town,Block 5,84,32175.925
248,5,Gulshan-e-Iqbal Town,Block 6,57,27777.780
249,5,Gulshan-e-Iqbal Town,Dawood Society,13,66666.670
250,5,Gulshan-e-Iqbal Town,Gulshan-E-Jamal,13,28888.890
251,5,Gulshan-e-Iqbal Town,Kda Officers Society,43,88888.890
252,5,Gulshan-e-Iqbal Town,Kda Scheme 1,87,40740.740
253,5,Gulshan-e-Iqbal Town,Kda Scheme 1 Extension,11,46666.670
254,5,Gulshan-e-Iqbal Town,Mohammad Ali Society,18,49000.000
255,5,Gulshan-e-Iqbal Town,National Stadium Colony,14,114271.940
256,5,Jamshed Town,Amir Khusro,36,51666.665
257,5,Jamshed Town,Hill Park,27,44444.440
258,5,Jamshed Town,Khalid Bin Walid Road,124,27224.570
259,5,Jamshed Town,Pechs,284,32384.935
260,5,Jamshed Town,Shaheed Millat Road,179,31500.570
261,5,Jamshed Town,Shahra-E-Qaideen,14,28584.875
262,5,Jamshed Town,Smchs - Sindhi Muslim Society,45,29782.360
263,5,Korangi,Qayyumabad,16,29526.060
264,5,Naya Nazimabad,Block A,95,38932.630
265,5,Naya Nazimabad,Block C,87,37962.960
266,5,Naya Nazimabad,Block D,68,34699.075
267,5,North Karachi,North Karachi Sector 10,14,30138.890
268,5,North Nazimabad,Block A,50,20370.370
269,5,North Nazimabad,Block C,12,30555.560
270,5,North Nazimabad,Block D,45,20911.360
271,5,Scheme 33,Central Information Cooperative Housing Society,10,27546.300
272,5,Shah Faisal,Falcon Complex Faisal,14,76666.670

In [180]:
# df[(df['sub_location'].value_counts() < 10)==True]

In [181]:
counts = df['sub_location'].value_counts()
df[df['sub_location'].isin(counts[counts < 10].index)][['location','sub_location','sub_location_score']].value_counts()

location            sub_location                         sub_location_score
Nazimabad           Nazimabad 5                          4                     9
Super Highway       Rabia Enclave                        1                     9
Gulistan-e-Jauhar   Latifi Cooperative Housing Society   5                     8
                    Safoora Goth                         1                     8
Nazimabad           Nazimabad 1                          2                     8
Rashid Minhas Road  Lakhani Presidency                   3                     8
DHA Defence         Darakhshan Villas, Dha Phase 6       5                     7
Gulistan-e-Jauhar   Kda Overseas Bungalows               5                     7
North Nazimabad     Shadman                              3                     6
                    Shadman Town - Sector-14/A, Shadman  4                     6
Super Highway       Oasis Park Residencia                3                     6
Bahria Town         Precinct 18                          3                     5
Nazimabad           Nazimabad 2                          2                     5
Name: count, dtype: int64

In [182]:
mapping = {
    "Darakhshan Villas, Dha Phase 6": "Phase 6"
}

df['sub_location'] = df['sub_location'].replace(mapping)

In [183]:
mapping = {
    "North Nazimabad Block M": "Block M"
}

df['sub_location'] = df['sub_location'].replace(mapping)

In [184]:
# merge similar sub_locations
sub_location_mapping = {
    "Shadman Town - Sector-14/A, Shadman": "Shadman",
    "Shadman Town - Sector-14/B, Shadman": "Shadman",
    "Shadman": "Shadman",
}


# This section handles Apply Mapping.df['sub_location'] = df['sub_location'].replace(sub_location_mapping)

In [185]:
df[df['location']=='Nazimabad']['sub_location'].value_counts()

sub_location
Nazimabad 4    22
Nazimabad 3    20
Nazimabad 5     9
Nazimabad 1     8
Nazimabad 2     5
Name: count, dtype: int64

In [186]:
df.shape

(22759, 25)

In [187]:
import pandas as pd


# This section handles Smoothing Strength.k = 10

# This section handles Overall Market Median.overall_median = df['price_per_sqft'].median()


# This section handles Sub Location Statistics.
sub_stats = (
    df.groupby('sub_location')
    .agg(
        median_ppsqft=('price_per_sqft', 'median'),
        count=('price_per_sqft', 'count')
    )
)


# This section handles Bayesian Count Smoothing.
sub_stats['adjusted_ppsqft'] = (
    (sub_stats['count'] / (sub_stats['count'] + k))
    *
    sub_stats['median_ppsqft']
    +
    (k / (sub_stats['count'] + k))
    *
    overall_median
)


# This section handles Unequal Luxury Distribution.
sub_stats['sub_location_score'] = pd.qcut(
    sub_stats['adjusted_ppsqft'],
    q=[
        0,
        0.30,
        0.65,
        0.85,
        0.95,
        1
    ],
    labels=[
        1,
        2,
        3,
        4,
        5
    ],
    duplicates='drop'
)


# This section handles Make Float.sub_stats['sub_location_score'] = (
    sub_stats['sub_location_score']
    .astype(float)
)


# # -----------------------------
# # Map back
# # -----------------------------

# df['sub_location_score'] = (
#     df['sub_location_score']
#     .astype(float)
# )

In [188]:
df['sub_location_score'] = df['sub_location'].map(sub_location_score)

In [189]:
df.shape

(22759, 25)

In [190]:
df['sub_location_score'].isnull().sum()

np.int64(2486)

In [192]:
df['sub_location_score'] = (
    df['sub_location_score']
    .astype(float)
)

In [193]:
df.groupby(['location','sub_location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median')

                                                                      count  \
location             sub_location
Bahria Town          Ali Block                                          109
                     Bahria Apartments                                  120
                     Bahria Heights                                      57
                     Bahria Hills                                        54
                     Bahria Paradise                                     76
                     Bahria Sports City                                 128
                     Bahria Town                                         62
                     Iqbal Villas                                        60
                     Precinct 1                                          70
                     Precinct 10A                                        92
                     Precinct 10B                                        68
                     Precinct 11A                                        85
                     Precinct 11B                                        74
                     Precinct 12                                         21
                     Precinct 15                                         22
                     Precinct 16                                         37
                     Precinct 17                                         26
                     Precinct 18                                          5
                     Precinct 19                                         34
                     Precinct 2                                          13
                     Precinct 27                                         61
                     Precinct 31                                         84
                     Precinct 4                                          49
                     Precinct 6                                          63
                     Precinct 7                                          14
                     Precinct 8                                          94
                     Precinct 9                                          11
                     Private High-Rises                                  92
                     Quaid Villas                                        72
Bin Qasim Town       Mateen Complex                                      34
Cantt                Askari 5                                           626
                     Askari 6                                           585
                     Dohs Phase 1                                        51
                     Dohs Phase 2                                        11
                     Gulshan-E-Roomi                                     43
                     Malir Cantonment                                    20
                     Navy Housing Scheme Karsaz                         131
                     P & T Colony                                        10
Clifton              Bath Island                                        128
                     Clifton Block 1                                     87
                     Clifton Block 2                                    160
                     Clifton Block 3                                     11
                     Clifton Block 4                                     52
                     Clifton Block 5                                     35
                     Clifton Block 6                                     11
                     Clifton Block 7                                     40
                     Clifton Block 8                                     89
                     Clifton Block 9                                     94
                     Frere Town                                          43
                     Gizri                                               11
DHA Defence          Phase 1                                             65
                     Phase 2                                             54
                     Phase 2 Extension                                   69
                     Phase 4                                            168
                     Phase 5                                            427
                     Phase 5 Extension                                   21
                     Phase 6                                            914
                     Phase 7                                            296
                     Phase 7 Extension                                  147
                     Phase 8                                           2241
                     Phase 8 Extension                                   12
Federal B Area       Block 10                                            75
                     Block 11                                            29
                     Block 12                                            54
                     Block 13                                            41
                     Block 14                                            23
                     Block 15                                            18
                     Block 16                                            19
                     Block 19                                            17
                     Block 20                                            10
                     Block 6                                             12
                     Block 7                                             11
                     Block 8                                             18
                     Block 9                                             19
                     Shahrah-E-Pakistan                                  10
Gadap                Gulshan-E-Maymar                                   468
                     Memon Goth                                          55
                     Surjani Town                                       273
Gulistan-e-Jauhar    Askari 4                                            34
                     Block 1                                             39
                     Block 10                                            39
                     Block 11                                            33
                     Block 12                                           117
                     Block 13                                           132
                     Block 14                                           152
                     Block 15                                           196
                     Block 16                                            71
                     Block 16A                                           14
                     Block 17                                           114
                     Block 18                                           132
                     Block 19                                            74
                     Block 2                                             91
                     Block 20                                            25
                     Block 3                                             57
                     Block 3A                                           119
                     Block 4                                             31
                     Block 5                                              7
                     Block 6                                              4
                     Block 7                                            122
                     Block 8                                             12
                     Block 9                                             14
                     Kda Overseas Bungalows                               7
                     Latifi Cooperative Housing Society                   8
                     Safoora Goth                                         8
Gulshan-e-Iqbal Town Adamjee Nagar                                       16
                     Bahadurabad                                        121
                     Block 1                                            194
                     Block 10                                            21
                     Block 10A                                          144
                     Block 11                                            34
                     Block 13                                            10
                     Block 13A                                           41
                     Block 13B                                           24
                     Block 13C                                           39
                     Block 13D                                           58
                     Block 13D1                                          65
                     Block 13D2                                          76
                     Block 13D3                                          32
                     Block 14                                            16
                     Block 16                                            23
                     Block 17                                            44
                     Block 19                                            17
                     Block 2                                             78
                     Block 3                                             39
                     Block 4                                             92
                     Block 4A                                            13
                     Block 5                                             84
                     Block 6                                             57
                     Block 7                                             91
                     Block 9                                             17
                     Callachi Cooperative Housing Society               302
                     Cp Barar Society, Gulshan-E-Iqbal Town              14
                     Dawood Society                                      13
                     Dhoraji Colony                                      59
                     Gulshan-E-Jamal                                     13
                     Kda Officers Society                                43
                     Kda Scheme 1                                        87
                     Kda Scheme 1 Extension                              11
                     Mohammad Ali Society                                18
                     National Stadium Colony                             14
                     Sharfabad                                           47
Jamshed Town         Amil Colony                                         29
                     Amir Khusro                                         36
                     Cosmopolitan Society                                17
                     Defence Skyline, Shaheed-E-Millat Expressway        12
                     Garden East                                         34
                     Hill Park                                           27
                     Jamshed Road                                        61
                     Karachi Administration Employees Society            46
                     Khalid Bin Walid Road                              124
                     Mehmoodabad                                         19
                     Muslimabad Society                                  12
                     Parsi Colony                                        21
                     Pechs                                              284
                     Shaheed Millat Road                                179
                     Shahra-E-Qaideen                                    14
                     Smchs - Sindhi Muslim Society                       45
                     Soldier Bazar                                       22
                     Tariq Road                                          39
Jinnah Avenue        Aman Golf View                                      38
                     Metropolis Residency                               112
                     Roomi Residency                                     33
Korangi              Allahwala Town                                     113
                     Kda Employees Society                               16
                     Korangi Industrial Area                             23
                     Qayyumabad                                          16
Malir                Airport                                             45
                     Falaknaz                                           118
                     Falcon Complex New Malir                           516
                     Golden Town                                         16
                     Jamia Millia Road                                   20
                     Malir Link To Super Highway                         82
                     Malir Town Residency                                13
                     Model Colony                                        96
                     Saima Projects                                      37
Naya Nazimabad       Block A                                             95
                     Block B                                             67
                     Block C                                             87
                     Block D                                             68
                     Block M                                             23
Nazimabad            Nazimabad 1                                          8
                     Nazimabad 2                                          5
                     Nazimabad 3                                         20
                     Nazimabad 4                                         22
                     Nazimabad 5                                          9
North Karachi        Buffer Zone                                        105
                     New Karachi                                         10
                     North Karachi Sector 10                             14
                     North Karachi Sector 11                             80
                     North Karachi Sector 5                              49
                     North Karachi Sector 7                              38
                     North Karachi Sector 8                              14
                     North Karachi Sector 9                              26
North Nazimabad      Block A                                             50
                     Block B                                             83
                     Block C                                             12
                     Block D                                             45
                     Block F                                            183
                     Block G                                             32
                     Block H                                            131
                     Block I                                             34
                     Block J                                             37
                     Block K                                             51
                     Block L                                            120
                     Block M                                             52
                     Block N                                            118
                     Shadman                                             48
Rashid Minhas Road   Lakhani Presidency                                   8
                     Lucky One Apartment                                 41
                     Saima Royal Residency                               32
Scheme 33            Andaleeb Cooperative Housing Society                13
                     Central Information Cooperative Housing Society     10
                     Chapal Courtyard                                    39
                     Chapal Sun City                                     33
                     Chapal Uptown                                       16
                     Cotton Export Cooperative Housing Society           23
                     Daniyal Residency                                   62
                     Falaknaz                                           110
                     Fatima Ali Towers                                   19
                     Federal Government Employees Housing Foundation     20
                     Grey Noor Tower                                     27
                     Gulshan-E-Kaneez Fatima                             76
                     Gulshan-E-Usman Housing Society                     12
                     Gulzar-E-Hijri                                      10
                     Gwalior Cooperative Housing Society                 40
                     Hansa Society                                       58
                     Karachi University Housing Society                  51
                     Kathiawar Society                                   14
                     Lakhani Fantasia                                    38
                     Meerut Society                                      57
                     Musalmanan-E-Punjab Cooperative Housing Society     22
                     Noman Residencia                                    25
                     Punjabi Saudagar Society                           156
                     Rafi Premier Residency                              26
                     Saadi Garden                                       173
                     Saadi Road                                          57
                     Saadi Town                                         272
                     Sadaf Cooperative Housing Society                   30
                     Sadat-E-Amroha Cooperative Housing Society          10
                     Sania Corner                                        25
                     Sawera Enclave                                      27
                     Sector 15-A                                         49
                     Sector 16-A                                         42
                     Sector 17-A                                         74
                     Sector 18-A                                         63
                     Sector 19-A                                         33
                     Sector 22-A                                         18
                     Sector 24-A                                         22
                     Sector 34-A                                         75
                     Sector 35-A                                        249
                     Sector 36-A                                         25
                     Sector 51-A                                         29
                     Sector 52-A                                         28
                     Sumaira Sky Tower                                   14
                     Taloo Gold Residency                                10
                     Yousaf Goth                                         11
                     Zeenatabad                                          42
Shah Faisal          Falcon Complex Faisal                               14
                     Gohar Green City Cluster                            42
                     Green Town / Rafah-E-Aam Belt                       24
                     Saima Luxury Belt                                   33

In [194]:
df['location'].unique()

array(['Scheme 33', 'North Nazimabad', 'Jamshed Town',
       'Gulistan-e-Jauhar', 'DHA Defence', 'Cantt', 'DHA City',
       'Shah Faisal', 'Gadap', 'Naya Nazimabad', 'Gulshan-e-Iqbal Town',
       'Bahria Town', 'Malir', 'Civil Lines', 'Jinnah Avenue', 'Clifton',
       'North Karachi', 'Korangi', 'Nazimabad', 'Federal B Area',
       'Rashid Minhas Road', 'Saddar', 'Super Highway', 'University Road',
       'Shahra-e-Faisal', 'Bin Qasim Town', 'Northern Bypass',
       'Tipu Sultan Road', 'Defence View', 'National Highway',
       'Abul Hassan Isphani Road'], dtype=object)

In [195]:
df.loc[df['location'].str.lower() == 'cantt', 'location'] = 'Malir Cantt'

df[df['sub_location']=='Malir Cantonment']['sub_location']

mask = df['sub_location'].str.contains('Gulshan-E-Roomi', case=False, na=False)
df.loc[mask, 'location'] = 'Scheme 33'
df.loc[mask, 'sub_location'] = 'Gulshan-e-Roomi'

mask = df['sub_location'].str.contains('P & T Colony', case=False, na=False)
df.loc[mask,'location']='Clifton'
df.loc[mask, 'sub_location'] = 'Gizri'



mask = df['sub_location'].str.contains('navy housing scheme karsaz|karsaz', case=False, na=False)
df.loc[mask, 'location'] = 'Karsaz'
df.loc[mask, 'sub_location'] = 'Navy Housing Scheme Karsaz'

In [196]:
df.loc[df['sub_location'] == 'Malir Cantonment', 'sub_location'] = np.nan

In [197]:
df['location'].unique()

array(['Scheme 33', 'North Nazimabad', 'Jamshed Town',
       'Gulistan-e-Jauhar', 'DHA Defence', 'Malir Cantt', 'DHA City',
       'Shah Faisal', 'Gadap', 'Naya Nazimabad', 'Gulshan-e-Iqbal Town',
       'Bahria Town', 'Malir', 'Civil Lines', 'Jinnah Avenue', 'Clifton',
       'North Karachi', 'Korangi', 'Nazimabad', 'Federal B Area',
       'Rashid Minhas Road', 'Saddar', 'Super Highway', 'Karsaz',
       'University Road', 'Shahra-e-Faisal', 'Bin Qasim Town',
       'Northern Bypass', 'Tipu Sultan Road', 'Defence View',
       'National Highway', 'Abul Hassan Isphani Road'], dtype=object)

In [198]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Bahria Sports City                                  128
                      Bahria Apartments                                   120
                      Ali Block                                           109
                      Precinct 8                                           94
                      Precinct 10A                                         92
                      Private High-Rises                                   92
                      Precinct 11A                                         85
                      Precinct 31                                          84
                      Bahria Paradise                                      76
                      Precinct 11B                                         74
                      Quaid Villas                                         72
                      Precinct 1                                           70
                      Precinct 10B                                         68
                      Precinct 6                                           63
                      Bahria Town                                          62
                      Precinct 27                                          61
                      Iqbal Villas                                         60
                      Bahria Heights                                       57
                      Bahria Hills                                         54
                      Precinct 4                                           49
                      Precinct 16                                          37
                      Precinct 19                                          34
                      Precinct 17                                          26
                      Precinct 15                                          22
                      Precinct 12                                          21
                      Precinct 7                                           14
                      Precinct 2                                           13
                      Precinct 9                                           11
                      Precinct 18                                           5
Bin Qasim Town        Mateen Complex                                       34
Clifton               Clifton Block 2                                     160
                      Bath Island                                         128
                      Clifton Block 9                                      94
                      Clifton Block 8                                      89
                      Clifton Block 1                                      87
                      Clifton Block 4                                      52
                      Frere Town                                           43
                      Clifton Block 7                                      40
                      Clifton Block 5                                      35
                      Gizri                                                21
                      Clifton Block 3                                      11
                      Clifton Block 6                                      11
DHA Defence           Phase 8                                            2241
                      Phase 6                                             914
                      Phase 5                                             427
                      Phase 7                                             296
                      Phase 4                                             168
                      Phase 7 Extension                                   147
                      Phase 2 Extension                                    69
                      Phase 1                                              65
                      Phase 2                                              54
                      Phase 5 Extension                                    21
                      Phase 8 Extension                                    12
Federal B Area        Block 10                                             75
                      Block 12                                             54
                      Block 13                                             41
                      Block 11                                             29
                      Block 14                                             23
                      Block 16                                             19
                      Block 9                                              19
                      Block 15                                             18
                      Block 8                                              18
                      Block 19                                             17
                      Block 6                                              12
                      Block 7                                              11
                      Block 20                                             10
                      Shahrah-E-Pakistan                                   10
Gadap                 Gulshan-E-Maymar                                    468
                      Surjani Town                                        273
                      Memon Goth                                           55
Gulistan-e-Jauhar     Block 15                                            196
                      Block 14                                            152
                      Block 13                                            132
                      Block 18                                            132
                      Block 7                                             122
                      Block 3A                                            119
                      Block 12                                            117
                      Block 17                                            114
                      Block 2                                              91
                      Block 19                                             74
                      Block 16                                             71
                      Block 3                                              57
                      Block 1                                              39
                      Block 10                                             39
                      Askari 4                                             34
                      Block 11                                             33
                      Block 4                                              31
                      Block 20                                             25
                      Block 16A                                            14
                      Block 9                                              14
                      Block 8                                              12
                      Latifi Cooperative Housing Society                    8
                      Safoora Goth                                          8
                      Block 5                                               7
                      Kda Overseas Bungalows                                7
                      Block 6                                               4
Gulshan-e-Iqbal Town  Callachi Cooperative Housing Society                302
                      Block 1                                             194
                      Block 10A                                           144
                      Bahadurabad                                         121
                      Block 4                                              92
                      Block 7                                              91
                      Kda Scheme 1                                         87
                      Block 5                                              84
                      Block 2                                              78
                      Block 13D2                                           76
                      Block 13D1                                           65
                      Dhoraji Colony                                       59
                      Block 13D                                            58
                      Block 6                                              57
                      Sharfabad                                            47
                      Block 17                                             44
                      Kda Officers Society                                 43
                      Block 13A                                            41
                      Block 13C                                            39
                      Block 3                                              39
                      Block 11                                             34
                      Block 13D3                                           32
                      Block 13B                                            24
                      Block 16                                             23
                      Block 10                                             21
                      Mohammad Ali Society                                 18
                      Block 19                                             17
                      Block 9                                              17
                      Adamjee Nagar                                        16
                      Block 14                                             16
                      Cp Barar Society, Gulshan-E-Iqbal Town               14
                      National Stadium Colony                              14
                      Block 4A                                             13
                      Dawood Society                                       13
                      Gulshan-E-Jamal                                      13
                      Kda Scheme 1 Extension                               11
                      Block 13                                             10
Jamshed Town          Pechs                                               284
                      Shaheed Millat Road                                 179
                      Khalid Bin Walid Road                               124
                      Jamshed Road                                         61
                      Karachi Administration Employees Society             46
                      Smchs - Sindhi Muslim Society                        45
                      Tariq Road                                           39
                      Amir Khusro                                          36
                      Garden East                                          34
                      Amil Colony                                          29
                      Hill Park                                            27
                      Soldier Bazar                                        22
                      Parsi Colony                                         21
                      Mehmoodabad                                          19
                      Cosmopolitan Society                                 17
                      Shahra-E-Qaideen                                     14
                      Defence Skyline, Shaheed-E-Millat Expressway         12
                      Muslimabad Society                                   12
Jinnah Avenue         Metropolis Residency                                112
                      Aman Golf View                                       38
                      Roomi Residency                                      33
Karsaz                Navy Housing Scheme Karsaz                          131
Korangi               Allahwala Town                                      113
                      Korangi Industrial Area                              23
                      Kda Employees Society                                16
                      Qayyumabad                                           16
Malir                 Falcon Complex New Malir                            516
                      Falaknaz                                            118
                      Model Colony                                         96
                      Malir Link To Super Highway                          82
                      Airport                                              45
                      Saima Projects                                       37
                      Jamia Millia Road                                    20
                      Golden Town                                          16
                      Malir Town Residency                                 13
Malir Cantt           Askari 5                                            626
                      Askari 6                                            585
                      Dohs Phase 1                                         51
                      Dohs Phase 2                                         11
Naya Nazimabad        Block A                                              95
                      Block C                                              87
                      Block D                                              68
                      Block B                                              67
                      Block M                                              23
Nazimabad             Nazimabad 4                                          22
                      Nazimabad 3                                          20
                      Nazimabad 5                                           9
                      Nazimabad 1                                           8
                      Nazimabad 2                                           5
North Karachi         Buffer Zone                                         105
                      North Karachi Sector 11                              80
                      North Karachi Sector 5                               49
                      North Karachi Sector 7                               38
                      North Karachi Sector 9                               26
                      North Karachi Sector 10                              14
                      North Karachi Sector 8                               14
                      New Karachi                                          10
North Nazimabad       Block F                                             183
                      Block H                                             131
                      Block L                                             120
                      Block N                                             118
                      Block B                                              83
                      Block M                                              52
                      Block K                                              51
                      Block A                                              50
                      Shadman                                              48
                      Block D                                              45
                      Block J                                              37
                      Block I                                              34
                      Block G                                              32
                      Block C                                              12
Rashid Minhas Road    Lucky One Apartment                                  41
                      Saima Royal Residency                                32
                      Lakhani Presidency                                    8
Scheme 33             Saadi Town                                          272
                      Sector 35-A                                         249
                      Saadi Garden                                        173
                      Punjabi Saudagar Society                            156
                      Falaknaz                                            110
                      Gulshan-E-Kaneez Fatima                              76
                      Sector 34-A                                          75
                      Sector 17-A                                          74
                      Sector 18-A                                          63
                      Daniyal Residency                                    62
                      Hansa Society                                        58
                      Meerut Society                                       57
                      Saadi Road                                           57
                      Karachi University Housing Society                   51
                      Sector 15-A                                          49
                      Gulshan-e-Roomi                                      43
                      Sector 16-A                                          42
                      Zeenatabad                                           42
                      Gwalior Cooperative Housing Society                  40
                      Chapal Courtyard                                     39
                      Lakhani Fantasia                                     38
                      Chapal Sun City                                      33
                      Sector 19-A                                          33
                      Sadaf Cooperative Housing Society                    30
                      Sector 51-A                                          29
                      Sector 52-A                                          28
                      Grey Noor Tower                                      27
                      Sawera Enclave                                       27
                      Rafi Premier Residency                               26
                      Noman Residencia                                     25
                      Sania Corner                                         25
                      Sector 36-A                                          25
                      Cotton Export Cooperative Housing Society            23
                      Musalmanan-E-Punjab Cooperative Housing Society      22
                      Sector 24-A                                          22
                      Federal Government Employees Housing Foundation      20
                      Fatima Ali Towers                                    19
                      Sector 22-A                                          18
                      Chapal Uptown                                        16
                      Kathiawar Society                                    14
                      Sumaira Sky Tower                                    14
                      Andaleeb Cooperative Housing Society                 13
                      Gulshan-E-Usman Housing Society                      12
                      Yousaf Goth                                          11
                      Central Information Cooperative Housing Society      10
                      Gulzar-E-Hijri                                       10
                      Sadat-E-Amroha Cooperative Housing Society           10
                      Taloo Gold Residency                                 10

In [199]:
df.groupby(['location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median'
).sort_values(by='median_ppsqft',ascending=False)

                          count  median_ppsqft
location
Karsaz                      131      65873.020
DHA Defence                4473      39647.580
Tipu Sultan Road             32      36539.745
Civil Lines                  86      33487.120
Naya Nazimabad              809      30462.960
Jamshed Town               1030      27777.780
Clifton                     831      26455.030
Federal B Area              428      25000.000
Malir                       997      24444.440
Gulshan-e-Iqbal Town       2305      21857.920
Northern Bypass              31      21269.840
North Karachi               409      20000.000
North Nazimabad            1077      19294.740
Rashid Minhas Road           83      18812.460
Shahra-e-Faisal              46      18208.180
Malir Cantt                1382      18166.500
Defence View                 47      17450.140
Gulistan-e-Jauhar          1828      15740.740
Scheme 33                  2834      15231.725
DHA City                     58      14354.350
Jinnah Avenue               247      14254.390
Nazimabad                    74      14066.950
Saddar                       90      13543.565
University Road             345      12820.510
Shah Faisal                 164      12719.105
Gadap                       796      12500.000
Super Highway               115      11805.560
Bahria Town                1757      10555.560
Abul Hassan Isphani Road     18       9583.615
Korangi                     174       5586.770
Bin Qasim Town               57       4373.520
National Highway              5       4255.320

In [295]:
location_score = {
    # 5 - Premium / Luxury
    "Karsaz": 5,
    "DHA Defence": 5,
    "Clifton": 5,
    "Malir Cantt": 5,
    "Naya Nazimabad": 5,

    # 4 - High Demand
    "Jamshed Town": 4,
    "Federal B Area": 4,
    "Malir": 4,
    "Gulshan-e-Iqbal Town": 4,
    "North Nazimabad": 4,

    # 3 - Good Residential
    "North Karachi": 3,
    "F.B. Area": 3,
    "Gulshan-e-Iqbal Town": 3,
    "Gulistan-e-Jauhar": 3,
    "Scheme 33": 3,
    "Nazimabad": 3,
    "Bahria Town": 3,

    # 2 - Developing
    "Shah Faisal": 2,
    "Gadap": 2,
    "Super Highway": 2,

    # 1 - Low Demand
    "Korangi": 1,
    "Bin Qasim Town": 1
}

In [299]:
df["location_score"] = df["location"].map(location_score)

In [202]:
df.groupby("location_score")["price_per_sqft"].agg(["count", "mean", "median"])

                count          mean    median
location_score
1.0               231   8647.884675   5555.56
2.0              1075  13742.562056  12273.90
3.0              6902  16051.604674  13511.11
4.0              5837  25306.352460  23286.76
5.0              7626  34473.504079  32222.22

In [203]:
scheme33_mapping = {

    # ---------- Sector 15-A ----------
    "Sadaf Cooperative Housing Society": "Sector 15-A",
    "Sadat-E-Amroha Cooperative Housing Society": "Sector 15-A",

    # ---------- Sector 16-A ----------
    "Gulshan-E-Kaneez Fatima": "Sector 16-A",

    # ---------- Sector 17-A ----------
    "Gwalior Cooperative Housing Society": "Sector 17-A",

    # ---------- Sector 18-A ----------
    "Karachi University Housing Society": "Sector 18-A",

    # ---------- Sector 19-A ----------
    "Kathiawar Society": "Sector 19-A",

    # ---------- Sector 20-A ----------
    "Musalmanan-E-Punjab Cooperative Housing Society": "Sector 20-A",

    # ---------- Sector 24-B ----------
    "Federal Government Employees Housing Foundation": "Sector 24-B",

    # ---------- Sector 25-B ----------
    "Fatima Ali Towers": "Sector 25-B",

    # ---------- Sector 29 ----------
    "Chapal Courtyard": "Sector 29",
    "Chapal Sun City": "Sector 29",
    "Grey Noor Tower": "Sector 29",

    # ---------- Sector 30 ----------
    "Noman Residencia": "Sector 30",

    # ---------- Sector 34-A ----------
    "Central Information Cooperative Housing Society": "Sector 34-A",
    "Lakhani Fantasia": "Sector 34-A",

    # ---------- Sector 35-A ----------
    "Daniyal Residency": "Sector 35-A",

    # ---------- Sector 36-A ----------
    "Hansa Society": "Sector 36-A",

    # ---------- Sector 47 ----------
    "Saadi Town": "Sector 47",

    # ---------- Sector 48-A ----------
    "Andaleeb Cooperative Housing Society": "Sector 48-A",

    # ---------- Sector 51-A ----------
    "Cotton Export Cooperative Housing Society": "Sector 51-A",
}

df["sub_location"] = df["sub_location"].replace(scheme33_mapping)

In [204]:
bahria_mapping = {
    "Iqbal Villas": "Precinct 2",
    "Quaid Villas": "Precinct 2",
    "Ali Block": "Precinct 12",
    "Bahria Town":np.nan
}
df["sub_location"] = df["sub_location"].replace(bahria_mapping)

In [205]:
df.groupby(['sub_location_score', 'location', 'sub_location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median'
).reset_index()

,sub_location_score,location,sub_location,count,median_ppsqft
0,1.0,Bahria Town,Bahria Apartments,120,8176.100
1,1.0,Bahria Town,Bahria Heights,57,6944.440
2,1.0,Bahria Town,Bahria Paradise,76,10000.000
3,1.0,Bahria Town,Bahria Sports City,128,6190.480
4,1.0,Bahria Town,Precinct 10A,92,10555.560
5,1.0,Bahria Town,Precinct 10B,68,10133.330
6,1.0,Bahria Town,Precinct 11A,85,10555.560
7,1.0,Bahria Town,Precinct 11B,74,10599.420
8,1.0,Bahria Town,Precinct 15,22,10488.890
9,1.0,Bahria Town,Precinct 16,37,11233.660
10,1.0,Bahria Town,Precinct 19,34,8415.090
11,1.0,Bahria Town,Precinct 27,61,7328.610
12,1.0,Bahria Town,Precinct 31,84,7092.200
13,1.0,Bahria Town,Private High-Rises,92,6410.260
14,1.0,Bin Qasim Town,Mateen Complex,34,4137.120
15,1.0,Clifton,Gizri,21,8925.320
16,1.0,Federal B Area,Block 20,10,18269.230
17,1.0,Gadap,Memon Goth,55,11111.110
18,1.0,Gadap,Surjani Town,273,11805.560
19,1.0,Gulistan-e-Jauhar,Block 17,114,7652.920
20,1.0,Gulistan-e-Jauhar,Block 18,132,8561.280
21,1.0,Gulistan-e-Jauhar,Block 20,25,8208.210
22,1.0,Gulistan-e-Jauhar,Safoora Goth,8,11126.735
23,1.0,Gulshan-e-Iqbal Town,Block 13D3,32,11020.035
24,1.0,Gulshan-e-Iqbal Town,Block 17,44,24114.330
25,1.0,Jamshed Town,Mehmoodabad,19,7777.780
26,1.0,Korangi,Allahwala Town,113,5277.780
27,1.0,Korangi,Korangi Industrial Area,23,6464.650
28,1.0,Malir,Golden Town,16,6166.785
29,1.0,Malir,Jamia Millia Road,20,7842.540
30,1.0,Malir,Malir Town Residency,13,6712.960
31,1.0,Nazimabad,Nazimabad 3,20,11916.170
32,1.0,North Nazimabad,Block G,32,9664.445
33,1.0,North Nazimabad,Block K,51,10928.960
34,1.0,Scheme 33,Chapal Uptown,16,11284.720
35,1.0,Scheme 33,Gulzar-E-Hijri,10,10429.195
36,1.0,Scheme 33,Rafi Premier Residency,26,11168.380
37,1.0,Scheme 33,Saadi Road,57,11191.050
38,1.0,Scheme 33,Sector 24-B,20,7980.545
39,1.0,Scheme 33,Sector 30,25,11284.720
40,1.0,Scheme 33,Sector 35-A,62,11396.010
41,1.0,Scheme 33,Sumaira Sky Tower,14,10625.380
42,1.0,Shah Faisal,Green Town / Rafah-E-Aam Belt,24,7853.640
43,1.0,Shah Faisal,Shamsi / Al-Falah Belt,27,7222.220
44,1.0,Super Highway,Rabia Enclave,9,10555.560
45,1.0,Super Highway,Saima Villas,72,11701.390
46,1.0,University Road,Burj-Ul-Harmain,143,11695.910
47,1.0,University Road,Safari Enclave Apartments,18,11845.785
48,2.0,Bahria Town,Bahria Hills,54,13055.555
49,2.0,Bahria Town,Precinct 1,70,14666.670
50,2.0,Bahria Town,Precinct 12,130,12533.330
51,2.0,Bahria Town,Precinct 17,26,12500.000
52,2.0,Bahria Town,Precinct 2,145,13523.390
53,2.0,Bahria Town,Precinct 4,49,12222.220
54,2.0,Bahria Town,Precinct 6,63,13111.110
55,2.0,Bahria Town,Precinct 7,14,13333.330
56,2.0,Bahria Town,Precinct 8,94,14297.390
57,2.0,Bahria Town,Precinct 9,11,13333.330
58,2.0,Federal B Area,Block 11,29,22222.220
59,2.0,Federal B Area,Block 13,41,25000.000
60,2.0,Gadap,Gulshan-E-Maymar,468,13425.930
61,2.0,Gulistan-e-Jauhar,Block 1,39,23148.150
62,2.0,Gulistan-e-Jauhar,Block 11,33,13433.520
63,2.0,Gulistan-e-Jauhar,Block 13,132,11287.015
64,2.0,Gulshan-e-Iqbal Town,Block 1,194,14885.700
65,2.0,Gulshan-e-Iqbal Town,Block 11,34,13468.440
66,2.0,Gulshan-e-Iqbal Town,Block 13,10,29861.110
67,2.0,Gulshan-e-Iqbal Town,Block 13A,41,14697.240
68,2.0,Gulshan-e-Iqbal Town,Block 13B,24,13463.355
69,2.0,Gulshan-e-Iqbal Town,Block 13D2,76,13737.940
70,2.0,Jinnah Avenue,Aman Golf View,38,14245.010
71,2.0,Jinnah Avenue,Metropolis Residency,112,14565.130
72,2.0,Jinnah Avenue,Roomi Residency,33,13533.830
73,2.0,Korangi,Kda Employees Society,16,12037.040
74,2.0,Malir,Falaknaz,118,11574.070
75,2.0,Malir,Malir Link To Super Highway,82,12167.920
76,2.0,Naya Nazimabad,Block M,23,27777.780
77,2.0,Nazimabad,Nazimabad 1,8,12833.145
78,2.0,Nazimabad,Nazimabad 2,5,15277.780
79,2.0,North Karachi,New Karachi,10,13385.885
80,2.0,North Nazimabad,Block M,52,13033.525
81,2.0,Scheme 33,Falaknaz,110,13242.400
82,2.0,Scheme 33,Sania Corner,25,12449.800
83,2.0,Scheme 33,Sawera Enclave,27,12500.000
84,2.0,Scheme 33,Sector 15-A,49,14775.410
85,2.0,Scheme 33,Sector 16-A,76,12283.950
86,2.0,Scheme 33,Sector 18-A,114,12165.240
87,2.0,Scheme 33,Sector 19-A,14,12391.625
88,2.0,Scheme 33,Sector 25-B,19,13176.640
89,2.0,Scheme 33,Sector 29,66,13754.445
90,2.0,Scheme 33,Sector 34-A,113,13366.750
91,2.0,Scheme 33,Sector 36-A,25,12500.000
92,2.0,Scheme 33,Taloo Gold Residency,10,12345.790
93,2.0,Scheme 33,Yousaf Goth,11,13425.930
94,2.0,Shah Faisal,Gohar Green City Cluster,42,12610.675
95,2.0,University Road,City Tower And Shopping Mall,17,14444.440
96,3.0,Bahria Town,Precinct 18,5,16666.670
97,3.0,Clifton,Clifton Block 1,87,19083.970
98,3.0,Clifton,Clifton Block 4,52,20794.365
99,3.0,DHA Defence,Phase 2 Extension,69,16708.440
100,3.0,Federal B Area,Block 10,75,20925.930
101,3.0,Federal B Area,Block 16,19,32407.410
102,3.0,Federal B Area,Block 19,17,28703.700
103,3.0,Federal B Area,Block 7,11,10416.670
104,3.0,Federal B Area,Block 8,18,13813.810
105,3.0,Federal B Area,Shahrah-E-Pakistan,10,15517.185
106,3.0,Gulistan-e-Jauhar,Block 10,39,12777.780
107,3.0,Gulistan-e-Jauhar,Block 16,71,15714.920
108,3.0,Gulistan-e-Jauhar,Block 16A,14,15529.720
109,3.0,Gulistan-e-Jauhar,Block 19,74,14644.830
110,3.0,Gulistan-e-Jauhar,Block 3A,119,15605.490
111,3.0,Gulistan-e-Jauhar,Block 7,122,14697.450
112,3.0,Gulistan-e-Jauhar,Block 8,12,17824.070
113,3.0,Gulshan-e-Iqbal Town,Block 10,21,21527.780
114,3.0,Gulshan-e-Iqbal Town,Block 10A,144,19285.725
115,3.0,Gulshan-e-Iqbal Town,Block 13C,39,15555.560
116,3.0,Gulshan-e-Iqbal Town,Block 16,23,22159.800
117,3.0,Gulshan-e-Iqbal Town,Block 19,17,32986.110
118,3.0,Gulshan-e-Iqbal Town,Block 7,91,22685.190
119,3.0,Gulshan-e-Iqbal Town,Callachi Cooperative Housing Society,302,19519.520
120,3.0,Jamshed Town,"Defence Skyline, Shaheed-E-Millat Expressway",12,17768.670
121,3.0,Jamshed Town,Jamshed Road,61,17342.740
122,3.0,Jamshed Town,Karachi Administration Employees Society,46,15772.025
123,3.0,Jamshed Town,Parsi Colony,21,21394.060
124,3.0,Malir,Airport,45,15432.100
125,3.0,Malir Cantt,Askari 5,626,17222.220
126,3.0,Nazimabad,Nazimabad 4,22,15323.850
127,3.0,North Karachi,North Karachi Sector 11,80,18904.320
128,3.0,North Karachi,North Karachi Sector 5,49,17361.110
129,3.0,North Karachi,North Karachi Sector 7,38,15879.630
130,3.0,North Nazimabad,Block F,183,18888.890
131,3.0,North Nazimabad,Block H,131,20287.140
132,3.0,North Nazimabad,Block J,37,20609.320
133,3.0,North Nazimabad,Shadman,48,24537.040
134,3.0,Rashid Minhas Road,Lakhani Presidency,8,17369.455
135,3.0,Rashid Minhas Road,Lucky One Apartment,41,19607.840
136,3.0,Rashid Minhas Road,Saima Royal Residency,32,18588.135
137,3.0,Scheme 33,Gulshan-E-Usman Housing Society,12,16435.185
138,3.0,Scheme 33,Gulshan-e-Roomi,43,18518.520
139,3.0,Scheme 33,Saadi Garden,173,16203.700
140,3.0,Scheme 33,Sector 15-A,40,19560.185
141,3.0,Scheme 33,Sector 16-A,42,15800.095
142,3.0,Scheme 33,Sector 19-A,33,17129.630
143,3.0,Scheme 33,Sector 22-A,18,19166.665
144,3.0,Scheme 33,Sector 29,33,19444.440
145,3.0,Scheme 33,Sector 47,272,18055.560
146,3.0,Scheme 33,Sector 51-A,29,19444.440
147,3.0,Scheme 33,Sector 52-A,28,19675.925
148,3.0,Super Highway,Oasis Park Residencia,6,19444.440
149,3.0,University Road,Al Madni Heights,41,15618.030
150,3.0,University Road,Saima Jinnah Avenue,50,15871.915
151,4.0,Clifton,Clifton Block 2,160,23047.635
152,4.0,Clifton,Clifton Block 3,11,23611.110
153,4.0,Clifton,Clifton Block 5,35,26276.280
154,4.0,DHA Defence,Phase 1,65,22222.220
155,4.0,DHA Defence,Phase 5,427,25555.560
156,4.0,Federal B Area,Block 12,54,28055.555
157,4.0,Federal B Area,Block 14,23,35185.190
158,4.0,Federal B Area,Block 15,18,31250.000
159,4.0,Federal B Area,Block 9,19,15000.000
160,4.0,Gulistan-e-Jauhar,Block 12,117,23148.150
161,4.0,Gulistan-e-Jauhar,Block 14,152,20000.000
162,4.0,Gulistan-e-Jauhar,Block 15,196,20833.330
163,4.0,Gulistan-e-Jauhar,Block 2,91,23611.110
164,4.0,Gulistan-e-Jauhar,Block 4,31,24305.560
165,4.0,Gulistan-e-Jauhar,Block 9,14,21180.555
166,4.0,Gulshan-e-Iqbal Town,Block 13D,58,26296.300
167,4.0,Gulshan-e-Iqbal Town,Block 14,16,21669.135
168,4.0,Gulshan-e-Iqbal Town,Block 2,78,22222.220
169,4.0,Gulshan-e-Iqbal Town,Block 4,92,19702.260
170,4.0,Gulshan-e-Iqbal Town,Block 4A,13,25000.000
171,4.0,Gulshan-e-Iqbal Town,Block 9,17,28571.430
172,4.0,Gulshan-e-Iqbal Town,"Cp Barar Society, Gulshan-E-Iqbal Town",14,25231.965
173,4.0,Gulshan-e-Iqbal Town,Dhoraji Colony,59,23286.760
174,4.0,Gulshan-e-Iqbal Town,Sharfabad,47,23611.110
175,4.0,Jamshed Town,Amil Colony,29,23023.020
176,4.0,Jamshed Town,Cosmopolitan Society,17,25025.030
177,4.0,Jamshed Town,Garden East,34,25483.890
178,4.0,Jamshed Town,Muslimabad Society,12,24451.100
179,4.0,Jamshed Town,Soldier Bazar,22,22150.995
180,4.0,Jamshed Town,Tariq Road,39,23286.760
181,4.0,Malir,Falcon Complex New Malir,516,26444.440
182,4.0,Malir,Model Colony,96,24933.860
183,4.0,Malir,Saima Projects,37,25000.000
184,4.0,Malir Cantt,Askari 6,585,24740.740
185,4.0,Naya Nazimabad,Block B,67,29166.670
186,4.0,Nazimabad,Nazimabad 5,9,22974.100
187,4.0,North Karachi,Buffer Zone,105,25000.000
188,4.0,North Karachi,North Karachi Sector 8,14,23564.815
189,4.0,North Karachi,North Karachi Sector 9,26,25925.930
190,4.0,North Nazimabad,Block B,83,18296.740
191,4.0,North Nazimabad,Block I,34,24765.510
192,4.0,North Nazimabad,Block L,120,22927.690
193,4.0,North Nazimabad,Block N,118,22131.845
194,4.0,Scheme 33,Meerut Society,57,22222.220
195,4.0,Scheme 33,Punjabi Saudagar Society,156,24537.040
196,4.0,Scheme 33,Sector 17-A,114,25000.000
197,4.0,Scheme 33,Sector 20-A,22,22314.815
198,4.0,Scheme 33,Sector 24-A,22,24120.370
199,4.0,Scheme 33,Sector 35-A,249,25000.000
200,4.0,Scheme 33,Sector 36-A,58,26898.145
201,4.0,Scheme 33,Sector 48-A,13,25925.930
202,4.0,Scheme 33,Sector 51-A,23,22222.220
203,4.0,Scheme 33,Zeenatabad,42,21990.740
204,4.0,Shah Faisal,Saima Luxury Belt,33,23148.150
205,5.0,Clifton,Bath Island,128,32769.060
206,5.0,Clifton,Clifton Block 6,11,32771.540
207,5.0,Clifton,Clifton Block 7,40,28570.240
208,5.0,Clifton,Clifton Block 8,89,30030.030
209,5.0,Clifton,Clifton Block 9,94,28115.160
210,5.0,Clifton,Frere Town,43,27777.780
211,5.0,DHA Defence,Phase 2,54,28888.890
212,5.0,DHA Defence,Phase 4,168,41666.665
213,5.0,DHA Defence,Phase 5 Extension,21,28888.890
214,5.0,DHA Defence,Phase 6,914,31111.110
215,5.0,DHA Defence,Phase 7,296,32222.220
216,5.0,DHA Defence,Phase 7 Extension,147,55555.560
217,5.0,DHA Defence,Phase 8,2241,44022.500
218,5.0,DHA Defence,Phase 8 Extension,12,50000.000
219,5.0,Federal B Area,Block 6,12,29686.680
220,5.0,Gulistan-e-Jauhar,Askari 4,34,27000.780
221,5.0,Gulistan-e-Jauhar,Block 3,57,28935.190
222,5.0,Gulistan-e-Jauhar,Block 5,7,25641.030
223,5.0,Gulistan-e-Jauhar,Block 6,4,8578.080
224,5.0,Gulistan-e-Jauhar,Kda Overseas Bungalows,7,37593.980
225,5.0,Gulistan-e-Jauhar,Latifi Cooperative Housing Society,8,34027.775
226,5.0,Gulshan-e-Iqbal Town,Adamjee Nagar,16,55555.560
227,5.0,Gulshan-e-Iqbal Town,Bahadurabad,121,27924.750
228,5.0,Gulshan-e-Iqbal Town,Block 13D1,65,37037.040
229,5.0,Gulshan-e-Iqbal Town,Block 3,39,26620.370
230,5.0,Gulshan-e-Iqbal Town,Block 5,84,32175.925
231,5.0,Gulshan-e-Iqbal Town,Block 6,57,27777.780
232,5.0,Gulshan-e-Iqbal Town,Dawood Society,13,66666.670
233,5.0,Gulshan-e-Iqbal Town,Gulshan-E-Jamal,13,28888.890
234,5.0,Gulshan-e-Iqbal Town,Kda Officers Society,43,88888.890
235,5.0,Gulshan-e-Iqbal Town,Kda Scheme 1,87,40740.740
236,5.0,Gulshan-e-Iqbal Town,Kda Scheme 1 Extension,11,46666.670
237,5.0,Gulshan-e-Iqbal Town,Mohammad Ali Society,18,49000.000
238,5.0,Gulshan-e-Iqbal Town,National Stadium Colony,14,114271.940
239,5.0,Jamshed Town,Amir Khusro,36,51666.665
240,5.0,Jamshed Town,Hill Park,27,44444.440
241,5.0,Jamshed Town,Khalid Bin Walid Road,124,27224.570
242,5.0,Jamshed Town,Pechs,284,32384.935
243,5.0,Jamshed Town,Shaheed Millat Road,179,31500.570
244,5.0,Jamshed Town,Shahra-E-Qaideen,14,28584.875
245,5.0,Jamshed Town,Smchs - Sindhi Muslim Society,45,29782.360
246,5.0,Karsaz,Navy Housing Scheme Karsaz,131,65873.020
247,5.0,Korangi,Qayyumabad,16,29526.060
248,5.0,Malir Cantt,Dohs Phase 1,51,32323.230
249,5.0,Malir Cantt,Dohs Phase 2,11,31313.130
250,5.0,Naya Nazimabad,Block A,95,38932.630
251,5.0,Naya Nazimabad,Block C,87,37962.960
252,5.0,Naya Nazimabad,Block D,68,34699.075
253,5.0,North Karachi,North Karachi Sector 10,14,30138.890
254,5.0,North Nazimabad,Block A,50,20370.370
255,5.0,North Nazimabad,Block C,12,30555.560
256,5.0,North Nazimabad,Block D,45,20911.360
257,5.0,Scheme 33,Sector 34-A,10,27546.300
258,5.0,Shah Faisal,Falcon Complex Faisal,14,76666.670

In [300]:
import pandas as pd

# Step 1: Median price/sqft for each sub-location
sub_stats = (
    df.groupby("sub_location")
      .agg(
          median_ppsqft=("price_per_sqft", "median"),
          count=("price_per_sqft", "size")
      )
      .reset_index()
)

# Step 2: Remove effect of very small groups
MIN_COUNT = 10

valid = sub_stats["count"] >= MIN_COUNT

sub_stats.loc[valid, "global_percentile"] = (
    sub_stats.loc[valid, "median_ppsqft"]
             .rank(method="average", pct=True)
)

# This section handles Fill Rare Sub-Locations With Median Percentile.sub_stats["global_percentile"] = (
    sub_stats["global_percentile"]
    .fillna(sub_stats.loc[valid, "global_percentile"].median())
)

# Step 3: Merge back
df = df.merge(
    sub_stats[["sub_location", "global_percentile"]],
    on="sub_location",
    how="left"
)

# Step 4: Normalize parent location score
# (1-5 --> 0-1)
parent_norm = (df["location_score"] - 1) / 4

# Step 5: Combine
combined_score = (
    0.8 * df["global_percentile"] +
    0.2 * parent_norm
)

# Step 6: Convert to 1-5 integer score
df["sub_location_score"] = pd.qcut(
    combined_score.rank(method="first"),
    q=5,
    labels=[1, 2, 3, 4, 5]
).astype(float)

In [286]:
import pandas as pd

# Step 1: Calculate median price/sqft for each sub-location
sub_stats = (
    df.groupby("sub_location")
      .agg(
          median_ppsqft=("price_per_sqft", "median"),
          count=("price_per_sqft", "size")
      )
      .reset_index()
)


# Step 2: Calculate global percentile of sub-locations
MIN_COUNT = 10

valid = sub_stats["count"] >= MIN_COUNT

sub_stats.loc[valid, "global_percentile"] = (
    sub_stats.loc[valid, "median_ppsqft"]
    .rank(method="average", pct=True)
)

# This section handles Handle Rare Sub-Locations.median_pct = sub_stats.loc[valid, "global_percentile"].median()

sub_stats["global_percentile"] = (
    sub_stats["global_percentile"]
    .fillna(median_pct)
)


# Step 3: Map percentile back to main dataframe
pct_map = sub_stats.set_index("sub_location")["global_percentile"]

df["global_percentile"] = df["sub_location"].map(pct_map)


# Step 4: Normalize parent location score
# 1-5 becomes 0-1
parent_norm = (df["location_score"] - 1) / 4


# Step 5: Combine parent score + market value
combined_score = (
    0.8 * df["global_percentile"] +
    0.2 * parent_norm
)


# Step 6: Convert into integer score 1-5
percentile = combined_score.rank(pct=True)

df["sub_location_score"] = pd.cut(
    percentile,
    bins=[0, 0.2, 0.4, 0.6, 0.8, 1],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
).astype(float)


# Step 7: Remove helper columns (optional)
df.drop(
    columns=["global_percentile"],
    inplace=True
)

In [208]:
df.groupby("sub_location_score").agg(
    count=("sub_location", "count"),
    median_ppsqft=("price_per_sqft", "median")
)

                    count  median_ppsqft
sub_location_score
1.0                  3900       10763.89
2.0                  4141       16290.73
3.0                  3761       22685.19
4.0                  4145       27652.09
5.0                  3711       42281.22

In [209]:
df.groupby(['sub_location_score', 'location', 'sub_location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median'
).reset_index()

,sub_location_score,location,sub_location,count,median_ppsqft
0,1.0,Bahria Town,Bahria Apartments,120,8176.100
1,1.0,Bahria Town,Bahria Heights,57,6944.440
2,1.0,Bahria Town,Bahria Hills,54,13055.555
3,1.0,Bahria Town,Bahria Paradise,76,10000.000
4,1.0,Bahria Town,Bahria Sports City,128,6190.480
5,1.0,Bahria Town,Precinct 10A,92,10555.560
6,1.0,Bahria Town,Precinct 10B,68,10133.330
7,1.0,Bahria Town,Precinct 11A,85,10555.560
8,1.0,Bahria Town,Precinct 11B,74,10599.420
9,1.0,Bahria Town,Precinct 12,130,12533.330
10,1.0,Bahria Town,Precinct 15,22,10488.890
11,1.0,Bahria Town,Precinct 16,37,11233.660
12,1.0,Bahria Town,Precinct 17,26,12500.000
13,1.0,Bahria Town,Precinct 19,34,8415.090
14,1.0,Bahria Town,Precinct 27,61,7328.610
15,1.0,Bahria Town,Precinct 31,84,7092.200
16,1.0,Bahria Town,Precinct 4,49,12222.220
17,1.0,Bahria Town,Precinct 6,63,13111.110
18,1.0,Bahria Town,Private High-Rises,92,6410.260
19,1.0,Bin Qasim Town,Mateen Complex,34,4137.120
20,1.0,Clifton,Gizri,21,8925.320
21,1.0,Federal B Area,Block 20,10,18269.230
22,1.0,Gadap,Gulshan-E-Maymar,468,13425.930
23,1.0,Gadap,Memon Goth,55,11111.110
24,1.0,Gadap,Surjani Town,273,11805.560
25,1.0,Gulistan-e-Jauhar,Block 13,132,11287.015
26,1.0,Gulistan-e-Jauhar,Block 17,114,7652.920
27,1.0,Gulistan-e-Jauhar,Block 18,132,8561.280
28,1.0,Gulistan-e-Jauhar,Block 20,25,8208.210
29,1.0,Gulshan-e-Iqbal Town,Block 13D3,32,11020.035
30,1.0,Gulshan-e-Iqbal Town,Block 17,44,24114.330
31,1.0,Jamshed Town,Mehmoodabad,19,7777.780
32,1.0,Korangi,Allahwala Town,113,5277.780
33,1.0,Korangi,Kda Employees Society,16,12037.040
34,1.0,Korangi,Korangi Industrial Area,23,6464.650
35,1.0,Malir,Golden Town,16,6166.785
36,1.0,Malir,Jamia Millia Road,20,7842.540
37,1.0,Malir,Malir Link To Super Highway,82,12167.920
38,1.0,Malir,Malir Town Residency,13,6712.960
39,1.0,Nazimabad,Nazimabad 3,20,11916.170
40,1.0,North Nazimabad,Block G,32,9664.445
41,1.0,North Nazimabad,Block K,51,10928.960
42,1.0,Scheme 33,Chapal Uptown,16,11284.720
43,1.0,Scheme 33,Falaknaz,110,13242.400
44,1.0,Scheme 33,Gulzar-E-Hijri,10,10429.195
45,1.0,Scheme 33,Rafi Premier Residency,26,11168.380
46,1.0,Scheme 33,Saadi Road,57,11191.050
47,1.0,Scheme 33,Sania Corner,25,12449.800
48,1.0,Scheme 33,Sawera Enclave,27,12500.000
49,1.0,Scheme 33,Sector 16-A,118,13033.525
50,1.0,Scheme 33,Sector 18-A,114,12165.240
51,1.0,Scheme 33,Sector 19-A,47,13049.100
52,1.0,Scheme 33,Sector 24-B,20,7980.545
53,1.0,Scheme 33,Sector 25-B,19,13176.640
54,1.0,Scheme 33,Sector 30,25,11284.720
55,1.0,Scheme 33,Sumaira Sky Tower,14,10625.380
56,1.0,Scheme 33,Taloo Gold Residency,10,12345.790
57,1.0,Shah Faisal,Gohar Green City Cluster,42,12610.675
58,1.0,Shah Faisal,Green Town / Rafah-E-Aam Belt,24,7853.640
59,1.0,Shah Faisal,Shamsi / Al-Falah Belt,27,7222.220
60,1.0,Super Highway,Saima Villas,72,11701.390
61,2.0,Bahria Town,Precinct 1,70,14666.670
62,2.0,Bahria Town,Precinct 18,5,16666.670
63,2.0,Bahria Town,Precinct 2,145,13523.390
64,2.0,Bahria Town,Precinct 7,14,13333.330
65,2.0,Bahria Town,Precinct 8,94,14297.390
66,2.0,Bahria Town,Precinct 9,11,13333.330
67,2.0,DHA Defence,Phase 2 Extension,69,16708.440
68,2.0,Federal B Area,Block 10,75,20925.930
69,2.0,Federal B Area,Block 11,29,22222.220
70,2.0,Federal B Area,Block 13,41,25000.000
71,2.0,Federal B Area,Block 16,19,32407.410
72,2.0,Federal B Area,Block 19,17,28703.700
73,2.0,Federal B Area,Block 7,11,10416.670
74,2.0,Federal B Area,Block 8,18,13813.810
75,2.0,Federal B Area,Shahrah-E-Pakistan,10,15517.185
76,2.0,Gulistan-e-Jauhar,Block 1,39,23148.150
77,2.0,Gulistan-e-Jauhar,Block 10,39,12777.780
78,2.0,Gulistan-e-Jauhar,Block 11,33,13433.520
79,2.0,Gulistan-e-Jauhar,Block 16,71,15714.920
80,2.0,Gulistan-e-Jauhar,Block 16A,14,15529.720
81,2.0,Gulistan-e-Jauhar,Block 19,74,14644.830
82,2.0,Gulistan-e-Jauhar,Block 3A,119,15605.490
83,2.0,Gulistan-e-Jauhar,Block 7,122,14697.450
84,2.0,Gulistan-e-Jauhar,Block 8,12,17824.070
85,2.0,Gulistan-e-Jauhar,Kda Overseas Bungalows,7,37593.980
86,2.0,Gulistan-e-Jauhar,Latifi Cooperative Housing Society,8,34027.775
87,2.0,Gulistan-e-Jauhar,Safoora Goth,8,11126.735
88,2.0,Gulshan-e-Iqbal Town,Block 1,194,14885.700
89,2.0,Gulshan-e-Iqbal Town,Block 10,21,21527.780
90,2.0,Gulshan-e-Iqbal Town,Block 11,34,13468.440
91,2.0,Gulshan-e-Iqbal Town,Block 13,10,29861.110
92,2.0,Gulshan-e-Iqbal Town,Block 13A,41,14697.240
93,2.0,Gulshan-e-Iqbal Town,Block 13B,24,13463.355
94,2.0,Gulshan-e-Iqbal Town,Block 13C,39,15555.560
95,2.0,Gulshan-e-Iqbal Town,Block 13D2,76,13737.940
96,2.0,Gulshan-e-Iqbal Town,Block 16,23,22159.800
97,2.0,Gulshan-e-Iqbal Town,Block 19,17,32986.110
98,2.0,Gulshan-e-Iqbal Town,Block 7,91,22685.190
99,2.0,Jamshed Town,"Defence Skyline, Shaheed-E-Millat Expressway",12,17768.670
100,2.0,Jamshed Town,Jamshed Road,61,17342.740
101,2.0,Jamshed Town,Karachi Administration Employees Society,46,15772.025
102,2.0,Malir,Airport,45,15432.100
103,2.0,Malir,Falaknaz,118,11574.070
104,2.0,Malir Cantt,Askari 5,626,17222.220
105,2.0,Naya Nazimabad,Block M,23,27777.780
106,2.0,Nazimabad,Nazimabad 1,8,12833.145
107,2.0,Nazimabad,Nazimabad 2,5,15277.780
108,2.0,Nazimabad,Nazimabad 4,22,15323.850
109,2.0,Nazimabad,Nazimabad 5,9,22974.100
110,2.0,North Karachi,New Karachi,10,13385.885
111,2.0,North Karachi,North Karachi Sector 11,80,18904.320
112,2.0,North Karachi,North Karachi Sector 5,49,17361.110
113,2.0,North Karachi,North Karachi Sector 7,38,15879.630
114,2.0,North Nazimabad,Block F,183,18888.890
115,2.0,North Nazimabad,Block M,52,13033.525
116,2.0,Scheme 33,Gulshan-E-Usman Housing Society,12,16435.185
117,2.0,Scheme 33,Gulshan-e-Roomi,43,18518.520
118,2.0,Scheme 33,Saadi Garden,173,16203.700
119,2.0,Scheme 33,Sector 15-A,89,16666.670
120,2.0,Scheme 33,Sector 22-A,18,19166.665
121,2.0,Scheme 33,Sector 29,99,14150.940
122,2.0,Scheme 33,Sector 34-A,123,13386.880
123,2.0,Scheme 33,Sector 47,272,18055.560
124,2.0,Scheme 33,Sector 51-A,52,20717.590
125,2.0,Scheme 33,Sector 52-A,28,19675.925
126,2.0,Scheme 33,Yousaf Goth,11,13425.930
127,2.0,Scheme 33,Zeenatabad,42,21990.740
128,2.0,Shah Faisal,Saima Luxury Belt,33,23148.150
129,2.0,Super Highway,Oasis Park Residencia,6,19444.440
130,2.0,Super Highway,Rabia Enclave,9,10555.560
131,3.0,Clifton,Clifton Block 1,87,19083.970
132,3.0,Clifton,Clifton Block 2,160,23047.635
133,3.0,Clifton,Clifton Block 3,11,23611.110
134,3.0,Clifton,Clifton Block 4,52,20794.365
135,3.0,DHA Defence,Phase 1,65,22222.220
136,3.0,Federal B Area,Block 14,23,35185.190
137,3.0,Federal B Area,Block 15,18,31250.000
138,3.0,Gulistan-e-Jauhar,Askari 4,34,27000.780
139,3.0,Gulistan-e-Jauhar,Block 12,117,23148.150
140,3.0,Gulistan-e-Jauhar,Block 14,152,20000.000
141,3.0,Gulistan-e-Jauhar,Block 15,196,20833.330
142,3.0,Gulistan-e-Jauhar,Block 2,91,23611.110
143,3.0,Gulistan-e-Jauhar,Block 3,57,28935.190
144,3.0,Gulistan-e-Jauhar,Block 4,31,24305.560
145,3.0,Gulistan-e-Jauhar,Block 6,4,8578.080
146,3.0,Gulistan-e-Jauhar,Block 9,14,21180.555
147,3.0,Gulshan-e-Iqbal Town,Block 10A,144,19285.725
148,3.0,Gulshan-e-Iqbal Town,Block 14,16,21669.135
149,3.0,Gulshan-e-Iqbal Town,Block 2,78,22222.220
150,3.0,Gulshan-e-Iqbal Town,Block 4,92,19702.260
151,3.0,Gulshan-e-Iqbal Town,Block 4A,13,25000.000
152,3.0,Gulshan-e-Iqbal Town,Callachi Cooperative Housing Society,302,19519.520
153,3.0,Gulshan-e-Iqbal Town,"Cp Barar Society, Gulshan-E-Iqbal Town",14,25231.965
154,3.0,Gulshan-e-Iqbal Town,Dhoraji Colony,59,23286.760
155,3.0,Gulshan-e-Iqbal Town,Sharfabad,47,23611.110
156,3.0,Jamshed Town,Amil Colony,29,23023.020
157,3.0,Jamshed Town,Cosmopolitan Society,17,25025.030
158,3.0,Jamshed Town,Garden East,34,25483.890
159,3.0,Jamshed Town,Muslimabad Society,12,24451.100
160,3.0,Jamshed Town,Parsi Colony,21,21394.060
161,3.0,Jamshed Town,Soldier Bazar,22,22150.995
162,3.0,Jamshed Town,Tariq Road,39,23286.760
163,3.0,Korangi,Qayyumabad,16,29526.060
164,3.0,Malir,Model Colony,96,24933.860
165,3.0,Malir,Saima Projects,37,25000.000
166,3.0,Naya Nazimabad,Block B,67,29166.670
167,3.0,North Karachi,Buffer Zone,105,25000.000
168,3.0,North Karachi,North Karachi Sector 8,14,23564.815
169,3.0,North Karachi,North Karachi Sector 9,26,25925.930
170,3.0,North Nazimabad,Block B,83,18296.740
171,3.0,North Nazimabad,Block H,131,20287.140
172,3.0,North Nazimabad,Block I,34,24765.510
173,3.0,North Nazimabad,Block J,37,20609.320
174,3.0,North Nazimabad,Block L,120,22927.690
175,3.0,North Nazimabad,Block N,118,22131.845
176,3.0,North Nazimabad,Shadman,48,24537.040
177,3.0,Scheme 33,Meerut Society,57,22222.220
178,3.0,Scheme 33,Punjabi Saudagar Society,156,24537.040
179,3.0,Scheme 33,Sector 17-A,114,25000.000
180,3.0,Scheme 33,Sector 20-A,22,22314.815
181,3.0,Scheme 33,Sector 24-A,22,24120.370
182,3.0,Scheme 33,Sector 35-A,311,22222.220
183,3.0,Scheme 33,Sector 36-A,83,26851.850
184,3.0,Scheme 33,Sector 48-A,13,25925.930
185,4.0,Clifton,Clifton Block 5,35,26276.280
186,4.0,Clifton,Clifton Block 7,40,28570.240
187,4.0,Clifton,Clifton Block 8,89,30030.030
188,4.0,Clifton,Clifton Block 9,94,28115.160
189,4.0,Clifton,Frere Town,43,27777.780
190,4.0,DHA Defence,Phase 2,54,28888.890
191,4.0,DHA Defence,Phase 5,427,25555.560
192,4.0,DHA Defence,Phase 5 Extension,21,28888.890
193,4.0,DHA Defence,Phase 6,914,31111.110
194,4.0,Federal B Area,Block 12,54,28055.555
195,4.0,Federal B Area,Block 6,12,29686.680
196,4.0,Federal B Area,Block 9,19,15000.000
197,4.0,Gulistan-e-Jauhar,Block 5,7,25641.030
198,4.0,Gulshan-e-Iqbal Town,Bahadurabad,121,27924.750
199,4.0,Gulshan-e-Iqbal Town,Block 13D,58,26296.300
200,4.0,Gulshan-e-Iqbal Town,Block 13D1,65,37037.040
201,4.0,Gulshan-e-Iqbal Town,Block 3,39,26620.370
202,4.0,Gulshan-e-Iqbal Town,Block 5,84,32175.925
203,4.0,Gulshan-e-Iqbal Town,Block 6,57,27777.780
204,4.0,Gulshan-e-Iqbal Town,Block 9,17,28571.430
205,4.0,Gulshan-e-Iqbal Town,Gulshan-E-Jamal,13,28888.890
206,4.0,Jamshed Town,Khalid Bin Walid Road,124,27224.570
207,4.0,Jamshed Town,Pechs,284,32384.935
208,4.0,Jamshed Town,Shaheed Millat Road,179,31500.570
209,4.0,Jamshed Town,Shahra-E-Qaideen,14,28584.875
210,4.0,Jamshed Town,Smchs - Sindhi Muslim Society,45,29782.360
211,4.0,Malir,Falcon Complex New Malir,516,26444.440
212,4.0,Malir Cantt,Askari 6,585,24740.740
213,4.0,North Karachi,North Karachi Sector 10,14,30138.890
214,4.0,North Nazimabad,Block A,50,20370.370
215,4.0,North Nazimabad,Block C,12,30555.560
216,4.0,North Nazimabad,Block D,45,20911.360
217,4.0,Shah Faisal,Falcon Complex Faisal,14,76666.670
218,5.0,Clifton,Bath Island,128,32769.060
219,5.0,Clifton,Clifton Block 6,11,32771.540
220,5.0,DHA Defence,Phase 4,168,41666.665
221,5.0,DHA Defence,Phase 7,296,32222.220
222,5.0,DHA Defence,Phase 7 Extension,147,55555.560
223,5.0,DHA Defence,Phase 8,2241,44022.500
224,5.0,DHA Defence,Phase 8 Extension,12,50000.000
225,5.0,Gulshan-e-Iqbal Town,Adamjee Nagar,16,55555.560
226,5.0,Gulshan-e-Iqbal Town,Dawood Society,13,66666.670
227,5.0,Gulshan-e-Iqbal Town,Kda Officers Society,43,88888.890
228,5.0,Gulshan-e-Iqbal Town,Kda Scheme 1,87,40740.740
229,5.0,Gulshan-e-Iqbal Town,Kda Scheme 1 Extension,11,46666.670
230,5.0,Gulshan-e-Iqbal Town,Mohammad Ali Society,18,49000.000
231,5.0,Gulshan-e-Iqbal Town,National Stadium Colony,14,114271.940
232,5.0,Jamshed Town,Amir Khusro,36,51666.665
233,5.0,Jamshed Town,Hill Park,27,44444.440
234,5.0,Karsaz,Navy Housing Scheme Karsaz,131,65873.020
235,5.0,Malir Cantt,Dohs Phase 1,51,32323.230
236,5.0,Malir Cantt,Dohs Phase 2,11,31313.130
237,5.0,Naya Nazimabad,Block A,95,38932.630
238,5.0,Naya Nazimabad,Block C,87,37962.960
239,5.0,Naya Nazimabad,Block D,68,34699.075

In [210]:
df.groupby('sub_location_score')['price'].agg(
    ['count','median','mean']
)

                    count       median          mean
sub_location_score
1.0                  3900   14500000.0  1.961560e+07
2.0                  4141   27000000.0  3.886741e+07
3.0                  3761   35000000.0  4.605948e+07
4.0                  4145   80000000.0  1.098885e+08
5.0                  3711  108200000.0  1.526710e+08

In [211]:
df.drop(columns='luxury_score',inplace=True)

In [212]:
df.sample(100)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,servant_quarter_score,sub_location_score,location_score
1338,Apartment Could Be Your Dream House When You C...,"civil lines, karachi",Civil Lines,NaN,110000000.0,39299.75,2799.0,4,5,0.0,3.0,14.0,2.0,4,0,1,0,2018.0,flat,8.0,Moderately Old,2.0,0,NaN,NaN
7209,Prime Corner Flat | 3rd Floor | Fully Renovate...,"north karachi, karachi",North Karachi,NaN,6500000.0,9759.76,666.0,3,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,NaN,3.0
10941,Houes For Sale,"gulshan-e-iqbal - block 2, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 2,65000000.0,36111.11,1800.0,8,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,3.0,4.0
22755,In The Calm Of Bath Island Stands Sawera Raj N...,"bath island, karachi",Clifton,Bath Island,76500000.0,37117.90,2061.0,3,4,1.0,NaN,20.0,2.0,4,1,1,1,2027.0,flat,-1.0,Under Construction,2.0,1,5.0,5.0
19209,HOUSE FOR SALE,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,100000000.0,22222.22,4500.0,5,5,1.0,NaN,NaN,2.0,0,1,1,1,2023.0,house,3.0,Relatively New,2.0,1,4.0,4.0
9682,120 SQYRDS SLIGHTLY USED House 40 Ft Road Face...,"gulshan-e-maymar - sector q, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,21000000.0,19444.44,1080.0,4,4,2.0,NaN,1.0,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,1.0,2.0
13487,PRIME 500 YARDS BUNGALOW | 1+3 BEDROOMS | EXCE...,"dha phase 5, dha defence",DHA Defence,Phase 5,130000000.0,28888.89,4500.0,4,5,1.0,NaN,1.0,2.0,0,1,1,0,2000.0,house,26.0,Old,2.0,1,4.0,5.0
14797,Defence Phase 5 Heart Of Dha 1000 Yards 5 Bedr...,"dha phase 5, dha defence",DHA Defence,Phase 5,290000000.0,32222.22,9000.0,5,6,2.0,NaN,2.0,4.0,0,2,1,1,2024.0,house,2.0,Relatively New,2.0,2,4.0,5.0
17824,Bungalow Proper 2 Units,"dha phase 6, dha defence",DHA Defence,Phase 6,170000000.0,31481.48,5400.0,6,6,2.0,NaN,NaN,0.0,0,1,0,0,NaN,house,NaN,NaN,0.0,1,4.0,5.0
5834,1800 Square Feet Flat In Only Rs. 35000000,"north nazimabad - block f, north nazimabad",North Nazimabad,Block F,35000000.0,19444.44,1800.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,2.0,4.0
16522,Get In Touch Now To Buy A Flat In HMR Waterfro...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,140000000.0,51851.85,2700.0,4,5,1.0,NaN,40.0,2.0,6,1,1,1,2024.0,flat,2.0,Relatively New,2.0,1,5.0,5.0
12507,Flat Available For Sale On Easy Installments G...,"gulshan-e-maymar, gadap town",Gadap,Gulshan-E-Maymar,15400000.0,11719.94,1314.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,1.0,2.0
18085,120 Square Yards House For sale In Beautiful N...,"naya nazimabad - block d, naya nazimabad",Naya Nazimabad,Block D,37000000.0,34259.26,1080.0,4,4,1.0,NaN,NaN,1.0,0,0,0,1,2026.0,house,0.0,New,1.0,0,5.0,5.0
19930,Brand New 350 Sq Yards Luxury House For Sale I...,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,87000000.0,27619.05,3150.0,4,5,1.0,NaN,2.0,1.0,0,1,1,1,2025.0,house,1.0,Relatively New,1.0,1,4.0,4.0
15313,Rafi Premier Residency Fully Leased 3DD Apartm...,"scheme 33, karachi",Scheme 33,NaN,19500000.0,11168.38,1746.0,3,4,1.0,1.0,13.0,0.0,10,1,1,1,NaN,flat,NaN,NaN,0.0,1,NaN,3.0
5247,2 Bed Lounge Apartment For Sale In Mateen Comp...,"malir, karachi",Malir,NaN,3600000.0,5555.56,648.0,2,2,1.0,NaN,4.0,1.0,1,1,1,1,2022.0,flat,4.0,Relatively New,1.0,1,NaN,4.0
10748,Brand New 120 Sq. yd. Bungalow For Sale,"naya nazimabad - block c, naya nazimabad",Naya Nazimabad,Block C,42500000.0,39351.85,1080.0,4,4,1.0,NaN,2.0,0.0,0,0,1,1,2026.0,house,0.0,New,0.0,0,5.0,5.0
2243,Fully Renovated 3 Bedrooms Apartment For Sale ...,"dha phase 6, dha defence",DHA Defence,Phase 6,29500000.0,24644.95,1197.0,3,3,1.0,2.0,4.0,30.0,1,0,1,0,2011.0,flat,15.0,Old,2.0,0,4.0,5.0
10059,2000 SQ YARDS GROUND PLUS 1 FOR COMMERCIAL USE...,"pechs, jamshed town",Jamshed Town,Pechs,420000000.0,23333.33,18000.0,4,5,2.0,NaN,2.0,5.0,0,4,1,1,2012.0,house,14.0,Old,2.0,2,4.0,4.0
5296,Last Unit Available | Luxury 1 Bed Partial Sea...,"emaar panorama, dha phase 8",DHA Defence,Phase 8,69500000.0,50472.04,1377.0,1,1,1.0,NaN,NaN,1.0,1,0,1,0,NaN,flat,NaN,NaN,1.0,0,5.0,5.0
13466,Samrina Boulevard 2 Bed DD With ROOF,"samrina boulevard, scheme 33",Scheme 33,Sector 19-A,21500000.0,19581.06,1098.0,2,2,1.0,15.0,15.0,1.0,3,0,1,0,2030.0,flat,-4.0,Under Construction,1.0,0,1.0,3.0
9028,Luxury Brand New 4 Bedrooms Apartment On Sale ...,"clifton - block 8, clifton",Clifton,Clifton Block 8,91000000.0,31400.97,2898.0,4,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,4.0,5.0
13745,400 Sq. Yards Prime Location Brand New Lavish ...,"gulshan-e-iqbal - block 5, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 5,157500000.0,43750.00,3600.0,8,6,2.0,NaN,2.0,2.0,0,1,0,1,2026.0,house,0.0,New,2.0,1,4.0,4.0
22065,240 Square Yard Renovated Single Storey House ...,"gulshan-e-maymar - sector t, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,25000000.0,11574.07,2160.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,1.0,2.0
10510,Aesthetic Flat Of 1700 Square Feet For sale Is...,"burj-ul-harmain, university road",University Road,Burj-Ul-Harmain,21400000.0,12580.83,1701.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,NaN,NaN
17679,LEASED BANK LOAN APPLICABLE BRAND NEW FLAT ALS...,"gulzar-e-hijri, scheme 33",Scheme 33,NaN,12500000.0,11384.34,1098.0,2,2,1.0,NaN,NaN,1.0,1,1,1,1,NaN,flat,NaN,NaN,1.0,1,NaN,3.0
18652,Brand New 3Side Corner Apartment 1700sqfts,"scheme 33, karachi",Scheme 33,NaN,20000000.0,11757.79,1701.0,3,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,NaN,3.0
1572,1 Bed Lounge Flat For Sale,"surjani town - sector 7c, surjani town",Gadap,Surjani Town,2200000.0,7407.41,297.0,1,1,1.0,1.0,4.0,1.0,1,2,1,1,2018.0,flat,8.0,Moderately Old,1.0,2,1.0,2.0
9073,350sq yards 4bedrooms luxury villa available f...,"bahria town - precinct 35, bahria sports city",Bahria Town,Bahria Sports City,20500000.0,6507.94,3150.0,4,4,0.0,NaN,NaN,1.0,0,0,1,0,2022.0,house,4.0,Relatively New,1.0,0,1.0,3.0
21643,Prime Location Bahria Homes - Iqbal Villas Hou...,"bahria homes - iqbal villas, bahria town - pre...",Bahria Town,Precinct 2,17500000.0,12792.40,1368.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,2.0,3.0
20998,Saima Pair Flower 3 Bed D D Flat For Sale,"north nazimabad - block f, north nazimabad",North Nazimabad,Block F,49000000.0,27222.22,1800.0,3,3,1.0,NaN,6.0,1.0,1,1,1,0,2023.0,flat,3.0,Relatively New,1.0,1,2.0,4.0
19969,"Luxury Apartment for Sale in Clifton Block 8, ...","clifton - block 8, clifton",Clifton,Clifton Block 8,50000000.0,31210.99,1602.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,4.0,5.0
780,Affordable House Of 350 Square Yards Is Availa...,"navy housing scheme karsaz, karachi",Karsaz,Navy Housing Scheme Karsaz,220000000.0,69841.27,3150.0,5,6,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,5.0,5.0
8619,Get In Touch Now To Buy A 120 Square Yards Hou...,"capital cooperative housing society, scheme 33...",Scheme 33,Sector 35-A,49900000.0,46203.70,1080.0,7,4,2.0,NaN,2.0,3.0,0,1,1,1,2025.0,house,1.0,Relatively New,2.0,1,3.0,3.0
6452,House For Sale,"gulistan-e-jauhar - block 14, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 14,50000000.0,23148.15,2160.0,5,5,0.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,0.0,0,3.0,3.0
8640,Centrally Located Flat In Gulistan-e-Jauhar - ...,"gulistan-e-jauhar - block 17, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 17,7500000.0,6775.07,1107.0,3,3,1.0,NaN,NaN,2.0,4,1,1,1,2030.0,flat,-4.0,Under Construction,2.0,1,1.0,3.0
15627,Flat for sell,"gulistan-e-jauhar - block 13, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 13,9500000.0,10555.56,900.0,2,2,0.0,NaN,NaN,1.0,1,0,1,0,NaN,flat,NaN,NaN,1.0,0,1.0,3.0
8332,Brand New And Fully Renovated 3 Bed Flat Avail...,"shaheed millat road, karachi",Jamshed Town,Shaheed Millat Road,64500000.0,33965.24,1899.0,4,4,1.0,NaN,13.0,1.0,4,0,1,0,2026.0,flat,0.0,New,1.0,0,4.0,4.0
5443,Prominently-Located Prime Location Flat Availa...,"hmr waterfront, dha phase 8",DHA Defence,Phase 8,35000000.0,29239.77,1197.0,1,1,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,5.0,5.0
18911,Bungalow For Sale Ground Plus 1 Block 5 Gulsha...,"gulshan-e-iqbal - block 5, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 5,66000000.0,30555.56,2160.0,5,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,4.0,4.0
8305,3 Rooms Flat | Naya Nazimabad | Peace Apartmen...,"naya nazimabad, karachi",Naya Nazimabad,NaN,17000000.0,16715.83,1017.0,2,2,1.0,12.0,28.0,1.0,4,1,1,1,2031.0,flat,-5.0,Under Construction,1.0,1,NaN,5.0
977,"Leased Corner House 300 Square Yard For Sale, ...","capital cooperative housing society, scheme 33...",Scheme 33,Sector 35-A,60000000.0,22222.22,2700.0,6,7,2.0,NaN,NaN,1.0,0,0,1,0,NaN,house,NaN,NaN,1.0,0,3.0,3.0
5393,Centrally Located West Open House Available In...,"federal b area - block 19, federal b area",Federal B Area,Block 19,41500000.0,32936.51,1260.0,4,4,2.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,2.0,4.0
12652,Apartments For Sale Cosmopolitan Society,"cosmopolitan society, karachi",Jamshed Town,Cosmopolitan Society,65000000.0,24074.07,2700.0,4,4,1.0,NaN,3.0,1.0,1,0,1,0,2026.0,flat,0.0,New,1.0,0,3.0,4.0
8784,Chance Deal Well Maintained 500 Yards House Fo...,"dha phase 6, dha defence",DHA Defence,Phase 6,180000000.0,40000.00,4500.0,4,5,3.0,NaN,2.0,3.0,0,1,1,0,2011.0,house,15.0,Old,2.0,1,4.0,5.0
995,Flat For Sale 3 Rooms In Maymar,"gulshan-e-maymar - sector y, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,6500000.0,8207.07,792.0,2,2,1.0,8.0,11.0,1.0,4,0,1,1,2015.0,flat,11.0,Old,1.0,0,1.0,2.0
22711,3 Bedroom Apartment Available For Sale In Dha ...,"emaar pearl towers, emaar crescent bay",DHA Defence,Phase 8,80000000.0,36579.79,2187.0,3,3,1.0,4.0,4.0,5.0,0,1,1,1,2000.0,flat,26.0,Old,2.0,1,5.0,5.0
2202,1150 Square Feet Flat For Sale Available In Fa...,"falaknaz dynasty, karachi",Scheme 33,Falaknaz,14200000.0,12326.39,1152.0,2,2,2.0,2.0,15.0,1.0,3,1,1,1,2013.0,flat,13.0,Old,1.0,1,1.0,3.0
14152,2 Bed DD Flat For Sale In Abdullah Terrace Gul...,"gulistan-e-jauhar, karachi",Gulistan-e-Jauhar,NaN,13500000.0,13513.51,999.0,2,2,1.0,2.0,NaN,2.0,0,0,0,0,NaN,flat,NaN,NaN,2.0,0,NaN,3.0
2573,Flat for sale,"gulshan-e-iqbal - block 13/c, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13C,26000000.0,16229.71,1602.0,3,3,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,2.0,4.0
5218,West Open 120 Yards Double Storey House For Sale,"zeenatabad, scheme 33",Scheme 33,Zeenatabad,29500000.0,27314.81,1080.0,4,6,1.0,NaN,NaN,1.0,0,1,1,0,2026.0,house,0.0,New,1.0,1,2.0,3.0
12909,300Yards Duplex For Sale In Dha Phase 6,"dha phase 6, dha defence",DHA Defence,Phase 6,95000000.0,35185.19,2700.0,4,4,1.0,NaN,1.0,0.0,0,0,0,0,2018.0,house,8.0,Moderately Old,0.0,0,4.0,5.0
21302,1000 Yards Brand New Owner Built Bungalow For ...,"dha phase 6, dha defence",DHA Defence,Phase 6,650000000.0,72222.22,9000.0,6,6,2.0,NaN,NaN,0.0,0,2,1,0,2026.0,house,0.0,New,0.0,2,4.0,5.0
6731,Get In Touch Now To Buy A Flat In Civil Lines,"civil lines, karachi",Civil Lines,NaN,85000000.0,37037.04,2295.0,3,4,2.0,NaN,22.0,2.0,2,1,1,1,2023.0,flat,3.0,Relatively New,2.0,1,NaN,NaN
12905,RENOVATED 2BEDROOMS APARTMENT FOR SALE,"bukhari commercial area, dha phase 6",DHA Defence,Phase 6,27500000.0,28826.00,954.0,2,2,1.0,3.0,4.0,0.0,0,0,1,0,2010.0,flat,16.0,Old,0.0,0,4.0,5.0
20586,Buy A Flat Of 390 Square Feet In Gulistan-e-Ja...,"gulistan-e-jauhar - block 13, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 13,3900000.0,10077.52,387.0,1,1,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,1.0,3.0
1616,272 Square Yards Luxury Villa Available For Sa...,"bahria town - precinct 8, bahria town karachi",Bahria Town,Precinct 8,28000000.0,11437.91,2448.0,3,3,1.0,NaN,NaN,0.0,0,0,0,1,NaN,house,NaN,NaN,0.0,0,2.0,3.0
18589,Prime Location 500 Square Yards Brand New Hous...,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,107500000.0,23888.89,4500.0,5,5,1.0,NaN,2.0,1.0,0,1,1,1,2024.0,house,2.0,Relatively New,1.0,1,4.0,4.0
4386,Falaknaz Presidency 2 Bed dd West open Flat Le...,"falaknaz presidency, malir",Malir,Falaknaz,13000000.0,11839.71,1098.0,2,2,1.0,NaN,13.0,2.0,2,0,1,1,NaN,flat,NaN,NaN,2.0,0,2.0,4.0
7750,400 Sq. Yards Block 5 Prime Location Double St...,"gulshan-e-iqbal - block 5, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 5,77500000.0,21527.78,3600.0,6,6,1.0,NaN,NaN,1.0,0,1,1,1,2022.0,house,4.0,Relatively New,1.0,1,4.0,4.0
413,Good 2603 Square Feet Flat For sale In Emaar T...,"emaar the views, dha phase 8",DHA Defence,Phase 8,133000000.0,51134.18,2601.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,5.0,5.0
8218,Pak Ideal Society 600 Sq Yd | A-Class Owner Bu...,"pak ideal cooperative housing society, karachi",Gulshan-e-Iqbal Town,NaN,135000000.0,25000.00,5400.0,6,6,2.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN,1.0,1,NaN,4.0
12770,Independent House Double Storey For Sale,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 10A,61500000.0,28472.22,2160.0,6,6,1.0,NaN,NaN,1.0,0,1,1,1,2019.0,house,7.0,Moderately Old,1.0,1,3.0,4.0
5492,3 Bed Dd Apartment For Sale Galaxy Apartments,"dha phase 5, dha defence",DHA Defence,Phase 5,42500000.0,21271.27,1998.0,3,3,0.0,9.0,12.0,0.0,2,0,0,0,NaN,flat,NaN,NaN,0.0,0,4.0,5.0
8893,BRAND NEW BUNGLOW FOR SALE,"dha phase 7, dha defence",DHA Defence,Phase 7,65000000.0,72222.22,900.0,3,4,2.0,NaN,2.0,2.0,0,2,1,1,NaN,house,NaN,NaN,2.0,2,5.0,5.0
4144,7236 Square Feet Flat In Clifton - Block 1 Is ...,"clifton - block 1, clifton",Clifton,Clifton Block 1,180900000.0,25000.00,7236.0,5,5,2.0,1.0,11.0,1.0,2,2,1,1,2021.0,flat,5.0,Relatively New,1.0,2,3.0,5.0
14066,1 Bed Lounge Apartment For Sale | Ready To Mov...,"korangi, karachi",Korangi,NaN,2000000.0,4444.44,450.0,1,1,1.0,NaN,5.0,1.0,1,1,1,1,2022.0,flat,4.0,Relatively New,1.0,1,NaN,1.0
6695,Buying A Prime Location House In Karachi?,"bahria hills, bahria town karachi",Bahria Town,Bahria Hills,55000000.0,12222.22,4500.0,6,6,1.0,NaN,NaN,1.0,0,0,1,0,NaN,house,NaN,NaN,1.0,0,1.0,3.0
15311,House For Buy In Gulistan E Jauhar Block 7. .,"gulistan-e-jauhar - block 7, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 7,31500000.0,29166.67,1080.0,6,6,2.0,NaN,2.0,3.0,0,1,1,1,2024.0,house,2.0,Relatively New,2.0,1,2.0,3.0
4438,Flat In Emaar The Views Sized 1850 Square Feet...,"emaar the views, dha phase 8",DHA Defence,Phase 8,88500000.0,47734.63,1854.0,2,1,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,5.0,5.0
13634,160 Square Yards Spacious House For Sale In Sa...,"saima villas, karachi motorway",Super Highway,Saima Villas,15800000.0,10972.22,1440.0,3,3,2.0,NaN,2.0,2.0,0,2,1,1,2020.0,house,6.0,Moderately Old,2.0,2,1.0,2.0
14562,Direct Owner 240 yards Ground Plus Two House,"scheme 33, karachi",Scheme 33,NaN,49600000.0,22962.96,2160.0,8,6,3.0,NaN,3.0,3.0,0,8,1,1,2005.0,house,21.0,Old,2.0,2,NaN,3.0
7235,Ground Plus 2 House 240 Yard Triple Storey 40f...,government teacher housing society - sector 16...,Scheme 33,Sector 16-A,90000000.0,41666.67,2160.0,6,6,1.0,NaN,1.0,1.0,0,1,1,1,2022.0,house,4.0,Relatively New,1.0,1,1.0,3.0
3911,Leased Flat For Sale With Completion,"gulshan-e-maymar - sector y, gulshan-e-maymar",Gadap,Gulshan-E-Maymar,9000000.0,10638.30,846.0,2,2,1.0,9.0,12.0,1.0,4,1,1,0,2012.0,flat,14.0,Old,1.0,1,1.0,2.0
14421,Saima Elite Villas Corner House Available For ...,"saima elite villas, malir",Malir,Saima Projects,45200000.0,18951.78,2385.0,3,2,1.0,NaN,1.0,1.0,0,0,1,1,2023.0,house,3.0,Relatively New,1.0,0,3.0,4.0
8168,"This Is A 2 Bed DD With 3 Washrooms, Almost Ne...","capital cooperative housing society, scheme 33...",Scheme 33,Sector 35-A,9700000.0,10777.78,900.0,2,3,2.0,NaN,13.0,1.0,6,4,1,1,2025.0,flat,1.0,Relatively New,1.0,2,3.0,3.0
8606,Sadaf Society Sector 15A4 West Open Lease G+1,"sadaf cooperative housing society, gulzar-e-hijri",Scheme 33,Sector 15-A,34000000.0,18888.89,1800.0,6,6,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,2.0,3.0
15266,250 Sq. Yards Block 3 Fully New Renovated Bang...,"gulistan-e-jauhar - block 3, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 3,50000000.0,22222.22,2250.0,4,4,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,3.0,3.0
14873,Quaid Villas 200sq Yard Close To Entrance Of B...,"bahria town - quaid villas, bahria town - prec...",Bahria Town,Precinct 2,22000000.0,12222.22,1800.0,3,3,1.0,NaN,NaN,1.0,0,1,1,0,NaN,house,NaN,NaN,1.0,1,2.0,3.0
17488,Block 3 House Sale 240 Yard,"gulistan-e-jauhar - block 3, gulistan-e-jauhar",Gulistan-e-Jauhar,Block 3,70000000.0,32407.41,2160.0,6,6,0.0,NaN,3.0,1.0,0,0,1,1,2025.0,house,1.0,Relatively New,1.0,0,3.0,3.0
10579,New Brand Flat For Sale In Golden Town,"golden town, malir",Malir,Golden Town,3500000.0,6481.48,540.0,2,2,2.0,NaN,10.0,1.0,2,1,1,1,2024.0,flat,2.0,Relatively New,1.0,1,1.0,4.0
18279,ASKARI-6 Villas ON INSTALMENT,"askari 6, malir cantonment",Malir Cantt,Askari 6,72900000.0,30000.00,2430.0,4,5,0.0,NaN,NaN,1.0,0,0,1,0,NaN,house,NaN,NaN,1.0,0,4.0,5.0
19343,Brand New 240 Single Storey House For Sale,"saadi garden - block 4, saadi garden",Scheme 33,Saadi Garden,28500000.0,13194.44,2160.0,3,5,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,2.0,3.0
14174,Brand New 4 Bed DD With Roof,"gulshan-e-iqbal - block 17, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 17,82500000.0,37568.31,2196.0,4,5,3.0,3.0,4.0,1.0,2,1,1,1,2023.0,flat,3.0,Relatively New,1.0,1,1.0,4.0
16896,Luxury Apartment For Sale 2 Bed DD Bungalow Fa...,"north nazimabad - block h, north nazimabad",North Nazimabad,Block H,22000000.0,22022.02,999.0,2,2,1.0,3.0,16.0,1.0,2,1,1,1,2018.0,flat,8.0,Moderately Old,1.0,1,3.0,4.0
3690,Spacious 3bedrooms Apartment For Sale In High ...,"civil lines, karachi",Civil Lines,NaN,85000000.0,42542.54,1998.0,3,4,1.0,1.0,20.0,2.0,1,1,1,1,2018.0,flat,8.0,Moderately Old,2.0,1,NaN,NaN
20869,Ideal Prime Location 872 Square Feet Flat Has ...,"emaar reef towers, emaar crescent bay",DHA Defence,Phase 8,65000000.0,74455.90,873.0,1,1,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,5.0,5.0
6694,GRAY NOOR TOWERS Scheme 33 Brand New Lease Lux...,"grey noor tower & shopping mall, scheme 33",Scheme 33,Sector 29,15100000.0,13752.28,1098.0,3,3,1.0,6.0,12.0,2.0,2,1,1,1,2021.0,flat,5.0,Relatively New,2.0,1,2.0,3.0
3072,Affordable Flat For sale In Sea View Apartments,"sea view apartments, karachi",DHA Defence,NaN,70000000.0,30381.94,2304.0,3,3,0.0,NaN,NaN,2.0,0,0,1,0,NaN,flat,NaN,NaN,2.0,0,NaN,5.0
19085,FLAT 4 BED LIVING FOR BOOKING,"callachi cooperative housing society, gulshan-...",Gulshan-e-Iqbal Town,Callachi Cooperative Housing Society,35000000.0,16408.81,2133.0,3,3,1.0,NaN,24.0,1.0,7,1,1,1,2028.0,flat,-2.0,Under Construction,1.0,1,3.0,4.0
2306,TULIP TOWER 2 BED DD FLAT FOR SALE,"tulip tower, saadi road",Scheme 33,Saadi Road,15000000.0,13020.83,1152.0,2,2,1.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,1.0,3.0
8990,Invest In Your Future: 2-Bedroom + Lounge Apar...,"jinnah avenue, karachi",Jinnah Avenue,NaN,8400000.0,11244.98,747.0,2,2,1.0,NaN,NaN,1.0,1,0,1,0,NaN,flat,NaN,NaN,1.0,0,NaN,NaN
5280,Prime Location 1100 Square Yards House Availab...,"karsaz, faisal cantonment",Malir Cantt,NaN,400000000.0,40404.04,9900.0,8,6,2.0,NaN,2.0,1.0,0,1,1,1,2024.0,house,2.0,Relatively New,1.0,1,NaN,5.0
5713,FALCON 500 YARDS HOUSE FOR SALE IN TOP LOCATION,"falcon complex new malir, malir",Malir,Falcon Complex New Malir,119000000.0,26444.44,4500.0,5,6,1.0,NaN,3.0,2.0,0,1,1,1,2025.0,house,1.0,Relatively New,2.0,1,4.0,4.0
18546,"3 Bed DD Luxury Flat for Sale in Arif Luxuria,...","gulistan-e-jauhar, karachi",Gulistan-e-Jauhar,NaN,23500000.0,13055.56,1800.0,3,3,0.0,1.0,NaN,1.0,2,0,1,0,NaN,flat,NaN,NaN,1.0,0,NaN,3.0
1359,Flat For Sale 3rd Floor Block K North Nazimabad,"north nazimabad - block k, north nazimabad",North Nazimabad,Block K,7000000.0,8363.20,837.0,2,2,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,1.0,4.0
14367,SEA BREEZE FULLY FURNISHED 02 BEDS+STUDY IN PE...,"emaar crescent bay, dha phase 8",DHA Defence,Phase 8,82000000.0,4461.86,18378.0,2,4,1.0,NaN,25.0,1.0,6,1,1,1,2021.0,flat,5.0,Relatively New,1.0,1,5.0,5.0

In [213]:
df.columns

Index(['property_name', 'address', 'location', 'sub_location', 'price',
       'price_per_sqft', 'area', 'bedrooms', 'bathrooms', 'kitchen', 'floor',
       'total_floors', 'parking', 'elevator', 'servant_quarters',
       'electricity_backup', 'furnished', 'completion_year', 'property_type',
       'property_age', 'age_category', 'parking_score',
       'servant_quarter_score', 'sub_location_score', 'location_score'],
      dtype='object')

In [214]:
df['area_per_bedroom']=df['area']/df['bedrooms']

In [215]:
df.sample(5)

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,servant_quarter_score,sub_location_score,location_score,area_per_bedroom
14574,Prime Location House In Naya Nazimabad For Sale,"naya nazimabad, karachi",Naya Nazimabad,NaN,42500000.0,39351.85,1080.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,NaN,5.0,360.0
2867,1 Bed Lounge Ground Floor Karachi University S...,"karachi university housing society, scheme 33",Scheme 33,Sector 18-A,5500000.0,10912.70,504.0,1,1,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,1.0,3.0,504.0
13359,Brand New Furnished Apartment Available,"defence view phase 1, defence view society",Defence View,NaN,24500000.0,17450.14,1404.0,3,3,1.0,9.0,17.0,1.0,0,2,1,1,2020.0,flat,6.0,Moderately Old,1.0,2,NaN,NaN,468.0
16704,SINGLE STORY HOUSE AVAILABLE FOR SALE,"gulshan-e-iqbal - block 13-d2, gulshan-e-iqbal",Gulshan-e-Iqbal Town,Block 13D2,51500000.0,28611.11,1800.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,2.0,4.0,600.0
20356,House For Sale,"bufferzone - sector 15-a/5, buffer zone",North Karachi,Buffer Zone,45000000.0,20833.33,2160.0,3,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,house,NaN,NaN,0.0,0,3.0,3.0,720.0

In [216]:
df[df['location']=='Cantt']['sub_location'].value_counts()

Series([], Name: count, dtype: int64)

In [217]:
df['sub_location'].isnull().sum()

np.int64(2568)

In [218]:
df['location'].unique()

array(['Scheme 33', 'North Nazimabad', 'Jamshed Town',
       'Gulistan-e-Jauhar', 'DHA Defence', 'Malir Cantt', 'DHA City',
       'Shah Faisal', 'Gadap', 'Naya Nazimabad', 'Gulshan-e-Iqbal Town',
       'Bahria Town', 'Malir', 'Civil Lines', 'Jinnah Avenue', 'Clifton',
       'North Karachi', 'Korangi', 'Nazimabad', 'Federal B Area',
       'Rashid Minhas Road', 'Saddar', 'Super Highway', 'Karsaz',
       'University Road', 'Shahra-e-Faisal', 'Bin Qasim Town',
       'Northern Bypass', 'Tipu Sultan Road', 'Defence View',
       'National Highway', 'Abul Hassan Isphani Road'], dtype=object)

In [219]:
df[df['location']=='Super Highway']['sub_location'].value_counts()

sub_location
Saima Villas             72
Rabia Enclave             9
Oasis Park Residencia     6
Name: count, dtype: int64

In [220]:
df[df['location']=='DHA City'].shape

(58, 26)

In [221]:
df['sub_location'].unique()

array(['Sector 47', 'Block B', 'Block F', 'Pechs', 'Block 13', 'Phase 8',
       'Askari 5', 'Sector 15-A', 'Phase 6', 'Phase 7', 'Block 2', nan,
       'Askari 6', 'Askari 4', 'Saadi Garden', 'Gulshan-E-Maymar',
       'Block N', 'Block 13D', 'Precinct 16', 'Block 10A', 'Precinct 10A',
       'Surjani Town', 'Bahria Paradise', 'Sector 35-A',
       'Jamia Millia Road', 'Phase 4', 'Block K', 'Phase 1', 'Phase 5',
       'Precinct 6', 'Sania Corner', 'Block I', 'Block 4', 'Precinct 11A',
       'Block G', 'Aman Golf View', 'Block 1', 'Block 15',
       'National Stadium Colony', 'Callachi Cooperative Housing Society',
       'Block 13D2', 'Bath Island', 'North Karachi Sector 9',
       'Buffer Zone', 'Sumaira Sky Tower', 'Falcon Complex New Malir',
       'Clifton Block 2', 'Block 7', 'Block 10', 'Block 17', 'Block L',
       'Sector 19-A', 'Falaknaz', 'Block 13D1', 'Shaheed Millat Road',
       'Roomi Residency', 'Precinct 1', 'Block C', 'Meerut Society',
       'Allahwala Town', 'Block 18', 'Phase 2 Extension',
       'Dhoraji Colony', 'Bahadurabad', 'Saima Luxury Belt',
       'Precinct 27', 'Block 13B', 'Saadi Road',
       'Cp Barar Society, Gulshan-E-Iqbal Town', 'Block 19',
       'Sector 52-A', 'Block 14', 'Kda Officers Society', 'Block 6',
       'Lucky One Apartment', 'Sector 16-A', 'Bahria Apartments',
       'North Karachi Sector 7', 'Oasis Park Residencia', 'Phase 2',
       'Block 16', 'Clifton Block 1', 'Block 20', 'Block 5', 'Precinct 4',
       'Navy Housing Scheme Karsaz', 'Kda Scheme 1',
       'North Karachi Sector 5', 'Model Colony', 'Block D', 'Precinct 17',
       'Burj-Ul-Harmain', 'Sector 17-A', 'Precinct 8', 'Clifton Block 4',
       'Saima Royal Residency', 'Sector 34-A', 'Phase 7 Extension',
       'Nazimabad 3', 'Malir Link To Super Highway', 'Sector 29',
       'Adamjee Nagar', 'Sharfabad', 'Block 3A',
       'North Karachi Sector 11', 'Bahria Heights',
       'Smchs - Sindhi Muslim Society', 'Dohs Phase 1', 'Sector 18-A',
       'Frere Town', 'Precinct 11B', 'Shahrah-E-Pakistan',
       'Gulshan-E-Usman Housing Society', 'Punjabi Saudagar Society',
       'Clifton Block 8', 'Memon Goth', 'Block H', 'Sector 51-A',
       'Precinct 10B', 'Korangi Industrial Area', 'Parsi Colony',
       'Kda Overseas Bungalows', 'Precinct 18', 'Block 8', 'Shadman',
       'Block 12', 'Sector 22-A', 'Sector 36-A', 'Saima Jinnah Avenue',
       'Block A', 'Safari Enclave Apartments', 'Zeenatabad',
       'Jamshed Road', 'Garden East', 'Block 3', 'Phase 5 Extension',
       'Shamsi / Al-Falah Belt', 'Mohammad Ali Society', 'Precinct 2',
       'Tariq Road', 'Shahra-E-Qaideen', 'Khalid Bin Walid Road',
       'Kda Scheme 1 Extension', 'Bahria Sports City', 'Block 13A',
       'Saima Projects', 'Private High-Rises', 'Precinct 12',
       'Precinct 9', 'North Karachi Sector 10', 'Block 11',
       'Metropolis Residency', 'Gulshan-e-Roomi', 'Block M', 'Hill Park',
       'Precinct 31', 'Gohar Green City Cluster', 'Block 9',
       'Malir Town Residency', 'Yousaf Goth', 'Sawera Enclave',
       'Block 13D3', 'Clifton Block 6', 'Block 16A', 'Clifton Block 9',
       'Al Madni Heights', 'Defence Skyline, Shaheed-E-Millat Expressway',
       'Falcon Complex Faisal', 'Sector 24-B',
       'Green Town / Rafah-E-Aam Belt', 'Dawood Society', 'Sector 30',
       'Clifton Block 7', 'Mateen Complex', 'Amil Colony',
       'Clifton Block 3', 'Nazimabad 1', 'Block J', 'Bahria Hills',
       'Block 13C', 'Airport', 'Muslimabad Society', 'Gizri',
       'Clifton Block 5', 'Rafi Premier Residency',
       'Cosmopolitan Society', 'Gulzar-E-Hijri', 'Precinct 19',
       'Karachi Administration Employees Society', 'Saima Villas',
       'Mehmoodabad', 'Sector 20-A', 'Golden Town', 'Sector 24-A',
       'Precinct 7', 'Precinct 15', 'Amir Khusro', 'Nazimabad 5',
       'Kda Employees Society', 'Rabia Enclave', 'Gulshan-E-Jamal',
       'Soldier Bazar', 'New Karachi', 'Phase 8 Extension', 'Qayyumabad',
       'Sector 25-B', 'Nazimabad 4', 'Sector 48-A',
       'North Karachi Sector 8', 'Lakhani Presidency', 'Dohs Phase 2',
       'Taloo Gold Residency', 'City Tower And Shopping Mall',
       'Chapal Uptown', 'Block 4A', 'Latifi Cooperative Housing Society',
       'Safoora Goth', 'Nazimabad 2'], dtype=object)

In [222]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Sector 35-A                        311
Sector 47                          272
Saadi Garden                       173
Punjabi Saudagar Society           156
Sector 34-A                        123
Sector 16-A                        118
Sector 18-A                        114
Sector 17-A                        114
Falaknaz                           110
Sector 29                           99
Sector 15-A                         89
Sector 36-A                         83
Meerut Society                      57
Saadi Road                          57
Sector 51-A                         52
Sector 19-A                         47
Gulshan-e-Roomi                     43
Zeenatabad                          42
Sector 52-A                         28
Sawera Enclave                      27
Rafi Premier Residency              26
Sania Corner                        25
Sector 30                           25
Sector 24-A                         22
Sector 20-A                         22
Sector 24-B                         20
Sector 25-B                         19
Sector 22-A                         18
Chapal Uptown                       16
Sumaira Sky Tower                   14
Sector 48-A                         13
Gulshan-E-Usman Housing Society     12
Yousaf Goth                         11
Gulzar-E-Hijri                      10
Taloo Gold Residency                10
Name: count, dtype: int64

In [223]:
df[df['sub_location']=='Gulzar-E-Hijri'][['address','sub_location']]

                                                 address    sub_location
1574            pioneer fountain phase 2, gulzar-e-hijri  Gulzar-E-Hijri
1840                       county garden, gulzar-e-hijri  Gulzar-E-Hijri
5289              grey stylux residences, gulzar-e-hijri  Gulzar-E-Hijri
6228           bilawal shah noorani goth, gulzar-e-hijri  Gulzar-E-Hijri
7933   kehkashan homes, sadaf cooperative housing soc...  Gulzar-E-Hijri
8545                       county garden, gulzar-e-hijri  Gulzar-E-Hijri
11498             grey stylux residences, gulzar-e-hijri  Gulzar-E-Hijri
13953          bilawal shah noorani goth, gulzar-e-hijri  Gulzar-E-Hijri
15620  kehkashan homes, sadaf cooperative housing soc...  Gulzar-E-Hijri
18932           pioneer fountain phase 2, gulzar-e-hijri  Gulzar-E-Hijri

In [224]:
df['sub_location'] = df['sub_location'].replace('Gulzar-E-Hijri', np.nan)

In [225]:
df[df['location']=='Gulistan-e-Jauhar']['sub_location'].value_counts()

sub_location
Block 15                              196
Block 14                              152
Block 13                              132
Block 18                              132
Block 7                               122
Block 3A                              119
Block 12                              117
Block 17                              114
Block 2                                91
Block 19                               74
Block 16                               71
Block 3                                57
Block 1                                39
Block 10                               39
Askari 4                               34
Block 11                               33
Block 4                                31
Block 20                               25
Block 9                                14
Block 16A                              14
Block 8                                12
Latifi Cooperative Housing Society      8
Safoora Goth                            8
Kda Overseas Bungalows                  7
Block 5                                 7
Block 6                                 4
Name: count, dtype: int64

In [226]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Callachi Cooperative Housing Society      302
Block 1                                   194
Block 10A                                 144
Bahadurabad                               121
Block 4                                    92
Block 7                                    91
Kda Scheme 1                               87
Block 5                                    84
Block 2                                    78
Block 13D2                                 76
Block 13D1                                 65
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 17                                   44
Kda Officers Society                       43
Block 13A                                  41
Block 13C                                  39
Block 3                                    39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  24
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Block 14                                   16
Adamjee Nagar                              16
National Stadium Colony                    14
Cp Barar Society, Gulshan-E-Iqbal Town     14
Dawood Society                             13
Gulshan-E-Jamal                            13
Block 4A                                   13
Kda Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [227]:
df['location'].value_counts()

location
DHA Defence                 4473
Scheme 33                   2834
Gulshan-e-Iqbal Town        2305
Gulistan-e-Jauhar           1828
Bahria Town                 1757
Malir Cantt                 1382
North Nazimabad             1077
Jamshed Town                1030
Malir                        997
Clifton                      831
Naya Nazimabad               809
Gadap                        796
Federal B Area               428
North Karachi                409
University Road              345
Jinnah Avenue                247
Korangi                      174
Shah Faisal                  164
Karsaz                       131
Super Highway                115
Saddar                        90
Civil Lines                   86
Rashid Minhas Road            83
Nazimabad                     74
DHA City                      58
Bin Qasim Town                57
Defence View                  47
Shahra-e-Faisal               46
Tipu Sultan Road              32
Northern Bypass               31
Abul Hassan Isphani Road      18
National Highway               5
Name: count, dtype: int64

In [228]:
df[df['location']=='Jinnah Avenue']['sub_location'].value_counts()

sub_location
Metropolis Residency    112
Aman Golf View           38
Roomi Residency          33
Name: count, dtype: int64

In [229]:
df[df['location']=='Jinnah Avenue']['sub_location'].value_counts()

sub_location
Metropolis Residency    112
Aman Golf View           38
Roomi Residency          33
Name: count, dtype: int64

In [230]:
df[df['location']=='Gulistan-e-Jauhar']['sub_location'].value_counts()

sub_location
Block 15                              196
Block 14                              152
Block 13                              132
Block 18                              132
Block 7                               122
Block 3A                              119
Block 12                              117
Block 17                              114
Block 2                                91
Block 19                               74
Block 16                               71
Block 3                                57
Block 1                                39
Block 10                               39
Askari 4                               34
Block 11                               33
Block 4                                31
Block 20                               25
Block 9                                14
Block 16A                              14
Block 8                                12
Latifi Cooperative Housing Society      8
Safoora Goth                            8
Kda Overseas Bungalows                  7
Block 5                                 7
Block 6                                 4
Name: count, dtype: int64

In [231]:
df['location'].value_counts()

location
DHA Defence                 4473
Scheme 33                   2834
Gulshan-e-Iqbal Town        2305
Gulistan-e-Jauhar           1828
Bahria Town                 1757
Malir Cantt                 1382
North Nazimabad             1077
Jamshed Town                1030
Malir                        997
Clifton                      831
Naya Nazimabad               809
Gadap                        796
Federal B Area               428
North Karachi                409
University Road              345
Jinnah Avenue                247
Korangi                      174
Shah Faisal                  164
Karsaz                       131
Super Highway                115
Saddar                        90
Civil Lines                   86
Rashid Minhas Road            83
Nazimabad                     74
DHA City                      58
Bin Qasim Town                57
Defence View                  47
Shahra-e-Faisal               46
Tipu Sultan Road              32
Northern Bypass               31
Abul Hassan Isphani Road      18
National Highway               5
Name: count, dtype: int64

In [232]:
df[df['location']=='Federal B Area']['sub_location'].value_counts()

sub_location
Block 10              75
Block 12              54
Block 13              41
Block 11              29
Block 14              23
Block 9               19
Block 16              19
Block 15              18
Block 8               18
Block 19              17
Block 6               12
Block 7               11
Shahrah-E-Pakistan    10
Block 20              10
Name: count, dtype: int64

In [233]:
# This section handles Lucky One Apartment.mask = (
    (df["location"] == "Rashid Minhas Road") &
    (df["sub_location"] == "Lucky One Apartment")
)
df.loc[mask, ["location", "sub_location"]] = [
    "F.B. Area",
    "Block 21"
]

# This section handles Saima Royal Residency.mask = (
    (df["location"] == "Rashid Minhas Road") &
    (df["sub_location"] == "Saima Royal Residency")
)
df.loc[mask, ["location", "sub_location"]] = [
    "Gulshan-e-Iqbal",
    "Block 2"
]

# This section handles Lakhani Presidency.mask = (
    (df["location"] == "Rashid Minhas Road") &
    (df["sub_location"] == "Lakhani Presidency")
)
df.loc[mask, ["location", "sub_location"]] = [
    "Gulshan-e-Iqbal",
    "Callachi Cooperative Housing Society"
]

In [234]:
df[df['location']=='Jinnah Avenue']['sub_location'].value_counts()

sub_location
Metropolis Residency    112
Aman Golf View           38
Roomi Residency          33
Name: count, dtype: int64

In [235]:
df[df['location']=='Jinnah Avenue']['property_name'].value_counts()

property_name
Brand New Flat For Sale                                                                                                                                               5
FLAT FOR SALE                                                                                                                                                         5
Metropolis Residency 3 Bed DD Apartment For Sale (Brand New)                                                                                                          4
Prime Apartments For Sale Jinnah Avenue, Malir Cantt                                                                                                                  4
Bank Loan Applicable 3 Bed DD Flat Available For Sale                                                                                                                 4
Brend new Flat For Sale at Metropolis Chance Deal                                                                                                                     3
3 Bed D/D Brand New Luxurious Apartment Available For Sale At Prime Location Of The City                                                                              3
Apparment For Sale                                                                                                                                                    3
4 Bed Duplex Flat Available For Sale Bank Loan Applicable                                                                                                             2
METROPOLIS LUXURY 3 BED FLAT FOR SELL                                                                                                                                 2
Brand New 3 BED DD Apartment Available For Sale                                                                                                                       2
AMAN GOLF VIEW 3 BED DD FLAT AVAILABLE FOR SALE                                                                                                                       2
2 Bed DD Apartment Available For Sale In Saima Pari Avenue                                                                                                            2
Bank Loan Applicable 4 Bed Duplex Semi Furnished Apartment Available For Sale                                                                                         2
Roomi Residency Jinnah Avenue                                                                                                                                         2
Brand New Flat For Sale At Metropolis Chance Deal                                                                                                                     2
Become Owner Of Your Flat Today Which Is Centrally Located In Metropolis Residency In Karachi                                                                         2
FLAT AVAILABLE FOR SELL CANT VIEW LODGE MAIN JINNAH AVENUE                                                                                                            1
2200 Square Feet Flat Up For sale In Jinnah Avenue                                                                                                                    1
RUMI RESIDENCY 3 BED DD FLAT AVAILABLE FOR SALE                                                                                                                       1
4 Beds Apartments Airport Residency                                                                                                                                   1
3 BED DD LUXURIOUS FLAT AVAILABLE IN METROPOLIS FOR SALE                                                                                                              1
FLAT IS AVAILABLE FOR SALE                                                                                                                                            1
Metropolis Residency 3 Bed DD Flat Available For Sale Bank Loan Applicable                                                                                            1
4 Bed Dd With Servant Quarter & Rooftop Available For Sale                                                                                                            1
Prime Location Flat For Sale In Karachi                                                                                                                               1
3 Bed DD In Newly Build Project Flat For Sale                                                                                                                         1
Metropolis Residency                                                                                                                                                  1
BURJ AL JINNAH PEARL APARTMENT | 1,765 SQ FT | MAIN JINNAH AVENUE, KARACHI                                                                                            1
3 Bed Dd West Open Corner Airport Facing Bank Loan Applicable Flat For Sale                                                                                           1
New Brand Flat For Sale Meter Police                                                                                                                                  1
1900 Square Feet Spacious Flat Available In Metropolis Residency For Sale                                                                                             1
Metropolis Residency Duplex For Sale                                                                                                                                  1
Roomi Residency | Loan Applicable | 2 Bed DD Apartment For Sale | 1,050 Sq. Ft. |                                                                                     1
Apparment For Sale at roomj Residency Bank Loan Applicable                                                                                                            1
Opportunity Of Investment Flat Is For Sale                                                                                                                            1
Book Prime Location Flat Today In Jinnah Avenue                                                                                                                       1
Flat Available For Sale Cant View Lodges Main Jinnah Avenue                                                                                                           1
Main Road Facing Jinnah Avenue 5 Room Kings Js Tower First Come First Buying Investor Rate Grand Launching On 23rd November 2025 Prices Will Increase After Launch    1
Super Luxury 2 Bed Dd Apartment For Sale  Both Locations Available                                                                                                    1
ROOMI ICON BOOKING FLAT FOR SALE                                                                                                                                      1
Brend New Flat For Sale At Metropolis                                                                                                                                 1
Metropolis Residency 3 Bed Dd For Sale                                                                                                                                1
Aman Golf View Flat Sized 1800 Square Feet                                                                                                                            1
Metropolis Residency 4 Bed D/D Duplex Available For Sale                                                                                                              1
Apartment For Sale at Metropolis Residency                                                                                                                            1
Spacious Prime Location 1600 Square Feet Flat Available For Sale In Roomi Residency                                                                                   1
FLAT FOR SALE METROPOLIS RESIDENCY                                                                                                                                    1
Metropolis Residency Flats For Sale                                                                                                                                   1
FLAT FOR SALE METROPOLIS RESIDENCY MAIN JINNAH AVENUE NEAR MALIR CAN'T CHECK POST 6                                                                                   1
4 Bed Semi Furnished Chance Deal 2600 SQ FT Burj Al Jinnah                                                                                                            1
3 Bed Apartment For Sale Ibrahim Heaven, Jinnah Avenue.                                                                                                               1
Brand New Flat For Sale In Metropolis                                                                                                                                 1
ULTRA -LUXURY 3 BED D. D APARTMENT WITH GYM, POOL & HOUSEKEEPING INCLUDED IN BURJ AL JINNAH MAIN JINNAH AVENUE MALIR CANTT KARACHI                                    1
Luxurious 3-Bedroom D Apartments For Sale!                                                                                                                            1
Luxury Apartments For Sale                                                                                                                                            1
PRIME LOCATION 2691 SQUARE FEET SERVICE APARTMENT FOR SALE IN BURJ AL JINNAH MAIN JINNAH AVENUE INFRONT OF MALIR CANTT                                                1
Metropolis Residency Duplex For Sale 4 Bed DD                                                                                                                         1
Spacious 3 Bedroom Lounge Apartment Available On Installment Near Falcon Society Malir Cantt Karachi                                                                  1
Prime Location 1950 Square Feet Flat Available For Sale In Metropolis Residency If You Hurry                                                                          1
In Metropolis Residency 2200 Square Feet Flat For Sale                                                                                                                1
Aman Golf view 3 bed dd flat for sale                                                                                                                                 1
Centrally Located House In Jinnah Avenue Is Available For sale                                                                                                        1
3 Bed Dd Flat For Sale At Metropolis Residency                                                                                                                        1
4 Bed DD Duplex Apartment Available For Sale In Metropolis Residency                                                                                                  1
Brand New 3 Bed DD Luxury Apartment For Sale                                                                                                                          1
Buy Prime Location 1500 Square Feet Flat At Highly Affordable Price                                                                                                   1
1600 Square Feet Flat For Sale In Jinnah Avenue                                                                                                                       1
3 Bed DD Semi Furnished Flats For Sale Ready To Move Main Jinnah Avenue Road                                                                                          1
Semi Furnished Apartment Available For Sale  Bank Loan Applicable                                                                                                     1
Brend New Flat For Sale At Metropolis Chance Deal                                                                                                                     1
Serviced Apartments Near Airport | High ROI | Burj Al Jinnah Karachi                                                                                                  1
Highly-Desirable Flat Available In Metropolis Residency For sale                                                                                                      1
Duplex 4 Bed DD Flat For Sale                                                                                                                                         1
Exclusive Luxury Apartments For Sale A New Standard Of Elegance And Comfort In The Heart Of The City                                                                  1
Flat Of 1900 Square Feet Is Available In Contemporary Neighborhood Of Jinnah Avenue                                                                                   1
2 BED DD BRAND NEW FOR SALE                                                                                                                                           1
Apartment For Sale In Burj Al Jinnah                                                                                                                                  1
3 Bed Luxurious Apartment Available For Sale                                                                                                                          1
Brend new Duplex 4 bed dd For Sale Chance Deal                                                                                                                        1
Bank Loan Applicable 4 Bed DD Flat Available For Sale                                                                                                                 1
METROPOLIS RESIDENCY FULL FURNISHED                                                                                                                                   1
03 Bed DD Flat For Sale In Saima Paari Avenue                                                                                                                         1
Aparment For Sale                                                                                                                                                     1
Brand New Luxurious Apartment Available For Sale Internationally Architecture Design State Of Art Amenities                                                           1
Flat Of 1500 Square Feet Is Available For Sale                                                                                                                        1
Duplex Flat for sale 4 bedrooms                                                                                                                                       1
4 Bed DD Available For Sell Bank Loan Facility Available                                                                                                              1
3 Bed DD Luxury Apartment For Sale Main Jinnah Avenue                                                                                                                 1
Brand New Duplex For Sale at Metropolis Chance Deal                                                                                                                   1
METROPOLIS SIGNATURE YEAR INSTALMENT PLAN FLAT FOR SALE                                                                                                               1
Aman Golf view 4 bed dd with maid room                                                                                                                                1
BURJ AL JINNAH PEARL APARTMENT 1,765 SQUARE FEET MAIN JINNAH AVENUE, KARACHI                                                                                          1
FLAT AVAILABLE FOR SELL CANT VIEW LODGES MAIN JINNAH AVENUE                                                                                                           1
3 Bed DD 2000 Square Feet Net Area Apartment For Sale                                                                                                                 1
Luxurious 2 Bed DD Apartment With Runway View For Sale | Aman Golf | Jinnah Avenue Near Malir Cantt                                                                   1
Centrally Located Flat In Jinnah Avenue Is Available For Sale                                                                                                         1
Metropolis Residency 4 Bed DD Duplex 3000 Square Feet Flat Available For Sell Bank Loan Applicable                                                                    1
End Your Search For Flat Here And sale Now                                                                                                                            1
Metropolis Residency Flat For Sale                                                                                                                                    1
One Of The Master Piece On The Prime Location Of Jinnah Avenue                                                                                                        1
Roomi Residency 3 bed DD Apartment                                                                                                                                    1
3 Bed DD Semi Furnished Flats For Sale Main Jinnah Avenue Road Malir Cantt                                                                                            1
KINGS NADIR TOWER, 3Bed room premium apartments opposite Check post # 6, Malir cantt karachi.                                                                         1
3 Bed DD Semi Furnished Ready Flat For Sale Jinnah Avenue Karachi                                                                                                     1
Duplex For Sale 4 Bed Dd At Metropolis Residency                                                                                                                      1
Ideal Duplex At Prime Location Of Jinnah Avenue Near Malir Cantt Check Post No 6 Karachi Available For Rs. 40000000                                                   1
Luxury 4-Bedroom Apartment | Grey Crest Tower                                                                                                                         1
Metropolis Residency Duplex For Sale 6 Rooms                                                                                                                          1
Fatima Golf Residency Duplex                                                                                                                                          1
Brand New Duplex For Sale At Metropolis Chance Deal                                                                                                                   1
Apartment For Sale 3 Bed Dd Metropolis Residency                                                                                                                      1
2 Bed dd Semi Furnished Available for Sale                                                                                                                            1
FLAT URGENT SALE CHANCE DEAL                                                                                                                                          1
Duplex 4 Bed Dd At Metropolis Residency Flat For Sale                                                                                                                 1
Brand New Semi-Furnished 4 Bed DD Duplex Available For Sale Metropolis Residency (Jinnah Avenue)  Luxury Living In A Modern High-Rise Community                       1
4 Bed Apartment For Sale In Saima Paari Avenue                                                                                                                        1
Prime Location Flat Of 950 Square Feet Available In Jinnah Avenue                                                                                                     1

In [236]:
mapping = [
    "Aman Golf View",
    "Roomi Residency",
    "Metropolis Residency"
]

mask = (
    (df["location"] == "Jinnah Avenue") &
    (df["sub_location"].isin(mapping))
)

df.loc[mask, "location"] = "Scheme 33"
df.loc[mask, "sub_location"] = "Sector 40"

In [237]:
df['sub_location'].value_counts()

sub_location
Phase 8                                         2241
Phase 6                                          914
Askari 5                                         626
Askari 6                                         585
Falcon Complex New Malir                         516
Gulshan-E-Maymar                                 468
Phase 5                                          427
Sector 35-A                                      311
Callachi Cooperative Housing Society             310
Phase 7                                          296
Pechs                                            284
Surjani Town                                     273
Sector 47                                        272
Block 1                                          233
Falaknaz                                         228
Block 7                                          224
Block 15                                         214
Block 2                                          201
Block 14                                         191
Block F                                          183
Sector 40                                        183
Block 13                                         183
Shaheed Millat Road                              179
Saadi Garden                                     173
Block 12                                         171
Phase 4                                          168
Clifton Block 2                                  160
Block 17                                         158
Punjabi Saudagar Society                         156
Block B                                          150
Phase 7 Extension                                147
Precinct 2                                       145
Block A                                          145
Block 10A                                        144
Burj-Ul-Harmain                                  143
Block 10                                         135
Block 18                                         132
Navy Housing Scheme Karsaz                       131
Block H                                          131
Precinct 12                                      130
Bath Island                                      128
Bahria Sports City                               128
Khalid Bin Walid Road                            124
Block 4                                          123
Sector 34-A                                      123
Bahadurabad                                      121
Bahria Apartments                                120
Block L                                          120
Block 3A                                         119
Sector 16-A                                      118
Block N                                          118
Sector 18-A                                      114
Sector 17-A                                      114
Block D                                          113
Block 16                                         113
Allahwala Town                                   113
Block 19                                         108
Buffer Zone                                      105
Block C                                           99
Sector 29                                         99
Model Colony                                      96
Block 3                                           96
Block 11                                          96
Precinct 8                                        94
Clifton Block 9                                   94
Private High-Rises                                92
Precinct 10A                                      92
Block 5                                           91
Sector 15-A                                       89
Clifton Block 8                                   89
Kda Scheme 1                                      87
Clifton Block 1                                   87
Precinct 11A                                      85
Precinct 31                                       84
Sector 36-A                                       83
Malir Link To Super Highway                       82
North Karachi Sector 11                           80
Bahria Paradise                                   76
Block 13D2                                        76
Block M                                           75
Precinct 11B                                      74
Block 6                                           73
Saima Villas                                      72
Precinct 1                                        70
Phase 2 Extension                                 69
Precinct 10B                                      68
Block 13D1                                        65
Phase 1                                           65
Precinct 6                                        63
Jamshed Road                                      61
Precinct 27                                       61
Dhoraji Colony                                    59
Block 13D                                         58
Bahria Heights                                    57
Saadi Road                                        57
Meerut Society                                    57
Memon Goth                                        55
Bahria Hills                                      54
Phase 2                                           54
Sector 51-A                                       52
Clifton Block 4                                   52
Dohs Phase 1                                      51
Block K                                           51
Saima Jinnah Avenue                               50
Block 9                                           50
North Karachi Sector 5                            49
Precinct 4                                        49
Shadman                                           48
Sharfabad                                         47
Sector 19-A                                       47
Karachi Administration Employees Society          46
Airport                                           45
Smchs - Sindhi Muslim Society                     45
Gulshan-e-Roomi                                   43
Frere Town                                        43
Kda Officers Society                              43
Zeenatabad                                        42
Gohar Green City Cluster                          42
Block 21                                          41
Al Madni Heights                                  41
Block 13A                                         41
Clifton Block 7                                   40
Block 13C                                         39
Tariq Road                                        39
North Karachi Sector 7                            38
Precinct 16                                       37
Block J                                           37
Saima Projects                                    37
Amir Khusro                                       36
Clifton Block 5                                   35
Block 20                                          35
Precinct 19                                       34
Askari 4                                          34
Garden East                                       34
Block I                                           34
Mateen Complex                                    34
Saima Luxury Belt                                 33
Block G                                           32
Block 13D3                                        32
Block 8                                           30
Amil Colony                                       29
Sector 52-A                                       28
Shamsi / Al-Falah Belt                            27
Sawera Enclave                                    27
Hill Park                                         27
North Karachi Sector 9                            26
Rafi Premier Residency                            26
Precinct 17                                       26
Sania Corner                                      25
Sector 30                                         25
Block 13B                                         24
Green Town / Rafah-E-Aam Belt                     24
Korangi Industrial Area                           23
Soldier Bazar                                     22
Sector 20-A                                       22
Sector 24-A                                       22
Precinct 15                                       22
Nazimabad 4                                       22
Phase 5 Extension                                 21
Parsi Colony                                      21
Gizri                                             21
Sector 24-B                                       20
Nazimabad 3                                       20
Jamia Millia Road                                 20
Mehmoodabad                                       19
Sector 25-B                                       19
Sector 22-A                                       18
Mohammad Ali Society                              18
Safari Enclave Apartments                         18
City Tower And Shopping Mall                      17
Cosmopolitan Society                              17
Chapal Uptown                                     16
Adamjee Nagar                                     16
Kda Employees Society                             16
Golden Town                                       16
Qayyumabad                                        16
Precinct 7                                        14
North Karachi Sector 8                            14
Shahra-E-Qaideen                                  14
Cp Barar Society, Gulshan-E-Iqbal Town            14
North Karachi Sector 10                           14
Sumaira Sky Tower                                 14
National Stadium Colony                           14
Block 16A                                         14
Falcon Complex Faisal                             14
Gulshan-E-Jamal                                   13
Sector 48-A                                       13
Dawood Society                                    13
Block 4A                                          13
Malir Town Residency                              13
Phase 8 Extension                                 12
Gulshan-E-Usman Housing Society                   12
Defence Skyline, Shaheed-E-Millat Expressway      12
Muslimabad Society                                12
Kda Scheme 1 Extension                            11
Dohs Phase 2                                      11
Clifton Block 3                                   11
Clifton Block 6                                   11
Yousaf Goth                                       11
Precinct 9                                        11
Shahrah-E-Pakistan                                10
Taloo Gold Residency                              10
New Karachi                                       10
Nazimabad 5                                        9
Rabia Enclave                                      9
Nazimabad 1                                        8
Latifi Cooperative Housing Society                 8
Safoora Goth                                       8
Kda Overseas Bungalows                             7
Oasis Park Residencia                              6
Precinct 18                                        5
Nazimabad 2                                        5
Name: count, dtype: int64

In [238]:
# This section handles Convert To Lowercase.df["property_name_lower"] = df["property_name"].str.lower()

# This section handles Project Patterns.patterns = {
    "metropolis residency": "Metropolis Residency",
    "metropolis signature": "Metropolis Signature",
    "burj al jinnah": "Burj Al Jinnah",
    "burj-ul-harmain": "Burj-Ul-Harmain",
    "burj ul harmain": "Burj-Ul-Harmain",
    "grey crest tower": "Grey Crest Tower",
    "airport residency": "Airport Residency",
    "ibrahim heaven": "Ibrahim Heaven",
    "cant view lodges": "Cant View Lodges",
    "cant view lodge": "Cant View Lodges",
    "gohar golf vista": "Gohar Golf Vista",
    "fatima golf residency": "Fatima Golf Residency",
    "saima pari avenue": "Saima Pari Avenue",
    "saima paari avenue": "Saima Pari Avenue",
    "roomi icon": "Roomi Icon",
    "roomi tower": "Roomi Tower",
    "kings js tower": "Kings JS Tower",
    "kings nadir tower": "Kings Nadir Tower",
    "falcon society": "Falcon Society",
    "falaknaz harmony": "Falaknaz Harmony"
}

# Extract project name into sub_location
for pattern, project in patterns.items():
    mask = (
        (df["location"] == "Jinnah Avenue") &
        (df["sub_location"].isna()) &
        (df["property_name_lower"].str.contains(pattern, na=False))
    )

    df.loc[mask, "sub_location"] = project

# Optional: remove helper column
df.drop(columns="property_name_lower", inplace=True)

In [239]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Precinct 2                                       145
                      Precinct 12                                      130
                      Bahria Sports City                               128
                      Bahria Apartments                                120
                      Precinct 8                                        94
                      Precinct 10A                                      92
                      Private High-Rises                                92
                      Precinct 11A                                      85
                      Precinct 31                                       84
                      Bahria Paradise                                   76
                      Precinct 11B                                      74
                      Precinct 1                                        70
                      Precinct 10B                                      68
                      Precinct 6                                        63
                      Precinct 27                                       61
                      Bahria Heights                                    57
                      Bahria Hills                                      54
                      Precinct 4                                        49
                      Precinct 16                                       37
                      Precinct 19                                       34
                      Precinct 17                                       26
                      Precinct 15                                       22
                      Precinct 7                                        14
                      Precinct 9                                        11
                      Precinct 18                                        5
Bin Qasim Town        Mateen Complex                                    34
Clifton               Clifton Block 2                                  160
                      Bath Island                                      128
                      Clifton Block 9                                   94
                      Clifton Block 8                                   89
                      Clifton Block 1                                   87
                      Clifton Block 4                                   52
                      Frere Town                                        43
                      Clifton Block 7                                   40
                      Clifton Block 5                                   35
                      Gizri                                             21
                      Clifton Block 3                                   11
                      Clifton Block 6                                   11
DHA Defence           Phase 8                                         2241
                      Phase 6                                          914
                      Phase 5                                          427
                      Phase 7                                          296
                      Phase 4                                          168
                      Phase 7 Extension                                147
                      Phase 2 Extension                                 69
                      Phase 1                                           65
                      Phase 2                                           54
                      Phase 5 Extension                                 21
                      Phase 8 Extension                                 12
F.B. Area             Block 21                                          41
Federal B Area        Block 10                                          75
                      Block 12                                          54
                      Block 13                                          41
                      Block 11                                          29
                      Block 14                                          23
                      Block 16                                          19
                      Block 9                                           19
                      Block 15                                          18
                      Block 8                                           18
                      Block 19                                          17
                      Block 6                                           12
                      Block 7                                           11
                      Block 20                                          10
                      Shahrah-E-Pakistan                                10
Gadap                 Gulshan-E-Maymar                                 468
                      Surjani Town                                     273
                      Memon Goth                                        55
Gulistan-e-Jauhar     Block 15                                         196
                      Block 14                                         152
                      Block 13                                         132
                      Block 18                                         132
                      Block 7                                          122
                      Block 3A                                         119
                      Block 12                                         117
                      Block 17                                         114
                      Block 2                                           91
                      Block 19                                          74
                      Block 16                                          71
                      Block 3                                           57
                      Block 1                                           39
                      Block 10                                          39
                      Askari 4                                          34
                      Block 11                                          33
                      Block 4                                           31
                      Block 20                                          25
                      Block 16A                                         14
                      Block 9                                           14
                      Block 8                                           12
                      Latifi Cooperative Housing Society                 8
                      Safoora Goth                                       8
                      Block 5                                            7
                      Kda Overseas Bungalows                             7
                      Block 6                                            4
Gulshan-e-Iqbal       Block 2                                           32
                      Callachi Cooperative Housing Society               8
Gulshan-e-Iqbal Town  Callachi Cooperative Housing Society             302
                      Block 1                                          194
                      Block 10A                                        144
                      Bahadurabad                                      121
                      Block 4                                           92
                      Block 7                                           91
                      Kda Scheme 1                                      87
                      Block 5                                           84
                      Block 2                                           78
                      Block 13D2                                        76
                      Block 13D1                                        65
                      Dhoraji Colony                                    59
                      Block 13D                                         58
                      Block 6                                           57
                      Sharfabad                                         47
                      Block 17                                          44
                      Kda Officers Society                              43
                      Block 13A                                         41
                      Block 13C                                         39
                      Block 3                                           39
                      Block 11                                          34
                      Block 13D3                                        32
                      Block 13B                                         24
                      Block 16                                          23
                      Block 10                                          21
                      Mohammad Ali Society                              18
                      Block 19                                          17
                      Block 9                                           17
                      Adamjee Nagar                                     16
                      Block 14                                          16
                      Cp Barar Society, Gulshan-E-Iqbal Town            14
                      National Stadium Colony                           14
                      Block 4A                                          13
                      Dawood Society                                    13
                      Gulshan-E-Jamal                                   13
                      Kda Scheme 1 Extension                            11
                      Block 13                                          10
Jamshed Town          Pechs                                            284
                      Shaheed Millat Road                              179
                      Khalid Bin Walid Road                            124
                      Jamshed Road                                      61
                      Karachi Administration Employees Society          46
                      Smchs - Sindhi Muslim Society                     45
                      Tariq Road                                        39
                      Amir Khusro                                       36
                      Garden East                                       34
                      Amil Colony                                       29
                      Hill Park                                         27
                      Soldier Bazar                                     22
                      Parsi Colony                                      21
                      Mehmoodabad                                       19
                      Cosmopolitan Society                              17
                      Shahra-E-Qaideen                                  14
                      Defence Skyline, Shaheed-E-Millat Expressway      12
                      Muslimabad Society                                12
Jinnah Avenue         Metropolis Residency                               6
                      Burj Al Jinnah                                     5
                      Cant View Lodges                                   5
                      Saima Pari Avenue                                  4
                      Grey Crest Tower                                   2
                      Ibrahim Heaven                                     2
                      Airport Residency                                  1
                      Burj-Ul-Harmain                                    1
                      Falaknaz Harmony                                   1
                      Falcon Society                                     1
                      Fatima Golf Residency                              1
                      Gohar Golf Vista                                   1
                      Kings JS Tower                                     1
                      Kings Nadir Tower                                  1
                      Metropolis Signature                               1
                      Roomi Icon                                         1
                      Roomi Tower                                        1
Karsaz                Navy Housing Scheme Karsaz                       131
Korangi               Allahwala Town                                   113
                      Korangi Industrial Area                           23
                      Kda Employees Society                             16
                      Qayyumabad                                        16
Malir                 Falcon Complex New Malir                         516
                      Falaknaz                                         118
                      Model Colony                                      96
                      Malir Link To Super Highway                       82
                      Airport                                           45
                      Saima Projects                                    37
                      Jamia Millia Road                                 20
                      Golden Town                                       16
                      Malir Town Residency                              13
Malir Cantt           Askari 5                                         626
                      Askari 6                                         585
                      Dohs Phase 1                                      51
                      Dohs Phase 2                                      11
Naya Nazimabad        Block A                                           95
                      Block C                                           87
                      Block D                                           68
                      Block B                                           67
                      Block M                                           23
Nazimabad             Nazimabad 4                                       22
                      Nazimabad 3                                       20
                      Nazimabad 5                                        9
                      Nazimabad 1                                        8
                      Nazimabad 2                                        5
North Karachi         Buffer Zone                                      105
                      North Karachi Sector 11                           80
                      North Karachi Sector 5                            49
                      North Karachi Sector 7                            38
                      North Karachi Sector 9                            26
                      North Karachi Sector 10                           14
                      North Karachi Sector 8                            14
                      New Karachi                                       10
North Nazimabad       Block F                                          183
                      Block H                                          131
                      Block L                                          120
                      Block N                                          118
                      Block B                                           83
                      Block M                                           52
                      Block K                                           51
                      Block A                                           50
                      Shadman                                           48
                      Block D                                           45
                      Block J                                           37
                      Block I                                           34
                      Block G                                           32
                      Block C                                           12
Scheme 33             Sector 35-A                                      311
                      Sector 47                                        272
                      Sector 40                                        183
                      Saadi Garden                                     173
                      Punjabi Saudagar Society                         156
                      Sector 34-A                                      123
                      Sector 16-A                                      118
                      Sector 17-A                                      114
                      Sector 18-A                                      114
                      Falaknaz                                         110
                      Sector 29                                         99
                      Sector 15-A                                       89
                      Sector 36-A                                       83
                      Meerut Society                                    57
                      Saadi Road                                        57
                      Sector 51-A                                       52
                      Sector 19-A                                       47
                      Gulshan-e-Roomi                                   43
                      Zeenatabad                                        42
                      Sector 52-A                                       28
                      Sawera Enclave                                    27
                      Rafi Premier Residency                            26
                      Sania Corner                                      25
                      Sector 30                                         25
                      Sector 20-A                                       22
                      Sector 24-A                                       22
                      Sector 24-B                                       20
                      Sector 25-B                                       19
                      Sector 22-A                                       18
                      Chapal Uptown                                     16
                      Sumaira Sky Tower                                 14
                      Sector 48-A                                       13
                      Gulshan-E-Usman Housing Society                   12
                      Yousaf Goth                                       11
                      Taloo Gold Residency                              10
Shah Faisal           Gohar Green City Cluster                          42
                      Saima Luxury Belt                                 33
                      Shamsi / Al-Falah Belt                            27
                      Green Town / Rafah-E-Aam Belt                     24
                      Falcon Complex Faisal                             14
Super Highway         Saima Villas                                      72
                      Rabia Enclave                                      9
                      Oasis Park Residencia                              6
University Road       Burj-Ul-Harmain                                  143
                      Saima Jinnah Avenue                               50
                      Al Madni Heights                                  41
                      Safari Enclave Apartments                         18
                      City Tower And Shopping Mall                      17
Name: count, dtype: int64

In [240]:
mapping = {
    # This section handles Sector 40.    "Metropolis Residency": ("Scheme 33", "Sector 40"),
    "Aman Golf View": ("Scheme 33", "Sector 40"),
    "Roomi Residency": ("Scheme 33", "Sector 40"),
    "Roomi Tower": ("Scheme 33", "Sector 40"),
    "Gulshan-e-Roomi": ("Scheme 33", "Sector 40"),
    "Fatima Golf Residency": ("Scheme 33", "Sector 40"),
    "Falaknaz Harmony": ("Scheme 33", "Sector 40"),
    "Gohar Golf Vista": ("Scheme 33", "Sector 40"),
    "Grey Crest Tower": ("Scheme 33", "Sector 40"),
    "Ibrahim Heaven": ("Scheme 33", "Sector 40"),

    # This section handles Sector 44.    "Falcon Society": ("Scheme 33", "Sector 44"),
    "Kings JS Tower": ("Scheme 33", "Sector 44"),

    # This section handles Sector 45-A.    "Burj Al Jinnah": ("Scheme 33", "Sector 45-A"),
    "Cant View Lodges": ("Scheme 33", "Sector 45-A"),

    # This section handles Gulshan-E-Usman Housing Society.    "Saima Pari Avenue": ("Scheme 33", "Gulshan-e-Usman Housing Society"),
    "Metropolis Signature": ("Scheme 33", "Gulshan-e-Usman Housing Society"),

    # This section handles Malir.    "Roomi Icon": ("Malir", "Malir Link To Super Highway"),
    "Airport Residency": ("Malir", "Airport"),

    # This section handles University Road.    "Burj-Ul-Harmain": ("University Road", "Burj-Ul-Harmain"),
}

# This section handles Apply Mapping.for project, (new_location, new_sub_location) in mapping.items():
    mask = df["sub_location"] == project
    df.loc[mask, "location"] = new_location
    df.loc[mask, "sub_location"] = new_sub_location

In [241]:
df[df['location']=='University Road']['sub_location'].value_counts()

sub_location
Burj-Ul-Harmain                 144
Saima Jinnah Avenue              50
Al Madni Heights                 41
Safari Enclave Apartments        18
City Tower And Shopping Mall     17
Name: count, dtype: int64

In [242]:
df[df['location']=='University Road']['sub_location'].value_counts()

sub_location
Burj-Ul-Harmain                 144
Saima Jinnah Avenue              50
Al Madni Heights                 41
Safari Enclave Apartments        18
City Tower And Shopping Mall     17
Name: count, dtype: int64

In [243]:
df[(df['location']=='University Road') & (df['sub_location'].isnull())]['property_name'].value_counts()

property_name
Rafi Premier Residency Fully Leased 3DD Apartment For Sale Ideal For Families, Bank Loan, Financers & Investors                                                 2
RUFI MARY LAND HOUSE AVAILABLE FOR SALE                                                                                                                         1
You Can Find A Gorgeous Flat For sale In University Road                                                                                                        1
Grand 5 Bed DD Apartment For Sale | Premium Family Living | Al Madni Heights, Karachi                                                                           1
West Open Apartment For Sale In Urban Twin Tower                                                                                                                1
Luxury 5 Bed DD Apartment for Sale | Grand Family Living | Al Madni Heights                                                                                     1
1250 Sq. Ft. Ready-To-Move Apartment For Sale In Sawera Enclave | 2 Bed DD                                                                                      1
2 Bed DD Luxury Apartment On Easy 12-Month Installments | 80% Completed Project | Al Madni Heights                                                              1
Exclusive 5 Bed DD Apartment | Premium Lifestyle | Al Madni Heights                                                                                             1
Grand 5 Bed DD Apartment for Sale | Premium Family Residence | Al Madni Heights                                                                                 1
Very Beautiful & Attractive Flat At Main University Road Facing                                                                                                 1
Airport Residency 2 Rooms Apartment For Sale                                                                                                                    1
Spacious West Open | Leased Apartment in Sarah Grands                                                                                                           1
3 Bed DD Apartment For Sale | Secure Your Home Before Possession | Al Madni Heights                                                                             1
2 Bed Dd Apartment For Sale In Al Zehra Complex At University Road                                                                                              1
Luxury 3 Bed DD Apartment For Sale | 80% Completed | Al Madni Heights                                                                                           1
A Palatial Residence For sale In University Road University Road                                                                                                1
Beautiful One Unit West Open 120 SQ Yard House For Sale                                                                                                         1
Luxury 5 Bed DD Apartment for Sale | 80% Completed | Al Madni Heights                                                                                           1
Brand New Apartment Ready For Possession 2400 Sq Ft 4 Bed Dd                                                                                                    1
Elite 5 Bed DD Apartment for Sale | Premium Gated Community | Al Madni Heights                                                                                  1
A Flat Of 1865 Square Feet In University Road                                                                                                                   1
Book A Flat Of 2200 Square Feet In University Road University Road                                                                                              1
Flat Available For Sale In Gul Naar Society Near Samama Mall University Road Karachi                                                                            1
Prime Location 700 Square Feet Flat Ideally Situated In University Road                                                                                         1
4 Rooms Brand New Appartment West Open Banglow Facing                                                                                                           1
Hiba Downtown Apartments For Sale                                                                                                                               1
CORNER 140 YARDS ONE UNIT BUNGALOW AVAILABLE FOR SALE                                                                                                           1
Flat For Sale Semi Furnished                                                                                                                                    1
Airport Residency 4 Room Apartment                                                                                                                              1
1280 Square Feet Flat In University Road Is Available                                                                                                           1
2 Bed DD Flat Available For Sale At Main University Road                                                                                                        1
Sheraton Square Flat                                                                                                                                            1
Gulistan E Jauhar Block 4 Apartment Available For Sale                                                                                                          1
2 Bed DD 1200 Square Feet Net Area Apartment For Sale                                                                                                           1
YOUR DREAMS HOME AWAITS YOU IN FRONT OF MAIN UNIVERSITY ROAD PROJECT , PIONEER COTTAGES                                                                         1
BRAND NEW APARTMENT 3000 SQUARE FEET AVAILABLE FOR SALE                                                                                                         1
Own A Luxury 3 Bed DD Apartment In A Landmark Community | Al Madni Heights                                                                                      1
Prestige 33 Luxury Project 3 bed lonuge                                                                                                                         1
Get In Touch Now To Buy A 1800 Square Feet Flat In University Road                                                                                              1
Own a Signature 5 Bed DD Residence | Al Madni Heights                                                                                                           1
120 Square Yards House For Sale In Shahmir Residency Karachi                                                                                                    1
Prime Location 1250 Square Feet Flat For Sale In The Perfect Location Of University Road                                                                        1
West Open Flat Available For Sale On Main University Road                                                                                                       1
A-301/4, Shaes Apartment 3-Side Corner 2 Bed DD Flat For Sale In Shaes Apartment Demand 1.20                                                                    1
Prime Location 700 Square Feet Flat Up For Sale In University Road                                                                                              1
Ideal Flat In University Road Available For Rs. 29800000                                                                                                        1
Brand New 2 Bed DD Flat For Sale                                                                                                                                1
Flat Available For Sale In Brand New Project                                                                                                                    1
Leased Brand New 3 Bed Room Lounge Apartment Available For Sale                                                                                                 1
3 Bed DD Apartment For Sale | Premium Family Living | Al Madni Heights                                                                                          1
One Unit House Leased House Available For Sale Bank Loan Applicable                                                                                             1
Billys Hames Bungalows Leased West Open Park Facing &Amp; Bank Loan Facalty Available Compound Facing Full Security System                                      1
Ground Plus Two Bungalow With Leased, West Open Park Facing With Boundary Wall Project At Main University Road Banl Loan Facalty Available With Solar System    1
3 Bed DD West Open Flat For Sale                                                                                                                                1
Brand New Apartments On The Prime Location Of University Road                                                                                                   1
AL IRHA Semi Furnished Apartment For Sale 2 Beds D. D In KDA Sch 33                                                                                             1
120 Yard Ground+1 House Is Available For Sale ALONG WITH 6KW SOLAR SYSMEM In Shahmir Residency Scheme 33 Karachi                                                1
5 Bed DD Luxury Apartment for Sale | Spacious Living with Flexible Installments | Al Madni Heights                                                              1
Own an Exclusive 5 Bed DD Luxury Apartment | Al Madni Heights                                                                                                   1
Premium 3 Bed DD Apartment | Modern Family Living | Al Madni Heights                                                                                            1
3 Bed Fully Furnished With All Items Near Safoora Main Road Facing                                                                                              1
Elegant 3 Bed DD Apartment for Sale | Prime Investment Opportunity | Al Madni Heights                                                                           1
sumaira residency lift                                                                                                                                          1
Luxury 3 Bed DD Apartment in a Prime Karachi Location | Al Madni Heights                                                                                        1
Prime Location Flat Of 1050 Square Feet In University Road For Sale                                                                                             1
Leased Flat For Sale At Main University Road                                                                                                                    1
URGENT SALE MAIN UNIVERSITY ROAD MOSMIYAT BOUNDRY WALLED SOCIETY GROUND +2 HOUSE FOR SALE                                                                       1
Brand New Karachi University K Sath Ground+2 House For Sell                                                                                                     1
Flat Available In Sheas Apartment 2 Bed Dd                                                                                                                      1
Buying A Flat In University Road University Road?                                                                                                               1
3 Bed DD Apartment With Premium Amenities | Al Madni Heights                                                                                                    1
Premium 5 Bed DD Apartment | Landmark Living At Al Madni Heights                                                                                                1
Invest in a Spacious 3 Bed DD Apartment | Al Madni Heights                                                                                                      1
5 Room Kings Cottage Phase 1 Project of Kings Group University Road, Gulistan-e-Johar Block 7                                                                   1
Name: count, dtype: int64

In [244]:
patterns = {
    "rafi premier residency": "Rafi Premier Residency",
    "rufi mary land": "Rufi Mary Land",
    "al madni heights": "Al Madni Heights",
    "urban twin tower": "Urban Twin Tower",
    "sawera enclave": "Sawera Enclave",
    "airport residency": "Airport Residency",
    "sarah grands": "Sarah Grands",
    "al zehra complex": "Al Zehra Complex",
    "gul naar society": "Gul Naar Society",
    "hiba downtown": "Hiba Downtown",
    "sheraton square": "Sheraton Square",
    "pioneer cottages": "Pioneer Cottages",
    "prestige 33": "Prestige 33",
    "shahmir residency": "Shahmir Residency",
    "shaes apartment": "Shaes Apartment",
    "al irha": "Al Irha",
    "sumaira residency": "Sumaira Residency",
    "kings cottage": "Kings Cottage"
}

# Extract into sub_location
df["property_name_lower"] = df["property_name"].str.lower()

for pattern, project in patterns.items():
    mask = (
        (df["location"] == "University Road") &
        (df["sub_location"].isna()) &
        (df["property_name_lower"].str.contains(pattern, na=False))
    )
    df.loc[mask, "sub_location"] = project

df.drop(columns="property_name_lower", inplace=True)

In [245]:
df = df[
    ~(
        (df["location"] == "University Road") &
        (df["sub_location"].isna())
    )
]

In [246]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Sector 35-A                        311
Sector 47                          272
Sector 40                          240
Saadi Garden                       173
Punjabi Saudagar Society           156
Sector 34-A                        123
Sector 16-A                        118
Sector 17-A                        114
Sector 18-A                        114
Falaknaz                           110
Sector 29                           99
Sector 15-A                         89
Sector 36-A                         83
Saadi Road                          57
Meerut Society                      57
Sector 51-A                         52
Sector 19-A                         47
Zeenatabad                          42
Sector 52-A                         28
Sawera Enclave                      27
Rafi Premier Residency              26
Sector 30                           25
Sania Corner                        25
Sector 20-A                         22
Sector 24-A                         22
Sector 24-B                         20
Sector 25-B                         19
Sector 22-A                         18
Chapal Uptown                       16
Sumaira Sky Tower                   14
Sector 48-A                         13
Gulshan-E-Usman Housing Society     12
Yousaf Goth                         11
Sector 45-A                         10
Taloo Gold Residency                10
Gulshan-e-Usman Housing Society      5
Sector 44                            2
Name: count, dtype: int64

In [247]:
df['location'].value_counts()

location
DHA Defence                 4473
Scheme 33                   3048
Gulshan-e-Iqbal Town        2305
Gulistan-e-Jauhar           1828
Bahria Town                 1757
Malir Cantt                 1382
North Nazimabad             1077
Jamshed Town                1030
Malir                        999
Clifton                      831
Naya Nazimabad               809
Gadap                        796
Federal B Area               428
North Karachi                409
University Road              310
Korangi                      174
Shah Faisal                  164
Karsaz                       131
Super Highway                115
Saddar                        90
Civil Lines                   86
Nazimabad                     74
DHA City                      58
Bin Qasim Town                57
Defence View                  47
Shahra-e-Faisal               46
F.B. Area                     41
Gulshan-e-Iqbal               40
Tipu Sultan Road              32
Northern Bypass               31
Jinnah Avenue                 30
Abul Hassan Isphani Road      18
National Highway               5
Rashid Minhas Road             2
Name: count, dtype: int64

In [248]:
mapping = {
    "Burj-Ul-Harmain": {
        "location": "Scheme 33",
        "sub_location": "Sector 44"
    },
    "Al Madni Heights": {
        "location": "Gulshan-e-Iqbal Town",
        "sub_location": "Block 13-C"
    },
    "Saima Jinnah Avenue": {
        "location": "Scheme 33",
        "sub_location": "Sector 43-A"
    },
    "Safari Enclave Apartments": {
        "location": "Scheme 33",
        "sub_location": "Sector 36-A"
    },
    "City Tower And Shopping Mall": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 5"
    },
   "Airport Residency": {
        "location": "Malir",
        "sub_location": "Airport"
    },
    "Shahmir Residency": {
        "location": "Scheme 33",
        "sub_location": "Sector 29-A"
    },
    "Rafi Premier Residency": {
        "location": "Scheme 33",
        "sub_location": "Sector 42-A"
    },
    "Gul Naar Society": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 19"
    },
    "Hiba Downtown": {
        "location": "Gulshan-e-Iqbal Town",
        "sub_location": "Block 13D2"
    },
    "Sheraton Square": {
        "location": "Scheme 33",
        "sub_location": "Sector 44"
    },
    "Pioneer Cottages": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 16"
    },
    "Urban Twin Tower": {
        "location": "Gulshan-e-Iqbal Town",
        "sub_location": "Block 13B"
    },
    "Sawera Enclave": {
        "location": "Scheme 33",
        "sub_location": "Sector 38-A"
    },
    "Prestige 33": {
        "location": "Scheme 33",
        "sub_location": "Sector 34-A"
    },
    "Sarah Grands": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 7"
    },
    "Al Zehra Complex": {
        "location": "Scheme 33",
        "sub_location": "Sector 14-B"
    },
    "Rufi Mary Land": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 13"
    },
    "Sumaira Residency": {
        "location": "Scheme 33",
        "sub_location": "Sector 4-B"
    },
    "Al Irha": {
        "location": "Scheme 33",
        "sub_location": "Sector 35-A"
    },
    "Shaes Apartment": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 4"
    },
    "Kings Cottage": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 7"
    }
}


for old_name, values in mapping.items():
    mask = df["sub_location"] == old_name
    
    df.loc[mask, "location"] = values["location"]
    df.loc[mask, "sub_location"] = values["sub_location"]

In [249]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Callachi Cooperative Housing Society      302
Block 1                                   194
Block 10A                                 144
Bahadurabad                               121
Block 4                                    92
Block 7                                    91
Kda Scheme 1                               87
Block 5                                    84
Block 2                                    78
Block 13D2                                 77
Block 13D1                                 65
Block 13-C                                 61
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 17                                   44
Kda Officers Society                       43
Block 13A                                  41
Block 13C                                  39
Block 3                                    39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  25
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Block 14                                   16
Adamjee Nagar                              16
Cp Barar Society, Gulshan-E-Iqbal Town     14
National Stadium Colony                    14
Dawood Society                             13
Gulshan-E-Jamal                            13
Block 4A                                   13
Kda Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [250]:
df['location'].value_counts()

location
DHA Defence                 4473
Scheme 33                   3270
Gulshan-e-Iqbal Town        2368
Gulistan-e-Jauhar           1851
Bahria Town                 1757
Malir Cantt                 1382
North Nazimabad             1077
Jamshed Town                1030
Malir                       1001
Clifton                      831
Naya Nazimabad               809
Gadap                        796
Federal B Area               428
North Karachi                409
Korangi                      174
Shah Faisal                  164
Karsaz                       131
Super Highway                115
Saddar                        90
Civil Lines                   86
Nazimabad                     74
DHA City                      58
Bin Qasim Town                57
Defence View                  47
Shahra-e-Faisal               46
F.B. Area                     41
Gulshan-e-Iqbal               40
Tipu Sultan Road              32
Northern Bypass               31
Jinnah Avenue                 30
Abul Hassan Isphani Road      18
National Highway               5
Rashid Minhas Road             2
Name: count, dtype: int64

In [251]:
df[df['location']=='Bahria Town']['sub_location'].unique()

array(['Precinct 16', 'Precinct 10A', 'Bahria Paradise', 'Precinct 6',
       'Precinct 11A', 'Precinct 1', 'Precinct 27', 'Bahria Apartments',
       'Precinct 4', 'Precinct 17', 'Precinct 8', 'Bahria Heights',
       'Precinct 11B', nan, 'Precinct 10B', 'Precinct 18', 'Precinct 2',
       'Bahria Sports City', 'Private High-Rises', 'Precinct 12',
       'Precinct 9', 'Precinct 31', 'Bahria Hills', 'Precinct 19',
       'Precinct 7', 'Precinct 15'], dtype=object)

In [252]:
df[df['location']=='Tipu Sultan Road']['property_name'].unique()

array(['Old Bungalow For Sale', 'Apartment For Sale',
       'Apartment For Sale On Tipu Sultan',
       'Flat Available For Sale In Remmco Tower Tipu Sultan Road With Finest Interior Work Done',
       '3 BED ROOM APARTMENT AVAILABLE FOR SALE',
       'BRAND NEW TOWN HOUSE FOR SALE',
       'Remco Tower 4bed Drawing For Sale Ultra Luxury Flat. Modern Interior',
       'Town House for Sale Tipu Sultan Road, Karachi',
       'Brand New 4 Bedrooms Drawing Lounge Luxury Flat Available For Sale At Prime Location Of Tipu Sultan Road With All Modern Facilities',
       '4 Bed Dd Available For Sale Remco Tower',
       'Roshan Towers Brand New Luxury Flat Available For Sale At Prime Location Of Tipu Sultan Road',
       'Flat For Sale On Main Tipu Sultan Road',
       'Brand New 3 Bedrooms Drawing Lounge Luxury Flat Available For Sale At Prime Location of Tipu Sultan Road With All Modern Facilities',
       'Remco Tower Tipu Sultan Road 2bed Drawing For Sale Top Class Location And Beautiful Flat For Sale',
       'Invest in Karachis Next Landmark Booking Now on Main Tipu Sultan Road',
       'Prime Location 2400 Square Feet Flat Is Available For Sale In Tipu Sultan Road',
       'LUXURY FURNISHED FLAT FOR SALE IN TIPU SULTAN ROAD',
       'HOT DEAL VERY WELL MAINTAIN BUNGALOW FOR SALE',
       'A Prime Location Flat Of 300 Square Yards',
       'A Perfect Prime Location Flat Awaits You In Tipu Sultan Road Tipu Sultan Road',
       'Prime Location House Of 300 Square Yards Is Available In Contemporary Neighborhood Of Tipu Sultan Road Bangalore Town Society',
       '1600 SQFT 3 BED FLAT IN NEW BUILDING LOCATED ON MAIN TIPU SULTAN ROAD',
       '237 Yards House For Sale',
       '4 BED DD FLAT FOR SALE ON TIPU SULTAN ROAD BRAND NEW PROJECT ROSHAN TOWER',
       '600 Yard Bungalow On Main Tipu Sultan Road In Kda Sch 1 For Sale',
       'Tipu Sultan Road Remmco Tower 3 Bed DD Flat For Sale',
       'LUXURY 2000 SQ FT APARTMENT AVAILABLE FOR SALE',
       'Remco Towers 2 Bed With DD 1450sqft Main Tipu Sultan Road',
       'APARTMENT AVAILABLE FOR SALE',
       '1500 SQ-YARDS | TIPU SULTAN | PRIME LOCATION | Steps from Shahrah-e-Faisal | Huge Garden & Parking'],
      dtype=object)

In [253]:
df = df[
    ~(
        (df["location"] == "Abul Hassan Isphani Road") &
        (df["sub_location"].isna())
    )
]

In [254]:
df = df[
    ~(
        (df["location"] == "Jinnah Avenue") 
    )
]

In [255]:
df['location'].value_counts()

location
DHA Defence             4473
Scheme 33               3270
Gulshan-e-Iqbal Town    2368
Gulistan-e-Jauhar       1851
Bahria Town             1757
Malir Cantt             1382
North Nazimabad         1077
Jamshed Town            1030
Malir                   1001
Clifton                  831
Naya Nazimabad           809
Gadap                    796
Federal B Area           428
North Karachi            409
Korangi                  174
Shah Faisal              164
Karsaz                   131
Super Highway            115
Saddar                    90
Civil Lines               86
Nazimabad                 74
DHA City                  58
Bin Qasim Town            57
Defence View              47
Shahra-e-Faisal           46
F.B. Area                 41
Gulshan-e-Iqbal           40
Tipu Sultan Road          32
Northern Bypass           31
National Highway           5
Rashid Minhas Road         2
Name: count, dtype: int64

In [256]:
patterns_tipu = {
    "remco tower": "Remco Tower",
    "remco towers": "Remco Tower",
    "roshan tower": "Roshan Tower",
    "roshan towers": "Roshan Tower",
    "kda sch 1": "KDA Scheme 1",
    "kda scheme 1": "KDA Scheme 1",
    "bangalore town society": "Bangalore Town Society"
}

# Extract into sub_location
df["property_name_lower"] = df["property_name"].str.lower()

for pattern, project in patterns_tipu.items():
    mask = (
        (df["location"] == "Tipu Sultan Road") &
        (df["sub_location"].isna()) &
        (df["property_name_lower"].str.contains(pattern, na=False))
    )
    df.loc[mask, "sub_location"] = project

df.drop(columns="property_name_lower", inplace=True)

In [257]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Sector 35-A                        312
Sector 47                          272
Sector 40                          240
Saadi Garden                       173
Punjabi Saudagar Society           156
Sector 44                          147
Sector 34-A                        124
Sector 16-A                        118
Sector 18-A                        114
Sector 17-A                        114
Falaknaz                           110
Sector 36-A                        101
Sector 29                           99
Sector 15-A                         89
Meerut Society                      57
Saadi Road                          57
Sector 51-A                         52
Sector 43-A                         50
Sector 19-A                         47
Zeenatabad                          42
Sector 52-A                         28
Sector 38-A                         28
Sector 42-A                         28
Sania Corner                        25
Sector 30                           25
Sector 20-A                         22
Sector 24-A                         22
Sector 24-B                         20
Sector 25-B                         19
Sector 22-A                         18
Chapal Uptown                       16
Sumaira Sky Tower                   14
Sector 48-A                         13
Gulshan-E-Usman Housing Society     12
Yousaf Goth                         11
Sector 45-A                         10
Taloo Gold Residency                10
Gulshan-e-Usman Housing Society      5
Sector 29-A                          2
Sector 4-B                           1
Sector 14-B                          1
Name: count, dtype: int64

In [258]:
mapping = {
    "Sania Corner": "Sector 18-C",
    "Sumaira Sky Tower": "Sector 25-B",
    "Taloo Gold Residency": "Sector 17-B",
    "Zeenatabad": "Sector 19-A",
    "Sector 29-A": "Sector 29",
    "Sector 14-B": np.nan,
    "Sector 4-B" : np.nan,
    "Gulshan-E-Usman Housing Society": "Gulshan-e-Usman Housing Society"
}

df["sub_location"] = df["sub_location"].replace(mapping)

In [259]:
df = df[
    ~(
        (df["location"] == "Scheme 33") &
        (df["sub_location"] == "Chapal Uptown")
    )
]

In [260]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Callachi Cooperative Housing Society      302
Block 1                                   194
Block 10A                                 144
Bahadurabad                               121
Block 4                                    92
Block 7                                    91
Kda Scheme 1                               87
Block 5                                    84
Block 2                                    78
Block 13D2                                 77
Block 13D1                                 65
Block 13-C                                 61
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 17                                   44
Kda Officers Society                       43
Block 13A                                  41
Block 13C                                  39
Block 3                                    39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  25
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Block 14                                   16
Adamjee Nagar                              16
Cp Barar Society, Gulshan-E-Iqbal Town     14
National Stadium Colony                    14
Dawood Society                             13
Gulshan-E-Jamal                            13
Block 4A                                   13
Kda Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [261]:
mapping = {
    "Callachi Cooperative Housing Society": "Block 10A",
    "Kda Officers Society": "Block 17",
    "Dawood Society": "Block 17",
    "Gulshan-E-Jamal": "Block 21"
}

df["sub_location"] = df["sub_location"].replace(mapping)

In [262]:
df[df['location']=='Gulistan-e-Jauhar']['sub_location'].value_counts()

sub_location
Block 15                              196
Block 14                              152
Block 13                              133
Block 18                              132
Block 7                               124
Block 3A                              119
Block 12                              117
Block 17                              114
Block 2                                91
Block 19                               75
Block 16                               72
Block 3                                57
Block 1                                39
Block 10                               39
Askari 4                               34
Block 11                               33
Block 4                                32
Block 20                               25
Block 5                                24
Block 9                                14
Block 16A                              14
Block 8                                12
Latifi Cooperative Housing Society      8
Safoora Goth                            8
Kda Overseas Bungalows                  7
Block 6                                 4
Name: count, dtype: int64

In [263]:
mapping = {
    "Kda Overseas Bungalows": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 16A"
    },
    "Latifi Cooperative Housing Society": {
        "location": "Gulistan-e-Jauhar",
        "sub_location": "Block 20"
    }
}

for old_name, values in mapping.items():
    mask = df["sub_location"] == old_name
    
    df.loc[mask, "location"] = values["location"]
    df.loc[mask, "sub_location"] = values["sub_location"]

In [264]:
df["sub_location"] = df["sub_location"].replace({
    "Bahria Hills": "Precinct 9"
})

In [265]:
df[(df['location']=='Bahria Town') & (df['sub_location']=='Bahria Heights')]['property_name'].value_counts()

property_name
READY TO MOVE 1100sq ft 2Bed Lounge Flat Available FOR SALE in Bahria Heights in TOWER A, H & G (Ready to Move)                                                             6
READY TO MOVE 1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G (Ready To Move)                                                             4
1100 Sq Ft 2BHK Apartment For Sale in TOWER-A Bahria Heights, Bahria Town Karachi Ready to Move | All Amenities Nearby Including Parks, Mosques & Shopping Gallery.         2
1100 Square Feet's Apartments Available For Sale in Bahria Heights BAHRIA TOWN KARACHI                                                                                      2
READY TO MOVE 1100 Square Feet 2 Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G (Ready To Move)                                                     2
READY TO MOVE 1100sq ft 2 Bed Lounge Flat Available FOR SALE in Bahria Heights in TOWER A, H & G (Ready to Move)                                                            2
1100 Sq Ft 2-BHK Apartment For Sale Bahria Heights Tower-D, Bahria Town Karachi Close to Completion | All Amenities Nearby Including Parks, Mosques & Shopping Gallery.     2
Affordable Prime Location Flat Of 1100 Square Feet Is Available For Sale                                                                                                    1
READY TO MOVE 1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H &Amp;Amp; G (Ready To Move)                                                     1
1100 Square feet 2 Bedroom Flat Available For Sale in Bahria Heights Bahria Town Karachi                                                                                    1
1100 Sq Ft Outer West Open 2BHK Apartment For Sale Bahria Heights, Bahria Town Karachi Ready To Move | All Amenities Nearby Including Parks, Mosques & Shopping Gallery.    1
2 BED DD FLAT (BAHRIA HEIGHTS) FOR SALE IN BAHRIA TOWN KARACHI                                                                                                              1
1400sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER B (Ready For Possession)                                                                           1
Prime Location Affordable Flat For sale In Bahria Heights                                                                                                                   1
Bahria Heights Apartment Bahria Town Karachi                                                                                                                                1
Luxury Ready-To-Move 2-Bed Family Apartment | Fully Furnished                                                                                                               1
1100 SQFts Flat Available For Sale In Bahria Heights BAHRIA TOWN KARACHI                                                                                                    1
1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER B (Ready For Possession                                                                            1
Prime Location Flat In Bahria Heights Sized 1100 Square Feet Is Available                                                                                                   1
1100 Sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights                                                                                                            1
Get Your Dream Prime Location Flat In Bahria Heights Karachi                                                                                                                1
1100 Sq Ft 2BHK Apartment For Sale In TOWER-A Bahria Heights, Bahria Town Karachi Ready To Move | All Amenities Nearby Including Parks, Mosques & Shopping Gallery.         1
1100 Square Feet 2 Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G (Ready To Move)                                                                   1
7th Floor Park Facing 1100sq Ft 2 Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER E Possession Utility Paid Extra Land Not Paid                               1
Get A Prime Location 1150 Square Feet Flat For Sale In Bahria Heights                                                                                                       1
Prime Location 1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights                                                                                              1
1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G (Ready To Move)                                                                           1
1100 Square Feet Apartments Available For Sale In Bahria Heights BAHRIA TOWN KARACHI                                                                                        1
Tower A Outer Parkface                                                                                                                                                      1
1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G                                                                                           1
Stunning Prime Location Flat Is Available For sale In Bahria Heights                                                                                                        1
Tower H 8th Floor Outer Park Face READY TO MOVE 1100sq Ft 2Bed Lounge Flat Available FOR SALE In Bahria Heights (Ready To Move)                                             1
1100 Square Feet 2 Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER F                                                                                          1
Get Your Hands On Prime Location Flat In Karachi Best Area                                                                                                                  1
Reserve A Prime Location Flat Of 1100 Square Feet Now In Bahria Heights                                                                                                     1
READY TO MOVE 1100 sq Ft 2 Bed Lounge Flat Available FOR SALE In Bahria Heights In TOWER A, H & G (Ready To Move)                                                           1
Prime Location In Bahria Heights 1100 Square Feet Flat For sale                                                                                                             1
1100 Square Feet Apartments Available For Sale In Bahria Heights Bahria Town Karachi                                                                                        1
BAHRIA HEIGHTS APARTMENT FOR SALE                                                                                                                                           1
YOUR DREAMS HOME AWAITS YOU IN MOST BEAUTIFUL LOCATION OF BAHRIA TOWN , BAHRIA HEIGHTS . .                                                                                  1
Bahria Heights Apartment For Sale                                                                                                                                           1
1100 Square Feet'S Apartment Available For Sale In Bahria Heights BAHRIA TOWN KARACHI                                                                                       1
2 Bed Lounge 1600 Sq Feet Flat Available FOR SALE IN Bahria Heights All Amenities Including Park , Mosques And Shops                                                        1
Prime Location Bahria Heights Flat For sale Sized 1400 Square Feet AVAILABLE FOR SALE                                                                                       1
Name: count, dtype: int64

In [266]:
df[df['location']=='Gadap']['sub_location'].value_counts()

sub_location
Gulshan-E-Maymar    468
Surjani Town        273
Memon Goth           55
Name: count, dtype: int64

In [267]:
locations_to_remove = [
    "Diamond City, Gulshan-E-Maymar",
    "Garden City"
]

df = df[~df["sub_location"].isin(locations_to_remove)].copy()

In [268]:
df[df['location']=='Rashid Minhas Road']['sub_location'].value_counts()

Series([], Name: count, dtype: int64)

In [269]:
df['sub_location'].value_counts()

sub_location
Phase 8                                         2241
Phase 6                                          914
Askari 5                                         626
Askari 6                                         585
Falcon Complex New Malir                         516
Gulshan-E-Maymar                                 468
Block 10A                                        454
Phase 5                                          427
Sector 35-A                                      312
Phase 7                                          296
Pechs                                            284
Surjani Town                                     273
Sector 47                                        272
Sector 40                                        240
Block 1                                          233
Falaknaz                                         228
Block 7                                          226
Block 17                                         214
Block 15                                         214
Block 2                                          201
Block 14                                         191
Block 13                                         184
Block F                                          183
Shaheed Millat Road                              179
Saadi Garden                                     173
Block 12                                         171
Phase 4                                          168
Clifton Block 2                                  160
Punjabi Saudagar Society                         156
Block B                                          150
Phase 7 Extension                                147
Sector 44                                        147
Block A                                          145
Precinct 2                                       145
Block 10                                         135
Block 18                                         132
Block H                                          131
Navy Housing Scheme Karsaz                       131
Precinct 12                                      130
Bahria Sports City                               128
Bath Island                                      128
Block 4                                          124
Sector 34-A                                      124
Khalid Bin Walid Road                            124
Bahadurabad                                      121
Block L                                          120
Bahria Apartments                                120
Block 3A                                         119
Sector 16-A                                      118
Block N                                          118
Sector 17-A                                      114
Block 16                                         114
Sector 18-A                                      114
Block D                                          113
Allahwala Town                                   113
Block 19                                         109
Block 5                                          108
Buffer Zone                                      105
Sector 36-A                                      101
Sector 29                                        101
Block C                                           99
Model Colony                                      96
Block 3                                           96
Block 11                                          96
Clifton Block 9                                   94
Precinct 8                                        94
Private High-Rises                                92
Precinct 10A                                      92
Sector 19-A                                       89
Sector 15-A                                       89
Clifton Block 8                                   89
Kda Scheme 1                                      87
Clifton Block 1                                   87
Precinct 11A                                      85
Precinct 31                                       84
Malir Link To Super Highway                       83
North Karachi Sector 11                           80
Block 13D2                                        77
Bahria Paradise                                   76
Block M                                           75
Precinct 11B                                      74
Block 6                                           73
Saima Villas                                      72
Precinct 1                                        70
Phase 2 Extension                                 69
Precinct 10B                                      68
Phase 1                                           65
Block 13D1                                        65
Precinct 9                                        65
Precinct 6                                        63
Precinct 27                                       61
Block 13-C                                        61
Jamshed Road                                      61
Dhoraji Colony                                    59
Block 13D                                         58
Bahria Heights                                    57
Saadi Road                                        57
Meerut Society                                    57
Memon Goth                                        55
Phase 2                                           54
Block 21                                          54
Clifton Block 4                                   52
Sector 51-A                                       52
Dohs Phase 1                                      51
Block K                                           51
Block 9                                           50
Sector 43-A                                       50
North Karachi Sector 5                            49
Precinct 4                                        49
Shadman                                           48
Airport                                           48
Sharfabad                                         47
Karachi Administration Employees Society          46
Smchs - Sindhi Muslim Society                     45
Block 20                                          43
Frere Town                                        43
Gohar Green City Cluster                          42
Block 13A                                         41
Clifton Block 7                                   40
Tariq Road                                        39
Block 13C                                         39
North Karachi Sector 7                            38
Block J                                           37
Saima Projects                                    37
Precinct 16                                       37
Amir Khusro                                       36
Clifton Block 5                                   35
Mateen Complex                                    34
Block I                                           34
Precinct 19                                       34
Garden East                                       34
Askari 4                                          34
Saima Luxury Belt                                 33
Sector 25-B                                       33
Block G                                           32
Block 13D3                                        32
Block 8                                           30
Amil Colony                                       29
Sector 38-A                                       28
Sector 42-A                                       28
Sector 52-A                                       28
Shamsi / Al-Falah Belt                            27
Hill Park                                         27
North Karachi Sector 9                            26
Precinct 17                                       26
Block 13B                                         25
Sector 18-C                                       25
Sector 30                                         25
Green Town / Rafah-E-Aam Belt                     24
Korangi Industrial Area                           23
Sector 20-A                                       22
Sector 24-A                                       22
Precinct 15                                       22
Soldier Bazar                                     22
Nazimabad 4                                       22
Gizri                                             21
Phase 5 Extension                                 21
Block 16A                                         21
Parsi Colony                                      21
Jamia Millia Road                                 20
Sector 24-B                                       20
Nazimabad 3                                       20
Mehmoodabad                                       19
Mohammad Ali Society                              18
Sector 22-A                                       18
Gulshan-e-Usman Housing Society                   17
Cosmopolitan Society                              17
Qayyumabad                                        16
Kda Employees Society                             16
Adamjee Nagar                                     16
Golden Town                                       16
North Karachi Sector 8                            14
Falcon Complex Faisal                             14
Cp Barar Society, Gulshan-E-Iqbal Town            14
Precinct 7                                        14
Shahra-E-Qaideen                                  14
National Stadium Colony                           14
North Karachi Sector 10                           14
Block 4A                                          13
Malir Town Residency                              13
Sector 48-A                                       13
Muslimabad Society                                12
Defence Skyline, Shaheed-E-Millat Expressway      12
Phase 8 Extension                                 12
Clifton Block 6                                   11
Kda Scheme 1 Extension                            11
Yousaf Goth                                       11
Dohs Phase 2                                      11
Clifton Block 3                                   11
Sector 17-B                                       10
Shahrah-E-Pakistan                                10
New Karachi                                       10
Sector 45-A                                       10
Rabia Enclave                                      9
Nazimabad 5                                        9
Nazimabad 1                                        8
Safoora Goth                                       8
Oasis Park Residencia                              6
Precinct 18                                        5
Nazimabad 2                                        5
Remco Tower                                        4
Roshan Tower                                       2
Bangalore Town Society                             1
KDA Scheme 1                                       1
Name: count, dtype: int64

In [270]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Block 10A                                 446
Block 1                                   194
Bahadurabad                               121
Block 17                                  100
Block 4                                    92
Block 7                                    91
Kda Scheme 1                               87
Block 5                                    84
Block 2                                    78
Block 13D2                                 77
Block 13D1                                 65
Block 13-C                                 61
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 13A                                  41
Block 3                                    39
Block 13C                                  39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  25
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Adamjee Nagar                              16
Block 14                                   16
National Stadium Colony                    14
Cp Barar Society, Gulshan-E-Iqbal Town     14
Block 21                                   13
Block 4A                                   13
Kda Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [271]:
counts = df["sub_location"].value_counts()
df = df[df["sub_location"].map(counts) > 4].copy()

In [272]:
df.head()

,property_name,address,location,sub_location,price,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,servant_quarter_score,sub_location_score,location_score,area_per_bedroom
0,"Brand New, West Open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,21111.11,1080.0,4,5,1.0,NaN,2.0,3.0,0,1,1,1,2025.0,house,1.0,Relatively New,2.0,1,2.0,3.0,270.00
1,Double Storey House Available For Sale,"north nazimabad - block b, north nazimabad",North Nazimabad,Block B,100000000.0,22222.22,4500.0,5,5,1.0,NaN,NaN,1.0,0,1,1,1,NaN,house,NaN,NaN,1.0,1,3.0,4.0,900.00
2,166 Square Yard Flat For Sale In North Nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,Block F,25500000.0,17068.27,1494.0,3,3,0.0,NaN,12.0,0.0,2,0,1,0,NaN,flat,NaN,NaN,0.0,0,2.0,4.0,498.00
3,Flat Available For Sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,27049.52,2403.0,4,4,2.0,NaN,NaN,2.0,0,0,1,0,NaN,flat,NaN,NaN,2.0,0,4.0,4.0,600.75
4,North Vista 2 Bed D D Flat For Sale,"north nazimabad - block b, north nazimabad",North Nazimabad,Block B,16500000.0,17295.60,954.0,2,3,0.0,NaN,NaN,0.0,0,0,0,0,NaN,flat,NaN,NaN,0.0,0,3.0,4.0,477.00

In [273]:
district_mapping = {
    # This section handles Karachi South.    "DHA Defence": "Karachi South",
    "Clifton": "Karachi South",

    # This section handles Karachi East.    "Karsaz": "Karachi East",
    "Gulshan-e-Iqbal Town": "Karachi East",
    "Gulistan-e-Jauhar": "Karachi East",
    "Jamshed Town": "Karachi East",
    "Scheme 33": "Karachi East",

    # This section handles Karachi Central.    "Federal B Area": "Karachi Central",
    "F.B. Area": "Karachi Central",
    "North Nazimabad": "Karachi Central",
    "North Karachi": "Karachi Central",
    "Nazimabad": "Karachi Central",
    "Naya Nazimabad": "Karachi Central",

    # This section handles Malir.    "Malir": "Malir",
    "Malir Cantt": "Malir",
    "Gadap": "Malir",
    "Super Highway": "Malir",
    "Bahria Town": "Malir",
    "Bin Qasim Town": "Malir",

    # This section handles Korangi.    "Korangi": "Korangi",
    "Shah Faisal": "Korangi"
}

In [274]:
df["district"] = df["location"].map(district_mapping)

In [275]:
df.loc[
    df["location"] == "Gulshan-e-Iqbal",
    "location"
] = "Gulshan-e-Iqbal Town"

In [276]:
print(df[df["district"].isna()]["location"].value_counts())

location
Gulshan-e-Iqbal Town    40
Name: count, dtype: int64

In [277]:
df.groupby("district")["price_per_sqft"].agg(['median','count']).sort_values(by='median',ascending=False)

                    median  count
district
Karachi South    37453.180   5185
Karachi Central  22453.700   2133
Karachi East     18750.000   7743
Malir            13659.305   4828
Korangi           7222.220    308

In [278]:
df['sub_location'].value_counts()

sub_location
Phase 8                                         2241
Phase 6                                          914
Askari 5                                         626
Askari 6                                         585
Falcon Complex New Malir                         516
Gulshan-E-Maymar                                 468
Block 10A                                        454
Phase 5                                          427
Sector 35-A                                      312
Phase 7                                          296
Pechs                                            284
Surjani Town                                     273
Sector 47                                        272
Sector 40                                        240
Block 1                                          233
Falaknaz                                         228
Block 7                                          226
Block 15                                         214
Block 17                                         214
Block 2                                          201
Block 14                                         191
Block 13                                         184
Block F                                          183
Shaheed Millat Road                              179
Saadi Garden                                     173
Block 12                                         171
Phase 4                                          168
Clifton Block 2                                  160
Punjabi Saudagar Society                         156
Block B                                          150
Phase 7 Extension                                147
Sector 44                                        147
Block A                                          145
Precinct 2                                       145
Block 10                                         135
Block 18                                         132
Navy Housing Scheme Karsaz                       131
Block H                                          131
Precinct 12                                      130
Bahria Sports City                               128
Bath Island                                      128
Sector 34-A                                      124
Block 4                                          124
Khalid Bin Walid Road                            124
Bahadurabad                                      121
Bahria Apartments                                120
Block L                                          120
Block 3A                                         119
Block N                                          118
Sector 16-A                                      118
Block 16                                         114
Sector 17-A                                      114
Sector 18-A                                      114
Allahwala Town                                   113
Block D                                          113
Block 19                                         109
Block 5                                          108
Buffer Zone                                      105
Sector 29                                        101
Sector 36-A                                      101
Block C                                           99
Block 11                                          96
Block 3                                           96
Model Colony                                      96
Precinct 8                                        94
Clifton Block 9                                   94
Precinct 10A                                      92
Private High-Rises                                92
Clifton Block 8                                   89
Sector 15-A                                       89
Sector 19-A                                       89
Kda Scheme 1                                      87
Clifton Block 1                                   87
Precinct 11A                                      85
Precinct 31                                       84
Malir Link To Super Highway                       83
North Karachi Sector 11                           80
Block 13D2                                        77
Bahria Paradise                                   76
Block M                                           75
Precinct 11B                                      74
Block 6                                           73
Saima Villas                                      72
Precinct 1                                        70
Phase 2 Extension                                 69
Precinct 10B                                      68
Block 13D1                                        65
Phase 1                                           65
Precinct 9                                        65
Precinct 6                                        63
Precinct 27                                       61
Block 13-C                                        61
Jamshed Road                                      61
Dhoraji Colony                                    59
Block 13D                                         58
Bahria Heights                                    57
Meerut Society                                    57
Saadi Road                                        57
Memon Goth                                        55
Phase 2                                           54
Block 21                                          54
Clifton Block 4                                   52
Sector 51-A                                       52
Dohs Phase 1                                      51
Block K                                           51
Sector 43-A                                       50
Block 9                                           50
Precinct 4                                        49
North Karachi Sector 5                            49
Shadman                                           48
Airport                                           48
Sharfabad                                         47
Karachi Administration Employees Society          46
Smchs - Sindhi Muslim Society                     45
Frere Town                                        43
Block 20                                          43
Gohar Green City Cluster                          42
Block 13A                                         41
Clifton Block 7                                   40
Block 13C                                         39
Tariq Road                                        39
North Karachi Sector 7                            38
Saima Projects                                    37
Precinct 16                                       37
Block J                                           37
Amir Khusro                                       36
Clifton Block 5                                   35
Block I                                           34
Mateen Complex                                    34
Precinct 19                                       34
Askari 4                                          34
Garden East                                       34
Sector 25-B                                       33
Saima Luxury Belt                                 33
Block 13D3                                        32
Block G                                           32
Block 8                                           30
Amil Colony                                       29
Sector 38-A                                       28
Sector 42-A                                       28
Sector 52-A                                       28
Shamsi / Al-Falah Belt                            27
Hill Park                                         27
Precinct 17                                       26
North Karachi Sector 9                            26
Sector 30                                         25
Block 13B                                         25
Sector 18-C                                       25
Green Town / Rafah-E-Aam Belt                     24
Korangi Industrial Area                           23
Soldier Bazar                                     22
Sector 20-A                                       22
Nazimabad 4                                       22
Sector 24-A                                       22
Precinct 15                                       22
Phase 5 Extension                                 21
Parsi Colony                                      21
Gizri                                             21
Block 16A                                         21
Sector 24-B                                       20
Jamia Millia Road                                 20
Nazimabad 3                                       20
Mehmoodabad                                       19
Mohammad Ali Society                              18
Sector 22-A                                       18
Gulshan-e-Usman Housing Society                   17
Cosmopolitan Society                              17
Qayyumabad                                        16
Golden Town                                       16
Kda Employees Society                             16
Adamjee Nagar                                     16
Precinct 7                                        14
North Karachi Sector 8                            14
Falcon Complex Faisal                             14
Cp Barar Society, Gulshan-E-Iqbal Town            14
Shahra-E-Qaideen                                  14
North Karachi Sector 10                           14
National Stadium Colony                           14
Sector 48-A                                       13
Block 4A                                          13
Malir Town Residency                              13
Phase 8 Extension                                 12
Muslimabad Society                                12
Defence Skyline, Shaheed-E-Millat Expressway      12
Kda Scheme 1 Extension                            11
Yousaf Goth                                       11
Clifton Block 6                                   11
Dohs Phase 2                                      11
Clifton Block 3                                   11
Sector 45-A                                       10
Sector 17-B                                       10
New Karachi                                       10
Shahrah-E-Pakistan                                10
Nazimabad 5                                        9
Rabia Enclave                                      9
Nazimabad 1                                        8
Safoora Goth                                       8
Oasis Park Residencia                              6
Precinct 18                                        5
Nazimabad 2                                        5
Name: count, dtype: int64

In [279]:
sub_location_type_mapping = {

    # This section handles Subdivision (Phase / Block / Sector / Precinct).
    "Phase 1": "Subdivision",
    "Phase 2": "Subdivision",
    "Phase 2 Extension": "Subdivision",
    "Phase 4": "Subdivision",
    "Phase 5": "Subdivision",
    "Phase 5 Extension": "Subdivision",
    "Phase 6": "Subdivision",
    "Phase 7": "Subdivision",
    "Phase 7 Extension": "Subdivision",
    "Phase 8": "Subdivision",
    "Phase 8 Extension": "Subdivision",

    "Block A": "Subdivision",
    "Block B": "Subdivision",
    "Block C": "Subdivision",
    "Block D": "Subdivision",
    "Block F": "Subdivision",
    "Block G": "Subdivision",
    "Block H": "Subdivision",
    "Block I": "Subdivision",
    "Block J": "Subdivision",
    "Block K": "Subdivision",
    "Block L": "Subdivision",
    "Block M": "Subdivision",
    "Block N": "Subdivision",

    "Block 1": "Subdivision",
    "Block 2": "Subdivision",
    "Block 3": "Subdivision",
    "Block 3A": "Subdivision",
    "Block 4": "Subdivision",
    "Block 4A": "Subdivision",
    "Block 5": "Subdivision",
    "Block 6": "Subdivision",
    "Block 7": "Subdivision",
    "Block 8": "Subdivision",
    "Block 9": "Subdivision",
    "Block 10": "Subdivision",
    "Block 10A": "Subdivision",
    "Block 11": "Subdivision",
    "Block 12": "Subdivision",
    "Block 13": "Subdivision",
    "Block 13A": "Subdivision",
    "Block 13B": "Subdivision",
    "Block 13C": "Subdivision",
    "Block 13D": "Subdivision",
    "Block 13D1": "Subdivision",
    "Block 13D2": "Subdivision",
    "Block 13D3": "Subdivision",
    "Block 14": "Subdivision",
    "Block 15": "Subdivision",
    "Block 16": "Subdivision",
    "Block 16A": "Subdivision",
    "Block 17": "Subdivision",
    "Block 18": "Subdivision",
    "Block 19": "Subdivision",
    "Block 20": "Subdivision",
    "Block 21": "Subdivision",

    "Sector 15-A": "Subdivision",
    "Sector 16-A": "Subdivision",
    "Sector 17-A": "Subdivision",
    "Sector 17-B": "Subdivision",
    "Sector 18-A": "Subdivision",
    "Sector 18-C": "Subdivision",
    "Sector 19-A": "Subdivision",
    "Sector 20-A": "Subdivision",
    "Sector 22-A": "Subdivision",
    "Sector 24-A": "Subdivision",
    "Sector 24-B": "Subdivision",
    "Sector 25-B": "Subdivision",
    "Sector 29": "Subdivision",
    "Sector 30": "Subdivision",
    "Sector 34-A": "Subdivision",
    "Sector 35-A": "Subdivision",
    "Sector 36-A": "Subdivision",
    "Sector 38-A": "Subdivision",
    "Sector 40": "Subdivision",
    "Sector 42-A": "Subdivision",
    "Sector 43-A": "Subdivision",
    "Sector 44": "Subdivision",
    "Sector 45-A": "Subdivision",
    "Sector 47": "Subdivision",
    "Sector 48-A": "Subdivision",
    "Sector 51-A": "Subdivision",
    "Sector 52-A": "Subdivision",

    "Precinct 1": "Subdivision",
    "Precinct 2": "Subdivision",
    "Precinct 4": "Subdivision",
    "Precinct 6": "Subdivision",
    "Precinct 7": "Subdivision",
    "Precinct 8": "Subdivision",
    "Precinct 9": "Subdivision",
    "Precinct 10A": "Subdivision",
    "Precinct 10B": "Subdivision",
    "Precinct 11A": "Subdivision",
    "Precinct 11B": "Subdivision",
    "Precinct 12": "Subdivision",
    "Precinct 15": "Subdivision",
    "Precinct 16": "Subdivision",
    "Precinct 17": "Subdivision",
    "Precinct 18": "Subdivision",
    "Precinct 19": "Subdivision",
    "Precinct 27": "Subdivision",
    "Precinct 31": "Subdivision",

    "Nazimabad 1": "Subdivision",
    "Nazimabad 2": "Subdivision",
    "Nazimabad 3": "Subdivision",
    "Nazimabad 4": "Subdivision",
    "Nazimabad 5": "Subdivision",

    "North Karachi Sector 5": "Subdivision",
    "North Karachi Sector 7": "Subdivision",
    "North Karachi Sector 8": "Subdivision",
    "North Karachi Sector 9": "Subdivision",
    "North Karachi Sector 10": "Subdivision",
    "North Karachi Sector 11": "Subdivision",


    # This section handles Military Housing.
    "Askari 4": "Military Housing",
    "Askari 5": "Military Housing",
    "Askari 6": "Military Housing",
    "Dohs Phase 1": "Military Housing",
    "Dohs Phase 2": "Military Housing",
    "Navy Housing Scheme Karsaz": "Military Housing",


    # This section handles Housing Society.
    "Pechs": "Housing Society",
    "Punjabi Saudagar Society": "Housing Society",
    "Meerut Society": "Housing Society",
    "Smchs - Sindhi Muslim Society": "Housing Society",
    "Karachi Administration Employees Society": "Housing Society",
    "Kda Employees Society": "Housing Society",
    "Kda Scheme 1": "Housing Society",
    "Kda Scheme 1 Extension": "Housing Society",
    "Gulshan-e-Usman Housing Society": "Housing Society",
    "Mohammad Ali Society": "Housing Society",
    "Cosmopolitan Society": "Housing Society",
    "Parsi Colony": "Housing Society",
    "Adamjee Nagar": "Housing Society",
    "National Stadium Colony": "Housing Society",


    # This section handles Residential Project.
    "Falcon Complex New Malir": "Residential Project",
    "Falcon Complex Faisal": "Residential Project",
    "Bahria Apartments": "Residential Project",
    "Bahria Heights": "Residential Project",
    "Bahria Paradise": "Residential Project",
    "Bahria Sports City": "Residential Project",
    "Private High-Rises": "Residential Project",
    "Saima Projects": "Residential Project",
    "Saima Villas": "Residential Project",
    "Mateen Complex": "Residential Project",
    "Oasis Park Residencia": "Residential Project",


    # This section handles Neighbourhood.
    "Gulshan-E-Maymar": "Neighbourhood",
    "Surjani Town": "Neighbourhood",
    "Memon Goth": "Neighbourhood",
    "Bath Island": "Neighbourhood",
    "Bahadurabad": "Neighbourhood",
    "Buffer Zone": "Neighbourhood",
    "Model Colony": "Neighbourhood",
    "Shadman": "Neighbourhood",
    "Sharfabad": "Neighbourhood",
    "Safoora Goth": "Neighbourhood",
    "Dhoraji Colony": "Neighbourhood",
    "Frere Town": "Neighbourhood",
    "Mehmoodabad": "Neighbourhood",
    "Gizri": "Neighbourhood",
    "New Karachi": "Neighbourhood",
    "Airport": "Neighbourhood",
    "Yousaf Goth": "Neighbourhood",
    "Qayyumabad": "Neighbourhood",


    # This section handles Road.
    "Tariq Road": "Road",
    "Shaheed Millat Road": "Road",
    "Khalid Bin Walid Road": "Road",
    "Jamia Millia Road": "Road",
    "Shahra-E-Qaideen": "Road",
    "Shahrah-E-Pakistan": "Road",
    "Malir Link To Super Highway": "Road",
    "Defence Skyline, Shaheed-E-Millat Expressway": "Road"
}

In [280]:
df["sub_location_type"] = df["sub_location"].map(sub_location_type_mapping)

# This section handles Check Missing Categories.df[df["sub_location_type"].isna()]["sub_location"].value_counts()

sub_location
Falaknaz                                  228
Saadi Garden                              173
Clifton Block 2                           160
Allahwala Town                            113
Clifton Block 9                            94
Clifton Block 8                            89
Clifton Block 1                            87
Jamshed Road                               61
Block 13-C                                 61
Saadi Road                                 57
Clifton Block 4                            52
Gohar Green City Cluster                   42
Clifton Block 7                            40
Amir Khusro                                36
Clifton Block 5                            35
Garden East                                34
Saima Luxury Belt                          33
Amil Colony                                29
Shamsi / Al-Falah Belt                     27
Hill Park                                  27
Green Town / Rafah-E-Aam Belt              24
Korangi Industrial Area                    23
Soldier Bazar                              22
Golden Town                                16
Cp Barar Society, Gulshan-E-Iqbal Town     14
Malir Town Residency                       13
Muslimabad Society                         12
Clifton Block 6                            11
Clifton Block 3                            11
Rabia Enclave                               9
Name: count, dtype: int64

In [281]:
remaining_mapping = {

    # This section handles Residential Project.    "Falaknaz": "Residential Project",
    "Gohar Green City Cluster": "Residential Project",
    "Saima Luxury Belt": "Residential Project",
    "Malir Town Residency": "Residential Project",


    # This section handles Subdivision.    "Clifton Block 1": "Subdivision",
    "Clifton Block 2": "Subdivision",
    "Clifton Block 3": "Subdivision",
    "Clifton Block 4": "Subdivision",
    "Clifton Block 5": "Subdivision",
    "Clifton Block 6": "Subdivision",
    "Clifton Block 7": "Subdivision",
    "Clifton Block 8": "Subdivision",
    "Clifton Block 9": "Subdivision",

    "Block 13-C": "Subdivision",


    # This section handles Housing Society.    "Saadi Garden": "Housing Society",
    "Saadi Road": "Road",
    "Cp Barar Society, Gulshan-E-Iqbal Town": "Housing Society",
    "Muslimabad Society": "Housing Society",


    # This section handles Neighbourhood.    "Allahwala Town": "Neighbourhood",
    "Jamshed Road": "Neighbourhood",
    "Amir Khusro": "Neighbourhood",
    "Garden East": "Neighbourhood",
    "Amil Colony": "Neighbourhood",
    "Hill Park": "Neighbourhood",
    "Shamsi / Al-Falah Belt": "Neighbourhood",
    "Green Town / Rafah-E-Aam Belt": "Neighbourhood",
    "Korangi Industrial Area": "Neighbourhood",
    "Soldier Bazar": "Neighbourhood",
    "Golden Town": "Neighbourhood"
}

In [282]:
df["sub_location_type"] = (
    df["sub_location_type"]
    .fillna(df["sub_location"].map(remaining_mapping))
)

# This section handles Check Remaining Unknown.df[df["sub_location_type"].isna()]["sub_location"].value_counts()

sub_location
Rabia Enclave    9
Name: count, dtype: int64

In [283]:
df.groupby('sub_location_type')['price_per_sqft'].agg(['median','count']).sort_values(by='median',ascending=False)

                        median  count
sub_location_type
Road                 25574.285    538
Housing Society      25277.780   1004
Military Housing     23407.410   1438
Subdivision          22405.645  13792
Neighbourhood        16256.825   1988
Residential Project  12777.780   1468

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20237 entries, 0 to 20236
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   property_name          20237 non-null  object
 1   address                20237 non-null  object
 2   location               20237 non-null  object
 3   sub_location           20237 non-null  object
 4   price                  20237 non-null  float64
 5   price_per_sqft         20237 non-null  float64
 6   area                   20237 non-null  float64
 7   bedrooms               20237 non-null  int64
 8   bathrooms              20237 non-null  int64
 9   kitchen                20207 non-null  float64
 10  floor                  3204 non-null   float64
 11  total_floors           8455 non-null   float64
 12  parking                20201 non-null  float64
 13  elevator               20237 non-null  int64
 14  servant_quarters       20237 non-null  int64
 15  electricity_backup     20237 non-null  int64
 16  furnished              20237 non-null  int64
 17  completion_year        10293 non-null  float64
 18  property_type          20237 non-null  object
 19  property_age           10293 non-null  float64
 20  age_category           10293 non-null  object
 21  parking_score          20201 non-null  float64
 22  servant_quarter_score  20237 non-null  int64
 23  sub_location_score     20237 non-null  float64
 24  location_score         20237 non-null  int64
 25  area_per_bedroom       20237 non-null  float64
 26  district               20197 non-null  object
 27  sub_location_type      20228 non-null  object
 28  global_percentile      20237 non-null  float64
dtypes: float64(13), int64(8), object(8)
memory usage: 4.5+ MB

In [313]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Block 10A                                 454
Block 1                                   194
Bahadurabad                               121
Block 2                                   110
Block 4                                   105
Block 17                                  100
Block 7                                    91
Kda Scheme 1                               87
Block 5                                    84
Block 13D2                                 77
Block 13D1                                 65
Block 13-C                                 61
Dhoraji Colony                             59
Block 13D                                  58
Block 6                                    57
Sharfabad                                  47
Block 13A                                  41
Block 3                                    39
Block 13C                                  39
Block 11                                   34
Block 13D3                                 32
Block 13B                                  25
Block 16                                   23
Block 10                                   21
Mohammad Ali Society                       18
Block 19                                   17
Block 9                                    17
Block 14                                   16
Adamjee Nagar                              16
Cp Barar Society, Gulshan-E-Iqbal Town     14
National Stadium Colony                    14
Block 21                                   13
Kda Scheme 1 Extension                     11
Block 13                                   10
Name: count, dtype: int64

In [312]:
df.loc[df["sub_location"] == "Block 4A", "sub_location"] = "Block 4"

In [314]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Precinct 2                                       145
                      Precinct 12                                      130
                      Bahria Sports City                               128
                      Bahria Apartments                                120
                      Precinct 8                                        94
                      Precinct 10A                                      92
                      Private High-Rises                                92
                      Precinct 11A                                      85
                      Precinct 31                                       84
                      Bahria Paradise                                   76
                      Precinct 11B                                      74
                      Precinct 1                                        70
                      Precinct 10B                                      68
                      Precinct 9                                        65
                      Precinct 6                                        63
                      Precinct 27                                       61
                      Bahria Heights                                    57
                      Precinct 4                                        49
                      Precinct 16                                       37
                      Precinct 19                                       34
                      Precinct 17                                       26
                      Precinct 15                                       22
                      Precinct 7                                        14
                      Precinct 18                                        5
Bin Qasim Town        Mateen Complex                                    34
Clifton               Clifton Block 2                                  160
                      Bath Island                                      128
                      Clifton Block 9                                   94
                      Clifton Block 8                                   89
                      Clifton Block 1                                   87
                      Clifton Block 4                                   52
                      Frere Town                                        43
                      Clifton Block 7                                   40
                      Clifton Block 5                                   35
                      Gizri                                             21
                      Clifton Block 3                                   11
                      Clifton Block 6                                   11
DHA Defence           Phase 8                                         2241
                      Phase 6                                          914
                      Phase 5                                          427
                      Phase 7                                          296
                      Phase 4                                          168
                      Phase 7 Extension                                147
                      Phase 2 Extension                                 69
                      Phase 1                                           65
                      Phase 2                                           54
                      Phase 5 Extension                                 21
                      Phase 8 Extension                                 12
F.B. Area             Block 21                                          41
Federal B Area        Block 10                                          75
                      Block 12                                          54
                      Block 13                                          41
                      Block 11                                          29
                      Block 14                                          23
                      Block 16                                          19
                      Block 9                                           19
                      Block 15                                          18
                      Block 8                                           18
                      Block 19                                          17
                      Block 6                                           12
                      Block 7                                           11
                      Block 20                                          10
                      Shahrah-E-Pakistan                                10
Gadap                 Gulshan-E-Maymar                                 468
                      Surjani Town                                     273
                      Memon Goth                                        55
Gulistan-e-Jauhar     Block 15                                         196
                      Block 14                                         152
                      Block 13                                         133
                      Block 18                                         132
                      Block 7                                          124
                      Block 3A                                         119
                      Block 12                                         117
                      Block 17                                         114
                      Block 2                                           91
                      Block 19                                          75
                      Block 16                                          72
                      Block 3                                           57
                      Block 1                                           39
                      Block 10                                          39
                      Askari 4                                          34
                      Block 11                                          33
                      Block 20                                          33
                      Block 4                                           32
                      Block 5                                           24
                      Block 16A                                         21
                      Block 9                                           14
                      Block 8                                           12
                      Safoora Goth                                       8
                      Block 6                                            4
Gulshan-e-Iqbal Town  Block 10A                                        454
                      Block 1                                          194
                      Bahadurabad                                      121
                      Block 2                                          110
                      Block 4                                          105
                      Block 17                                         100
                      Block 7                                           91
                      Kda Scheme 1                                      87
                      Block 5                                           84
                      Block 13D2                                        77
                      Block 13D1                                        65
                      Block 13-C                                        61
                      Dhoraji Colony                                    59
                      Block 13D                                         58
                      Block 6                                           57
                      Sharfabad                                         47
                      Block 13A                                         41
                      Block 13C                                         39
                      Block 3                                           39
                      Block 11                                          34
                      Block 13D3                                        32
                      Block 13B                                         25
                      Block 16                                          23
                      Block 10                                          21
                      Mohammad Ali Society                              18
                      Block 19                                          17
                      Block 9                                           17
                      Adamjee Nagar                                     16
                      Block 14                                          16
                      Cp Barar Society, Gulshan-E-Iqbal Town            14
                      National Stadium Colony                           14
                      Block 21                                          13
                      Kda Scheme 1 Extension                            11
                      Block 13                                          10
Jamshed Town          Pechs                                            284
                      Shaheed Millat Road                              179
                      Khalid Bin Walid Road                            124
                      Jamshed Road                                      61
                      Karachi Administration Employees Society          46
                      Smchs - Sindhi Muslim Society                     45
                      Tariq Road                                        39
                      Amir Khusro                                       36
                      Garden East                                       34
                      Amil Colony                                       29
                      Hill Park                                         27
                      Soldier Bazar                                     22
                      Parsi Colony                                      21
                      Mehmoodabad                                       19
                      Cosmopolitan Society                              17
                      Shahra-E-Qaideen                                  14
                      Defence Skyline, Shaheed-E-Millat Expressway      12
                      Muslimabad Society                                12
Karsaz                Navy Housing Scheme Karsaz                       131
Korangi               Allahwala Town                                   113
                      Korangi Industrial Area                           23
                      Kda Employees Society                             16
                      Qayyumabad                                        16
Malir                 Falcon Complex New Malir                         516
                      Falaknaz                                         118
                      Model Colony                                      96
                      Malir Link To Super Highway                       83
                      Airport                                           48
                      Saima Projects                                    37
                      Jamia Millia Road                                 20
                      Golden Town                                       16
                      Malir Town Residency                              13
Malir Cantt           Askari 5                                         626
                      Askari 6                                         585
                      Dohs Phase 1                                      51
                      Dohs Phase 2                                      11
Naya Nazimabad        Block A                                           95
                      Block C                                           87
                      Block D                                           68
                      Block B                                           67
                      Block M                                           23
Nazimabad             Nazimabad 4                                       22
                      Nazimabad 3                                       20
                      Nazimabad 5                                        9
                      Nazimabad 1                                        8
                      Nazimabad 2                                        5
North Karachi         Buffer Zone                                      105
                      North Karachi Sector 11                           80
                      North Karachi Sector 5                            49
                      North Karachi Sector 7                            38
                      North Karachi Sector 9                            26
                      North Karachi Sector 10                           14
                      North Karachi Sector 8                            14
                      New Karachi                                       10
North Nazimabad       Block F                                          183
                      Block H                                          131
                      Block L                                          120
                      Block N                                          118
                      Block B                                           83
                      Block M                                           52
                      Block K                                           51
                      Block A                                           50
                      Shadman                                           48
                      Block D                                           45
                      Block J                                           37
                      Block I                                           34
                      Block G                                           32
                      Block C                                           12
Scheme 33             Sector 35-A                                      312
                      Sector 47                                        272
                      Sector 40                                        240
                      Saadi Garden                                     173
                      Punjabi Saudagar Society                         156
                      Sector 44                                        147
                      Sector 34-A                                      124
                      Sector 16-A                                      118
                      Sector 17-A                                      114
                      Sector 18-A                                      114
                      Falaknaz                                         110
                      Sector 29                                        101
                      Sector 36-A                                      101
                      Sector 15-A                                       89
                      Sector 19-A                                       89
                      Meerut Society                                    57
                      Saadi Road                                        57
                      Sector 51-A                                       52
                      Sector 43-A                                       50
                      Sector 25-B                                       33
                      Sector 38-A                                       28
                      Sector 42-A                                       28
                      Sector 52-A                                       28
                      Sector 18-C                                       25
                      Sector 30                                         25
                      Sector 20-A                                       22
                      Sector 24-A                                       22
                      Sector 24-B                                       20
                      Sector 22-A                                       18
                      Gulshan-e-Usman Housing Society                   17
                      Sector 48-A                                       13
                      Yousaf Goth                                       11
                      Sector 17-B                                       10
                      Sector 45-A                                       10
Shah Faisal           Gohar Green City Cluster                          42
                      Saima Luxury Belt                                 33
                      Shamsi / Al-Falah Belt                            27
                      Green Town / Rafah-E-Aam Belt                     24
                      Falcon Complex Faisal                             14
Super Highway         Saima Villas                                      72
                      Rabia Enclave                                      9
                      Oasis Park Residencia                              6
Name: count, dtype: int64

In [318]:
df["sub_location_original"] = df["sub_location"]

df.loc[
    df["location"].eq("Gulshan-e-Iqbal Town") &
    df["sub_location"].str.match(r"^Block ", na=False),
    "sub_location"
] = "Gulshan-e-Iqbal " + df["sub_location"]

df.loc[
    df["location"].eq("Gulistan-e-Jauhar") &
    df["sub_location"].str.match(r"^Block ", na=False),
    "sub_location"
] = "Gulistan-e-Jauhar " + df["sub_location"]

df.loc[
    df["location"].eq("Federal B Area") &
    df["sub_location"].str.match(r"^Block ", na=False),
    "sub_location"
] = "Federal B Area " + df["sub_location"]

df.loc[
    df["location"].eq("North Nazimabad") &
    df["sub_location"].str.match(r"^Block ", na=False),
    "sub_location"
] = "North Nazimabad " + df["sub_location"]

df.loc[
    df["location"].eq("Naya Nazimabad") &
    df["sub_location"].str.match(r"^Block ", na=False),
    "sub_location"
] = "Naya Nazimabad " + df["sub_location"]

In [319]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Precinct 2                                       145
                      Precinct 12                                      130
                      Bahria Sports City                               128
                      Bahria Apartments                                120
                      Precinct 8                                        94
                      Precinct 10A                                      92
                      Private High-Rises                                92
                      Precinct 11A                                      85
                      Precinct 31                                       84
                      Bahria Paradise                                   76
                      Precinct 11B                                      74
                      Precinct 1                                        70
                      Precinct 10B                                      68
                      Precinct 9                                        65
                      Precinct 6                                        63
                      Precinct 27                                       61
                      Bahria Heights                                    57
                      Precinct 4                                        49
                      Precinct 16                                       37
                      Precinct 19                                       34
                      Precinct 17                                       26
                      Precinct 15                                       22
                      Precinct 7                                        14
                      Precinct 18                                        5
Bin Qasim Town        Mateen Complex                                    34
Clifton               Clifton Block 2                                  160
                      Bath Island                                      128
                      Clifton Block 9                                   94
                      Clifton Block 8                                   89
                      Clifton Block 1                                   87
                      Clifton Block 4                                   52
                      Frere Town                                        43
                      Clifton Block 7                                   40
                      Clifton Block 5                                   35
                      Gizri                                             21
                      Clifton Block 3                                   11
                      Clifton Block 6                                   11
DHA Defence           Phase 8                                         2241
                      Phase 6                                          914
                      Phase 5                                          427
                      Phase 7                                          296
                      Phase 4                                          168
                      Phase 7 Extension                                147
                      Phase 2 Extension                                 69
                      Phase 1                                           65
                      Phase 2                                           54
                      Phase 5 Extension                                 21
                      Phase 8 Extension                                 12
Federal B Area        Federal B Area Block 10                           75
                      Federal B Area Block 12                           54
                      F.B. Area Block 21                                41
                      Federal B Area Block 13                           41
                      Federal B Area Block 11                           29
                      Federal B Area Block 14                           23
                      Federal B Area Block 16                           19
                      Federal B Area Block 9                            19
                      Federal B Area Block 15                           18
                      Federal B Area Block 8                            18
                      Federal B Area Block 19                           17
                      Federal B Area Block 6                            12
                      Federal B Area Block 7                            11
                      Federal B Area Block 20                           10
                      Shahrah-E-Pakistan                                10
Gadap                 Gulshan-E-Maymar                                 468
                      Surjani Town                                     273
                      Memon Goth                                        55
Gulistan-e-Jauhar     Gulistan-e-Jauhar Block 15                       196
                      Gulistan-e-Jauhar Block 14                       152
                      Gulistan-e-Jauhar Block 13                       133
                      Gulistan-e-Jauhar Block 18                       132
                      Gulistan-e-Jauhar Block 7                        124
                      Gulistan-e-Jauhar Block 3A                       119
                      Gulistan-e-Jauhar Block 12                       117
                      Gulistan-e-Jauhar Block 17                       114
                      Gulistan-e-Jauhar Block 2                         91
                      Gulistan-e-Jauhar Block 19                        75
                      Gulistan-e-Jauhar Block 16                        72
                      Gulistan-e-Jauhar Block 3                         57
                      Gulistan-e-Jauhar Block 1                         39
                      Gulistan-e-Jauhar Block 10                        39
                      Askari 4                                          34
                      Gulistan-e-Jauhar Block 11                        33
                      Gulistan-e-Jauhar Block 20                        33
                      Gulistan-e-Jauhar Block 4                         32
                      Gulistan-e-Jauhar Block 5                         24
                      Gulistan-e-Jauhar Block 16A                       21
                      Gulistan-e-Jauhar Block 9                         14
                      Gulistan-e-Jauhar Block 8                         12
                      Safoora Goth                                       8
                      Gulistan-e-Jauhar Block 6                          4
Gulshan-e-Iqbal Town  Gulshan-e-Iqbal Block 10A                        454
                      Gulshan-e-Iqbal Block 1                          194
                      Bahadurabad                                      121
                      Gulshan-e-Iqbal Block 2                          110
                      Gulshan-e-Iqbal Block 4                          105
                      Gulshan-e-Iqbal Block 17                         100
                      Gulshan-e-Iqbal Block 7                           91
                      Kda Scheme 1                                      87
                      Gulshan-e-Iqbal Block 5                           84
                      Gulshan-e-Iqbal Block 13D2                        77
                      Gulshan-e-Iqbal Block 13D1                        65
                      Gulshan-e-Iqbal Block 13-C                        61
                      Dhoraji Colony                                    59
                      Gulshan-e-Iqbal Block 13D                         58
                      Gulshan-e-Iqbal Block 6                           57
                      Sharfabad                                         47
                      Gulshan-e-Iqbal Block 13A                         41
                      Gulshan-e-Iqbal Block 13C                         39
                      Gulshan-e-Iqbal Block 3                           39
                      Gulshan-e-Iqbal Block 11                          34
                      Gulshan-e-Iqbal Block 13D3                        32
                      Gulshan-e-Iqbal Block 13B                         25
                      Gulshan-e-Iqbal Block 16                          23
                      Gulshan-e-Iqbal Block 10                          21
                      Mohammad Ali Society                              18
                      Gulshan-e-Iqbal Block 19                          17
                      Gulshan-e-Iqbal Block 9                           17
                      Adamjee Nagar                                     16
                      Gulshan-e-Iqbal Block 14                          16
                      Cp Barar Society, Gulshan-E-Iqbal Town            14
                      National Stadium Colony                           14
                      Gulshan-e-Iqbal Block 21                          13
                      Kda Scheme 1 Extension                            11
                      Gulshan-e-Iqbal Block 13                          10
Jamshed Town          Pechs                                            284
                      Shaheed Millat Road                              179
                      Khalid Bin Walid Road                            124
                      Jamshed Road                                      61
                      Karachi Administration Employees Society          46
                      Smchs - Sindhi Muslim Society                     45
                      Tariq Road                                        39
                      Amir Khusro                                       36
                      Garden East                                       34
                      Amil Colony                                       29
                      Hill Park                                         27
                      Soldier Bazar                                     22
                      Parsi Colony                                      21
                      Mehmoodabad                                       19
                      Cosmopolitan Society                              17
                      Shahra-E-Qaideen                                  14
                      Defence Skyline, Shaheed-E-Millat Expressway      12
                      Muslimabad Society                                12
Karsaz                Navy Housing Scheme Karsaz                       131
Korangi               Allahwala Town                                   113
                      Korangi Industrial Area                           23
                      Kda Employees Society                             16
                      Qayyumabad                                        16
Malir                 Falcon Complex New Malir                         516
                      Falaknaz                                         118
                      Model Colony                                      96
                      Malir Link To Super Highway                       83
                      Airport                                           48
                      Saima Projects                                    37
                      Jamia Millia Road                                 20
                      Golden Town                                       16
                      Malir Town Residency                              13
Malir Cantt           Askari 5                                         626
                      Askari 6                                         585
                      Dohs Phase 1                                      51
                      Dohs Phase 2                                      11
Naya Nazimabad        Naya Nazimabad Block A                            95
                      Naya Nazimabad Block C                            87
                      Naya Nazimabad Block D                            68
                      Naya Nazimabad Block B                            67
                      Naya Nazimabad Block M                            23
Nazimabad             Nazimabad 4                                       22
                      Nazimabad 3                                       20
                      Nazimabad 5                                        9
                      Nazimabad 1                                        8
                      Nazimabad 2                                        5
North Karachi         Buffer Zone                                      105
                      North Karachi Sector 11                           80
                      North Karachi Sector 5                            49
                      North Karachi Sector 7                            38
                      North Karachi Sector 9                            26
                      North Karachi Sector 10                           14
                      North Karachi Sector 8                            14
                      New Karachi                                       10
North Nazimabad       North Nazimabad Block F                          183
                      North Nazimabad Block H                          131
                      North Nazimabad Block L                          120
                      North Nazimabad Block N                          118
                      North Nazimabad Block B                           83
                      North Nazimabad Block M                           52
                      North Nazimabad Block K                           51
                      North Nazimabad Block A                           50
                      Shadman                                           48
                      North Nazimabad Block D                           45
                      North Nazimabad Block J                           37
                      North Nazimabad Block I                           34
                      North Nazimabad Block G                           32
                      North Nazimabad Block C                           12
Scheme 33             Sector 35-A                                      312
                      Sector 47                                        272
                      Sector 40                                        240
                      Saadi Garden                                     173
                      Punjabi Saudagar Society                         156
                      Sector 44                                        147
                      Sector 34-A                                      124
                      Sector 16-A                                      118
                      Sector 17-A                                      114
                      Sector 18-A                                      114
                      Falaknaz                                         110
                      Sector 29                                        101
                      Sector 36-A                                      101
                      Sector 15-A                                       89
                      Sector 19-A                                       89
                      Meerut Society                                    57
                      Saadi Road                                        57
                      Sector 51-A                                       52
                      Sector 43-A                                       50
                      Sector 25-B                                       33
                      Sector 38-A                                       28
                      Sector 42-A                                       28
                      Sector 52-A                                       28
                      Sector 18-C                                       25
                      Sector 30                                         25
                      Sector 20-A                                       22
                      Sector 24-A                                       22
                      Sector 24-B                                       20
                      Sector 22-A                                       18
                      Gulshan-e-Usman Housing Society                   17
                      Sector 48-A                                       13
                      Yousaf Goth                                       11
                      Sector 17-B                                       10
                      Sector 45-A                                       10
Shah Faisal           Gohar Green City Cluster                          42
                      Saima Luxury Belt                                 33
                      Shamsi / Al-Falah Belt                            27
                      Green Town / Rafah-E-Aam Belt                     24
                      Falcon Complex Faisal                             14
Super Highway         Saima Villas                                      72
                      Rabia Enclave                                      9
                      Oasis Park Residencia                              6
Name: count, dtype: int64

In [317]:
# This section handles Rename F.B. Area To Federal B Area.df.loc[
    df["location"].eq("F.B. Area"),
    "location"
] = "Federal B Area"

(20237, 30)