In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [127]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [4]:
df=pd.read_csv('karachi_properties_outlier_treated.csv')

In [5]:
df.shape

(20479, 29)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20479 entries, 0 to 20478
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20479 non-null  object
 1   address             20479 non-null  object
 2   location            20479 non-null  object
 3   sub_location        18297 non-null  object
 4   price               20479 non-null  float64
 5   price_crore         20479 non-null  float64
 6   price_per_sqft      20479 non-null  float64
 7   area                20479 non-null  float64
 8   bedrooms            20479 non-null  int64
 9   bathrooms           20479 non-null  int64
 10  kitchen             20447 non-null  float64
 11  floor               3473 non-null   float64
 12  total_floors        9617 non-null   float64
 13  parking             20385 non-null  float64
 14  elevator            20479 non-null  int64
 15  servant_quarters    20479 non-null  float64
 16  electricity_backup  20479 non-null  int64
 17  furnished           20479 non-null  int64
 18  completion_year     10867 non-null  float64
 19  property_type       20479 non-null  object
 20  property_age        10867 non-null  float64
 21  age_category        10867 non-null  object
 22  parking_score       20479 non-null  int64
 23  area_per_bedroom    20479 non-null  float64
 24  district            20094 non-null  object
 25  sub_location_type   18289 non-null  object
 26  location_score      20131 non-null  float64
 27  sub_location_score  18297 non-null  float64
 28  expected_floors     1624 non-null   float64
dtypes: float64(15), int64(6), object(8)
memory usage: 4.5+ MB

In [7]:
df[df['sub_location'].isnull()]['property_name'].value_counts().index

Index(['flat for sale', 'house for sale',
       'leased bank loan applicable brand new flat also available for sale',
       '1 bed lounge apartment for sale | ready to move | opposite fast university | national highway',
       'brand new apartment available for sale',
       'apartment available for sale', 'apartment for sale',
       'brand new house for sale', 'brand new bungalow for sale',
       'bungalow for sale',
       ...
       'bank loan not applicable 2 bed dd apartment for sale in mateen complex | main national highway | apartments for sale',
       'two unit bungalow available for sale',
       'remco tower 4bed drawing for sale ultra luxury flat. modern interior',
       'prime location house of 1250 square feet in naya nazimabad for sale',
       'brand new town house for sale',
       'flat for sale in sawera enclave (a project of ok estate & builders)',
       'get in touch now to buy a flat in gulshan-e-iqbal',
       'prime location 1180 square feet spacious flat is available in gulzar-e-hijri for sale',
       'chance deal | 4 bed luxury apartment for sale',
       'flat for sale corner'],
      dtype='object', name='property_name', length=1977)

In [8]:
for item in df[df['sub_location'].isnull()]['property_name'].value_counts().index.tolist():
    print(item)

flat for sale
house for sale
leased bank loan applicable brand new flat also available for sale
1 bed lounge apartment for sale | ready to move | opposite fast university | national highway
brand new apartment available for sale
apartment available for sale
apartment for sale
brand new house for sale
brand new bungalow for sale
bungalow for sale
house available for sale
2 bed lounge apartment for sale in mateen complex ready to move main national highway
brand new flat is for sale
located in the heart of scheme 33 gulshan-e-maymar, rainbow twin tower
prime location 1250 square feet flat for sale in naya nazimabad
brand new houses for sale
leased bank loan applicable brand new flat available for sale
beautiful apartment available for sale
prime location 120 square yards house for sale in naya nazimabad
prime location flat for sale
(direct owner deal)
brand new house available for sale
beautiful apartment for sale
brand new project burj-ul-harmain at main safoora chowrangi
flat available for sale in defense view society karachi
2 bed lounge apartment for sale in mateen complex | ready to move | main national highway
prime location affordable house for sale in naya nazimabad
get in touch now to buy a prime location flat in naya nazimabad
fully renovated seaview apartment second floor available for sale
120 yards one unit banglow block a
silver sands tower 2 bedrooms apartment
flat available for booking in sawera grand enclave
brand new duplex apartment available for sale
2 rooms apartment for sale | ready to move | opposite fast university | national highway | mateen complex
apartment is available for sale
main shahrah-e-faisal facing 2 bed apartment for sale | malir-15 | approved project
350 square yard house is available for sale
prime location ideal house for sale in naya nazimabad
prime location house in naya nazimabad for sale
prime location flat for sale in naya nazimabad naya nazimabad
2 bed dd apartment for sell in naya nazimabad globe residency
*2 bed lounge flat for sale in country comfort, gulzar e hijri scheme 33*
brand new houses for sale purpose
grey structure villa for sale in bahria town karachi lowest price!
a prime location 160 square yards house has landed on market in naya nazimabad of naya nazimabad
spacious 5 bedroom one-unit ruby villa hampstead villas dha city
this is your chance to buy prime location house in naya nazimabad naya nazimabad
flat available for sale bakshi tower in shahra-e-faisal karachi
invest in karachis next landmark booking now on main tipu sultan road
brand new apartment sale
brand new flat in brand new building (ideal for bank loan applicants)
installment based flats is available for sale in scheme 33
3 bed luxury apartment available in easy monthly installment at most prime location of nazimabad
fully renovated seaview apartment ground floor gf-2 available for sale
prime location 1750 square feet flat for sale in naya nazimabad
ud tower 2 bed lounge yaseenabad flat
luxurious 3-bedroom apartment for sale near aladin park secure boundary wall project
ideal flat is available for sale in karachi
4 bed dd apartment for sale in chapal navinta saddar karachi
old house for sale
prime location naya nazimabad flat sized 1500 square feet for sale
airport residency 2 room apartment
reserve a centrally located house in nhs mauripur
120 yards one unit bungalow block a
3 bed dd flat available for sale in gulistan e jauhar
beautiful double storey house for sale block 7, gulshan-e-iqbal
bank loan applicable prime 2-bed dd apartment for sale rabia pearl apartments
3 bed dd flat available for sale
3 bed dd flat for sale
naya nazimabad luxurious apartment | easy instalment plan | 4 rooms + 2 bed d/d + park face + corner + masjid facing + globe residency + most premium location
house for sale in karachi
500sq yd luxury villa for sale. 2km from entrance of btk. 6 bed ddl 2 kitchens
affordable prime location flat available for sale in naya nazimabad
leased 2 bed drawing lounge apartment available for sale shahfaisal colony #1
get in touch now to buy a prime location house in bahria town karachi
modern life style project flat sima square
house is available for sale
exquisite 3 bedroom one-unit luxury topaz villa hampstead villas dha city karachi
3 bed dd for sale in mateen complex main national highway
3 bed dd apartment available for sale
spacious 2 bed d. d flat available for sale
get in touch now to buy a flat in civil lines
house available for sale brand new 160 square yard
your search for prime location flat in naya nazimabad ends here
1150 square feet flat in sohni serenity executive apartments is available for sale
direct owner 240 yards ground plus two house
airport residency 4 & 5 room apartment
3 bed dd flat available for sale in gulshan e iqbal block-1
bungalow available for sale
modern luxury apartment with premium amenities also available on installments
stunning prime location flat is available for sale in scheme 33
3 bed dd apartment for sale
350 sq. yards | corner | east open | well-maintained house
rafi premier residency fully leased 3dd apartment for sale ideal for families, bank loan, financers & investors
prime location 1250 square feet flat for sale available in naya nazimabad
prime location house of 120 square yards in naya nazimabad for sale
4 bedroom luxury sapphire villa with private basement hampstead villas
smart living: luxury 4 bed dual-living emerald villa in dha city karachi hampstead villas karachi
3 bed dd apartment for sale in mateen complex | main national highway | oppo. fast national university
naya nazimabad peace apartment | 6.5 years easy instalment plan | 5 rooms + 3 bed d/d + front facing + extended terrace + corner + masjid facing + boulevard + com 41 + most premium location
flat for sale on main tipu sultan road
nhs mauripur house sized 120 square yards
unparalleled luxury living at nhs zamzama karachi your dream lifestyle awaits! house for sale
end your search for prime location flat here and sale now
super luxury apartment for sale
ready to buy a prime location house in naya nazimabad naya nazimabad
naya nazimabad peace apartment | 6.5 years easy instalment plan | 5 rooms + 3 bed d/d + front facing + corner + masjid facing + boulevard + com 41 + most premium location
zayan victoria 2bed lounge flat available for sale on installment
sawera enclave a luxurious project by ok estate & builders flat for sale
rabia patel 2 bed lounge abul hassan isphani road well maintained 3rd floor
bungalow for available on sell gulistan. e. jouhar
fully renovated seaview apartment available for sale
ideal prime location flat for sale in karachi - hyderabad motorway
bank loan applicable 2 bed lounge flat in shaz residency 750 sqft for sale
120 square yards luxurious villa
120 square yards house in only rs. 30000000 for sale
buy a flat of 1800 square feet in gulistan-e-jauhar
shahraefaisal main duplex apartment for sale ideal location
3 bed drawing flat for sale in ciivl lines
installment based flat is available for sale in scheme 33
bran new building 3 bed rooms apartment opposite shaheen complex near to pc hotel
3bed dd leased apartment available for sale
saadi garden block 1 beautiful house for sale ground flore
unparalleled luxury living at nhs zamzama, karachi your dream lifestyle awaits!
chance deal luxurious beautiful independent house 500 sq yards for sale
in shah faisal town 540 square feet flat for sale
leased bank loan applicable 2 bed drawing lounge apartment available for sale scheme 33
3 bed dd flat for sale in scheme 33 on bank loan
leased bank loan applicable brand new luxury flat also available for sale
sale flat jamshed road new ma jinnah road
2 bed dd apartment for sale in kings residency gulistan e jauhar block 13
brand new double story designer house available for sale
ultra premium project,ultra modern apartments burj-ul-harmain
ground plus 2, 120sqyds house available for sale in federal b area block 3 near meena bazar opposite hef school best for commercial plus residential purpose ideal location
naya nazimabad com 50 ashaab builders stadium view residencia main road facing apartments
stunning and affordable house available for sale in gulshan-e-iqbal - block 15
luxury apartments for sale on installments globe residency naya nazimabad
brand new house ground plus 1 sector 10 near kalyana hal
brand new apartment/flat in naya nazimabad fl-07 (corner / west open / park facing)
demolished house for sale at prime location of north nazimabad
flat for sale ground floor 2 bed lounge
sawera enclave, a project by ok estate & builders.
highly-desirable prime location 120 square yards house available in scheme 33
flat for sale 2 bed lounge
sawera enclave, a luxurious project of ok estate & builders flat for sale
double story house available for sale
fully furnished ready-to-move homes in dha city karachi - aaryans homes
120 sq. yards house for sale in naya nazimabad block b | rental income property | 2 bed dd planning
120 yards corner park face one unit bungalow for sale
livable 200 sq yd house for sale in block r north nazimabad
dadabhoy apartments proper 4 bed with big lounge apartment for sale
2 bed dd for sale in garden west ( ana grand palace)
a perfect 2 bed and 3-bed apartments by sawera groups
4 bed dd flat for sale on tipu sultan road brand new project roshan tower
500 yards brand new villa for sale in precinct 4 near olives park 6 bed villa with half basement classical finishing huge kitchen bahria town karachi
ideally located flat of 3275 square feet is available for sale in karachi
4 rooms luxury apartment in naya nazimabad ideal family living
brand new 2 and 3 bed room apartment available for sale
apartment could be your dream when you can spend your life without tension servant quarter facility is also available
prime location house for sale in federal b area
my new house ready to move
1 bed + 1 lounch+(seprate kitchen) flat for sale in shafi excellency apartmenr north khi
golden chance 2 room flat for sale in ghouri classic first floor new project lift stand by generator car parking sector 11a north karachi
brand new 160 sq. yards one unit bungalow for sale | 60 ft road | prime location | block d, naya nazimabad
spacious bungalow brand new 400 yard proper 2 unit block 14 gulistan e jauhar
luxurious 3-bedroom apartment with private pool in clifton block 9 near ocean mall, karachi
flat for sale 2 bed lounge near shahrah e faisal
a centrally located flat is available for sale in karachi
120 square yard bungalow block c
bank loan applicable luxurious flat available for sale on main rashid minhas road gulshan e iqbal block 10a.
unoccupied house of 120 square yards is available for sale in shah faisal town
237 yards house for sale
brand new ground+1 house available for sale in gulistan e jauhar block 12
saima presidency 1st floor duplex for sale
1 bed + 1 lounch flat for sale in new building al-ghafoor sky tower sector 11 a north karachi
150 sq yard rufi fountain house for sale in gulistan e jauhar block 19
vip block 15 brand new 240 yds proper double storey bungalow near continental bakeri
blue sky h block near essa lab
brand new house for sale builder transfer and condition ,corner, west open new possession
investors should sale this house located ideally in bahria town karachi
main shahrah-e-faisal facing 3 rooms, rental value 30000 no commission flat for sale no bank loan only cash last unit
shaz residency flat for sale
1600 sqft 3 bed flat in new building located on main tipu sultan road
270 square yards house for sale in beautiful malir cantonment
prime location flat for sale in rs. 26750000
prime location 2800 square feet flat in only rs 95,000,000
1st floor flat 2 bed drawing dining leas 35 lac
120 sq yard 1st floor corner flat
looking for a house in karachi
reserve a apartment now in naya nazimabad
brand new corner 2 bed drawing tv lounge
400 sq. yd bungalow for sale in gulistan-e-jauhar vip block
80 yard ground plus 3 house for sale in defence view phase 2
1000 square feet flat is available in affordable price in jamshed town
your dream prime location 120 square yards house is available in naya nazimabad
spacious single story house for sale al-mehran cooperative housing society
luxury living & business opportunities: 2 & 3 bedroom apartments & showroom spaces in a secure boundary wall community
brand new 2 bedroom apartment in towers available
fariha excellency 4 bed drawing dining road facing west open next to saima jinnah icon mall
luxury 3 bedrooms 2100 square feet apartment for sale
flat for sale lease 750 square feet
zamzam tower flat for sale
prime location 120 square yards house for sale in naya nazimabad naya nazimabad
get in touch now to buy a prime location 1500 square feet flat in grey stylux residences karachi
peace apartment com 35 # pre booking discount
newly constructed flat is available for sale in north nazimabad block t
reserve a flat now in garden west
200 sqyds west open ground plus one brand new house for sale
band new house for sale in gulistan e jauhar block 3
house for sale in north nazimabad block w
400 yard bungalow townhouse like brand new condition basement g+1
highly-desirable 120 square yards house available in port qasim al jannan society
highly-coveted facing park 400 square yards house is available in north nazimabad for sale
shaez 1650 sq feet apartment for sale
get in touch now to buy a prime location flat in naya nazimabad naya nazimabad
120 yards house for sale gulshan e azeem, karachi
tipu sultan road remmco tower 3 bed dd flat for sale
silver sand m block 2 bed dd flat road face
attap city
2000 square feet flat ideally situated in clifton block 8
120 sq. yards brand new house available for sale in naya nazimabad block c and d
240 sq. yds. luxurious villa for sale
prime location flat of 1500 square feet is available for sale in naya nazimabad, naya nazimabad
new flat for sale airport opposite
well maintained flat available for sale !!!
prime location flat of 1850 square feet available for sale in saddar
reserve a flat of 1000 square feet now in north nazimabad
flat for sale naya naximabad globe residency
prime location 800 square feet flat available for sale in country heights
abuzar ghaffari phase 2 gulshan e maymar 180 sq yrd leased house available
idyllic flat available in civil lines for sale
reserve a centrally located prime location flat in north karachi
brand new apartment west open available
avanti terrace apartment for sale
dha city villa for booking
120 yards one unit house for sale block a
gulshan-e-iqbal block 8 600 yard bungalow extremely neat and clean available for sale
spacious flat is available in kesc housing society for sale
3 bed dd saima square one flat for sale in gulshan e iqbal block 10a
an ideal location flat for small family with ideal facilities
very well maintained 2 bed drawing and dinning flat available for sale in gulzar e hijri scheme 33
flat for sale fl-04
120 yards park face west open block d
240 sq yard house for sale in gulshan e iqbal block 11
get in touch now to buy a prime location 1249 square feet flat in naya nazimabad
flat for sale 3 bed dd firdous residency block 10 gulistan e jauher
500 yards, g+1, grey structure, precinct 20, golf, near mosque, bahria school, bahria town karachi
3 bedroom drawing lounge flat available for sale at daniyal residency opp hansa society
in navy housing scheme zamzama house for sale sized 350 square yards
prime location 1250 square feet flat for sale in naya nazimabad naya nazimabad in only rs. 16000000
outclass renovated ground floor flat for sale
iqbal plaza 3rd floor corner leas 2bed lounge flat for sale
3 bedroom lounge available in f l 7
prime location 1260 square feet flat available for sale in naya nazimabad
flat available for booking in sawera grand enclave highway
best for u 4 room leased flat for sale in mahad residency new project lift stand by generator car parking sector 11a north karachi
sea view fully renovated like a brand new apartment
house in dha city - sector 14b sized 125 square yards is available
zoramin residency 120 yards one unit bungalow wide road facing builder design
2 bed dd neat & clean apartment
3 bed dd flat available for sale prime location
highly-coveted prime location 2189 square feet flat is available in gulshan-e-iqbal town for sale
best location h block house
globe residency apartments for sale comfort, class & convenience in naya nazimabad!
gulshan-e-iqbal flat for sale
2 bed lounge flat for sale daniyal tower - leased flat, bank loan applicable
well maintained ground+1 bungalow available for sale in gulistan e jauhar block 15
want to buy a prime location flat in garden west?
hampstead villas dha city: flagship 300 sq. yds luxury living via malir expressway
available for sell one. bed lounge apartment in lakhani fantasia with roof  bank loan applicable
used & well-maintained 120 sq. yards g+2 house for sale
3 bedroom lounge apartment for sale fl7
flat for sale in civil lines civil lines is available
prime location 850 square feet flat for sale in rs. 8500000 only
jori flats for sale
2 bed furnished bahria apartment available for sale well designed and we'll maintained in bahria town karachi
in naya nazimabad you can find the perfect prime location house for sale
300 yard brand new bungalow
600 yard bungalow on main tipu sultan road in kda sch 1 for sale
3 bed dd al khizra height flat for sale in gulistan e jauhar block 3a
prime location flat of 2500 square feet is available in contemporary neighborhood of civil lines
in tulip tower, a zero meter 3500 square feet flat is available for sale in tulip tower, in scheme 33 karachi
120 sq. yards beautiful house for sale in block d, naya nazimabad best family location
5 rooms super luxury new corner road side ready to move apartment for sale in cantt view lodges
prime location 390 square feet flat is available in north town residency phase 1
your search for prime location house in naya nazimabad ends here
4 bedrooms apartment available for sale in ferere town, clifton
600 yards leased luxury house for sale owner built (pak-ideal housing society)
gulshan-e-iqbal block 18 350 sq yard old bungalow best for investment best chance deal resonabale price details
ary laguna dha city karachi 1 bedrooms, duplex units available on resale
beautifully constructed prime location house is available for sale in naya nazimabad
300 square yards house available for sale in dha city - sector 1
exclusive apartment projects on easy installments! in naya nazimabad
bungalow available for sale at defence view phase 1
leased bank loan applicable full tiled flooring flat also available for sale
2 & 3 bedroom apartments for sale prime location naya nazimabad karachi
120 square yards house in defence view society
complete 120 square yard house with penthouse park facing for sale
200 sq yrds maintain house for sale fb area block 18
ideal prime location house in naya nazimabad available for rs. 41500000
"experience luxury living at sawera sky tower, located near ocean mall, clifton block 9, with flexible installment plans to make your dream home a reality. "
affordable flat available for sale in saddar town
150 yards house in dha city woodlands 273k monthly book now
a palatial residence for sale in dha city karachi dha city karachi
*2 bed lounge flat for sale in asma garden, gulzar e hijri scheme 33*
bismillah center 2 bed lounch for sale boundary wall project
brand new 120 sq. yards one unit bungalow for sale in naya nazimabad block c | park facing | west open
2nd floor saima pride 5 rooms super luxury apartment boundary wall project, masjid, parking, play ground, guard & main rashid minhas road facing
prime location 900 square feet flat for sale in scheme 33 scheme 33
prime location flat in north karachi for sale
naya nazimabad block c 120 sq yard beautiful bungalow available for sale
apartment available for sale in sawera enclave.
a true 2200 square yard bungalow covers a massive ft printi deal for sprawling luxurious homes or semi-farmhouse designs

In [9]:
df['sub_location'].value_counts()

sub_location
Phase 8                                         2049
Phase 6                                          884
Askari 5                                         498
Askari 6                                         489
Falcon Complex New Malir                         449
Gulshan-E-Maymar                                 436
Gulshan-e-Iqbal Block 10A                        422
Phase 5                                          421
Sector 35-A                                      301
Phase 7                                          286
Pechs                                            268
Sector 47                                        260
Sector 40                                        235
Falaknaz                                         220
Surjani Town                                     209
Gulistan-e-Jauhar Block 15                       186
North Nazimabad Block F                          179
Shaheed Millat Road                              173
Saadi Garden                                     166
Clifton Block 2                                  159
Phase 4                                          156
Punjabi Saudagar Society                         146
Gulistan-e-Jauhar Block 14                       142
Gulshan-e-Iqbal Block 1                          141
Phase 7 Extension                                141
Gulistan-e-Jauhar Block 18                       126
Gulistan-e-Jauhar Block 13                       125
Navy Housing Scheme Karsaz                       124
Bath Island                                      122
North Nazimabad Block H                          122
Sector 34-A                                      121
Khalid Bin Walid Road                            121
Gulistan-e-Jauhar Block 7                        121
Gulistan-e-Jauhar Block 3A                       117
North Nazimabad Block L                          117
Bahadurabad                                      116
Sector 18-A                                      113
North Nazimabad Block N                          113
Sector 17-A                                      109
Sector 16-A                                      109
Sector 44                                        104
Gulistan-e-Jauhar Block 17                       103
Gulshan-e-Iqbal Block 2                          102
Gulistan-e-Jauhar Block 12                       102
Sector 29                                        100
Gulshan-e-Iqbal Block 4                          100
Allahwala Town                                    99
Sector 36-A                                       97
Gulshan-e-Iqbal Block 17                          97
Model Colony                                      96
Buffer Zone                                       95
Bahria Sports City                                93
Precinct 2                                        91
Clifton Block 9                                   90
Sector 15-A                                       89
Clifton Block 8                                   88
Gulshan-e-Iqbal Block 7                           88
Clifton Block 1                                   87
Gulistan-e-Jauhar Block 2                         86
Precinct 12                                       85
Sector 19-A                                       85
Kda Scheme 1                                      84
Malir Link To Super Highway                       82
North Nazimabad Block B                           81
North Karachi Sector 11                           76
Bahria Apartments                                 74
Gulshan-e-Iqbal Block 5                           74
Precinct 8                                        73
Naya Nazimabad Block A                            72
Gulshan-e-Iqbal Block 13D2                        70
Private High-Rises                                70
Saima Villas                                      69
Gulistan-e-Jauhar Block 16                        69
Phase 2 Extension                                 68
Naya Nazimabad Block C                            67
Gulistan-e-Jauhar Block 19                        67
Federal B Area Block 10                           65
Gulshan-e-Iqbal Block 13D1                        65
Phase 1                                           64
Jamshed Road                                      59
Precinct 11A                                      58
Gulshan-e-Iqbal Block 6                           57
Meerut Society                                    57
Dhoraji Colony                                    56
Gulistan-e-Jauhar Block 3                         56
Bahria Paradise                                   56
Precinct 31                                       54
Precinct 9                                        54
Precinct 1                                        53
North Nazimabad Block M                           52
Phase 2                                           52
Naya Nazimabad Block D                            52
Saadi Road                                        52
Gulshan-e-Iqbal Block 13D                         51
Clifton Block 4                                   51
Federal B Area Block 12                           50
Precinct 10A                                      49
Memon Goth                                        49
Airport                                           48
Naya Nazimabad Block B                            48
Precinct 11B                                      48
Sector 43-A                                       48
Sector 51-A                                       47
Sharfabad                                         46
Bahria Heights                                    45
North Nazimabad Block A                           45
Precinct 6                                        44
North Karachi Sector 5                            44
North Nazimabad Block D                           44
Shadman                                           43
Smchs - Sindhi Muslim Society                     43
Frere Town                                        43
Precinct 10B                                      42
North Nazimabad Block K                           42
Federal B Area Block 21                           41
Karachi Administration Employees Society          41
Gohar Green City Cluster                          41
Precinct 27                                       40
Dohs Phase 1                                      40
Clifton Block 7                                   40
Federal B Area Block 13                           39
Gulistan-e-Jauhar Block 1                         39
Gulshan-e-Iqbal Block 3                           39
Gulshan-e-Iqbal Block 13A                         38
Saima Projects                                    37
Gulistan-e-Jauhar Block 10                        37
Gulshan-e-Iqbal Block 13C                         37
Precinct 4                                        36
North Karachi Sector 7                            36
Tariq Road                                        35
North Nazimabad Block J                           35
North Nazimabad Block I                           34
Clifton Block 5                                   34
Gulistan-e-Jauhar Block 20                        33
Saima Luxury Belt                                 33
Sector 25-B                                       33
Amir Khusro                                       33
Gulshan-e-Iqbal Block 13D3                        32
Askari 4                                          32
Garden East                                       31
Precinct 19                                       31
Gulistan-e-Jauhar Block 4                         31
Precinct 16                                       30
Amil Colony                                       29
Gulshan-e-Iqbal Block 11                          29
Gulistan-e-Jauhar Block 11                        28
Sector 42-A                                       28
Sector 52-A                                       28
Federal B Area Block 11                           27
Shamsi / Al-Falah Belt                            26
Sector 38-A                                       26
Sector 18-C                                       25
Hill Park                                         25
Gulshan-e-Iqbal Block 13B                         24
Green Town / Rafah-E-Aam Belt                     24
North Karachi Sector 9                            24
Gulistan-e-Jauhar Block 5                         23
Gulshan-e-Iqbal Block 16                          23
Sector 24-A                                       22
Sector 20-A                                       22
Nazimabad 4                                       22
National Stadium Colony                           22
Gulshan-e-Iqbal Block 10                          21
Gizri                                             21
North Nazimabad Block G                           21
Sector 30                                         21
Phase 5 Extension                                 21
Nazimabad 3                                       20
Soldier Bazar                                     20
Parsi Colony                                      20
Gulistan-e-Jauhar Block 16A                       20
Sector 24-B                                       20
Precinct 17                                       19
Korangi Industrial Area                           19
Federal B Area Block 14                           19
Mehmoodabad                                       18
Federal B Area Block 8                            18
Sector 22-A                                       18
Federal B Area Block 9                            18
Cosmopolitan Society                              17
Precinct 15                                       17
Gulshan-e-Iqbal Block 9                           17
Gulshan-e-Usman Housing Society                   17
Gulshan-e-Iqbal Block 19                          17
Federal B Area Block 19                           17
Mohammad Ali Society                              17
Mateen Complex                                    16
Adamjee Nagar                                     16
Kda Employees Society                             16
Golden Town                                       16
Jamia Millia Road                                 16
Naya Nazimabad Block M                            16
Gulshan-e-Iqbal Block 14                          16
Gulshan-e-Iqbal Block 13-C                        15
North Karachi Sector 8                            14
North Karachi Sector 10                           14
Shahra-E-Qaideen                                  14
Federal B Area Block 16                           14
Qayyumabad                                        14
Falcon Complex Faisal                             14
Gulistan-e-Jauhar Block 9                         14
Cp Barar Society, Gulshan-E-Iqbal Town            13
Gulshan-e-Iqbal Block 21                          13
Sector 48-A                                       13
Federal B Area Block 15                           13
Muslimabad Society                                12
Phase 8 Extension                                 12
Federal B Area Block 6                            12
Defence Skyline, Shaheed-E-Millat Expressway      12
North Nazimabad Block C                           12
Clifton Block 6                                   11
Kda Scheme 1 Extension                            11
Federal B Area Block 7                            11
Dohs Phase 2                                      11
Malir Town Residency                              11
Clifton Block 3                                   11
Shahrah-E-Pakistan                                10
Sector 17-B                                       10
Gulshan-e-Iqbal Block 13                          10
Sector 45-A                                       10
Federal B Area Block 20                            9
Rabia Enclave                                      9
New Karachi                                        9
Nazimabad 5                                        8
Nazimabad 1                                        8
Safoora Goth                                       8
Precinct 7                                         7
Gulistan-e-Jauhar Block 8                          7
Oasis Park Residencia                              6
Precinct 18                                        5
Yousaf Goth                                        5
Gulistan-e-Jauhar Block 6                          4
Nazimabad 2                                        4
Name: count, dtype: int64

In [10]:
import re



sub_locations = (
    df['sub_location']
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)


sub_locations = sorted(sub_locations, key=len, reverse=True)


def extract_sub_location(property_name):
    if pd.isna(property_name):
        return np.nan

    property_name = str(property_name)

    for sub_loc in sub_locations:

        pattern = re.escape(sub_loc)


        if re.search(pattern, property_name, flags=re.IGNORECASE):
            return sub_loc

    return np.nan



mask = df['sub_location'].isna()

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'property_name']
      .apply(extract_sub_location)
)

In [11]:
df['sub_location'].isnull().sum()

np.int64(2009)

In [12]:
import re
import numpy as np
import pandas as pd

# Existing known sub-locations
sub_locations = (
    df['sub_location']
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

# Match longer names first
sub_locations = sorted(sub_locations, key=len, reverse=True)


def extract_sub_location(property_name):
    if pd.isna(property_name):
        return np.nan

    text = str(property_name)

    
    for sub_loc in sub_locations:
        pattern = re.escape(sub_loc)

        if re.search(pattern, text, flags=re.IGNORECASE):
            return sub_loc

    # --------------------------------------------------
    # 2. Extract Phase
    # Examples:
    # Phase 8
    # Phase 8 Extension
    # Phase 2
    # Phase 2 Extension
    # --------------------------------------------------
    match = re.search(
        r'\bPhase\s+\d+(?:\s+Extension)?\b',
        text,
        flags=re.IGNORECASE
    )

    if match:
        return match.group(0).strip()

    # --------------------------------------------------
    # 3. Extract Sector
    # Examples:
    # Sector 35-A
    # Sector 11
    # Sector 13D
    # Sector 24-B
    # --------------------------------------------------
    match = re.search(
        r'\bSector\s+\d+[A-Za-z]?(?:[-/][A-Za-z0-9]+)?\b',
        text,
        flags=re.IGNORECASE
    )

    if match:
        return match.group(0).strip()

    # --------------------------------------------------
    # 4. Extract Block
    # Examples:
    # Block F
    # Block 10A
    # Block 13D2
    # Block A
    # --------------------------------------------------
    match = re.search(
        r'\bBlock\s+[A-Za-z0-9]+(?:[-/][A-Za-z0-9]+)?\b',
        text,
        flags=re.IGNORECASE
    )

    if match:
        return match.group(0).strip()

    return np.nan


# Only fill missing sub_location
mask = df['sub_location'].isna()

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'property_name']
      .apply(extract_sub_location)
)

In [13]:
df.groupby('location')['sub_location'].value_counts()

location              sub_location
Bahria Town           Bahria Sports City                                94
                      Precinct 2                                        92
                      Precinct 12                                       85
                      Precinct 8                                        75
                      Bahria Apartments                                 74
                      Private High-Rises                                70
                      Precinct 11A                                      58
                      Bahria Paradise                                   56
                      Precinct 1                                        54
                      Precinct 31                                       54
                      Precinct 9                                        54
                      Precinct 10A                                      50
                      Precinct 11B                                      48
                      Bahria Heights                                    47
                      Precinct 6                                        45
                      Precinct 10B                                      42
                      Precinct 27                                       40
                      Precinct 4                                        37
                      Precinct 19                                       32
                      Precinct 16                                       30
                      Precinct 17                                       19
                      Precinct 15                                       17
                      Precinct 7                                         7
                      Precinct 18                                        5
Bin Qasim Town        Mateen Complex                                    22
                      Model Colony                                       2
                      Phase 2                                            2
                      block a                                            1
Clifton               Clifton Block 2                                  161
                      Bath Island                                      123
                      Clifton Block 9                                   92
                      Clifton Block 1                                   88
                      Clifton Block 8                                   88
                      Clifton Block 4                                   51
                      Frere Town                                        43
                      Clifton Block 7                                   40
                      Clifton Block 5                                   34
                      Gizri                                             21
                      Clifton Block 3                                   11
                      Clifton Block 6                                   11
                      Phase 8                                            1
DHA City              sector 1                                           8
                      sector 14b                                         2
                      sector 14-b                                        1
                      sector 3a                                          1
                      sector 3c                                          1
DHA Defence           Phase 8                                         2049
                      Phase 6                                          886
                      Phase 5                                          422
                      Phase 7                                          286
                      Phase 4                                          156
                      Phase 7 Extension                                141
                      Phase 2 Extension                                 68
                      Phase 1                                           64
                      Phase 2                                           52
                      Phase 5 Extension                                 21
                      Phase 8 Extension                                 12
Defence View          Phase 1                                            6
                      Phase 2                                            1
Federal B Area        Federal B Area Block 10                           65
                      Federal B Area Block 12                           50
                      Federal B Area Block 21                           41
                      Federal B Area Block 13                           39
                      Federal B Area Block 11                           27
                      Federal B Area Block 14                           19
                      Federal B Area Block 8                            18
                      Federal B Area Block 9                            18
                      Federal B Area Block 19                           17
                      Federal B Area Block 16                           14
                      Federal B Area Block 15                           13
                      Federal B Area Block 6                            12
                      Federal B Area Block 7                            11
                      Federal B Area Block 20                           10
                      Shahrah-E-Pakistan                                10
                      block 5                                            4
                      block 4                                            3
                      block 18                                           2
                      block 3                                            2
                      block 11                                           1
                      block 17                                           1
                      block 2                                            1
                      block 21                                           1
                      block 9                                            1
Gadap                 Gulshan-E-Maymar                                 436
                      Surjani Town                                     209
                      Memon Goth                                        49
Gulistan-e-Jauhar     Gulistan-e-Jauhar Block 15                       188
                      Gulistan-e-Jauhar Block 14                       148
                      Gulistan-e-Jauhar Block 18                       127
                      Gulistan-e-Jauhar Block 13                       126
                      Gulistan-e-Jauhar Block 7                        121
                      Gulistan-e-Jauhar Block 3A                       117
                      Gulistan-e-Jauhar Block 17                       103
                      Gulistan-e-Jauhar Block 12                       102
                      Gulistan-e-Jauhar Block 2                         87
                      Gulistan-e-Jauhar Block 16                        70
                      Gulistan-e-Jauhar Block 19                        69
                      Gulistan-e-Jauhar Block 3                         56
                      Gulistan-e-Jauhar Block 1                         39
                      Gulistan-e-Jauhar Block 10                        37
                      Gulistan-e-Jauhar Block 20                        33
                      Askari 4                                          32
                      Gulistan-e-Jauhar Block 4                         31
                      Gulistan-e-Jauhar Block 11                        28
                      Gulistan-e-Jauhar Block 5                         23
                      Gulistan-e-Jauhar Block 16A                       20
                      Gulistan-e-Jauhar Block 9                         14
                      block 13                                           9
                      Safoora Goth                                       8
                      Gulistan-e-Jauhar Block 8                          7
                      block 2                                            6
                      block 15                                           5
                      Gulistan-e-Jauhar Block 6                          4
                      block 16                                           4
                      block 19                                           4
                      block 3a                                           4
                      block 7                                            4
                      block 12                                           3
                      block 4                                            3
                      Mateen Complex                                     2
                      block 10                                           2
                      block 14                                           2
                      block 3                                            2
                      block 5                                            2
                      Phase 1                                            1
                      block 02                                           1
                      block 03-a                                         1
                      block 03a                                          1
                      block 04                                           1
                      block 05                                           1
                      block 1                                            1
                      block 10a                                          1
                      block 11                                           1
                      block 16-a                                         1
                      block 16a                                          1
                      block 17                                           1
                      block 9a                                           1
Gulshan-e-Iqbal Town  Gulshan-e-Iqbal Block 10A                        422
                      Gulshan-e-Iqbal Block 1                          144
                      Bahadurabad                                      116
                      Gulshan-e-Iqbal Block 2                          102
                      Gulshan-e-Iqbal Block 4                          101
                      Gulshan-e-Iqbal Block 17                          97
                      Gulshan-e-Iqbal Block 7                           88
                      Kda Scheme 1                                      84
                      Gulshan-e-Iqbal Block 5                           74
                      Gulshan-e-Iqbal Block 13D2                        70
                      Gulshan-e-Iqbal Block 13D1                        65
                      Gulshan-e-Iqbal Block 6                           57
                      Dhoraji Colony                                    56
                      Gulshan-e-Iqbal Block 13D                         52
                      Sharfabad                                         46
                      Gulshan-e-Iqbal Block 3                           39
                      Gulshan-e-Iqbal Block 13A                         38
                      Gulshan-e-Iqbal Block 13C                         37
                      Gulshan-e-Iqbal Block 13D3                        32
                      Gulshan-e-Iqbal Block 11                          29
                      Gulshan-e-Iqbal Block 13B                         24
                      Gulshan-e-Iqbal Block 16                          23
                      National Stadium Colony                           22
                      Gulshan-e-Iqbal Block 10                          21
                      Gulshan-e-Iqbal Block 19                          17
                      Gulshan-e-Iqbal Block 9                           17
                      Mohammad Ali Society                              17
                      Adamjee Nagar                                     16
                      Gulshan-e-Iqbal Block 14                          16
                      Gulshan-e-Iqbal Block 13-C                        15
                      Cp Barar Society, Gulshan-E-Iqbal Town            13
                      Gulshan-e-Iqbal Block 21                          13
                      Kda Scheme 1 Extension                            11
                      Gulshan-e-Iqbal Block 13                          10
                      block 10a                                          4
                      block 13d2                                         4
                      block 2                                            4
                      block 4                                            4
                      block 8                                            4
                      block 5                                            3
                      Hill Park                                          2
                      block 10                                           2
                      block 11                                           2
                      block 13                                           2
                      block 13d                                          2
                      block 15                                           2
                      block 18                                           2
                      block 7                                            2
                      block 13a                                          1
                      block 19                                           1
                      block 3                                            1
                      block 6                                            1
                      block a                                            1
                      block c                                            1
                      block of                                           1
Jamshed Town          Pechs                                            268
                      Shaheed Millat Road                              173
                      Khalid Bin Walid Road                            121
                      Jamshed Road                                      60
                      Smchs - Sindhi Muslim Society                     43
                      Karachi Administration Employees Society          41
                      Tariq Road                                        35
                      Amir Khusro                                       33
                      Garden East                                       31
                      Amil Colony                                       30
                      Hill Park                                         25
                      Parsi Colony                                      20
                      Soldier Bazar                                     20
                      Mehmoodabad                                       18
                      Cosmopolitan Society                              17
                      Shahra-E-Qaideen                                  14
                      Defence Skyline, Shaheed-E-Millat Expressway      12
                      Muslimabad Society                                12
Karsaz                Navy Housing Scheme Karsaz                       124
Korangi               Allahwala Town                                    99
                      Korangi Industrial Area                           19
                      Kda Employees Society                             16
                      Qayyumabad                                        14
                      Mateen Complex                                     1
Malir                 Falcon Complex New Malir                         449
                      Falaknaz                                         113
                      Model Colony                                      98
                      Malir Link To Super Highway                       82
                      Airport                                           50
                      Saima Projects                                    37
                      Golden Town                                       16
                      Jamia Millia Road                                 16
                      Malir Town Residency                              11
                      Mateen Complex                                     5
                      Shadman                                            1
Malir Cantt           Askari 5                                         499
                      Askari 6                                         490
                      Dohs Phase 1                                      40
                      Dohs Phase 2                                      11
                      Airport                                            2
                      block 7                                            2
                      block 9                                            1
                      block a                                            1
Naya Nazimabad        Naya Nazimabad Block A                            77
                      Naya Nazimabad Block C                            77
                      Naya Nazimabad Block D                            56
                      Naya Nazimabad Block B                            53
                      Naya Nazimabad Block M                            20
                      block a                                           16
                      block c                                           14
                      block d                                           10
                      Nazimabad 1                                        5
                      Nazimabad 2                                        4
                      block m                                            3
                      Nazimabad 3                                        1
                      Phase 2                                            1
                      block house                                        1
Nazimabad             Nazimabad 4                                       24
                      Nazimabad 3                                       20
                      Nazimabad 5                                        9
                      Nazimabad 1                                        8
                      Nazimabad 2                                        4
North Karachi         Buffer Zone                                       95
                      North Karachi Sector 11                           78
                      North Karachi Sector 5                            47
                      North Karachi Sector 7                            36
                      North Karachi Sector 9                            24
                      North Karachi Sector 10                           14
                      North Karachi Sector 8                            14
                      New Karachi                                        9
                      sector 11a                                         9
                      sector 10                                          2
                      sector 11                                          2
                      Phase 1                                            1

In [14]:
df.loc[
    df['sub_location'].eq('Mateen Complex'),
    'location'
] = 'Bin Qasim Town'

In [15]:
import re

mask = (
    (df['location'] == 'Gulshan-e-Iqbal Town') &
    (df['sub_location'].str.match(r'^\s*block\s+', case=False, na=False))
)

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'sub_location']
      .str.strip()
      .str.replace(r'^block\s+', 'Gulshan-e-Iqbal Block ', regex=True, case=False)
)

In [16]:
gulshan_mapping = {
    'Gulshan-e-Iqbal Block 10a': 'Gulshan-e-Iqbal Block 10A',
    'Gulshan-e-Iqbal Block 13d2': 'Gulshan-e-Iqbal Block 13D2',
    'Gulshan-e-Iqbal Block 13d': 'Gulshan-e-Iqbal Block 13D',
    'Gulshan-e-Iqbal Block 15': 'Gulshan-e-Iqbal Block 15',
    'Gulshan-e-Iqbal Block 18': 'Gulshan-e-Iqbal Block 18',
    'Gulshan-e-Iqbal Block 13a': 'Gulshan-e-Iqbal Block 13A',
}

df['sub_location'] = df['sub_location'].replace(gulshan_mapping)

In [17]:
invalid_sub_locations = [
    'Gulshan-e-Iqbal Block a',
    'Gulshan-e-Iqbal Block c',
    'Gulshan-e-Iqbal Block of'
]

df = df[~df['sub_location'].isin(invalid_sub_locations)].copy()

In [18]:
df.loc[
    df['sub_location'].eq('Hill Park'),
    'sub_location'
] = 'Jamshed Town'

In [19]:
federal_b_area_mapping = {
    'block 5': 'Federal B Area Block 5',
    'block 4': 'Federal B Area Block 4',
    'block 18': 'Federal B Area Block 18',
    'block 3': 'Federal B Area Block 3',
    'block 11': 'Federal B Area Block 11',
    'block 17': 'Federal B Area Block 17',
    'block 2': 'Federal B Area Block 2',
    'block 21': 'Federal B Area Block 21',
    'block 9': 'Federal B Area Block 9',
}

mask = df['location'].eq('Federal B Area')

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'sub_location']
      .replace(federal_b_area_mapping)
)

In [20]:
gulistan_jauhar_mapping = {
    'block 13': 'Gulistan-e-Jauhar Block 13',
    'block 2': 'Gulistan-e-Jauhar Block 2',
    'block 15': 'Gulistan-e-Jauhar Block 15',
    'block 16': 'Gulistan-e-Jauhar Block 16',
    'block 19': 'Gulistan-e-Jauhar Block 19',
    'block 3a': 'Gulistan-e-Jauhar Block 3A',
    'block 7': 'Gulistan-e-Jauhar Block 7',
    'block 12': 'Gulistan-e-Jauhar Block 12',
    'block 4': 'Gulistan-e-Jauhar Block 4',
    'block 10': 'Gulistan-e-Jauhar Block 10',
    'block 14': 'Gulistan-e-Jauhar Block 14',
    'block 3': 'Gulistan-e-Jauhar Block 3',
    'block 5': 'Gulistan-e-Jauhar Block 5',
    'block 02': 'Gulistan-e-Jauhar Block 2',
    'block 03-a': 'Gulistan-e-Jauhar Block 3A',
    'block 03a': 'Gulistan-e-Jauhar Block 3A',
    'block 04': 'Gulistan-e-Jauhar Block 4',
    'block 05': 'Gulistan-e-Jauhar Block 5',
    'block 1': 'Gulistan-e-Jauhar Block 1',
    'block 10a': 'Gulistan-e-Jauhar Block 10',
    'block 11': 'Gulistan-e-Jauhar Block 11',
    'block 16-a': 'Gulistan-e-Jauhar Block 16A',
    'block 16a': 'Gulistan-e-Jauhar Block 16A',
    'block 17': 'Gulistan-e-Jauhar Block 17',
    'block 9a': 'Gulistan-e-Jauhar Block 9',
}

mask = df['location'].eq('Gulistan-e-Jauhar')

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'sub_location']
      .replace(gulistan_jauhar_mapping)
)

In [21]:
mask = df['sub_location'].str.strip().str.lower().eq('airport')

df.loc[mask, 'location'] = 'Malir'

In [22]:
# Map valid lowercase blocks
naya_nazimabad_mapping = {
    'block a': 'Naya Nazimabad Block A',
    'block c': 'Naya Nazimabad Block C',
    'block d': 'Naya Nazimabad Block D',
    'block m': 'Naya Nazimabad Block M',
}

mask = df['location'].eq('Naya Nazimabad')

df.loc[mask, 'sub_location'] = (
    df.loc[mask, 'sub_location']
      .replace(naya_nazimabad_mapping)
)


# Delete invalid "block house"
df = df[
    ~(
        df['location'].eq('Naya Nazimabad') &
        df['sub_location'].str.strip().str.lower().eq('block house')
    )
].copy()

In [23]:
df[(df['location'] == 'Bahria Town') & (df['sub_location'].isnull())][
    'property_name']

322      152 square yards villa available for sale in b...
399      850 square feet's apartments available for sal...
442                                      bungalow for sale
549      1500 square feet ready to move apartments avai...
1284     grey structure villa for sale in bahria town k...
1596     850 square feet 2 bedroom flat available for s...
2643     950 square feet flat available for sale in bah...
2718     brand new 500 yards villa chance deal best pri...
3215     bahria hills, p9-500sq yds, most prime locatio...
3463     3 bedroom grey structure villa at prime locati...
3553     bahria hills 500 sq yards double story with ba...
4001     fully renovated villa for sale in paradise bahria
4350     200 yds one unit prime location villa at muree...
4507     most prime apartment of bahria town karachi sp...
4774     1000sq yards, precent 7, brandnew banglow, top...
4810     350 yard ready to move brand villa available s...
5161     2 bed lounge flat available on booking in us &...
5165     get in touch now to buy a prime location house...
5299     500sq yd luxury villa for sale. 2km from entra...
5349     500sq yd luxury villa for sale. 2km from entra...
5800     152 sq yard villa prime location bahria town k...
6464     ready to move 272 sq yd 5 bedroom ddl luxury v...
6689                  two unit bungalow available for sale
7586     theme park facing exclusive unit 3 bed dd 1830...
8574     ready to move 4 & 5 bedroom 272 square yards v...
9546     152 square yards villas available for sale in ...
9786     grey structure villa for sale in bahria town k...
9868       152 yard bungalow available sale bahria karachi
10388    get in touch now to buy a prime location house...
11125    brand new park facing 2 bed appt for sale 1 mi...
12034    prime location house of 125 square yards is av...
12228    2 bed corner west open apartment for sale | to...
12242    272 square yards villa available for sale in b...
12310    get in touch now to buy a 1400 square feet fla...
12864    4 bed dd corner theme park facing huge apartme...
13138    investors should sale this house located ideal...
13469    brand new 2 bedroom apartment in towers available
14350    brand new bungalow available sale nearest mani...
14490    2 bed furnished bahria apartment available for...
14550    a true 2200 square yard bungalow covers a mass...
15346    1000sq yd luxury villa with designer kitchen, ...
15612    your search for prime location house in bahria...
15992    4 bed apartment in dominion shoping mall and a...
16290    3bed ddl 125sq yd villa for sale. all amenitie...
16909    ready to move 272sq yd 5 bedroom ddl luxury vi...
16930    1100 square feet 2 bedroom flats available for...
18161    500 square yard luxury villa for sale 2 km fro...
18363    3 bed ddl 125sq yd villa for sale all amenitie...
18791    brand new grand mosque facing 2 bed putter out...
18992    beautiful 1000 yards architect designed villa ...
18993    precint 22 private constructed villa available...
19173    brand new corner 1100 sq yards 6 bed dd design...
20403    bahria hills, p9 designer villa at most prime ...
20431    500 sq yd luxury villa for sale bahria golf ci...
Name: property_name, dtype: object

In [24]:
# Save the filtered property names to a CSV file
df[(df['location'] == 'Bahria Town') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('bahria_town_null_sublocations.csv', index=False)

In [25]:
# Save the value_counts result to an Excel file
df[df["location"] == "Bahria Town"]["sub_location"].value_counts()

sub_location
Bahria Sports City    94
Precinct 2            92
Precinct 12           85
Precinct 8            75
Bahria Apartments     74
Private High-Rises    70
Precinct 11A          58
Bahria Paradise       56
Precinct 1            54
Precinct 9            54
Precinct 31           54
Precinct 10A          50
Precinct 11B          48
Bahria Heights        47
Precinct 6            45
Precinct 10B          42
Precinct 27           40
Precinct 4            37
Precinct 19           32
Precinct 16           30
Precinct 17           19
Precinct 15           17
Precinct 7             7
Precinct 18            5
Name: count, dtype: int64

In [26]:
sub_location_mapping = {
    3215: 'Precinct 9',        
    3553: 'Precinct 9',        
    4001: 'Bahria Paradise',   
    4774: 'Precinct 7',        
    18993: 'Precinct 22',      
    20403: 'Precinct 9',       
    20431: 'Precinct 20',      
}

In [27]:
df[(df['location'] == 'Bin Qasim Town') & (df['sub_location'].isnull())][
    'property_name']

590      newly constructed park face house for sale adj...
6001                                        house for sale
6228                              double road corner house
8508                                     bungalow for sale
10481              flat for sale ground floor 2 bed lounge
10503    1 bed lounge apartment for sale | ready to mov...
10770    highly-desirable 120 square yards house availa...
11519    buy a house of 180 square yards in pn welfare ...
12096    well designed and renovated house in safe and ...
13619    1 bed lounge apartment for sale | ready to mov...
14789    1 bed lounge apartment for sale | ready to mov...
16634    1 bed lounge apartment for sale | ready to mov...
Name: property_name, dtype: object

In [28]:
df[(df['location'] == 'Bin Qasim Town') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('bahria_town_null_sublocations.csv', index=False)

In [29]:
df[df["location"] == "Bin Qasim Town"]["sub_location"].value_counts()

sub_location
Mateen Complex    35
Phase 2            2
Model Colony       2
block a            1
Name: count, dtype: int64

In [30]:
df = df[~((df['location'] == 'Bin Qasim Town') & (df['sub_location'].isnull()))]

In [31]:
df[(df['location'] == 'Bin Qasim Town ') & (df['sub_location'].isnull())][
    'property_name']

Series([], Name: property_name, dtype: object)

In [32]:
mask = df['location'].eq('Bin Qasim Town') & df['sub_location'].isin(['Model Colony', 'Phase 2', 'block a'])

df.loc[mask, 'sub_location'] = None

In [33]:
df = df[~((df['location'] == 'Bin Qasim Town') & (df['sub_location'].isnull()))]

In [34]:
df[(df['location'] == 'Clifton') & (df['sub_location'].isnull())][
    'property_name']

249          flat for sale in clifton ideal family living!
812                   fresh booking flat available clifton
900      prime location in punjab chowrangi 1600 square...
1383     2628 square feet flat is available in grand mo...
1459                              brand new apartment sale
1680                          apartment available for sale
1972     a palatial residence for prime location sale i...
2034                brand new apartment available for sale
2258         brand new duplex apartment available for sale
2598                              flat for sale in karachi
3067          flat of 1800 square feet in clifton for sale
3727     1800 square feet apartment available for sale ...
5900     luxurious sea facing 3 bedrooms apartment for ...
7283     spacious 3 bedrooms apartment for sale servant...
7318                             brand new duplex for sale
7563                brand new apartment available for sale
7664                          apartment available for sale
7811                       apartment is available for sale
7996                         brand new apartment available
9306     fully furnished 3 bed dd apartment for sale ab...
9323     brand new centrally located 4 bedrooms apartme...
9370     premium 3 rooms big layout (rent 250k-260k) re...
9701                         1 bed lounge with car parking
9748                          apartment available for sale
10210                                        flat for sale
10453    4 bedrooms apartment available for sale in fer...
11171       clifton 4 bedroom brand new apartment for sale
11478                       3 bed room apartment with lift
11609               brand new apartment available for sale
11664    flat for sale in beautiful grand monarch seasi...
11701        ideal location house clifton karachi for sale
11848    4 bed dd apartment for sale in clifton next to...
11950        3 bedroom drawing dining lounge flat for sale
12383               brand new apartment available for sale
12852    luxurious 4 bedrooms apartment available for r...
13032    4 bed sea facing duplex available for sale in ...
13073                             brand new apartment sale
14024    ideally located flat of 3275 square feet is av...
14059               brand new apartment available for sale
16263                       clifton 3&4 apartment for sale
16462               brand new apartment available for sale
16472    prime location flat sized 1600 square feet is ...
16602    250-yard townhouses and apartments on installm...
16838    luxurious brand new 3 bedrooms apartment for s...
17657               3 bedroom apartment with lift for sale
18005                                   apartment for sale
18837                apartment for sale in chandio village
18871                         apartment available for sale
20099               brand new apartment available for sale
20168     90 square yards flat for sale in chandio village
20441    your ideal 250 square yards house has just bec...
Name: property_name, dtype: object

In [35]:
df[(df['location'] == 'Clifton') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('Clifton_null_sublocations.csv', index=False)

In [36]:
mask = df['location'].eq('DHA City')

df.loc[mask, 'location'] = 'Super Highway'
df.loc[mask, 'sub_location'] = 'DHA City'

In [37]:
df[(df['location'] == 'DHA Defence') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('DHA_Defence_null_sublocations.csv', index=False)

In [38]:
df[(df['location'] == 'DHA Defence') & (df['sub_location'].isnull())][
    'property_name']

24       prime location 2700 square feet flat for sale ...
104      huge driveway offering ample parking space hou...
432      prime location flat of 2350 square feet in sea...
564                                      apartment on sale
842      unparalleled luxury living at nhs zamzama kara...
883                  sea view apartment available for sale
1165     fully renovated seaview apartment second floor...
1222     seaview apartment first floor ff-2 available f...
1392     fully renovated sea view apartment 2nd floor sv 5
1597        furnished seaview apartment available for sale
1744     fully renovated seaview apartment ground floor...
2353     seaview apartment second floor available for sale
2397     sefacing luxury sea view apartment second floo...
2501                                      galaxy sky tower
2808                          sea view apartment for sale.
2952       affordable flat for sale in sea view apartments
3328                  renovated seaview apartment for sale
3526     sea facing 3 bedrooms apartment for sale in se...
3743     unparalleled luxury living at nhs zamzama kara...
3888     fully renovated seaview apartment second floor...
4379           sea view appartment gf1 available for sale.
4592     navy housing scheme zamzama - 350 square yards...
4918                             house for sale in karachi
5111     1000 sq yards bungalow available for sale in g...
5453                1000 yards bungalow for sale brand new
5806                       bungalow for sale near 2 talwar
6063          luxury brand new 1000 yard bungalow for sale
6717          seaview apartment ground floor gf-2 for sale
7191                navy housing zamzama bungalow for sale
8418                            seaview apartment for sale
8477     fully renovated seaview apartment second floor...
8536              ground floor seaview apartment for sale.
8952     fully renovated & furnished seaview apartment ...
8988     nazy housing zamzama 350 nhs house west open p...
9521                         fully renovated flat for sale
11099                          sea view apartment for sale
11241                                      with extra land
11910    3 bed dd sea view apartment for sale 2nd floor...
12837    centrally located flat in sea view apartments ...
13090                          apartment for sale like new
13712    unparalleled luxury living at nhs zamzama, kar...
13893    fully renovated seaview apartment available fo...
15084    sea view fully renovated like a brand new apar...
15180    in navy housing scheme zamzama house for sale ...
15766    fully renovated seaview apartment ground floor...
16485                           duplex apartment available
16896              fully and newly renovated flat for sale
16959    defence residency | west open | 1800 sqft 3 be...
19138                     ideal house in zamzama available
20040    seaview apartment ground floor gf-2 available ...
20053    fully renovated & furnished seaview apartment ...
20055      sea view apartment available for sale 1st floor
20347    get in touch now to buy a prime location flat ...
Name: property_name, dtype: object

In [39]:
sea_view_apartment_indexes = [
    883,
    1165,
    1222,
    1392,
    1597,
    1744,
    2353,
    2397,
    2808,
    2952,
    3328,
    3888,
    4379,
    6717,
    8418,
    8477,
    8536,
    8952,
    11099,
    11910,
    12837,
    13893,
    15084,
    15766,
    20040,
    20053,
    20055
]

df.loc[
    df.index.isin(sea_view_apartment_indexes),
    'sub_location'
] = 'Phase 5'

In [40]:
df[(df['location'] == 'Malir') & (df['sub_location'].isnull())][
    'property_name']

261      3 bed lounge flat next to corner jinnah avenue...
288      tipu sultan housing society malir cantt karach...
365      flat for booking in sumsum grand 2 on main jin...
433      80 sq. yards corner house + road facing shop f...
1558           apartment for sale on easy installment plan
1575     08 bed dd g+2 bungalow for sale in tipu sultan...
3206          flat for grabs in 70 square yards moria goth
3208     chance deal ground +2 house for sale in malir ...
3667     prime location 160 square yards house in kazim...
3973                           gohar complex flat for sale
4109     brand new flat for sale at al amin city malir ...
4548                             new project flat for sale
4656     this is the most luxurious, fully maintained, ...
5094     brand new house 240 sq leased map approved for...
5613                            3 bed lounge flat for sale
6314     gohar complex brand new 3 sides corner, west o...
6779     tipu sultan housing society near malir cantt c...
7164              new brand flat for sale shah faisal town
7429     zayan victoria 3 bed loungue flat for sale jus...
7860        100 sq yards villa for sale river valley malir
7872                 corner flat for sale in gohar complex
7968     main shahrah-e-faisal facing 2 bed apartment f...
8192     double story house for sale in burhani town ho...
8392     210 yard one unit villa for sale in gohar gree...
8606     brand new house for sale at malir tanki market...
9478                    flat for sale leased gohar complex
9508               120 yard leased house ground+1 for sale
9865     zayan victoria 2 bed lounge flat available for...
10628    zayan victoria 2bed lounge flat available for ...
11549    270-yard askari villas project on 3-years inta...
13129    main shahrah-e-faisal facing 3 rooms, rental v...
13238                           my new house ready to move
13949    main shahrah-e-faisal facing 2 bed apartment f...
14603    1 bed lounge apartment for sale | ready to mov...
14608    spacious 9-bedroom corner house with 2 shops j...
15060    1 bed lounge apartment for sale | ready to mov...
15474    2 rooms apartment for sale | ready to move | o...
16945    350 yard double storey corner banglow opposite...
19421    ready to move 1 bed lounge apartment for sale ...
19583            new brand flat for sale shah fayical town
19672      133 sq yd ground plus1 house available for sale
Name: property_name, dtype: object

In [41]:
df[(df['location'] == 'Malir') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('Malir Town_null_sublocations.csv', index=False)

In [42]:
mateen_complex_idx = [14603, 15060, 15474, 19421]

df.loc[
    df.index.isin(mateen_complex_idx),
    'location'
] = 'Bin Qasim Town'

df.loc[
    df.index.isin(mateen_complex_idx),
    'sub_location'
] = 'Mateen Complex'


shahra_e_faisal_idx = [7968, 13129, 13949]

df.loc[
    df.index.isin(shahra_e_faisal_idx),
    'location'
] = 'Shahra-e-Faisal'

In [43]:
df[(df['location'] == 'Malir') & (df['sub_location'].isnull())][
    'property_name']

261      3 bed lounge flat next to corner jinnah avenue...
288      tipu sultan housing society malir cantt karach...
365      flat for booking in sumsum grand 2 on main jin...
433      80 sq. yards corner house + road facing shop f...
1558           apartment for sale on easy installment plan
1575     08 bed dd g+2 bungalow for sale in tipu sultan...
3206          flat for grabs in 70 square yards moria goth
3208     chance deal ground +2 house for sale in malir ...
3667     prime location 160 square yards house in kazim...
3973                           gohar complex flat for sale
4109     brand new flat for sale at al amin city malir ...
4548                             new project flat for sale
4656     this is the most luxurious, fully maintained, ...
5094     brand new house 240 sq leased map approved for...
5613                            3 bed lounge flat for sale
6314     gohar complex brand new 3 sides corner, west o...
6779     tipu sultan housing society near malir cantt c...
7164              new brand flat for sale shah faisal town
7429     zayan victoria 3 bed loungue flat for sale jus...
7860        100 sq yards villa for sale river valley malir
7872                 corner flat for sale in gohar complex
8192     double story house for sale in burhani town ho...
8392     210 yard one unit villa for sale in gohar gree...
8606     brand new house for sale at malir tanki market...
9478                    flat for sale leased gohar complex
9508               120 yard leased house ground+1 for sale
9865     zayan victoria 2 bed lounge flat available for...
10628    zayan victoria 2bed lounge flat available for ...
11549    270-yard askari villas project on 3-years inta...
13238                           my new house ready to move
14608    spacious 9-bedroom corner house with 2 shops j...
16945    350 yard double storey corner banglow opposite...
19583            new brand flat for sale shah fayical town
19672      133 sq yd ground plus1 house available for sale
Name: property_name, dtype: object

In [44]:
# Nazimabad 1, 2, 3 → Nazimabad
mask = (
    (df['location'] == 'Naya Nazimabad') &
    (df['sub_location'].isin(['Nazimabad 1', 'Nazimabad 2', 'Nazimabad 3']))
)

df.loc[mask, 'location'] = 'Nazimabad'

In [45]:
df[(df['location'] == 'Scheme 33') & (df['sub_location'].isnull())][
    'property_name']

18       prime location sale the ideally located house ...
121                 scheme 33 apartment available for sale
131      sawera grand enclave (a project by ok estate &...
166      a stunning house is up for grabs in scheme 33 ...
172                      roomi boulevard new project louch
225      brand new flat for buy in scheme 33 near madra...
274      road facing 2 bed dd flat with roof for sale g...
444      modern living redefined apartments for sale in...
497             flat available on booking in saima project
553             pakistan air crew bondrt wall society west
687                   transfer house is available for sale
697                                          flat for sale
709      pcsir society scheme-33 240square yards single...
725      prime location 945 square feet flat in scheme ...
764      3 bed dd apartment available for sell in sakin...
771      end your search for prime location flat here a...
824      a 120 square yards house has landed on market ...
951           950 square feet apartment available for sale
1101     3 bd lounge apartment in booking gated communi...
1112     prime location 1760 square feet flat for sale ...
1158     leased 2 bed lounge apartment for sale bhayani...
1171     prime location 847 square feet flat in central...
1175     2 bed dd flat available for sale in abuzar gha...
1223                          brand new g+2 house for sell
1316     3 bed dd and 2 bed dd flats are available for ...
1354     sawera grand enclave. a project by ok estate &...
1384     stunning 2 bedroom apartment in sawera enclave...
1390                           2 bed dd apartment for sale
1465            flat for sale in 800 square feet scheme 33
1480     sawera grand enclave a project by ok estate & ...
1483     teachers society, ground + 2, 12 bed corner, w...
1621     fully maintained apartment, lease complete doc...
1665     prime location flat sized 850 square feet is a...
1786     3 side corner flat 2 bed dd 4th floor lift not...
1833                         4 rooms kda society scheme 33
1909     get in touch now to buy a prime location 240 s...
1912     abuzar ghaffari society scheme 33 near gulshan...
1967     brand new flat ( west open, double corner) ( i...
1976     nomi terrace beautiful apartment available for...
2171                      30 ft road ground+1 house corner
2229     sawera enclave a luxurious project apartments ...
2300     luxurious loan applicable house  sale with all...
2442     prominently-located 120 square yards one unit ...
2474     pre-booking | sawera grand enclave | ok estate...
2507     sawera enclave luxury apartments & prime comme...
2509     1000 square feet flat for sale available in sc...
2513     loan applicable house haroon bungalows safoora...
2538     direct owner urgent sale 2 bed lounge faria ap...
2555     *3 bed lounge flat for sale in country comfort...
2557     affordable prime location flat of 625 square f...
2632     madina resistance : luxury furniture apartment...
2645     leased flat is available for sale in tulip tow...
2676     flats available for resale scheme 33 near dow ...
2694                     under construction house for sale
2706     modern high-rise apartments near gulshan in sc...
2901     in nomand residential ,west open , corner,2 be...
2979     brand new 120 sq. yards double storey (g+1) ho...
3073     prime location 3 bed dd flat available for sal...
3146            new flat for sale for sale shahra-e-faisal
3148               flat is available for sale in scheme 33
3268     get your dream prime location flat in scheme 3...
3270     reserve a flat now in country comforts appartment
3284     a one villas one unit lease corner 80 ft road ...
3358     brand new ultra modern project burj-ul-harmain...
3378     120 sqy single storey structure pir gul hassan...
3449     ocean garden phase iii - duplexes pre-launchin...
3528     perfect 133 square yards house in scheme 33 fo...
3544     2 bed dd flat available for sale in abuzar gha...
3676         commander heights 2 bedrooms luxury apartment
3680     * _2 bed dd flat for sale in country apartment...
3752             flat available for sale in pioneer castle
3825                               home for sale available
3847     lease boundary wall project 4 room beside memo...
3929                              flat for sale  scheme 33
3963     gorgeous prime location 1450 square feet flat ...
3997                "al rauf gold raas" apartment for sale
4007     prime location flat of 1151 square feet availa...
4043     luxury 2 bed apartment for sale in installment...
4049                  2 bed lounge flat available for sale
4082     2 bed dd flat available for sale in al zahra c...
4103     luxury 4 -rooms big size exclusive unite | gre...
4106     2 bed dd second floor flat boundary wall compo...
4128     prime location 625 square feet flat situated i...
4162     highly-coveted prime location 845 square feet ...
4175     nearing possession | sawera enclave | 2 &amp; ...
4181     prime location flat spread over 845 square fee...
4316        1200 square feet flat up for sale in scheme 33
4322                  sea-facing luxury apartment for sale
4508                         brand new apartments for sale
4611                        kings grand apartment for sale
4628     samrina grand on booking under construction ap...
4645     bank loan applicable prime 2-bed dd apartment ...
4675     sawera enclave (a project by ok estate & build...
4829     centrally located house in scheme 33 is availa...
4888     we are pleased to inform you that we have soft...
4975     beautiful flat available for sale in booking p...
5018     brand new project burj-ul-harmain at main safo...
5032     prime location flat for sale in grey stylux re...
5192     spacious 2 bed dd flat for sale in elaaf tower...
5209     bank loan applicable prime 2-bed dd apartment ...
5251     200 sqyd grey structure 3 bed dd planning for ...
5325     2 bad dd 900 square feet flat in only rs. 4800000
5341     2 bed dd 88 lac (850 sq. ft, 5th floor, by bir...
5360     apartment for sale 2 bed lounge hakeem classic...
5392         flat is available for sale in burj ul harmain
5401     120 square yards house in beautiful location o...
5405     2 bed dd flat available for sale in abuzar gha...
5502     luxury brand new flat available for sale.  in ...
5655     house for sale in pakistan air crew cooperativ...
5672     sawera enclave (a project by ok estate & build...
5778     unoccupied house of 120 square yards is availa...
5870     prime location 1050 square feet flat available...
5896     prime location 1050 square feet flat is availa...
5897     balaj icon 0ne 2 bed dd flat available for sal...
5956                       2 bed lounge apartment for sale
6010     prime location 1760 square feet flat for sale ...
6026     3 bed dd road facing flat available for sale i...
6031           1232 square feet flat in scheme 33 for sale
6072     prime location 625 square feet flat for sale i...
6118                 brand new house vip location for sale
6156            leased bungalow 6 bedroom reasonable price
6224     sawera grand enclave where luxury meets modern...
6226     ideally located flat of 900 square feet is ava...
6310     your ideal 950 square feet flat has just becom...
6390     stunning prime location flat is available for ...
6487                house for sale ground plus 2 scheme 33
6537           1050 sqft net area flat available for sale.
6629     prime location 1180 square feet spacious flat ...
6639     flat for sale in sawera enclave (a project of ...
6685     leased bank loan applicable brand new flat als...
6729     prime location 1250 square feet cottage (flat)...
6763     west open 2 bed lounge flat is avaialblr for s...
6985     saadat e amroha society, west open, park facin...
6995     prime location scheme 33 flat sized 750 square...
7128                             house for sale in karachi
7162     your dream home is now within reach!introducin...
7185                     bank loan applicable 3 bed lounge
7267     beautiful new 120 sq yards single storey house...
7274     ideal 120 square yards house available in rimj...
7387                        safari signature flat for sale
7409             brand new double storey bungalow for sale
7428     3 bed dd west open lease flat main malir cant ...
7462     kehkashan homes one unit lease west open house...
7500     flat in al fatah brishna heights, scheme 33, k...
7555            get in touch now to buy a house in karachi
7616     2 bed lounge flat available for sale in daniya...
7649        flat of 1200 square feet for sale in scheme 33
7716     leased bank loan applicable brand new flat als...
7769     flat available for booking in sawera grand enc...
7817     one of the most luxurious project available in...
7928              al falah tower asfani road flat for sale
7978       punjabi sudagraan corner new g+2 house for sell
8019     bank loan available 2 bedroom drawing dining 2...
8038     sawera enclave a luxurious lifestyle project b...
8045     2 bed drawing and dinning flat available for s...
8081     spacious 2 bedrooms apartment with lounge & sc...
8124     prime location apartments near jamali bridge s...
8146                            2 bed lounge flat for sale
8148     get in touch now to buy a 2750 square feet fla...
8150                            flat is available for sale
8155     get in touch now to buy a prime location 1340 ...
8239                   brand new flat 2 bed drawing lounge
8251     2 bed lounge flat available for installments i...
8282                           best location no lodshading
8329                                 sohni view apartments
8363     king's garden brand new luxurious bungalow, 4b...
8378     spacious prime location flat is available in s...
8435     installment based flats is available for sale ...
8457     ocean garden gated community discount booking ...
8458              sawera grand enclave apartments for sale
8469     leased 3 bed drawing lounge apartment availabl...
8516                           4 bed dd apartment for sale
8523     zeenatabad cooperative housing society house f...
8548     get in touch now to buy a prime location flat ...
8571                 a flat at affordable price awaits you
8584     ideal prime location house for sale in rufi ro...
8611          leased west open corner road facing 3 bed dd
8627     house for sale fatima sun rise city scheme 33 ...
8745     house in scheme 33 sized 120 square yards is a...
8924                       2 bed dd available on bank loan
8939                                    new house for sale
8989     *2 bed lounge flat for sale in country comfort...
9020     leased bank loan applicable brand new flat als...
9049     stunning 2 bedroom apartment in sawera enclave...
9076                            600 sq yard house for sale
9095                      book ur dream apartment for sale
9269            chapal courtyard 3 new project coming soon
9310     urgent sale 2bed dd schene 33 prime location f...
9384                           panjabi sodagiran ps city 1
9440                                sumaira residency lift
9442     cotton co operative housing   40ft road   a pl...
9481     your dream apartment is now affordable! book t...
9577                      3 bed dd flat available for sale
9704     3 bed dd apartment pay 50 % & shift in your ap...
9760     best located single belt plot west open ground...
9842     book your dream apartments at sawera grand enc...
9926                 federal government apartment for sale
10028                  200 yards g+1 villa with possession
10072    3 bedroom drawing lounge flat available for sa...
10120                      2 bed dd neat & clean apartment
10130      3 bed dd flat available for sale prime location
10143    prime location 800 square feet flat available ...
10285    *2 bed lounge flat for sale in asma garden, gu...
10303    prime location 900 square feet flat for sale i...
10383    installment based flats is available for sale ...
10487    highly-desirable prime location 120 square yar...
10584          3bed dd leased apartment available for sale
10694    get in touch now to buy a prime location 1500 ...
10831    prime location 945 square feet flat for sale i...
10892                                  prime location flat
10991    premium west open 1050 square feet flat is ava...
11051    leased house in punjabi sadagran ps-ii, ps-2 l...
11071    2 bed dd for sale lakhani fantasia bank loan a...
11075         boundary wall 2bed lounge apartment for sale
11078    leased 3 bed d d building bin safeer store bes...
11164                         apartment available for sale
11223    120 square yards brand-new house for sale ps c...
11240    2 bed dd brand new apartment (possession in 6-...
11404    leased bank loan applicable brand new 2 bed dr...
11466    stunning prime location flat is available for ...
11580        2 and 3 bedroom apartments available for sale
11637    2 bed dd 1250 sq ft 2nd floor apartment availa...
11673    prime location 750 square feet flat available ...
11806    leased one unit house is available for sale in...
11901    flat available for booking in sawera grand enc...
11935    in scheme 33 you can find the perfect east ope...
11948    leased bank loan applicable brand new flat ava...
12075    ground + 2 leased house for sale near rim jhim...
12084    3 bed lounge flat available for sale   at pcsi...
12177    leased bank loan applicable 2 bed dd apartment...
12221    04 bed dd leased apartment available for sale ...
12238    main farea chook near to paradise bakery 2 nd ...
12328    house for sale in abbas town 120 yards ground ...
12340    *1 bed lounge flat for sale in country comfort...
12368     120 yards west open single storey house for sale
12372    double-story bungalow for sale rok cooperative...
12398    2 bed dd apartment for sale in al zehra comple...
12516    leased bank loan applicable brand new flat ava...
12554    grey noor tower, 2 bed dd , 2 bed lounge, 3 be...
12603    sawera enclave a project by ok estate & builde...
12692                      corner house for sale 120 yards
12705    fair-priced 1671 square feet flat available in...
12708    dream flat alert: luxurious flat 3 bed dd for ...
12829    leased bank loan applicable brand new flat ava...
12889    balaj icon one 2 bed dd brand new apartment av...
12972    reserve a prime location flat of 900 square fe...
13024    prime location in scheme 33 flat sized 600 squ...
13053                          safari signature apartments
13093    instalment based flat is available for sale in...
13149    brand new house for sale builder transfer and ...
13151    leased bank loan applicable brand new flat als...
13169                          bungalow available for sale
13421         direct owner 240 yards ground plus two house
13452                  flat for sale lease 750 square feet
13491    spacious single story house for sale al-mehran...
13598    brand new 2 and 3 bed room apartment available...
13667     3 bed dd flat for sale in scheme 33 on bank loan
13691    leased bank loan applicable 2 bed drawing loun...
13795    installment based flat is available for sale i...
13826    sawera enclave a luxurious project by ok estat...
13842    120 square yards house in only rs. 30000000 fo...
13858    rabia patel 2 bed lounge abul hassan isphani r...
13973    ultra premium project,ultra modern apartments ...
14046                                  (direct owner deal)
14064    a perfect 2 bed and 3-bed apartments by sawera...
14069    rafi premier residency fully leased 3dd apartm...
14235    sawera enclave, a project by ok estate & build...
14317             brand new corner 2 bed drawing tv lounge
14332    used & well-maintained 120 sq. yards g+2 house...
14377                          house is available for sale
14443    5 rooms super luxury new corner road side read...
14449    in tulip tower, a zero meter 3500 square feet ...
14501                                  jori flats for sale
14551     pakistan post office workers comparative housing
14615    near rimjhim tower 240 square yards leased sin...
14637                 flat available for sale in scheme 33
14664      apartment available for sale in sawera enclave.
14700    bismillah center 2 bed lounch for sale boundar...
14754    available for sell one. bed lounge apartment i...
14758    rafi premier residency fully leased 3dd apartm...
14809    spacious flat is available in kesc housing soc...
14877                               3 bed dd flat for sale
14894    120 yards house for sale gulshan e azeem, karachi
14920    leased bank loan applicable brand new flat als...
15054    very well maintained 2 bed drawing and dinning...
15107    2 bed lounge flat for sale daniyal tower - lea...
15126    zoramin residency 120 yards one unit bungalow ...
15229                             house available for sale
15348                     brand new 2 bed dd flat for sale
15440    get your hands on prime location flat in schem...
15465    bank loan not applicable  2 bed dd flat for sa...
15532                        roshan prestige flat for sale
15551    on booking under construction apartment availa...
15602                   rabia pearl apartments is for sale
15623    loan applicable leased house g+1 of 120 yards ...
15644                   brand new house available for sale
15651         direct owner 240 yards ground plus two house
15728    muhammadi corner new project available flat fo...
15825    sawera grand enclave. a project by ok estate &...
15834    120 sq. yards brand new house for sale ground ...
15859    khurasan heights lease apartment scheme 33 nea...
15895    leased bank loan applicable brand new flat als...
15900              country comfarts scheme 33 gulzar hijri
15907    saima elite 120 yards one unit is available fo...
16030    brand new 3 storey villa for sale on 40 feet r...
16079    leased bank loan applicable brand new flat als...
16106                                        flat for sell
16107    leased bank loan applicable brand new flat als...
16299            urgent sale scheme 33 ideal location flat
16338    get in touch now to buy a prime location 1298 ...
16498      apartment available on booking in saima project
16499    leased bank loan applicable 2 bedroom lounge a...
16688                       120 square yard house for sale
16756       apartment available for sale in sawera enclave
16908    200 square yards house for sale in kesc housin...
16949           brand new 3side corner apartment 1700sqfts
16986    transfer ideal 400 square yards house has land...
17019    apartments for sale in under construction proj...
17036                                 sawera grand enclave
17057    *2 bed lounge flat for sale in country comfort...
17107    leased bank loan applicable brand new flat als...
17176                     roomi sapphire booking available
17191    sawera enclave, a signature project by ok esta...
17198    luxury 3 bed dd | 1600 sq. ft. | private roof ...
17347                          3 bed dd apartment for sale
17372          950 square feet flat for grabs in scheme 33
17374                               house g+1 vip location
17488    urgent sale ideal location flat in scheme 33 1...
17514    brand new architect designed owner built house...
17624    brand new flat in brand new building (ideal fo...
17629    ready-to-move 2 & 3 bed apartments at sawera e...
17647    premium 1000 square feet flat is available for...
17776    g+1 banglolw for sale in air crew society sche...
18000                      flat in sawera enclave for sale
18012    mera ghar mera aashiana flats available at sch...
18017       ultra modern brand new project burj-ul-harmain
18047    sawera grand enclave luxury living starts here...
18058            flat available for sale in sawera enclave

In [46]:
df[(df['location'] == 'Scheme 33') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('Scheme 33_null_sublocations.csv', index=True)

In [47]:
# Map original dataframe index -> sub_location
# Only fill rows where sub_location is currently NaN

sector_mapping = {
    # Sector 29
    131: "Sector 29",
    444: "Sector 29",
    1316: "Sector 29",
    1354: "Sector 29",
    1384: "Sector 29",
    1480: "Sector 29",
    2229: "Sector 29",
    2474: "Sector 29",
    2507: "Sector 29",
    2706: "Sector 29",
    3270: "Sector 29",
    4675: "Sector 29",
    5018: "Sector 29",
    5392: "Sector 29",
    5672: "Sector 29",
    6224: "Sector 29",
    6639: "Sector 29",
    7162: "Sector 29",
    7769: "Sector 29",
    7817: "Sector 29",
    8038: "Sector 29",
    8124: "Sector 29",
    8251: "Sector 29",
    8458: "Sector 29",
    9049: "Sector 29",
    9842: "Sector 29",
    11901: "Sector 29",
    12603: "Sector 29",
    13826: "Sector 29",
    14235: "Sector 29",
    14664: "Sector 29",
    15825: "Sector 29",
    16756: "Sector 29",
    17019: "Sector 29",
    17036: "Sector 29",
    17191: "Sector 29",
    17629: "Sector 29",
    18000: "Sector 29",
    18047: "Sector 29",
    18058: "Sector 29",
    18420: "Sector 29",
    20046: "Sector 29",
    20249: "Sector 29",

    # Sector 30
    497: "Sector 30",
    16498: "Sector 30",

    # Sector 18-A
    1483: "Sector 18-A",

    # Sector 17-A
    7978: "Sector 17-A",
    9384: "Sector 17-A",
    11051: "Sector 17-A",
    11223: "Sector 17-A",

    # Sector 24-A
    2645: "Sector 24-A",
    3073: "Sector 24-A",
    5192: "Sector 24-A",
    5360: "Sector 24-A",
    7387: "Sector 24-A",
    14449: "Sector 24-A",
    15126: "Sector 24-A",
    18735: "Sector 24-A",

    # Sector 35-A
    764: "Sector 35-A",
    4645: "Sector 35-A",
    5209: "Sector 35-A",
    15602: "Sector 35-A",

    # Sector 42-A
    3676: "Sector 42-A",

    # Sector 40
    3997: "Sector 40",
    4082: "Sector 40",
    4103: "Sector 40",
    5032: "Sector 40",
    10694: "Sector 40",
    12554: "Sector 40",
    12705: "Sector 40",
    12708: "Sector 40",
    16949: "Sector 40",
    17198: "Sector 40",
    18955: "Sector 40",
    19264: "Sector 40",
    19277: "Sector 40",
    19286: "Sector 40",
    19670: "Sector 40",
    19698: "Sector 40",

    # Sector 19-A
    3680: "Sector 19-A",
    10285: "Sector 19-A",
    12340: "Sector 19-A",
    15054: "Sector 19-A",
    15859: "Sector 19-A",
    15900: "Sector 19-A",
    17057: "Sector 19-A",
    18080: "Sector 19-A",

    # Sector 34-A
    6985: "Sector 34-A",
    14069: "Sector 34-A",
    14758: "Sector 34-A",

    # Sector 15-A
    12372: "Sector 15-A",
    19309: "Sector 15-A",

    # Sector 4-C
    11637: "Sector 4-C",

    # Sector 4-A
    12084: "Sector 4-A",

    # Sector 25-B
    5897: "Sector 25-B",
    12889: "Sector 25-B",

    # Sector 33
    14551: "Sector 33",
}


# Only fill NaN values in the EXISTING sub_location column
for idx, sector in sector_mapping.items():
    if idx in df.index and pd.isna(df.loc[idx, "sub_location"]):
        df.loc[idx, "sub_location"] = sector

In [48]:
sector_normalization = {
    "sector 21-a": "Sector 21-A",
    "sector 13-a": "Sector 13-A",
    "sector 17a": "Sector 17-A",
    "sector 25a": "Sector 25-A",
    "sector 34a": "Sector 34-A",
    "sector 5a": "Sector 5-A",
    "sector 9-a": "Sector 9-A",
    "sector 9a/1": "Sector 9-A",
    
    "block 1": "Block 1",
    "block 2": "Block 2",
    "block 9": "Block 9",
    
    "phase 1": "Phase 1",
    "phase 3": "Phase 3",
}

df["sub_location"] = df["sub_location"].replace(sector_normalization)

In [49]:
df['sub_location'].isnull().sum()

np.int64(1586)

In [50]:
df[(df['location'] == 'Super Highway') & (df['sub_location'].isnull())][
    'property_name']

1419                    sawera grand enclave flat for sale
3096          2 shops + house main road facing chance deal
5722     legacy icon prime location flat for sale in ka...
7767     1350 square feet flat in central karachi - hyd...
9810     introducing a brand new premium project on sup...
10076    flat available for booking in sawera grand enc...
10977    bismillah center 2 bed lounge super highway ne...
11111                                       prime location
11334    flat available for booking in sawera grand enc...
11411    get in touch now to buy a prime location flat ...
11667                            beautifull villa for sale
12339    prime location in karachi - hyderabad motorway...
12347    legacy icon your address to prime location kar...
12642    luxury brand new west open bungalow for sale i...
12969    flat available for booking in sawera grand enc...
13846    ideal prime location flat for sale in karachi ...
15663    legacy icon fair-priced prime location in kara...
15737    to sale you can find spacious prime location f...
15823    affordable prime location flat available for s...
16878         house for sale in beautiful karachi motorway
17758    roomi enclave near jamali pul scheme 33 , 3 la...
17945    prime location 1000 square feet flat for sale ...
20357    prime location 1151 square feet flat in karach...
Name: property_name, dtype: object

In [51]:
df[df['sub_location'].isnull()]['location'].value_counts()

location
Naya Nazimabad          300
Scheme 33               282
Gulshan-e-Iqbal Town    178
Gulistan-e-Jauhar        95
Malir Cantt              91
Civil Lines              79
Saddar                   69
Bahria Town              54
North Nazimabad          53
Clifton                  51
North Karachi            46
Federal B Area           45
Defence View             40
Malir                    34
Shahra-e-Faisal          32
Tipu Sultan Road         32
DHA Defence              26
Northern Bypass          26
Super Highway            23
Shah Faisal              13
Jamshed Town              7
Nazimabad                 7
Korangi                   3
Name: count, dtype: int64

In [52]:
df[(df['location'] == 'Naya Nazimabad') & (df['sub_location'].isnull())][
    'property_name']

161      prime location affordable house for sale in na...
233      a prime location 1750 square feet house has la...
289      get this amazing prime location 1950 square fe...
303      1280 square feet flat situated in naya nazimab...
320      ideal prime location 160 square yards house av...
414      buy your ideal facing park 120 square yards ho...
438      naya nazimabad peace apartment | 6.5 years eas...
486      prime location 120 square yards house in naya ...
598      prime location affordable house for sale in na...
602      2&3 bedrooms apartment | naya nazimabad | glob...
609                         naya nazimabad peace apartment
629      naya nazimabad luxurious apartment fl-05 | eas...
639      prime location naya nazimabad flat sized 1250 ...
652      prime location property for sale in naya nazim...
659      naya nazimabad: secure, boundary-walled apartm...
960      buy prime location 1750 square feet house at h...
1011     prime location flat for sale in naya nazimabad...
1036     2 bed dd apartment for sell in naya nazimabad ...
1068                 nayanazimabad peace apartments com 35
1083     naya nazimabad peace apartment | 6.5 years eas...
1200     gorgeous prime location 1300 square feet flat ...
1314     a prime location 160 square yards house has la...
1351     2 bed dd apartment for sell in naya nazimabad ...
1423     get a prime location 1750 square feet flat for...
1461     prime location flat of 1250 square feet availa...
1617            affordable 3 bed dd flat in naya nazimabad
1731     120 square yards house for sale in the perfect...
1768     prime location 1750 square feet flat for sale ...
1805     a prime location 1250 square feet flat has lan...
1917     luxury 120 square yard used bungalow available...
1929     a great choice for a 1785 square feet flat ava...
2023     naya nazimabad ready to move apartment | fl-04...
2063     prime location ideal house for sale in naya na...
2164     want to buy a prime location flat in naya nazi...
2230     get your hands on prime location house in naya...
2401     flat for sale fl 4 ready to position bank loan...
2403     prime location 1750 square feet flat ideally s...
2406          peace apartment naya nazimabad flat for sale
2410     direct booked: 2 bedroom apartment on installm...
2446     beautifully constructed prime location flat is...
2600     7 years payment plan apartments available in n...
2725                   fl-08 globe residency nayanazimabad
2741     prime location naya nazimabad house sized 120 ...
2849     naya nazimabad luxurious apartment instalment ...
2997     perfect prime location 1250 square feet flat i...
3087     prime location 120 square yards house in naya ...
3178     prime location sale the ideally located house ...
3205     naya nazimabad peace apartment | 6.5 years eas...
3327     your search for prime location flat in naya na...
3397     global residency 2 bed apartment available for...
3518          3 bedroom lounge apartment available in fl 4
3563     get in touch now to buy a prime location 133 s...
3569               flat for sale signature signature tower
3599     prime location 1250 square feet flat for sale ...
3646                          120 sq. yds. luxurious villa
3651     buy a centrally located prime location 1250 sq...
3688        265 yards corner green belt west open bungalow
3702          peace apartment com # 39 main boulevard road
3764     reserve a centrally located flat of 1785 squar...
3767     spacious prime location flat is available in n...
3826              240 yards double storey corner west open
3832     naya nazimabad luxurious apartment fl-03 | eas...
3863                  naya nazimabad fl4 flat 4 bed lounge
3971            naya nazimabad brand new bungalow for sale
3972         prime location house for sale in rs. 58000000
4069       120 yards one unit house 2 kitchens 6 washrooms
4224     prime location 120 square yards spacious house...
4359     120 sqyd single story bungalow available for sale
4392     get in touch now to buy a prime location 1700 ...
4410     prime location naya nazimabad flat for sale si...
4455        naya nazimabad globe residency apartments fl04
4494                          naya nazimabad flat for sale
4509     a prime location flat of 1750 square feet in r...
4515                    120 sq. yds. villa on installments
4542     2 & 3 bedroom luxury apartments in naya nazimabad
4563     highly-coveted prime location 1546 square feet...
4568     prime location 240 square yards house in only ...
4598                                     rahat residency 1
4642        flat for sale naya nazimabad rahat residency 1
4851     own a prime location house in 120 square yards...
4985     prime location naya nazimabad house sized 120 ...
4999     prime location flat is available for sale in n...
5017     your search for prime location flat in naya na...
5048     want to buy a prime location house in naya naz...
5056     affordable prime location flat available for s...
5145     reasonably-priced prime location 120 square ya...
5149     we offer our new project 2-bedroom apartment i...
5183                    flat for sale naya nazimabad fl 05
5242     prime location 160 square yards house in naya ...
5254     1785 square feet flat for sale available in na...
5323      luxurious 400 sq yard villa | 8 bed d/d for sale
5372                         globe residency fl05 tower o2
5532     naya nazimabad luxurious apartment | easy inst...
5558          3 bedroom +lounge appartment globe residency
5732          ideal prime location house in naya nazimabad
5774             brand new 160 sq. yards bungalow for sale
5843                         flat for sale globe residency
5862                fl-04 apartment 2 bed dd nayanazimabad
5892     affordable prime location flat available for s...
5902            naya nazimabad flat sized 1260 square feet
5930     a prime location house of 114 square yards in ...
5995     prime location 120 square yards house for sale...
6142     prominently-located prime location 240 square ...
6217     affordable prime location house for sale in na...
6230     aesthetic prime location house of 120 square y...
6256     prime location 1250 square feet flat for sale ...
6267                  luxrious 2 bed dd apartment for sale
6288     naya nazimabad fl-05 fl-07 3 bed dd flat for sale
6325     prime location flat of 1250 square feet in nay...
6337     prime location in naya nazimabad house for sal...
6360     luxurious 120 square yards house available for...
6364     affordable 3 bed dd flat in naya nazimabad for...
6419     ideally located prime location flat for sale i...
6421     stunning prime location flat is available for ...
6498     modern luxury apartment with premium amenities...
6533     ready 2-bed apartment for sale in naya nazimab...
6548     centrally located prime location flat availabl...
6680     prime location house of 1250 square feet in na...
6742     prime location 160 square yards house up for s...
6832     get your dream prime location house in naya na...
6842     2 bed drawing dinning, ready to possession, gl...
6869     prominently-located flat available in naya naz...
6901     flat for sale in installment naya nazimabad ne...
6910     modern luxury apartment with premium amenities...
7015     prime 2-bed dd apartment available at fl 4 in ...
7144     affordable prime location flat for sale in nay...
7172     prime location naya nazimabad house sized 120 ...
7247     house available for sale brand new 160 square ...
7302     240 sq yd single storey | park face | west ope...
7315     buy your ideal prime location 1750 square feet...
7463     prime location 1750 square feet flat is availa...
7475     prime location flat for sale is readily availa...
7573        naya nazimabad rahat residency 1 flat for sale
7692     naya nazimabad peace apartment flat for sale i...
7702     looking for a prime location flat in naya nazi...
7770     stunning and affordable prime location house a...
7801     3 rooms flat | naya nazimabad | peace apartmen...
7819       prime location house for sale in naya nazimabad
7869     prime location 1750 square feet house for grab...
7979     investors should sale this prime location flat...
7992     peace apartment comm 37 2 bedroom drawing dinn...
8008     1200 square feet flat in beautiful location of...
8065     a spacious prime location 1000 square feet fla...
8115         3 bedroom lounge apartment available for sale
8216       naya nazimabad | fl-03 3 bed dd | flat for sale
8250     aesthetic prime location flat of 913 square fe...
8269     prime location 120 square yards house in naya ...
8270     prime location 1250 square feet flat available...
8369     2 bed dd apartment, naya nazimabad globe resid...
8482     prime location 1250 square feet house in naya ...
8566     spacious prime location house is available in ...
8577     prime location 240 square yards house up for s...
8581     this is your chance to buy prime location hous...
8605       prime location house in naya nazimabad for sale
8608     secure gated community fresh apartment booking...
8637     ideally located prime location house for sale ...
8740     get in touch now to buy a prime location flat ...
8851     booked: 3 & 2 bedroom apartment in fresh proje...
8996     brand new 240 sq. yards football stadium facin...
9113     prime location naya nazimabad house sized 1750...
9143     naya nazimabad peace apartment | 6.5 years eas...
9255                2 bed dd apartment fl 7 naya nazimabad
9285            nayanazimabad peace apartments new com- 35
9411     luxurious 400 sq. yard villa | 8 bed dd | for ...
9471     fair-priced prime location 240 square yards ho...
9671           3 bed dd flats sale on 7 years payment plan
9956     prime location 1250 square feet flat for sale ...
10070    get in touch now to buy a prime location 1249 ...
10159    prime location flat of 1500 square feet is ava...
10389              3 bedroom lounge apartment for sale fl7
10467    beautifully constructed prime location house i...
10470    get in touch now to buy a prime location flat ...
10531    end your search for prime location flat here a...
10679    luxury living & business opportunities: 2 & 3 ...
10840    2 bed drawing lounge flat available on easy in...
10867    ready to buy a prime location house in naya na...
10939                      flat for sale in naya nazimabad
10996    prime location 1750 square feet flat in naya n...
11021    prime location 120 square yards house for sale...
11131    prime location flat sized 1280 square feet ava...
11157    a prime location house of 120 square yards in ...
11245    globe residency tower # fl-04 | 3 bed d/d | ma...
11332    prime location 1250 square feet flat for sale ...
11468    apartments available on booking 2 bed 3 bath e...
11540    prime location house of 160 square yards is av...
11740    get in touch now to buy a prime location 240 s...
11756                         240 sq. yds. luxury bungalow
11785                                   120 sq. yds. villa
11878    ready to buy a prime location house in naya na...
11971    prime location flat for sale in naya nazimabad...
12065    get in touch now to buy a prime location flat ...
12200    prime location in naya nazimabad house for sal...
12334    prime location 160 square yards house for sale...
12527    affordable prime location ready to move flat f...
12535    2 bed dd | fl 04 | semi furnished | 1250 sqft ...
12664    4 rooms flat | peace apartment | naya nazimaba...
13055    naya nazimabad stadium view residencia apartme...
13110    2 & 3 bedroom apartments for sale prime locati...
13112         prime location flat for sale in rs. 26750000
13334    prime location ideal house for sale in naya na...
13419        peace apartment com 35 # pre booking discount
13430      prime location house in naya nazimabad for sale
13438    prime location 120 square yards house for sale...
13516    your dream prime location 120 square yards hou...
13560            reserve a apartment now in naya nazimabad
13585    4 rooms luxury apartment in naya nazimabad ide...
13844                     120 square yards luxurious villa
13970    naya nazimabad peace apartment | 6.5 years eas...
14164    120 yards corner park face one unit bungalow f...
14218    prime location affordable house for sale in na...
14274    brand new apartment/flat in naya nazimabad fl-...
14276    luxury apartments for sale on installments glo...
14297    naya nazimabad com 50 ashaab builders stadium ...
14365    exclusive apartment projects on easy installme...
14441    your search for prime location house in naya n...
14488    in naya nazimabad you can find the perfect pri...
14678    ideal prime location house in naya nazimabad a...
14714    get in touch now to buy a prime location flat ...
14886         flat for sale naya naximabad globe residency
14957                240 sq. yds. luxurious villa for sale
15069                                  flat for sale fl-04
15115    globe residency apartments for sale comfort, c...
15159    prime location 1260 square feet flat available...
15161                  3 bedroom lounge available in f l 7
15178    prime location 1250 square feet flat for sale ...
15519    prime location 1750 square feet flat for sale ...
15541    prime location 1250 square feet flat for sale ...
15681            nayanazimabad peace apartments on booking
15858    naya nazimabad luxurious apartment | fl-07 | 4...
15930    get this amazing prime location 120 square yar...
16064    ready to buy a prime location house 1250 squar...
16080                peace apartment com 35 naya nazimabad
16098    prime location naya nazimabad flat sized 1500 ...
16102    prime location 120 square yards house for sale...
16118    a prime location house at affordable price awa...
16142    prime location house of 160 square yards is av...
16207    prime location house of 1750 square feet is av...
16250              2 bed dd apartments n easy payment plan
16312    a prime location 160 square yards house has la...
16350    a great choice for a prime location 1750 squar...
16403    centrally located prime location house availab...
16416    naya nazimabad | peace com 41 1775 sq feet fla...
16438    naya nazimabad luxurious apartment instalment ...
16489    prime location house of 120 square yards in na...
16693    avail yourself a great prime location 240 squa...
16706    change your address to prime location naya naz...
16843           3 bed lounge 2 bed dd flat peace apartment
16853    buying a prime location flat in naya nazimabad...
16870    naya nazimabad luxurious apartment | easy inst...
17111    spacious prime location flat is available for ...
17147    house available for sale brand new 160 square ...
17202    prime location 120 square yards house situated...
17267    buy prime location 1750 square feet flat at hi...
17365    centrally located prime location house in naya...
17527    2 bed d d apartment available at fl 4 naya naz...
17578                                 globe residency fl04
17711    buy your ideal prime location 160 square yards...
17807    prime location house of 120 square yards in na...
17849    your ideal prime location 1050 square feet fla...
17940    buy prime location 240 square yards house at h...
17981    this is your chance to buy prime location flat...
18040    a well designed prime location flat is up for ...
18077    looking for a prime location house in naya naz...
18095    a prime location 1250 square feet flat located...
18267                          peace apartment is for sale
18346                       luxurious villa  160 sq. yards
18392    flat for sale 1 year's easy payment plan in na...
18466     nayanazimabad peace apartments new com-35 lounge
18500    prime location in naya nazimabad flat for sale...
18514           160 yards double storey bungalow park face
18553          naya nazimabad fl-04 2 bed dd flat for sale
18625                     160 square yards luxury bungalow
18640    prime location house of 160 square yards for s...
18670    2 bed dd, 1250 square feet, -chance deal- glob...
18681    prime location 288 square yards house ideally ...
18689                                 globe residency fl07
18756    3-bedroom & 2-bedroom ready apartments in naya...
18757    stunning prime location house is available for...
18891    prime location 1750 square feet flat available...
18931    change your address to prime location naya naz...
19063    prime location naya nazimabad flat sized 1500 ...
19150    fair-priced prime location 1250 square feet fl...
19209    3 bed dd apartment for sell in naya nazimabad ...
19258       1250 sq. ft. apartment for sale naya nazimabad
19343    ideal prime location house in naya nazimabad a...
19352    this is your chance to buy prime location hous...
19457    corner/west open apartment globe residency fl0...
19559    investor deals booked limited units remaining ...
19621    looking for a prime location house in naya naz...
19688    prime location naya nazimabad flat sized 1750 ...
19750    2 & 3 bedroom luxury apartments in naya nazima...
19784    prime location naya nazimabad flat for sale si...
19971      2 bedroom drawing lounge apartment 6 years plan
20059    naya nazimabad ready to move apartment fl-04 5...
20080    naya nazimabad luxurious apartment easy instal...
20143    own a prime location flat in 1500 square feet ...
20207    flat for sale 1375 square feet naya nazimabad ...
20315    a prime location 1050 square feet flat located...
20447                       160 yards super luxury banglow
20456    a perfect prime location flat awaits you in na...
Name: property_name, dtype: object

In [53]:
df[(df['location'] == 'Naya Nazimabad') & (df['sub_location'].isnull())][
    'property_name'
].to_csv('Naya Nazimabad_null_sublocations.csv', index=True)

In [54]:
sublocation_count = (
    df.groupby(["location", "sub_location"])["sub_location"]
      .transform("count")
)
mask = (
    df["sub_location"].isna() |
    (sublocation_count < 5)
)

df.loc[mask, "sub_location"] = df.loc[mask, "location"]

In [55]:
df['sub_location'].isnull().sum()

np.int64(0)

In [56]:
df['location'].value_counts()

location
DHA Defence             4210
Scheme 33               3063
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
North Nazimabad         1020
Jamshed Town             980
Malir                    922
Clifton                  815
Gadap                    694
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            161
Shah Faisal              152
Korangi                  151
Karsaz                   124
Nazimabad                 82
Civil Lines               79
Saddar                    69
Defence View              47
Bin Qasim Town            39
Shahra-e-Faisal           34
Tipu Sultan Road          32
Northern Bypass           26
Name: count, dtype: int64

In [57]:
df['location_score'].isnull().sum()

np.int64(348)

In [58]:
df[df['location_score'].isnull()]['location'].value_counts()

location
Civil Lines         79
Saddar              69
Super Highway       54
Defence View        47
Tipu Sultan Road    32
Shahra-e-Faisal     31
Northern Bypass     26
Malir               10
Name: count, dtype: int64

In [66]:
location_score = {
    # 5 - Premium / Highly Desirable
    "DHA Defence": 5,
    "Clifton": 5,
    "Karsaz": 5,
    "Malir Cantt": 5,

    # 4 - High Demand / Established
    "Jamshed Town": 4,
    "Gulshan-e-Iqbal Town": 4,
    "Civil Lines": 4,
    "North Nazimabad": 4,
    "Federal B Area": 4,
    "Malir": 4,
    "Naya Nazimabad": 4,
    "Shahra-e-Faisal": 4,

    # 3 - Good Residential / Established
    "Gulistan-e-Jauhar": 3,
    "Scheme 33": 3,
    "Bahria Town": 3,
    "Nazimabad": 3,
    "Saddar": 3,
    "Shah Faisal": 3,

    # 2 - Developing / Moderate
    "Northern Bypass": 2,
    "North Karachi": 2,
    "Gadap": 2,
    "Super Highway": 2,

    # 1 - Lower Residential Desirability
    "Korangi": 1,
    "Bin Qasim Town": 1
}



df["location_score"] = df["location"].map(location_score)
df.groupby("location_score")["price_per_sqft"].agg(["count", "mean", "median"])

                count          mean    median
location_score
1                 190   8095.816158   5555.56
2                1260  14961.879167  13130.32
3                6353  16228.628102  13777.78
4                6371  25741.603562  23611.11
5                6284  35112.914086  32532.53

In [60]:
df.groupby('location')['price_crore'].agg(['mean','median']).sort_values(by='mean',ascending=False)

                           mean  median
location
Karsaz                21.504032  20.875
DHA Defence           15.325057  11.000
Tipu Sultan Road      11.398438   8.100
Jamshed Town           8.308224   5.500
Northern Bypass        8.050000   6.785
Gulshan-e-Iqbal Town   7.479763   4.000
Civil Lines            7.418228   8.250
Clifton                6.921080   5.850
Malir Cantt            6.689782   5.350
Shahra-e-Faisal        6.515441   3.750
Malir                  6.014009   5.700
North Nazimabad        5.831608   3.450
Federal B Area         5.731118   4.500
Shah Faisal            4.792592   1.225
Naya Nazimabad         3.993174   3.850
Gulistan-e-Jauhar      3.598153   2.300
Saddar                 2.772174   2.150
Bahria Town            2.613928   1.820
Scheme 33              2.610465   2.150
Defence View           2.522766   2.450
Nazimabad              2.353049   1.525
North Karachi          2.202858   1.950
Gadap                  2.067046   1.550
Super Highway          1.874963   1.600
Korangi                1.019185   0.300
Bin Qasim Town         0.337436   0.350

In [61]:
df.loc[df["location"] == "Tipu Sultan Road", "sub_location"] = "Tipu Sultan Road"
df.loc[df["sub_location"] == "Tipu Sultan Road", "location"] = "Jamshed Town"

In [62]:
same = df["location"].eq(df["sub_location"])

df.loc[same, "sub_location"] = (
    df.loc[same, "location"] + "_Unspecified"
)

In [63]:
mask = df["location"].eq("Defence View")

df.loc[mask, "location"] = "Jamshed Town"
df.loc[mask, "sub_location"] = "Defence View"

In [64]:
df[df['location']=='Jamshed Town']['sub_location'].value_counts()

sub_location
Pechs                                           268
Shaheed Millat Road                             173
Khalid Bin Walid Road                           121
Jamshed Road                                     60
Defence View                                     47
Smchs - Sindhi Muslim Society                    43
Karachi Administration Employees Society         41
Tariq Road                                       35
Amir Khusro                                      33
Jamshed Town_Unspecified                         32
Tipu Sultan Road                                 32
Garden East                                      31
Amil Colony                                      30
Soldier Bazar                                    20
Parsi Colony                                     20
Mehmoodabad                                      18
Cosmopolitan Society                             17
Shahra-E-Qaideen                                 14
Muslimabad Society                               12
Defence Skyline, Shaheed-E-Millat Expressway     12
Name: count, dtype: int64

In [68]:
import pandas as pd

# ============================================================
# Step 1: Calculate median price/sqft for each sub-location
# ============================================================

sub_stats = (
    df.groupby("sub_location")
      .agg(
          median_ppsqft=("price_per_sqft", "median"),
          count=("price_per_sqft", "size")
      )
      .reset_index()
)


# ============================================================
# Step 2: Calculate global percentile of sub-locations
# ============================================================

MIN_COUNT = 10

valid = sub_stats["count"] >= MIN_COUNT

sub_stats.loc[valid, "global_percentile"] = (
    sub_stats.loc[valid, "median_ppsqft"]
    .rank(method="average", pct=True)
)


# ============================================================
# Handle rare sub-locations
# ============================================================

median_pct = (
    sub_stats.loc[valid, "global_percentile"]
    .median()
)

sub_stats["global_percentile"] = (
    sub_stats["global_percentile"]
    .fillna(median_pct)
)


# ============================================================
# Step 3: Map percentile back to main dataframe
# ============================================================

pct_map = (
    sub_stats
    .set_index("sub_location")["global_percentile"]
)

df["global_percentile"] = (
    df["sub_location"].map(pct_map)
)


# ============================================================
# Step 4: Normalize parent location score
# 1–5 → 0–1
# ============================================================

parent_norm = (
    (df["location_score"] - 1) / 4
)


# ============================================================
# Step 5: Combine sub-location market value
# 80% sub-location market value
# 20% parent location desirability
# ============================================================

combined_score = (
    0.8 * df["global_percentile"] +
    0.2 * parent_norm
)


# ============================================================
# Step 6: Convert combined percentile to 1–5 score
# ============================================================

percentile = combined_score.rank(pct=True)

df["sub_location_score"] = pd.cut(
    percentile,
    bins=[0, 0.2, 0.4, 0.6, 0.8, 1],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
).astype(float)


# ============================================================
# Step 7: Handle Unspecified Sub-Locations
#
# If sub-location is:
#   Scheme 33_Unspecified
#   DHA Defence_Unspecified
#   Clifton_Unspecified
#
# use the parent location_score
# ============================================================

unknown_mask = (
    df["sub_location"]
    .str.endswith("_Unspecified", na=False)
)

df.loc[unknown_mask, "sub_location_score"] = (
    df.loc[unknown_mask, "location_score"]
)


# ============================================================
# Step 8: Safety fallback for any remaining NaN
# ============================================================

df["sub_location_score"] = (
    df["sub_location_score"]
    .fillna(df["location_score"])
)


# ============================================================
# Step 9: Convert to integer
# ============================================================

df["sub_location_score"] = (
    df["sub_location_score"]
    .astype(int)
)


# ============================================================
# Step 10: Remove helper column
# ============================================================

df.drop(
    columns=["global_percentile"],
    inplace=True
)


# ============================================================
# Step 11: Check result
# ============================================================

df.groupby("sub_location_score").agg(
    count=("sub_location", "count"),
    median_ppsqft=("price_per_sqft", "median")
)

                    count  median_ppsqft
sub_location_score
1                    3577      11111.110
2                    3468      15277.780
3                    4472      20283.215
4                    4465      26666.670
5                    4476      40000.000

In [69]:
df.groupby('sub_location_score')['price_crore'].agg(['count','mean','median'])

                    count       mean  median
sub_location_score
1                    3577   1.992770    1.50
2                    3468   3.122766    2.25
3                    4472   4.761355    3.50
4                    4465   8.075010    6.25
5                    4476  15.428023   11.00

In [70]:
df.groupby(['sub_location_score', 'location', 'sub_location'])['price_per_sqft'].agg(
    count='count',
    median_ppsqft='median'
).reset_index()

,sub_location_score,location,sub_location,count,median_ppsqft
0,1,Bahria Town,Bahria Apartments,74,8176.100
1,1,Bahria Town,Bahria Heights,47,7103.830
2,1,Bahria Town,Bahria Paradise,56,10222.220
3,1,Bahria Town,Bahria Sports City,94,6349.210
4,1,Bahria Town,Precinct 10A,50,11111.110
5,1,Bahria Town,Precinct 10B,42,10133.330
6,1,Bahria Town,Precinct 11A,58,10789.470
7,1,Bahria Town,Precinct 11B,48,10633.045
8,1,Bahria Town,Precinct 12,85,12888.890
9,1,Bahria Town,Precinct 15,17,10488.890
10,1,Bahria Town,Precinct 16,30,11213.085
11,1,Bahria Town,Precinct 17,19,11111.110
12,1,Bahria Town,Precinct 19,32,8467.505
13,1,Bahria Town,Precinct 27,40,7565.010
14,1,Bahria Town,Precinct 31,54,7328.610
15,1,Bahria Town,Precinct 4,37,12222.220
16,1,Bahria Town,Precinct 6,45,12888.890
17,1,Bahria Town,Precinct 9,54,13333.330
18,1,Bahria Town,Private High-Rises,70,6410.260
19,1,Bin Qasim Town,Mateen Complex,39,4444.440
20,1,Clifton,Gizri,21,8925.320
21,1,Federal B Area,Federal B Area Block 7,11,10416.670
22,1,Gadap,Gulshan-E-Maymar,436,13888.890
23,1,Gadap,Memon Goth,49,10925.930
24,1,Gadap,Surjani Town,209,10763.890
25,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 10,40,12258.650
26,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 11,29,13295.350
27,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 13,135,11310.710
28,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 17,104,7652.920
29,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 18,127,8492.570
30,1,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 20,33,9722.220
31,1,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13D3,32,11020.035
32,1,Jamshed Town,Mehmoodabad,18,7777.780
33,1,Korangi,Allahwala Town,99,5252.530
34,1,Korangi,Kda Employees Society,16,12037.040
35,1,Korangi,Korangi Industrial Area,19,6913.580
36,1,Korangi,Korangi_Unspecified,3,5888.890
37,1,Malir,Golden Town,16,6166.785
38,1,Malir,Jamia Millia Road,16,8541.665
39,1,Malir,Malir Link To Super Highway,82,12222.220
40,1,Malir,Malir Town Residency,11,6712.960
41,1,Nazimabad,Nazimabad 3,21,12012.010
42,1,North Nazimabad,North Nazimabad Block G,21,9958.070
43,1,North Nazimabad,North Nazimabad Block K,42,9987.520
44,1,Scheme 33,Falaknaz,108,13344.650
45,1,Scheme 33,Saadi Road,52,10893.740
46,1,Scheme 33,Sector 16-A,109,13205.830
47,1,Scheme 33,Sector 17-B,10,12345.790
48,1,Scheme 33,Sector 18-A,114,12165.240
49,1,Scheme 33,Sector 18-C,25,12449.800
50,1,Scheme 33,Sector 24-B,20,7980.545
51,1,Scheme 33,Sector 25-B,36,11577.445
52,1,Scheme 33,Sector 30,23,11024.310
53,1,Scheme 33,Sector 34-A,125,13366.750
54,1,Scheme 33,Sector 38-A,26,12522.400
55,1,Scheme 33,Sector 42-A,29,11168.380
56,1,Scheme 33,Sector 44,105,11695.910
57,1,Shah Faisal,Gohar Green City Cluster,41,12617.700
58,1,Shah Faisal,Green Town / Rafah-E-Aam Belt,24,7853.640
59,1,Shah Faisal,Shamsi / Al-Falah Belt,26,7222.220
60,1,Super Highway,DHA City,54,14076.575
61,1,Super Highway,Saima Villas,69,11666.670
62,2,Bahria Town,Precinct 1,54,14370.915
63,2,Bahria Town,Precinct 18,5,16666.670
64,2,Bahria Town,Precinct 2,92,13567.250
65,2,Bahria Town,Precinct 7,7,13333.330
66,2,Bahria Town,Precinct 8,75,14444.440
67,2,Federal B Area,Federal B Area Block 8,18,13813.810
68,2,Federal B Area,Federal B Area Block 9,19,15000.000
69,2,Federal B Area,Shahrah-E-Pakistan,10,15517.185
70,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 14,150,21064.815
71,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 16,74,15640.605
72,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 16A,22,19184.915
73,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 19,73,14675.050
74,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 3A,123,15579.070
75,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 5,26,14767.330
76,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 7,125,14619.880
77,2,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 8,7,18518.520
78,2,Gulistan-e-Jauhar,Safoora Goth,8,11126.735
79,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 1,144,14921.480
80,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 11,31,12637.100
81,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13-C,15,15618.030
82,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13A,39,15046.300
83,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13B,24,13972.615
84,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13C,37,15555.560
85,2,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13D2,74,13676.310
86,2,Jamshed Town,"Defence Skyline, Shaheed-E-Millat Expressway",12,17768.670
87,2,Jamshed Town,Defence View,47,17450.140
88,2,Jamshed Town,Jamshed Road,60,17125.475
89,2,Jamshed Town,Karachi Administration Employees Society,41,15046.300
90,2,Malir,Airport,65,14722.220
91,2,Malir,Falaknaz,113,11574.070
92,2,Nazimabad,Nazimabad 1,13,13532.760
93,2,Nazimabad,Nazimabad 2,8,14822.800
94,2,Nazimabad,Nazimabad 4,24,15323.850
95,2,Nazimabad,Nazimabad 5,9,12051.730
96,2,North Karachi,New Karachi,9,12512.510
97,2,North Karachi,North Karachi Sector 11,78,18904.320
98,2,North Karachi,North Karachi Sector 5,47,16666.670
99,2,North Karachi,North Karachi Sector 7,36,15416.670
100,2,North Karachi,North Karachi_Unspecified,53,7977.210
101,2,North Karachi,sector 11a,9,7142.860
102,2,North Nazimabad,North Nazimabad Block B,81,18257.690
103,2,North Nazimabad,North Nazimabad Block F,179,18726.590
104,2,North Nazimabad,North Nazimabad Block M,52,13033.525
105,2,Northern Bypass,Northern Bypass_Unspecified,26,21460.315
106,2,Scheme 33,Gulshan-E-Maymar,6,11415.940
107,2,Scheme 33,Gulshan-e-Usman Housing Society,17,14351.850
108,2,Scheme 33,Saadi Garden,169,16203.700
109,2,Scheme 33,Sector 15-A,91,16666.670
110,2,Scheme 33,Sector 19-A,93,16003.320
111,2,Scheme 33,Sector 22-A,18,19166.665
112,2,Scheme 33,Sector 24-A,30,20370.370
113,2,Scheme 33,Sector 29,143,13420.720
114,2,Scheme 33,Sector 40,251,14464.460
115,2,Scheme 33,Sector 43-A,48,15871.915
116,2,Scheme 33,Sector 45-A,10,13993.320
117,2,Scheme 33,Sector 47,260,18055.560
118,2,Scheme 33,Sector 51-A,47,20833.330
119,2,Scheme 33,Sector 52-A,28,19675.925
120,2,Scheme 33,Yousaf Goth,5,13425.930
121,2,Super Highway,Oasis Park Residencia,6,19444.440
122,2,Super Highway,Rabia Enclave,9,10555.560
123,2,Super Highway,Super Highway_Unspecified,23,12962.960
124,3,Bahria Town,Bahria Town_Unspecified,54,9836.170
125,3,Clifton,Clifton Block 1,88,18940.480
126,3,Clifton,Clifton Block 4,51,20656.660
127,3,DHA Defence,Phase 1,64,22222.220
128,3,DHA Defence,Phase 2 Extension,68,16778.630
129,3,Federal B Area,Federal B Area Block 10,65,22222.220
130,3,Federal B Area,Federal B Area Block 11,28,21990.740
131,3,Federal B Area,Federal B Area Block 20,10,21064.815
132,3,Federal B Area,Federal B Area Block 21,42,19569.545
133,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 1,40,22671.295
134,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 12,105,22222.220
135,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 15,193,21145.710
136,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 2,94,23541.665
137,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 4,35,24305.560
138,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 9,15,22222.220
139,3,Gulistan-e-Jauhar,Gulistan-e-Jauhar_Unspecified,100,14957.120
140,3,Gulshan-e-Iqbal Town,"Cp Barar Society, Gulshan-E-Iqbal Town",13,22435.900
141,3,Gulshan-e-Iqbal Town,Dhoraji Colony,56,23286.760
142,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 10,23,21527.780
143,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 10A,426,19352.090
144,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13D,54,24189.815
145,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 14,16,21669.135
146,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 16,23,22159.800
147,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 2,106,19106.410
148,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 4,105,21111.110
149,3,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 7,90,22824.075
150,3,Gulshan-e-Iqbal Town,Sharfabad,46,23882.850
151,3,Jamshed Town,Amil Colony,30,23178.175
152,3,Jamshed Town,Muslimabad Society,12,24451.100
153,3,Jamshed Town,Parsi Colony,20,21342.405
154,3,Jamshed Town,Soldier Bazar,20,21370.465
155,3,Jamshed Town,Tariq Road,35,23286.760
156,3,Korangi,Qayyumabad,14,29123.760
157,3,Malir Cantt,Askari 5,499,17186.250
158,3,Nazimabad,Nazimabad_Unspecified,7,11211.210
159,3,North Karachi,Buffer Zone,95,25347.220
160,3,North Karachi,North Karachi Sector 8,14,23564.815
161,3,North Karachi,North Karachi Sector 9,24,25925.930
162,3,North Nazimabad,North Nazimabad Block A,45,23611.110
163,3,North Nazimabad,North Nazimabad Block D,44,21566.790
164,3,North Nazimabad,North Nazimabad Block H,122,19998.255
165,3,North Nazimabad,North Nazimabad Block J,35,20833.330
166,3,North Nazimabad,North Nazimabad Block L,117,23003.470
167,3,North Nazimabad,North Nazimabad Block N,113,22065.730
168,3,North Nazimabad,Shadman,43,23148.150
169,3,Saddar,Saddar_Unspecified,69,15027.320
170,3,Scheme 33,Meerut Society,57,22222.220
171,3,Scheme 33,Punjabi Saudagar Society,147,24768.520
172,3,Scheme 33,Scheme 33_Unspecified,302,12624.595
173,3,Scheme 33,Sector 17-A,114,25000.000
174,3,Scheme 33,Sector 20-A,22,22314.815
175,3,Scheme 33,Sector 35-A,305,22222.220
176,3,Scheme 33,Sector 36-A,97,26388.890
177,3,Scheme 33,Sector 48-A,13,25925.930
178,3,Shah Faisal,Saima Luxury Belt,33,23148.150
179,3,Shah Faisal,Shah Faisal_Unspecified,14,8143.275
180,4,Civil Lines,Civil Lines_Unspecified,79,31718.570
181,4,Clifton,Clifton Block 2,161,22772.770
182,4,Clifton,Clifton Block 3,11,23611.110
183,4,Clifton,Clifton Block 5,34,27402.405
184,4,Clifton,Clifton Block 7,40,28570.240
185,4,Clifton,Clifton Block 8,88,30166.530
186,4,Clifton,Clifton Block 9,92,28115.160
187,4,Clifton,Frere Town,43,27777.780
188,4,DHA Defence,Phase 2,52,28888.890
189,4,DHA Defence,Phase 5,449,25555.560
190,4,DHA Defence,Phase 5 Extension,21,28888.890
191,4,Federal B Area,Federal B Area Block 12,50,29444.445
192,4,Federal B Area,Federal B Area Block 13,39,25000.000
193,4,Federal B Area,Federal B Area Block 14,19,32870.370
194,4,Federal B Area,Federal B Area Block 15,13,30092.590
195,4,Federal B Area,Federal B Area Block 16,14,29259.260
196,4,Federal B Area,Federal B Area Block 19,17,28703.700
197,4,Federal B Area,Federal B Area Block 6,12,29686.680
198,4,Federal B Area,Federal B Area_Unspecified,58,25000.000
199,4,Gulistan-e-Jauhar,Askari 4,32,27386.485
200,4,Gulistan-e-Jauhar,Gulistan-e-Jauhar Block 3,58,28819.445
201,4,Gulshan-e-Iqbal Town,Bahadurabad,116,28007.320
202,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13,12,28819.445
203,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 13D1,65,37037.040
204,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 19,18,32986.110
205,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 21,13,28888.890
206,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 3,40,26620.370
207,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 5,77,31944.440
208,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 6,58,27777.780
209,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 9,17,28571.430
210,4,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Town_Unspecified,188,17357.210
211,4,Jamshed Town,Cosmopolitan Society,17,25025.030
212,4,Jamshed Town,Garden East,31,25905.120
213,4,Jamshed Town,Jamshed Town_Unspecified,32,40000.000
214,4,Jamshed Town,Khalid Bin Walid Road,121,27126.740
215,4,Jamshed Town,Pechs,268,32532.530
216,4,Jamshed Town,Shaheed Millat Road,173,31500.570
217,4,Jamshed Town,Shahra-E-Qaideen,14,28584.875
218,4,Jamshed Town,Smchs - Sindhi Muslim Society,43,29782.360
219,4,Jamshed Town,Tipu Sultan Road,32,36539.745
220,4,Malir,Falcon Complex New Malir,449,26444.440
221,4,Malir,Malir_Unspecified,35,13777.780
222,4,Malir,Model Colony,98,25000.000
223,4,Malir,Saima Projects,37,25000.000
224,4,Malir Cantt,Askari 6,490,24518.515
225,4,Naya Nazimabad,Naya Nazimabad Block B,53,27777.780
226,4,Naya Nazimabad,Naya Nazimabad Block D,66,34856.150
227,4,Naya Nazimabad,Naya Nazimabad Block M,23,27777.780
228,4,Naya Nazimabad,Naya Nazimabad_Unspecified,301,17377.570
229,4,North Karachi,North Karachi Sector 10,14,30138.890
230,4,North Nazimabad,North Nazimabad Block C,12,30555.560
231,4,North Nazimabad,North Nazimabad Block I,34,24765.510
232,4,North Nazimabad,North Nazimabad_Unspecified,80,17388.445
233,4,Scheme 33,Phase 2,8,12731.480
234,4,Shah Faisal,Falcon Complex Faisal,14,76666.670
235,4,Shahra-e-Faisal,Shahra-e-Faisal_Unspecified,34,18937.595
236,5,Clifton,Bath Island,123,32532.530
237,5,Clifton,Clifton Block 6,11,32771.540
238,5,Clifton,Clifton_Unspecified,52,27012.190
239,5,DHA Defence,DHA Defence_Unspecified,26,36486.795
240,5,DHA Defence,Phase 4,156,40740.740
241,5,DHA Defence,Phase 6,886,31111.110
242,5,DHA Defence,Phase 7,286,32222.220
243,5,DHA Defence,Phase 7 Extension,141,55555.560
244,5,DHA Defence,Phase 8,2049,44117.650
245,5,DHA Defence,Phase 8 Extension,12,50000.000
246,5,Gulshan-e-Iqbal Town,Adamjee Nagar,16,55555.560
247,5,Gulshan-e-Iqbal Town,Gulshan-e-Iqbal Block 17,97,48888.890
248,5,Gulshan-e-Iqbal Town,Kda Scheme 1,84,40740.740
249,5,Gulshan-e-Iqbal Town,Kda Scheme 1 Extension,11,46666.670
250,5,Gulshan-e-Iqbal Town,Mohammad Ali Society,17,48000.000
251,5,Gulshan-e-Iqbal Town,National Stadium Colony,22,114271.940
252,5,Jamshed Town,Amir Khusro,33,48666.670
253,5,Karsaz,Navy Housing Scheme Karsaz,124,64285.715
254,5,Malir Cantt,Dohs Phase 1,40,34595.955
255,5,Malir Cantt,Dohs Phase 2,11,31313.130
256,5,Malir Cantt,Malir Cantt_Unspecified,95,17298.740
257,5,Naya Nazimabad,Naya Nazimabad Block A,93,40277.780
258,5,Naya Nazimabad,Naya Nazimabad Block C,91,37847.220

In [71]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,...,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score,expected_floors
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,...,house,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2,NaN
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,...,house,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2,2.0
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,...,flat,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2,NaN
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,...,flat,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4,NaN
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,...,flat,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2,NaN

In [72]:
df['property_age'].isnull().sum()

np.int64(9606)

In [73]:
df['district'].isnull().sum()

np.int64(385)

In [74]:
df[df['district'].isnull()]['location'].value_counts().index

Index(['Civil Lines', 'Jamshed Town', 'Saddar', 'Super Highway',
       'Gulshan-e-Iqbal Town', 'Shahra-e-Faisal', 'Northern Bypass', 'Malir'],
      dtype='object', name='location')

In [117]:
district_mapping = {
    # Karachi South
    "DHA Defence": "Karachi South",
    "Clifton": "Karachi South",

    # Karachi East
    "Karsaz": "Karachi East",
    "Gulshan-e-Iqbal Town": "Karachi East",
    "Gulistan-e-Jauhar": "Karachi East",
    "Jamshed Town": "Karachi East",
    "Scheme 33": "Karachi East",

    # Karachi Central
    "Federal B Area": "Karachi Central",
    "F.B. Area": "Karachi Central",
    "North Nazimabad": "Karachi Central",
    "North Karachi": "Karachi Central",
    "Nazimabad": "Karachi Central",
    "Naya Nazimabad": "Karachi Central",

    # Malir
    "Malir": "Malir",
    "Malir Cantt": "Malir",
    "Gadap": "Malir",
    "Super Highway": "Malir",
    "Bahria Town": "Malir",
    "Bin Qasim Town": "Malir",

    # Korangi
    "Korangi": "Korangi",
    "Shah Faisal": "Korangi"
}

In [76]:
df['district'].value_counts()

district
Karachi East       8077
Karachi South      5025
Malir              4126
Karachi Central    2533
Korangi             312
Name: count, dtype: int64

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20458 entries, 0 to 20478
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20458 non-null  object
 1   address             20458 non-null  object
 2   location            20458 non-null  object
 3   sub_location        20458 non-null  object
 4   price               20458 non-null  float64
 5   price_crore         20458 non-null  float64
 6   price_per_sqft      20458 non-null  float64
 7   area                20458 non-null  float64
 8   bedrooms            20458 non-null  int64
 9   bathrooms           20458 non-null  int64
 10  kitchen             20458 non-null  float64
 11  floor               4008 non-null   float64
 12  total_floors        9609 non-null   float64
 13  parking             20458 non-null  float64
 14  elevator            20458 non-null  int64
 15  servant_quarters    20458 non-null  float64
 16  electricity_backup  20458 non-null  int64
 17  furnished           20458 non-null  int64
 18  completion_year     10852 non-null  float64
 19  property_type       20458 non-null  object
 20  property_age        10852 non-null  float64
 21  age_category        10852 non-null  object
 22  parking_score       20458 non-null  int64
 23  area_per_bedroom    20458 non-null  float64
 24  district            20073 non-null  object
 25  sub_location_type   20458 non-null  object
 26  location_score      20458 non-null  int64
 27  sub_location_score  20458 non-null  int64
dtypes: float64(12), int64(8), object(8)
memory usage: 5.0+ MB

In [78]:
df[df['sub_location_type'].isnull()]['sub_location'].value_counts()

sub_location
Scheme 33_Unspecified               302
Naya Nazimabad_Unspecified          301
Gulshan-e-Iqbal Town_Unspecified    188
Gulistan-e-Jauhar_Unspecified        96
Malir Cantt_Unspecified              95
North Nazimabad_Unspecified          80
Civil Lines_Unspecified              79
Saddar_Unspecified                   69
Federal B Area_Unspecified           58
Bahria Town_Unspecified              54
DHA City                             54
North Karachi_Unspecified            53
Clifton_Unspecified                  52
Defence View                         47
Sector 29                            43
Malir_Unspecified                    35
Shahra-e-Faisal_Unspecified          34
Tipu Sultan Road                     32
Phase 5                              28
DHA Defence_Unspecified              26
Northern Bypass_Unspecified          26
Naya Nazimabad Block C               24
Super Highway_Unspecified            23
Mateen Complex                       23
Naya Nazimabad Block A               21
Airport                              17
Sector 40                            16
Naya Nazimabad Block D               14
Shah Faisal_Unspecified              14
Gulistan-e-Jauhar Block 13           10
sector 11a                            9
Sector 19-A                           8
Gulistan-e-Jauhar Block 2             8
Phase 2                               8
National Stadium Colony               8
Gulistan-e-Jauhar Block 14            8
Sector 24-A                           8
Gulistan-e-Jauhar Block 15            7
Jamshed Town_Unspecified              7
Nazimabad_Unspecified                 7
Naya Nazimabad Block M                7
Gulistan-e-Jauhar Block 19            6
Gulshan-E-Maymar                      6
Gulistan-e-Jauhar Block 3A            6
Sector 17-A                           5
Gulshan-e-Iqbal Block 4               5
Naya Nazimabad Block B                5
Nazimabad 1                           5
Gulistan-e-Jauhar Block 16            5
Sector 35-A                           4
Gulshan-e-Iqbal Block 2               4
Gulistan-e-Jauhar Block 7             4
Gulshan-e-Iqbal Block 13D2            4
Sector 34-A                           4
Nazimabad 2                           4
Gulshan-e-Iqbal Block 10A             4
Gulistan-e-Jauhar Block 4             4
Gulshan-e-Iqbal Block 13D             3
Saadi Garden                          3
Korangi_Unspecified                   3
North Karachi Sector 5                3
Gulshan-e-Iqbal Block 5               3
Gulshan-e-Iqbal Block 1               3
Gulistan-e-Jauhar Block 10            3
Gulistan-e-Jauhar Block 5             3
Gulistan-e-Jauhar Block 12            3
Sector 25-B                           3
Gulistan-e-Jauhar Block 3             2
Clifton Block 2                       2
North Karachi Sector 11               2
Sector 15-A                           2
Nazimabad 4                           2
Gulshan-e-Iqbal Block 10              2
Gulistan-e-Jauhar Block 16A           2
Model Colony                          2
Clifton Block 9                       2
Gulshan-e-Iqbal Block 13              2
Phase 6                               2
Gulshan-e-Iqbal Block 7               2
Gulshan-e-Iqbal Block 11              2
Sector 30                             2
Precinct 8                            2
Bahria Heights                        2
Nazimabad 3                           1
Precinct 2                            1
Gulshan-e-Iqbal Block 6               1
Amil Colony                           1
Sector 18-A                           1
Gulistan-e-Jauhar Block 1             1
Jamshed Road                          1
Precinct 4                            1
Gulistan-e-Jauhar Block 9             1
Punjabi Saudagar Society              1
Federal B Area Block 9                1
Bahria Sports City                    1
Gulshan-e-Iqbal Block 13A             1
Federal B Area Block 20               1
Precinct 10A                          1
Federal B Area Block 11               1
Gulshan-e-Iqbal Block 19              1
Gulistan-e-Jauhar Block 11            1
Gulistan-e-Jauhar Block 17            1
Clifton Block 1                       1
Nazimabad 5                           1
Federal B Area Block 21               1
Askari 5                              1
Askari 6                              1
Falaknaz                              1
Sector 42-A                           1
Gulshan-e-Iqbal Block 3               1
Sector 44                             1
Gulistan-e-Jauhar Block 18            1
Bath Island                           1
Precinct 19                           1
Precinct 1                            1
Precinct 6                            1
Name: count, dtype: int64

In [79]:
sub_location_type_mapping = {

    "Sector 29": "Subdivision",
    "Sector 40": "Subdivision",
    "Sector 35-A": "Subdivision",
    "Sector 19-A": "Subdivision",
    "Sector 24-A": "Subdivision",
    "Sector 17-A": "Subdivision",
    "Sector 25-B": "Subdivision",
    "Sector 15-A": "Subdivision",
    "Sector 18-A": "Subdivision",
    "Sector 42-A": "Subdivision",
    "Sector 44": "Subdivision",
    "Sector 30": "Subdivision",
    "sector 11a": "Subdivision",

    "Phase 2": "Subdivision",
    "Phase 5": "Subdivision",
    "Phase 6": "Subdivision",

    "Naya Nazimabad Block A": "Subdivision",
    "Naya Nazimabad Block B": "Subdivision",
    "Naya Nazimabad Block C": "Subdivision",
    "Naya Nazimabad Block D": "Subdivision",
    "Naya Nazimabad Block M": "Subdivision",

    "Gulshan-e-Iqbal Block 1": "Subdivision",
    "Gulshan-e-Iqbal Block 2": "Subdivision",
    "Gulshan-e-Iqbal Block 3": "Subdivision",
    "Gulshan-e-Iqbal Block 4": "Subdivision",
    "Gulshan-e-Iqbal Block 5": "Subdivision",
    "Gulshan-e-Iqbal Block 6": "Subdivision",
    "Gulshan-e-Iqbal Block 7": "Subdivision",
    "Gulshan-e-Iqbal Block 10": "Subdivision",
    "Gulshan-e-Iqbal Block 10A": "Subdivision",
    "Gulshan-e-Iqbal Block 11": "Subdivision",
    "Gulshan-e-Iqbal Block 13": "Subdivision",
    "Gulshan-e-Iqbal Block 13A": "Subdivision",
    "Gulshan-e-Iqbal Block 13D": "Subdivision",
    "Gulshan-e-Iqbal Block 13D2": "Subdivision",
    "Gulshan-e-Iqbal Block 19": "Subdivision",

    "Gulistan-e-Jauhar Block 1": "Subdivision",
    "Gulistan-e-Jauhar Block 2": "Subdivision",
    "Gulistan-e-Jauhar Block 3": "Subdivision",
    "Gulistan-e-Jauhar Block 3A": "Subdivision",
    "Gulistan-e-Jauhar Block 4": "Subdivision",
    "Gulistan-e-Jauhar Block 5": "Subdivision",
    "Gulistan-e-Jauhar Block 7": "Subdivision",
    "Gulistan-e-Jauhar Block 9": "Subdivision",
    "Gulistan-e-Jauhar Block 10": "Subdivision",
    "Gulistan-e-Jauhar Block 11": "Subdivision",
    "Gulistan-e-Jauhar Block 12": "Subdivision",
    "Gulistan-e-Jauhar Block 13": "Subdivision",
    "Gulistan-e-Jauhar Block 14": "Subdivision",
    "Gulistan-e-Jauhar Block 15": "Subdivision",
    "Gulistan-e-Jauhar Block 16": "Subdivision",
    "Gulistan-e-Jauhar Block 16A": "Subdivision",
    "Gulistan-e-Jauhar Block 17": "Subdivision",
    "Gulistan-e-Jauhar Block 18": "Subdivision",
    "Gulistan-e-Jauhar Block 19": "Subdivision",

    "Federal B Area Block 9": "Subdivision",
    "Federal B Area Block 11": "Subdivision",
    "Federal B Area Block 20": "Subdivision",
    "Federal B Area Block 21": "Subdivision",

    "Nazimabad 1": "Subdivision",
    "Nazimabad 2": "Subdivision",
    "Nazimabad 3": "Subdivision",
    "Nazimabad 4": "Subdivision",
    "Nazimabad 5": "Subdivision",

    "North Karachi Sector 5": "Subdivision",
    "North Karachi Sector 11": "Subdivision",

    "Precinct 1": "Subdivision",
    "Precinct 2": "Subdivision",
    "Precinct 4": "Subdivision",
    "Precinct 6": "Subdivision",
    "Precinct 8": "Subdivision",
    "Precinct 10A": "Subdivision",
    "Precinct 19": "Subdivision",

    "Punjabi Saudagar Society": "Housing Society",

    "Askari 5": "Military Housing",
    "Askari 6": "Military Housing",


    "Mateen Complex": "Residential Project",
    "Bahria Heights": "Residential Project",
    "Bahria Sports City": "Residential Project",
    "Falaknaz": "Residential Project",


    "Tipu Sultan Road": "Road",
    "Jamshed Road": "Road",
    "Shahra-e-Faisal": "Road",
    "Super Highway_Unspecified": "Unspecified",
    "Northern Bypass_Unspecified": "Unspecified",


    "Saadi Garden": "Neighbourhood",
    "Gulshan-E-Maymar": "Neighbourhood",
    "National Stadium Colony": "Neighbourhood",
    "Amil Colony": "Neighbourhood",
    "Model Colony": "Neighbourhood",
    "Bath Island": "Neighbourhood",
    "Airport": "Neighbourhood",
    "Jamshed Town_Unspecified": "Unspecified",
}

df["sub_location_type"] = df["sub_location"].map(sub_location_type_mapping).fillna(
    df["sub_location_type"]
)

In [80]:
df[df['sub_location_type'].isnull()]['sub_location'].value_counts()

sub_location
Scheme 33_Unspecified               302
Naya Nazimabad_Unspecified          301
Gulshan-e-Iqbal Town_Unspecified    188
Gulistan-e-Jauhar_Unspecified        96
Malir Cantt_Unspecified              95
North Nazimabad_Unspecified          80
Civil Lines_Unspecified              79
Saddar_Unspecified                   69
Federal B Area_Unspecified           58
DHA City                             54
Bahria Town_Unspecified              54
North Karachi_Unspecified            53
Clifton_Unspecified                  52
Defence View                         47
Malir_Unspecified                    35
Shahra-e-Faisal_Unspecified          34
DHA Defence_Unspecified              26
Shah Faisal_Unspecified              14
Nazimabad_Unspecified                 7
Sector 34-A                           4
Korangi_Unspecified                   3
Clifton Block 9                       2
Clifton Block 2                       2
Clifton Block 1                       1
Name: count, dtype: int64

In [81]:
sub_location_type_mapping = {

    # ---------------------------------------------------------
    # Unspecified parent-level locations
    # ---------------------------------------------------------
    "Scheme 33_Unspecified": "Unspecified",
    "Naya Nazimabad_Unspecified": "Unspecified",
    "Gulshan-e-Iqbal Town_Unspecified": "Unspecified",
    "Gulistan-e-Jauhar_Unspecified": "Unspecified",
    "Malir Cantt_Unspecified": "Unspecified",
    "North Nazimabad_Unspecified": "Unspecified",
    "Civil Lines_Unspecified": "Unspecified",
    "Saddar_Unspecified": "Unspecified",
    "Federal B Area_Unspecified": "Unspecified",
    "Bahria Town_Unspecified": "Unspecified",
    "North Karachi_Unspecified": "Unspecified",
    "Clifton_Unspecified": "Unspecified",
    "Malir_Unspecified": "Unspecified",
    "Shahra-e-Faisal_Unspecified": "Unspecified",
    "DHA Defence_Unspecified": "Unspecified",
    "Shah Faisal_Unspecified": "Unspecified",
    "Nazimabad_Unspecified": "Unspecified",
    "Korangi_Unspecified": "Unspecified",

    # ---------------------------------------------------------
    # DHA City
    # ---------------------------------------------------------
    "DHA City": "Housing Society",

    # ---------------------------------------------------------
    # Defence View
    # ---------------------------------------------------------
    "Defence View": "Housing Society",

    # ---------------------------------------------------------
    # Sectors
    # ---------------------------------------------------------
    "Sector 34-A": "Subdivision",

    # ---------------------------------------------------------
    # Clifton Blocks
    # ---------------------------------------------------------
    "Clifton Block 1": "Subdivision",
    "Clifton Block 2": "Subdivision",
    "Clifton Block 9": "Subdivision",
}
df["sub_location_type"] = df["sub_location"].map(sub_location_type_mapping).fillna(
    df["sub_location_type"]
)

In [82]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,...,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score,expected_floors
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,...,house,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2,NaN
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,...,house,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2,2.0
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,...,flat,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2,NaN
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,...,flat,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4,NaN
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,...,flat,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2,NaN

In [83]:
floor_rows = df[
    df["property_name"]
    .astype(str).str.contains("floor", case=False, na=False)
]

floor_rows

                                           property_name  \
99     1100 sq feet 2-bed dd apartment for sale on 2n...
106    main alamgir road 1st floor apartment lift sta...
117    saadi town block 7 extension  120 square yards...
126                luxurious 4 bed dd naz no-4 2nd floor
132    urgent house for sale in block 6 federal b are...
193    ground rcc + 1st floor 2 room precast, 80 yard...
198    apartment for sale dha phase 2 extension west ...
271    karachi university co operative housing societ...
298    studio apartment for sale 4th floor bukhari co...
326                 2nd floor 3 beds drawing dining flat
355    emaar oceanfront! 2bed apartment for sale in c...
378    brand new ground plus2 . . . . 7crore. 90lac d...
384    120sqyd brand new house, nearest to the main e...
386    dha phase 5 500 yards 5 bedrooms tile flooring...
390    4 bed dd 1st floor west open near family park ...
401    _emaar - the views_ | 2 bed brand new fully fu...
436             2 bed lounge 4th floor flat without lift
473    dha phase 7 540 yards 5 bedrooms west open mar...
482    ultra luxury full sea-facing (3b-1) 3br + maid...
536                         3rd floor with roof for sale
556    2nd floor 150 feet road apposite kfc. parking ...
581    higher floor 2 bed full sea facing in pearl to...
627    *alrauf sky tower* inverstor deal | 2bed drawi...
630    flat available for sale 3rd floor with roof | ...
631    500 sq yards bungalow near hill park basement ...
721    4 bedroom west open apartment on 8th floor ask...
726     3bdd 1950 sqft 4 floor lease airport facing. . .
738    brand new 500 sq yard beautiful house with bas...
740    2 bed drawing lounge 3rd floor flat available ...
774    excellent 1200 square feet 4th floor apartment...
790    flat for sale 3 bed dd flat 2239 sq feet g+3 t...
804    ground floor apartment for sale available in b...
806    creek vista 3-bedrooms apartment for sale west...
834                   big nishat com 3rd floor with lift
876                   flat for sale. 2 bed dd, 1st floor
1002   tower 24 6th floor ready to move 955sq ft 2 be...
1056   luxury 3-beddd apartment (stylishly converted ...
1059   flat for sale 1100 square feet 2 bedrooms draw...
1067   premium corner house, west open, in capital so...
1079   vip block 15 beautiful project al afnan arcade...
1081                       1st floor apartment available
1097   5th floor 3 bedroom apartment | sehar commerci...
1139   brand new 2 bedroom drawing room and lounge fl...
1156   iqbal plaza ground floor flat available for sa...
1165   fully renovated seaview apartment second floor...
1169         falaknaz twin tower 5th floor flat for sale
1185   ground floor west open flat available for sale...
1187   200 sq yard 3rd floor paint house 4 bed withou...
1195   apartment for sale in rufi green city  3 bed d...
1222   seaview apartment first floor ff-2 available f...
1230          prime location of block j third floor flat
1276   400 square yards double storey house each floo...
1290   chance deal , west open lower floor in saima r...
1326     flat for sale 3rd floor block k north nazimabad
1392   fully renovated sea view apartment 2nd floor sv 5
1420   1150 sq ft full floor beautiful, specious & lu...
1443   1st floor 2 bed dd corner west open flat for s...
1448   first floor flat available for sale at very pr...
1449   tower h 8th floor outer park face ready to mov...
1517   brand new 2 bedroom drawing room and lounge on...
1611   2 bed lounge lease apartment for sale | ground...
1628   on cash only west open 2 bedroom and lounge 5t...
1647   chance deal , 2 bed dd, 2nd floor after mezzan...
1654   1st floor 3bedroom apartment in towers near sh...
1658   2b-1 two bedroom apartment marina beach higher...
1682   spacious2 bed lounge ground floor flat for sal...
1698   2-bed dd ground floor cottage for sale kings c...
1706   luxury apartment for sale very well maintained...
1744   fully renovated seaview apartment ground floor...
1746   babar vista | bank loan applicable | k block |...
1772   flat for sale ground floor block h 2 bed dd fo...
1786   3 side corner flat 2 bed dd 4th floor lift not...
1798   4bed dd flat is available for sale brand new  ...
1842   safa residency | 1st floor | with extra land /...
1869   ground+2 floor house block 12 gulistan e jauha...
2017   dha phase 1 1000 yards 5 bedrooms tile floorin...
2046   just like new, ground floor apartment like bun...
2078   flat for sale in karachi administration societ...
2089    brand new house 240 square yard ground + 2 floor
2111   close to baitus salam masjid west open owner b...
2120                           first floor flat for sale
2126   west open 3 bed dd flat for sale sector j aska...
2155   beautiful 9th floor 2 bed lounge road facing w...
2168   fully renovated 3 bedrooms apartment for sale ...
2174   3 bed dd flat for sale fully renovated fully f...
2183       dha studio 1st floor west open prime location
2239   flat for sale phase 2 e x t d h a 3 bed d/d 3r...
2272   3rd floor north west leased 3 bed apartment av...
2290   2 bed dd apartment for sale | 950 sq. ft. | 1s...
2295   al minal tower 01 1500 sq ft | 5th floor | 3 b...
2345   3 bed dd brand new ground floor, main road fac...
2353   seaview apartment second floor available for sale
2356   "luxurious 120 yards bungalow ground + 2 floor...
2394   3bdd 1450 sqft 3 floor corner very good condit...
2397   sefacing luxury sea view apartment second floo...
2408   ground floor flats for sale in north nazimabad...
2416   first floor 2 bed dd flat for sale in paradise...
2421   bungalow facing three bed dd apartment for sal...
2433   brand new flat on 4 floor with roof, 2 bed lou...
2441   2 bed dd, 1st floor , with lift, 1000 sqft, 3 ...
2468   1st floor west open flat 2 bed dd rabia enclav...
2484   brand new luxury 120 sq yards ground +1 floor ...
2493    2nd floor west open corner flat sized 2700 sq ft
2504   lakhani fantasia 2 bed d 1sr floor lease bank ...
2529   westopen 1st floor newly renovated flat in bou...
2532   brand new 120 sq yards g+1 house for sale in g...
2541   luxury with a view 2 bed dd with exclusive roo...
2544   dha phase 7 500 yards 5 bedrooms with basement...
2570   3b-2 full sea facing panorama tower of emaar f...
2579   2 sided corner 400 yard house ground plus 2 fl...
2581   bank loan applicable brand new 3rd floor flat ...
2595   2-bed flat | 4th floor | lift | near chai mast...
2614                                  2 bed dd 3rd floor
2673   leased flat for sale, 2-bed dd, 10th floor, we...
2736   brand new, 3rd floor 2 bed lounge flat for sal...
2756   park-facing 4-bed flat for sale prime location...
2758   1 bed lounge ground floor karachi university s...
2806   5 rooms super appartment in "rao & israr heigh...
2826   ground plus one good condition each floor 3 be...
2832                4th floor flat is available for sale
2926   gulistan e johar block 12 400 sq yd vvip luxur...
2938               noman avenue 8th floor flat with lift
2962   gulistan e johar block 15 300 sq yard g+1 | 3 ...
2980       west open 3 bed dd ground floor flat for sale
2993   spacious apartment available dha phase 2 exten...
2996   proper 2 unit with basement bungalow sale ph 7...
3029   1st floor g+5 new construction flat with eleva...
3040   fatema ali tower two bedrooms with dd leased a...
3047   for sale 4 bed dd flat askari 6 g+13 building ...
3084   ready to move | 1700 sqft | 5th floor | falakn...
3093            4 bed dd bismillah tower 12th floor flat
3100   3bed dd flat available for sale g+3 building 1...
3138   4th floor prime location 500 square feet flat ...
3172             2 bed lounge ground floor flat for sale
3174   2 rooms flat for sale ground floor 50 sq yards...
3196   60 sq. yards house for sale ground floor only ...
3207   2 bed drawing loung second floor three bedroom...
3251   ground floor flat for sale in nazimabad 5d (2 ...
3265   higher floor 1 bedroom sea facing panorama is ...
3274   full floor apartment for sale in dha phase 8 a...
3302   westopen mid floor highly-desirable 3000 squar...
3345   brand new 2 bedroom drawing room and lounge on...
3381   kings palm residency phase ii 3rd floor 4 room...
3382   flat for sale in bhayani heights main road fac...
3403   tower-10 | 3rd floor 955 sq ft 2-bhk ready-to-...
3411   2 bed bahia appt park facing ground floor prem...
3422    400 square yard double storey 3bed dd each floor
3423   west open second floor flat three bed drawing ...
3427   lease ground floor with extra land flat for sa...
3433   flat for sale korangi crossing allah wala town...
3466   ground plus one 2nd floor 1 master bedroom att...
3474   ultraluxe waterfront residence: coveted 2-bedr...
3521   1800sqft 4 bd dd 2nd floor and jori 5th floor ...
3537   road facing beautiful commercial house with 2 ...
3539                 ground floor flat for sale 2 bed dd
3559   luxury seaview apartment for sale prime locati...
3572                           first floor flat for sale
3580                2bed dd for sale 5th floor with lift
3598   under-construction 3 bed dd furnished apartmen...
3609   high floor 1 bed with sea view | chance deal i...
3636   3 bed dd flat for sale 2500 square feet for sa...
3653   2 bed dd flat | 4th floor with lift | 900 sq. ...
3694   leased flat for sale, 3-bed dd, 5th floor, roa...
3711   used ground floor 200 square yard house for sa...
3723   with rental income brand new 3 bed apartment 1...
3741   urgent sale g+1 3 bed d d each floor sector z ...
3769   well maintained 400 sq yards house for sell in...
3811   creek vista investor chance deal today's deal ...
3813   luxury full sea facing 3-bed apartment for sal...
3820   40 feet wide road house leased triple storey 3...
3832   naya nazimabad luxurious apartment fl-03 | eas...
3840   1200sq ft 14th floor apartment in di cort regency
3888   fully renovated seaview apartment second floor...
3890   3 bed dd bank loan applicable for sale in bada...
3900   creek vista 4 bedrooms apartment for sale high...
3912   3 bed dd ground floor flat ( leased ) for sale...
3922   500sqyds premium construction house having ext...
3932   luxurious 600 square yards house basement + gr...
3948   brand new house for sale g+1 3 bedrooms dine d...
3965   2nd floor flat + penthouse | road facing | for...
3966   brand new 3side corner 3rd floor 2bed drawing ...
4005   flat for sale first floor boundary wall tiles ...
4022              flat emaar pearl tower 3 ( high floor)
4025   gulshan-e-iqbal block 17 back national stadium...
4029   road facing 3 bed d. d | 3rd floor | 1100 sqft...
4057   urgent sale ideal location house ground + 2 tw...
4095                1 bed apartment available 18th floor
4097   al nahdi towers luxury apartments 3 beds d d 7...
4102   sale flat ist floor 2 bed lounge gulshan compl...
4106   2 bed dd second floor flat boundary wall compo...
4108   apartment for sale fully renovated first floor...
4178   2 room flat for sale 3rd floor with roof no ba...
4198   4 rooms luxury apartment on 2nd floor with lif...
4204   zero metar three side corner ground plus two p...
4216   fully renovated flat 2 bed dd for sale 3rd flo...
4250   chance deal available flat for sale in baferzo...
4257             2 bed dd 2nd floor corner flat for sale
4284          2 bed dd upper ground floor 950sq. ft flat
4296   120 yards, ground rcc and 2 bed dd in 1st floo...
4311   ground floor apartment for sale in the prime l...
4334   1 bedroom biggest layout 1b-5 | above 30th flo...
4395   2 bed-dd flat (ground floor) (sui gas availabl...
4401   prime location 3 bed flat for sale near tariq ...
4415    1st floor huge size 3bed room apartment for sale
4452   discover a stunning 3 bedroom luxury full paid...
4531   brand new 4 floor flat,2 bed lounge with roof,...
4571   well maintained ground floor apartment on sale...
4588   2 bed dd flat available for sale lift car park...
4595   saima medows 2nd floor 2 bed drawing lounj res...
4617                                 full floor for sale
4655              1st floor apartment available for sale
4661   2 bedroom flat 1100 sqft in bahria heights 1st...
4692   luxury brand new 120 square yards ground + 1 f...
4694   1200 square feet 1 bedroom sea facing is avail...
4696   120 yards brand new double story house hansa s...
4708        apartment available for sale at ground floor
4723   double storey 400 square yard 7 bedrooms with ...
4743   3 bed drawing apartment 1 st floor full renovated
4785   excellent 1st floor 2 bed dd in nishat commerc...
4808   brand new, luxurious apartment 3 bed dd on fir...
4828   flat for sale 3rd floor boundary wall block m ...
4879   high floor 2 bed chance deal | boulevard & par...
4899   2 bedroom drawing dining kaneez fatima block 2...
4907   iconic sky loft 5-bed crown-floor residence em...
4919                     fully renovated marble flooring
4922    2 bed drawing lounge first floor video available
4945   booking in 5% only 3 bedroom apartment on midd...
4954   noman grand city second floor leased noman gra...
4980      ground floor west open 4 bedroom flat for sale
5053   2 bed apartment for sale gulistan-e-jauhar, bl...
5089   top floor g+7 leased 3 bed apartment available...
5099   prominently-located flat available in pakistan...
5164   falaknaz presidency | 2 bed dd cottage for sal...
5178            3 bed dd 4th floor without lift for sale
5233   brand new 3 bedroom and lounge on 6 floor (lif...
5257   4-bedrooms creek vista apartment for sale on h...
5264                          lower floor 3bed apartment
5292   first floor flat brand new 2 bed dd with 3 was...
5306   1300 sq ft 3 bed dd west open leased 2nd floor...
5341   2 bed dd 88 lac (850 sq. ft, 5th floor, by bir...
5343   ground plus two floors east open maintained ho...
5350   bungalow-facing full floor apartment for sale ...
5380   first floor ideal and prime location flat for ...
5396   240 sq yards | g+1 house for sale | 3 bed dd e...
5406   *apartment for sale* in gulistane jauhar *bloc...
5411   2bed dd 2nd floor available for sale bank loan...
5423                                     3rd floor 3 bed
5490   vip block 4 maymar avenue 4-rooms apartment, w...
5496   120 yards house for sale in juhar 2 bed dd eac...
5505   3bdd 1450 sqft 2 floor flat very good conditio...
5508   4250 sqft huge 4-bedroom apartment on higher f...
5516   3 bed dd flat for sale saima jinnah avenue 6th...
5536   gulshan-e-roomi | 3 bed dd 1800 sqft | bank lo...
5542                          2 bed dd ground floor flat
5549   1 bedroom 996 square feet apartment on middle ...
5579   ultra-rare 01 series 4-bedroom sea-facing apar...
5588   leased 3 bed d. d 2nd floor flat available for...
5608   brand new full furnished luxurious flat near t...
5618   brand new leased 2nd floor 3 bed dd west open ...
5621   600 square feet 2 bedroom west open apartment ...
5623    2nd floor kda leased near by al mustafa hospital
5625   regency apartment vip block 4 near disco baker...
5626   fully renovated 2nd floor flat for sale in far...
5641   mushtaq blessing 1 bed lounge 4th floor with r...
5677        3 bed drawing dining on 2nd floor in shumail
5714        2 bed dd lease flat 3rd floor flat in maymar
5728                                first floor for sale
5733   1st floor 3bed dd flat available for sale in b...
5772   exclusive 1 bedroom apartment spanning at 996 ...
5791          2 bed dd ground floor leased flat for sale
5811   korangi crossing allah wala town main 3rd floo...
5814              2bdd 1000 sq ft 2 floor west open. . .
5863   3bdd 1500 sqft lease ground floor very excelle...
5916   120 square yards g+1+ 1 room on 2nd floor hous...
5957   3 bed dd 60ft road facing 1300sqft flat west o...
5966   high floor 3 bed with park + marina + downtown...
5993   beautiful interior decorated apartment on the ...
6003   1st floor 2 bed portion near model school nice...
6007   grove apartments 3 bedroom tower a - 17 th flo...
6027                ground + 1 floor 240 sq yard banglow
6060       ground floor flat corner in nazimabad block 1
6085   180 sq. yd house three side corner ground & 1s...
6105   gulshan iqbal block 11 noman plaza 3 bed drawi...
6122   clifton block 2 small complex 1st floor near b...
6150   gulshan-e-iqbal block 16 maymar arcde 3rd floo...
6152                     2 bed dd 4th floor without lift
6154   creek vista 4 bedrooms higher 14 floor compoun...
6167   2 bed d/d like brand new flat available for sa...
6178   gulshan-e-iqbal block 16 near buitul mukkram m...
6190   ground floor apartment 2 bed dd for sale clift...
6197   flat for sale 3rd floor, 2 bed rooms drawing d...
6213   best for investment 4 room first floor flat fo...
6229   king homes | 2 bed dd each floor | 120 yards g...
6235   gulshan-e-iqbal block 16 buitul mukkram masjid...
6242   compact 1 bed lounge 1st floor | ready kitchen...
6322   full paid investor deal of near to possession ...
6341   for sale west open flat 4 bed dd askari 6 mid ...
6356   brand new fully furnished 3 bed marina view ap...
6417   gulshan-e-iqbal block 17 back national stadium...
6431   purely residential corner 3 bed,d,d, store roo...
6451   3 bed dd flat available first floor cantt view...
6465   merchant navy co operative housing society fir...
6482   bank loan applicable 2-bed lounge flat on 3rd ...
6593   fully furnished 4 bedroom corner apartment on ...
6595   3 bed lounge brand new 2nd floor 1100 sq feet ...
6618                           first floor flat for sale
6644         2 bed drawing dining on 1st floor west open
6671   apartment for sale | 3 bed dd | 1450 sq. ft. |...
6717        seaview apartment ground floor gf-2 for sale
6718    premium ground floor 4 bed dd apartment for sale
6729   prime location 1250 square feet cottage (flat)...
6739             5th floor apartment for sale in karachi
6761   flat for sale 2 bed dd, floor 1 leased , capit...
6789   prime corner flat | 3rd floor | fully renovate...
6804   3 bed dd 3rd floor apartment avaiable for sale...
6826                   fully renovated ground floor flat
6834      3 bedroom apartment 4th floor rahat commercial
6842   2 bed drawing dinning, ready to possession, gl...
6924   mehran apartment block 16 | premium 3 bed dd (...
6934                          ground floor flat for sale
7017                  experience karachi from 50th floor
7025                120 sq yard g+1 floor house for sale
7037   fully renovated 2 bedroom drawing lounge 1st f...
7248   apartment at 3rd floor in madina comfort west ...
7251   2 bedroom drawing room and lounge bungalow on ...
7265   flat for sale 3rd floor 2 rooms 50 square yard...
7376   1st floor 3 bed dd west open flat for sale blo...
7384   5th floor sanober pride x 2 apposit kfc . main...
7418   120 sq yard house west open ground floor plus ...
7462   kehkashan homes one unit lease west open house...
7482          2000 sq. ft. apartment for sale full floor
7485   2 bed lounge apartment, 3rd floor, corner, mai...
7532   2 bed dd flat for sale ideal location in jauha...
7535   kda leased 2nd floor flat gulshan block 5 noma...
7551   1st floor 3 bed dd apartment for sale sector-j...
7577   brand new 8th floor 3 bed d/d apartment availa...
7635   iqbal plaza 3rd floor corner (phase 2) flat av...
7652          2bl 4 floor lease very good condition. . .
7674   this is a 2 bed dd with 3 washrooms, almost ne...
7715   corner road facing kings palm residency 6 floo...
7722   direct owner meeting | brand new house 240sqyd...
7735   240 yards ground plus 1 park facing house leas...
7760   2 bed luxury apartment | high floor | sea & po...
7816   flat for sale 4th floor with roof west open fl...
7823                  1st floor renovated huge size flat
7824   2nd floor flat available for sale in north kar...
7843   opulent four (04) bedroom residence with entic...
7852   2 bed lounge flat available for sell 2nd floor...
7859   gulshan block 13d2. flat 2bed. lounge on 1st f...

In [84]:
floor_rows['property_name'].to_csv("floor_rows.csv", index=False)

In [85]:
import re



# ============================================================
# Extract floor number from property_name
# ============================================================

def extract_floor(text):

    if pd.isna(text):
        return np.nan

    text = str(text).lower().strip()

    # --------------------------------------------------------
    # 1. Ground floor
    # --------------------------------------------------------
    ground_patterns = [
        r'\bground\s+floor\b',
        r'\bgf\b',
        r'\bg\s+floor\b',
    ]

    for pattern in ground_patterns:
        if re.search(pattern, text):
            return 0

    # --------------------------------------------------------
    # 2. Written floor numbers
    # --------------------------------------------------------
    word_floors = {
        "first": 1,
        "second": 2,
        "third": 3,
        "fourth": 4,
        "fifth": 5,
        "sixth": 6,
        "seventh": 7,
        "eighth": 8,
        "ninth": 9,
        "tenth": 10,
        "eleventh": 11,
        "twelfth": 12,
        "thirteenth": 13,
        "fourteenth": 14,
        "fifteenth": 15,
        "sixteenth": 16,
        "seventeenth": 17,
        "eighteenth": 18,
        "nineteenth": 19,
        "twentieth": 20
    }

    for word, number in word_floors.items():

        pattern = rf'\b{word}\s+floor\b'

        if re.search(pattern, text):
            return number

    # --------------------------------------------------------
    # 3. Ordinal format
    #    1st floor, 2nd floor, 3rd floor, 4th floor...
    # --------------------------------------------------------
    match = re.search(
        r'\b(\d+)(?:st|nd|rd|th)\s+floor\b',
        text
    )

    if match:
        return int(match.group(1))

    # --------------------------------------------------------
    # 4. Simple numeric format
    #    1 floor, 2 floor, 3 floor...
    # --------------------------------------------------------
    match = re.search(
        r'\b(\d+)\s+floor\b',
        text
    )

    if match:
        return int(match.group(1))

    # --------------------------------------------------------
    # 5. No reliable floor found
    # --------------------------------------------------------
    return np.nan


# ============================================================
# Apply
# ============================================================

df["floor_from_name"] = df["property_name"].apply(extract_floor)

In [86]:
# Extract floor from property name
df["floor_from_name"] = df["property_name"].apply(extract_floor)

# Fill existing floor only where it is missing
df["floor"] = df["floor"].fillna(df["floor_from_name"])

# Optional: remove helper column
df.drop(columns=["floor_from_name"], inplace=True)

In [87]:
import re

def extract_total_floors(text):
    if pd.isna(text):
        return np.nan

    text = str(text).lower().strip()

    # --------------------------------------------------------
    # G+13, G + 13, G+3, etc.
    # G = ground floor (0), so total floors = number + 1
    # --------------------------------------------------------
    match = re.search(r'\bg\s*\+\s*(\d+)\b', text)

    if match:
        return int(match.group(1)) + 1

    # --------------------------------------------------------
    # Ground + 13, Ground + 3, etc.
    # --------------------------------------------------------
    match = re.search(r'\bground\s*\+\s*(\d+)\b', text)

    if match:
        return int(match.group(1)) + 1

    # --------------------------------------------------------
    # Ground and First / Ground, First and Second etc.
    # --------------------------------------------------------
    if re.search(r'\bground\b', text):

        floor_numbers = []

        word_numbers = {
            "first": 1,
            "second": 2,
            "third": 3,
            "fourth": 4,
            "fifth": 5,
            "sixth": 6,
            "seventh": 7,
            "eighth": 8,
            "ninth": 9,
            "tenth": 10
        }

        for word, number in word_numbers.items():
            if re.search(rf'\b{word}\b', text):
                floor_numbers.append(number)

        if floor_numbers:
            return max(floor_numbers) + 1

    return np.nan


# ============================================================
# Extract from property name
# ============================================================

df["total_floors_from_name"] = (
    df["property_name"]
      .apply(extract_total_floors)
)


# ============================================================
# Fill total_floors ONLY where it is missing
# ============================================================

df["total_floors"] = df["total_floors"].fillna(
    df["total_floors_from_name"]
)


# ============================================================
# Remove helper column
# ============================================================

df.drop(
    columns=["total_floors_from_name"],
    inplace=True
)

In [88]:
df['total_floors'].isnull().sum()

np.int64(10849)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20458 entries, 0 to 20478
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20458 non-null  object
 1   address             20458 non-null  object
 2   location            20458 non-null  object
 3   sub_location        20458 non-null  object
 4   price               20458 non-null  float64
 5   price_crore         20458 non-null  float64
 6   price_per_sqft      20458 non-null  float64
 7   area                20458 non-null  float64
 8   bedrooms            20458 non-null  int64
 9   bathrooms           20458 non-null  int64
 10  kitchen             20426 non-null  float64
 11  floor               4008 non-null   float64
 12  total_floors        9609 non-null   float64
 13  parking             20364 non-null  float64
 14  elevator            20458 non-null  int64
 15  servant_quarters    20458 non-null  float64
 16  electricity_backup  20458 non-null  int64
 17  furnished           20458 non-null  int64
 18  completion_year     10852 non-null  float64
 19  property_type       20458 non-null  object
 20  property_age        10852 non-null  float64
 21  age_category        10852 non-null  object
 22  parking_score       20458 non-null  int64
 23  area_per_bedroom    20458 non-null  float64
 24  district            20073 non-null  object
 25  sub_location_type   20458 non-null  object
 26  location_score      20458 non-null  int64
 27  sub_location_score  20458 non-null  int64
 28  expected_floors     1624 non-null   float64
dtypes: float64(13), int64(8), object(8)
memory usage: 5.2+ MB

In [90]:
df[df['kitchen'].isnull()][['area','total_floors','price_crore']]

          area  total_floors  price_crore
1619    1377.0           NaN        2.050
2089    2160.0           3.0       11.000
2842   18000.0           NaN       40.000
2892     999.0           NaN        1.350
4123    1602.0          16.0        1.680
4178     405.0           NaN        0.265
5046    1350.0           3.0        3.950
5792     450.0           4.0        0.250
5957    1296.0          15.0        1.750
8325     999.0           4.0        1.950
9093    6750.0           NaN       36.000
9222    9000.0           4.0       40.000
9388    1800.0           5.0        3.700
9409    4500.0           NaN       11.900
10570   1080.0           2.0        3.500
10847   2160.0           NaN        3.500
10852   1440.0           2.0        4.000
11873   1080.0           2.0        3.500
11935   1053.0           NaN        1.300
13159   2700.0           3.0       27.000
13640   3375.0           2.0        8.750
13701   1800.0           2.0        4.500
14196   1080.0           2.0        2.000
14423   1098.0           NaN        2.250
14720   1998.0           4.0        3.250
15628   5400.0           NaN        9.500
16167   2799.0           NaN        4.750
16306   6750.0           1.0       18.500
17076   1890.0           NaN       16.000
19361   1800.0           2.0        3.000
19482   1998.0           NaN        2.350
20175   1800.0           5.0        5.000

In [91]:
df.groupby("kitchen").agg(
    count=("kitchen", "size"),
    mean_area=("area", "mean"),
    median_area=("area", "median"),
    min_area=("area", "min"),
    max_area=("area", "max"),
    mean_floors=("total_floors", "mean"),
    median_floors=("total_floors", "median"),
    min_floors=("total_floors", "min"),
    max_floors=("total_floors", "max")
).sort_index()

,count,mean_area,median_area,min_area,max_area,mean_floors,median_floors,min_floors,max_floors
kitchen,,,,,,,,,
0.0,4984,2133.768258,1503.0,252.0,27000.0,5.079853,2.0,1.0,49.0
1.0,10843,2171.237204,1746.0,225.0,36000.0,9.452729,5.0,1.0,92.0
2.0,3975,3115.510943,2250.0,198.0,36000.0,4.626730,2.0,1.0,48.0
3.0,576,3544.984375,2160.0,351.0,31500.0,2.955774,2.0,1.0,45.0
4.0,48,4956.750000,3600.0,648.0,30600.0,2.636364,3.0,1.0,4.0

In [92]:
kitchen_mapping = {
    1619: 1,
    2842: 4,
    2892: 1,
    4178: 1,
    9093: 4,
    9409: 3,
    10847: 2,
    11935: 1,
    14423: 1,
    15628: 3,
    16167: 2,
    17076: 2,
    19482: 2,
}

df.loc[df.index.isin(kitchen_mapping), "kitchen"] = (
    df.index.to_series().map(kitchen_mapping)
)

In [93]:
kitchen_mapping = {
    2089: 2,
    4123: 1,
    5046: 1,
    5792: 1,
    5957: 1,
    8325: 1,
    9222: 4,
    9388: 2,
    10570: 1,
    10852: 1,
    11873: 1,
    13159: 3,
    13640: 3,
    13701: 2,
    14196: 1,
    14720: 2,
    16306: 3,
    19361: 2,
    20175: 2
}

df.loc[kitchen_mapping.keys(), "kitchen"] = pd.Series(kitchen_mapping)

In [94]:
df['parking'].isnull().sum()

np.int64(94)

In [95]:
df.groupby("parking").agg(
    count=("parking", "size"),
    mean_area=("area", "mean"),
    median_area=("area", "median"),
    min_area=("area", "min"),
    max_area=("area", "max")
).sort_index()

         count     mean_area  median_area  min_area  max_area
parking
0.0       6345   2095.231836       1503.0     252.0   27000.0
1.0       8561   2078.518981       1701.0     198.0   27000.0
2.0       2885   2528.046101       2250.0     342.0   21996.0
3.0       1104   3299.551630       3150.0     351.0   18000.0
4.0        843   3670.761566       3150.0     279.0   18000.0
5.0        314   4862.694268       3600.0     450.0   18000.0
6.0        134   6507.402985       6597.0     549.0   27000.0
7.0         29   6447.413793       9000.0     846.0   18000.0
8.0         60   6335.250000       4950.0     846.0   19800.0
9.0          9   2796.000000       1800.0     540.0    9000.0
10.0        70   6211.157143       2250.0     279.0   36000.0
11.0         1   3600.000000       3600.0    3600.0    3600.0
12.0         2  23998.500000      23998.5   18000.0   29997.0
14.0         1  27000.000000      27000.0   27000.0   27000.0
15.0         6  16200.000000      13500.0    3600.0   30600.0

In [96]:
df['parking'].isnull

<bound method Series.isnull of 0         3.0
1         1.0
2         0.0
3         2.0
4         0.0
5         4.0
6         1.0
7         4.0
8         1.0
9         0.0
10        3.0
11        0.0
12        1.0
13        2.0
14        2.0
15        1.0
16        0.0
17        1.0
18        0.0
19        1.0
20        0.0
21        0.0
22        1.0
23        1.0
24        2.0
25        0.0
26        1.0
27        2.0
28        1.0
29        0.0
30        1.0
31        1.0
32        0.0
33        1.0
34        1.0
35        0.0
36        1.0
37        2.0
38        1.0
39        1.0
40        1.0
41        1.0
42        0.0
43        2.0
44        5.0
45        0.0
46        1.0
47        0.0
48        1.0
49        1.0
50        0.0
51        1.0
52        1.0
53        1.0
54        1.0
55        0.0
56        2.0
57        2.0
58        1.0
59        1.0
60        0.0
61        5.0
62        2.0
63        4.0
64        1.0
65        1.0
66        2.0
67        0.0
68        0.0
69        1.0
70        1.0
71        0.0
72        1.0
73        1.0
74        1.0
75        0.0
76        1.0
77        0.0
78        1.0
79        1.0
80        8.0
81        1.0
82        0.0
83        1.0
84        1.0
85        1.0
86        1.0
87        1.0
88        2.0
89        1.0
90        1.0
91        1.0
92        1.0
93        1.0
94        0.0
95        1.0
96        0.0
97        1.0
98        0.0
99        1.0
100       0.0
101       0.0
102       2.0
103       1.0
104       4.0
105       0.0
106       0.0
107       2.0
108       0.0
109       1.0
110       1.0
111       1.0
112       0.0
113       2.0
114       1.0
115       0.0
116       1.0
117       0.0
118       1.0
119       4.0
120       1.0
121       1.0
122      10.0
123       4.0
124       1.0
125       1.0
126       0.0
127       0.0
128       1.0
129       1.0
130       1.0
131       1.0
132       0.0
133       1.0
134       1.0
135       0.0
136       0.0
137       0.0
138       1.0
139       3.0
140       0.0
141       1.0
142       1.0
143       0.0
144       0.0
145       0.0
146       5.0
147       1.0
148       3.0
149       0.0
150       3.0
151       2.0
152       2.0
153       0.0
154       3.0
155       2.0
156       4.0
157       0.0
158       2.0
159       4.0
160       4.0
161       0.0
162       0.0
163       0.0
164       1.0
165       2.0
166       0.0
167       3.0
168       1.0
169       0.0
170       1.0
171       1.0
172       0.0
173       1.0
174       0.0
175       0.0
176       1.0
177       4.0
178       0.0
179       1.0
180       1.0
181       2.0
182       1.0
183       4.0
184       1.0
185       1.0
186       1.0
187       1.0
188       1.0
189       0.0
190       1.0
191       1.0
192       1.0
193       1.0
194       0.0
195       0.0
196       0.0
197       2.0
198       0.0
199       0.0
200       4.0
201       1.0
202       2.0
203       0.0
204       2.0
205       3.0
206       1.0
207       1.0
208       1.0
209       1.0
210       2.0
211       0.0
212       2.0
213       4.0
214       1.0
215       4.0
216       1.0
217       0.0
218       1.0
219       1.0
220       0.0
221       1.0
222       1.0
223       0.0
224       1.0
225       1.0
226       0.0
227       6.0
228       0.0
229       0.0
230       0.0
231       0.0
232       2.0
233       0.0
234       1.0
235       0.0
236       0.0
237       0.0
238       1.0
239       1.0
240       1.0
241       1.0
242       0.0
243       2.0
244       0.0
245       1.0
246       2.0
247       4.0
248       0.0
249       1.0
250       2.0
251       NaN
252       2.0
253       1.0
254       1.0
255       1.0
256       1.0
257       1.0
258       1.0
259       1.0
260       0.0
261       1.0
262       1.0
263       1.0
264       0.0
265       0.0
266       1.0
267       1.0
268       2.0
269       2.0
270       2.0
271       0.0
272       2.0
273       1.0
274       2.0
275       0.0
276       0.0
277       1.0
278       1.0
279       5.0
280       3.0
281       1.0
282       2.0
283       0.0
284       2.0
285       2.0
286       1.0
287       4.0
288       1.0
289       0.0
290       5.0
291       2.0
292       1.0
293       2.0
294       1.0
295       0.0
296       0.0
297       0.0
298       0.0
299       1.0
300       1.0
301       1.0
302       1.0
303       1.0
304       1.0
305       1.0
306       2.0
307       1.0
308       1.0
309       1.0
310       5.0
311       1.0
312       1.0
313       1.0
314       1.0
315       0.0
316       0.0
317       1.0
318       4.0
319       3.0
320       0.0
321       3.0
322       1.0
323       1.0
324       1.0
325       1.0
326       4.0
327       0.0
328       1.0
329       0.0
330       0.0
331       0.0
332       0.0
333       1.0
334       1.0
335       0.0
336       1.0
337       1.0
338       4.0
339       1.0
340       0.0
341       1.0
342       0.0
343       4.0
344       1.0
345       1.0
346       5.0
347       1.0
348       4.0
349       1.0
350       1.0
351       1.0
352       0.0
353       1.0
354       5.0
355       1.0
356       1.0
357       1.0
358       0.0
359       1.0
360       0.0
361       0.0
362       0.0
363       1.0
364       1.0
365       0.0
366       3.0
367       0.0
368       1.0
369       1.0
370       2.0
371       1.0
372       2.0
373       2.0
374       2.0
375       1.0
376       1.0
377       0.0
378       1.0
379       0.0
380       1.0
381       1.0
382       0.0
383       0.0
384       3.0
385       1.0
386       0.0
387       0.0
388       2.0
389       0.0
390       1.0
391       0.0
392       4.0
393       1.0
394       0.0
395       3.0
396       0.0
397       1.0
398       4.0
399       0.0
400       2.0
401       1.0
402       0.0
403       0.0
404       0.0
405       1.0
406       0.0
407       7.0
408       1.0
409       1.0
410       0.0
411       0.0
412       0.0
413       1.0
414       0.0
415       0.0
416       1.0
417       0.0
418       3.0
419       6.0
420       0.0
421       1.0
422       0.0
423       2.0
424       1.0
425       0.0
426       0.0
427       2.0
428       1.0
429       0.0
430       1.0
431       0.0
432       4.0
433       1.0
434       0.0
435       2.0
436       0.0
437       0.0
438       2.0
439       1.0
440       2.0
441       3.0
442       6.0
443       0.0
444       2.0
445       1.0
446       0.0
447       0.0
448       1.0
449       2.0
450       0.0
451       2.0
452       1.0
453       1.0
454       2.0
455       1.0
456       1.0
457       0.0
458       0.0
459       1.0
460       3.0
461       0.0
462       4.0
463       0.0
464       0.0
465       0.0
466       1.0
467       1.0
468       1.0
469       2.0
470       0.0
471       2.0
472       0.0
473       0.0
474       0.0
475       0.0
476       0.0
477       0.0
478       0.0
479       1.0
480       2.0
481       0.0
482       3.0
483       1.0
484       2.0
485       3.0
486       0.0
487       1.0
488       1.0
489       1.0
490       1.0
491       2.0
492       1.0
493       4.0
494       1.0
495       2.0
496       1.0
497       1.0
498       1.0
499       0.0
500       0.0
501       0.0
502       3.0
503       3.0
504       1.0
505       3.0
506       0.0
507       1.0
508       0.0
509       8.0
510       3.0
511       1.0
512       1.0
513       1.0
514       2.0
515       1.0
516       0.0
517       2.0
518       2.0
519       0.0
520       0.0
521       1.0
522       1.0
523       1.0
524       1.0
525       0.0
526       2.0
527       1.0
528       4.0
529       1.0
530       1.0
531       0.0
532       0.0
533       0.0
534       1.0
535       0.0
536       1.0
537       0.0
538       4.0
539       2.0
540       1.0
541       2.0
542       1.0
543       0.0
544       0.0
545       3.0
546       0.0
547       0.0
548       1.0
549       1.0
550       1.0
551       0.0
552       1.0
553       0.0
554       4.0
555       0.0
556       1.0
557       0.0
558       1.0
559       1.0
560       1.0
561       0.0
562       0.0
563       0.0
564       2.0
565       1.0
566       4.0
567       0.0
568       0.0
569       0.0
570       3.0
571       0.0
572       1.0
573       1.0
574       3.0
575       0.0
576       1.0
577       1.0
578       1.0
579       2.0
580       2.0
581       1.0
582       1.0
583       5.0
584       1.0
585       1.0
586       1.0
587       0.0
588       1.0
589       0.0
591       0.0
592       2.0
593       1.0
594       2.0
595       2.0
596       1.0
597       0.0
598       0.0
599       1.0
600       1.0
601       1.0
602       1.0
603       1.0
604       4.0
605       2.0
606       0.0
607       0.0
608       1.0
609       1.0
610       0.0
611       1.0
612       0.0
613       3.0
614       0.0
615       1.0
616       1.0
617       4.0
618       2.0
619       2.0
620      10.0
621       0.0
622       0.0
623       1.0
624       0.0
625       1.0
626       0.0
627       1.0
628       0.0
629       1.0
630       1.0
631       4.0
632       1.0
633       1.0
634       1.0
635       1.0
636       1.0
637       3.0
638       5.0
639       0.0
640       1.0
641       0.0
642       1.0
643       1.0
644       1.0
645       1.0
646       1.0
647       2.0
648       2.0
649       0.0
650       1.0
651       0.0
652       0.0
653       1.0
654       1.0
655       2.0
656       0.0
657       0.0
658       1.0
659       1.0
660       1.0
661      10.0
662       3.0
663       2.0
664       0.0
665       1.0
666       2.0
667       1.0
668       4.0
669       0.0
670       4.0
671       0.0
672       0.0
673       1.0
674       1.0
675       0.0
676       1.0
677       1.0
678       0.0
679       0.0
680       0.0
681       1.0
682       0.0
683       1.0
684       0.0
685       0.0
686       0.0
687       0.0
688       1.0
689       1.0
690       1.0
691       1.0
692       1.0
693       1.0
694       2.0
695       1.0
696       0.0
697       1.0
698       0.0
699       1.0
700       1.0
701       1.0
702       0.0
703       0.0
704       1.0
705       0.0
706       1.0
707       1.0
708       0.0
709       1.0
710       2.0
711       1.0
712       0.0
713       0.0
714       3.0
715       1.0
716       0.0
717       2.0
718       2.0
719       0.0
720       2.0
721       1.0
722       0.0
723       2.0
724       2.0
725       0.0
726       1.0
727       0.0
728       0.0
729       0.0
730       0.0
731       2.0
732       3.0
733       1.0
734       1.0
735       3.0
736       0.0
737       1.0
738       1.0
739       0.0
740       0.0
741       2.0
742       1.0
743       1.0
744       1.0
745       1.0
746       1.0
747       2.0
748       1.0
749       0.0
750       1.0
751       1.0
752       0.0
753       0.0
754       2.0
755       2.0
756       0.0
757       2.0
758       1.0
759       2.0
760       1.0
761       0.0
762       1.0
763       1.0
764       4.0
765       3.0
766       1.0
767       0.0
768       1.0
769       0.0
770       0.0
771       0.0
772       1.0
773       0.0
774      10.0
775       1.0
776       2.0
777       0.0
778       0.0
779       2.0
780       2.0
781       1.0
782       1.0
783       1.0
784       3.0
785      11.0
786       0.0
787       1.0
788       1.0
789       0.0
790       2.0
791       1.0
792       0.0
793      10.0
794       0.0
795       0.0
796       3.0
797       1.0
798       1.0
799       1.0
800       1.0
801       2.0
802       4.0
803       1.0
804       2.0
805       1.0
806       1.0
807       0.0
808       1.0
809       1.0
810       1.0
811       0.0
812       3.0
813       1.0
814       1.0
815       1.0
816       0.0
817       1.0
818       0.0
819       3.0
820       1.0
821       2.0
822       1.0
823       2.0
824       0.0
825       1.0
826       4.0
827       1.0
828       1.0
829       3.0
830       1.0
831       0.0
832       0.0
833       1.0
834       0.0
835       0.0
836       0.0
837       0.0
838       2.0
839       1.0
840       2.0
841       0.0
842       2.0
843       0.0
844       3.0
845       2.0
846       0.0
847       2.0
848       1.0
849       2.0
850       0.0
851       0.0
852       2.0
853       0.0
854       0.0
855       2.0
856       0.0
857       4.0
858       1.0
859       0.0
860       1.0
861       1.0
862       1.0
863       1.0
864       1.0
865       0.0
866       0.0
867       1.0
868       1.0
869       1.0
870       0.0
871       1.0
872       0.0
873       2.0
874       2.0
875       1.0
876       2.0
877       1.0
878       3.0
879       1.0
880       0.0
881       4.0
882       1.0
883       4.0
884       1.0
885       2.0
886       2.0
887       1.0
888       0.0
889       0.0
890       0.0
891       1.0
892       2.0
893       2.0
894       0.0
895       2.0
896       1.0
897       1.0
898       2.0
899       3.0
900       1.0
901       3.0
902       1.0
903       1.0
904       1.0
905       0.0
906       4.0
907       1.0
908       0.0
909       0.0
910       0.0
911       3.0
912       1.0
913       2.0
914       1.0
915       0.0
916       0.0
917       2.0
918       4.0
919       1.0
920       0.0
921       2.0
922       1.0
923       0.0
924       6.0
925       1.0
926       0.0
927       0.0
928       1.0
929       1.0
930       1.0
931       0.0
932       1.0
933       7.0
934       1.0
935       6.0
936       1.0
937       0.0
938       0.0
939       1.0
940       2.0
941       1.0
942       1.0
943       4.0
944       1.0
945       6.0
946       0.0
947       1.0
948       0.0
949       2.0
950       1.0
951       1.0
952       0.0
953       1.0
954       0.0
955       1.0
956       0.0
957       0.0
958       1.0
959       1.0
960       0.0
961       0.0
962       2.0
963       1.0
964       0.0
965       1.0
966       0.0
967       3.0
968       1.0
969       0.0
970       0.0
971       1.0
972       1.0
973       2.0
974       1.0
975       0.0
976       1.0
977       3.0
978       1.0
979       1.0
980       1.0
981       0.0
982       1.0
983       1.0
984       0.0
985       5.0
986       0.0
987       1.0
988       0.0
989       2.0
990       1.0
991       0.0
992       0.0
993       1.0
994       3.0
995       1.0
996       1.0
997       1.0
998       2.0
999       1.0
1000      2.0
1001      3.0
1002      1.0
1003      1.0
1004      0.0
1005      0.0
1006      8.0
1007      0.0
1008      0.0
1009      0.0
1010      0.0
1011      0.0
1012      1.0
1013      2.0
1014      1.0
1015      3.0
1016      6.0
1017      0.0
1018      1.0
1019      1.0
1020      0.0
1021      0.0
1022      0.0
1023      1.0
1024      1.0
1025      1.0
1026      1.0
1027      0.0
1028      1.0
1029      0.0
1030      0.0
1031      0.0
1032      1.0
1033      1.0
1034      0.0
1035      6.0
1036      3.0
1037      0.0
1038      1.0
1039      0.0
1040      1.0
1041      0.0
1042      0.0
1043      1.0
1044      0.0
1045      1.0
1046      1.0
1047      2.0
1048      2.0
1049      2.0
1050      0.0
1051      1.0
1052      4.0
1053      0.0
1054      0.0
1055      0.0
1056      2.0
1057      3.0
1058      0.0
1059      1.0
1060      1.0
1061      1.0
1062      1.0
1063      0.0
1064      0.0
1065      0.0
1066      1.0
1067      4.0
1068      0.0
1070      3.0
1071      0.0
1072      0.0
1073      0.0
1074      1.0
1075      1.0
1076      0.0
1077      1.0
1078      2.0
1079      2.0
1080      3.0
1081      0.0
1082      0.0
1083      2.0
1084      3.0
1085      0.0
1086      1.0
1087      1.0
1088      2.0
1089      1.0
1090      2.0
1091      1.0
1092      1.0
1093      1.0
1094      2.0
1095      2.0
1096      0.0
1097      1.0
1098      1.0
1099      0.0
1100      1.0
1101      1.0
1102      2.0
1103      3.0
1104      1.0
1105      0.0
1106      1.0
1107      0.0
1108      1.0
1109      2.0
1110      1.0
1111      0.0
1112      0.0
1113      2.0
1114      1.0
1115      3.0
1116      0.0
1117      0.0
1118      0.0
1119      1.0
1120      2.0
1121      2.0
1122      1.0
1123      0.0
1124      1.0
1125      1.0
1126      3.0
1127      0.0
1128      1.0
1129      2.0
1130      1.0
1131      0.0
1132      1.0
1133      1.0
1134      1.0
1135      0.0
1136      0.0
1137      1.0
1138      3.0
1139      0.0
1140      1.0
1141      4.0
1142      1.0
1143      4.0
1144      1.0
1145      3.0
1146      1.0
1147      0.0
1148      1.0
1149      0.0
1150      1.0
1151      1.0
1152      1.0
1153      1.0
1154      2.0
1155      1.0
1156      1.0
1157      1.0
1158      1.0
1159      1.0
1160      2.0
1161      1.0
1162      1.0
1163      5.0
1164      1.0
1165      4.0
1166      0.0
1167      0.0
1168      1.0
1169      0.0
1170      0.0
1171      0.0
1172      5.0
1173      1.0
1174      1.0
1175      0.0
1176      2.0
1177      0.0
1178      2.0
1179      1.0
1180      1.0
1181      0.0
1182      0.0
1183      0.0
1184      0.0
1185      2.0
1186      0.0
1187      0.0
1188      1.0
1189      2.0
1190      2.0
1191      0.0
1192      2.0
1193      0.0
1194      0.0
1195      1.0
1196      1.0
1197      0.0
1198      5.0
1199      1.0
1200      2.0
1201      1.0
1202      1.0
1203      0.0
1204      1.0
1205      1.0
1206      3.0
1207      0.0
1208      1.0
1209      1.0
1210      1.0
1211      0.0
1212      0.0
1213      0.0
1214      0.0
1215      1.0
1216      1.0
1217      1.0
1218      1.0
1219      1.0
1220      1.0
1221      1.0
1222      2.0
1223      1.0
1224      4.0
1225      2.0
1226      0.0
1227      1.0
1228      1.0
1229      1.0
1230      0.0
1231      1.0
1232      0.0
1233      4.0
1234      1.0
1235      2.0
1236      1.0
1237      2.0
1238      3.0
1239      0.0
1240      1.0
1241      1.0
1242      0.0
1243      3.0
1244      0.0
1245      1.0
1246      0.0
1247      1.0
1248      3.0
1249      1.0
1250      0.0
1251      4.0
1252      0.0
1253      1.0
1254      1.0
1255      6.0
1256      1.0
1257      0.0
1258      0.0
1259      1.0
1260      3.0
1261      0.0
1262      0.0
1263      2.0
1264      0.0
1265      2.0
1266      1.0
1267      1.0
1268      2.0
1269      1.0
1270      1.0
1271      2.0
1272      4.0
1273      0.0
1274      1.0
1275      1.0
1276      1.0
1277      1.0
1278      1.0
1279      0.0
1280      2.0
1281      2.0
1282      2.0
1283      1.0
1284      1.0
1285      1.0
1286      1.0
1287      0.0
1288      1.0
1289      0.0
1290      1.0
1291      3.0
1292      2.0
1293      2.0
1294      0.0
1295      1.0
1296      3.0
1297      1.0
1298      1.0
1299      6.0
1300      3.0
1301      3.0
1302      1.0
1303      1.0
1304      1.0
1305      2.0
1306      4.0
1307      1.0
1308      1.0
1309      0.0
1310      0.0
1311      1.0
1312      1.0
1313      4.0
1314      0.0
1315      1.0
1316      1.0
1317      0.0
1318      1.0
1319      0.0
1320      0.0
1321      3.0
1322      1.0
1323      4.0
1324      1.0
1325      1.0
1326      0.0
1327      1.0
1328      3.0
1329      0.0
1330      2.0
1331      1.0
1332      0.0
1333      1.0
1334      1.0
1335      1.0
1336      0.0
1337      1.0
1338      1.0
1339      0.0
1340      1.0
1341      1.0
1342      0.0
1343      2.0
1344      0.0
1345      1.0
1346      0.0
1347      0.0
1348      0.0
1349      0.0
1350      1.0
1351      3.0
1352      1.0
1353      5.0
1354      1.0
1355      2.0
1356      1.0
1357      3.0
1358      0.0
1359      0.0
1360      2.0
1361      1.0
1362      0.0
1363      1.0
1364      0.0
1365      2.0
1366      1.0
1367      1.0
1368      1.0
1369      1.0
1370      0.0
1371      3.0
1372      3.0
1373      0.0
1374      0.0
1375      1.0
1376      2.0
1377      0.0
1378      1.0
1379      1.0
1380      0.0
1381      3.0
1382      1.0
1383      4.0
1384      1.0
1385      1.0
1386      0.0
1387      0.0
1388      1.0
1389      1.0
1390      0.0
1391      1.0
1392      5.0
1393      0.0
1394      0.0
1395      2.0
1396      1.0
1397      1.0
1398      2.0
1399      1.0
1400      1.0
1401      0.0
1402      1.0
1403      3.0
1404      1.0
1405      1.0
1406      1.0
1407      0.0
1408      0.0
1409      3.0
1410      1.0
1411      0.0
1412      0.0
1413      0.0
1414      2.0
1415      0.0
1416      1.0
1417      0.0
1418      1.0
1419      4.0
1420      0.0
1421      1.0
1422      3.0
1423      0.0
1424      1.0
1425      0.0
1426      1.0
1427      1.0

In [97]:
df["area_group"] = pd.cut(
    df["area"],
    bins=[0, 1200, 1800, 2400, 3600, 5000, 7000, 10000, float("inf")]
)

pd.crosstab(
    df["area_group"],
    df["parking"],
    normalize="index"
).round(3)

parking,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,14.0,15.0
area_group,,,,,,,,,,,,,,,
"(0.0, 1200.0]",0.398,0.446,0.088,0.025,0.026,0.007,0.003,0.000,0.002,0.001,0.004,0.0,0.000,0.000,0.000
"(1200.0, 1800.0]",0.323,0.498,0.110,0.031,0.023,0.008,0.002,0.000,0.002,0.000,0.002,0.0,0.000,0.000,0.000
"(1800.0, 2400.0]",0.277,0.468,0.165,0.047,0.030,0.009,0.002,0.000,0.001,0.000,0.001,0.0,0.000,0.000,0.000
"(2400.0, 3600.0]",0.245,0.377,0.251,0.060,0.041,0.016,0.004,0.002,0.001,0.000,0.002,0.0,0.000,0.000,0.000
"(3600.0, 5000.0]",0.211,0.291,0.204,0.185,0.080,0.017,0.008,0.002,0.003,0.000,0.001,0.0,0.000,0.000,0.000
"(5000.0, 7000.0]",0.281,0.274,0.078,0.126,0.173,0.048,0.007,0.002,0.007,0.002,0.002,0.0,0.000,0.000,0.000
"(7000.0, 10000.0]",0.237,0.203,0.042,0.055,0.153,0.136,0.097,0.024,0.034,0.002,0.013,0.0,0.000,0.000,0.003
"(10000.0, inf]",0.209,0.233,0.078,0.047,0.062,0.085,0.070,0.008,0.047,0.000,0.116,0.0,0.016,0.008,0.023

In [98]:
def estimate_parking(area):
    if pd.isna(area):
        return np.nan
    elif area < 1200:
        return 1
    elif area < 1800:
        return 1
    elif area < 2400:
        return 2
    elif area < 3600:
        return 2
    elif area < 5000:
        return 3
    elif area < 7000:
        return 4
    elif area < 10000:
        return 5
    else:
        return 5


df["parking"] = df["parking"].fillna(
    df["area"].apply(estimate_parking)
)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20458 entries, 0 to 20478
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20458 non-null  object
 1   address             20458 non-null  object
 2   location            20458 non-null  object
 3   sub_location        20458 non-null  object
 4   price               20458 non-null  float64
 5   price_crore         20458 non-null  float64
 6   price_per_sqft      20458 non-null  float64
 7   area                20458 non-null  float64
 8   bedrooms            20458 non-null  int64
 9   bathrooms           20458 non-null  int64
 10  kitchen             20458 non-null  float64
 11  floor               4008 non-null   float64
 12  total_floors        9609 non-null   float64
 13  parking             20458 non-null  float64
 14  elevator            20458 non-null  int64
 15  servant_quarters    20458 non-null  float64
 16  electricity_backup  20458 non-null  int64
 17  furnished           20458 non-null  int64
 18  completion_year     10852 non-null  float64
 19  property_type       20458 non-null  object
 20  property_age        10852 non-null  float64
 21  age_category        10852 non-null  object
 22  parking_score       20458 non-null  int64
 23  area_per_bedroom    20458 non-null  float64
 24  district            20073 non-null  object
 25  sub_location_type   20458 non-null  object
 26  location_score      20458 non-null  int64
 27  sub_location_score  20458 non-null  int64
 28  expected_floors     1624 non-null   float64
 29  area_group          20458 non-null  category
dtypes: category(1), float64(13), int64(8), object(8)
memory usage: 5.2+ MB

In [100]:
df["property_age_missing"] = df["property_age"].isna().astype(int)
df["total_floors_missing"] = df["total_floors"].isna().astype(int)

In [101]:
df.drop(columns=['expected_floors','area_group'],inplace=True)

In [102]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,...,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score,property_age_missing,total_floors_missing
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,...,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2,0,0
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,...,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2,1,1
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,...,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2,1,0
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,...,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4,1,1
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,...,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2,1,1

In [103]:
df['property_type'].value_counts()

property_type
flat     10559
house     9899
Name: count, dtype: int64

In [114]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,...,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,...,2025.0,house,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,...,NaN,house,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,...,NaN,flat,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,...,NaN,flat,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,...,NaN,flat,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2

In [113]:
df.drop(columns=['property_age_missing','total_floors_missing','age_category_filled','age_category_imputed_from'],inplace=True)

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20458 entries, 0 to 20478
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20458 non-null  object
 1   address             20458 non-null  object
 2   location            20458 non-null  object
 3   sub_location        20458 non-null  object
 4   price               20458 non-null  float64
 5   price_crore         20458 non-null  float64
 6   price_per_sqft      20458 non-null  float64
 7   area                20458 non-null  float64
 8   bedrooms            20458 non-null  int64
 9   bathrooms           20458 non-null  int64
 10  kitchen             20458 non-null  float64
 11  floor               4008 non-null   float64
 12  total_floors        9609 non-null   float64
 13  parking             20458 non-null  float64
 14  elevator            20458 non-null  int64
 15  servant_quarters    20458 non-null  float64
 16  electricity_backup  20458 non-null  int64
 17  furnished           20458 non-null  int64
 18  completion_year     10852 non-null  float64
 19  property_type       20458 non-null  object
 20  property_age        10852 non-null  float64
 21  age_category        10852 non-null  object
 22  parking_score       20458 non-null  int64
 23  area_per_bedroom    20458 non-null  float64
 24  district            20458 non-null  object
 25  sub_location_type   20458 non-null  object
 26  location_score      20458 non-null  int64
 27  sub_location_score  20458 non-null  int64
dtypes: float64(12), int64(8), object(8)
memory usage: 5.0+ MB

In [116]:
df[df['district'].isnull()]['location'].value_counts()

location
Civil Lines             79
Jamshed Town            79
Saddar                  69
Super Highway           54
Gulshan-e-Iqbal Town    37
Shahra-e-Faisal         31
Northern Bypass         26
Malir                   10
Name: count, dtype: int64

In [119]:
district_mapping = {
    # Karachi South
    "DHA Defence": "Karachi South",
    "Clifton": "Karachi South",
    "Civil Lines": "Karachi South",
    "Saddar": "Karachi South",

    # Karachi East
    "Karsaz": "Karachi East",
    "Gulshan-e-Iqbal Town": "Karachi East",
    "Gulistan-e-Jauhar": "Karachi East",
    "Jamshed Town": "Karachi East",
    "Scheme 33": "Karachi East",

    # Karachi Central
    "Federal B Area": "Karachi Central",
    "F.B. Area": "Karachi Central",
    "North Nazimabad": "Karachi Central",
    "North Karachi": "Karachi Central",
    "Nazimabad": "Karachi Central",
    "Naya Nazimabad": "Karachi Central",

    # Malir
    "Malir": "Malir",
    "Malir Cantt": "Malir",
    "Gadap": "Malir",
   
    "Bahria Town": "Malir",
    "Bin Qasim Town": "Malir",

    # Korangi
    "Korangi": "Korangi",
    "Shah Faisal": "Korangi",

    # Multi-District / Routes
    "Super Highway": "Multi-District",
    "Shahra-e-Faisal": "Multi-District",
    "Northern Bypass": "Multi-District"
}

In [120]:
df["district"] = df["location"].map(district_mapping)

In [122]:
df['age_category'].unique()

array(['Relatively New', nan, 'Old', 'New', 'Moderately Old',
       'Under Construction'], dtype=object)

In [129]:
df[df['total_floors'] < df['floor']]

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
14536,zamzam homes 3 bed drawing dining 2100 square ...,"bath island, karachi",Clifton,Bath Island,75000000.0,7.5,35765.38,2097.0,3,4,2.0,18.0,17.0,3.0,1,1.0,1,0,2025.0,flat,1.0,Relatively New,2,699.0,Karachi South,Neighbourhood,5,5

In [130]:
df.loc[14536, 'total_floors'] = 18

In [131]:
df.groupby('property_type')['floor'].apply(lambda x: x.isna().mean())

property_type
flat     0.626669
house    0.993333
Name: floor, dtype: float64

In [132]:
df.shape

(20458, 28)

In [133]:
df.to_csv('karachi_properties_handle_missing_value.csv', index=False)