In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('karachi_properties_handle_missing_value.csv')

In [4]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,1.0,NaN,2.0,3.0,0,0.0,1,1,2025.0,house,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,1.0,NaN,NaN,1.0,0,2.0,1,1,NaN,house,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,0.0,NaN,12.0,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,2.0,NaN,NaN,2.0,0,1.0,1,0,NaN,flat,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,0.0,NaN,NaN,0.0,0,0.0,0,0,NaN,flat,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2

In [5]:
df.drop(index=[13969, 16505], inplace=True)

In [6]:
df.head()

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
0,"brand new, west open","saadi town - block 7, saadi town",Scheme 33,Sector 47,22800000.0,2.28,21111.11,1080.0,4,5,1.0,NaN,2.0,3.0,0,0.0,1,1,2025.0,house,1.0,Relatively New,3,270.00,Karachi East,Subdivision,3,2
1,double storey house available for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,100000000.0,10.00,22222.22,4500.0,5,5,1.0,NaN,NaN,1.0,0,2.0,1,1,NaN,house,NaN,NaN,2,900.00,Karachi Central,Subdivision,4,2
2,166 square yard flat for sale in north nazimab...,"north nazimabad - block f, north nazimabad",North Nazimabad,North Nazimabad Block F,25500000.0,2.55,17068.27,1494.0,3,3,0.0,NaN,12.0,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,498.00,Karachi Central,Subdivision,4,2
3,flat available for sale,"pechs block 2, pechs",Jamshed Town,Pechs,65000000.0,6.50,27049.52,2403.0,4,4,2.0,NaN,NaN,2.0,0,1.0,1,0,NaN,flat,NaN,NaN,1,600.75,Karachi East,Housing Society,4,4
4,north vista 2 bed d d flat for sale,"north nazimabad - block b, north nazimabad",North Nazimabad,North Nazimabad Block B,16500000.0,1.65,17295.60,954.0,2,3,0.0,NaN,NaN,0.0,0,0.0,0,0,NaN,flat,NaN,NaN,0,477.00,Karachi Central,Subdivision,4,2

In [7]:
df['sub_location'].value_counts()

sub_location
Phase 8                                         2047
Phase 6                                          886
Askari 5                                         499
Askari 6                                         490
Falcon Complex New Malir                         449
Phase 5                                          449
Gulshan-E-Maymar                                 442
Gulshan-e-Iqbal Block 10A                        426
Sector 35-A                                      305
Scheme 33_Unspecified                            302
Naya Nazimabad_Unspecified                       301
Phase 7                                          286
Pechs                                            268
Sector 47                                        260
Sector 40                                        251
Falaknaz                                         221
Surjani Town                                     209
Gulistan-e-Jauhar Block 15                       193
Gulshan-e-Iqbal Town_Unspecified                 188
North Nazimabad Block F                          179
Shaheed Millat Road                              173
Saadi Garden                                     169
Clifton Block 2                                  161
Phase 4                                          156
Gulistan-e-Jauhar Block 14                       150
Punjabi Saudagar Society                         147
Gulshan-e-Iqbal Block 1                          144
Sector 29                                        143
Phase 7 Extension                                141
Gulistan-e-Jauhar Block 13                       135
Gulistan-e-Jauhar Block 18                       127
Sector 34-A                                      125
Gulistan-e-Jauhar Block 7                        125
Navy Housing Scheme Karsaz                       124
Gulistan-e-Jauhar Block 3A                       123
Bath Island                                      123
North Nazimabad Block H                          122
Khalid Bin Walid Road                            121
North Nazimabad Block L                          117
Bahadurabad                                      116
Sector 17-A                                      114
Sector 18-A                                      114
North Nazimabad Block N                          113
Sector 16-A                                      109
Gulshan-e-Iqbal Block 2                          106
Gulshan-e-Iqbal Block 4                          105
Sector 44                                        105
Gulistan-e-Jauhar Block 12                       105
Gulistan-e-Jauhar Block 17                       104
Gulistan-e-Jauhar_Unspecified                    100
Allahwala Town                                    99
Model Colony                                      98
Sector 36-A                                       97
Gulshan-e-Iqbal Block 17                          97
Buffer Zone                                       95
Malir Cantt_Unspecified                           95
Gulistan-e-Jauhar Block 2                         94
Bahria Sports City                                94
Sector 19-A                                       93
Naya Nazimabad Block A                            93
Clifton Block 9                                   92
Precinct 2                                        92
Sector 15-A                                       91
Naya Nazimabad Block C                            91
Gulshan-e-Iqbal Block 7                           90
Clifton Block 8                                   88
Clifton Block 1                                   88
Precinct 12                                       85
Kda Scheme 1                                      84
Malir Link To Super Highway                       82
North Nazimabad Block B                           81
North Nazimabad_Unspecified                       80
Civil Lines_Unspecified                           79
North Karachi Sector 11                           78
Gulshan-e-Iqbal Block 5                           77
Precinct 8                                        75
Bahria Apartments                                 74
Gulistan-e-Jauhar Block 16                        74
Gulshan-e-Iqbal Block 13D2                        74
Gulistan-e-Jauhar Block 19                        73
Private High-Rises                                70
Saddar_Unspecified                                69
Saima Villas                                      69
Phase 2 Extension                                 68
Naya Nazimabad Block D                            66
Federal B Area Block 10                           65
Gulshan-e-Iqbal Block 13D1                        65
Airport                                           65
Phase 1                                           64
Jamshed Road                                      60
Phase 2                                           60
Gulistan-e-Jauhar Block 3                         58
Precinct 11A                                      58
Federal B Area_Unspecified                        58
Gulshan-e-Iqbal Block 6                           58
Meerut Society                                    57
Bahria Paradise                                   56
Dhoraji Colony                                    56
Precinct 1                                        54
Bahria Town_Unspecified                           54
DHA City                                          54
Precinct 31                                       54
Gulshan-e-Iqbal Block 13D                         54
Precinct 9                                        54
Naya Nazimabad Block B                            53
North Karachi_Unspecified                         53
North Nazimabad Block M                           52
Clifton_Unspecified                               52
Saadi Road                                        52
Clifton Block 4                                   51
Precinct 10A                                      50
Federal B Area Block 12                           50
Memon Goth                                        49
Precinct 11B                                      48
Sector 43-A                                       48
North Karachi Sector 5                            47
Defence View                                      47
Sector 51-A                                       47
Bahria Heights                                    47
Sharfabad                                         46
Precinct 6                                        45
North Nazimabad Block A                           45
North Nazimabad Block D                           44
Shadman                                           43
Smchs - Sindhi Muslim Society                     43
Frere Town                                        43
Federal B Area Block 21                           42
North Nazimabad Block K                           42
Precinct 10B                                      42
Karachi Administration Employees Society          41
Gohar Green City Cluster                          41
Dohs Phase 1                                      40
Gulshan-e-Iqbal Block 3                           40
Gulistan-e-Jauhar Block 10                        40
Precinct 27                                       40
Gulistan-e-Jauhar Block 1                         40
Clifton Block 7                                   40
Gulshan-e-Iqbal Block 13A                         39
Federal B Area Block 13                           39
Mateen Complex                                    39
Precinct 4                                        37
Saima Projects                                    37
Gulshan-e-Iqbal Block 13C                         37
North Karachi Sector 7                            36
Sector 25-B                                       36
Tariq Road                                        35
Gulistan-e-Jauhar Block 4                         35
North Nazimabad Block J                           35
Malir_Unspecified                                 35
Clifton Block 5                                   34
Shahra-e-Faisal_Unspecified                       34
North Nazimabad Block I                           34
Amir Khusro                                       33
Gulistan-e-Jauhar Block 20                        33
Saima Luxury Belt                                 33
Gulshan-e-Iqbal Block 13D3                        32
Tipu Sultan Road                                  32
Jamshed Town_Unspecified                          32
Precinct 19                                       32
Askari 4                                          32
Garden East                                       31
Gulshan-e-Iqbal Block 11                          31
Amil Colony                                       30
Precinct 16                                       30
Sector 24-A                                       30
Sector 42-A                                       29
Gulistan-e-Jauhar Block 11                        29
Sector 52-A                                       28
Federal B Area Block 11                           28
Sector 38-A                                       26
Gulistan-e-Jauhar Block 5                         26
Shamsi / Al-Falah Belt                            26
DHA Defence_Unspecified                           26
Northern Bypass_Unspecified                       26
Sector 18-C                                       25
Nazimabad 4                                       24
Gulshan-e-Iqbal Block 13B                         24
North Karachi Sector 9                            24
Green Town / Rafah-E-Aam Belt                     24
Gulshan-e-Iqbal Block 16                          23
Sector 30                                         23
Gulshan-e-Iqbal Block 10                          23
Naya Nazimabad Block M                            23
Super Highway_Unspecified                         23
Gulistan-e-Jauhar Block 16A                       22
National Stadium Colony                           22
Sector 20-A                                       22
Gizri                                             21
Nazimabad 3                                       21
Phase 5 Extension                                 21
North Nazimabad Block G                           21
Sector 24-B                                       20
Soldier Bazar                                     20
Parsi Colony                                      20
Federal B Area Block 9                            19
Federal B Area Block 14                           19
Korangi Industrial Area                           19
Precinct 17                                       19
Federal B Area Block 8                            18
Gulshan-e-Iqbal Block 19                          18
Sector 22-A                                       18
Mehmoodabad                                       18
Mohammad Ali Society                              17
Gulshan-e-Usman Housing Society                   17
Gulshan-e-Iqbal Block 9                           17
Cosmopolitan Society                              17
Precinct 15                                       17
Federal B Area Block 19                           17
Adamjee Nagar                                     16
Golden Town                                       16
Jamia Millia Road                                 16
Gulshan-e-Iqbal Block 14                          16
Kda Employees Society                             16
Gulistan-e-Jauhar Block 9                         15
Gulshan-e-Iqbal Block 13-C                        15
Shah Faisal_Unspecified                           14
Federal B Area Block 16                           14
Shahra-E-Qaideen                                  14
Falcon Complex Faisal                             14
North Karachi Sector 10                           14
North Karachi Sector 8                            14
Qayyumabad                                        14
Gulshan-e-Iqbal Block 21                          13
Sector 48-A                                       13
Federal B Area Block 15                           13
Nazimabad 1                                       13
Cp Barar Society, Gulshan-E-Iqbal Town            13
Muslimabad Society                                12
Phase 8 Extension                                 12
North Nazimabad Block C                           12
Gulshan-e-Iqbal Block 13                          12
Defence Skyline, Shaheed-E-Millat Expressway      12
Federal B Area Block 6                            12
Dohs Phase 2                                      11
Clifton Block 6                                   11
Malir Town Residency                              11
Federal B Area Block 7                            11
Kda Scheme 1 Extension                            11
Clifton Block 3                                   11
Federal B Area Block 20                           10
Shahrah-E-Pakistan                                10
Sector 45-A                                       10
Sector 17-B                                       10
sector 11a                                         9
Rabia Enclave                                      9
New Karachi                                        9
Nazimabad 5                                        9
Nazimabad 2                                        8
Safoora Goth                                       8
Nazimabad_Unspecified                              7
Precinct 7                                         7
Gulistan-e-Jauhar Block 8                          7
Oasis Park Residencia                              6
Yousaf Goth                                        5
Precinct 18                                        5
Korangi_Unspecified                                3
Name: count, dtype: int64

In [8]:
df[df['location']=='super_highway']

Empty DataFrame
Columns: [property_name, address, location, sub_location, price, price_crore, price_per_sqft, area, bedrooms, bathrooms, kitchen, floor, total_floors, parking, elevator, servant_quarters, electricity_backup, furnished, completion_year, property_type, property_age, age_category, parking_score, area_per_bedroom, district, sub_location_type, location_score, sub_location_score]
Index: []

In [9]:
df['location'].value_counts()

location
DHA Defence             4208
Scheme 33               3063
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
Jamshed Town            1059
North Nazimabad         1020
Malir                    922
Clifton                  815
Gadap                    694
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            161
Shah Faisal              152
Korangi                  151
Karsaz                   124
Nazimabad                 82
Civil Lines               79
Saddar                    69
Bin Qasim Town            39
Shahra-e-Faisal           34
Northern Bypass           26
Name: count, dtype: int64

In [10]:
df[df['location']=='Super Highway']['sub_location'].value_counts()

sub_location
Saima Villas                 69
DHA City                     54
Super Highway_Unspecified    23
Rabia Enclave                 9
Oasis Park Residencia         6
Name: count, dtype: int64

In [11]:
df[df['location']=='Scheme 33']['sub_location'].value_counts()

sub_location
Sector 35-A                        305
Scheme 33_Unspecified              302
Sector 47                          260
Sector 40                          251
Saadi Garden                       169
Punjabi Saudagar Society           147
Sector 29                          143
Sector 34-A                        125
Sector 17-A                        114
Sector 18-A                        114
Sector 16-A                        109
Falaknaz                           108
Sector 44                          105
Sector 36-A                         97
Sector 19-A                         93
Sector 15-A                         91
Meerut Society                      57
Saadi Road                          52
Sector 43-A                         48
Sector 51-A                         47
Sector 25-B                         36
Sector 24-A                         30
Sector 42-A                         29
Sector 52-A                         28
Sector 38-A                         26
Sector 18-C                         25
Sector 30                           23
Sector 20-A                         22
Sector 24-B                         20
Sector 22-A                         18
Gulshan-e-Usman Housing Society     17
Sector 48-A                         13
Sector 45-A                         10
Sector 17-B                         10
Phase 2                              8
Gulshan-E-Maymar                     6
Yousaf Goth                          5
Name: count, dtype: int64

In [12]:
df.loc[
    df["sub_location"].str.contains("Rabia Enclave", case=False, na=False), 
    ["location", "sub_location"]
] = ["Scheme 33", "Sector 17-B"]

print(df[df["sub_location"] == "Sector 17-B"]["sub_location"].value_counts())

sub_location
Sector 17-B    19
Name: count, dtype: int64

In [13]:
df[df['location']=='Gadap']['sub_location'].value_counts()

sub_location
Gulshan-E-Maymar    436
Surjani Town        209
Memon Goth           49
Name: count, dtype: int64

In [14]:
df = df[~(
    (df["location"] == "Scheme 33") & 
    (df["sub_location"].isin(["Yousaf Goth", "Phase 2"]))
)]

print(df[df["location"] == "Scheme 33"]["sub_location"].value_counts())

sub_location
Sector 35-A                        305
Scheme 33_Unspecified              302
Sector 47                          260
Sector 40                          251
Saadi Garden                       169
Punjabi Saudagar Society           147
Sector 29                          143
Sector 34-A                        125
Sector 17-A                        114
Sector 18-A                        114
Sector 16-A                        109
Falaknaz                           108
Sector 44                          105
Sector 36-A                         97
Sector 19-A                         93
Sector 15-A                         91
Meerut Society                      57
Saadi Road                          52
Sector 43-A                         48
Sector 51-A                         47
Sector 25-B                         36
Sector 24-A                         30
Sector 42-A                         29
Sector 52-A                         28
Sector 38-A                         26
Sector 18-C                         25
Sector 30                           23
Sector 20-A                         22
Sector 24-B                         20
Sector 17-B                         19
Sector 22-A                         18
Gulshan-e-Usman Housing Society     17
Sector 48-A                         13
Sector 45-A                         10
Gulshan-E-Maymar                     6
Name: count, dtype: int64

In [15]:
df.loc[
    (df["location"] == "Scheme 33") & (df["sub_location"].str.contains("Gulshan-E-Maymar", case=False, na=False)), 
    "location"
] = "Gadap"


print(df[df["location"] == "Gadap"]["sub_location"].value_counts())

sub_location
Gulshan-E-Maymar    442
Surjani Town        209
Memon Goth           49
Name: count, dtype: int64

In [16]:
df['location'].value_counts()

location
DHA Defence             4208
Scheme 33               3053
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
Jamshed Town            1059
North Nazimabad         1020
Malir                    922
Clifton                  815
Gadap                    700
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            152
Shah Faisal              152
Korangi                  151
Karsaz                   124
Nazimabad                 82
Civil Lines               79
Saddar                    69
Bin Qasim Town            39
Shahra-e-Faisal           34
Northern Bypass           26
Name: count, dtype: int64

In [17]:
df[df['location']=='Gulshan-e-Iqbal Town']['sub_location'].value_counts()

sub_location
Gulshan-e-Iqbal Block 10A                 426
Gulshan-e-Iqbal Town_Unspecified          188
Gulshan-e-Iqbal Block 1                   144
Bahadurabad                               116
Gulshan-e-Iqbal Block 2                   106
Gulshan-e-Iqbal Block 4                   105
Gulshan-e-Iqbal Block 17                   97
Gulshan-e-Iqbal Block 7                    90
Kda Scheme 1                               84
Gulshan-e-Iqbal Block 5                    77
Gulshan-e-Iqbal Block 13D2                 74
Gulshan-e-Iqbal Block 13D1                 65
Gulshan-e-Iqbal Block 6                    58
Dhoraji Colony                             56
Gulshan-e-Iqbal Block 13D                  54
Sharfabad                                  46
Gulshan-e-Iqbal Block 3                    40
Gulshan-e-Iqbal Block 13A                  39
Gulshan-e-Iqbal Block 13C                  37
Gulshan-e-Iqbal Block 13D3                 32
Gulshan-e-Iqbal Block 11                   31
Gulshan-e-Iqbal Block 13B                  24
Gulshan-e-Iqbal Block 16                   23
Gulshan-e-Iqbal Block 10                   23
National Stadium Colony                    22
Gulshan-e-Iqbal Block 19                   18
Mohammad Ali Society                       17
Gulshan-e-Iqbal Block 9                    17
Gulshan-e-Iqbal Block 14                   16
Adamjee Nagar                              16
Gulshan-e-Iqbal Block 13-C                 15
Gulshan-e-Iqbal Block 21                   13
Cp Barar Society, Gulshan-E-Iqbal Town     13
Gulshan-e-Iqbal Block 13                   12
Kda Scheme 1 Extension                     11
Name: count, dtype: int64

In [18]:
df.loc[
    (df["location"] == "Gulshan-e-Iqbal Town") & (df["sub_location"] == "Gulshan-e-Iqbal Block 13-C"), 
    "sub_location"
] = "Gulshan-e-Iqbal Block 13C"

In [19]:
print(df[df["location"] == "Jamshed Town"]["sub_location"].value_counts())

sub_location
Pechs                                           268
Shaheed Millat Road                             173
Khalid Bin Walid Road                           121
Jamshed Road                                     60
Defence View                                     47
Smchs - Sindhi Muslim Society                    43
Karachi Administration Employees Society         41
Tariq Road                                       35
Amir Khusro                                      33
Jamshed Town_Unspecified                         32
Tipu Sultan Road                                 32
Garden East                                      31
Amil Colony                                      30
Soldier Bazar                                    20
Parsi Colony                                     20
Mehmoodabad                                      18
Cosmopolitan Society                             17
Shahra-E-Qaideen                                 14
Muslimabad Society                               12
Defence Skyline, Shaheed-E-Millat Expressway     12
Name: count, dtype: int64

In [20]:
df.loc[
    (df["location"] == "Jamshed Town") & 
    (df["sub_location"] == "Defence Skyline, Shaheed-E-Millat Expressway"), 
    "sub_location"
] = "Shaheed E Millat"


print(df[df["location"] == "Jamshed Town"]["sub_location"].value_counts())

sub_location
Pechs                                       268
Shaheed Millat Road                         173
Khalid Bin Walid Road                       121
Jamshed Road                                 60
Defence View                                 47
Smchs - Sindhi Muslim Society                43
Karachi Administration Employees Society     41
Tariq Road                                   35
Amir Khusro                                  33
Jamshed Town_Unspecified                     32
Tipu Sultan Road                             32
Garden East                                  31
Amil Colony                                  30
Soldier Bazar                                20
Parsi Colony                                 20
Mehmoodabad                                  18
Cosmopolitan Society                         17
Shahra-E-Qaideen                             14
Muslimabad Society                           12
Shaheed E Millat                             12
Name: count, dtype: int64

In [21]:
df.loc[
    (df["location"] == "Jamshed Town") & 
    (df["sub_location"] == "Shaheed E Millat"), 
    "sub_location"
] = "Shaheed Millat Road"


print(df[df["location"] == "Naya Nazimabad"]["sub_location"].value_counts())

sub_location
Naya Nazimabad_Unspecified    301
Naya Nazimabad Block A         93
Naya Nazimabad Block C         91
Naya Nazimabad Block D         66
Naya Nazimabad Block B         53
Naya Nazimabad Block M         23
Name: count, dtype: int64

In [22]:
x=df[df["location"] == "Naya Nazimabad"]['property_name']

In [ ]:
import re
import numpy as np

mask = (
    df['location'].str.strip().str.lower().eq('naya nazimabad') &
    df['sub_location'].str.strip().str.lower().eq('naya nazimabad_unspecified')
)

# Combine the property name and address so both can help identify the block.
text = (
    df['property_name'].fillna('').astype(str) + ' ' +
    df['address'].fillna('').astype(str)
).str.lower()

# Look for a block letter and ignore any other text around it.
block = text.str.extract(
    r'(?:block|blk)[\s\-]*([a-z])\b',
    expand=False
)

# Format the extracted letter as a standard Naya Nazimabad block name.
extracted = block.str.upper().map(
    lambda x: f'Naya Nazimabad Block {x}' if pd.notna(x) else np.nan
)

# Fill in only the rows where a matching block was found.
update_mask = mask & extracted.notna()

df.loc[update_mask, 'sub_location'] = extracted[update_mask]

print("Updated:", update_mask.sum())

print(
    df.loc[
        df['location'].str.strip().str.lower().eq('naya nazimabad'),
        'sub_location'
    ].value_counts()
)

Updated: 0
sub_location
Naya Nazimabad_Unspecified    301
Naya Nazimabad Block A         93
Naya Nazimabad Block C         91
Naya Nazimabad Block D         66
Naya Nazimabad Block B         53
Naya Nazimabad Block M         23
Name: count, dtype: int64

In [24]:
df[df["location"] == "Naya Nazimabad"]['sub_location'].value_counts()

sub_location
Naya Nazimabad_Unspecified    301
Naya Nazimabad Block A         93
Naya Nazimabad Block C         91
Naya Nazimabad Block D         66
Naya Nazimabad Block B         53
Naya Nazimabad Block M         23
Name: count, dtype: int64

In [25]:
text = (
    df['property_name'].fillna('').astype(str) + ' ' +
    df['address'].fillna('').astype(str)
).str.lower()

block = text.str.extract(
    r'\b(?:block|blk)\s*[-]?\s*([a-z])\b',
    expand=False
).str.upper()

print(block[mask].value_counts(dropna=False))

NaN    301
Name: count, dtype: int64

In [26]:
x=df[(df['location']=='Naya Nazimabad') & (df['sub_location']=='Naya Nazimabad_Unspecified')]['property_name']

In [ ]:
# Match each known project with the block where it is located.
project_block_map = {
    'Globe Residency': 'Naya Nazimabad Block B',
    'Peace Apartment': 'Naya Nazimabad Block A',
    'Rahat Residency': 'Naya Nazimabad Block B', # Or Block D as appropriate
    'Stadium View Residencia': 'Naya Nazimabad Block A',
    'Signature Tower': 'Naya Nazimabad Block A'
}

# Replace the project name with its standard block label.
for project, block in project_block_map.items():
    mask = (
        (df['location'].str.strip().str.lower() == 'naya nazimabad') & 
        (df['sub_location'].str.contains(project, case=False, na=False))
    )
    df.loc[mask, 'sub_location'] = block

# Check the updated distribution of Naya Nazimabad sub-locations.
print(df[df['location'].str.strip().str.lower() == 'naya nazimabad']['sub_location'].value_counts())

sub_location
Naya Nazimabad_Unspecified    301
Naya Nazimabad Block A         93
Naya Nazimabad Block C         91
Naya Nazimabad Block D         66
Naya Nazimabad Block B         53
Naya Nazimabad Block M         23
Name: count, dtype: int64

In [28]:
print(df[df["location"] == "Federal B Area"]["sub_location"].value_counts())

sub_location
Federal B Area Block 10       65
Federal B Area_Unspecified    58
Federal B Area Block 12       50
Federal B Area Block 21       42
Federal B Area Block 13       39
Federal B Area Block 11       28
Federal B Area Block 9        19
Federal B Area Block 14       19
Federal B Area Block 8        18
Federal B Area Block 19       17
Federal B Area Block 16       14
Federal B Area Block 15       13
Federal B Area Block 6        12
Federal B Area Block 7        11
Shahrah-E-Pakistan            10
Federal B Area Block 20       10
Name: count, dtype: int64

In [29]:
x=df[(df['location']=='Federal B Area') & (df['sub_location']=='Federal B Area_Unspecified')]['property_name']

In [ ]:
# Standardize standalone block names under Federal B Area.
fba_block_mapping = {
    'Block 2': 'Federal B Area Block 2',
    'Block 3': 'Federal B Area Block 3',
    'Block 4': 'Federal B Area Block 4',
    'Block 5': 'Federal B Area Block 5',
    'Block 8': 'Federal B Area Block 8',
    'Block 9': 'Federal B Area Block 9',
    'Block 17': 'Federal B Area Block 17',
    'Block 18': 'Federal B Area Block 18',
    'Block 21': 'Federal B Area Block 21',
}

df['sub_location'] = df['sub_location'].replace(fba_block_mapping)

In [ ]:
# Count the Federal B Area sub-locations before grouping the rare ones.
fb_counts = df[df['location'].str.strip() == 'Federal B Area']['sub_location'].value_counts()

# Treat sub-locations with four or fewer records as unspecified.
low_count_subs = fb_counts[fb_counts <= 4].index

# Replace those rare labels only within Federal B Area.
mask = (df['location'].str.strip() == 'Federal B Area') & (df['sub_location'].isin(low_count_subs))
df.loc[mask, 'sub_location'] = 'Federal B Area_Unspecified'

# Confirm the final Federal B Area sub-location counts.
print(df[df['location'].str.strip() == 'Federal B Area']['sub_location'].value_counts())

sub_location
Federal B Area Block 10       65
Federal B Area_Unspecified    58
Federal B Area Block 12       50
Federal B Area Block 21       42
Federal B Area Block 13       39
Federal B Area Block 11       28
Federal B Area Block 9        19
Federal B Area Block 14       19
Federal B Area Block 8        18
Federal B Area Block 19       17
Federal B Area Block 16       14
Federal B Area Block 15       13
Federal B Area Block 6        12
Federal B Area Block 7        11
Shahrah-E-Pakistan            10
Federal B Area Block 20       10
Name: count, dtype: int64

In [32]:
df[(df['location']=='North Karachi')]['sub_location'].value_counts()

sub_location
Buffer Zone                  95
North Karachi Sector 11      78
North Karachi_Unspecified    53
North Karachi Sector 5       47
North Karachi Sector 7       36
North Karachi Sector 9       24
North Karachi Sector 10      14
North Karachi Sector 8       14
sector 11a                    9
New Karachi                   9
Name: count, dtype: int64

In [33]:
df[df['location']=='North Karachi']['sub_location'].value_counts()

sub_location
Buffer Zone                  95
North Karachi Sector 11      78
North Karachi_Unspecified    53
North Karachi Sector 5       47
North Karachi Sector 7       36
North Karachi Sector 9       24
North Karachi Sector 10      14
North Karachi Sector 8       14
sector 11a                    9
New Karachi                   9
Name: count, dtype: int64

In [34]:
mask = (df['location'].str.strip() == 'North Karachi') & (df['sub_location'].str.lower() == 'sector 11a')
df.loc[mask, 'sub_location'] = 'North Karachi Sector 11'

print(df[df['location'].str.strip() == 'North Karachi']['sub_location'].value_counts())

sub_location
Buffer Zone                  95
North Karachi Sector 11      87
North Karachi_Unspecified    53
North Karachi Sector 5       47
North Karachi Sector 7       36
North Karachi Sector 9       24
North Karachi Sector 10      14
North Karachi Sector 8       14
New Karachi                   9
Name: count, dtype: int64

In [35]:
x=df[(df['location']=='North Karachi') & (df['sub_location']=='North Karachi_Unspecified')]['property_name']
x.to_csv('xyz.csv')

In [37]:
import re
import pandas as pd

SECTOR_RE = re.compile(
    r'\bsector\.?\s*-?\s*([0-9]+[a-z0-9]*(?:[\-/][a-z0-9]+)*)(?:\s+([a-z])\b)?',
    re.IGNORECASE
)

def extract_sector(text):
    if not isinstance(text, str):
        return None
    m = SECTOR_RE.search(text)
    if m:
        val = m.group(1).upper()
        if m.group(2):
            val += m.group(2).upper()
        return f"Sector {val}"
    return None

extracted = x.apply(extract_sector)
extracted = extracted.apply(lambda v: f"North Karachi {v}" if pd.notna(v) else None)


df.loc[extracted.index, 'sub_location'] = extracted.combine_first(df.loc[extracted.index, 'sub_location'])

In [38]:
df[(df['location']=='') & (df['sub_location']=='Federal B Area_Unspecified')]['property_name']

Series([], Name: property_name, dtype: object)

In [39]:
sub_location_mapping = {
    "North Karachi Sector 11A": "North Karachi Sector 11",
    "North Karachi Sector 11-C/1": "North Karachi Sector 11",
    "North Karachi Sector 5K": "North Karachi Sector 5",
    "North Karachi Sector 5A3": "North Karachi Sector 5"
}

df["sub_location"] = df["sub_location"].replace(sub_location_mapping)

In [40]:
df[df['location']=='Shah Faisal']['sub_location'].value_counts()

sub_location
Gohar Green City Cluster         41
Saima Luxury Belt                33
Shamsi / Al-Falah Belt           26
Green Town / Rafah-E-Aam Belt    24
Falcon Complex Faisal            14
Shah Faisal_Unspecified          14
Name: count, dtype: int64

In [41]:
x=df[(df['location']=='Shah Faisal') & (df['sub_location']=='Shah Faisal_Unspecified')]['property_name']
x.to_csv('xyz.csv')

In [ ]:
# Move Falcon Complex Faisal under its correct parent location.
mask = df['sub_location'].str.contains('Falcon Complex Faisal', case=False, na=False)
df.loc[mask, 'location'] = 'Jamshed Town'

# Confirm the parent and sub-location values after the update.
print(df[df['sub_location'].str.contains('Falcon Complex Faisal', case=False, na=False)][['location', 'sub_location']].value_counts())

location      sub_location
Jamshed Town  Falcon Complex Faisal    14
Name: count, dtype: int64

In [43]:
df[df['location']=='Korangi']['sub_location'].value_counts()

sub_location
Allahwala Town             99
Korangi Industrial Area    19
Kda Employees Society      16
Qayyumabad                 14
Korangi_Unspecified         3
Name: count, dtype: int64

In [44]:
df = df[df['sub_location'] != 'Korangi_Unspecified']

In [45]:
df[df['location']=='Nazimabad']['sub_location'].value_counts()

sub_location
Nazimabad 4              24
Nazimabad 3              21
Nazimabad 1              13
Nazimabad 5               9
Nazimabad 2               8
Nazimabad_Unspecified     7
Name: count, dtype: int64

In [46]:
df[(df['location']=='Nazimabad') & (df['sub_location']=='Nazimabad_Unspecified')]['property_name']

126                  luxurious 4 bed dd naz no-4 2nd floor
150                           flat for sale nazimabad no 3
613      westopen corner park facing lift 3bed dd naz no-2
7341           spacious 2 bed d. d flat available for sale
16905                           fourth floor flat for sale
18068    park face 133 sq yd house for sale near paposh...
18075    2 bed dd booking available at flexible payment...
Name: property_name, dtype: object

In [47]:
df = df[df['sub_location'] != 'Nazimabad_Unspecified']

In [48]:
df[df['location']=='Civil Lines']

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
53,apartment booking available for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,43500000.0,4.35,30208.33,1440.0,3,4,1.0,4.0,47.0,1.0,1,1.0,1,1,2030.0,flat,-4.0,Under Construction,1,480.00,Karachi South,Unspecified,4,4
170,ideal prime location flat is available for sal...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,16000000.0,1.60,21419.01,747.0,2,2,1.0,NaN,1.0,1.0,1,0.0,1,1,NaN,flat,NaN,NaN,1,373.50,Karachi South,Unspecified,4,4
190,flat of 2200 square feet is available for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,52500000.0,5.25,23907.10,2196.0,4,5,1.0,NaN,NaN,1.0,0,1.0,0,1,NaN,flat,NaN,NaN,1,549.00,Karachi South,Unspecified,4,4
431,4 bed flat for sell civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,75000000.0,7.50,29976.02,2502.0,4,4,0.0,NaN,NaN,0.0,0,2.0,1,0,NaN,flat,NaN,NaN,0,625.50,Karachi South,Unspecified,4,4
449,super luxury apartment for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,4,1.0,35.0,50.0,2.0,1,2.0,1,0,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
709,affordable flat for sale in civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32000000.0,3.20,23703.70,1350.0,3,3,0.0,NaN,NaN,2.0,1,1.0,1,0,NaN,flat,NaN,NaN,1,450.00,Karachi South,Unspecified,4,4
732,luxury 4 bed dd apartment for sale abeeda towe...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,33972.82,2502.0,4,5,1.0,NaN,NaN,1.0,1,2.0,1,1,2010.0,flat,16.0,Old,1,625.50,Karachi South,Unspecified,4,4
1002,get your hands on flat in civil lines best area,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,60000000.0,6.00,33333.33,1800.0,3,3,1.0,7.0,9.0,1.0,1,1.0,1,0,NaN,flat,NaN,NaN,1,600.00,Karachi South,Unspecified,4,4
1076,fully renovated 4 bedroom apartment available ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,87500000.0,8.75,34972.02,2502.0,4,4,1.0,NaN,14.0,2.0,1,2.0,1,1,NaN,flat,NaN,NaN,1,625.50,Karachi South,Unspecified,4,4
1082,flats available on booking at prime location o...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,102500000.0,10.25,46675.77,2196.0,4,4,2.0,4.0,40.0,3.0,1,1.0,1,1,2024.0,flat,2.0,Relatively New,2,549.00,Karachi South,Unspecified,4,4
1264,"(christian building) one eye building, 2 bedro...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,12500000.0,1.25,18768.77,666.0,2,1,1.0,NaN,8.0,1.0,1,0.0,1,1,2018.0,flat,8.0,Moderately Old,1,333.00,Karachi South,Unspecified,4,4
1272,abeeda tower flat for sale full furnished,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,87500000.0,8.75,33640.91,2601.0,4,4,1.0,NaN,NaN,1.0,1,2.0,1,1,NaN,flat,NaN,NaN,1,650.25,Karachi South,Unspecified,4,4
1294,"flat for sale in citi club residency, civil l...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,147500000.0,14.75,42130.82,3501.0,4,5,1.0,NaN,NaN,3.0,1,2.0,1,0,2010.0,flat,16.0,Old,2,875.25,Karachi South,Unspecified,4,4
1303,apartment could be your dream house when you c...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,110000000.0,11.00,39299.75,2799.0,4,5,0.0,3.0,14.0,2.0,1,2.0,1,0,2018.0,flat,8.0,Moderately Old,1,699.75,Karachi South,Unspecified,4,4
1949,3000 sq ft super luxury appartment sale on und...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,28361.70,2997.0,4,5,0.0,NaN,NaN,1.0,0,2.0,1,0,NaN,flat,NaN,NaN,1,749.25,Karachi South,Unspecified,4,4
2049,4 bed luxury apartment for sale in sawera comf...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,122500000.0,12.25,47097.27,2601.0,4,5,1.0,4.0,12.0,2.0,1,2.0,1,1,2024.0,flat,2.0,Relatively New,1,650.25,Karachi South,Unspecified,4,4
2230,"marina residence,civil line near pc hotel , 3/...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32000000.0,3.20,24691.36,1296.0,3,3,0.0,3.0,NaN,2.0,1,1.0,1,0,2026.0,flat,0.0,New,1,432.00,Karachi South,Unspecified,4,4
2240,"hsj icon 3 bed d,d for sale","hsj icon, civil lines",Civil Lines,Civil Lines_Unspecified,50000000.0,5.00,27917.36,1791.0,3,3,1.0,15.0,46.0,1.0,1,1.0,1,1,2025.0,flat,1.0,Relatively New,1,597.00,Karachi South,Unspecified,4,4
2289,chapal sky mark 3 bed rooms brand new tallest ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,37453.18,2403.0,3,4,0.0,NaN,NaN,0.0,0,1.0,0,0,NaN,flat,NaN,NaN,0,801.00,Karachi South,Unspecified,4,4
2685,luxury furnished 4 bed dd apartment for sale a...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,33972.82,2502.0,4,5,2.0,9.0,NaN,2.0,1,2.0,1,1,2014.0,flat,12.0,Old,1,625.50,Karachi South,Unspecified,4,4
2830,brand new apartment 3 bed dd available,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,52000000.0,5.20,23679.42,2196.0,3,4,1.0,25.0,NaN,1.0,1,1.0,1,0,2028.0,flat,-2.0,Under Construction,1,732.00,Karachi South,Unspecified,4,4
2991,get in touch now to buy a flat in civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,48000000.0,4.80,28218.69,1701.0,3,3,2.0,NaN,NaN,1.0,1,1.0,1,1,NaN,flat,NaN,NaN,1,567.00,Karachi South,Unspecified,4,4
3188,luxurious 3 bed flat available in chapal sky mark,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,4,1.0,15.0,50.0,1.0,1,2.0,1,1,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
3320,luxury 3 & 4 bed apartments for sale in marina...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32000000.0,3.20,24691.36,1296.0,3,3,1.0,NaN,NaN,1.0,1,1.0,0,0,2030.0,flat,-4.0,Under Construction,1,432.00,Karachi South,Unspecified,4,4
3534,spacious 3bedrooms apartment for sale in high ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,42542.54,1998.0,3,4,1.0,1.0,20.0,2.0,1,1.0,1,1,2018.0,flat,8.0,Moderately Old,1,666.00,Karachi South,Unspecified,4,4
4550,luxurious 3bedrooms apartment for sale with al...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,4,1.0,10.0,50.0,2.0,1,2.0,1,1,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
5049,luxury 3 bed apartments for sale pakistan tall...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,4,1.0,NaN,50.0,1.0,1,2.0,1,1,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
5381,4 bed dd flat for sale in civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,33500000.0,3.35,19694.30,1701.0,4,4,1.0,NaN,12.0,1.0,1,1.0,1,1,2000.0,flat,26.0,Old,1,425.25,Karachi South,Unspecified,4,4
5895,a super luxury apartment by sawera 3 bed dd,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,65000000.0,6.50,28322.44,2295.0,3,4,1.0,NaN,38.0,1.0,1,1.0,1,0,2023.0,flat,3.0,Relatively New,1,765.00,Karachi South,Unspecified,4,4
5984,"under construction today, iconic tomorrow book...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,34500000.0,3.45,22817.46,1512.0,3,3,3.0,NaN,NaN,1.0,1,1.0,1,1,NaN,flat,NaN,NaN,1,504.00,Karachi South,Unspecified,4,4
6029,city club & residency flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,150000000.0,15.00,41050.90,3654.0,4,4,1.0,NaN,NaN,3.0,1,2.0,1,1,2015.0,flat,11.0,Old,2,913.50,Karachi South,Unspecified,4,4
6345,get in touch now to buy a flat in civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,37037.04,2295.0,3,4,2.0,NaN,22.0,2.0,1,1.0,1,1,2023.0,flat,3.0,Relatively New,1,765.00,Karachi South,Unspecified,4,4
6421,you can find a gorgeous flat for sale in civil...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,120000000.0,12.00,41407.87,2898.0,4,4,0.0,NaN,NaN,0.0,0,2.0,0,0,NaN,flat,NaN,NaN,0,724.50,Karachi South,Unspecified,4,4
6423,"purely residential corner 3 bed,d,d, store roo...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32500000.0,3.25,18613.97,1746.0,3,3,1.0,4.0,4.0,1.0,0,1.0,1,1,2015.0,flat,11.0,Old,1,582.00,Karachi South,Unspecified,4,4
6580,chance deal | 4 bed luxury apartment for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,61500000.0,6.15,23644.75,2601.0,4,5,1.0,NaN,NaN,2.0,1,2.0,1,1,2012.0,flat,14.0,Old,1,650.25,Karachi South,Unspecified,4,4
7009,experience karachi from 50th floor,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,39062.50,2304.0,3,3,1.0,30.0,50.0,1.0,1,1.0,1,0,2026.0,flat,0.0,New,1,768.00,Karachi South,Unspecified,4,4
7314,3 bedroom drawing dining 2200 sqft apartment o...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,52000000.0,5.20,23679.42,2196.0,3,3,0.0,NaN,26.0,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,732.00,Karachi South,Unspecified,4,4
7413,marina residency clifton - flexible 4 year pay...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32000000.0,3.20,24024.02,1332.0,3,4,1.0,9.0,17.0,1.0,1,1.0,1,1,2030.0,flat,-4.0,Under Construction,1,444.00,Karachi South,Unspecified,4,4
8351,luxury 4 bed dd apartment for sale in abeeda t...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,80000000.0,8.00,30757.40,2601.0,4,5,0.0,NaN,NaN,2.0,1,2.0,0,0,NaN,flat,NaN,NaN,1,650.25,Karachi South,Unspecified,4,4
8396,flat available in sawera comfort,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,115000000.0,11.50,45963.23,2502.0,4,5,1.0,9.0,38.0,1.0,1,2.0,1,1,2024.0,flat,2.0,Relatively New,1,625.50,Karachi South,Unspecified,4,4
8727,flat 4 bed dd at civil lines for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,102500000.0,10.25,42655.01,2403.0,4,4,2.0,NaN,14.0,2.0,1,1.0,1,0,2020.0,flat,6.0,Moderately Old,1,600.75,Karachi South,Unspecified,4,4
8748,"renovated 1 bedroom with attached bathroom, lo...","civil lines, karachi",Civil Lines,Civil Lines_Unspecified,10000000.0,1.00,19841.27,504.0,1,1,1.0,5.0,5.0,1.0,1,0.0,1,0,2025.0,flat,1.0,Relatively New,1,504.00,Karachi South,Unspecified,4,4
8785,brand new high-floor apartment for sale | 3 be...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,34602.08,2601.0,3,3,1.0,NaN,NaN,1.0,1,2.0,1,1,NaN,flat,NaN,NaN,1,867.00,Karachi South,Unspecified,4,4
9030,premium 2035 square feet flat is available for...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,51500000.0,5.15,25319.57,2034.0,4,4,1.0,NaN,NaN,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,508.50,Karachi South,Unspecified,4,4
9078,luxury 4bed drawing apartment for sale in civi...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,120000000.0,12.00,40040.04,2997.0,4,5,1.0,NaN,10.0,3.0,1,2.0,1,1,2024.0,flat,2.0,Relatively New,2,749.25,Karachi South,Unspecified,4,4
9115,luxury 3 bed apartments for sale | pakistans t...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,4,1.0,NaN,50.0,1.0,1,2.0,1,0,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
9564,4-bedroom apartment 4-years payment plan reali...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,43600000.0,4.36,21341.16,2043.0,4,4,1.0,NaN,NaN,1.0,1,1.0,1,1,NaN,flat,NaN,NaN,1,510.75,Karachi South,Unspecified,4,4
9866,4 bed flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,135000000.0,13.50,45731.71,2952.0,4,5,2.0,1.0,9.0,2.0,1,2.0,1,1,2022.0,flat,4.0,Relatively New,1,738.00,Karachi South,Unspecified,4,4
10162,idyllic flat available in civil lines for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,105000000.0,10.50,47814.21,2196.0,3,3,1.0,NaN,NaN,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,732.00,Karachi South,Unspecified,4,4
10674,zamzam tower flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,85000000.0,8.50,40534.10,2097.0,3,4,2.0,NaN,NaN,4.0,0,1.0,1,1,2026.0,flat,0.0,New,2,699.00,Karachi South,Unspecified,4,4
10810,a secure project where you can enjoy all ameni...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,43000000.0,4.30,28609.45,1503.0,3,3,2.0,15.0,44.0,2.0,1,1.0,1,1,2028.0,flat,-2.0,Under Construction,1,501.00,Karachi South,Unspecified,4,4
11437,saars 3 | signature residences flat,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,57600000.0,5.76,28444.44,2025.0,4,4,1.0,NaN,49.0,1.0,1,1.0,1,0,2032.0,flat,-6.0,Under Construction,1,506.25,Karachi South,Unspecified,4,4
11863,apprment for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,87500000.0,8.75,33640.91,2601.0,4,5,2.0,8.0,14.0,2.0,1,2.0,1,1,2018.0,flat,8.0,Moderately Old,1,650.25,Karachi South,Unspecified,4,4
11886,ideally located flat for sale in civil lines a...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,87500000.0,8.75,33640.91,2601.0,4,5,2.0,7.0,14.0,2.0,1,2.0,1,1,2018.0,flat,8.0,Moderately Old,1,650.25,Karachi South,Unspecified,4,4
12220,chapal sky mark brand new building beautiful f...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,5,1.0,10.0,50.0,1.0,1,2.0,1,1,2026.0,flat,0.0,New,1,849.00,Karachi South,Unspecified,4,4
13338,prime location 2800 square feet flat in only r...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,122500000.0,12.25,43765.63,2799.0,4,5,1.0,5.0,14.0,1.0,1,2.0,1,1,2015.0,flat,11.0,Old,1,699.75,Karachi South,Unspecified,4,4
13441,luxury 3 bedrooms 2100 square feet apartment f...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,62500000.0,6.25,29804.48,2097.0,3,4,1.0,1.0,5.0,1.0,1,1.0,1,0,2008.0,flat,18.0,Old,1,699.00,Karachi South,Unspecified,4,4
13541,apartment could be your dream when you can spe...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,82500000.0,8.25,41291.29,1998.0,3,4,2.0,6.0,22.0,2.0,1,1.0,1,1,2018.0,flat,8.0,Moderately Old,1,666.00,Karachi South,Unspecified,4,4
13803,3 bed drawing flat for sale in ciivl lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,30000000.0,3.00,21367.52,1404.0,3,3,1.0,NaN,NaN,1.0,1,1.0,1,0,2000.0,flat,26.0,Old,1,468.00,Karachi South,Unspecified,4,4
14437,prime location flat of 2500 square feet is ava...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,95000000.0,9.50,37969.62,2502.0,3,3,1.0,NaN,10.0,1.0,1,2.0,1,0,2025.0,flat,1.0,Relatively New,1,834.00,Karachi South,Unspecified,4,4
14488,flat for sale in civil lines civil lines is av...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,80000000.0,8.00,17028.52,4698.0,3,3,1.0,2.0,2.0,1.0,0,2.0,1,1,2020.0,flat,6.0,Moderately Old,1,1566.00,Karachi South,Unspecified,4,4
14608,apartment available for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,31545.74,2853.0,3,4,1.0,12.0,12.0,2.0,1,2.0,1,1,2024.0,flat,2.0,Relatively New,1,951.00,Karachi South,Unspecified,4,4
14636,apartment available for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35971.22,2502.0,3,4,1.0,NaN,NaN,2.0,0,2.0,1,1,2026.0,flat,0.0,New,1,834.00,Karachi South,Unspecified,4,4
15404,"flat in hsj icon 2 bed d,d for sale","hsj icon, civil lines",Civil Lines,Civil Lines_Unspecified,40000000.0,4.00,28129.40,1422.0,2,2,1.0,NaN,NaN,2.0,1,1.0,1,1,2015.0,flat,11.0,Old,1,711.00,Karachi South,Unspecified,4,4
15544,booking available 3 bedrooms lounge 1334 squar...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,38500000.0,3.85,28903.90,1332.0,3,3,1.0,NaN,20.0,1.0,1,1.0,1,0,2031.0,flat,-5.0,Under Construction,1,444.00,Karachi South,Unspecified,4,4
15803,parsa heaven civil line flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,61500000.0,6.15,26692.71,2304.0,3,3,1.0,1.0,NaN,1.0,1,1.0,0,0,NaN,flat,NaN,NaN,1,768.00,Karachi South,Unspecified,4,4
16312,find your ideal flat in civil lines under rs. ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,41841.00,2151.0,3,4,0.0,NaN,NaN,0.0,0,1.0,0,0,NaN,flat,NaN,NaN,0,717.00,Karachi South,Unspecified,4,4
16430,"hsj icon 4 bed d,d flat for sale","hsj icon, civil lines",Civil Lines,Civil Lines_Unspecified,75000000.0,7.50,25100.40,2988.0,4,4,1.0,NaN,46.0,1.0,1,2.0,1,1,2025.0,flat,1.0,Relatively New,1,747.00,Karachi South,Unspecified,4,4
16704,spacious 4 bedrooms park facing apartment for ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,75000000.0,7.50,29976.02,2502.0,4,4,1.0,7.0,11.0,2.0,1,2.0,1,1,2012.0,flat,14.0,Old,1,625.50,Karachi South,Unspecified,4,4
16729,biggest building brand new flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,32154.34,2799.0,3,4,1.0,NaN,52.0,2.0,1,2.0,1,0,2026.0,flat,0.0,New,1,933.00,Karachi South,Unspecified,4,4
17017,saars 3 | signature residences flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,44700000.0,4.47,29919.68,1494.0,3,3,1.0,NaN,49.0,1.0,1,1.0,1,0,2032.0,flat,-6.0,Under Construction,1,498.00,Karachi South,Unspecified,4,4
17212,gorgeous 2600 square feet flat for sale availa...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,82500000.0,8.25,31718.57,2601.0,4,4,0.0,NaN,NaN,0.0,0,2.0,0,0,NaN,flat,NaN,NaN,0,650.25,Karachi South,Unspecified,4,4
17214,4 bedrooms apartment for sale available in civ...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,82500000.0,8.25,34332.08,2403.0,4,5,1.0,NaN,NaN,2.0,1,1.0,1,0,2018.0,flat,8.0,Moderately Old,1,600.75,Karachi South,Unspecified,4,4
17696,3 beds lounge apartment available on sale at c...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,90000000.0,9.00,35335.69,2547.0,3,3,0.0,NaN,NaN,0.0,0,2.0,0,0,NaN,flat,NaN,NaN,0,849.00,Karachi South,Unspecified,4,4
17802,booking 4 bedrooms lounge 1839 square feet,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,52500000.0,5.25,28594.77,1836.0,4,4,2.0,NaN,NaN,0.0,0,1.0,0,0,NaN,house,NaN,NaN,1,459.00,Karachi South,Unspecified,4,4
18103,flat for sale in civil lines,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,48500000.0,4.85,24274.27,1998.0,3,4,1.0,NaN,6.0,1.0,1,1.0,1,0,2016.0,flat,10.0,Moderately Old,1,666.00,Karachi South,Unspecified,4,4
18616,saars 3 | signature residences,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,43000000.0,4.30,29861.11,1440.0,3,3,0.0,NaN,49.0,1.0,1,1.0,1,0,2032.0,flat,-6.0,Under Construction,1,480.00,Karachi South,Unspecified,4,4
19392,in civil lines 3000 square feet flat for sale,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,160000000.0,16.00,53386.72,2997.0,4,4,1.0,1.0,4.0,1.0,1,2.0,1,1,1985.0,flat,41.0,Old,1,749.25,Karachi South,Unspecified,4,4
19403,best investment & huge discount opportunity fl...,"civil lines, karachi",Civil Lines,Civil Lines_Unspecified,32000000.0,3.20,24024.02,1332.0,3,3,1.0,NaN,NaN,0.0,1,1.0,1,0,NaN,flat,NaN,NaN,0,444.00,Karachi South,Unspecified,4,4

In [49]:
df[df['location']=='Saddar']['address']

138                garden west, karachi
220                 saddar, saddar town
333                 saddar, saddar town
1050               saddar town, karachi
1471               garden west, karachi
2088                saddar, saddar town
2224               garden west, karachi
2854               saddar town, karachi
3003                saddar, saddar town
4043               garden west, karachi
4375         m. a. jinnah road, karachi
4406               garden west, karachi
4583               garden west, karachi
4699                saddar, saddar town
4707                saddar, saddar town
4734            chapal skymark, karachi
5064                saddar, saddar town
5198               saddar town, karachi
5234                saddar, saddar town
5608               garden west, karachi
5885            chapal skymark, karachi
6361               garden west, karachi
6370               saddar town, karachi
6899            chapal skymark, karachi
7291              mt khan road, karachi
7790                saddar, saddar town
7940     i. i. chundrigar road, karachi
7981     i. i. chundrigar road, karachi
9151               garden west, karachi
9262               garden west, karachi
9860                saddar, saddar town
9942            chapal skymark, karachi
9975               saddar town, karachi
10159               saddar, saddar town
10251               saddar, saddar town
10299            parsa city, gazdarabad
10319              garden west, karachi
10545              garden west, karachi
11126               saddar, saddar town
11350               saddar, saddar town
11880           chapal skymark, karachi
12580              garden west, karachi
12866              saddar town, karachi
13395              garden west, karachi
13465    i. i. chundrigar road, karachi
13769    i. i. chundrigar road, karachi
14638              garden west, karachi
14720              saddar town, karachi
15068              garden west, karachi
15306              garden west, karachi
15492              saddar town, karachi
16225             mt khan road, karachi
16300              garden west, karachi
16411              saddar town, karachi
16799              garden west, karachi
17472              saddar town, karachi
17583      ranchore line bazar, karachi
18006               saddar, saddar town
18038               burnes road, saddar
18107              saddar town, karachi
18338               saddar, saddar town
18807              saddar town, karachi
18975               saddar, saddar town
19089        m. a. jinnah road, karachi
19279    i. i. chundrigar road, karachi
19751           chapal skymark, karachi
19882              garden west, karachi
20003              saddar town, karachi
20314               saddar, saddar town
Name: address, dtype: object

In [50]:
x=df[(df['location']=='Saddar') & (df['address']=='saddar town, karachi')]['property_name']
x

1050     sawera icon a new landmark in the heart of kar...
2854     4 bed dd apartment for sale in chapal navinta ...
5198         well maintain flat near empress market saddar
6370         sawera icon a project by ok estate & builders
9975                    flat for sale @ taj complex saddar
12866        3 bed flat for sale near avari towers karachi
14720    affordable flat available for sale in saddar town
15492    4 bed dd apartment for sale in chapal navinta ...
16411    near karachi press club, 1800 square feet, 3 b...
17472                                          sawera mega
18107                         house for sale single storey
18807       flat for grabs in 1450 square feet saddar town
20003    sawera mega residency a project by ok estate &...
Name: property_name, dtype: object

In [51]:
import re

PROJECT_PATTERNS = [
    ('Sawera Mega Residency', r'sawera mega residency'),
    ('Sawera Mega', r'sawera mega(?!\s+residency)'),
    ('Sawera Icon', r'sawera icon'),
    ('Chapal Navinta', r'chapal navinta'),
    ('Taj Complex', r'taj complex'),
    ('Avari Towers', r'avari towers?'),
    ('Empress Market', r'empress market'),
    ('Karachi Press Club', r'karachi press club'),
    ('Saddar Town', r'saddar town'),
]

def extract_sub_location(text):
    if not isinstance(text, str):
        return None
    for name, pat in PROJECT_PATTERNS:
        if re.search(pat, text, re.IGNORECASE):
            return name
    return None


extracted = x.apply(extract_sub_location)


df.loc[extracted.index, 'sub_location'] = extracted.combine_first(df.loc[extracted.index, 'sub_location'])

In [52]:
df[df['location']=='Saddar']['address'].value_counts()

address
garden west, karachi              20
saddar, saddar town               18
saddar town, karachi              13
chapal skymark, karachi            6
i. i. chundrigar road, karachi     5
m. a. jinnah road, karachi         2
mt khan road, karachi              2
parsa city, gazdarabad             1
ranchore line bazar, karachi       1
burnes road, saddar                1
Name: count, dtype: int64

In [53]:
x.to_csv('xyz.csv')

In [54]:
df[(df['location']=='Saddar')]['sub_location'].value_counts()

sub_location
Saddar_Unspecified       57
Sawera Icon               2
Chapal Navinta            2
Saddar Town               2
Empress Market            1
Taj Complex               1
Avari Towers              1
Karachi Press Club        1
Sawera Mega               1
Sawera Mega Residency     1
Name: count, dtype: int64

In [ ]:
# Find unspecified Saddar rows, excluding the generic Saddar Town address.
mask = (
    (df['location'] == 'Saddar') & 
    (df['sub_location'] == 'Saddar_Unspecified') & 
    (df['address'] != 'saddar town, karachi')
)

# Use the address as the sub-location when it gives us more detail.
df.loc[mask, 'sub_location'] = df.loc[mask, 'address']

# Review the updated Saddar sub-location counts.
print(df[df['location'] == 'Saddar']['sub_location'].value_counts())

sub_location
garden west, karachi              20
saddar, saddar town               18
chapal skymark, karachi            6
i. i. chundrigar road, karachi     5
Sawera Icon                        2
Chapal Navinta                     2
m. a. jinnah road, karachi         2
mt khan road, karachi              2
Saddar Town                        2
Sawera Mega                        1
Saddar_Unspecified                 1
burnes road, saddar                1
ranchore line bazar, karachi       1
Taj Complex                        1
Karachi Press Club                 1
Avari Towers                       1
parsa city, gazdarabad             1
Empress Market                     1
Sawera Mega Residency              1
Name: count, dtype: int64

In [ ]:
# Group the detailed Saddar names into a smaller set of useful areas.
mapping_dict = {
    # Central Saddar market and nearby roads.
    'saddar, saddar town': 'Saddar Core',
    'Saddar_Unspecified': 'Saddar Core',
    'Empress Market': 'Saddar Core',
    'burnes road, saddar': 'Saddar Core',
    'm. a. jinnah road, karachi': 'Saddar Core',
    'i. i. chundrigar road, karachi': 'Saddar Core',
    'mt khan road, karachi': 'Saddar Core',
    'ranchore line bazar, karachi': 'Saddar Core',
    'Karachi Press Club': 'Saddar Core',
    'Taj Complex': 'Saddar Core',
    
    # Civil Lines and its recognizable landmarks.
    'chapal skymark, karachi': 'Civil Lines',
    'Chapal Navinta': 'Civil Lines',
    'Avari Towers': 'Civil Lines',
    'Civil Lines': 'Civil Lines',
    
    # Garden West and the nearby Sawera projects.
    'garden west, karachi': 'Garden West',
    
    # Other named areas that belong to Garden West.
    'Sawera Icon': 'Garden West',
    'Sawera Mega': 'Garden West',
    'Sawera Mega Residency': 'Garden West',
}

# Apply the mapping only to records whose parent location is Saddar.
mask = (df['location'] == 'Saddar') & (df['sub_location'].isin(mapping_dict.keys()))
df.loc[mask, 'sub_location'] = df.loc[mask, 'sub_location'].map(mapping_dict)

# Review the simplified Saddar sub-location counts.
print(df[df['location'] == 'Saddar']['sub_location'].value_counts())

sub_location
Saddar Core               33
Garden West               24
Civil Lines                9
Saddar Town                2
parsa city, gazdarabad     1
Name: count, dtype: int64

In [ ]:
# Remove the two entries that do not belong in the Saddar group.
mask_to_drop = (df['location'] == 'Saddar') & (df['sub_location'].isin(['Saddar Town', 'parsa city, gazdarabad']))
df = df[~mask_to_drop]

# Confirm the remaining Saddar sub-location counts.
print(df[df['location'] == 'Saddar']['sub_location'].value_counts())

sub_location
Saddar Core    33
Garden West    24
Civil Lines     9
Name: count, dtype: int64

In [ ]:
# Fold Civil Lines into the Saddar parent location.
mask = df['location'] == 'Civil Lines'
df.loc[mask, 'location'] = 'Saddar'

# Preserve Civil Lines as the more specific sub-location.
df.loc[mask, 'sub_location'] = 'Civil Lines'

# Check the resulting sub-location counts for Saddar.
print(df[df['location'] == 'Saddar']['sub_location'].value_counts())

sub_location
Civil Lines    88
Saddar Core    33
Garden West    24
Name: count, dtype: int64

In [59]:
df.loc[df['location'] == 'Saddar', 'location'] = 'Saddar Town'
print(df['location'].value_counts())

location
DHA Defence             4208
Scheme 33               3053
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
Jamshed Town            1073
North Nazimabad         1020
Malir                    922
Clifton                  815
Gadap                    700
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            152
Korangi                  148
Saddar Town              145
Shah Faisal              138
Karsaz                   124
Nazimabad                 75
Bin Qasim Town            39
Shahra-e-Faisal           34
Northern Bypass           26
Name: count, dtype: int64

In [60]:
df[df['location']=='Bin Qasim Town']

,property_name,address,location,sub_location,price,price_crore,price_per_sqft,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type,property_age,age_category,parking_score,area_per_bedroom,district,sub_location_type,location_score,sub_location_score
813,2 bed lounge apartment for sale in mateen comp...,"saudabad, malir",Bin Qasim Town,Mateen Complex,3500000.0,0.350,5804.31,603.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,301.5,Malir,Residential Project,1,1
1031,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,1700000.0,0.170,3777.78,450.0,1,1,1.0,NaN,4.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
1554,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,1800000.0,0.180,6060.61,297.0,1,1,1.0,NaN,4.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,297.0,Malir,Residential Project,1,1
2451,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,2050000.0,0.205,4555.56,450.0,1,1,1.0,NaN,NaN,1.0,0,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
2494,2 rooms apartment for sale | ready to move | o...,"shah faisal town, karachi",Bin Qasim Town,Mateen Complex,3000000.0,0.300,6666.67,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
2939,2 bed lounge apartment for sale in mateen comp...,"korangi, karachi",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
3371,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,1700000.0,0.170,3777.78,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
3942,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
4037,3 bed dd flat for sale in mateen complex | mai...,"shah latif town, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,3,3,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,282.0,Malir,Residential Project,1,1
4082,2 bed lounge apartment for sale in mateen comp...,"drigh colony, shah faisal town",Bin Qasim Town,Mateen Complex,3800000.0,0.380,4491.73,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
4479,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,2300000.0,0.230,5111.11,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
4987,2 bed lounge apartment for sale in mateen comp...,"malir, karachi",Bin Qasim Town,Mateen Complex,3600000.0,0.360,5555.56,648.0,2,2,1.0,NaN,4.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,324.0,Malir,Residential Project,1,1
5287,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3600000.0,0.360,5797.10,621.0,2,2,1.0,NaN,4.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,310.5,Malir,Residential Project,1,1
5369,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
6429,ready to move 1 bed lounge apartment for sale ...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,1800000.0,0.180,4000.00,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
6688,bank loan not applicable 2 bed dd apartment fo...,"shah faisal town, karachi",Bin Qasim Town,Mateen Complex,4500000.0,0.450,5319.15,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
8341,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,2100000.0,0.210,4666.67,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
9261,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3600000.0,0.360,4255.32,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
9264,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4369.54,801.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,400.5,Malir,Residential Project,1,1
9390,2 rooms apartment for sale | ready to move | o...,"shah faisal town, karachi",Bin Qasim Town,Mateen Complex,1900000.0,0.190,4222.22,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
9703,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4369.54,801.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,400.5,Malir,Residential Project,1,1
10293,ready to move 1 bed lounge apartment for sale ...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,2000000.0,0.200,4444.44,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
10721,1 bed lounge apartment for sale | ready to mov...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,2000000.0,0.200,5698.01,351.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,351.0,Malir,Residential Project,1,1
10797,3 bed dd apartment for sale in mateen complex ...,"gulistan-e-jauhar, karachi",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
12024,3 bed dd apartment for sale in mateen complex ...,"gulistan-e-jauhar, karachi",Bin Qasim Town,Mateen Complex,4600000.0,0.460,5437.35,846.0,3,3,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,282.0,Malir,Residential Project,1,1
12267,2 bed lounge apartment for sale in mateen comp...,"quaidabad, bin qasim town",Bin Qasim Town,Mateen Complex,4850000.0,0.485,6054.93,801.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,400.5,Malir,Residential Project,1,1
12755,2 bed lounge apartment for sale in mateen comp...,"mateen complex, bin qasim town",Bin Qasim Town,Mateen Complex,3700000.0,0.370,4373.52,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
14234,3 bed dd for sale in mateen complex main natio...,"shah latif town, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
14587,1 bed lounge apartment for sale | ready to mov...,"malir halt, malir",Bin Qasim Town,Mateen Complex,2000000.0,0.200,4444.44,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
14847,3 bed dd for sale in mateen complex main natio...,"shah latif town, bin qasim town",Bin Qasim Town,Mateen Complex,3650000.0,0.365,4314.42,846.0,3,3,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,282.0,Malir,Residential Project,1,1
15043,1 bed lounge apartment for sale | ready to mov...,"malir halt, malir",Bin Qasim Town,Mateen Complex,2050000.0,0.205,4555.56,450.0,1,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,450.0,Malir,Residential Project,1,1
15058,2 bed lounge apartment for sale in mateen comp...,"malir, karachi",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,14.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
15457,2 rooms apartment for sale | ready to move | o...,"saudabad, malir",Bin Qasim Town,Mateen Complex,2000000.0,0.200,4444.44,450.0,2,1,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,225.0,Malir,Residential Project,1,1
16347,2 bed lounge apartment for sale in mateen comp...,"saudabad, malir",Bin Qasim Town,Mateen Complex,3900000.0,0.390,3117.51,1251.0,2,2,1.0,NaN,5.0,1.0,1,1.0,1,1,2022.0,flat,4.0,Relatively New,1,625.5,Malir,Residential Project,1,1
17364,2-bed apartment for sale in mateen complex pri...,"gulshan-e-hadeed, bin qasim town",Bin Qasim Town,Mateen Complex,15500000.0,1.550,19350.81,801.0,2,2,0.0,NaN,NaN,0.0,0,0.0,0,0,NaN,flat,NaN,NaN,0,400.5,Malir,Residential Project,1,1
18161,2 bed lounge apartment for sale in mateen comp...,"malir, karachi",Bin Qasim Town,Mateen Complex,3900000.0,0.390,4609.93,846.0,2,2,1.0,NaN,14.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
19351,3 bed dd apartment for sale in mateen complex ...,"shah faisal town, karachi",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4137.12,846.0,2,2,1.0,NaN,NaN,1.0,0,0.0,1,1,2022.0,flat,4.0,Relatively New,1,423.0,Malir,Residential Project,1,1
19400,ready to move 1 bed lounge apartment for sale ...,"malir halt, malir",Bin Qasim Town,Mateen Complex,2000000.0,0.200,5698.01,351.0,1,1,1.0,NaN,4.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,351.0,Malir,Residential Project,1,1
19612,2 bed lounge apartment for sale in mateen comp...,"quaidabad, bin qasim town",Bin Qasim Town,Mateen Complex,3500000.0,0.350,4369.54,801.0,2,2,1.0,NaN,5.0,1.0,1,0.0,1,1,2022.0,flat,4.0,Relatively New,1,400.5,Malir,Residential Project,1,1

In [ ]:
# Remove Bin Qasim Town because it is outside the locations used here.
df = df[df['location'] != 'Bin Qasim Town']

# Check the location counts after removing it.
print(df['location'].value_counts())

location
DHA Defence             4208
Scheme 33               3053
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
Jamshed Town            1073
North Nazimabad         1020
Malir                    922
Clifton                  815
Gadap                    700
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            152
Korangi                  148
Saddar Town              145
Shah Faisal              138
Karsaz                   124
Nazimabad                 75
Shahra-e-Faisal           34
Northern Bypass           26
Name: count, dtype: int64

In [62]:
df = df[~df['location'].isin(['Shahra-e-Faisal', 'Northern Bypass'])]
print(df['location'].value_counts())

location
DHA Defence             4208
Scheme 33               3053
Gulshan-e-Iqbal Town    2205
Gulistan-e-Jauhar       1748
Bahria Town             1239
Malir Cantt             1135
Jamshed Town            1073
North Nazimabad         1020
Malir                    922
Clifton                  815
Gadap                    700
Naya Nazimabad           627
Federal B Area           425
North Karachi            379
Super Highway            152
Korangi                  148
Saddar Town              145
Shah Faisal              138
Karsaz                   124
Nazimabad                 75
Name: count, dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20331 entries, 0 to 20457
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20331 non-null  object
 1   address             20331 non-null  object
 2   location            20331 non-null  object
 3   sub_location        20331 non-null  object
 4   price               20331 non-null  float64
 5   price_crore         20331 non-null  float64
 6   price_per_sqft      20331 non-null  float64
 7   area                20331 non-null  float64
 8   bedrooms            20331 non-null  int64
 9   bathrooms           20331 non-null  int64
 10  kitchen             20331 non-null  float64
 11  floor               3982 non-null   float64
 12  total_floors        9517 non-null   float64
 13  parking             20331 non-null  float64
 14  elevator            20331 non-null  int64
 15  servant_quarters    20331 non-null  float64
 16  electricity_backup  20331 non-null  int64
 17  furnished           20331 non-null  int64
 18  completion_year     10758 non-null  float64
 19  property_type       20331 non-null  object
 20  property_age        10758 non-null  float64
 21  age_category        10758 non-null  object
 22  parking_score       20331 non-null  int64
 23  area_per_bedroom    20331 non-null  float64
 24  district            20331 non-null  object
 25  sub_location_type   20331 non-null  object
 26  location_score      20331 non-null  int64
 27  sub_location_score  20331 non-null  int64
dtypes: float64(12), int64(8), object(8)
memory usage: 4.5+ MB

In [64]:
df['sub_location'].value_counts()

sub_location
Phase 8                                     2047
Phase 6                                      886
Askari 5                                     499
Askari 6                                     490
Falcon Complex New Malir                     449
Phase 5                                      449
Gulshan-E-Maymar                             442
Gulshan-e-Iqbal Block 10A                    426
Sector 35-A                                  305
Scheme 33_Unspecified                        302
Naya Nazimabad_Unspecified                   301
Phase 7                                      286
Pechs                                        268
Sector 47                                    260
Sector 40                                    251
Falaknaz                                     221
Surjani Town                                 209
Gulistan-e-Jauhar Block 15                   193
Gulshan-e-Iqbal Town_Unspecified             188
Shaheed Millat Road                          185
North Nazimabad Block F                      179
Saadi Garden                                 169
Clifton Block 2                              161
Phase 4                                      156
Gulistan-e-Jauhar Block 14                   150
Punjabi Saudagar Society                     147
Gulshan-e-Iqbal Block 1                      144
Sector 29                                    143
Phase 7 Extension                            141
Gulistan-e-Jauhar Block 13                   135
Gulistan-e-Jauhar Block 18                   127
Sector 34-A                                  125
Gulistan-e-Jauhar Block 7                    125
Navy Housing Scheme Karsaz                   124
Gulistan-e-Jauhar Block 3A                   123
Bath Island                                  123
North Nazimabad Block H                      122
Khalid Bin Walid Road                        121
North Nazimabad Block L                      117
Bahadurabad                                  116
Sector 18-A                                  114
Sector 17-A                                  114
North Nazimabad Block N                      113
Sector 16-A                                  109
Gulshan-e-Iqbal Block 2                      106
Gulshan-e-Iqbal Block 4                      105
Gulistan-e-Jauhar Block 12                   105
Sector 44                                    105
Gulistan-e-Jauhar Block 17                   104
Gulistan-e-Jauhar_Unspecified                100
Allahwala Town                                99
Model Colony                                  98
Sector 36-A                                   97
Gulshan-e-Iqbal Block 17                      97
Malir Cantt_Unspecified                       95
Buffer Zone                                   95
Gulistan-e-Jauhar Block 2                     94
Bahria Sports City                            94
Sector 19-A                                   93
Naya Nazimabad Block A                        93
Clifton Block 9                               92
Precinct 2                                    92
Sector 15-A                                   91
Naya Nazimabad Block C                        91
Gulshan-e-Iqbal Block 7                       90
North Karachi Sector 11                       90
Clifton Block 8                               88
Clifton Block 1                               88
Civil Lines                                   88
Precinct 12                                   85
Kda Scheme 1                                  84
Malir Link To Super Highway                   82
North Nazimabad Block B                       81
North Nazimabad_Unspecified                   80
Gulshan-e-Iqbal Block 5                       77
Precinct 8                                    75
Bahria Apartments                             74
Gulistan-e-Jauhar Block 16                    74
Gulshan-e-Iqbal Block 13D2                    74
Gulistan-e-Jauhar Block 19                    73
Private High-Rises                            70
Saima Villas                                  69
Phase 2 Extension                             68
Naya Nazimabad Block D                        66
Gulshan-e-Iqbal Block 13D1                    65
Airport                                       65
Federal B Area Block 10                       65
Phase 1                                       64
Jamshed Road                                  60
Precinct 11A                                  58
Gulistan-e-Jauhar Block 3                     58
Federal B Area_Unspecified                    58
Gulshan-e-Iqbal Block 6                       58
Meerut Society                                57
Dhoraji Colony                                56
Bahria Paradise                               56
Precinct 1                                    54
Precinct 9                                    54
DHA City                                      54
Gulshan-e-Iqbal Block 13D                     54
Bahria Town_Unspecified                       54
Precinct 31                                   54
Naya Nazimabad Block B                        53
Clifton_Unspecified                           52
Phase 2                                       52
Saadi Road                                    52
North Nazimabad Block M                       52
Gulshan-e-Iqbal Block 13C                     52
Clifton Block 4                               51
Federal B Area Block 12                       50
Precinct 10A                                  50
North Karachi Sector 5                        49
Memon Goth                                    49
Precinct 11B                                  48
Sector 43-A                                   48
Sector 51-A                                   47
Defence View                                  47
Bahria Heights                                47
Sharfabad                                     46
North Karachi_Unspecified                     46
Precinct 6                                    45
North Nazimabad Block A                       45
North Nazimabad Block D                       44
Shadman                                       43
Smchs - Sindhi Muslim Society                 43
Frere Town                                    43
Precinct 10B                                  42
Federal B Area Block 21                       42
North Nazimabad Block K                       42
Gohar Green City Cluster                      41
Karachi Administration Employees Society      41
Dohs Phase 1                                  40
Gulistan-e-Jauhar Block 10                    40
Clifton Block 7                               40
Gulistan-e-Jauhar Block 1                     40
Precinct 27                                   40
Gulshan-e-Iqbal Block 3                       40
Gulshan-e-Iqbal Block 13A                     39
Federal B Area Block 13                       39
Precinct 4                                    37
Saima Projects                                37
Sector 25-B                                   36
North Karachi Sector 7                        36
Gulistan-e-Jauhar Block 4                     35
Tariq Road                                    35
North Nazimabad Block J                       35
Malir_Unspecified                             35
North Nazimabad Block I                       34
Clifton Block 5                               34
Gulistan-e-Jauhar Block 20                    33
Amir Khusro                                   33
Saima Luxury Belt                             33
Saddar Core                                   33
Jamshed Town_Unspecified                      32
Gulshan-e-Iqbal Block 13D3                    32
Askari 4                                      32
Tipu Sultan Road                              32
Precinct 19                                   32
Garden East                                   31
Gulshan-e-Iqbal Block 11                      31
Amil Colony                                   30
Precinct 16                                   30
Sector 24-A                                   30
Gulistan-e-Jauhar Block 11                    29
Sector 42-A                                   29
Federal B Area Block 11                       28
Sector 52-A                                   28
Sector 38-A                                   26
Gulistan-e-Jauhar Block 5                     26
DHA Defence_Unspecified                       26
Shamsi / Al-Falah Belt                        26
Sector 18-C                                   25
North Karachi Sector 9                        24
Green Town / Rafah-E-Aam Belt                 24
Garden West                                   24
Gulshan-e-Iqbal Block 13B                     24
Nazimabad 4                                   24
Sector 30                                     23
Naya Nazimabad Block M                        23
Super Highway_Unspecified                     23
Gulshan-e-Iqbal Block 16                      23
Gulshan-e-Iqbal Block 10                      23
National Stadium Colony                       22
Gulistan-e-Jauhar Block 16A                   22
Sector 20-A                                   22
Nazimabad 3                                   21
North Nazimabad Block G                       21
Phase 5 Extension                             21
Gizri                                         21
Soldier Bazar                                 20
Parsi Colony                                  20
Sector 24-B                                   20
Federal B Area Block 9                        19
Federal B Area Block 14                       19
Precinct 17                                   19
Sector 17-B                                   19
Korangi Industrial Area                       19
Gulshan-e-Iqbal Block 19                      18
Mehmoodabad                                   18
Federal B Area Block 8                        18
Sector 22-A                                   18
Cosmopolitan Society                          17
Federal B Area Block 19                       17
Gulshan-e-Iqbal Block 9                       17
Gulshan-e-Usman Housing Society               17
Precinct 15                                   17
Mohammad Ali Society                          17
Gulshan-e-Iqbal Block 14                      16
Kda Employees Society                         16
Golden Town                                   16
Adamjee Nagar                                 16
North Karachi Sector 10                       16
Jamia Millia Road                             16
Gulistan-e-Jauhar Block 9                     15
Qayyumabad                                    14
Shah Faisal_Unspecified                       14
Federal B Area Block 16                       14
North Karachi Sector 8                        14
Shahra-E-Qaideen                              14
Falcon Complex Faisal                         14
Cp Barar Society, Gulshan-E-Iqbal Town        13
Nazimabad 1                                   13
Gulshan-e-Iqbal Block 21                      13
Federal B Area Block 15                       13
Sector 48-A                                   13
Phase 8 Extension                             12
North Nazimabad Block C                       12
Muslimabad Society                            12
Gulshan-e-Iqbal Block 13                      12
Federal B Area Block 6                        12
Dohs Phase 2                                  11
Malir Town Residency                          11
Clifton Block 3                               11
Federal B Area Block 7                        11
Clifton Block 6                               11
Kda Scheme 1 Extension                        11
Sector 45-A                                   10
Federal B Area Block 20                       10
Shahrah-E-Pakistan                            10
Nazimabad 5                                    9
New Karachi                                    9
Nazimabad 2                                    8
Safoora Goth                                   8
Precinct 7                                     7
Gulistan-e-Jauhar Block 8                      7
Oasis Park Residencia                          6
Precinct 18                                    5
Name: count, dtype: int64

In [65]:
df['sub_location_type'].unique()

array(['Subdivision', 'Housing Society', 'Military Housing',
       'Unspecified', 'Neighbourhood', 'Residential Project', 'Road'],
      dtype=object)

In [ ]:
sub_location_type_mapping = {

    # SUBDIVISION
    # Unit / Sector / Phase / Block / Precinct


    # DHA / Phases
    "Phase 1": "Subdivision",
    "Phase 2": "Subdivision",
    "Phase 2 Extension": "Subdivision",
    "Phase 4": "Subdivision",
    "Phase 5": "Subdivision",
    "Phase 5 Extension": "Subdivision",
    "Phase 6": "Subdivision",
    "Phase 7": "Subdivision",
    "Phase 7 Extension": "Subdivision",
    "Phase 8": "Subdivision",
    "Phase 8 Extension": "Subdivision",

    # Sectors
    "Sector 15-A": "Subdivision",
    "Sector 16-A": "Subdivision",
    "Sector 17-A": "Subdivision",
    "Sector 17-B": "Subdivision",
    "Sector 18-A": "Subdivision",
    "Sector 18-C": "Subdivision",
    "Sector 19-A": "Subdivision",
    "Sector 20-A": "Subdivision",
    "Sector 22-A": "Subdivision",
    "Sector 24-A": "Subdivision",
    "Sector 24-B": "Subdivision",
    "Sector 25-B": "Subdivision",
    "Sector 29": "Subdivision",
    "Sector 30": "Subdivision",
    "Sector 34-A": "Subdivision",
    "Sector 35-A": "Subdivision",
    "Sector 36-A": "Subdivision",
    "Sector 38-A": "Subdivision",
    "Sector 40": "Subdivision",
    "Sector 42-A": "Subdivision",
    "Sector 43-A": "Subdivision",
    "Sector 44": "Subdivision",
    "Sector 45-A": "Subdivision",
    "Sector 47": "Subdivision",
    "Sector 48-A": "Subdivision",
    "Sector 51-A": "Subdivision",
    "Sector 52-A": "Subdivision",

    # Gulshan-e-Iqbal Blocks
    "Gulshan-e-Iqbal Block 1": "Subdivision",
    "Gulshan-e-Iqbal Block 2": "Subdivision",
    "Gulshan-e-Iqbal Block 3": "Subdivision",
    "Gulshan-e-Iqbal Block 4": "Subdivision",
    "Gulshan-e-Iqbal Block 5": "Subdivision",
    "Gulshan-e-Iqbal Block 6": "Subdivision",
    "Gulshan-e-Iqbal Block 7": "Subdivision",
    "Gulshan-e-Iqbal Block 9": "Subdivision",
    "Gulshan-e-Iqbal Block 10": "Subdivision",
    "Gulshan-e-Iqbal Block 10A": "Subdivision",
    "Gulshan-e-Iqbal Block 11": "Subdivision",
    "Gulshan-e-Iqbal Block 13": "Subdivision",
    "Gulshan-e-Iqbal Block 13A": "Subdivision",
    "Gulshan-e-Iqbal Block 13B": "Subdivision",
    "Gulshan-e-Iqbal Block 13C": "Subdivision",
    "Gulshan-e-Iqbal Block 13D": "Subdivision",
    "Gulshan-e-Iqbal Block 13D1": "Subdivision",
    "Gulshan-e-Iqbal Block 13D2": "Subdivision",
    "Gulshan-e-Iqbal Block 13D3": "Subdivision",
    "Gulshan-e-Iqbal Block 14": "Subdivision",
    "Gulshan-e-Iqbal Block 16": "Subdivision",
    "Gulshan-e-Iqbal Block 17": "Subdivision",
    "Gulshan-e-Iqbal Block 19": "Subdivision",
    "Gulshan-e-Iqbal Block 21": "Subdivision",

    # Gulistan-e-Jauhar Blocks
    "Gulistan-e-Jauhar Block 1": "Subdivision",
    "Gulistan-e-Jauhar Block 2": "Subdivision",
    "Gulistan-e-Jauhar Block 3": "Subdivision",
    "Gulistan-e-Jauhar Block 3A": "Subdivision",
    "Gulistan-e-Jauhar Block 4": "Subdivision",
    "Gulistan-e-Jauhar Block 5": "Subdivision",
    "Gulistan-e-Jauhar Block 7": "Subdivision",
    "Gulistan-e-Jauhar Block 8": "Subdivision",
    "Gulistan-e-Jauhar Block 9": "Subdivision",
    "Gulistan-e-Jauhar Block 10": "Subdivision",
    "Gulistan-e-Jauhar Block 11": "Subdivision",
    "Gulistan-e-Jauhar Block 12": "Subdivision",
    "Gulistan-e-Jauhar Block 13": "Subdivision",
    "Gulistan-e-Jauhar Block 14": "Subdivision",
    "Gulistan-e-Jauhar Block 15": "Subdivision",
    "Gulistan-e-Jauhar Block 16": "Subdivision",
    "Gulistan-e-Jauhar Block 16A": "Subdivision",
    "Gulistan-e-Jauhar Block 17": "Subdivision",
    "Gulistan-e-Jauhar Block 18": "Subdivision",
    "Gulistan-e-Jauhar Block 19": "Subdivision",
    "Gulistan-e-Jauhar Block 20": "Subdivision",

    # North Nazimabad Blocks
    "North Nazimabad Block A": "Subdivision",
    "North Nazimabad Block B": "Subdivision",
    "North Nazimabad Block C": "Subdivision",
    "North Nazimabad Block D": "Subdivision",
    "North Nazimabad Block F": "Subdivision",
    "North Nazimabad Block G": "Subdivision",
    "North Nazimabad Block H": "Subdivision",
    "North Nazimabad Block I": "Subdivision",
    "North Nazimabad Block J": "Subdivision",
    "North Nazimabad Block K": "Subdivision",
    "North Nazimabad Block L": "Subdivision",
    "North Nazimabad Block M": "Subdivision",
    "North Nazimabad Block N": "Subdivision",

    # Federal B Area Blocks
    "Federal B Area Block 6": "Subdivision",
    "Federal B Area Block 7": "Subdivision",
    "Federal B Area Block 8": "Subdivision",
    "Federal B Area Block 9": "Subdivision",
    "Federal B Area Block 10": "Subdivision",
    "Federal B Area Block 11": "Subdivision",
    "Federal B Area Block 12": "Subdivision",
    "Federal B Area Block 13": "Subdivision",
    "Federal B Area Block 14": "Subdivision",
    "Federal B Area Block 15": "Subdivision",
    "Federal B Area Block 16": "Subdivision",
    "Federal B Area Block 19": "Subdivision",
    "Federal B Area Block 20": "Subdivision",
    "Federal B Area Block 21": "Subdivision",

    # Clifton Blocks
    "Clifton Block 1": "Subdivision",
    "Clifton Block 2": "Subdivision",
    "Clifton Block 3": "Subdivision",
    "Clifton Block 4": "Subdivision",
    "Clifton Block 5": "Subdivision",
    "Clifton Block 6": "Subdivision",
    "Clifton Block 7": "Subdivision",
    "Clifton Block 8": "Subdivision",
    "Clifton Block 9": "Subdivision",

    # North Karachi Sectors
    "North Karachi Sector 5": "Subdivision",
    "North Karachi Sector 5A3": "Subdivision",
    "North Karachi Sector 5K": "Subdivision",
    "North Karachi Sector 7": "Subdivision",
    "North Karachi Sector 8": "Subdivision",
    "North Karachi Sector 9": "Subdivision",
    "North Karachi Sector 10": "Subdivision",
    "North Karachi Sector 11": "Subdivision",
    "North Karachi Sector 11A": "Subdivision",
    "North Karachi Sector 11-C/1": "Subdivision",

    # Nazimabad
    "Nazimabad 1": "Subdivision",
    "Nazimabad 2": "Subdivision",
    "Nazimabad 3": "Subdivision",
    "Nazimabad 4": "Subdivision",
    "Nazimabad 5": "Subdivision",

    # Bahria Precincts
    "Precinct 1": "Subdivision",
    "Precinct 2": "Subdivision",
    "Precinct 4": "Subdivision",
    "Precinct 6": "Subdivision",
    "Precinct 7": "Subdivision",
    "Precinct 8": "Subdivision",
    "Precinct 9": "Subdivision",
    "Precinct 10A": "Subdivision",
    "Precinct 10B": "Subdivision",
    "Precinct 11A": "Subdivision",
    "Precinct 11B": "Subdivision",
    "Precinct 12": "Subdivision",
    "Precinct 15": "Subdivision",
    "Precinct 16": "Subdivision",
    "Precinct 17": "Subdivision",
    "Precinct 18": "Subdivision",
    "Precinct 19": "Subdivision",
    "Precinct 27": "Subdivision",
    "Precinct 31": "Subdivision",

    # Other actual subdivisions
    "Kda Scheme 1": "Subdivision",
    "Kda Scheme 1 Extension": "Subdivision",




    # MILITARY HOUSING


    "Askari 4": "Military Housing",
    "Askari 5": "Military Housing",
    "Askari 6": "Military Housing",
    "Navy Housing Scheme Karsaz": "Military Housing",
    "Malir Cantt_Unspecified": "Military Housing",
    "Dohs Phase 1": "Military Housing",
    "Dohs Phase 2": "Military Housing",
    "Falcon Complex New Malir": "Military Housing",
    "Falcon Complex Faisal": "Military Housing",

    # ROAD
    

    "Shaheed Millat Road": "Road",
    "Khalid Bin Walid Road": "Road",
    "Jamshed Road": "Road",
    "Tariq Road": "Road",
    "Tipu Sultan Road": "Road",
    "Jamia Millia Road": "Road",
    "Saadi Road": "Road",
    "Shahra-E-Qaideen": "Road",
    "Shahrah-E-Pakistan": "Road",
    "Malir Link To Super Highway": "Road",


    # SOCIETY

    "Pechs": "Society",
    "Punjabi Saudagar Society": "Society",
    "Meerut Society": "Society",
    "Smchs - Sindhi Muslim Society": "Society",
    "Karachi Administration Employees Society": "Society",
    "Cosmopolitan Society": "Society",
    "Gulshan-e-Usman Housing Society": "Society",
    "Mohammad Ali Society": "Society",
    "Muslimabad Society": "Society",
    "Kda Employees Society": "Society",
    "Cp Barar Society, Gulshan-E-Iqbal Town": "Society",
    "Dhoraji Colony": "Society",
    "Saadi Garden": "Society",
    "Bath Island": "Society",
    "Bahadurabad": "Society",


    # RESIDENTIAL PROJECT


    "Falaknaz": "Residential Project",
    "Bahria Sports City": "Residential Project",
    "Bahria Apartments": "Residential Project",
    "Bahria Paradise": "Residential Project",
    "Bahria Heights": "Residential Project",
    "Bahria Town_Unspecified": "Unspecified",
    "Saima Villas": "Residential Project",
    "Saima Projects": "Residential Project",
    "Saima Luxury Belt": "Residential Project",
    "Private High-Rises": "Residential Project",
    "Gohar Green City Cluster": "Residential Project",
    "Oasis Park Residencia": "Residential Project",
    "Malir Town Residency": "Residential Project",
    "DHA City": "Residential Project",


    # NEIGHBOURHOOD
    
    # Small named localities / areas within Karachi 

    "Gulshan-E-Maymar": "Neighbourhood",
    "Surjani Town": "Neighbourhood",
    "Gulshan-e-Iqbal Town_Unspecified": "Unspecified",
    "Gulistan-e-Jauhar_Unspecified": "Unspecified",
    "Gulshan-e-Iqbal Town_Unspecified": "Unspecified",

    "Allahwala Town": "Neighbourhood",
    "Model Colony": "Neighbourhood",
    "Buffer Zone": "Neighbourhood",
    "New Karachi": "Neighbourhood",
    "Airport": "Neighbourhood",
    "Civil Lines": "Neighbourhood",
    "Frere Town": "Neighbourhood",
    "Garden East": "Neighbourhood",
    "Garden West": "Neighbourhood",
    "Gizri": "Neighbourhood",
    "Amir Khusro": "Neighbourhood",
    "Shadman": "Neighbourhood",
    "Mehmoodabad": "Neighbourhood",
    "Soldier Bazar": "Neighbourhood",
    "National Stadium Colony": "Neighbourhood",
    "Parsi Colony": "Neighbourhood",
    "Golden Town": "Neighbourhood",
    "Amil Colony": "Neighbourhood",
    "Qayyumabad": "Neighbourhood",
    "Safoora Goth": "Neighbourhood",
    "Memon Goth": "Neighbourhood",
    "Korangi Industrial Area": "Neighbourhood",
    "Shamsi / Al-Falah Belt": "Neighbourhood",
    "Green Town / Rafah-E-Aam Belt": "Neighbourhood",
    "Sharfabad": "Neighbourhood",
    "Dhoraji Colony": "Society",
    "Saadi Garden": "Society",
    "Bath Island": "Neighbourhood",
    "Bahadurabad": "Neighbourhood",
    "Kda Scheme 1": "Subdivision",
    "Jamshed Town_Unspecified": "Unspecified",
    "Malir": "Neighbourhood",
    "Clifton_Unspecified": "Unspecified",
    "North Nazimabad_Unspecified": "Unspecified",
    "North Karachi_Unspecified": "Unspecified",
    "Federal B Area_Unspecified": "Unspecified",
    "DHA Defence_Unspecified": "Unspecified",
    "Malir_Unspecified": "Unspecified",
    "Shah Faisal_Unspecified": "Unspecified",
    "Super Highway_Unspecified": "Unspecified",
    "Naya Nazimabad_Unspecified": "Unspecified",
    "Scheme 33_Unspecified": "Unspecified",
    "Gulistan-e-Jauhar_Unspecified": "Unspecified",

    # UNSPECIFIED
    
    "Scheme 33_Unspecified": "Unspecified",
    "Naya Nazimabad_Unspecified": "Unspecified",
    "Gulshan-e-Iqbal Town_Unspecified": "Unspecified",
    "Gulistan-e-Jauhar_Unspecified": "Unspecified",
    "North Nazimabad_Unspecified": "Unspecified",
    "North Karachi_Unspecified": "Unspecified",
    "Clifton_Unspecified": "Unspecified",
    "Federal B Area_Unspecified": "Unspecified",
    "DHA Defence_Unspecified": "Unspecified",
    "Malir_Unspecified": "Unspecified",
    "Shah Faisal_Unspecified": "Unspecified",
    "Super Highway_Unspecified": "Unspecified",
    "Jamshed Town_Unspecified": "Unspecified",

    "Naya Nazimabad Block A": "Subdivision",
    "Naya Nazimabad Block B": "Subdivision",
    "Naya Nazimabad Block C": "Subdivision",
    "Naya Nazimabad Block D": "Subdivision",
    "Naya Nazimabad Block M": "Subdivision",

    "Defence View": "Neighbourhood",
    "Saddar Core": "Neighbourhood",
    "Adamjee Nagar": "Neighbourhood"
}

In [67]:
df["sub_location_type"] = df["sub_location"].map(sub_location_type_mapping)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20331 entries, 0 to 20457
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20331 non-null  object
 1   address             20331 non-null  object
 2   location            20331 non-null  object
 3   sub_location        20331 non-null  object
 4   price               20331 non-null  float64
 5   price_crore         20331 non-null  float64
 6   price_per_sqft      20331 non-null  float64
 7   area                20331 non-null  float64
 8   bedrooms            20331 non-null  int64
 9   bathrooms           20331 non-null  int64
 10  kitchen             20331 non-null  float64
 11  floor               3982 non-null   float64
 12  total_floors        9517 non-null   float64
 13  parking             20331 non-null  float64
 14  elevator            20331 non-null  int64
 15  servant_quarters    20331 non-null  float64
 16  electricity_backup  20331 non-null  int64
 17  furnished           20331 non-null  int64
 18  completion_year     10758 non-null  float64
 19  property_type       20331 non-null  object
 20  property_age        10758 non-null  float64
 21  age_category        10758 non-null  object
 22  parking_score       20331 non-null  int64
 23  area_per_bedroom    20331 non-null  float64
 24  district            20331 non-null  object
 25  sub_location_type   20331 non-null  object
 26  location_score      20331 non-null  int64
 27  sub_location_score  20331 non-null  int64
dtypes: float64(12), int64(8), object(8)
memory usage: 4.5+ MB

In [ ]:
# Compare the number of listings and typical price in each location.
location_price_stats = df.groupby('location')['price_crore'].agg(
    count='count',
    mean='mean',
    median='median'
).sort_values(by='mean', ascending=False)

# Print the complete comparison table.
print(location_price_stats.to_string())

                      count       mean  median
location
Karsaz                  124  21.504032  20.875
DHA Defence            4208  15.300796  11.000
Jamshed Town           1073   8.492898   5.500
Gulshan-e-Iqbal Town   2205   7.479763   4.000
Clifton                 815   6.921080   5.850
Malir Cantt            1135   6.689782   5.350
Malir                   922   6.014009   5.700
North Nazimabad        1020   5.831608   3.450
Federal B Area          425   5.731118   4.500
Saddar Town             145   5.287724   4.300
Naya Nazimabad          627   3.993174   3.850
Gulistan-e-Jauhar      1748   3.598153   2.300
Bahria Town            1239   2.613928   1.820
Scheme 33              3053   2.612790   2.150
Nazimabad                75   2.413067   1.550
North Karachi           379   2.202858   1.950
Gadap                   700   2.060257   1.550
Super Highway           152   1.929566   1.625
Shah Faisal             138   1.746188   0.900
Korangi                 148   1.006297   0.300

In [70]:
df[df['location']=='Malir']['sub_location']

19                           Airport
40                 Jamia Millia Road
74          Falcon Complex New Malir
78          Falcon Complex New Malir
110         Falcon Complex New Malir
128         Falcon Complex New Malir
191         Falcon Complex New Malir
195                     Model Colony
200         Falcon Complex New Malir
205         Falcon Complex New Malir
212         Falcon Complex New Malir
241      Malir Link To Super Highway
261                Malir_Unspecified
267         Falcon Complex New Malir
273         Falcon Complex New Malir
288                Malir_Unspecified
365                Malir_Unspecified
372         Falcon Complex New Malir
395         Falcon Complex New Malir
408         Falcon Complex New Malir
423         Falcon Complex New Malir
427         Falcon Complex New Malir
433                Malir_Unspecified
490         Falcon Complex New Malir
502                     Model Colony
533                         Falaknaz
551                     Model Colony
554                   Saima Projects
572         Falcon Complex New Malir
578                     Model Colony
584         Falcon Complex New Malir
617         Falcon Complex New Malir
653         Falcon Complex New Malir
654                Malir_Unspecified
669             Malir Town Residency
703                         Falaknaz
733                     Model Colony
788      Malir Link To Super Highway
797         Falcon Complex New Malir
859         Falcon Complex New Malir
885         Falcon Complex New Malir
898         Falcon Complex New Malir
912                   Saima Projects
928         Falcon Complex New Malir
956                     Model Colony
957         Falcon Complex New Malir
960      Malir Link To Super Highway
976                     Model Colony
980                         Falaknaz
992                         Falaknaz
1060        Falcon Complex New Malir
1098        Falcon Complex New Malir
1113                  Saima Projects
1125                    Model Colony
1126                        Falaknaz
1151        Falcon Complex New Malir
1213                         Airport
1291        Falcon Complex New Malir
1326                  Saima Projects
1328                         Airport
1386        Falcon Complex New Malir
1408                        Falaknaz
1415     Malir Link To Super Highway
1434        Falcon Complex New Malir
1436                        Falaknaz
1444        Falcon Complex New Malir
1475        Falcon Complex New Malir
1504        Falcon Complex New Malir
1520        Falcon Complex New Malir
1553     Malir Link To Super Highway
1556               Malir_Unspecified
1560                         Airport
1568        Falcon Complex New Malir
1573               Malir_Unspecified
1574                  Saima Projects
1578        Falcon Complex New Malir
1587                         Airport
1611                  Saima Projects
1635        Falcon Complex New Malir
1639     Malir Link To Super Highway
1641        Falcon Complex New Malir
1673        Falcon Complex New Malir
1683        Falcon Complex New Malir
1732                        Falaknaz
1739                    Model Colony
1752               Jamia Millia Road
1763        Falcon Complex New Malir
1775        Falcon Complex New Malir
1797                    Model Colony
1799        Falcon Complex New Malir
1809                        Falaknaz
1810                     Golden Town
1861        Falcon Complex New Malir
1886        Falcon Complex New Malir
1906        Falcon Complex New Malir
1908        Falcon Complex New Malir
1911                        Falaknaz
1912                         Airport
1926                        Falaknaz
1972        Falcon Complex New Malir
1977     Malir Link To Super Highway
2006        Falcon Complex New Malir
2017     Malir Link To Super Highway
2097                    Model Colony
2135        Falcon Complex New Malir
2235     Malir Link To Super Highway
2259        Falcon Complex New Malir
2282        Falcon Complex New Malir
2299        Falcon Complex New Malir
2323                        Falaknaz
2329        Falcon Complex New Malir
2356        Falcon Complex New Malir
2371        Falcon Complex New Malir
2392        Falcon Complex New Malir
2408                        Falaknaz
2457        Falcon Complex New Malir
2508                    Model Colony
2510                        Falaknaz
2516        Falcon Complex New Malir
2552     Malir Link To Super Highway
2584               Jamia Millia Road
2588        Falcon Complex New Malir
2589        Falcon Complex New Malir
2623                         Airport
2625                     Golden Town
2655        Falcon Complex New Malir
2658        Falcon Complex New Malir
2744                    Model Colony
2778        Falcon Complex New Malir
2783                        Falaknaz
2789                  Saima Projects
2814                        Falaknaz
2835        Falcon Complex New Malir
2837        Falcon Complex New Malir
2855        Falcon Complex New Malir
2900        Falcon Complex New Malir
2945                         Airport
2946        Falcon Complex New Malir
2982        Falcon Complex New Malir
2988                  Saima Projects
3015        Falcon Complex New Malir
3048        Falcon Complex New Malir
3050        Falcon Complex New Malir
3053     Malir Link To Super Highway
3072        Falcon Complex New Malir
3078     Malir Link To Super Highway
3109        Falcon Complex New Malir
3123        Falcon Complex New Malir
3156               Jamia Millia Road
3160                    Model Colony
3168                     Golden Town
3192            Malir Town Residency
3193        Falcon Complex New Malir
3202               Malir_Unspecified
3204               Malir_Unspecified
3207               Jamia Millia Road
3227                         Airport
3256        Falcon Complex New Malir
3259        Falcon Complex New Malir
3276        Falcon Complex New Malir
3352        Falcon Complex New Malir
3353        Falcon Complex New Malir
3360        Falcon Complex New Malir
3388                    Model Colony
3390                        Falaknaz
3404                    Model Colony
3405                    Model Colony
3414        Falcon Complex New Malir
3492     Malir Link To Super Highway
3493                         Airport
3497        Falcon Complex New Malir
3500        Falcon Complex New Malir
3503        Falcon Complex New Malir
3506        Falcon Complex New Malir
3518        Falcon Complex New Malir
3519        Falcon Complex New Malir
3535                    Model Colony
3554                        Falaknaz
3566                        Falaknaz
3616        Falcon Complex New Malir
3622                         Airport
3639        Falcon Complex New Malir
3656                        Falaknaz
3661        Falcon Complex New Malir
3662               Malir_Unspecified
3685                        Falaknaz
3737        Falcon Complex New Malir
3748                    Model Colony
3750        Falcon Complex New Malir
3766        Falcon Complex New Malir
3778                         Airport
3780        Falcon Complex New Malir
3785        Falcon Complex New Malir
3789                        Falaknaz
3790        Falcon Complex New Malir
3824        Falcon Complex New Malir
3825                    Model Colony
3857        Falcon Complex New Malir
3880        Falcon Complex New Malir
3925                  Saima Projects
3968               Malir_Unspecified
4054        Falcon Complex New Malir
4059        Falcon Complex New Malir
4104               Malir_Unspecified
4107        Falcon Complex New Malir
4112        Falcon Complex New Malir
4162                    Model Colony
4191                        Falaknaz
4199               Jamia Millia Road
4200        Falcon Complex New Malir
4230        Falcon Complex New Malir
4250     Malir Link To Super Highway
4273                        Falaknaz
4288                  Saima Projects
4292                        Falaknaz
4293        Falcon Complex New Malir
4308        Falcon Complex New Malir
4329        Falcon Complex New Malir
4336                        Falaknaz
4420        Falcon Complex New Malir
4445        Falcon Complex New Malir
4464                         Airport
4477                        Falaknaz
4495        Falcon Complex New Malir
4505        Falcon Complex New Malir
4542               Malir_Unspecified
4559        Falcon Complex New Malir
4598        Falcon Complex New Malir
4626                         Airport
4644     Malir Link To Super Highway
4650               Malir_Unspecified
4657        Falcon Complex New Malir
4684                    Model Colony
4732                        Falaknaz
4739        Falcon Complex New Malir
4755        Falcon Complex New Malir
4782        Falcon Complex New Malir
4819     Malir Link To Super Highway
4836        Falcon Complex New Malir
4884                  Saima Projects
4920        Falcon Complex New Malir
4936        Falcon Complex New Malir
4951                  Saima Projects
4962        Falcon Complex New Malir
4973        Falcon Complex New Malir
4981        Falcon Complex New Malir
5070     Malir Link To Super Highway
5076        Falcon Complex New Malir
5088               Malir_Unspecified
5108                        Falaknaz
5129        Falcon Complex New Malir
5132        Falcon Complex New Malir
5153        Falcon Complex New Malir
5158                        Falaknaz
5162                        Falaknaz
5173        Falcon Complex New Malir
5208        Falcon Complex New Malir
5209                        Falaknaz
5247        Falcon Complex New Malir
5289                         Airport
5292        Falcon Complex New Malir
5342               Jamia Millia Road
5358        Falcon Complex New Malir
5389        Falcon Complex New Malir
5401        Falcon Complex New Malir
5412                    Model Colony
5421        Falcon Complex New Malir
5426        Falcon Complex New Malir
5430     Malir Link To Super Highway
5441        Falcon Complex New Malir
5491        Falcon Complex New Malir
5501     Malir Link To Super Highway
5537        Falcon Complex New Malir
5564     Malir Link To Super Highway
5607               Malir_Unspecified
5618     Malir Link To Super Highway
5636     Malir Link To Super Highway
5644        Falcon Complex New Malir
5664            Malir Town Residency
5684                     Golden Town
5694                    Model Colony
5699                        Falaknaz
5717        Falcon Complex New Malir
5731        Falcon Complex New Malir
5739     Malir Link To Super Highway
5747                        Falaknaz
5764        Falcon Complex New Malir
5767        Falcon Complex New Malir
5769                         Airport
5830        Falcon Complex New Malir
5839        Falcon Complex New Malir
5840     Malir Link To Super Highway
5841                     Golden Town
5860     Malir Link To Super Highway
5892                    Model Colony
5922     Malir Link To Super Highway
5961        Falcon Complex New Malir
5968        Falcon Complex New Malir
5986        Falcon Complex New Malir
6023        Falcon Complex New Malir
6028        Falcon Complex New Malir
6031        Falcon Complex New Malir
6119        Falcon Complex New Malir
6138        Falcon Complex New Malir
6194        Falcon Complex New Malir
6199        Falcon Complex New Malir
6241                         Airport
6279     Malir Link To Super Highway
6303                        Falaknaz
6306               Malir_Unspecified
6316                    Model Colony
6340        Falcon Complex New Malir
6347     Malir Link To Super Highway
6400        Falcon Complex New Malir
6443     Malir Link To Super Highway
6448                         Airport
6461                    Model Colony
6480        Falcon Complex New Malir
6513                        Falaknaz
6537        Falcon Complex New Malir
6552        Falcon Complex New Malir
6574                        Falaknaz
6622                     Golden Town
6662                    Model Colony
6673        Falcon Complex New Malir
6700                         Airport
6735                     Golden Town
6736                        Falaknaz
6771               Malir_Unspecified
6774        Falcon Complex New Malir
6777        Falcon Complex New Malir
6783        Falcon Complex New Malir
6825        Falcon Complex New Malir
6846                    Model Colony
6858                    Model Colony
6912        Falcon Complex New Malir
6992                         Airport
7013     Malir Link To Super Highway
7016        Falcon Complex New Malir
7035        Falcon Complex New Malir
7057        Falcon Complex New Malir
7066        Falcon Complex New Malir
7086        Falcon Complex New Malir
7111        Falcon Complex New Malir
7156               Malir_Unspecified
7169                  Saima Projects
7202        Falcon Complex New Malir
7273                        Falaknaz
7283                        Falaknaz
7342        Falcon Complex New Malir
7354        Falcon Complex New Malir
7398        Falcon Complex New Malir
7421               Malir_Unspecified
7434        Falcon Complex New Malir
7463        Falcon Complex New Malir
7471     Malir Link To Super Highway
7538        Falcon Complex New Malir
7544        Falcon Complex New Malir
7593                    Model Colony
7635        Falcon Complex New Malir
7658        Falcon Complex New Malir
7683        Falcon Complex New Malir
7721        Falcon Complex New Malir
7722        Falcon Complex New Malir
7773        Falcon Complex New Malir
7789                         Airport
7823        Falcon Complex New Malir
7836                         Airport
7846                  Saima Projects
7852               Malir_Unspecified
7857        Falcon Complex New Malir
7864               Malir_Unspecified
7870                        Falaknaz
7890        Falcon Complex New Malir
7921                         Airport
7930        Falcon Complex New Malir
7954        Falcon Complex New Malir
7977                     Golden Town
7989                    Model Colony
8003        Falcon Complex New Malir
8043                    Model Colony
8050        Falcon Complex New Malir
8066                        Falaknaz
8100     Malir Link To Super Highway
8136                  Saima Projects
8139        Falcon Complex New Malir
8155        Falcon Complex New Malir
8158        Falcon Complex New Malir
8159        Falcon Complex New Malir
8171        Falcon Complex New Malir
8184               Malir_Unspecified
8253                    Model Colony
8269        Falcon Complex New Malir
8275        Falcon Complex New Malir
8276                         Airport
8301                         Airport
8339        Falcon Complex New Malir
8354                        Falaknaz
8360        Falcon Complex New Malir
8367        Falcon Complex New Malir
8376                        Falaknaz
8384               Malir_Unspecified
8385                    Model Colony
8453                        Falaknaz
8471     Malir Link To Super Highway
8473        Falcon Complex New Malir
8485                  Saima Projects
8506        Falcon Complex New Malir
8510                        Falaknaz
8529        Falcon Complex New Malir
8584                    Model Colony
8597               Malir_Unspecified
8623        Falcon Complex New Malir
8655        Falcon Complex New Malir
8740                    Model Colony
8749        Falcon Complex New Malir
8758     Malir Link To Super Highway
8803        Falcon Complex New Malir
8820                    Model Colony
8884        Falcon Complex New Malir
8954                         Airport
8963                    Model Colony
8982        Falcon Complex New Malir
8994        Falcon Complex New Malir
9018     Malir Link To Super Highway
9062                         Airport
9077        Falcon Complex New Malir
9079                    Model Colony
9139        Falcon Complex New Malir
9140        Falcon Complex New Malir
9161        Falcon Complex New Malir
9170                         Airport
9211        Falcon Complex New Malir
9223                        Falaknaz
9316        Falcon Complex New Malir
9347                        Falaknaz
9412        Falcon Complex New Malir
9453                    Model Colony
9456                  Saima Projects
9469               Malir_Unspecified
9470                        Falaknaz
9473     Malir Link To Super Highway
9479                    Model Colony
9499               Malir_Unspecified
9583                     Golden Town
9588     Malir Link To Super Highway
9639               Jamia Millia Road
9653     Malir Link To Super Highway
9713     Malir Link To Super Highway
9740        Falcon Complex New Malir
9746        Falcon Complex New Malir
9786               Jamia Millia Road
9819     Malir Link To Super Highway
9820                    Model Colony
9842        Falcon Complex New Malir
9848                        Falaknaz
9849                  Saima Projects
9853                     Golden Town
9856               Malir_Unspecified
9861                    Model Colony
10006       Falcon Complex New Malir
10010    Malir Link To Super Highway
10083    Malir Link To Super Highway
10090       Falcon Complex New Malir
10092                   Model Colony
10103       Falcon Complex New Malir
10148       Falcon Complex New Malir
10152       Falcon Complex New Malir
10184       Falcon Complex New Malir
10194    Malir Link To Super Highway
10209       Falcon Complex New Malir
10211       Falcon Complex New Malir
10246    Malir Link To Super Highway
10249       Falcon Complex New Malir
10257       Falcon Complex New Malir
10262                   Model Colony
10329           Malir Town Residency
10466       Falcon Complex New Malir
10478    Malir Link To Super Highway
10576       Falcon Complex New Malir
10581       Falcon Complex New Malir
10617              Malir_Unspecified
10637                   Model Colony
10658       Falcon Complex New Malir
10713       Falcon Complex New Malir
10724       Falcon Complex New Malir
10733       Falcon Complex New Malir
10736                   Model Colony
10753                   Model Colony
10792       Falcon Complex New Malir
10849       Falcon Complex New Malir
10868                       Falaknaz
10890                   Model Colony
10929                 Saima Projects
10977       Falcon Complex New Malir
11000                   Model Colony
11012                 Saima Projects
11029       Falcon Complex New Malir
11047                       Falaknaz
11053                 Saima Projects
11054              Jamia Millia Road
11064       Falcon Complex New Malir
11089                   Model Colony
11102       Falcon Complex New Malir
11103       Falcon Complex New Malir
11130              Jamia Millia Road
11133                   Model Colony
11172       Falcon Complex New Malir
11216                   Model Colony
11238                   Model Colony
11253       Falcon Complex New Malir
11260    Malir Link To Super Highway
11265                        Airport
11293       Falcon Complex New Malir
11314       Falcon Complex New Malir
11326                   Model Colony
11332                       Falaknaz
11334       Falcon Complex New Malir
11360                       Falaknaz
11388       Falcon Complex New Malir
11391       Falcon Complex New Malir
11425       Falcon Complex New Malir
11433                       Falaknaz
11435                       Falaknaz
11472                        Airport
11473       Falcon Complex New Malir
11480       Falcon Complex New Malir
11489                   Model Colony
11498                        Airport
11536              Malir_Unspecified
11542       Falcon Complex New Malir
11556       Falcon Complex New Malir
11570       Falcon Complex New Malir
11625       Falcon Complex New Malir
11645    Malir Link To Super Highway
11663                       Falaknaz
11666                       Falaknaz
11677       Falcon Complex New Malir
11692       Falcon Complex New Malir
11698       Falcon Complex New Malir

In [ ]:
location_desirability = {

    # The most established areas with the strongest market appeal.
    "DHA Defence": 5,
    "Malir Cantt": 5,
    "Clifton": 5,
    "Karsaz": 5,

    # Premium areas with consistently strong demand.
    "Gulshan-e-Iqbal Town": 4,
    "North Nazimabad": 4,
    "Jamshed Town": 4,

    # Balanced areas with room for continued growth.
    "Federal B Area": 3,
    "Naya Nazimabad": 3,
    "Gulistan-e-Jauhar": 3,
    "Saddar Town": 3,
    "Scheme 33": 3,
    "Bahria Town": 3,

    # More affordable, densely populated areas.
    "Nazimabad": 2,
    "Malir": 2,
    "North Karachi": 2,
    "Shah Faisal": 2,

    # Outer or industrial areas with longer-term potential.
    "Super Highway": 1,
    "Gadap": 1,
    "Korangi": 1,
}

df["location_score"] = df["location"].map(location_desirability)

In [ ]:
import pandas as pd
import numpy as np


MIN_COUNT = 10


K = 10


location_stats = (
    df.groupby("location")
      .agg(
          location_median_ppsqft=("price_per_sqft", "median"),
          location_count=("price_per_sqft", "count")
      )
      .reset_index()
)


sub_stats = (
    df.groupby(["location", "sub_location"])
      .agg(
          sub_median_ppsqft=("price_per_sqft", "median"),
          sub_count=("price_per_sqft", "count")
      )
      .reset_index()
)




sub_stats = sub_stats.merge(
    location_stats,
    on="location",
    how="left"
)

sub_stats["sub_weight"] = (
    sub_stats["sub_count"] /
    (sub_stats["sub_count"] + K)
)

sub_stats["parent_weight"] = (
    K /
    (sub_stats["sub_count"] + K)
)


sub_stats["adjusted_ppsqft"] = (
    sub_stats["sub_weight"] *
    sub_stats["sub_median_ppsqft"]
    +
    sub_stats["parent_weight"] *
    sub_stats["location_median_ppsqft"]
)


sub_stats["adjusted_ppsqft"] = (
    sub_stats["adjusted_ppsqft"]
    .fillna(sub_stats["location_median_ppsqft"])
)

sub_stats["price_percentile"] = (
    sub_stats["adjusted_ppsqft"]
    .rank(
        method="average",
        pct=True
    )
)



# Turn each adjusted percentile into a score from 1 to 5.


sub_stats["sub_location_score"] = pd.cut(
    sub_stats["price_percentile"],
    bins=[
        0,
        0.20,
        0.40,
        0.60,
        0.80,
        1.00
    ],
    labels=[
        1,
        2,
        3,
        4,
        5
    ],
    include_lowest=True
).astype(int)


# Build a lookup table for each location and sub-location pair.

score_map = (
    sub_stats
    .set_index(["location", "sub_location"])
    ["sub_location_score"]
)


# Add the calculated sub-location score back to the main dataframe.

df["sub_location_score"] = [
    score_map.get((loc, sub), np.nan)
    for loc, sub in zip(
        df["location"],
        df["sub_location"]
    )
]



# Use the parent location's score for rows with an unspecified sub-location.
#
# For example, DHA Defence_Unspecified does not identify a specific area,
# so it receives the broader DHA Defence market score.


unknown_mask = (
    df["sub_location"]
    .astype("string")
    .str.endswith("_Unspecified", na=False)
)


# Rank parent locations by their median price per square foot.
location_percentile_map = (
    location_stats
    .set_index("location")
    ["location_median_ppsqft"]
    .rank(pct=True)
)


location_score_map = pd.cut(
    location_percentile_map,
    bins=[
        0,
        0.20,
        0.40,
        0.60,
        0.80,
        1.00
    ],
    labels=[
        1,
        2,
        3,
        4,
        5
    ],
    include_lowest=True
).astype(int)


df.loc[unknown_mask, "sub_location_score"] = (
    df.loc[unknown_mask, "location"]
      .map(location_score_map)
)


# Fill scores for records where the sub-location itself is missing.

missing_sub_mask = df["sub_location"].isna()

df.loc[missing_sub_mask, "sub_location_score"] = (
    df.loc[missing_sub_mask, "location"]
      .map(location_score_map)
)


# Use the parent-location score as the final fallback for any remaining gaps.

df["sub_location_score"] = (
    df["sub_location_score"]
    .fillna(
        df["location"]
        .map(location_score_map)
    )
)


# Round the scores and keep them within the expected 1-to-5 range.

df["sub_location_score"] = (
    df["sub_location_score"]
    .round()
    .clip(1, 5)
    .astype(int)
)


# Print a sample of the results so the scoring can be checked.

print(
    sub_stats[
        [
            "location",
            "sub_location",
            "sub_count",
            "sub_median_ppsqft",
            "location_median_ppsqft",
            "sub_weight",
            "parent_weight",
            "adjusted_ppsqft",
            "sub_location_score"
        ]
    ]
    .sort_values(
        "adjusted_ppsqft",
        ascending=False
    )
    .head(30)
)


# Show how many records received each score.

print(
    "\nSub-location score distribution:"
)

print(
    df["sub_location_score"]
    .value_counts()
    .sort_index()
)

                 location                sub_location  sub_count  \
125  Gulshan-e-Iqbal Town     National Stadium Colony         22
147                Karsaz  Navy Housing Scheme Karsaz        124
131          Jamshed Town       Falcon Complex Faisal         14
47            DHA Defence           Phase 7 Extension        141
111  Gulshan-e-Iqbal Town    Gulshan-e-Iqbal Block 17         97
49            DHA Defence           Phase 8 Extension         12
48            DHA Defence                     Phase 8       2047
128          Jamshed Town                 Amir Khusro         33
93   Gulshan-e-Iqbal Town               Adamjee Nagar         16
42            DHA Defence                     Phase 4        156
167        Naya Nazimabad      Naya Nazimabad Block A         93
122  Gulshan-e-Iqbal Town                Kda Scheme 1         84
124  Gulshan-e-Iqbal Town        Mohammad Ali Society         17
38            DHA Defence     DHA Defence_Unspecified         26
169        Naya Nazimabad      Naya Nazimabad Block C         91
134          Jamshed Town    Jamshed Town_Unspecified         32
106  Gulshan-e-Iqbal Town  Gulshan-e-Iqbal Block 13D1         65
123  Gulshan-e-Iqbal Town      Kda Scheme 1 Extension         11
146          Jamshed Town            Tipu Sultan Road         32
170        Naya Nazimabad      Naya Nazimabad Block D         66
46            DHA Defence                     Phase 7        286
140          Jamshed Town                       Pechs        268
44            DHA Defence           Phase 5 Extension         21
25                Clifton                 Bath Island        123
164           Malir Cantt                Dohs Phase 1         40
202           Saddar Town                 Civil Lines         88
45            DHA Defence                     Phase 6        886
141          Jamshed Town         Shaheed Millat Road        185
117  Gulshan-e-Iqbal Town     Gulshan-e-Iqbal Block 5         77
40            DHA Defence                     Phase 2         52

     sub_median_ppsqft  location_median_ppsqft  sub_weight  parent_weight  \
125         114271.940               21957.670    0.687500       0.312500
147          64285.715               64285.715    0.925373       0.074627
131          76666.670               27948.190    0.583333       0.416667
47           55555.560               38888.890    0.933775       0.066225
111          48888.890               21957.670    0.906542       0.093458
49           50000.000               38888.890    0.545455       0.454545
48           44117.650               38888.890    0.995139       0.004861
128          48666.670               27948.190    0.767442       0.232558
93           55555.560               21957.670    0.615385       0.384615
42           40740.740               38888.890    0.939759       0.060241
167          40277.780               30769.230    0.902913       0.097087
122          40740.740               21957.670    0.893617       0.106383
124          48000.000               21957.670    0.629630       0.370370
38           36486.795               38888.890    0.722222       0.277778
169          37847.220               30769.230    0.900990       0.099010
134          40000.000               27948.190    0.761905       0.238095
106          37037.040               21957.670    0.866667       0.133333
123          46666.670               21957.670    0.523810       0.476190
146          36539.745               27948.190    0.761905       0.238095
170          34856.150               30769.230    0.868421       0.131579
46           32222.220               38888.890    0.966216       0.033784
140          32532.530               27948.190    0.964029       0.035971
44           28888.890               38888.890    0.677419       0.322581
25           32532.530               26455.030    0.924812       0.075188
164          34595.955               18351.690    0.800000       0.200000
202          32032.570               24024.020    0.897959       0.102041
45           31111.110               38888.890    0.988839       0.011161
141          31141.010               27948.190    0.948718       0.051282
117          31944.440               21957.670    0.885057       0.114943
40           28888.890               38888.890    0.838710       0.161290

     adjusted_ppsqft  sub_location_score
125     85423.730625                   5
147     64285.715000                   5
131     56367.303333                   5
47      54451.807020                   5
111     46371.953551                   5
49      44949.495455                   5
48      44092.230651                   5
128     43848.418837                   5
93      42633.294615                   5
42      40629.182771                   5
167     39354.619806                   5
122     38742.541064                   5
124     38354.692593                   5
38      37154.043611                   5
169     37146.428911                   5
134     37130.521429                   5
106     35026.457333                   5
123     34900.479524                   5
146     34494.136667                   5
170     34318.397368                   5
46      32447.445338                   5
140     32367.625683                   5
44      32114.696452                   5
25      32075.575113                   5
164     31347.102000                   5
202     31215.371020                   5
45      31197.915580                   5
141     30977.275641                   5
117     30796.535402                   5
40      30501.793226                   5

Sub-location score distribution:
sub_location_score
1    2526
2    3597
3    3842
4    3996
5    6370
Name: count, dtype: int64

In [73]:
df.groupby('sub_location_score')['sub_location'].value_counts().index

MultiIndex([(1,               'Surjani Town'),
            (1, 'Gulistan-e-Jauhar Block 13'),
            (1, 'Gulistan-e-Jauhar Block 18'),
            (1,                'Sector 18-A'),
            (1,                   'Falaknaz'),
            (1,                  'Sector 44'),
            (1, 'Gulistan-e-Jauhar Block 17'),
            (1,             'Allahwala Town'),
            (1,         'Bahria Sports City'),
            (1,                'Precinct 12'),
            ...
            (5,       'Mohammad Ali Society'),
            (5,              'Adamjee Nagar'),
            (5,    'North Karachi Sector 10'),
            (5,      'Falcon Complex Faisal'),
            (5,           'Shahra-E-Qaideen'),
            (5,    'Federal B Area Block 15'),
            (5,     'Federal B Area Block 6'),
            (5,          'Phase 8 Extension'),
            (5,            'Clifton Block 6'),
            (5,     'Kda Scheme 1 Extension')],
           names=['sub_location_score', 'sub_location'], length=248)

In [ ]:
sub_location_score_mapping = {


    # SCORE 5 — VERY PREMIUM (Median PPSF >= 40,000)
    
    "National Stadium Colony": 5,
    "Falcon Complex Faisal": 5,
    "Navy Housing Scheme Karsaz": 5,
    "Adamjee Nagar": 5,
    "Phase 7 Extension": 5,
    "Phase 8 Extension": 5,
    "Gulshan-e-Iqbal Block 17": 5,
    "Amir Khusro": 5,
    "Mohammad Ali Society": 5,
    "Kda Scheme 1 Extension": 5,
    "Phase 8": 5,
    "Kda Scheme 1": 5,
    "Phase 4": 5,
    "Naya Nazimabad Block A": 5,
    "Jamshed Town_Unspecified": 5,

    # SCORE 4 — PREMIUM (Median PPSF 30,000–39,999)

    "Naya Nazimabad Block C": 4,
    "Gulshan-e-Iqbal Block 13D1": 4,
    "Tipu Sultan Road": 4,
    "DHA Defence_Unspecified": 4,
    "Naya Nazimabad Block D": 4,
    "Dohs Phase 1": 4,
    "Gulshan-e-Iqbal Block 19": 4,
    "Federal B Area Block 14": 4,
    "Clifton Block 6": 4,
    "Bath Island": 4,
    "Pechs": 4,
    "Phase 7": 4,
    "Civil Lines": 4,
    "Gulshan-e-Iqbal Block 5": 4,
    "North Karachi Sector 10": 4,
    "Dohs Phase 2": 4,
    "Shaheed Millat Road": 4,
    "Phase 6": 4,
    "North Nazimabad Block C": 4,
    "Clifton Block 8": 4,
    "Federal B Area Block 15": 4,

    
    # SCORE 3 — UPPER/MIDDLE MARKET
    # Median PPSF 20,000–29,999

    "Smchs - Sindhi Muslim Society": 3,
    "Federal B Area Block 6": 3,
    "Federal B Area Block 12": 3,
    "Federal B Area Block 16": 3,
    "Qayyumabad": 3,
    "Gulshan-e-Iqbal Block 21": 3,
    "Phase 2": 3,
    "Phase 5 Extension": 3,
    "Gulistan-e-Jauhar Block 3": 3,
    "Gulshan-e-Iqbal Block 13": 3,
    "Federal B Area Block 19": 3,
    "Shahra-E-Qaideen": 3,
    "Gulshan-e-Iqbal Block 9": 3,
    "Clifton Block 7": 3,
    "Clifton Block 9": 3,
    "Bahadurabad": 3,
    "Gulshan-e-Iqbal Block 6": 3,
    "Naya Nazimabad Block M": 3,
    "Naya Nazimabad Block B": 3,
    "Frere Town": 3,
    "Clifton Block 5": 3,
    "Askari 4": 3,
    "Khalid Bin Walid Road": 3,
    "Clifton_Unspecified": 3,
    "Gulshan-e-Iqbal Block 3": 3,
    "Falcon Complex New Malir": 3,
    "Sector 36-A": 3,
    "North Karachi Sector 9": 3,
    "Sector 48-A": 3,
    "Garden East": 3,
    "Phase 5": 3,
    "Buffer Zone": 3,
    "Cosmopolitan Society": 3,
    "Federal B Area Block 13": 3,
    "Sector 17-A": 3,
    "Model Colony": 3,
    "Federal B Area_Unspecified": 3,
    "Saima Projects": 3,
    "Punjabi Saudagar Society": 3,
    "North Nazimabad Block I": 3,
    "Askari 6": 3,
    "Muslimabad Society": 3,
    "Gulistan-e-Jauhar Block 4": 3,
    "Gulshan-e-Iqbal Block 13D": 3,
    "Sharfabad": 3,
    "Clifton Block 3": 3,
    "North Nazimabad Block A": 3,
    "North Karachi Sector 8": 3,
    "Gulistan-e-Jauhar Block 2": 3,
    "Dhoraji Colony": 3,
    "Tariq Road": 3,
    "Amil Colony": 3,
    "Saima Luxury Belt": 3,
    "Shadman": 3,
    "North Nazimabad Block L": 3,
    "Gulshan-e-Iqbal Block 7": 3,
    "Clifton Block 2": 3,
    "Gulistan-e-Jauhar Block 1": 3,
    "Cp Barar Society, Gulshan-E-Iqbal Town": 3,
    "Sector 20-A": 3,
    "Gulistan-e-Jauhar Block 12": 3,
    "Meerut Society": 3,
    "Sector 35-A": 3,
    "Phase 1": 3,
    "Federal B Area Block 10": 3,
    "Gulistan-e-Jauhar Block 9": 3,
    "Gulshan-e-Iqbal Block 16": 3,
    "North Nazimabad Block N": 3,
    "Federal B Area Block 11": 3,
    "Gulshan-e-Iqbal Block 14": 3,
    "North Nazimabad Block D": 3,
    "Gulshan-e-Iqbal Block 10": 3,
    "Soldier Bazar": 3,
    "Parsi Colony": 3,
    "Gulistan-e-Jauhar Block 15": 3,
    "Gulshan-e-Iqbal Block 4": 3,
    "Gulistan-e-Jauhar Block 14": 3,
    "Federal B Area Block 20": 3,
    "North Nazimabad Block J": 3,
    "Sector 51-A": 3,
    "Clifton Block 4": 3,
    "Sector 24-A": 3,
    "North Nazimabad Block H": 3,
    "Sector 52-A": 3,
    "Federal B Area Block 21": 3,
    "Oasis Park Residencia": 3,
    "Gulshan-e-Iqbal Block 10A": 3,
    "Gulistan-e-Jauhar Block 16A": 2,
    "Sector 22-A": 2,
    "Gulshan-e-Iqbal Block 2": 2,
    "Clifton Block 1": 2,
    "North Nazimabad Block F": 2,


    
    # SCORE 2 — MIDDLE/LOWER MARKET
    # Median PPSF 10,000–19,999
    
    
    "Gulistan-e-Jauhar Block 8": 2,
    "North Nazimabad Block B": 2,
    "Sector 47": 2,
    "Defence View": 2,
    "North Nazimabad_Unspecified": 2,
    "Naya Nazimabad_Unspecified": 2,
    "Gulshan-e-Iqbal Town_Unspecified": 2,
    "Malir Cantt_Unspecified": 2,
    "Askari 5": 2,
    "Jamshed Road": 2,
    "Phase 2 Extension": 2,
    "Sector 15-A": 2,
    "North Karachi Sector 5": 2,
    "Precinct 18": 2,
    "Saadi Garden": 2,
    "Sector 19-A": 2,
    "Sector 43-A": 2,
    "Gulistan-e-Jauhar Block 16": 2,
    "Gulshan-e-Iqbal Block 13C": 2,
    "Gulistan-e-Jauhar Block 3A": 2,
    "Shahrah-E-Pakistan": 2,
    "North Karachi Sector 7": 2,
    "Nazimabad 4": 2,
    "North Karachi Sector 11": 2,
    "Karachi Administration Employees Society": 2,
    "Gulshan-e-Iqbal Block 13A": 2,
    "Saddar Core": 2,
    "Federal B Area Block 9": 2,
    "Gulistan-e-Jauhar_Unspecified": 2,
    "Gulshan-e-Iqbal Block 1": 2,
    "Nazimabad 2": 2,
    "Gulistan-e-Jauhar Block 5": 2,
    "Airport": 2,
    "Gulistan-e-Jauhar Block 19": 2,
    "Gulistan-e-Jauhar Block 7": 2,
    "Sector 40": 2,
    "Precinct 8": 2,
    "Precinct 1": 2,
    "Gulshan-e-Usman Housing Society": 2,
    "DHA City": 2,
    "Sector 45-A": 2,
    "Gulshan-e-Iqbal Block 13B": 2,
    "Federal B Area Block 8": 2,
    "Malir_Unspecified": 2,
    "Gulshan-E-Maymar": 2,
    "Garden West": 2,
    "Gulshan-e-Iqbal Block 13D2": 2,
    "Precinct 2": 2,
    "Nazimabad 1": 2,
    "Sector 29": 2,
    "Sector 34-A": 2,
    "Precinct 9": 2,
    "Precinct 7": 2,
    "Gulistan-e-Jauhar Block 11": 2,
    "Sector 16-A": 2,
    "North Nazimabad Block M": 2,
    "Super Highway_Unspecified": 2,
    "Precinct 6": 2,
    "Precinct 12": 2,
    "Gulshan-e-Iqbal Block 11": 2,
    "Scheme 33_Unspecified": 2,
    "Gohar Green City Cluster": 2,
    "Sector 38-A": 2,
    "New Karachi": 2,
    "Falaknaz": 2,
    "Sector 18-C": 2,
    "Gulistan-e-Jauhar Block 10": 2,
    "Precinct 4": 2,
    "Malir Link To Super Highway": 2,
    "Sector 18-A": 2,
    "Nazimabad 5": 2,
    "Kda Employees Society": 2,
    "Nazimabad 3": 2,
    "Sector 44": 2,
    "Saima Villas": 2,
    "Sector 25-B": 2,
    "Gulistan-e-Jauhar Block 13": 2,
    "Precinct 16": 2,
    "Sector 42-A": 2,
    "Safoora Goth": 2,
    "Precinct 17": 2,
    "Precinct 10A": 2,
    "Sector 30": 2,
    "Gulshan-e-Iqbal Block 13D3": 2,
    "Memon Goth": 2,
    "Saadi Road": 2,
    "Sector 17-B": 2,
    "Precinct 11A": 2,
    "Surjani Town": 2,
    "Precinct 11B": 2,
    "Precinct 15": 2,
    "Federal B Area Block 7": 2,



    # SCORE 1 — LOWER MARKET
    # Median PPSF < 10,000

    "Bahria Paradise": 1,
    "Precinct 10B": 1,
    "North Nazimabad Block K": 1,
    "North Nazimabad Block G": 1,
    "Bahria Town_Unspecified": 1,
    "Gulistan-e-Jauhar Block 20": 1,
    "Gizri": 1,
    "Jamia Millia Road": 1,
    "Gulistan-e-Jauhar Block 18": 1,
    "Precinct 19": 1,
    "Bahria Apartments": 1,
    "Shah Faisal_Unspecified": 1,
    "Sector 24-B": 1,
    "North Karachi_Unspecified": 1,
    "Green Town / Rafah-E-Aam Belt": 1,
    "Mehmoodabad": 1,
    "Gulistan-e-Jauhar Block 17": 1,
    "Precinct 27": 1,
    "Precinct 31": 1,
    "Shamsi / Al-Falah Belt": 1,
    "Bahria Heights": 1,
    "Korangi Industrial Area": 1,
    "Malir Town Residency": 1,
    "Private High-Rises": 1,
    "Bahria Sports City": 1,
    "Golden Town": 1,
    "Allahwala Town": 1
}
# Map desirability score
df["sub_location_score"] = (
    df["sub_location"]
    .map(sub_location_score_mapping)
)

In [87]:
df.groupby('sub_location')['price_per_sqft'].agg(['mean','median']).sort_values(by='median', ascending=False)

                                                   mean      median
sub_location
National Stadium Colony                   103054.294091  114271.940
Falcon Complex Faisal                      79668.367143   76666.670
Navy Housing Scheme Karsaz                 62041.607742   64285.715
Adamjee Nagar                              55407.533750   55555.560
Phase 7 Extension                          48472.636667   55555.560
Phase 8 Extension                          50766.675833   50000.000
Gulshan-e-Iqbal Block 17                   57297.774845   48888.890
Amir Khusro                                51790.410606   48666.670
Mohammad Ali Society                       44566.316471   48000.000
Kda Scheme 1 Extension                     49248.900000   46666.670
Phase 8                                    47044.278390   44117.650
Kda Scheme 1                               44825.873571   40740.740
Phase 4                                    39236.589487   40740.740
Naya Nazimabad Block A                     38164.248387   40277.780
Jamshed Town_Unspecified                   39817.883125   40000.000
Naya Nazimabad Block C                     36889.878681   37847.220
Gulshan-e-Iqbal Block 13D1                 34892.499231   37037.040
Tipu Sultan Road                           39249.395000   36539.745
DHA Defence_Unspecified                    46519.704615   36486.795
Naya Nazimabad Block D                     34475.228333   34856.150
Dohs Phase 1                               34434.194250   34595.955
Gulshan-e-Iqbal Block 19                   31008.392222   32986.110
Federal B Area Block 14                    33990.406842   32870.370
Clifton Block 6                            30545.840000   32771.540
Bath Island                                33171.158293   32532.530
Pechs                                      36664.279104   32532.530
Phase 7                                    33201.692308   32222.220
Civil Lines                                31971.661818   32032.570
Gulshan-e-Iqbal Block 5                    32019.563636   31944.440
North Karachi Sector 10                    27901.465000   31567.460
Dohs Phase 2                               33663.880909   31313.130
Shaheed Millat Road                        32570.128811   31141.010
Phase 6                                    32705.094244   31111.110
North Nazimabad Block C                    30470.086667   30555.560
Clifton Block 8                            32107.689205   30166.530
Federal B Area Block 15                    30717.743077   30092.590
Smchs - Sindhi Muslim Society              34316.166744   29782.360
Federal B Area Block 6                     29402.553333   29686.680
Federal B Area Block 12                    32287.416800   29444.445
Federal B Area Block 16                    28953.383571   29259.260
Qayyumabad                                 25945.973571   29123.760
Gulshan-e-Iqbal Block 21                   26701.511538   28888.890
Phase 2                                    29154.447308   28888.890
Phase 5 Extension                          27313.225714   28888.890
Gulistan-e-Jauhar Block 3                  28506.883448   28819.445
Gulshan-e-Iqbal Block 13                   27001.589167   28819.445
Federal B Area Block 19                    27450.098824   28703.700
Shahra-E-Qaideen                           30056.585000   28584.875
Gulshan-e-Iqbal Block 9                    28449.622353   28571.430
Clifton Block 7                            32823.519250   28570.240
Clifton Block 9                            28212.313152   28115.160
Bahadurabad                                33069.563621   28007.320
Gulshan-e-Iqbal Block 6                    28175.926034   27777.780
Naya Nazimabad Block M                     27415.459565   27777.780
Naya Nazimabad Block B                     27499.224528   27777.780
Frere Town                                 27332.730698   27777.780
Clifton Block 5                            31992.443824   27402.405
Askari 4                                   28011.052812   27386.485
Khalid Bin Walid Road                      28819.847686   27126.740
Clifton_Unspecified                        27539.972692   27012.190
Gulshan-e-Iqbal Block 3                    24260.415500   26620.370
Falcon Complex New Malir                   26434.796971   26444.440
Sector 36-A                                21636.350722   26388.890
North Karachi Sector 9                     25371.197917   25925.930
Sector 48-A                                25705.129231   25925.930
Garden East                                26686.062581   25905.120
Phase 5                                    26879.839373   25555.560
Buffer Zone                                25203.380316   25347.220
Cosmopolitan Society                       25928.497059   25025.030
Federal B Area Block 13                    25197.346923   25000.000
Sector 17-A                                22778.703158   25000.000
Model Colony                               23029.013673   25000.000
Federal B Area_Unspecified                 25100.763167   25000.000
Saima Projects                             23963.786757   25000.000
Punjabi Saudagar Society                   22428.679252   24768.520
North Nazimabad Block I                    24482.494118   24765.510
Askari 6                                   21550.447204   24518.515
Muslimabad Society                         24239.728333   24451.100
Gulistan-e-Jauhar Block 4                  22134.012000   24305.560
Gulshan-e-Iqbal Block 13D                  25216.170556   24189.815
Sharfabad                                  30995.755330   23882.850
Clifton Block 3                            24178.152727   23611.110
North Nazimabad Block A                    21716.078889   23611.110
North Karachi Sector 8                     23240.740714   23564.815
Gulistan-e-Jauhar Block 2                  22792.427447   23541.665
Dhoraji Colony                             27219.763036   23286.760
Tariq Road                                 25161.987143   23286.760
Amil Colony                                26005.766333   23178.175
Saima Luxury Belt                          22026.515152   23148.150
Shadman                                    20795.383256   23148.150
North Nazimabad Block L                    23839.112308   23003.470
Gulshan-e-Iqbal Block 7                    23855.558778   22824.075
Clifton Block 2                            23288.310870   22772.770
Gulistan-e-Jauhar Block 1                  22283.323250   22671.295
Cp Barar Society, Gulshan-E-Iqbal Town     28945.019231   22435.900
Sector 20-A                                21877.104091   22314.815
Gulistan-e-Jauhar Block 12                 21379.160571   22222.220
Meerut Society                             20966.156842   22222.220
Sector 35-A                                20506.021672   22222.220
Phase 1                                    24204.829375   22222.220
Federal B Area Block 10                    22653.466308   22222.220
Gulistan-e-Jauhar Block 9                  21367.029333   22222.220
Gulshan-e-Iqbal Block 16                   24053.165217   22159.800
North Nazimabad Block N                    24146.669027   22065.730
Federal B Area Block 11                    23568.123214   21990.740
Gulshan-e-Iqbal Block 14                   21035.945000   21669.135
North Nazimabad Block D                    22614.076818   21566.790
Gulshan-e-Iqbal Block 10                   21231.206957   21527.780
Soldier Bazar                              21031.967500   21370.465
Parsi Colony                               21540.700000   21342.405
Gulistan-e-Jauhar Block 15                 22142.009948   21145.710
Gulshan-e-Iqbal Block 4                    21110.256000   21111.110
Gulistan-e-Jauhar Block 14                 20729.257333   21064.815
Federal B Area Block 20                    24077.778000   21064.815
North Nazimabad Block J                    21023.204000   20833.330
Sector 51-A                                19415.944468   20833.330
Clifton Block 4                            25902.018235   20656.660
Sector 24-A                                19703.764667   20370.370
North Nazimabad Block H                    22899.520492   19998.255
Sector 52-A                                20006.625357   19675.925
Federal B Area Block 21                    19898.507857   19569.545
Oasis Park Residencia                      20617.283333   19444.440
Gulshan-e-Iqbal Block 10A                  20045.656103   19352.090
Gulistan-e-Jauhar Block 16A                27049.465909   19184.915
Sector 22-A                                20398.053889   19166.665
Gulshan-e-Iqbal Block 2                    22948.061038   19106.410
Clifton Block 1                            19854.857386   18940.480
North Nazimabad Block F                    20798.648324   18726.590
Gulistan-e-Jauhar Block 8                  17675.687143   18518.520
North Nazimabad Block B                    18802.449877   18257.690
Sector 47                                  18239.322269   18055.560
Defence View                               19242.855106   17450.140
North Nazimabad_Unspecified                19902.071250   17388.445
Naya Nazimabad_Unspecified                 22413.808106   17377.570
Gulshan-e-Iqbal Town_Unspecified           23935.173032   17357.210
Malir Cantt_Unspecified                    22029.618947   17298.740
Askari 5                                   19391.405170   17186.250
Jamshed Road                               16543.917333   17125.475
Phase 2 Extension                          20490.503529   16778.630
Sector 15-A                                18738.940659   16666.670
North Karachi Sector 5                     15941.082857   16666.670
Precinct 18                                16444.448000   16666.670
Saadi Garden                               17535.141953   16203.700
Sector 19-A                                17916.914516   16003.320
Sector 43-A                                15958.471042   15871.915
Gulistan-e-Jauhar Block 16                 17124.077162   15640.605
Gulshan-e-Iqbal Block 13C                  19558.593462   15580.525
Gulistan-e-Jauhar Block 3A                 17691.691382   15579.070
Shahrah-E-Pakistan                         16826.200000   15517.185
North Karachi Sector 7                     15949.308889   15416.670
Nazimabad 4                                15346.447917   15323.850
North Karachi Sector 11                    16612.977000   15123.455
Karachi Administration Employees Society   19550.745727   15046.300
Gulshan-e-Iqbal Block 13A                  16224.086410   15046.300
Saddar Core                                15431.911818   15015.020
Federal B Area Block 9                     18240.127368   15000.000
Gulistan-e-Jauhar_Unspecified              17352.479300   14957.120
Gulshan-e-Iqbal Block 1                    17347.456528   14921.480
Nazimabad 2                                16072.148750   14822.800
Gulistan-e-Jauhar Block 5                  16971.554231   14767.330
Airport                                    15286.482615   14722.220
Gulistan-e-Jauhar Block 19                 18028.407671   14675.050
Gulistan-e-Jauhar Block 7                  17011.343440   14619.880
Sector 40                                  14792.296180   14464.460
Precinct 8                                 14767.340267   14444.440
Precinct 1                                 14478.670000   14370.915
Gulshan-e-Usman Housing Society            14842.064118   14351.850
DHA City                                   14428.505370   14076.575
Sector 45-A                                15698.759000   13993.320
Gulshan-e-Iqbal Block 13B                  14481.838333   13972.615
Federal B Area Block 8                     18142.017222   13813.810
Malir_Unspecified                          16511.264000   13777.780
Gulshan-E-Maymar                           14052.675136   13777.780
Garden West                                13954.672500   13722.830
Gulshan-e-Iqbal Block 13D2                 16938.680270   13676.310
Precinct 2                                 13454.477174   13567.250
Nazimabad 1                                18574.888462   13532.760
Sector 29                                  14219.747972   13420.720
Sector 34-A                                15507.507280   13366.750
Precinct 9                                 14244.391296   13333.330
Precinct 7                                 14206.350000   13333.330
Gulistan-e-Jauhar Block 11                 12957.504828   13295.350
Sector 16-A                                16991.007064   13205.830
North Nazimabad Block M                    12668.014808   13033.525
Super Highway_Unspecified                  12495.260000   12962.960
Precinct 6                                 13159.120000   12888.890
Precinct 12                                12392.569647   12888.890
Gulshan-e-Iqbal Block 11                   15642.140323   12637.100
Scheme 33_Unspecified                      14990.957550   12624.595
Gohar Green City Cluster                   14638.587317   12617.700
Sector 38-A                                12410.131538   12522.400
New Karachi                                13338.470000   12512.510
Falaknaz                                   12499.006471   12500.000
Sector 18-C                                12456.069600   12449.800
Gulistan-e-Jauhar Block 10                 12882.563250   12258.650
Precinct 4                                 12335.692703   12222.220
Malir Link To Super Highway                12770.399634   12222.220
Sector 18-A                                15604.164737   12165.240
Nazimabad 5                                16588.632222   12051.730
Kda Employees Society                      12609.183750   12037.040
Nazimabad 3                                19335.340476   12012.010
Sector 44                                  11876.852571   11695.910
Saima Villas                               11801.768696   11666.670
Sector 25-B                                12967.626944   11577.445
Gulistan-e-Jauhar Block 13                 14214.183407   11310.710
Precinct 16                                11534.227333   11213.085
Sector 42-A                                11466.365172   11168.380
Safoora Goth                               12474.023750   11126.735
Precinct 17                                12271.203158   11111.110
Precinct 10A                               11163.280653   11111.110
Sector 30                                  11319.040000   11024.310
Gulshan-e-Iqbal Block 13D3                 14219.276250   11020.035
Memon Goth                                 11203.811837   10925.930
Saadi Road                                 10984.146154   10893.740
Sector 17-B                                11236.612632   10875.960
Precinct 11A                               10896.332759   10789.470
Surjani Town                               10789.909856   10763.890
Precinct 11B                               10805.677645   10633.045
Precinct 15                                10771.242353   10488.890
Federal B Area Block 7                     11755.921818   10416.670
Bahria Paradise                            10259.921250   10222.220
Precinct 10B                                9988.959524   10133.330
North Nazimabad Block K                    10340.272143    9987.520
North Nazimabad Block G                    10910.444286    9958.070
Bahria Town_Unspecified                    10188.495370    9836.170
Gulistan-e-Jauhar Block 20                 17589.979091    9722.220
Gizri                                       9449.493810    8925.320
Jamia Millia Road                          12191.995000    8541.665
Gulistan-e-Jauhar Block 18                  9150.374173    8492.570
Precinct 19                                 8875.400000    8467.505
Bahria Apartments                           8129.568514    8176.100
Shah Faisal_Unspecified                    12664.157857    8143.275
Sector 24-B                                 8039.671000    7980.545
North Karachi_Unspecified                  11477.843696    7864.575
Green Town / Rafah-E-Aam Belt              12207.311667    7853.640
Mehmoodabad                                10103.827778    7777.780
Gulistan-e-Jauhar Block 17                 11488.290192    7652.920
Precinct 27                                 7939.784750    7565.010
Precinct 31                                 7334.450556    7328.610
Shamsi / Al-Falah Belt                      8333.752308    7222.220
Bahria Heights                              6746.412340    7103.830
Korangi Industrial Area                     9155.507895    6913.580
Malir Town Residency                        8298.036364    6712.960
Private High-Rises                          6753.617286    6410.260
Bahria Sports City                          6476.530319    6349.210
Golden Town                                 6762.323125    6166.785
Allahwala Town                              5560.094242    5252.530

In [95]:
df.groupby('sub_location_score')['price_crore'].median()

sub_location_score
1     0.95
2     2.15
3     4.85
4     8.20
5    11.00
Name: price_crore, dtype: float64

In [98]:
df['sub_location_score'].value_counts()

sub_location_score
2    7464
3    6327
5    2899
4    2421
1    1220
Name: count, dtype: int64

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20331 entries, 0 to 20457
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       20331 non-null  object
 1   address             20331 non-null  object
 2   location            20331 non-null  object
 3   sub_location        20331 non-null  object
 4   price               20331 non-null  float64
 5   price_crore         20331 non-null  float64
 6   price_per_sqft      20331 non-null  float64
 7   area                20331 non-null  float64
 8   bedrooms            20331 non-null  int64
 9   bathrooms           20331 non-null  int64
 10  kitchen             20331 non-null  float64
 11  floor               3982 non-null   float64
 12  total_floors        9517 non-null   float64
 13  parking             20331 non-null  float64
 14  elevator            20331 non-null  int64
 15  servant_quarters    20331 non-null  float64
 16  electricity_backup  20331 non-null  int64
 17  furnished           20331 non-null  int64
 18  completion_year     10758 non-null  float64
 19  property_type       20331 non-null  object
 20  property_age        10758 non-null  float64
 21  age_category        10758 non-null  object
 22  parking_score       20331 non-null  int64
 23  area_per_bedroom    20331 non-null  float64
 24  district            20331 non-null  object
 25  sub_location_type   20331 non-null  object
 26  location_score      20331 non-null  int64
 27  sub_location_score  20331 non-null  int64
dtypes: float64(12), int64(8), object(8)
memory usage: 4.5+ MB

In [100]:
df.to_csv('karachi_properties_handle_missing_value-2.csv',index=False)