In [143]:
import pandas as pd
import numpy as np

In [144]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [145]:
df=pd.read_csv('raw_house_data.csv')

In [146]:
df.head()

,property_name,link,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,https://www.zameen.com/Property/bahria_town_pr...,"Bahria Town - Ali Block, Bahria Town - Precinc...","Bahria Town Karachi, Karachi, Sindh",1.45 Crore,125 Sq. Yd.,3,3,1,2.0,1,0,1,1,1,2025.0
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,https://www.zameen.com/Property/bahria_town_ka...,"Bahria Paradise, Bahria Town Karachi","Bahria Town Karachi, Karachi, Sindh",4.6 Crore,500 Sq. Yd.,5,5,2,NaN,1,0,1,1,0,NaN
2,Prime Location 250 Square Yards Modern Design ...,https://www.zameen.com/Property/bahria_town_ka...,"Bahria Town - Precinct 1, Bahria Town Karachi","Bahria Town Karachi, Karachi, Sindh",2.9 Crore,250 Sq. Yd.,5,5,1,NaN,1,0,1,1,0,2025.0
3,Construct Your 272 Sq. Yds Dream House on Easy...,https://www.zameen.com/Property/bahria_town_ka...,"Bahria Town - Precinct 6, Bahria Town Karachi","Bahria Town Karachi, Karachi, Sindh",2.4 Crore,250 Sq. Yd.,5,5,1,NaN,1,0,1,1,0,NaN
4,Bungalow for Sale 1000 Square yards in DHA pha...,https://www.zameen.com/Property/dha_defence_dh...,"DHA Phase 6, DHA Defence","DHA Defence, Karachi, Sindh",45 Crore,"1,000 Sq. Yd.",6,7,0,2.0,4,0,0,1,0,2024.0

In [147]:
df.shape

(11982, 16)

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11982 entries, 0 to 11981
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11982 non-null  object
 1   link                11982 non-null  object
 2   address             11982 non-null  object
 3   location            11982 non-null  object
 4   price               11982 non-null  object
 5   area                11982 non-null  object
 6   bedrooms            11982 non-null  object
 7   bathrooms           11982 non-null  object
 8   kitchen             11982 non-null  int64
 9   total_floors        4707 non-null   float64
 10  parking             11982 non-null  int64
 11  elevator            11982 non-null  int64
 12  servant_quarters    11982 non-null  int64
 13  electricity_backup  11982 non-null  int64
 14  furnished           11982 non-null  int64
 15  built_year          5664 non-null   float64
dtypes: float64(2), int64(6), object(8)
memory usage: 1.5+ MB

In [149]:
df.duplicated().sum()

np.int64(0)

In [150]:
df.isnull().sum()

property_name            0
link                     0
address                  0
location                 0
price                    0
area                     0
bedrooms                 0
bathrooms                0
kitchen                  0
total_floors          7275
parking                  0
elevator                 0
servant_quarters         0
electricity_backup       0
furnished                0
built_year            6318
dtype: int64

In [151]:
df.drop(columns='link',inplace=True)

In [152]:
#location
df['location'].value_counts()

location
DHA Defence, Karachi, Sindh                                        2348
Scheme 33, Karachi, Sindh                                          1466
Bahria Town Karachi, Karachi, Sindh                                1436
Gulshan-e-Iqbal Town, Karachi, Sindh                                916
Gulistan-e-Jauhar, Karachi, Sindh                                   782
Cantt, Karachi, Sindh                                               755
Malir, Karachi, Sindh                                               743
Naya Nazimabad, Karachi, Sindh                                      572
Gadap Town, Karachi, Sindh                                          569
North Nazimabad, Karachi, Sindh                                     511
Federal B Area, Karachi, Sindh                                      417
North Karachi, Karachi, Sindh                                       276
Jamshed Town, Karachi, Sindh                                        248
Navy Housing Scheme Karsaz, Karachi, Sindh                          109
Clifton, Karachi, Sindh                                              77
Karachi Motorway, Karachi, Sindh                                     75
KDA Scheme 1, Karachi, Sindh                                         61
DHA City Karachi, Karachi, Sindh                                     46
Korangi, Karachi, Sindh                                              35
Amir Khusro, Karachi, Sindh                                          33
Saima Luxury Homes, Karachi, Sindh                                   32
Northern Bypass, Karachi, Sindh                                      32
Shaheed Millat Road, Karachi, Sindh                                  24
Hill Park, Karachi, Sindh                                            24
Nazimabad, Karachi, Sindh                                            23
Shah Faisal Town, Karachi, Sindh                                     21
Falcon Complex Faisal, Karachi, Sindh                                18
Zamzama, Karachi, Sindh                                              17
KN Gohar Green City, Karachi, Sindh                                  17
Cotton Export Cooperative Housing Society, Karachi, Sindh            16
Bath Island, Karachi, Sindh                                          16
Chapal Uptown, Karachi, Sindh                                        16
Defence View Society, Karachi, Sindh                                 14
Tipu Sultan Road, Karachi, Sindh                                     14
KDA Scheme 1 Extension, Karachi, Sindh                               13
University Road, Karachi, Sindh                                      12
Airport Road, Karachi, Sindh                                         12
Bin Qasim Town, Karachi, Sindh                                       12
Yousaf Goth, Karachi, Sindh                                          11
Gulshan-e-Usman Housing Society, Karachi, Sindh                      10
Darul Aman Society, Karachi, Sindh                                   10
Naval Colony, Karachi, Sindh                                          9
Pak Ideal Cooperative Housing Society, Karachi, Sindh                 7
Abul Hassan Isphani Road, Karachi, Sindh                              7
Oasis Park Residencia, Karachi, Sindh                                 6
Shahra-e-Faisal, Karachi, Sindh                                       5
Metrovil Colony, Karachi, Sindh                                       5
Siraj-ud-Daula Road, Karachi, Sindh                                   5
Khalid Bin Walid Road, Karachi, Sindh                                 5
Orangi Town, Karachi, Sindh                                           5
Khayaban-e-Ittehad Road, Karachi, Sindh                               5
APP Employees Co-operative Housing Society, Karachi, Sindh            5
Gulberg Town, Karachi, Sindh                                          5
New Karachi, Karachi, Sindh                                           5
Sindh Industrial Trading Estate (SITE), Karachi, Sindh                4
Liaquatabad, Karachi, Sindh                                           4
Qayyumabad, Karachi, Sindh                                            4
Jinnah Avenue, Karachi, Sindh                                         4
Manzoor Colony, Karachi, Sindh                                        4
Kamran Chowrangi, Karachi, Sindh                                      3
Scheme 45, Karachi, Sindh                                             3
Malir Link To Super Highway, Karachi, Sindh                           3
Rufi Rose Petals, Karachi, Sindh                                      3
Muhammad Bin Qasim Co-operative Housing Society, Karachi, Sindh       2
Baldia Town, Karachi, Sindh                                           2
Dr Daud Pota Road, Karachi, Sindh                                     2
Kemari Town, Karachi, Sindh                                           2
Saadi Road, Karachi, Sindh                                            2
Abid Town, Karachi, Sindh                                             2
Al-Hilal Society, Karachi, Sindh                                      2
Old Ravians Co-Operative Housing Society, Karachi, Sindh              1
Surti Muslim Co-Operative Housing Society, Karachi, Sindh             1
Gulshan-e-Umair, Karachi, Sindh                                       1
Old Clifton, Karachi, Sindh                                           1
Khokan Cooperative Housing Society, Karachi, Sindh                    1
Punjab Colony, Karachi, Sindh                                         1
Garden West, Karachi, Sindh                                           1
Gulistan-e-Malir, Karachi, Sindh                                      1
Super Highway, Karachi, Sindh                                         1
Mangopir, Karachi, Sindh                                              1
Shahrah-e-Pakistan, Karachi, Sindh                                    1
Numaish Chowrangi, Karachi, Sindh                                     1
Hub River Road, Karachi, Sindh                                        1
Gizri, Karachi, Sindh                                                 1
Amil Colony, Karachi, Sindh                                           1
PIB Colony, Karachi, Sindh                                            1
Landhi, Karachi, Sindh                                                1
Chapal Courtyard, Karachi, Sindh                                      1
Civil Lines, Karachi, Sindh                                           1
Airport, Karachi, Sindh                                               1
Saddar Town, Karachi, Sindh                                           1
Shahra-e-Qaideen, Karachi, Sindh                                      1
Kashmir Road, Karachi, Sindh                                          1
Name: count, dtype: int64

In [153]:
df['location']=df['location'].str.split(',').str.get(0).str.lower()

In [154]:
#area
df['area']=df['area'].str.split().str.get(0).str.replace(',', '').astype(float)*9

In [155]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,"Bahria Town - Ali Block, Bahria Town - Precinc...",bahria town karachi,1.45 Crore,1125.0,3,3,1,2.0,1,0,1,1,1,2025.0
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,"Bahria Paradise, Bahria Town Karachi",bahria town karachi,4.6 Crore,4500.0,5,5,2,NaN,1,0,1,1,0,NaN
2,Prime Location 250 Square Yards Modern Design ...,"Bahria Town - Precinct 1, Bahria Town Karachi",bahria town karachi,2.9 Crore,2250.0,5,5,1,NaN,1,0,1,1,0,2025.0
3,Construct Your 272 Sq. Yds Dream House on Easy...,"Bahria Town - Precinct 6, Bahria Town Karachi",bahria town karachi,2.4 Crore,2250.0,5,5,1,NaN,1,0,1,1,0,NaN
4,Bungalow for Sale 1000 Square yards in DHA pha...,"DHA Phase 6, DHA Defence",dha defence,45 Crore,9000.0,6,7,0,2.0,4,0,0,1,0,2024.0

In [156]:
#price
def convert_price(price):
    if pd.isna(price):
        return None

    price = str(price).replace(",", "").strip().lower()

    if "arab" in price:
        return float(price.replace("arab", "").strip()) * 1_000_000_000

    elif "crore" in price:
        return float(price.replace("crore", "").strip()) * 10_000_000

    elif "lakh" in price:
        return float(price.replace("lakh", "").strip()) * 100_000

    else:
        return float(price)

df['price']=df['price'].apply(convert_price)

In [110]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,"Bahria Town - Ali Block, Bahria Town - Precinc...",bahria town karachi,14500000.0,1125.0,3,3,1,2.0,1,0,1,1,1,2025.0
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,"Bahria Paradise, Bahria Town Karachi",bahria town karachi,46000000.0,4500.0,5,5,2,NaN,1,0,1,1,0,NaN
2,Prime Location 250 Square Yards Modern Design ...,"Bahria Town - Precinct 1, Bahria Town Karachi",bahria town karachi,29000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,2025.0
3,Construct Your 272 Sq. Yds Dream House on Easy...,"Bahria Town - Precinct 6, Bahria Town Karachi",bahria town karachi,24000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,NaN
4,Bungalow for Sale 1000 Square yards in DHA pha...,"DHA Phase 6, DHA Defence",dha defence,450000000.0,9000.0,6,7,0,2.0,4,0,0,1,0,2024.0

In [157]:
df[df['built_year'] > 2026]['built_year'].value_counts()

built_year
2027.0    27
2028.0    20
2029.0    15
2030.0     6
2222.0     3
3025.0     2
2826.0     1
3024.0     1
Name: count, dtype: int64

In [158]:
df.rename(columns={'built_year':'completion_year'},inplace=True)

In [159]:
df['completion_year'].value_counts()

completion_year
2025.0    1189
2026.0    1138
2024.0     705
2023.0     415
2022.0     304
2020.0     283
2015.0     207
2000.0     172
2018.0     158
2021.0     157
2010.0     144
2019.0      94
2005.0      79
2016.0      72
2012.0      65
2017.0      58
2014.0      40
2013.0      39
2008.0      38
1990.0      33
2027.0      27
2011.0      25
2028.0      20
2006.0      19
2009.0      18
1999.0      17
2029.0      15
2002.0      13
1995.0      12
2007.0      12
2004.0      11
2001.0      11
1980.0       7
1985.0       6
2030.0       6
2003.0       6
1988.0       6
1994.0       5
1996.0       5
1970.0       4
1998.0       4
2222.0       3
3025.0       2
1989.0       2
1997.0       2
1992.0       1
2826.0       1
1960.0       1
201.0        1
1972.0       1
1880.0       1
1918.0       1
1975.0       1
0.0          1
3024.0       1
1979.0       1
1993.0       1
1968.0       1
1976.0       1
1850.0       1
1965.0       1
Name: count, dtype: int64

In [160]:

df.loc[(df["completion_year"] < 1900) | (df["completion_year"] > 2100),"completion_year"]=np.nan

In [161]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,"Bahria Town - Ali Block, Bahria Town - Precinc...",bahria town karachi,14500000.0,1125.0,3,3,1,2.0,1,0,1,1,1,2025.0
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,"Bahria Paradise, Bahria Town Karachi",bahria town karachi,46000000.0,4500.0,5,5,2,NaN,1,0,1,1,0,NaN
2,Prime Location 250 Square Yards Modern Design ...,"Bahria Town - Precinct 1, Bahria Town Karachi",bahria town karachi,29000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,2025.0
3,Construct Your 272 Sq. Yds Dream House on Easy...,"Bahria Town - Precinct 6, Bahria Town Karachi",bahria town karachi,24000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,NaN
4,Bungalow for Sale 1000 Square yards in DHA pha...,"DHA Phase 6, DHA Defence",dha defence,450000000.0,9000.0,6,7,0,2.0,4,0,0,1,0,2024.0

In [162]:
#bedroom and bathroom
idx=df[(df['bedrooms']=='-') | (df['bedrooms'].isna())].index
df.drop(index=idx,inplace=True)

In [163]:
df.drop(index=df[(df['bathrooms']=='-')].index,inplace=True)

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11221 entries, 0 to 11981
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11221 non-null  object
 1   address             11221 non-null  object
 2   location            11221 non-null  object
 3   price               11221 non-null  float64
 4   area                11221 non-null  float64
 5   bedrooms            11221 non-null  object
 6   bathrooms           11221 non-null  object
 7   kitchen             11221 non-null  int64
 8   total_floors        4524 non-null   float64
 9   parking             11221 non-null  int64
 10  elevator            11221 non-null  int64
 11  servant_quarters    11221 non-null  int64
 12  electricity_backup  11221 non-null  int64
 13  furnished           11221 non-null  int64
 14  completion_year     5396 non-null   float64
dtypes: float64(4), int64(6), object(5)
memory usage: 1.4+ MB

In [165]:
df['bedrooms']=df['bedrooms'].astype('int64')
df['bathrooms']=df['bathrooms'].astype('int64')

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11221 entries, 0 to 11981
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11221 non-null  object
 1   address             11221 non-null  object
 2   location            11221 non-null  object
 3   price               11221 non-null  float64
 4   area                11221 non-null  float64
 5   bedrooms            11221 non-null  int64
 6   bathrooms           11221 non-null  int64
 7   kitchen             11221 non-null  int64
 8   total_floors        4524 non-null   float64
 9   parking             11221 non-null  int64
 10  elevator            11221 non-null  int64
 11  servant_quarters    11221 non-null  int64
 12  electricity_backup  11221 non-null  int64
 13  furnished           11221 non-null  int64
 14  completion_year     5396 non-null   float64
dtypes: float64(4), int64(8), object(3)
memory usage: 1.4+ MB

In [167]:
#address
df['address'].value_counts()

address
DHA Phase 8, DHA Defence                                                                      657
DHA Phase 6, DHA Defence                                                                      550
Falcon Complex New Malir, Malir                                                               515
Askari 6, Malir Cantonment                                                                    382
DHA Phase 5, DHA Defence                                                                      242
Naya Nazimabad, Karachi                                                                       226
DHA Phase 7, DHA Defence                                                                      219
Capital Cooperative Housing Society, Scheme 33 - Sector 35-A                                  179
Saadi Town, Scheme 33                                                                         149
DHA Phase 4, DHA Defence                                                                      145
DHA Phase 7 Extension, DHA Defence                                                            112
Bahria Town - Ali Block, Bahria Town - Precinct 12                                            109
Bahria Sports City, Bahria Town Karachi                                                       108
Bahria Town - Precinct 8, Bahria Town Karachi                                                  94
Bahria Town - Precinct 10-A, Bahria Town Karachi                                               91
Gulistan-e-Jauhar - Block 15, Gulistan-e-Jauhar                                                90
Naya Nazimabad - Block A, Naya Nazimabad                                                       90
Naya Nazimabad - Block C, Naya Nazimabad                                                       87
Saadi Garden, Scheme 33                                                                        84
Bahria Town - Precinct 11-A, Bahria Town - Precinct 11                                         83
Gulistan-e-Jauhar - Block 14, Gulistan-e-Jauhar                                                83
Bahria Town - Precinct 31, Bahria Town Karachi                                                 82
Askari 5 - Sector J, Askari 5                                                                  81
Model Colony - Malir, Malir                                                                    80
Gulshan-e-Iqbal - Block 5, Gulshan-e-Iqbal                                                     78
Gulistan-e-Jauhar - Block 12, Gulistan-e-Jauhar                                                77
North Nazimabad - Block N, North Nazimabad                                                     76
Gulistan-e-Jauhar, Karachi                                                                     75
Bahria Town - Precinct 11-B, Bahria Town - Precinct 11                                         74
Saima Villas, Karachi Motorway                                                                 72
Bahria Town - Quaid Villas, Bahria Town - Precinct 2                                           72
Bahria Town - Precinct 1, Bahria Town Karachi                                                  69
Bahria Town - Precinct 10-B, Bahria Town Karachi                                               68
North Nazimabad - Block L, North Nazimabad                                                     67
Gulistan-e-Jauhar - Block 2, Gulistan-e-Jauhar                                                 67
Naya Nazimabad - Block D, Naya Nazimabad                                                       67
North Town Residency, Surjani Town                                                             67
PECHS Block 6, PECHS                                                                           65
DHA Phase 8 - Zone A, DHA Phase 8                                                              64
Saima Arabian Villas, Gadap Town                                                               63
Naya Nazimabad - Block B, Naya Nazimabad                                                       63
Bahria Town - Precinct 6, Bahria Town Karachi                                                  63
Askari 5 - Sector H, Askari 5                                                                  62
PECHS Block 2, PECHS                                                                           62
Bahria Town - Precinct 27, Bahria Town Karachi                                                 61
Bahria Homes - Iqbal Villas, Bahria Town - Precinct 2                                          60
Gulshan-e-Maymar, Gadap Town                                                                   60
KDA Scheme 1, Karachi                                                                          58
Gulshan-e-Iqbal - Block 7, Gulshan-e-Iqbal                                                     58
North Nazimabad - Block H, North Nazimabad                                                     56
North Nazimabad - Block F, North Nazimabad                                                     56
Gulshan-e-Iqbal - Block 13/D-1, Gulshan-e-Iqbal                                                56
Bahria Hills, Bahria Town Karachi                                                              54
Hansa Society, Scheme 33                                                                       53
Federal B Area - Block 12, Federal B Area                                                      53
Gulistan-e-Jauhar - Block 3, Gulistan-e-Jauhar                                                 52
Gulistan-e-Jauhar - Block 7, Gulistan-e-Jauhar                                                 51
DOHS Phase 1, Malir Cantonment                                                                 51
Meerut Society, Scheme 33                                                                      50
Scheme 33, Karachi                                                                             50
Bahria Town - Precinct 4, Bahria Town Karachi                                                  48
Gulshan-e-Iqbal - Block 4, Gulshan-e-Iqbal                                                     47
Gulshan-e-Maymar - Sector R, Gulshan-e-Maymar                                                  46
Gulshan-e-Iqbal - Block 6, Gulshan-e-Iqbal                                                     46
Gulshan-e-Iqbal - Block 13/D, Gulshan-e-Iqbal                                                  45
Navy Housing Scheme Karsaz, Karachi                                                            44
Bahria Town Karachi, Karachi                                                                   43
DHA Phase 1, DHA Defence                                                                       43
DHA Phase 2, DHA Defence                                                                       43
KDA Officers Society, Gulshan-e-Iqbal Town                                                     42
Gulshan-e-Iqbal - Block 2, Gulshan-e-Iqbal                                                     41
Federal B Area - Block 10, Federal B Area                                                      41
Bahria Paradise - Precinct 51, Bahria Paradise                                                 40
Gulshan-e-Maymar - Sector T, Gulshan-e-Maymar                                                  39
Gulshan-e-Iqbal, Gulshan-e-Iqbal Town                                                          38
Falaknaz Dreams, Malir                                                                         38
Saima Elite Villas, Malir                                                                      37
Bahria Town - Precinct 16, Bahria Town Karachi                                                 37
Gulshan-e-Iqbal - Block 10-A, Gulshan-e-Iqbal                                                  37
Saadi Town - Block 5, Saadi Town                                                               37
State Bank of Pakistan Housing Society, Scheme 33 - Sector 17-A                                36
Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33 - Sector 31                               36
Bahria Paradise, Bahria Town Karachi                                                           36
North Nazimabad - Block D, North Nazimabad                                                     34
Gulistan-e-Jauhar - Block 19, Gulistan-e-Jauhar                                                34
Sector 25-A - Punjabi Saudagar Multi Purpose Society, Scheme 33 - Sector 25-A                  33
Federal B Area - Block 13, Federal B Area                                                      33
Gulshan-e-Roomi, Faisal Cantonment                                                             32
North Nazimabad - Block I, North Nazimabad                                                     32
North Nazimabad - Block J, North Nazimabad                                                     32
Saadi Garden - Block 5, Saadi Garden                                                           32
Gulshan-e-Maymar - Sector Q, Gulshan-e-Maymar                                                  32
Saima Luxury Homes, Karachi                                                                    31
Amir Khusro, Karachi                                                                           31
North Nazimabad - Block B, North Nazimabad                                                     30
Federal B Area - Block 11, Federal B Area                                                      29
NHS Mauripur, Northern Bypass                                                                  29
Gulshan-e-Iqbal - Block 1, Gulshan-e-Iqbal                                                     29
Zeenatabad, Scheme 33                                                                          29
Saadi Garden - Block 1, Saadi Garden                                                           27
Gulshan-e-Maymar - Sector X, Gulshan-e-Maymar                                                  27
Bahadurabad, Gulshan-e-Iqbal Town                                                              27
DHA City Karachi, Karachi                                                                      27
Chapal Sun City, Scheme 33                                                                     27
DHA Phase 8 - Zone B, DHA Phase 8                                                              27
Gulshan-e-Iqbal - Block 3, Gulshan-e-Iqbal                                                     27
Gulshan-e-Maymar - Sector Y, Gulshan-e-Maymar                                                  26
Gwalior Cooperative Housing Society, Scheme 33                                                 26
North Nazimabad, Karachi                                                                       26
North Karachi - Sector 9, North Karachi                                                        25
Gulistan-e-Jauhar - Block 3-A, Gulistan-e-Jauhar                                               25
North Nazimabad - Block A, North Nazimabad                                                     25
Askari 5 - Sector G, Askari 5                                                                  24
Bahria Town - Precinct 17, Bahria Town Karachi                                                 24
Gulistan-e-Jauhar - Block 13, Gulistan-e-Jauhar                                                24
Saadi Town - Block 4, Saadi Town                                                               23
Gulistan-e-Jauhar - Block 17, Gulistan-e-Jauhar                                                23
Navy Housing Scheme Karsaz - Phase 3, Navy Housing Scheme Karsaz                               23
Naya Nazimabad - Block M, Naya Nazimabad                                                       23
Hill Park, Karachi                                                                             22
Gulshan-e-Iqbal - Block 13-D2, Gulshan-e-Iqbal                                                 22
Federal B Area, Karachi                                                                        22
Saadi Town - Block 7, Saadi Town                                                               22
Shadman Town - Sector-14/B, Shadman                                                            22
Gulshan-e-Maymar - Sector Z, Gulshan-e-Maymar                                                  22
Sadaf Cooperative Housing Society, Gulzar-e-Hijri                                              22
Bahria Town - Precinct 15, Bahria Town Karachi                                                 22
Federal B Area - Block 14, Federal B Area                                                      22
Bahria Town - Precinct 12, Bahria Town Karachi                                                 21
North Karachi - Sector 11B, North Karachi                                                      21
Musalmanan-E-Punjab Cooperative Housing Society, Scheme 33 - Sector 20-A                       21
Gulistan-e-Jauhar - Block 4, Gulistan-e-Jauhar                                                 20
Shaheed Millat Road, Karachi                                                                   20
Clifton - Block 8, Clifton                                                                     20
North Karachi - Sector 7-D3, North Karachi                                                     20
Gulistan-e-Jauhar - Block 1, Gulistan-e-Jauhar                                                 19
Sector 32 - Punjabi Saudagar City Phase 1, Scheme 33 - Sector 32                               19
North Karachi, Karachi                                                                         19
Bufferzone - Sector 15-A/2, Buffer Zone                                                        19
KN Gohar Green City, Karachi                                                                   17
Gulshan-e-Maymar - Sector W, Gulshan-e-Maymar                                                  17
Madras Cooperative Housing Society, Scheme 33 - Sector 17-A                                    17
Gulshan-e-Iqbal - Block 9, Gulshan-e-Iqbal                                                     17
Bufferzone - Sector 15-A/4, Buffer Zone                                                        17
Federal B Area - Block 15, Federal B Area                                                      17
Bahria Town - Precinct 35, Bahria Sports City                                                  17
Pilibhit Cooperative Housing Society, Scheme 33 - Sector 18-A                                  17
Chapal Uptown, Karachi                                                                         16
Gulshan-e-Iqbal Town, Karachi                                                                  16
Alize Garden, Gadap Town                                                                       16
Cotton Export Cooperative Housing Society, Karachi                                             16
Bath Island, Karachi                                                                           16
Federal B Area - Block 19, Federal B Area                                                      16
Gulshan-e-Iqbal - Block 19, Gulshan-e-Iqbal                                                    15
Punjabi Saudagar Society Phase 2, Scheme 33 - Sector 50                                        15
Navy Housing Scheme Karsaz - Phase 1, Navy Housing Scheme Karsaz                               15
Federal B Area - Block 16, Federal B Area                                                      15
SMCHS - Sindhi Muslim Society, Jamshed Town                                                    15
North Karachi - Sector 8, North Karachi                                                        14
Sindhi Muslim Society - Block A, SMCHS - Sindhi Muslim Society                                 14
Adamjee Nagar, Gulshan-e-Iqbal Town                                                            14
Bahria Town - Precinct 7, Bahria Town Karachi                                                  14
Bufferzone - Sector 15-A/1, Buffer Zone                                                        14
Falcon Complex Faisal, Karachi                                                                 14
Dawood Society, Gulshan-e-Iqbal Town                                                           13
Mohammad Ali Society, Gulshan-e-Iqbal Town                                                     13
Andaleeb Cooperative Housing Society, Scheme 33                                                13
Gulshan-e-Iqbal - Block 10, Gulshan-e-Iqbal                                                    13
PECHS Block 3, PECHS                                                                           13
Cantt Bazar, Malir Cantonment                                                                  13
DHA Phase 2 Extension, DHA Defence                                                             13
Navy Housing Scheme Karsaz - Phase 2, Navy Housing Scheme Karsaz                               13
Dhoraji Colony, Gulshan-e-Iqbal Town                                                           13
Clifton - Block 7, Clifton                                                                     12
Saadi Garden - Block 3, Saadi Garden                                                           12
Airport Road, Karachi                                                                          12
Saima Green Valley, Gadap Town                                                                 12
Gulistan-e-Jauhar - Block 16, Gulistan-e-Jauhar                                                12
Saadi Town - Block 3, Saadi Town                                                               12
North Karachi - Sector 10, North Karachi                                                       12
Pakistan Merchant Navy Society, Scheme 33 - Sector 15-A                                        12
North Karachi - Sector 11A, North Karachi                                                      12
KDA Scheme 1 Extension, Karachi                                                                11
Diamond City, Gulshan-e-Maymar                                                                 11
Al Muslim Society, Scheme 33 - Sector 34-A                                                     11
DOHS Phase 2, Malir Cantonment                                                                 11
DHA Phase 8 Extension, DHA Phase 8                                                             11
National Stadium Colony, Gulshan-e-Iqbal Town                                                  11
Bufferzone - Sector 15-A/3, Buffer Zone                                                        11
Shahnawaz Cooperative Housing Society, Scheme 33 - Sector 51-A                                 11
Clifton - Block 5, Clifton                                                                     11
Karachi University Housing Society, Scheme 33                                                  11
Gulshan-e-Iqbal - Block 4A, Gulshan-e-Iqbal                                                    11
Bahria Town - Precinct 2, Bahria Town Karachi                                                  11
Gulshan-e-Iqbal - Block 13/C, Gulshan-e-Iqbal                                                  11
Yousaf Goth, Karachi                                                                           11
DHA Phase 5 Extension, DHA Phase 5                                                             11
Navy Housing Scheme Zamzama, Zamzama                                                           10
Askari 5, Malir Cantonment                                                                     10
Askari 5 - Sector B, Askari 5                                                                  10
Sindhi Muslim Society - Block B, SMCHS - Sindhi Muslim Society                                 10
Federal B Area - Block 6, Federal B Area                                                       10
PECHS, Jamshed Town                                                                            10
Bahria Town - Precinct 9, Bahria Town Karachi                                                  10

In [168]:
df["address"] = df["address"].str.lower().str.strip()

In [169]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,"bahria town - ali block, bahria town - precinc...",bahria town karachi,14500000.0,1125.0,3,3,1,2.0,1,0,1,1,1,2025.0
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,"bahria paradise, bahria town karachi",bahria town karachi,46000000.0,4500.0,5,5,2,NaN,1,0,1,1,0,NaN
2,Prime Location 250 Square Yards Modern Design ...,"bahria town - precinct 1, bahria town karachi",bahria town karachi,29000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,2025.0
3,Construct Your 272 Sq. Yds Dream House on Easy...,"bahria town - precinct 6, bahria town karachi",bahria town karachi,24000000.0,2250.0,5,5,1,NaN,1,0,1,1,0,NaN
4,Bungalow for Sale 1000 Square yards in DHA pha...,"dha phase 6, dha defence",dha defence,450000000.0,9000.0,6,7,0,2.0,4,0,0,1,0,2024.0

In [170]:
#floor
df['total_floors'].value_counts()

total_floors
2.0       3145
1.0        820
3.0        504
4.0         23
5.0          6
32.0         4
12.0         3
8.0          3
38.0         3
28.0         3
9.0          2
14.0         2
40.0         2
25.0         1
6.0          1
4500.0       1
17.0         1
Name: count, dtype: int64

In [135]:
df[df['total_floors'] > 5 ]

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
319,ULTRA-LUXURY COASTAL LIVING: EXQUISITE 4-BEDRO...,"emaar pearl towers, emaar crescent bay",dha defence,160000000.0,2628.0,4,5,1,12.0,2,0,1,1,0,2021.0
550,Luxury 2 Bed Sea-Facing Apartment | The Trilli...,"the trillium, dha phase 5",dha defence,99700000.0,1881.0,2,3,1,32.0,1,0,1,1,1,2030.0
1636,Saadi Town House For Sale,"saadi town, scheme 33",scheme 33,17500000.0,1080.0,4,5,3,9.0,1,0,1,0,1,2026.0
2925,400 Sq Yard House For Sale In Gulshan E Iqbal ...,"gulshan-e-iqbal, gulshan-e-iqbal town",gulshan-e-iqbal town,64500000.0,3600.0,3,3,1,8.0,5,0,2,1,1,2025.0
3451,BEAUTIFUL BRAND NEW 80 SQ YARDS G+1 HOUSE FOR ...,"north town residency, surjani town",gadap town,13500000.0,720.0,4,3,1,14.0,1,0,0,1,1,2026.0
3557,80 Square Yard Fully Furnished House Available...,"diamond city, gulshan-e-maymar",gadap town,12000000.0,720.0,2,3,1,38.0,2,0,0,1,0,2029.0
4731,DOHS 1 HOUSE FOR SALE MALIR CANTT,"dohs phase 1, malir cantonment",cantt,124500000.0,4950.0,4,5,1,14.0,4,0,1,1,1,2024.0
5137,House Available For Sale Brand New 160 Square ...,"naya nazimabad, karachi",naya nazimabad,56000000.0,1440.0,5,5,1,32.0,1,0,1,1,1,2025.0
5591,Ground Plus One Storey House Is Available For ...,"federal b area - block 11, federal b area",federal b area,120000000.0,5400.0,5,6,2,32.0,1,0,1,1,1,2025.0
5595,Ground Plus One House For Sale,"federal b area - block 11, federal b area",federal b area,120000000.0,5400.0,5,6,2,32.0,1,0,1,1,1,2025.0
6056,2000 Sq Ft Sea Facing Apartment For Sale | Sai...,"hmr waterfront, dha phase 8",dha defence,80000000.0,1944.0,2,3,2,40.0,2,0,1,1,0,2028.0
6117,2300 Square Feet House For sale In Rs. 6750000...,"askari 4, gulistan-e-jauhar",gulistan-e-jauhar,67500000.0,2304.0,3,3,2,8.0,3,0,1,1,0,NaN
6244,Last Unit Available on Higher Floor with Chanc...,"emaar panorama, dha phase 8",dha defence,64300000.0,1377.0,1,1,1,28.0,1,0,1,1,0,2026.0
7124,Looking For A House In Lakhani Park Vista Karachi,"lakhani park vista, gulshan-e-maymar",gadap town,13000000.0,1197.0,2,2,1,12.0,1,0,1,1,1,2024.0
7728,Saima Defence Mall & Residency House For Sale,"china gold park mall & residency, khayaban-e-i...",khayaban-e-ittehad road,62500000.0,1800.0,3,3,1,12.0,2,0,0,1,0,2025.0
7736,Luxury 1 Bed with Oversized Balcony & Pool | G...,"hmr waterfront, dha phase 8",dha defence,42800000.0,1098.0,1,2,1,38.0,1,0,1,1,1,2029.0
8337,"Ultra-Luxury 4 Bedroom Sky Villa (5,836 Sqft) ...","emaar ocean front, dha phase 8",dha defence,270000000.0,5832.0,4,6,2,40.0,3,0,1,1,1,2028.0
9014,Corner 120 Square Yard Bungalow Available In S...,"saadi town, scheme 33",scheme 33,26500000.0,1080.0,4,5,2,25.0,1,0,2,1,1,2020.0
9538,Chance Deal Owner Built Brand New 500 Sq. Yard...,"dha phase 6, dha defence",dha defence,250000000.0,4500.0,5,6,3,6.0,3,0,2,1,0,2026.0
9857,"186 Yards House, Prime Corner Spot!","saadi town - block 1, saadi town",scheme 33,32000000.0,1674.0,6,6,0,4500.0,500,0,0,1,1,NaN
10053,House For Sale,"gulistan-e-jauhar - block 2, gulistan-e-jauhar",gulistan-e-jauhar,85000000.0,3960.0,8,6,2,28.0,1,0,0,1,1,NaN
10081,"APARTMENT FOR SALE Country & Naval View, Clift...","clifton - block 9, clifton",clifton,33500000.0,1197.0,2,2,1,17.0,1,0,0,1,1,2026.0
10176,600 Yards Architectural Design Bungalow For Sa...,"dha phase 6, dha defence",dha defence,149500000.0,5400.0,4,4,2,28.0,1,0,2,1,1,2025.0
10238,PS HEIGHTS LIMITED TIME 10% MEGA DISCOUNT OFFE...,"ps heights, scheme 33 - sector 31",scheme 33,13600000.0,1098.0,2,2,1,9.0,1,0,0,1,1,NaN
10947,House FOr Sale In Sawera 5 Sky Tower,"clifton - block 9, clifton",clifton,85000000.0,3870.0,4,5,2,38.0,1,0,1,1,1,2026.0
11330,2 Bad Dd House For Sale Available,"tulip tower, saadi road",saadi road,14000000.0,1251.0,2,2,1,8.0,1,0,1,1,0,2025.0

In [171]:
#removing appartments
idx = [
    550,
    6056,
    6244,
    7728,
    7736,
    8337,
    10081,
    10238,
    10947,
    11330,
    319
]
df.drop(index=idx,inplace=True)

In [181]:
#parking
df['parking'].value_counts()

parking
1       4057
0       3678
2       1478
3        846
4        617
5        243
6        119
10        46
8         42
7         23
15        10
100        8
20         7
50         7
9          5
40         3
180        3
12         3
30         2
42         1
88         1
11         1
2023       1
16         1
250        1
400        1
14         1
150        1
19         1
500        1
350        1
25         1
Name: count, dtype: int64

In [184]:
df.loc[df["parking"] > 15, "parking"] = np.nan

In [193]:
#furnished
df[df['furnished']==1]['price'].mean()

np.float64(112092296.44624381)

In [194]:
df[df['furnished']==0]['price'].mean()

np.float64(97327820.81608516)

In [195]:
#kitchen
df['kitchen'].value_counts()

kitchen
1     4447
2     3287
0     2866
3      537
4       53
21       4
11       3
5        3
6        3
17       1
14       1
8        1
31       1
9        1
22       1
7        1
Name: count, dtype: int64

In [196]:
df.groupby("kitchen")["price"].agg(["count", "mean", "median"]).sort_index()

         count          mean       median
kitchen
0         2866  9.179284e+07   54900000.0
1         4447  8.881503e+07   66000000.0
2         3287  1.217337e+08   70000000.0
3          537  1.611028e+08   75000000.0
4           53  1.783208e+08   78500000.0
5            3  5.700000e+07   45000000.0
6            3  1.383333e+08   35000000.0
7            1  2.700000e+08  270000000.0
8            1  4.000000e+08  400000000.0
9            1  5.000000e+07   50000000.0
11           3  2.241667e+08  185000000.0
14           1  3.950000e+07   39500000.0
17           1  3.500000e+07   35000000.0
21           4  8.600000e+07   77000000.0
22           1  4.000000e+07   40000000.0
31           1  1.100000e+08  110000000.0

In [207]:
df.loc[df['kitchen'] > 4,'kitchen']=np.nan

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11210 entries, 0 to 11981
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11210 non-null  object
 1   address             11210 non-null  object
 2   location            11210 non-null  object
 3   price               11210 non-null  float64
 4   area                11210 non-null  float64
 5   bedrooms            11210 non-null  int64
 6   bathrooms           11210 non-null  int64
 7   kitchen             11190 non-null  float64
 8   total_floors        4513 non-null   float64
 9   parking             11169 non-null  float64
 10  elevator            11210 non-null  int64
 11  servant_quarters    11210 non-null  int64
 12  electricity_backup  11210 non-null  int64
 13  furnished           11210 non-null  int64
 14  completion_year     5386 non-null   float64
dtypes: float64(6), int64(6), object(3)
memory usage: 1.4+ MB

In [209]:
df.to_csv('house_cleaned.csv',index=False)