In [10]:
import pandas as pd
import numpy as np

In [11]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [12]:
df=pd.read_csv('raw_flats_data.csv')

In [13]:
df.shape

(11939, 17)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11939 entries, 0 to 11938
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11939 non-null  object
 1   link                11939 non-null  object
 2   address             11939 non-null  object
 3   location            11936 non-null  object
 4   price               11936 non-null  object
 5   area                11936 non-null  object
 6   bedrooms            11936 non-null  object
 7   bathrooms           11936 non-null  object
 8   kitchen             11939 non-null  int64
 9   floor               3761 non-null   float64
 10  total_floors        5066 non-null   float64
 11  parking             11939 non-null  int64
 12  elevator            11939 non-null  int64
 13  servant_quarters    11939 non-null  int64
 14  electricity_backup  11939 non-null  int64
 15  furnished           11939 non-null  int64
 16  built_year          6295 non-null   float64
dtypes: float64(3), int64(6), object(8)
memory usage: 1.5+ MB

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isnull().sum()

property_name            0
link                     0
address                  0
location                 3
price                    3
area                     3
bedrooms                 3
bathrooms                3
kitchen                  0
floor                 8178
total_floors          6873
parking                  0
elevator                 0
servant_quarters         0
electricity_backup       0
furnished                0
built_year            5644
dtype: int64

In [17]:
df.drop(columns='link',inplace=True)

In [18]:
#location
df['location'].value_counts()

location
DHA Defence, Karachi, Sindh                                  2289
Gulshan-e-Iqbal Town, Karachi, Sindh                         1335
Scheme 33, Karachi, Sindh                                    1149
Gulistan-e-Jauhar, Karachi, Sindh                            1113
Cantt, Karachi, Sindh                                         720
North Nazimabad, Karachi, Sindh                               586
Clifton, Karachi, Sindh                                       565
University Road, Karachi, Sindh                               335
Bahria Town Karachi, Karachi, Sindh                           332
Gadap Town, Karachi, Sindh                                    300
Jamshed Town, Karachi, Sindh                                  269
Naya Nazimabad, Karachi, Sindh                                255
Jinnah Avenue, Karachi, Sindh                                 247
Korangi, Karachi, Sindh                                       168
Malir, Karachi, Sindh                                         167
Shaheed Millat Road, Karachi, Sindh                           160
North Karachi, Karachi, Sindh                                 147
Khalid Bin Walid Road, Karachi, Sindh                         119
Bath Island, Karachi, Sindh                                   112
Federal B Area, Karachi, Sindh                                107
Civil Lines, Karachi, Sindh                                    86
Rashid Minhas Road, Karachi, Sindh                             83
Malir Link To Super Highway, Karachi, Sindh                    76
Shah Faisal Town, Karachi, Sindh                               66
Jamshed Road, Karachi, Sindh                                   57
Saadi Road, Karachi, Sindh                                     56
Saddar Town, Karachi, Sindh                                    53
Nazimabad, Karachi, Sindh                                      52
Frere Town, Karachi, Sindh                                     48
Suparco Road, Karachi, Sindh                                   46
Bin Qasim Town, Karachi, Sindh                                 45
Shahra-e-Faisal, Karachi, Sindh                                43
Navy Housing Scheme Karsaz, Karachi, Sindh                     41
Tariq Road, Karachi, Sindh                                     40
Chapal Courtyard, Karachi, Sindh                               39
Sea View Apartments, Karachi, Sindh                            39
Falaknaz Harmony, Karachi, Sindh                               38
Defence View Society, Karachi, Sindh                           37
KDA Scheme 1, Karachi, Sindh                                   30
Amil Colony, Karachi, Sindh                                    28
Falaknaz Dynasty, Karachi, Sindh                               27
Dalmia Cement Factory Road, Karachi, Sindh                     27
Airport Road, Karachi, Sindh                                   25
Tipu Sultan Road, Karachi, Sindh                               24
KN Gohar Green City, Karachi, Sindh                            20
Garden West, Karachi, Sindh                                    19
DHA City Karachi, Karachi, Sindh                               17
Cosmopolitan Society, Karachi, Sindh                           17
Qayyumabad, Karachi, Sindh                                     14
Shahra-e-Qaideen, Karachi, Sindh                               14
Muslimabad Society, Karachi, Sindh                             12
Karachi Motorway, Karachi, Sindh                               12
Shaheed-e-Millat Expressway, Karachi, Sindh                    12
Karachi - Hyderabad Motorway, Karachi, Sindh                   11
Abul Hassan Isphani Road, Karachi, Sindh                       11
Mehmoodabad, Karachi, Sindh                                    11
Gizri, Karachi, Sindh                                          10
P & T Colony, Karachi, Sindh                                   10
Super Highway, Karachi, Sindh                                  10
Shahrah-e-Pakistan, Karachi, Sindh                              9
Liaquat Avenue, Karachi, Sindh                                  8
Airport, Karachi, Sindh                                         7
Cotton Export Cooperative Housing Society, Karachi, Sindh       7
Amir Khusro, Karachi, Sindh                                     6
Hill Park, Karachi, Sindh                                       6
Gulberg Town, Karachi, Sindh                                    6
Chapal Skymark, Karachi, Sindh                                  6
Rufi Lake Drive Apartments, Karachi, Sindh                      6
Al-Hilal Society, Karachi, Sindh                                6
New Karachi, Karachi, Sindh                                     5
I. I. Chundrigar Road, Karachi, Sindh                           5
Delhi Colony, Karachi, Sindh                                    5
National Highway, Karachi, Sindh                                5
Liaquatabad, Karachi, Sindh                                     4
PIB Colony, Karachi, Sindh                                      4
Shahra-e-Usman, Karachi, Sindh                                  4
Punjab Colony, Karachi, Sindh                                   4
Kashmir Colony, Karachi, Sindh                                  4
M. A. Jinnah Road, Karachi, Sindh                               3
Guru Mandir Chorangi, Karachi, Sindh                            3
MT Khan Road, Karachi, Sindh                                    2
Punjab Chowrangi, Karachi, Sindh                                2
Gulshan-e-Usman Housing Society, Karachi, Sindh                 2
Sindh Industrial Trading Estate (SITE), Karachi, Sindh          2
Baloch Colony, Karachi, Sindh                                   2
Kemari Town, Karachi, Sindh                                     2
Orangi Town, Karachi, Sindh                                     2
Ranchore Line Bazar, Karachi, Sindh                             2
Gadap Road, Karachi, Sindh                                      2
Kamran Chowrangi, Karachi, Sindh                                2
Allama Iqbal Town, Karachi, Sindh                               1
Stadium Road, Karachi, Sindh                                    1
Metrovil Colony, Karachi, Sindh                                 1
Darul Aman Society, Karachi, Sindh                              1
Sakhi Hassan Chowrangi, Karachi, Sindh                          1
Jamaluddin Afghani Road, Karachi, Sindh                         1
Royal Defence Tower, Karachi, Sindh                             1
Kashmir Road, Karachi, Sindh                                    1
Maqboolabad Society, Karachi, Sindh                             1
Dastgir Colony, Karachi, Sindh                                  1
Pak Ideal Cooperative Housing Society, Karachi, Sindh           1
Azam Town, Karachi, Sindh                                       1
Aisha Manzil, Karachi, Sindh                                    1
Maskan Chowrangi, Karachi, Sindh                                1
Cutchi Memon Cooperative Housing Society, Karachi, Sindh        1
Rabia City, Karachi, Sindh                                      1
ASF Tower, Karachi, Sindh                                       1
Police Society, Karachi, Sindh                                  1
Manzoor Colony, Karachi, Sindh                                  1
Numaish Chowrangi, Karachi, Sindh                               1
Moria Goth, Karachi, Sindh                                      1
Saima Luxury Homes, Karachi, Sindh                              1
Name: count, dtype: int64

In [19]:
df['location']=df['location'].str.split(',').str.get(0).str.lower()

In [20]:
#area
df['area']=df['area'].str.split().str.get(0).str.replace(',', '').astype(float)*9

In [21]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
0,3 Bed Drawing Dining Flat Is For Sale,"Tariq Road, Karachi",tariq road,6.5 Crore,1800.0,3,4,1,NaN,NaN,1,0,0,0,0,2023.0
1,3b-2 Bedrooms full sea facing of Panorama towe...,"Emaar Panorama, DHA Phase 8",dha defence,13 Crore,2700.0,3,4,2,NaN,45.0,2,4,1,1,0,2026.0
2,2000 Square Feet Spacious 3 Bedroom Apartment ...,"DHA Phase 6, DHA Defence",dha defence,5.5 Crore,1998.0,3,4,1,NaN,NaN,0,0,0,0,0,NaN
3,ULTRA-LUXURY COASTAL INVESTMENT: EXPANSIVE 3-B...,"Emaar Park Edge, DHA Phase 8",dha defence,14.35 Crore,2700.0,3,3,1,NaN,NaN,0,1,0,0,1,NaN
4,Prime Location WEST OPEN CHANCE DEAL IDEAL FLO...,"Askari 6, Malir Cantonment",cantt,3.9 Crore,2997.0,4,4,3,1.0,3.0,6,2,1,1,1,2026.0

In [22]:
#price
def convert_price(price):
    if pd.isna(price):
        return None

    price = str(price).replace(",", "").strip().lower()

    if "arab" in price:
        return float(price.replace("arab", "").strip()) * 1_000_000_000

    elif "crore" in price:
        return float(price.replace("crore", "").strip()) * 10_000_000

    elif "lakh" in price:
        return float(price.replace("lakh", "").strip()) * 100_000

    else:
        return float(price)

df['price']=df['price'].apply(convert_price)

In [23]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
0,3 Bed Drawing Dining Flat Is For Sale,"Tariq Road, Karachi",tariq road,65000000.0,1800.0,3,4,1,NaN,NaN,1,0,0,0,0,2023.0
1,3b-2 Bedrooms full sea facing of Panorama towe...,"Emaar Panorama, DHA Phase 8",dha defence,130000000.0,2700.0,3,4,2,NaN,45.0,2,4,1,1,0,2026.0
2,2000 Square Feet Spacious 3 Bedroom Apartment ...,"DHA Phase 6, DHA Defence",dha defence,55000000.0,1998.0,3,4,1,NaN,NaN,0,0,0,0,0,NaN
3,ULTRA-LUXURY COASTAL INVESTMENT: EXPANSIVE 3-B...,"Emaar Park Edge, DHA Phase 8",dha defence,143500000.0,2700.0,3,3,1,NaN,NaN,0,1,0,0,1,NaN
4,Prime Location WEST OPEN CHANCE DEAL IDEAL FLO...,"Askari 6, Malir Cantonment",cantt,39000000.0,2997.0,4,4,3,1.0,3.0,6,2,1,1,1,2026.0

In [24]:
#year
df[df['built_year'] > 2026]

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,built_year
21,Flat Available For Booking in Titan One,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,25000000.0,1431.0,2,2,3,5.0,18.0,1,2,2,1,1,2027.0
22,Flat Available For Booking In SAWERA RAJ NOOR,"Bath Island, Karachi",bath island,60000000.0,2061.0,3,4,1,1.0,4.0,1,4,1,1,0,2030.0
24,Flat Available For Booking In 5 Sky Tower By S...,"Clifton - Block 9, Clifton",clifton,53500000.0,2223.0,3,4,2,6.0,39.0,1,3,2,1,1,2030.0
31,3 Bed Lounge For Sale in Karachi University So...,"Karachi University Housing Society, Scheme 33",scheme 33,13000000.0,873.0,3,3,1,NaN,5.0,0,1,0,0,0,2027.0
43,Flat Available For Booking In 5 Sky Tower By S...,"Clifton - Block 9, Clifton",clifton,53500000.0,2196.0,3,4,1,9.0,38.0,1,1,2,1,1,2030.0
44,Flat Available For Sale In Sawera Galaxy Heigh...,"Alamgir Road, Gulshan-e-Iqbal Town",gulshan-e-iqbal town,46000000.0,1701.0,3,4,1,NaN,NaN,1,1,2,1,0,2027.0
52,Naya Nazimabad Peace Apartment | 6.5 Years Eas...,"Naya Nazimabad, Karachi",naya nazimabad,31100000.0,1773.0,3,4,1,6.0,28.0,1,5,0,1,0,2029.0
61,5 SKY TOWER BY SAWERA 3 Bed DD With Private Po...,"Clifton - Block 9, Clifton",clifton,62500000.0,2223.0,3,4,1,NaN,NaN,2,0,1,1,1,2029.0
112,H&S 1 BED LOUNGE WITH EASY PAYMENT PLAN,"DHA Phase 8, DHA Defence",dha defence,39000000.0,999.0,1,2,1,15.0,40.0,1,1,0,1,0,2029.0
123,With ROOF Flat 4 BED DD 2200 SQFT+ 2200 SQFT ROOF,"Garden East, Jamshed Town",jamshed town,72500000.0,2196.0,4,4,2,NaN,NaN,1,0,3,1,1,2028.0
136,West Open Flat Of 1665 Square Feet Is Availabl...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,33000000.0,1665.0,3,3,1,1.0,NaN,1,1,1,1,0,2028.0
150,5 SKY TOWER BY SAWERA | PREMIUM LIVING CURATED...,"Clifton - Block 9, Clifton",clifton,62500000.0,2223.0,3,4,1,NaN,3.0,1,1,1,1,1,2030.0
156,2 Bed Lounge Flat for sale Naya Nazimabad - Gr...,"Naya Nazimabad, Karachi",naya nazimabad,14000000.0,855.0,2,2,0,NaN,7.0,1,2,0,0,0,2028.0
163,Prime Location 2300 Square Feet Flat For Sale ...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,40000000.0,2304.0,3,4,1,2.0,NaN,2,0,1,1,0,2031.0
169,3 BED LOUNGE 1250SQ FT ROAD FACING APARTMENT I...,"Karachi University Housing Society, Scheme 33",scheme 33,15000000.0,1251.0,3,3,1,9.0,16.0,180,6,0,1,0,2029.0
186,Samrina Boulevard 2 Bed DD With ROOF,"Samrina Boulevard, Scheme 33",scheme 33,21500000.0,1098.0,2,2,1,15.0,15.0,1,3,0,1,0,2030.0
211,4 Bed Drawing Dining Corner West Open Flat For...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,43500000.0,1971.0,4,4,1,NaN,NaN,1,1,0,1,0,2028.0
234,3 Bed Drawing Dining West Open,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,33000000.0,1665.0,3,3,1,NaN,NaN,1,0,0,1,0,2028.0
235,3 Bed Drawing Dining Flat,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,30000000.0,1665.0,3,3,1,NaN,NaN,1,0,0,1,0,2028.0
260,2 Bed Drawing Dining Possession 13 months,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,17500000.0,1449.0,2,3,1,NaN,NaN,1,1,2,1,1,2027.0
300,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,45000000.0,2601.0,5,6,1,NaN,NaN,2,5,1,1,0,2030.0
330,Booking Apartment For Sale In Clifton,"Clifton - Block 1, Clifton",clifton,35800000.0,1989.0,3,3,1,14.0,20.0,1,3,1,1,0,2030.0
353,Buy 1452 Square Feet Flat At Highly Affordable...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,20500000.0,1449.0,2,3,1,NaN,15.0,1,4,0,1,1,2027.0
357,2 Bed Lounge flat for sale Naya Nazimabad Bloc...,"Naya Nazimabad - Block A, Naya Nazimabad",naya nazimabad,15000000.0,909.0,2,2,0,NaN,7.0,0,2,0,1,0,2028.0
373,Booking Projects Flat Available,"DHA Phase 8, DHA Defence",dha defence,34500000.0,1152.0,1,1,1,NaN,30.0,1,4,1,1,0,2029.0
393,Looking For A Flat In Karachi,"Clifton - Block 8, Clifton",clifton,60000000.0,2259.0,3,4,1,NaN,NaN,2,0,1,1,1,2029.0
402,2 Bed Drawing Dining West Open Flat,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,20000000.0,1233.0,2,2,1,NaN,NaN,1,0,0,1,0,2028.0
434,Naya Nazimabad Peace Apartment | 6.5 Years Eas...,"Naya Nazimabad, Karachi",naya nazimabad,31900000.0,1818.0,3,4,1,10.0,28.0,1,5,0,1,0,2029.0
444,Newly Renovated Apartment for Sale in Prime Lo...,"Bahadurabad, Gulshan-e-Iqbal Town",gulshan-e-iqbal town,27500000.0,1503.0,3,3,1,5.0,6.0,3,1,0,1,0,2222.0
451,Emaar Park Edge 3 Bedroom Luxury Apartment | E...,"Emaar Park Edge, DHA Phase 8",dha defence,104500000.0,2502.0,3,4,1,NaN,NaN,2,4,1,1,1,2028.0
485,FLAT 4 BED LIVING FOR BOOKING,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,35000000.0,2133.0,3,3,1,NaN,24.0,1,7,1,1,1,2028.0
504,Gulshan Prime Location 3 Bed DD 1756sqft Flat ...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,33000000.0,1755.0,3,4,1,NaN,NaN,1,2,1,1,1,2027.0
509,SAWERA 5 SKY TOWER A PROJECT OF (OK ESTATE & ...,"Clifton - Block 9, Clifton",clifton,75000000.0,3870.0,4,5,2,4.0,38.0,2,6,1,1,1,2029.0
510,Sawera Grand Enclave Luxury Living Starts Here...,"Scheme 33, Karachi",scheme 33,9500000.0,909.0,2,2,1,NaN,22.0,1,2,0,1,0,2032.0
514,2-Bedroom Apartment At EMAAR Park Edge Now Ava...,"Emaar Crescent Bay, DHA Phase 8",dha defence,94000000.0,1440.0,2,4,1,NaN,NaN,1,1,1,1,0,2028.0
524,Booking In 5% Only 2 Bedroom West Open Full Se...,"HMR Waterfront, DHA Phase 8",dha defence,50500000.0,1377.0,2,3,1,1.0,40.0,1,6,1,1,1,2028.0
580,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,17500000.0,1170.0,2,3,1,13.0,20.0,1,4,0,0,1,2027.0
676,Dubai Lifestyle in Karachi | Luxury 2-Bedroom ...,"Emaar Park Edge, DHA Phase 8",dha defence,81500000.0,1737.0,2,3,1,NaN,NaN,1,5,1,1,1,2028.0
702,HMR Waterfront Nikken Sikken Tower 1 Bedroom F...,"HMR Waterfront, DHA Phase 8",dha defence,35000000.0,999.0,1,2,1,9.0,38.0,1,5,1,1,1,2029.0
714,Flat For Sale Booking In Clifton,"Clifton - Block 1, Clifton",clifton,16200000.0,900.0,2,2,1,5.0,20.0,1,3,0,1,0,2030.0
755,03 Bed Premium Sea Facing Flat For Sale In Ema...,"Emaar Panorama, DHA Phase 8",dha defence,156000000.0,3096.0,3,4,0,NaN,45.0,1,4,0,0,0,2027.0
760,Invest In Timeless Elegance At Zainab Habib To...,"Khalid Bin Walid Road, Karachi",khalid bin walid road,78500000.0,2952.0,4,5,1,5.0,25.0,2,1,0,1,0,2029.0
784,Clifton Luxury Modern Living Prime Location Di...,"Clifton - Block 9, Clifton",clifton,62000000.0,2223.0,3,4,1,25.0,38.0,2,1,2,1,1,2028.0
791,"Apartment For Sale Main Alamgir Road, Sharfaba...","Bahadurabad, Gulshan-e-Iqbal Town",gulshan-e-iqbal town,29000000.0,1602.0,3,3,1,1.0,6.0,3,3,0,1,0,2222.0
806,02 Bed Sea Facing Flat For Sale In AA Waterfro...,"HMR Waterfront, DHA Phase 8",dha defence,97500000.0,2376.0,3,4,0,NaN,4.0,1,4,0,0,0,2028.0
810,Wake Up To The Ocean Own Your Dream Home At AA...,"HMR Waterfront, DHA Phase 8",dha defence,108500000.0,22500.0,3,3,1,NaN,25.0,2,5,1,1,0,2031.0
826,A High Standard Apartment Project With Spaciou...,"Surjani Town, Gadap Town",gadap town,3000000.0,702.0,2,2,1,NaN,5.0,1,1,1,1,1,2027.0
834,Invest In Paradise AA Beachfront-HMR Water Fro...,"HMR Waterfront, DHA Phase 8",dha defence,40000000.0,999.0,1,1,1,NaN,25.0,2,5,1,1,0,2031.0
835,"""Experience Luxury Living At Sawera Sky Tower,...","Clifton, Karachi",clifton,55000000.0,2223.0,3,3,1,33.0,38.0,2,6,1,1,0,2028.0
850,THE TILT RESIDENCE By Nikken Sekkei 3 Bed Sea...,"HMR Waterfront, DHA Phase 8",dha defence,119000000.0,2898.0,3,4,1,NaN,NaN,2,4,1,1,0,2030.0
859,"""Experience Luxury Living At Sawera Sky Tower,...","Clifton - Block 9, Clifton",clifton,75000000.0,3870.0,4,4,1,NaN,34.0,2,5,1,1,0,2029.0
884,"""Experience Luxury Living At Sawera Sky Tower,...","Clifton - Block 9, Clifton",clifton,63500000.0,2223.0,3,3,1,NaN,38.0,2,1,1,1,0,2029.0
905,Luxury 2 bedroom Huge size Apartment in The Tilt,"HMR Waterfront, DHA Phase 8",dha defence,54200000.0,1359.0,2,3,1,NaN,40.0,1,4,1,1,0,2030.0
926,Luxury 1 Bedroom Apartment In HMR Waterfront |...,"DHA Phase 8, DHA Defence",dha defence,40000000.0,999.0,1,2,0,NaN,35.0,1,7,0,1,1,2031.0
947,"Apartment Available For Sale In Askari-5 , Mal...","Askari 5, Malir Cantonment",cantt,33500000.0,2250.0,3,3,2,NaN,11.0,1,1,0,1,1,2028.0
1001,1020 Sq Ft Sea Facing Apartment For Sale | Sai...,"HMR Waterfront, DHA Phase 8",dha defence,40000000.0,1017.0,1,2,1,NaN,NaN,1,0,1,1,0,2028.0
1025,Flat Booking Projects Available For Sale,"HMR Waterfront, DHA Phase 8",dha defence,56000000.0,1422.0,2,3,1,10.0,30.0,1,4,1,1,0,2029.0
1030,Fresh Booking Bungalow Facing 3-Side Corner We...,"DHA Phase 6, DHA Defence",dha defence,30000000.0,1251.0,3,3,1,NaN,NaN,1,1,0,1,0,2027.0
1032,2100 Square Feet 3 Bedroom Drawing Dining Apar...,"Bath Island, Karachi",bath island,65000000.0,2097.0,3,3,1,NaN,19.0,2,1,1,1,1,2028.0
1091,1700 Sq Ft Well Maintain Luxury Flat For Sale ...,"North Nazimabad - Block B, North Nazimabad",north nazimabad,19000000.0,1701.0,3,3,1,NaN,3.0,1,1,1,1,1,2027.0
1113,"""AL RAUF GOLD RAAS"" APARTMENT FOR SALE","Scheme 33 - Sector 51-A, Scheme 33",scheme 33,20400000.0,1701.0,3,3,1,5.0,14.0,1,4,0,1,0,2031.0
1115,"""AL RAUF GOLD RAAS"" APARTMENT FOR SALE","Scheme 33 - Sector 51-A, Scheme 33",scheme 33,14500000.0,1206.0,2,2,1,5.0,14.0,1,4,2,1,1,2031.0
1116,"""AL RAUF GOLD RAAS"" APARTMENT FOR SALE","Scheme 33 - Sector 51-A, Scheme 33",scheme 33,11400000.0,954.0,-,2,1,5.0,14.0,1,4,0,1,0,2031.0
1117,"""AL RAUF GOLD RAAS"" APARTMENT FOR SALE","Gulzar-e-Hijri, Scheme 33",scheme 33,19000000.0,1584.0,3,3,1,5.0,14.0,1,4,0,1,0,2031.0
1309,Cantt Pearl Residency Apartment Opposite Lakha...,"Cantt Pearl Residency & Shopping Mall, Scheme ...",scheme 33,12200000.0,1197.0,2,2,1,4.0,12.0,2,2,1,1,1,2027.0
1311,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,30000000.0,1701.0,3,4,1,7.0,20.0,1,4,0,1,0,2027.0
1327,3 BEDROOMS DRAWING DINING APARTMENT AVAILABLE ...,"Askari 4, Gulistan-e-Jauhar",gulistan-e-jauhar,70000000.0,2502.0,3,4,1,NaN,10.0,2,3,1,1,1,2029.0
1398,S. M. Axis Luxurious Apartments For Sale,"North Nazimabad - Block N, North Nazimabad",north nazimabad,28200000.0,1278.0,2,3,1,8.0,22.0,1,2,0,1,0,2030.0
1432,8 Room 2750 Sq Ft 1000 Sq Ft Parking Space Inv...,"Kings Grand Towers, Scheme 33 - Sector 35-A",scheme 33,22000000.0,2754.0,5,6,1,6.0,16.0,1,6,1,1,1,2028.0
1475,SAWERA 5 SKY TOWERS. A PROJECT OF OK ESTATE & ...,"Clifton - Block 9, Clifton",clifton,62500000.0,2223.0,3,4,2,6.0,38.0,2,4,1,1,1,2029.0
1501,Naya Nazimabad | Peace Com 41 1775 Sq Feet Fla...,"Naya Nazimabad, Karachi",naya nazimabad,29000000.0,1773.0,3,4,1,26.0,26.0,1,1,0,1,0,2029.0
1507,Luxurious 3 Bedrooms Apartment For Booking At ...,"HMR Waterfront, DHA Phase 8",dha defence,89100000.0,2349.0,3,4,1,23.0,53.0,2,4,1,1,1,2030.0
1508,Luxurious Ultra Modern 3bedrooms Apartment On ...,"Clifton - Block 2, Clifton",clifton,109600000.0,3213.0,3,4,1,16.0,52.0,2,4,1,1,1,2030.0
1519,Prime Location Callachi Cooperative Housing So...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,45000000.0,2700.0,4,4,1,2.0,NaN,2,0,1,1,1,2031.0
1524,In KDA Park Facing 2400 Sq Ft Flat On Booking ...,"KDA Scheme 1, Karachi",kda scheme 1,81300000.0,2403.0,4,5,2,NaN,15.0,2,3,1,0,1,2030.0
1526,4 Bed Drawing Dining Flat Corner West Open,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,43500000.0,1971.0,4,4,1,NaN,NaN,1,0,2,1,1,2028.0
1547,FLAT AVAILABLE FOR BOOKING IN UNDER CONSTRUCTI...,"Khalid Bin Walid Road, Karachi",khalid bin walid road,80000000.0,2898.0,4,5,0,NaN,NaN,1,1,0,1,0,2031.0
1552,3 Bed Drawing Dining West Open Flat For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,31000000.0,1971.0,3,4,1,NaN,NaN,1,2,2,1,1,2027.0
1566,Discover the Ultimate Investment: Four-Year Ea...,"Bath Island, Karachi",bath island,65000000.0,2115.0,3,3,1,6.0,20.0,2,3,0,1,0,2028.0
1568,Prime Location Sale The Ideally Located Flat F...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,41500000.0,1998.0,4,4,1,NaN,24.0,1,7,1,1,1,2028.0
1578,FLAT AVAILABLE FOR BOOKING IN UNDER CONSTRUCTI...,"Khalid Bin Walid Road, Karachi",khalid bin walid road,78500000.0,2898.0,4,5,0,NaN,NaN,1,1,0,1,0,2031.0
1593,Lowest Priced! Sea Facing 1 Bed Apartment | Pr...,"HMR Waterfront, DHA Phase 8",dha defence,34500000.0,864.0,1,1,1,NaN,NaN,1,1,0,1,0,2030.0
1601,2400 Square Feet Flat In Askari 5 - Sector J I...,"Askari 5 - Sector J, Askari 5",cantt,41500000.0,2403.0,3,3,1,NaN,14.0,1,4,1,1,1,2027.0
1602,Flat Of 3000 Square Feet Is Available In Conte...,"Askari 5 - Sector J, Askari 5",cantt,50000000.0,2997.0,4,4,1,NaN,NaN,2,1,1,1,1,2030.0
1620,"""Experience Luxury Living At Sawera Sky Tower,...","Clifton - Block 9, Clifton",clifton,62500000.0,2223.0,3,4,1,NaN,38.0,1,1,1,1,1,2028.0
1647,Luxurious 3-Bedroom Apartment With Private Poo...,"Clifton, Karachi",clifton,61500000.0,2223.0,3,3,1,NaN,NaN,1,1,1,1,1,2029.0
1649,ZAINAB HABIB TOWER BY OK ESTATE & BUILDERS. AN...,"Khalid Bin Walid Road, Karachi",khalid bin walid road,52500000.0,1953.0,3,4,1,NaN,22.0,1,1,1,1,0,2030.0
1652,1 Bed Olympia (Type D) Partial Sea Facing With...,"HMR Waterfront, DHA Phase 8",dha defence,43700000.0,1089.0,1,2,1,NaN,NaN,1,4,1,1,1,2030.0
1653,3 Bed A-Type Sea Facing Fresh Flat Pre-Booking...,"HMR Waterfront, DHA Phase 8",dha defence,121000000.0,2880.0,3,4,1,NaN,NaN,1,4,1,1,1,2030.0
1654,Buy A Centrally Located 1935 Square Feet Flat ...,"HMR Waterfront, DHA Phase 8",dha defence,81300000.0,1935.0,2,3,2,NaN,NaN,1,4,1,1,1,2030.0
1668,HMR Waterfront Gold Crest Bay Sands Tower 2 | ...,"HMR Waterfront, DHA Phase 8",dha defence,109600000.0,2736.0,3,3,1,NaN,NaN,2,4,1,1,1,2030.0
1669,HMR Waterfront Gold Crest Bay Sands Tower 2 | ...,"HMR Waterfront, DHA Phase 8",dha defence,35800000.0,900.0,1,1,2,NaN,NaN,1,4,1,1,0,2030.0
1677,"5 SKY TOWER BY SAWERA, 3 Bed DD Premium Apartm...","Clifton - Block 9, Clifton",clifton,70000000.0,2223.0,3,4,1,21.0,38.0,2,3,1,1,1,2030.0
1706,APARTMENT LIVING LIKE 400 SQ YARDS HOUSE 8 ROO...,"Kings Grand Towers, Scheme 33 - Sector 35-A",scheme 33,22000000.0,3600.0,6,6,1,2.0,16.0,1,5,2,1,1,2028.0
1724,SAWERA GRAND ENCLAVE A Vision Beyond Living 2 ...,"Scheme 33, Karachi",scheme 33,9500000.0,909.0,2,2,1,NaN,18.0,1,2,1,1,1,2031.0
1729,3-Bed Lounge Fresh Booking DHA Karachi Easy In...,"Bukhari Commercial Area, DHA Phase 6",dha defence,31000000.0,1053.0,3,3,1,NaN,4.0,1,1,1,1,1,2028.0
1743,Trillium Residential Towers 2 Bedroom Apartmen...,"DHA Phase 8, DHA Defence",dha defence,99700000.0,1881.0,2,2,0,10.0,42.0,2,4,0,1,0,2028.0
1746,Sawera Grand Enclave Apartments For Sale,"Scheme 33, Karachi",scheme 33,9500000.0,909.0,2,2,1,10.0,20.0,1,1,1,1,1,2031.0
1747,SAWERA RAJNOOR Apartment A Project Of OK Estat...,"Bath Island, Karachi",bath island,65000000.0,2115.0,3,4,1,NaN,32.0,2,1,1,1,1,2028.0
1754,Flat For Sale Naya Nazimabad Rahat Residency 1,"Naya Nazimabad, Karachi",naya nazimabad,22000000.0,1431.0,3,2,1,7.0,35.0,1,4,1,1,1,2027.0
1760,Sawera Grand Enclave Where Luxury Meets Modern...,"Scheme 33, Karachi",scheme 33,12800000.0,1188.0,2,3,0,NaN,NaN,1,3,0,1,0,2032.0
1764,Prime Location Apartments Near Jamali Bridge S...,"Scheme 33, Karachi",scheme 33,10000000.0,909.0,2,2,2,NaN,22.0,1,3,1,1,1,2031.0
1773,3 Bedroom Apartment Available On Booking On Ea...,"Bukhari Commercial Area, DHA Phase 6",dha defence,31000000.0,1017.0,3,3,1,NaN,4.0,1,1,1,1,1,2028.0
1787,SAWERA GRAND ENCLAVE,"Gulzar-e-Hijri, Scheme 33",scheme 33,9500000.0,909.0,2,3,1,NaN,22.0,1,1,1,1,1,2031.0
1788,ZAINAB HABIB TOWER BY SAWERA,"Khalid Bin Walid Road, Karachi",khalid bin walid road,52500000.0,1953.0,4,4,1,NaN,24.0,1,1,1,1,1,2030.0
1855,Prime Location Apartment For Sale On Booking,"DHA Phase 8, DHA Defence",dha defence,47000000.0,1701.0,3,4,1,3.0,5.0,1,2,0,1,0,2027.0
1856,Booking Apartment For Sale In Itehad Comercial,"Ittehad Commercial Area, DHA Phase 6",dha defence,23000000.0,900.0,2,2,1,3.0,4.0,0,1,0,0,0,2027.0
1882,Premium Sea Facing 3bedrooms Apartment For Sel...,"Clifton - Block 1, Clifton",clifton,104800000.0,3276.0,3,4,1,18.0,34.0,3,5,1,1,1,2027.0
1901,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,40000000.0,2196.0,4,5,1,NaN,NaN,2,6,1,1,0,2030.0
1903,Flat For Sale In Callachi Cooperative Housing ...,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,27000000.0,1395.0,2,3,1,NaN,18.0,1,5,0,1,1,2027.0
1918,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,33000000.0,1800.0,3,4,1,NaN,NaN,1,2,0,1,0,2027.0
1920,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,25000000.0,1296.0,2,3,1,NaN,NaN,1,2,0,1,0,2027.0
1950,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,30000000.0,1800.0,4,4,1,NaN,NaN,1,2,0,1,0,2027.0
1972,4 Bedroom & Lounge Apartment For Sale,"Gulshan-e-Iqbal - Block 10-A, Gulshan-e-Iqbal",gulshan-e-iqbal town,35000000.0,2133.0,4,4,1,1.0,4.0,1,7,1,1,1,2030.0
1973,Jauhar Dynasty New Apartments in Gulistan e Ja...,"Gulistan-e-Jauhar - Block 19, Gulistan-e-Jauhar",gulistan-e-jauhar,11500000.0,774.0,4,2,1,NaN,NaN,1,1,1,1,1,2027.0
1976,SHAYAN ICONIOC RESIDENCY FLAT FOR SALE,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,21500000.0,1161.0,2,3,0,NaN,20.0,1,1,0,1,0,2027.0
1997,Otel Residency Flat In Defence View Society Fo...,"Defence View Society, Karachi",defence view society,15000000.0,819.0,2,2,1,4.0,28.0,4,6,1,1,1,2028.0
2003,Callachi Icon Booking Flat Near Signature Banquet,"Gulshan-e-Iqbal - Block 10-A, Gulshan-e-Iqbal",gulshan-e-iqbal town,35000000.0,2133.0,3,4,1,10.0,22.0,1,7,1,1,1,2027.0
2017,Calachi Icon Project located in Callachi Socie...,"Gulshan-e-Iqbal Town, Karachi",gulshan-e-iqbal town,35000000.0,2772.0,4,5,1,5.0,22.0,1,7,1,1,1,2028.0
2018,Calachi Icon Luxury Apartments,"Dalmia Cement Factory Road, Karachi",dalmia cement factory road,35000000.0,2097.0,3,4,1,15.0,22.0,1,7,2,1,1,2028.0
2020,Flat For Sale In Airport Residency On Booking,"Shahra-e-Faisal, Karachi",shahra-e-faisal,15500000.0,1368.0,2,3,1,5.0,13.0,1,5,1,1,1,2027.0
2023,Under Construction 5 Room Apartment For Sale,"Malir Cantonment, Cantt",cantt,15500000.0,1098.0,5,4,1,NaN,NaN,1,1,1,1,1,2028.0
2024,4 Bedroom Apartment || Under Construction Buil...,"Federal B Area - Block 9, Federal B Area",federal b area,19000000.0,1242.0,4,3,1,20.0,25.0,1,3,1,1,1,2030.0
2025,Under Construction 5 Room Apartment For Sale,"Malir Cantonment, Cantt",cantt,15500000.0,1098.0,5,4,1,NaN,NaN,1,1,1,1,1,2028.0
2026,Airport Residency Flat For Sale,"Tariq Bin Ziyad Housing Society, Malir",malir,19500000.0,1413.0,3,4,1,1.0,13.0,2,10,1,1,1,2028.0
2027,Airport Residency Flat Is For Sale,"Shahra-e-Faisal, Karachi",shahra-e-faisal,20000000.0,1764.0,3,4,1,3.0,13.0,2,5,1,1,1,2028.0
2028,OTEL RESIDENCY Luxury Apartments Booking Near DHA,"DHA Phase 7, DHA Defence",dha defence,32500000.0,2151.0,3,4,1,11.0,21.0,1,6,0,1,1,2027.0
2044,Airport Residency 4 Room Apartment,"University Road, Karachi",university road,19000000.0,1098.0,2,2,1,NaN,NaN,1,1,1,1,1,2029.0
2047,*AIRPORT RESIDENCY* 3 BED DD,"Shahra-e-Faisal, Karachi",shahra-e-faisal,20000000.0,1764.0,3,4,1,NaN,NaN,1,1,1,1,1,2028.0
2053,*AIRPORT RESIDENCY* 3BED DD,"Shahra-e-Faisal, Karachi",shahra-e-faisal,22000000.0,1764.0,4,2,1,NaN,NaN,1,1,1,1,1,2028.0
2058,3 Bed Luxury Apartment Available In Easy Month...,"Nazimabad 5, Nazimabad",nazimabad,10000000.0,846.0,2,3,1,6.0,19.0,2,4,1,1,0,2028.0
2070,Apartment For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,45000000.0,2727.0,5,6,1,NaN,NaN,1,7,0,1,0,2030.0
2071,Apartment Is Available For Sale,"Callachi Cooperative Housing Society, Gulshan-...",gulshan-e-iqbal town,36000000.0,2133.0,4,4,1,NaN,NaN,1,7,0,1,0,2030.0

In [25]:
df.rename(columns={'built_year':'completion_year'},inplace=True)

In [26]:
df['completion_year'].value_counts()

completion_year
2025.0    1012
2026.0     960
2024.0     770
2023.0     460
2022.0     458
2020.0     371
2021.0     274
2018.0     201
2028.0     191
2019.0     183
2015.0     171
2000.0     142
2010.0     125
2030.0     111
2027.0     105
2029.0      95
2017.0      87
2016.0      77
2012.0      55
2005.0      47
2031.0      45
2008.0      39
2014.0      38
1990.0      33
2013.0      24
2002.0      21
2009.0      21
2222.0      21
2011.0      19
2032.0      14
2007.0      13
1999.0      13
2001.0      13
2003.0      11
1992.0      10
1996.0      10
1995.0       9
2006.0       9
2004.0       5
2823.0       5
1985.0       4
1998.0       4
2033.0       4
1997.0       3
1993.0       3
1980.0       3
1988.0       1
2826.0       1
0.0          1
3026.0       1
1989.0       1
5022.0       1
Name: count, dtype: int64

In [27]:

df.loc[(df["completion_year"] < 1900) | (df["completion_year"] > 2100),"completion_year"]=np.nan

In [28]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
0,3 Bed Drawing Dining Flat Is For Sale,"Tariq Road, Karachi",tariq road,65000000.0,1800.0,3,4,1,NaN,NaN,1,0,0,0,0,2023.0
1,3b-2 Bedrooms full sea facing of Panorama towe...,"Emaar Panorama, DHA Phase 8",dha defence,130000000.0,2700.0,3,4,2,NaN,45.0,2,4,1,1,0,2026.0
2,2000 Square Feet Spacious 3 Bedroom Apartment ...,"DHA Phase 6, DHA Defence",dha defence,55000000.0,1998.0,3,4,1,NaN,NaN,0,0,0,0,0,NaN
3,ULTRA-LUXURY COASTAL INVESTMENT: EXPANSIVE 3-B...,"Emaar Park Edge, DHA Phase 8",dha defence,143500000.0,2700.0,3,3,1,NaN,NaN,0,1,0,0,1,NaN
4,Prime Location WEST OPEN CHANCE DEAL IDEAL FLO...,"Askari 6, Malir Cantonment",cantt,39000000.0,2997.0,4,4,3,1.0,3.0,6,2,1,1,1,2026.0

In [29]:
#bedroom and bathroom
idx=df[(df['bedrooms']=='-') | (df['bedrooms'].isna())].index
df.drop(index=idx,inplace=True)

In [30]:
df.drop(index=df[(df['bathrooms']=='-')].index,inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11678 entries, 0 to 11938
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11678 non-null  object
 1   address             11678 non-null  object
 2   location            11678 non-null  object
 3   price               11678 non-null  float64
 4   area                11678 non-null  float64
 5   bedrooms            11678 non-null  object
 6   bathrooms           11678 non-null  object
 7   kitchen             11678 non-null  int64
 8   floor               3717 non-null   float64
 9   total_floors        5013 non-null   float64
 10  parking             11678 non-null  int64
 11  elevator            11678 non-null  int64
 12  servant_quarters    11678 non-null  int64
 13  electricity_backup  11678 non-null  int64
 14  furnished           11678 non-null  int64
 15  completion_year     6179 non-null   float64
dtypes: float64(5), int64(6), object(5)
memory usage: 1.5+ MB

In [32]:
df['bedrooms']=df['bedrooms'].astype('int64')
df['bathrooms']=df['bathrooms'].astype('int64')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11678 entries, 0 to 11938
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11678 non-null  object
 1   address             11678 non-null  object
 2   location            11678 non-null  object
 3   price               11678 non-null  float64
 4   area                11678 non-null  float64
 5   bedrooms            11678 non-null  int64
 6   bathrooms           11678 non-null  int64
 7   kitchen             11678 non-null  int64
 8   floor               3717 non-null   float64
 9   total_floors        5013 non-null   float64
 10  parking             11678 non-null  int64
 11  elevator            11678 non-null  int64
 12  servant_quarters    11678 non-null  int64
 13  electricity_backup  11678 non-null  int64
 14  furnished           11678 non-null  int64
 15  completion_year     6179 non-null   float64
dtypes: float64(5), int64(8), object(3)
memory usage: 1.5+ MB

In [34]:
#address
df['address'].value_counts()

address
HMR Waterfront, DHA Phase 8                                                                   508
Askari 5 - Sector J, Askari 5                                                                 323
Callachi Cooperative Housing Society, Gulshan-e-Iqbal - Block 10-A                            261
Naya Nazimabad, Karachi                                                                       243
Scheme 33, Karachi                                                                            227
Askari 6, Malir Cantonment                                                                    203
Shaheed Millat Road, Karachi                                                                  158
Emaar The Views, DHA Phase 8                                                                  158
Emaar Crescent Bay, DHA Phase 8                                                               154
Clifton - Block 2, Clifton                                                                    150
Burj-Ul-Harmain, University Road                                                              143
North Nazimabad - Block F, North Nazimabad                                                    127
Emaar Panorama, DHA Phase 8                                                                   124
Bahria Apartments, Bahria Town Karachi                                                        120
Khalid Bin Walid Road, Karachi                                                                119
Bukhari Commercial Area, DHA Phase 6                                                          119
Bath Island, Karachi                                                                          111
Gulistan-e-Jauhar - Block 13, Gulistan-e-Jauhar                                               108
DHA Phase 6, DHA Defence                                                                      106
Emaar Pearl Towers, Emaar Crescent Bay                                                        103
Gulistan-e-Jauhar, Karachi                                                                    101
Emaar Coral Towers, Emaar Crescent Bay                                                        101
Metropolis Residency, Jinnah Avenue                                                           101
Gulistan-e-Jauhar - Block 18, Gulistan-e-Jauhar                                                95
Gulistan-e-Jauhar - Block 15, Gulistan-e-Jauhar                                                91
Gulistan-e-Jauhar - Block 17, Gulistan-e-Jauhar                                                91
Clifton - Block 9, Clifton                                                                     88
Harmain Royal Residency, Gulshan-e-Iqbal - Block 1                                             88
DHA Phase 5, DHA Defence                                                                       86
DHA Phase 8, DHA Defence                                                                       86
Clifton - Block 1, Clifton                                                                     86
Gulistan-e-Jauhar - Block 3-A, Gulistan-e-Jauhar                                               83
Civil Lines, Karachi                                                                           82
Gulshan-e-Iqbal - Block 1, Gulshan-e-Iqbal                                                     76
North Nazimabad - Block H, North Nazimabad                                                     75
Askari 5, Malir Cantonment                                                                     73
Bahadurabad, Gulshan-e-Iqbal Town                                                              73
Gulshan-e-Iqbal - Block 10-A, Gulshan-e-Iqbal                                                  73
Gulistan-e-Jauhar - Block 14, Gulistan-e-Jauhar                                                69
Clifton - Block 8, Clifton                                                                     69
Emaar Reef Towers, Emaar Crescent Bay                                                          63
Jinnah Avenue, Karachi                                                                         63
Daniyal Residency, Scheme 33                                                                   62
University Road, Karachi                                                                       61
PECHS Block 2, PECHS                                                                           60
Jamshed Road, Karachi                                                                          57
Badar Commercial Area, DHA Phase 5                                                             57
Bahria Heights, Bahria Town Karachi                                                            56
DHA Phase 2 Extension, DHA Defence                                                             56
Gulshan-e-Iqbal, Gulshan-e-Iqbal Town                                                          55
North Karachi, Karachi                                                                         54
Allahwala Town - Sector 31-G, Allahwala Town                                                   54
North Nazimabad - Block L, North Nazimabad                                                     53
North Nazimabad - Block B, North Nazimabad                                                     53
Cantt View Lodges, Malir Link To Super Highway                                                 53
Falaknaz Presidency, Malir                                                                     52
North Nazimabad - Block M, North Nazimabad                                                     52
Gulistan-e-Jauhar - Block 16, Gulistan-e-Jauhar                                                52
Gulzar-e-Hijri, Scheme 33                                                                      51
North Nazimabad - Block K, North Nazimabad                                                     51
Gulshan-e-Iqbal - Block 13-D2, Gulshan-e-Iqbal                                                 51
Saima Jinnah Avenue, University Road                                                           50
Paragon Tower, Bahria Town - Precinct 17                                                       50
Emaar Park Edge, DHA Phase 8                                                                   49
Creek Vista, DHA Phase 8                                                                       49
Gulistan-e-Jauhar - Block 7, Gulistan-e-Jauhar                                                 49
Saima Residencia, Scheme 33 - Sector 34-A                                                      49
Nishat Commercial Area, DHA Phase 6                                                            46
Capital Cooperative Housing Society, Scheme 33 - Sector 35-A                                   46
Dhoraji Colony, Gulshan-e-Iqbal Town                                                           46
Clifton - Block 4, Clifton                                                                     45
Tulip Tower, Saadi Road                                                                        44
Falaknaz Twin Tower, Gulzar-e-Hijri                                                            43
Frere Town, Karachi                                                                            43
Gulshan-e-Iqbal - Block 4, Gulshan-e-Iqbal                                                     42
Shaz Residency, Gulshan-e-Iqbal Town                                                           42
North Nazimabad - Block N, North Nazimabad                                                     42
Al-Murtaza Commercial Area, DHA Phase 8                                                        42
Shahra-e-Faisal, Karachi                                                                       41
Al Madni Heights, University Road                                                              41
Lucky One Apartment, Rashid Minhas Road                                                        41
Dascon Tower, Bahria Hills                                                                     41
Gulistan-e-Jauhar - Block 12, Gulistan-e-Jauhar                                                40
Sharfabad, Gulshan-e-Iqbal Town                                                                40
Karachi University Housing Society, Scheme 33                                                  40
Tariq Road, Karachi                                                                            39
Gulshan-e-Maymar, Gadap Town                                                                   39
Chapal Courtyard, Karachi                                                                      39
Sea View Apartments, Karachi                                                                   39
Lakhani Fantasia, Scheme 33                                                                    38
Gulshan-e-Iqbal - Block 13/A, Gulshan-e-Iqbal                                                  38
Saddar, Saddar Town                                                                            38
Aman Golf View, Jinnah Avenue                                                                  38
Gulistan-e-Jauhar - Block 19, Gulistan-e-Jauhar                                                38
Clifton, Karachi                                                                               37
Gulshan-e-Iqbal - Block 2, Gulshan-e-Iqbal                                                     37
Falaknaz Harmony, Karachi                                                                      37
Sehar Commercial Area, DHA Phase 7                                                             36
Gulshan-e-Iqbal - Block 17, Gulshan-e-Iqbal                                                    36
Gulshan-e-Maymar - Sector Y, Gulshan-e-Maymar                                                  35
Ittehad Commercial Area, DHA Phase 6                                                           35
Mateen Complex, Bin Qasim Town                                                                 34
Federal B Area - Block 10, Federal B Area                                                      34
Bahria Town - Precinct 19, Bahria Town Karachi                                                 34
Navy Housing Scheme Karsaz, Karachi                                                            33
Gulshan-e-Iqbal - Block 7, Gulshan-e-Iqbal                                                     32
North Nazimabad - Block G, North Nazimabad                                                     32
Saima Royal Residency, Rashid Minhas Road                                                      32
Allahwala Town - Sector 31-B, Allahwala Town                                                   32
DHA Phase 7, DHA Defence                                                                       31
Karachi Administration Employees Society, Jamshed Town                                         31
Government Teacher Housing Society - Sector 16-A, Scheme 33 - Sector 16-A                      31
Garden East, Jamshed Town                                                                      30
Askari 4, Gulistan-e-Jauhar                                                                    30
Rahat Commercial Area, DHA Phase 6                                                             30
Gulistan-e-Jauhar - Block 10, Gulistan-e-Jauhar                                                30
KDA Scheme 1, Karachi                                                                          29
Gulshan-e-Iqbal - Block 11, Gulshan-e-Iqbal                                                    29
Gulshan-e-Iqbal - Block 13/C, Gulshan-e-Iqbal                                                  28
Gulshan-e-Iqbal - Block 13/D-3, Gulshan-e-Iqbal                                                28
Clifton - Block 7, Clifton                                                                     28
Pilibhit Cooperative Housing Society, Scheme 33 - Sector 18-A                                  28
Amil Colony, Karachi                                                                           28
Sawera Enclave, Suparco Road                                                                   27
Falaknaz Dynasty, Karachi                                                                      27
Grey Noor Tower & Shopping Mall, Scheme 33                                                     27
DHA Phase 7 Extension, DHA Defence                                                             27
Roomi Residency, Jinnah Avenue                                                                 27
Rafi Premier Residency, Scheme 33                                                              26
North Nazimabad, Karachi                                                                       26
Askari 5 - Sector F, Askari 5                                                                  26
Fatima Golf Residency, Gulistan-e-Jauhar                                                       25
Falaknaz Dreams, Malir                                                                         25
Gulshan-e-Iqbal Town, Karachi                                                                  25
Airport Road, Karachi                                                                          25
Noman Residencia, Scheme 33                                                                    25
The Court Regency, Dalmia Cement Factory Road                                                  25
North Nazimabad - Block A, North Nazimabad                                                     25
The Court Twin Towers, Callachi Cooperative Housing Society                                    24
Clifton - Block 5, Clifton                                                                     24
Saima Presidency, Malir Cantonment                                                             24
Gulistan-e-Jauhar - Block 11, Gulistan-e-Jauhar                                                24
Shamsi Society, Shah Faisal Town                                                               24
Surjani Town, Gadap Town                                                                       24
Sania Corner, Gulzar-e-Hijri                                                                   24
Gulshan-e-Iqbal - Block 13/B, Gulshan-e-Iqbal                                                  24
Allahwala Town, Korangi                                                                        24
Gulshan-e-Kaneez Fatima - Block 4, Gulshan-e-Kaneez Fatima                                     24
Gulshan-e-Maymar - Sector R, Gulshan-e-Maymar                                                  23
Tipu Sultan Road, Karachi                                                                      23
DHA Phase 4, DHA Defence                                                                       22
DHA Phase 1, DHA Defence                                                                       22
Gulshan-e-Iqbal - Block 16, Gulshan-e-Iqbal                                                    21
Gulistan-e-Jauhar - Block 2, Gulistan-e-Jauhar                                                 21
Parsi Colony, Jamshed Town                                                                     21
Gulistan-e-Jauhar - Block 20, Gulistan-e-Jauhar                                                20
North Town Residency, Surjani Town                                                             19
Federal Government Employees Housing Foundation, Scheme 33                                     19
Garden West, Karachi                                                                           19
Silk Garden, Surjani Town                                                                      19
Fatima Ali Towers, Gulzar-e-Hijri                                                              19
Bahria Town Karachi, Karachi                                                                   19
KN Gohar Green City, Karachi                                                                   18
Saima Arabian Villas, Gadap Town                                                               18
Gulshan-e-Kaneez Fatima, Scheme 33                                                             18
Safari Enclave Apartments, University Road                                                     17
Cosmopolitan Society, Karachi                                                                  17
PECHS Block 3, PECHS                                                                           17
City Tower And Shopping Mall, University Road                                                  17
Soldier Bazar, Jamshed Town                                                                    17
Pakistan Merchant Navy Society, Scheme 33 - Sector 15-A                                        16
Model Colony - Malir, Malir                                                                    16
Defence View Society, Karachi                                                                  16
Tauheed Commercial Area, DHA Phase 5                                                           15
Golden Town, Malir                                                                             15
Defence View Phase 1, Defence View Society                                                     15
Sector 25-A - Punjabi Saudagar Multi Purpose Society, Scheme 33 - Sector 25-A                  15
PECHS Block 6, PECHS                                                                           15
Malir Cantonment, Cantt                                                                        15
Alamgir Road, Gulshan-e-Iqbal Town                                                             14
Gwalior Cooperative Housing Society, Scheme 33                                                 14
Shadman Town - Sector-14/B, Shadman                                                            14
Quetta Town - Sector 18-A, Scheme 33 - Sector 18-A                                             14
Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33 - Sector 31                               14
PECHS, Jamshed Town                                                                            14
Sumaira Sky Tower, Gulzar-e-Hijri                                                              14
Shahra-e-Qaideen, Karachi                                                                      14
Askari 5 - Sector E, Askari 5                                                                  14
Kings Cottages, Gulistan-e-Jauhar - Block 7                                                    13
Gulshan-e-Iqbal - Block 14, Gulshan-e-Iqbal                                                    13
Gulistan-e-Jauhar - Block 1, Gulistan-e-Jauhar                                                 13
Gulshan-e-Iqbal - Block 13/D, Gulshan-e-Iqbal                                                  13
Muslimabad Society, Karachi                                                                    12
Shah Faisal Town, Karachi                                                                      12
Saddar Town, Karachi                                                                           12
Gulshan-e-Iqbal - Block 3, Gulshan-e-Iqbal                                                     12
Sanober Twin Tower, Saadi Road                                                                 12
Zamzama Commercial Area, DHA Phase 5                                                           12
Samrina Grand, Kathiawar Society                                                               12
Defence Skyline, Shaheed-e-Millat Expressway                                                   12
Malir, Karachi                                                                                 12
North Karachi - Sector 11A, North Karachi                                                      11
North Nazimabad - Block D, North Nazimabad                                                     11
Gulshan-e-Iqbal - Block 6, Gulshan-e-Iqbal                                                     11

In [35]:
df["address"] = df["address"].str.lower().str.strip()

In [36]:
df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
0,3 Bed Drawing Dining Flat Is For Sale,"tariq road, karachi",tariq road,65000000.0,1800.0,3,4,1,NaN,NaN,1,0,0,0,0,2023.0
1,3b-2 Bedrooms full sea facing of Panorama towe...,"emaar panorama, dha phase 8",dha defence,130000000.0,2700.0,3,4,2,NaN,45.0,2,4,1,1,0,2026.0
2,2000 Square Feet Spacious 3 Bedroom Apartment ...,"dha phase 6, dha defence",dha defence,55000000.0,1998.0,3,4,1,NaN,NaN,0,0,0,0,0,NaN
3,ULTRA-LUXURY COASTAL INVESTMENT: EXPANSIVE 3-B...,"emaar park edge, dha phase 8",dha defence,143500000.0,2700.0,3,3,1,NaN,NaN,0,1,0,0,1,NaN
4,Prime Location WEST OPEN CHANCE DEAL IDEAL FLO...,"askari 6, malir cantonment",cantt,39000000.0,2997.0,4,4,3,1.0,3.0,6,2,1,1,1,2026.0

In [37]:
#floor
df.loc[(df["floor"] > 40) | (df["completion_year"] > 2100),"completion_year"]=np.nan

In [38]:
df[df['floor'] > 35 ]

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
2084,Flat Of 1750 Square Feet Is Available For Sale...,"emaar crescent bay, dha phase 8",dha defence,84000000.0,1746.0,2,2,1,36.0,43.0,1,1,1,1,1,2031.0
2262,Luxurious Sea Facing 1 Bedroom Apartment With ...,"hmr waterfront, dha phase 8",dha defence,39000000.0,999.0,1,2,1,40.0,25.0,1,6,1,1,1,2022.0
2563,1Bedroom - AA Beachfront Luxury Apartments For...,"hmr waterfront, dha phase 8",dha defence,39900000.0,999.0,1,1,1,38.0,NaN,1,6,0,1,0,NaN
2875,Flat for sale,"dha phase 2 extension, dha defence",dha defence,24000000.0,1053.0,2,3,0,1234.0,4.0,1,1,0,0,0,NaN
6004,8-Month Plan Chance Deal | 2-Bed Type 2B-2 | T...,"emaar the views, dha phase 8",dha defence,82500000.0,1827.0,2,3,1,36.0,41.0,2,6,1,1,1,2026.0
7745,Prime Location 2100 Square Feet Spacious Flat ...,"burj-ul-harmain, university road",university road,25500000.0,2097.0,4,4,1,786.0,8.0,1,2,0,1,0,NaN
7925,2-Bed Luxury Apartment For Sale Park Edge By E...,"emaar park edge, dha phase 8",dha defence,78000000.0,1638.0,2,3,2,40.0,40.0,2,8,1,1,1,NaN
8488,Like New 2bed Dd Flat For Sale,"shaz residency, gulshan-e-iqbal town",gulshan-e-iqbal town,13000000.0,1017.0,2,2,1,12345.0,10.0,1,2,0,1,0,NaN
8489,Brand New Apartment For Sale,"burj-ul-harmain, university road",university road,13500000.0,1197.0,2,2,1,12345678.0,8.0,1,2,0,1,1,NaN
9388,Spacious 2 Bed DD Flat For Sale,"taloo gold residency, suparco road",suparco road,13000000.0,1224.0,2,2,1,123456789.0,13.0,1,4,6,1,1,NaN
10456,3 Bed Luxury Apartment For Booking For Sale,"al-murtaza commercial area, dha phase 8",dha defence,45000000.0,1674.0,3,4,1,1234.0,4.0,1,1,0,1,0,NaN
11110,Chance Deal Brand New Apartment For Sale,"burj-ul-harmain, university road",university road,18500000.0,1746.0,3,4,1,123456789.0,15.0,1,4,1,1,1,NaN

In [39]:
df.loc[(df["floor"] > 100) | (df["floor"] < 0),"floor"] = np.nan

In [40]:
df.loc[2262,'floor']=25
df.loc[2262,'total_floors']=40

In [41]:
df['floor'].value_counts()

floor
1.0     632
2.0     560
3.0     545
4.0     398
5.0     312
6.0     220
8.0     181
7.0     156
9.0     113
10.0    100
11.0     73
12.0     56
15.0     53
13.0     41
14.0     37
20.0     29
18.0     25
19.0     20
16.0     18
17.0     17
25.0     17
21.0     15
22.0     14
24.0     14
28.0     11
26.0     10
23.0      9
32.0      6
30.0      6
35.0      4
29.0      3
31.0      3
33.0      3
27.0      2
36.0      2
34.0      2
0.0       1
38.0      1
40.0      1
Name: count, dtype: int64

In [42]:
#total floor
df[df['total_floors'] > 50]

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
630,3 Bed DD Cottage Flat For Sale,"falaknaz harmony, karachi",falaknaz harmony,18500000.0,1701.0,3,4,1,8.0,92.0,1,1,1,1,1,2021.0
1470,"Pakistan Tallest Tower,Burj Qaid ,941feet High...","dha city - cbd commercial, dha city karachi",dha city karachi,17800000.0,657.0,1,1,1,NaN,82.0,2,8,1,1,1,NaN
1507,Luxurious 3 Bedrooms Apartment For Booking At ...,"hmr waterfront, dha phase 8",dha defence,89100000.0,2349.0,3,4,1,23.0,53.0,2,4,1,1,1,2030.0
1508,Luxurious Ultra Modern 3bedrooms Apartment On ...,"clifton - block 2, clifton",clifton,109600000.0,3213.0,3,4,1,16.0,52.0,2,4,1,1,1,2030.0
3022,Luxurious 2 Bedrooms Apartment On Booking In M...,"clifton - block 2, clifton",clifton,67000000.0,2160.0,2,3,1,21.0,52.0,2,5,1,1,1,2026.0
8384,Just Like New Apartment For Sale Nishat Comm...,"dha phase 6, dha defence",dha defence,29000000.0,1647.0,3,4,2,NaN,1234.0,1,0,2,1,1,2024.0
9415,Biggest Building Brand New Flat For Sale,"civil lines, karachi",civil lines,90000000.0,2799.0,3,4,1,NaN,52.0,2,3,1,1,0,2026.0
11736,Buy Your Ideal 1500 Square Feet Flat In A Prim...,"frere town, karachi",frere town,65000000.0,1503.0,3,3,0,NaN,2021.0,1,1,1,1,1,2021.0

In [43]:
df.loc[603, ["floor", "total_floors"]] = np.nan

In [44]:
#parking
df['parking'].value_counts()

parking
1       5634
0       3674
2       1560
3        307
4        273
5         84
10        26
6         21
8         20
100        9
9          6
7          6
22         5
50         5
500        5
15         4
18         4
11         4
180        3
30         3
400        3
120        2
350        2
88         2
250        2
56         1
300        1
130        1
3000       1
360        1
20         1
26         1
40         1
36         1
25         1
5000       1
60         1
160        1
63         1
Name: count, dtype: int64

In [45]:
df[(df['parking'] > 50)]

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year
169,3 BED LOUNGE 1250SQ FT ROAD FACING APARTMENT I...,"karachi university housing society, scheme 33",scheme 33,15000000.0,1251.0,3,3,1,9.0,16.0,180,6,0,1,0,2029.0
669,3 bed DD apartment for sale,"zamzama commercial area, dha phase 5",dha defence,30000000.0,1701.0,3,4,1,4.0,5.0,3000,0,1,1,0,NaN
708,Luxury 2 Bed DD Flat,"taloo gold residency, suparco road",suparco road,13000000.0,936.0,2,2,1,NaN,13.0,130,4,0,1,1,2021.0
1876,Otel Residency Apartments For Sale,"defence view phase 1, defence view society",defence view society,15000000.0,1044.0,2,2,1,28.0,7.0,360,1,1,1,1,2024.0
1877,Airport Residency Flat For Sale,"airport road, karachi",airport road,19500000.0,1404.0,2,3,1,13.0,3.0,300,5,1,1,1,2024.0
2324,Flat For Sale In Saim Square One,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",gulshan-e-iqbal town,36500000.0,1899.0,3,4,2,1.0,28.0,100,2,0,1,0,2016.0
2346,1600 Square Feet Flat In Only Rs. 33000000,"kings tower, gulistan-e-jauhar - block 15",gulistan-e-jauhar,33000000.0,1602.0,3,3,1,7.0,14.0,100,2,0,1,0,2023.0
2347,A 1800 Square Feet Flat Located In Bisma Green...,"bisma greens, gulistan-e-jauhar - block 15",gulistan-e-jauhar,37400000.0,1800.0,3,3,1,NaN,NaN,100,1,1,1,0,2025.0
2985,Brand New Flat For Sale,"gulistan-e-jauhar - block 16, gulistan-e-jauhar",gulistan-e-jauhar,32000000.0,1602.0,3,3,1,NaN,NaN,100,0,1,1,1,2023.0
3849,Clifton Flat For Sale,"clifton - block 1, clifton",clifton,22500000.0,1269.0,2,2,0,2.0,5.0,56,1,1,0,0,2025.0
5691,Get In Touch Now To Buy A Prime Location 1298 ...,"scheme 33, karachi",scheme 33,14500000.0,1296.0,3,3,0,NaN,4.0,120,1,0,1,0,2020.0
5726,1700 Square Feet Flat In Beautiful Location Of...,"dha phase 2 extension, dha defence",dha defence,33000000.0,1701.0,3,3,0,NaN,NaN,500,0,0,1,0,NaN
5808,Get Your Dream Prime Location Flat In Federal ...,"federal b area, karachi",federal b area,18000000.0,1116.0,2,2,2,NaN,4.0,120,1,1,1,1,2020.0
6210,Calachi Icon Apartments For Sale,"callachi cooperative housing society, gulshan-...",gulshan-e-iqbal town,36000000.0,2151.0,4,4,1,25.0,12.0,350,6,1,1,1,2023.0
6317,Corner Road Facing KINGS PALM RESIDENCY 6 Floo...,"gulistan-e-jauhar - block 3, gulistan-e-jauhar",gulistan-e-jauhar,22500000.0,1854.0,3,3,1,1.0,11.0,180,2,1,1,0,2018.0
8032,Prime Location Gulshan-e-Iqbal - Block 3 Flat ...,"gulshan-e-iqbal - block 3, gulshan-e-iqbal",gulshan-e-iqbal town,14000000.0,999.0,2,2,1,9.0,10.0,400,4,1,1,1,2022.0
8248,SAMSUM THE HILL VEIW LUXURY FLAT FOR SALE GULS...,"gulshan-e-iqbal - block 17, gulshan-e-iqbal",gulshan-e-iqbal town,80000000.0,1998.0,4,4,1,10.0,16.0,180,6,0,1,1,2029.0
8645,2 Bedrooms Flat For Booking in PECHS,"pechs block 2, pechs",jamshed town,32500000.0,1296.0,2,2,1,1.0,15.0,500,4,1,1,1,2026.0
8648,4 Bedrooms Flat For Booking in PECHS,"pechs block 2, pechs",jamshed town,65000000.0,2304.0,4,4,1,1.0,15.0,500,4,1,1,1,2026.0
9128,Prime Location 1950 Square Feet Flat Available...,"metropolis residency, jinnah avenue",jinnah avenue,31000000.0,1953.0,4,5,2,22.0,16.0,250,4,0,1,1,2025.0
9208,4 Bed DD 1st Floor Flat Is For Sale,"dhoraji colony, gulshan-e-iqbal town",gulshan-e-iqbal town,36000000.0,1503.0,4,4,2,NaN,4.0,100,1,1,1,1,2000.0
9908,Exclusive Luxury Apartments For Sale A New Sta...,"jinnah avenue, karachi",jinnah avenue,23000000.0,2403.0,4,4,1,4.0,10.0,5000,10,1,1,1,2020.0
10051,This Is Your Chance To Buy Flat In Gulshan-e-I...,"gulshan-e-iqbal - block 10-a, gulshan-e-iqbal",gulshan-e-iqbal town,13800000.0,1098.0,2,2,2,3.0,4.0,100,1,1,1,1,2024.0
10058,Safari Heights Flat For Sale,"gulistan-e-jauhar - block 15, gulistan-e-jauhar",gulistan-e-jauhar,24000000.0,1602.0,3,3,1,2.0,6.0,100,2,1,1,1,2000.0
10357,"Spacious 3 Bed DD Flat For Sale In Block 17, G...","gulistan-e-jauhar - block 17, gulistan-e-jauhar",gulistan-e-jauhar,17000000.0,1800.0,3,3,1,6.0,12.0,100,1,1,1,1,NaN
10468,"Luxury Apartment For Sale Askari V, Sector C ,...","askari 5 - sector c, askari 5",cantt,31500000.0,2601.0,3,4,0,NaN,3.0,60,1,0,1,0,2025.0
10632,Idyllic Prime Location Flat Available In North...,"north nazimabad - block h, north nazimabad",north nazimabad,34000000.0,1800.0,3,3,1,10.0,10.0,350,3,2,1,1,2025.0
11033,LEASED BANK LOAN APPLICABLE BRAND NEW FLAT ALS...,"gulzar-e-hijri, scheme 33",scheme 33,11500000.0,1152.0,2,2,1,NaN,4.0,400,1,1,1,1,2022.0
11065,LEASED BANK LOAN APPLICABLE BRAND NEW LUXURY F...,"shaz residency, gulshan-e-iqbal town",gulshan-e-iqbal town,12500000.0,1152.0,2,2,1,5.0,10.0,400,2,1,1,1,2022.0
11114,Flat For Sale AJWA PARK VIEW,"north nazimabad - block l, north nazimabad",north nazimabad,14000000.0,999.0,2,2,2,NaN,NaN,160,0,1,1,1,2027.0
11176,3 Bed DD Flat Sharfabad Prime Location For Sale,"sharfabad, gulshan-e-iqbal town",gulshan-e-iqbal town,25000000.0,1503.0,3,3,1,2.0,3.0,63,1,1,1,0,2000.0
11396,2 Bedrooms Flat For Booking in PECHS,"pechs block 2, pechs",jamshed town,32500000.0,1296.0,2,2,1,1.0,15.0,500,4,1,1,1,2026.0
11399,4 Bedrooms Flat For Booking in PECHS,"pechs block 2, pechs",jamshed town,65000000.0,2304.0,4,4,1,1.0,15.0,500,4,1,1,1,2026.0
11487,Brand new 2 Bedroom Drawing Room and Lounge on...,government teacher housing society - sector 16...,scheme 33,17400000.0,1053.0,2,2,1,NaN,NaN,88,2,1,1,1,NaN
11490,Brand New 2 Bedroom Drawing Room And Lounge On...,government teacher housing society - sector 16...,scheme 33,16700000.0,1053.0,2,2,1,NaN,NaN,88,2,1,1,0,2015.0
11529,2 Bed DD 1250 SQ FT 2nd Floor Apartment Availa...,"scheme 33, karachi",scheme 33,9900000.0,1251.0,2,2,1,22.0,16.0,250,4,1,1,1,2025.0
11734,Ideal Prime Location Flat Is Available For Sal...,"dhoraji colony, gulshan-e-iqbal town",gulshan-e-iqbal town,45000000.0,1998.0,4,4,2,NaN,4.0,100,1,1,1,1,2000.0

In [46]:
#furnished
df[df['furnished']==1]['price'].mean()

np.float64(37028650.05705591)

In [47]:
df[df['furnished']==0]['price'].mean()

np.float64(32865434.423676014)

In [48]:
#kitchen
df['kitchen'].value_counts()

kitchen
1     7779
0     2800
2      999
3       87
4        8
11       2
6        1
7        1
22       1
Name: count, dtype: int64

In [49]:
df.groupby("kitchen")["price"].agg(["count", "mean", "median"]).sort_index()

         count          mean      median
kitchen
0         2800  2.780552e+07  17500000.0
1         7779  3.647211e+07  26000000.0
2          999  4.139578e+07  27800000.0
3           87  2.870575e+07  18000000.0
4            8  2.239375e+07  21000000.0
6            1  1.750000e+07  17500000.0
7            1  2.500000e+06   2500000.0
11           2  2.465000e+07  24650000.0
22           1  2.050000e+07  20500000.0

In [50]:
df.loc[df["kitchen"] > 3, "kitchen"] = np.nan

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11678 entries, 0 to 11938
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       11678 non-null  object
 1   address             11678 non-null  object
 2   location            11678 non-null  object
 3   price               11678 non-null  float64
 4   area                11678 non-null  float64
 5   bedrooms            11678 non-null  int64
 6   bathrooms           11678 non-null  int64
 7   kitchen             11665 non-null  float64
 8   floor               3710 non-null   float64
 9   total_floors        5013 non-null   float64
 10  parking             11678 non-null  int64
 11  elevator            11678 non-null  int64
 12  servant_quarters    11678 non-null  int64
 13  electricity_backup  11678 non-null  int64
 14  furnished           11678 non-null  int64
 15  completion_year     6173 non-null   float64
dtypes: float64(6), int64(7), object(3)
memory usage: 1.8+ MB

In [52]:
df.to_csv('flats_cleaned.csv',index=False)